- src/gwc/src/main/java/org/geoserver/gwc/dispatch/GwcServiceDispatcherCallback.java
- src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
- src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
Follows up (and requires) https://github.com/GeoWebCache/geowebcache/pull/725
Added for early feedback, I think I still need to add a test for the backlinks to resources.
Surprisingly the exists tests did not fail despite the current user not being logged in as admin, but the same non authenticated requests would have failed in a running GeoServer with a 401.
> Follow up on GWC #724, fixes GEOS-8995, GEOS-8910

- src/main/src/main/java/org/geoserver/config/GeoServerDataDirectory.java
- src/main/src/main/java/org/geoserver/config/GeoServerResourcePersister.java
- src/main/src/test/java/org/geoserver/catalog/CatalogIntegrationTest.java
- src/main/src/test/resources/org/geoserver/catalog/se_relativepath.sld
- src/main/src/test/resources/org/geoserver/catalog/square16.svg
Depends on a couple of GeoTools fixes, hopefully they are already deployed
> [GEOS-9109] Styles referring to relative icons in subdirectories fail to change workspace

- src/web/core/src/main/java/org/geoserver/web/wicket/CodeMirrorEditor.js
- src/web/core/src/main/java/org/geoserver/web/wicket/js/codemirror/js/xml-hint.js
Follow-up to https://github.com/geoserver/geoserver/pull/3244
Disables automatic autocomplete on keyup - now Ctrl-Space is the only autocomplete method
> [GEOS-9018] Only use Ctrl-Space to trigger autocomplete

- src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
- src/main/src/main/java/org/geoserver/security/GeoServerSecurityFilterChainProxy.java
Issues addressed by this change:
* [GEOS-8913] Layer Preview URL contained a potentially malicious String
* [GEOS-8988] WMTS tile requests fail with 'RequestRejectedException: The request was rejected because the URL was not normalized'
* [GEOS-9054] Geoserver object names cannot contain special characters (dot,...) when the are used in URLs for the REST API.
I've tried to use a tamed down StrictHttpFirewall but there is no way to configure it so that it allows layer group usage in WMTS restful request (which ends up having a double slahs, as the style name is a empty string).
Verified it works manually, did not find a reasonable way to check it with an actual test (our mocks have no cooking management, security chain is not enabled, and the like).
Ah, this PR comes with a side issue that …
> Fix various issues related to URL checking

- src/web/core/src/main/java/org/geoserver/web/js/jquery.fullscreen.js
This issue cannot be unit tested, would be nice if someone could verify manually?
@tixvieira @ianturton or @tbarsballe would be good candidates as they were involved in the discussion
> [GEOS-9022] geoserver Style page, after expand button, html breaks

- src/release/jetty/start.ini
Reverts geoserver/geoserver#3331, I believe it's the cause of all the CITE test failures (the CITE machinery uses old ways of setting ports that apparently are not working anymore if the configuration contains the new property names)
> Revert "Update Jetty deprecated properties"

- src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorFilter.java
- src/extension/monitor/core/src/test/java/org/geoserver/monitor/MonitorFilterTest.java
This PR:
- Fix Authentication propagation between Monitor filter and its underlying PostProcessTask thread.
- For testing purposes adds an (optional-nullable) audit functional consumer to Monitor filter for having feedback of RequestData and Authentication variables from threadpool's background thread scope.
https://osgeo-org.atlassian.net/browse/GEOS-8762
> [GEOS-8762] Fix Monitor asynchronous post processing does not play well with security

- doc/en/user/source/data/raster/gdal.rst
- src/pom.xml
It's in particular interesting to check the native library installation section, which has been overhauled to use generally available GDAL binaries.
Given the amount of edits it's likely easier to review the final result:
https://github.com/geoserver/geoserver/blob/b7f01358b3c4d6106ead57c622d6f2a60dc41a5d/doc/en/user/source/data/raster/gdal.rst
> [GEOS-9136] Upgrade GDAL dependencies to 2.x

- src/wms/src/main/resources/org/geoserver/wms/map/OpenLayers3MapTemplate.ftl
"neu" is not a "new" misnomer, it's really "north east up", so it should be used only for flipped CRSes
> [GEOS-8754] OpenLayers 3 preview fails to display projected maps in WMS 1.3

- src/wcs1_0/src/main/java/org/geoserver/wcs/DefaultWebCoverageService100.java
- src/wcs1_0/src/test/java/org/geoserver/wcs/GetCoverageTest.java
See https://osgeo-org.atlassian.net/browse/GEOS-9148
> [GEOS-9148] Fixed NPE for WCS 1.0.0 GetCoverage requests that don't intersect the coverage bounding box.

- src/wcs1_0/src/main/java/org/geoserver/wcs/DefaultWebCoverageService100.java
- src/wcs1_0/src/test/java/org/geoserver/wcs/GetCoverageTest.java
2.15.x backport for https://github.com/geoserver/geoserver/pull/3397
> [GEOS-9148][2.15.x] Fixed NPE for WCS 1.0.0 GetCoverage requests that don't intersect the coverage bounding box.

- src/wcs1_0/src/main/java/org/geoserver/wcs/DefaultWebCoverageService100.java
- src/wcs1_0/src/test/java/org/geoserver/wcs/GetCoverageTest.java
2.14.x backport for https://github.com/geoserver/geoserver/pull/3397
> [GEOS-9148][2.14.x] Fixed NPE for WCS 1.0.0 GetCoverage requests that don't intersect the coverage bounding box.

- src/extension/wcs2_0-eo/core/src/main/java/org/geoserver/wcs2_0/eo/response/DescribeEOCoverageSetTransformer.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/GMLTransformer.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCS20DescribeCoverageTransformer.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCS20GetCapabilitiesTransformer.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/DescribeCoverageTest.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/GetCapabilitiesTest.java
See https://osgeo-org.atlassian.net/browse/GEOS-9142
I am not familiar with the EO module but the sample DescribeEOCoverageSet responses in the module actually include the xmlns:ows namespace even though GeoServer wasn't writing it to its responses.
> [GEOS-9142] Added missing metadata to WCS 2.0.1 GetCapabilities and DescribeCoverage.

- src/wcs1_0/src/main/java/applicationContext.xml
- src/wcs1_0/src/main/java/org/geoserver/wcs/DefaultWebCoverageService100.java
- src/wcs1_0/src/main/java/org/geoserver/wcs/kvp/ElevationKvpParser.java
- src/wcs1_0/src/main/java/org/geoserver/wcs/kvp/Wcs10GetCoverageRequestReader.java
- src/wcs1_0/src/test/java/org/geoserver/wcs/CustomDimensionsTest.java
- src/wcs1_0/src/test/java/org/geoserver/wcs/DynamicDimensionsTest.java
- src/wcs1_0/src/test/java/org/geoserver/wcs/GetCoverageTest.java
See https://osgeo-org.atlassian.net/browse/GEOS-6977
Incorrect parsing of elevation ranges that did not allow decimal numbers was also fixed and some duplicate/unnecessary elevation parsing that had the same incorrect elevation range parsing was removed.
> [GEOS-6977] Fixed WCS 1.0.0 GetCoverage KVP ignoring elevation and custom dimension parameters.

- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/GMLTransformer.java
- src/wcs2_0/src/main/resources/schemas/wcs/2.0/wcsgs.xsd
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/DescribeCoverageTest.java
See https://osgeo-org.atlassian.net/browse/GEOS-9141
This pull request combines the following changes:
1. Changes "gml:EnvelopeWithTimePeriod" to "gml:Envelope" for coverages with an elevation dimension and no time dimension.
1. Ensures unique "gml:id" attributes for custom temporal dimensions.
1. Adds "ElevationDomain" and "DimensionDomain" to wcsgs.xsd.
No new unit tests were added but schema validation was added to all of the DescribeCoverage unit tests for elevation and custom dimensions.
> [GEOS-9141] Fixed invalid WCS 2.0.1 DescribeCoverage with elevation and custom dimensions.

- src/web/core/src/main/java/org/geoserver/web/data/store/DefaultDataStoreEditPanel.java
- src/web/core/src/test/java/org/geoserver/web/data/store/URLModelTest.java
Added support for https:// on default datastore edit panel, and added tests for URLModel class use cases.
https://osgeo-org.atlassian.net/browse/GEOS-9163
> [GEOS-9163] Added 'https://' protocol support for default Data Store Edit Panel and URLModel class

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/GeoJsonOutputFormatWfsTest.java
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/Gsml32Borehole.properties
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/Gsml32Borehole.xml
- src/wfs/src/main/java/org/geoserver/wfs/json/ComplexGeoJsonWriter.java
- src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONBuilder.java
Comes with a fix for "[GEOS-9160] JSON encoding of 1-d linear geometries fails" as I could not get the date test running otherwise.
> [GEOS-9161] Complex attributes with date simple content are not encoed properly by the ComplexJSONBuilder

- src/wcs1_0/src/main/java/applicationContext.xml
- src/wcs1_0/src/main/java/org/geoserver/wcs/DefaultWebCoverageService100.java
- src/wcs1_0/src/main/java/org/geoserver/wcs/kvp/ElevationKvpParser.java
- src/wcs1_0/src/main/java/org/geoserver/wcs/kvp/Wcs10GetCoverageRequestReader.java
- src/wcs1_0/src/test/java/org/geoserver/wcs/CustomDimensionsTest.java
- src/wcs1_0/src/test/java/org/geoserver/wcs/DynamicDimensionsTest.java
- src/wcs1_0/src/test/java/org/geoserver/wcs/GetCoverageTest.java
2.15.x backport for https://github.com/geoserver/geoserver/pull/3389
> [GEOS-6977][2.15.x] Fixed WCS 1.0.0 GetCoverage KVP ignoring elevation and custom dimension parameters.

- src/extension/wcs2_0-eo/core/src/main/java/org/geoserver/wcs2_0/eo/response/DescribeEOCoverageSetTransformer.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/GMLTransformer.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCS20DescribeCoverageTransformer.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCS20GetCapabilitiesTransformer.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/DescribeCoverageTest.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/GetCapabilitiesTest.java
2.15.x backport for https://github.com/geoserver/geoserver/pull/3395
> [GEOS-9142][2.15.x] Added missing metadata to WCS 2.0.1 GetCapabilities and DescribeCoverage.

- src/extension/wcs2_0-eo/core/src/main/java/org/geoserver/wcs2_0/eo/response/DescribeEOCoverageSetTransformer.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/GMLTransformer.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCS20DescribeCoverageTransformer.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCS20GetCapabilitiesTransformer.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/DescribeCoverageTest.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/GetCapabilitiesTest.java
2.14.x backport for https://github.com/geoserver/geoserver/pull/3395
> [GEOS-9142][2.14.x] Added missing metadata to WCS 2.0.1 GetCapabilities and DescribeCoverage.

- src/wcs1_0/src/main/java/applicationContext.xml
- src/wcs1_0/src/main/java/org/geoserver/wcs/DefaultWebCoverageService100.java
- src/wcs1_0/src/main/java/org/geoserver/wcs/kvp/ElevationKvpParser.java
- src/wcs1_0/src/main/java/org/geoserver/wcs/kvp/Wcs10GetCoverageRequestReader.java
- src/wcs1_0/src/test/java/org/geoserver/wcs/CustomDimensionsTest.java
- src/wcs1_0/src/test/java/org/geoserver/wcs/DynamicDimensionsTest.java
- src/wcs1_0/src/test/java/org/geoserver/wcs/GetCoverageTest.java
2.14.x backport for https://github.com/geoserver/geoserver/pull/3389
> [GEOS-6977][2.14.x] Fixed WCS 1.0.0 GetCoverage KVP ignoring elevation and custom dimension parameters.

- src/web/core/src/main/java/org/geoserver/web/data/store/DefaultDataStoreEditPanel.java
- src/web/core/src/test/java/org/geoserver/web/data/store/URLModelTest.java
Added support for https:// on default datastore edit panel, and added tests for URLModel class use cases.
https://osgeo-org.atlassian.net/browse/GEOS-9163
> [GEOS-9163] Added 'https://' protocol support for default Data Store Edit Panel and URLModel class (2.15.x.backport)

- doc/en/user/source/data/app-schema/app-schema-resolution.rst
Adds a warning about schema.cache.dir system property requirement for remote URL mapping file to user manual.
> Add schema.cache.dir system property usage to user manual

- doc/en/developer/source/eclipse-guide/index.rst
Add modified google-java-format version jar download with 4 spaces indent on developer documentation.
> Add to developer manual a modified google-java-format version plugin option.

- src/main/src/main/resources/schemas/sld/StyledLayerDescriptor.xsd
- src/main/src/test/java/org/vfny/geoserver/util/SLDValidatorTest.java
- src/main/src/test/java/org/vfny/geoserver/util/validi18n.sld
Fix Geoserver New Style page validation throwing an error when using Localized tags in Title.
- Internal validation schema updated.
- Added a test using a new SLD file using Localized tags inside Title tag.
See:
https://osgeo-org.atlassian.net/browse/GEOS-9132
> [GEOS-9132] Style Validation fix for i18N.

- src/web/core/src/main/java/org/geoserver/web/data/store/DefaultDataStoreEditPanel.java
- src/web/core/src/test/java/org/geoserver/web/data/store/URLModelTest.java
Added support for https:// on default datastore edit panel, and added tests for URLModel class use cases.
https://osgeo-org.atlassian.net/browse/GEOS-9163
> [GEOS-9163] Added 'https://' protocol support for default Data Store Edit Panel and URLModel class (2.14.x.backport)

- doc/en/user/source/data/app-schema/app-schema-resolution.rst
Adds a warning about schema.cache.dir system property requirement for remote URL mapping file to user manual.
> Add schema.cache.dir system property usage to user manual (2.15.x backport)

- doc/en/user/source/data/app-schema/app-schema-resolution.rst
Adds a warning about schema.cache.dir system property requirement for remote URL mapping file to user manual.
> Add schema.cache.dir system property usage to user manual (2.14.x backport)

- src/web/app/pom.xml
PR covers two changes:
See [GEOS-9187](https://osgeo-org.atlassian.net/browse/GEOS-9187) for details.
> Fix web-app jetty:run configuration to allow running from jar packaging [GEOS-9187]

- src/release/installer/win/wrapper.conf
- src/release/wrapper/bin/wrapper/wrapper.conf
Use of a relative path for java tmp folder throws off zip-slip checks
> windows service fix

- src/gwc/src/main/java/org/geoserver/gwc/layer/DefaultTileLayerCatalog.java
- src/gwc/src/test/java/org/geoserver/gwc/layer/DefaultTileLayerCatalogTest.java
DefaultTileLayerCatalog listens to Resouce events under
the data directory's gwc-layers folder resource in order to
notify its local instance listeners of tile layer configuration
changes even when on a shared directory by several service
instances.
To do so, it was using both a "folder" listener on gwc-layers,
and one listener per tile layer info resource (i.e. gwc-layers/*.xml).
This resulted in a severe startup hit when there are several
tile layers.
This patch uses a single listener on the gwc-cache folder resource
to handle all the scenarios, and hence removes the need to set up
and cache one resource listener per tile layer.
> Fix gwc tile layer load performance regression at startup

- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/ScalingPolicy.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/ScaleKvpTest.java
No new tests because it fixes a build failure that would occur merging https://github.com/geotools/geotools/pull/2354
Basically the GeoTools change triggers a but in GeoServer which then fails the build in the WCS 2.0 module, unless this PR gets applied.
> [GEOS-9153] WCS 2.0 scaling policies do not account for scaling factor already applied during read (due to subsampling and overview)

- src/community/solr/src/main/java/applicationContext.xml
- src/community/solr/src/main/java/org/geoserver/solr/SolrFeatureTypeCallback.java
This PR provides a fix for [GEOS-9183] Unresolvable Spring circular reference on Solr module.
Since this bug can be reproduced only on Apache Tomcat 7 runtime environment and only dependency injection init method refactoring is involved, no integration test was added.
Tested on Apache Tomcat 7.0.93.
https://osgeo-org.atlassian.net/browse/GEOS-9183
> [GEOS-9183] Fix for Solr circular Spring Bean reference exception

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SortByTest.java
Executing a WFS query with nested filter and multiple sortBy expressions throws an malformed SQL exception on App-schema and Postgresql.
This PR tests fix for SQL nested filter building on multiple sortBy expressions did on [GEOT-6252]
https://osgeo-org.atlassian.net/browse/GEOT-6252
https://osgeo-org.atlassian.net/browse/GEOS-9131
https://github.com/geotools/geotools/pull/2277
> [GEOS-9131] App-schema multiple sortBy support on SQL testing

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SortByTest.java
Executing a WFS query with nested filter and multiple sortBy expressions throws an malformed SQL exception on App-schema and Postgresql.
This PR tests fix for SQL nested filter building on multiple sortBy expressions did on [GEOT-6252]
https://osgeo-org.atlassian.net/browse/GEOT-6252
https://osgeo-org.atlassian.net/browse/GEOS-9131
https://github.com/geotools/geotools/pull/2357
> [GEOS-9131] App-schema multiple sortBy support on SQL testing (2.14.x backport)

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SortByTest.java
Executing a WFS query with nested filter and multiple sortBy expressions throws an malformed SQL exception on App-schema and Postgresql.
This PR tests fix for SQL nested filter building on multiple sortBy expressions did on [GEOT-6252]
https://osgeo-org.atlassian.net/browse/GEOT-6252
https://osgeo-org.atlassian.net/browse/GEOS-9131
https://github.com/geotools/geotools/pull/2355
> [GEOS-9131] App-schema multiple sortBy support on SQL testing (2.15.x backport)

- src/wms/src/main/java/org/geoserver/wms/WMSServiceExceptionHandler.java
- src/wms/src/test/java/org/geoserver/wms/WMSServiceExceptionTest.java
This pull request is to XML encode the service exception code before writing it into the WMS service exception report.
> Encode the code attribute in WMS service exception reports.

- src/wms/src/main/java/org/geoserver/wms/WMSServiceExceptionHandler.java
- src/wms/src/test/java/org/geoserver/wms/WMSServiceExceptionTest.java
2.15.x backport for https://github.com/geoserver/geoserver/pull/3488
> [2.15.x] Encode the code attribute in WMS service exception reports.

- src/wms/src/main/java/org/geoserver/wms/WMSServiceExceptionHandler.java
- src/wms/src/test/java/org/geoserver/wms/WMSServiceExceptionTest.java
2.14.x backport for https://github.com/geoserver/geoserver/pull/3488
> [2.14.x] Encode the code attribute in WMS service exception reports.

- src/main/src/main/java/org/geoserver/catalog/StyleInfo.java
- src/main/src/main/java/org/geoserver/catalog/impl/StyleInfoImpl.java
- src/main/src/test/java/org/geoserver/catalog/CatalogIntegrationTest.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/StyleControllerTest.java
This PR enhances StyleInfo and StyleInfoImpl Catalog objects adding a MetadataMap attribute for being serialized by Xstream.
Also adds Rest integration tests on Restconfig module.
2.15.x backport.
https://osgeo-org.atlassian.net/browse/GEOS-9209
> [GEOS-9209] Enhance StyleInfo with MetadataMap on Catalog object and Rest entpoint (2.15.x.backport).

- src/community/mapml/src/main/java/org/geoserver/mapml/MapMLGenerator.java
- src/community/mapml/src/main/java/org/geoserver/mapml/xml/Feature.java
I noticed that when I used the MapML client to query example layers like "A sample ArcGrid file" or "North America sample imagery" in the default Preview Layers, that a null pointer exception occurred.  There are no tests for this module (yet).  The checkstyle build profile reports a bunch of failures because _generated_ files (mostly) don't have a license header.  Not sure what to do there (I didn't commit them).  No Jira for this,  I will do that after submitting.  Hopefully have not missed anything. LMK. Attn: @cmhodgson 
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of …
> Fix MapML community module NPE when querying images returning no geometry

- src/community/security/oauth2-core/pom.xml
- src/community/security/oauth2-geonode/pom.xml
- src/community/security/oauth2-github/pom.xml
- src/community/security/oauth2-google/pom.xml
- src/community/security/oauth2-openid-connect/pom.xml
Upgrades the Spring Security OAuth2 version to release 2.0.16, fixing several critical vulnerabilities.
> [Closes JIRA GEOS-9220] Upgrade spring-security-oauth2 version from 2.0.11 to 2.0.16

- src/pom.xml
The main goal of this pull request is to back port the upgrade of Spring Security 5.1.1 to 5.1.5 which was done on the master branch. 
> [GEOS-9221] Upgrade spring security to 5.1.5 (backport to 2.15.x)

- src/community/security/oauth2-core/pom.xml
- src/community/security/oauth2-geonode/pom.xml
- src/community/security/oauth2-github/pom.xml
- src/community/security/oauth2-google/pom.xml
- src/community/security/oauth2-openid-connect/pom.xml
Backports to 2.15.x fix for JIRA GEOS-9220: "Upgrade spring-security-oauth2 version from 2.0.11 to 2.0.16"
> [Backports JIRA GEOS-9220] Upgrade spring-security-oauth2 version from 2.0.11 to 2.0.16

- src/community/params-extractor/pom.xml
- src/community/params-extractor/src/main/java/org/geoserver/params/extractor/RequestWrapper.java
- src/community/params-extractor/src/test/java/org/geoserver/params/extractor/RequestWrapperTest.java
is usedIf the Parameter Extraction plugin and the Monitor Plugin are installed, every request that is rewritten by the Parameter Extraction plugin is not logged in the Monitoring Plugin audit files.
This PR fix RequestWrapper class and its path extract methods, so Monitor module can read its paths properly.
2.14.x backport.
See:
https://osgeo-org.atlassian.net/browse/GEOS-9218
> [GEOS-9218] Parameter Extractor plugin prevents the Monitor plugin to log requests (2.14.x. backport)

- src/community/params-extractor/src/main/java/org/geoserver/params/extractor/RequestWrapper.java
- src/community/params-extractor/src/test/java/org/geoserver/params/extractor/RequestWrapperTest.java
If the Parameter Extraction plugin and the Monitor Plugin are installed, every request that is rewritten by the Parameter Extraction plugin is not logged in the Monitoring Plugin audit files.
This PR fix RequestWrapper class and its path extract methods, so Monitor module can read its paths properly.
See:
https://osgeo-org.atlassian.net/browse/GEOS-9218
> [GEOS-9218] Parameter Extractor plugin prevents the Monitor plugin to log requests

- src/community/params-extractor/src/main/java/org/geoserver/params/extractor/RequestWrapper.java
- src/community/params-extractor/src/test/java/org/geoserver/params/extractor/RequestWrapperTest.java
If the Parameter Extraction plugin and the Monitor Plugin are installed, every request that is rewritten by the Parameter Extraction plugin is not logged in the Monitoring Plugin audit files.
This PR fix RequestWrapper class and its path extract methods, so Monitor module can read its paths properly.
2.15.x backport.
See:
https://osgeo-org.atlassian.net/browse/GEOS-9218
> [GEOS-9218] Parameter Extractor plugin prevents the Monitor plugin to log requests (2.15.x. backport)

- src/community/params-extractor/pom.xml
- src/community/params-extractor/src/main/java/org/geoserver/params/extractor/RequestWrapper.java
- src/community/params-extractor/src/test/java/org/geoserver/params/extractor/RequestWrapperTest.java
Parameter Extractor plugin prevents the Monitor plugin to log requests.
If the Parameter Extraction plugin and the Monitor Plugin are installed, every request that is rewritten by the Parameter Extraction plugin is not logged in the Monitoring Plugin audit files.
This PR fixes RequestWrapper class and its path extract methods, so Monitor module can read its paths properly.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9218
> [GEOS-9218] Parameter Extractor plugin prevents the Monitor plugin to log requests (2.14.x backport)

- src/main/src/test/java/org/geoserver/data/test/SystemTestData.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/FeatureTypeController.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/FeatureTypeControllerTest.java
Fix https://osgeo-org.atlassian.net/browse/GEOS-9217
Copy of PR https://github.com/geoserver/geoserver/pull/3509 for branch 2.15.x
> No feature type for workspace with multiple datastore

- src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
- src/main/src/main/java/org/geoserver/security/password/ConfigurationPasswordEncryptionHelper.java
ConfigurationPasswordEncryptionHelper.decode(String)
is called by XstreamPersister -> StoreInfoConverter
for each DataStoreInfo read from the data directory at
start up time.
This patch makes it use a ConcurrentMap internally
instead of a HashMap, and removes the sychronization
on its CACHE member variable. Additionally, and most
importantly, caches the encryptable store parameter
names by StoreInfo.getType() too, avoiding the fallback
to full DataAccessFactory parameter lookup, which
implies a rather expensive call to getCatalog() \
.getResourcePool().getDataStoreFactory((DataStoreInfo) info)
As a result, loading time when there are lots of
DataStoreInfos is reduced to about 1/3 of the time
it takes without this patch.
> Speed up data_dir load when there are lots of DataStoreInfos

- src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
- src/main/src/main/java/org/geoserver/security/password/ConfigurationPasswordEncryptionHelper.java
Backport of #3450 onto 2.15.x
ConfigurationPasswordEncryptionHelper.decode(String)
is called by XstreamPersister -> StoreInfoConverter
for each DataStoreInfo read from the data directory at
start up time.
This patch makes it use a ConcurrentMap internally
instead of a HashMap, and removes the sychronization
on its CACHE member variable. Additionally, and most
importantly, caches the encryptable store parameter
names by StoreInfo.getType() too, avoiding the fallback
to full DataAccessFactory parameter lookup, which
implies a rather expensive call to getCatalog() \
.getResourcePool().getDataStoreFactory((DataStoreInfo) info)
As a result, loading time when there are lots of
DataStoreInfos is reduced to about 1/3 of the time
it takes without this patch.
> [GEOS-9231] Speed up data_dir load when there are lots of DataStoreInfos

- src/gwc/src/main/java/org/geoserver/gwc/layer/DefaultTileLayerCatalog.java
- src/gwc/src/test/java/org/geoserver/gwc/layer/DefaultTileLayerCatalogTest.java
Backport #3451 to 2.15.x
DefaultTileLayerCatalog listens to Resouce events under
the data directory's gwc-layers folder resource in order to
notify its local instance listeners of tile layer configuration
changes even when on a shared directory by several service
instances.
To do so, it was using both a "folder" listener on gwc-layers,
and one listener per tile layer info resource (i.e. gwc-layers/*.xml).
This resulted in a severe startup hit when there are several
tile layers.
This patch uses a single listener on the gwc-cache folder resource
to handle all the scenarios, and hence removes the need to set up
and cache one resource listener per tile layer.
> [GEOS-9219] backport fix gwc tile layer load performance regression at startup

- src/gwc/src/main/java/org/geoserver/gwc/seed/SeederThreadLocalTransferExecutor.java
- src/gwc/src/main/resources/geowebcache-core-context.xml
- src/gwc/src/test/java/org/geoserver/gwc/GWCSeedingSecurityIntegrationTest.java
PR for https://osgeo-org.atlassian.net/browse/GEOS-8752
This basically just makes the embedded GWC use a thread pool that can transfer thread locals, same as the one used for the GeoServer renderer. GWC's config was modular enough that this was relatively easy to drop in place of the old one.
(Now that Planet Federal has a signed CLA again, I've got a bit of a backlog of bugfixes I'm contributing. Obviously, merging them is going to have to wait until the build server is working again)
> [GEOS-8752] Allow integrated GWC to seed secured layers

- src/gwc/src/test/java/org/geoserver/gwc/RESTIntegrationTest.java
After some recent changes on master (I'm not sure exactly which one, but I'm guessing the depreciation removal PR), the GWC RESTIntegrationTest is failing.
Looking into the failures, it appears they are only affecting tests that were modified to work around some changes introduced by the Spring MVC REST update a couple years ago (see: https://github.com/geoserver/geoserver/commit/a354c9dd5177c0a739efcfc40bece4ece5b7afd2 ).
After restoring the tests to their original state (or something close to it) everything seems to be passing again.
> Fix GWC RESTIntegration test to work after recent Spring MVC fix

- src/restconfig/src/test/java/org/geoserver/rest/resources/ResourceControllerTest.java
Looking to fix a charset dependent test
> Use Charset.defaultCharset() to test resource operations

- src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
Follows up with https://github.com/geotools/geotools/pull/2409 and restores the build (changes in GT caused one test failure in web/core due to an unexpected new read parameter in mosaic)
> Follow up on scale/offset imageio-ext and gt support

- src/extension/geofence/src/main/java/org/geoserver/geofence/rest/xml/JaxbRule.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/rest/JaxbRuleTest.java
> [GEOS-9245] GeoFence rule update fails with NPE on an empty area

- src/gwc/src/test/java/org/geoserver/gwc/RESTIntegrationTest.java
Backport of https://github.com/geoserver/geoserver/pull/3545 to fix [recent 2.15.x failures](https://build.geoserver.org/view/geoserver/job/geoserver-2.15.x/448) in Jenkins
> Fix GWC RESTIntegration test to work after recent Spring MVC fix (2.15.x backport)

- src/gwc/src/test/java/org/geoserver/gwc/RESTIntegrationTest.java
Backport of #3545 to fix [recent 2.14.x failures](https://build.geoserver.org/view/geoserver/job/geoserver-2.14.x/587/console) in Jenkins
> Fix GWC RESTIntegration test to work after recent Spring MVC fix (2.14.x backport)

- src/extension/app-schema/app-schema-mongo-test/src/test/java/org/geoserver/test/onlineTest/ComplexMongoDBSupport.java
- src/extension/app-schema/app-schema-mongo-test/src/test/java/org/geoserver/test/onlineTest/ComplexMongoDBTest.java
- src/extension/app-schema/app-schema-mongo-test/src/test/resources/data/stations1.json
- src/extension/app-schema/app-schema-mongo-test/src/test/resources/mappings/stations.xml
- src/extension/app-schema/app-schema-mongo-test/src/test/resources/schemas/stations.xsd
This PR adds testing for PropertyIsNull filter on App-Schema MongoDB test module.
Requires merged:
https://github.com/geotools/geotools/pull/2426
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-9240
> [GEOS-9240] Add App-Schema MongoDb PropertyIsNull filter testing.

- .gitignore
- build/build_release.sh
- build/publish_release.sh
- doc/en/developer/source/release-guide/index.rst
This prevents gitignore from conflicting with src/release folder.
> Change staging directory from release to distribution

- src/community/params-extractor/src/main/java/org/geoserver/params/extractor/UrlMangler.java
- src/community/params-extractor/src/test/java/org/geoserver/params/extractor/TestSupport.java
- src/community/params-extractor/src/test/java/org/geoserver/params/extractor/UrlManglerTest.java
…
Fixed conflict between params-extractor and monitor plugins, corectly unwrapping request wrapper added by monitor
> [GEOS-9256]: fixed conflict between params-extractor and monitor plugins, corectly unwrapping request wrapper added by monitor

- doc/en/user/source/extensions/vectortiles/install.rst
- doc/en/user/source/extensions/vectortiles/tutorial.rst
- doc/en/user/source/styling/mbstyle/reference/spec.rst
- doc/en/user/source/styling/mbstyle/source.rst
- doc/en/user/source/styling/workshop/mbstyle/mbstyle.rst
The code was modified in https://github.com/geoserver/geoserver/commit/62d6887dba4ab115e690139c56a182c9ee58002d
This just modifies docs / examples to match.
> docs: Update user manual to reflect modified mapbox vector tiles MIME type

- src/community/ogcapi/src/main/java/org/geoserver/api/features/CollectionDocument.java
- src/community/ogcapi/src/main/resources/org/geoserver/api/features/collection.ftl
- src/community/ogcapi/src/main/resources/org/geoserver/api/features/collection_include.ftl
- src/community/ogcapi/src/main/resources/org/geoserver/api/features/collections.ftl
- src/community/ogcapi/src/test/java/org/geoserver/api/features/CollectionTest.java
This was changed in the WFS 3 spec in https://github.com/opengeospatial/WFS_FES/commit/a9be3db1b63d7947c74dd0b276cfc97374e9c0a6
*(Not required, existing unit tests have been updated)*
*(Not applicable)*
> [GEOS-9261] Update name to id in OGC API Collection

- src/community/ogcapi/src/main/java/org/geoserver/api/features/LandingPageDocument.java
- src/community/ogcapi/src/test/java/org/geoserver/api/features/LandingPageTest.java
This was added to the spec at https://github.com/opengeospatial/WFS_FES/commit/5b450ef18404d4a4fdb443f6444142c89ed4445f
*Not applicable*
> [GEOS-9262] Update ogcapi module to return title and description in landing page

- src/main/src/main/java/org/geoserver/security/filter/GeoServerUserNamePasswordAuthenticationFilter.java
- src/web/core/src/test/java/org/geoserver/web/GeoServerSecuredPageTest.java
This pull request sets an appropriate Spring Security authentication strategy to ensure that the session token is updated after successful username/password authentication.
https://osgeo-org.atlassian.net/browse/GEOS-9260
> [GEOS-9260] Update the session token after a successful login.

- src/web/wms/src/main/java/org/geoserver/wms/web/data/AbstractStylePage.java
- src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java
Fixes the extension point enabling others to provide custom tabs to the style editor. JIRA Ticket: https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-9263
> [GEOS-9263] Style editor extension point not working

- doc/en/user/source/services/wfs/reference.rst
Updated WFS GetFeature using bbox description and example to include the optional ``[CRS]`` parameter value for cases where the bbox is in a different coordinate system to the featureTypes native coordinate system.
Modified description text to indicate that ``srsName=CRS`` parameter specifies the resulting output features CRS, and not the CRS of the bbox.
- [N/A] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation) …
> Updated WFS GetFeature using bbox text & example

- src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
This one is not really possible to test because you need a clustered set-up with hazelcast.
However, it is a minimal and trivial change, that does not break any tests and can be easily understood to improve cluster-safety.
> GEOS-9169 ResourcePool datastore cache cluster-safe

- src/wfs/src/main/java/org/geoserver/wfs/json/ComplexGeoJsonWriter.java
- src/wfs/src/test/java/org/geoserver/wfs/json/ComplexGeoJsonWriterTest.java
GeoJSON output request Geoserver throws a NullPointerException on WFS ComplexGeoJsonWriter class -> checkIfFeatureIsLinked method, due to null userData object (attributes parameter) in properties not being null safe checked before using its methods.
This PR adds null-safe checks fixing the issue.
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-9271
Submitting the PR …
> [GEOS-9271] NullPointerException on WFS ComplexGeoJsonWriter Link check

- src/main/src/main/java/org/geoserver/config/default_line.sld
- src/main/src/main/java/org/geoserver/config/default_point.sld
- src/main/src/main/java/org/geoserver/config/default_polygon.sld
The default geoserver sld styles contained the wrong abstract for the styles, so I changed the abstract.
> Default SLD abstracts updated to fit the style

- src/pom.xml
This is a test of appveyor and travis
- [x ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
> Upgrade surefire plugin to 2.22 so jacoco profile will execute correctly

- src/web/core/src/main/java/org/geoserver/web/wicket/FileExistsValidator.java
- src/web/core/src/main/resources/GeoServerApplication.properties
- src/web/core/src/test/java/org/geoserver/web/wicket/FileExistsValidatorTest.java
- src/web/wms/src/main/java/org/geoserver/wms/web/WMSAdminPage.java
In WMS configuration page (main or workspace) the watermark file input allows to validate a remote http url making a request on it to check if exists.  This PR makes Watermark input detects introduced text is not a file url and don't make any tcp/ip connection to reach the resource.
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-9276
Submitting the PR does not …
> [GEOS-9276] WMS configuration UI, watermark file input allows to validate a remote HTTP URL

- src/extension/geofence/pom.xml
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/AccessManagerWMTSLayerTest.java
- src/main/pom.xml
- src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
- src/main/src/main/java/org/geoserver/catalog/WMTSLayerInfo.java
- src/main/src/main/java/org/geoserver/catalog/impl/WMTSLayerInfoImpl.java
- src/main/src/main/java/org/geoserver/security/decorators/DecoratingWMTSLayerInfo.java
- src/main/src/main/java/org/geoserver/security/decorators/SecuredWMTSLayer.java
- src/main/src/main/java/org/geoserver/security/decorators/SecuredWMTSLayerInfo.java
- src/main/src/main/java/org/geoserver/security/decorators/SecuredWebMapTileServer.java
- src/main/src/test/java/org/geoserver/security/decorators/SecuredWMTSLayerTest.java
- src/main/src/test/java/org/geoserver/security/decorators/SecuredWebMapTileServerTest.java
See https://osgeo-org.atlassian.net/browse/GEOS-8813
When WMTS was added to GeoServer
a) GeoFence was not updated with support for it
b) The GeoServer Security subsystem was only updated to include minimal support for it.
This fixes both these issues, and as a result, the linked bug (The geofence changes are split into a separate commit from the core api changes).
Note: This fix required nontrivial API changes to the core WMTSLayerInfo API (so that SecuredWMTSLayer would actually delegate to the wrapped WMTSLayer properly). 
(Now that Planet Federal has a signed CLA again, I've got a bit of a backlog of bugfixes I'm contributing. Obviously, merging them is going to have to wait until the build server is working again)
> [GEOS-8813] Add support for WMTS layers to GeoFence plugin

- doc/en/api/1.0.0/datastores.yaml
- src/extension/app-schema/app-schema-mongo-test/src/test/java/org/geoserver/test/onlineTest/ComplexMongoDBSupport.java
- src/extension/app-schema/app-schema-mongo-test/src/test/java/org/geoserver/test/onlineTest/ComplexMongoDBTest.java
- src/extension/mongodb/src/main/java/org/geoserver/rest/service/MongoStoreRestController.java
This PR improves MongoDB App-Schema schema rebuild REST endpoint, building only schemas used in declared mappings and giving an extra parameter to define a schema name to re-build.
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-9268 …
> [GEOS-9268] Make MongoDB App-Schema schema rebuilder endpoints only rebuild schemas present in mappings

- src/community/gwc-azure-blob/src/main/java/org/geoserver/gwc/web/blob/AzureBlobStoreType.java
- src/community/gwc-azure-blob/src/main/resources/applicationContext.xml
- src/community/gwc-azure-blob/src/test/java/org/geoserver/gwc/web/blob/AzureBlobStorePageTest.java
- src/web/app/pom.xml
This PR aligns with GeoWebCache Azure Blobstore fixes on ALLOW_ENV_PARAMETRIZATION variable resolving.
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-9288
Requires:
https://github.com/GeoWebCache/geowebcache/pull/779
> [GEOS-9288] Azure Blobstore shows values instead of parameter names if ALLOW_ENV_PARAMETRIZATION is active

- doc/en/user/source/configuration/globalsettings.rst
Updated to inform about case-insesitivity of appended path in Proxy URL templates
> Updated Use Headers for Proxy URL

- doc/en/user/source/configuration/globalsettings.rst
Updated to inform about case-insesitivity of appended path in Proxy URL templates
> Updated Use Headers for Proxy URL (#3675) (backport 2.15.x)

- doc/en/user/source/configuration/globalsettings.rst
Updated to inform about case-insesitivity of appended path in Proxy URL templates
> Updated Use Headers for Proxy URL (#3675) (backport 2.14.x)

- build/build_release.sh
Try to force manual document to be called geoserver-2.x.t-user-manual.pdf
> mv manual to new name

- doc/en/user/source/data/raster/imagemosaic/configuration.rst
Adding doc for WrapStore parameter of ImageMosaic's Indexer
> Documenting ImageMosaic-Indexer's WrapStore parameter

- doc/en/user/source/data/raster/imagemosaic/configuration.rst
Backport of Documenting ImageMosaic-Indexer's WrapStore parameter
> Documenting ImageMosaic-Indexer's WrapStore parameter - bkpt to 2.15.x

- doc/en/user/source/security/tutorials/ldap/index.rst
This PR fixes a failure on Security LDAP docs build because an extra space character.
2.15.x branch.
> Security LDAP docs fix (2.15.x)

- doc/en/user/source/styling/ysld/reference/featurestyles.rst
new x-ruleEvaluation parameter instead old x-firstMatch
> Update YAML featurestyles.rst

- src/extension/printing/pom.xml
Merge from: https://github.com/geoserver/geoserver/pull/3673
Upgrade of mapfish-print lib version to support font configuration on windows machines.
Reference:
mapfish/mapfish-print#998
Already release on central maven:
http://central.maven.org/maven2/org/mapfish/print/print-lib/2.1.5/
> Mapfish Print - Error when loading fonts, with configDir in windows machines

- doc/en/user/source/styling/css/properties.rst
Using CSS styling it appears there's a "font-opacity" which works for labels, but is not documented. Looking at the generated SLD, it compiles to TextSymbolizer->Fill->CssParameter:fill-opacity. In GeoTool's source code, there appears to be a "font-opacity" property in the CSS parser. …
> Added font-opacity

- doc/en/docguide/source/background.rst
- doc/en/docguide/source/contributing.rst
- doc/en/docguide/source/install.rst
- doc/en/docguide/source/installlatex.rst
- doc/en/docguide/source/sphinx.rst
- doc/en/docguide/source/style.rst
- doc/en/docguide/source/tutorial.rst
- doc/en/docguide/source/workflow.rst
This PR updates the docguide to reflect the changes to the process over the years, such as the retirement of  `make`, the easier ways to add latex to an ubuntu machine now. It also reverses the order of contribution paths to now run from easy to hard to avoid putting new users off. …
> [GEOS-9299] update docguide to reflect new processes and fix typos

- src/community/pom.xml
This PR removes status-monitoring reference on community pom.xml since it was promoted to extension.
> (2.15.x) Fix status-monitoring reference on community pom.xml

- src/community/mapml/src/main/java/org/geoserver/mapml/MapMLController.java
- src/community/mapml/src/main/java/org/geoserver/mapml/tcrs/TiledCRS.java
This change applies only to code in the MapML Community Moduel.
This commit adds a `<picture>` element to the html response for a MapML preview page, which provides a basic map in the case where script fails to load or run.  The objective of this is to demonstrate / prove the use of the <map> element as a reasonable extension point of HTML for maps. Interactivity is not provided, but likely could be, in the form of `<area>` elements with (pixel-based) coordinates in the map coordinate reference system as appropriate to the requested map.
@cmhodgson please review
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a …
> Add responsive images to MapML html response as fallback

- src/main/src/main/java/org/geoserver/catalog/impl/ModificationProxyCloner.java
- src/main/src/test/java/org/geoserver/catalog/impl/ModificationProxyClonerTest.java
The ModificationProxyCloner deep copies only one level, but it should deep copy infinitely.
(This is relevant for the upcoming metadata module, which puts deeper level metadata in resources)
> ModificationProxyCloner deep copy fix

- src/wms/src/main/java/org/geoserver/wms/map/AbstractOpenLayersMapOutputFormat.java
- src/wms/src/main/resources/org/geoserver/wms/map/OpenLayers2MapTemplate.ftl
- src/wms/src/main/resources/org/geoserver/wms/map/OpenLayers3MapTemplate.ftl
- src/wms/src/test/java/org/geoserver/wms/map/GetMapIntegrationTest.java
- src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapTemplateTest.java
This PR adds a fix for a mixed protocol issue on Openlayers WMS map preview static resources (js and css).
> [GEOS-8504] Wrong URL scheme in layer preview

- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TiledCollectionDocument.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TilesService.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/GetTileTest.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/TilesTestSupport.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/AbstractAppSchemaTestSupport.java
- src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
- src/wms/src/test/java/org/geoserver/wms/WMSTestSupport.java
Simple core test refactor (pulling up a method to be shared, via automated refactoring) and changes in the OGC API community module. Just running though PR to get the QA validation.
> Tiles API returns error if png and png8 are both configured, due to duplicated format key

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/ByteArrayMessageConverter.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TilesService.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/GetTileTest.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/TilesTestSupport.java
Again just using the PR facilities for QA here
> json and topojson tiles are returned a odd binary string blobs instead of json due to jackson converter catching all

- doc/en/user/source/services/wfs/outputformats.rst
- src/community/security/keycloak/pom.xml
- src/community/security/oauth2-geonode/pom.xml
- src/community/security/oauth2-github/pom.xml
- src/community/security/oauth2-openid-connect/pom.xml
- src/main/pom.xml
- src/pom.xml
- src/wfs/pom.xml
- src/wfs/src/test/java/org/geoserver/wfs/json/GeoJSONBuilderTest.java
This PR upgrades json-lib version and adds testing or the max nested limit issue on WFS GeoJson encoding.
https://osgeo-org.atlassian.net/browse/GEOS-9321
> [GEOS-9321] WFS GeoJSONBuilder limits max nested level to 20

- doc/en/user/source/services/wfs/outputformats.rst
- src/community/security/keycloak/pom.xml
- src/community/security/oauth2-geonode/pom.xml
- src/community/security/oauth2-github/pom.xml
- src/community/security/oauth2-openid-connect/pom.xml
- src/main/pom.xml
- src/pom.xml
- src/wfs/pom.xml
- src/wfs/src/test/java/org/geoserver/wfs/json/GeoJSONBuilderTest.java
This PR upgrades json-lib version and adds testing or the max nested limit issue on WFS GeoJson encoding.
https://osgeo-org.atlassian.net/browse/GEOS-9321
> [Backport 2.16.x][GEOS-9321] WFS GeoJSONBuilder limits max nested level to 20

- doc/en/user/source/services/wfs/outputformats.rst
- src/community/security/keycloak/pom.xml
- src/community/security/oauth2-geonode/pom.xml
- src/community/security/oauth2-github/pom.xml
- src/community/security/oauth2-openid-connect/pom.xml
- src/main/pom.xml
- src/pom.xml
- src/wfs/pom.xml
- src/wfs/src/test/java/org/geoserver/wfs/json/GeoJSONBuilderTest.java
This PR upgrades json-lib version and adds testing or the max nested limit issue on WFS GeoJson encoding.
https://osgeo-org.atlassian.net/browse/GEOS-9321
> [Backport 2.15.x][GEOS-9321] WFS GeoJSONBuilder limits max nested level to 20

- src/release/jetty/etc/jetty.xml
- src/web/app/src/test/java/org/geoserver/web/Start.java
This PR adds hyperspectral image configuration support in "bin" package due to form too big.
This is a draft since an hyperspectral image is required for testing purposes.
https://osgeo-org.atlassian.net/browse/GEOS-9133
> [GEOS-9133] hyperspectral image configuration support in "bin" package

- src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/CapabilityUtil.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
- src/wms/src/test/java/org/geoserver/wms/LegendNonValidCapabilitiesTest.java
This PR adds extra LegendInfo validation rules on WMS Capabilities_1_3_0_Translator class, fixing the bug described on:
https://osgeo-org.atlassian.net/browse/GEOS-8982
> [GEOS-8982] GetCapabilities on a single layer fails if a style is duplicated

- doc/en/user/source/services/wfs/webadmin.rst
- src/wfs/src/main/java/org/geoserver/wfs/xml/WFSXmlUtils.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v1_0_0/WfsXmlReader.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v1_1_0/WfsXmlReader.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v2_0/WfsXmlReader.java
- src/wfs/src/test/java/org/geoserver/wfs/TransactionTest.java
- src/wfs/src/test/java/org/geoserver/wfs/v1_1/TransactionTest.java
- src/wfs/src/test/java/org/geoserver/wfs/v2_0/TransactionTest.java
Currently WFS XML Readers (example: org.geoserver.wfs.xml.v1_0_0.WfsXmlReader) don't have a way to set an Entity expansion limit configuration. A good improvement could be having a configuration System Property that allows to achieve this task and setting a low default (100 as example?).
See Entity Expansion limit on documentation:
https://docs.oracle.com/javase/tutorial/jaxp/limits/using.html
This PR uses improved Geotools XML Parser API and adds a org.geoserver.wfs.xml.entityExpansionLimit System Property for configuring Entity Expansion Limit with 100 as default value.
https://github.com/geotools/geotools/pull/2437
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-9248
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to …
> [GEOS-9248] Allow setting Entity Expansion limit on WFS XML Readers.

- src/main/src/main/java/org/geoserver/data/util/TemporalUtils.java
- src/main/src/test/java/org/geoserver/data/test/TemporalData.properties
- src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/TextFeatureInfoOutputFormat.java
- src/wms/src/test/java/org/geoserver/wms/featureinfo/GetFeatureInfoJSONTest.java
- src/wms/src/test/java/org/geoserver/wms/featureinfo/TextFeatureInfoOutputFormatTest.java
The following formats: text/html, GeoJSON, text/plain don't have any special treatment for date \ times and simply do a to string regardless of the timezone or time format in WMS GetFeatureInfo.
This is PR fixes GeoJSON, text/plain temporal types formatting handling.
Text/html is managed by Freemarker template engine, but checking how to override it.
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-8356
Requires:
https://github.com/geotools/geotools/pull/2477
The following are required only for …
> [GEOS-8356] WMS GetFeatureInfo formats text/plain, GeoJSON don't handle time correctly

- src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/CapabilityUtil.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
- src/wms/src/test/java/org/geoserver/wms/LegendNonValidCapabilitiesTest.java
This PR adds extra LegendInfo validation rules on WMS Capabilities_1_3_0_Translator class, fixing the bug described on:
https://osgeo-org.atlassian.net/browse/GEOS-8982
> [Backport 2.15.x][GEOS-8982] GetCapabilities on a single layer fails if a style is duplicated

- src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/CapabilityUtil.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
- src/wms/src/test/java/org/geoserver/wms/LegendNonValidCapabilitiesTest.java
This PR adds extra LegendInfo validation rules on WMS Capabilities_1_3_0_Translator class, fixing the bug described on:
https://osgeo-org.atlassian.net/browse/GEOS-8982 …
> [Backport 2.16.x][GEOS-8982] GetCapabilities on a single layer fails if a style is duplicated

- doc/en/user/source/services/wfs/webadmin.rst
- src/wfs/src/main/java/org/geoserver/wfs/xml/WFSXmlUtils.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v1_0_0/WfsXmlReader.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v1_1_0/WfsXmlReader.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v2_0/WfsXmlReader.java
- src/wfs/src/test/java/org/geoserver/wfs/TransactionTest.java
- src/wfs/src/test/java/org/geoserver/wfs/v1_1/TransactionTest.java
- src/wfs/src/test/java/org/geoserver/wfs/v2_0/TransactionTest.java
Currently WFS XML Readers (example: org.geoserver.wfs.xml.v1_0_0.WfsXmlReader) don't have a way to set an Entity expansion limit configuration. A good improvement could be having a configuration System Property that allows to achieve this task and setting a low default (100 as example?).
See Entity Expansion limit on documentation:
https://docs.oracle.com/javase/tutorial/jaxp/limits/using.html
This PR uses improved Geotools XML Parser API and adds a org.geoserver.wfs.xml.entityExpansionLimit System Property for configuring Entity Expansion Limit with 100 as default value.
geotools/geotools#2437
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-9248
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as …
> [Backport 2.16.x][GEOS-9248] Allow setting Entity Expansion limit on WFS XML Readers.

- doc/en/user/source/services/wfs/webadmin.rst
- src/wfs/src/main/java/org/geoserver/wfs/xml/WFSXmlUtils.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v1_0_0/WfsXmlReader.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v1_1_0/WfsXmlReader.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v2_0/WfsXmlReader.java
- src/wfs/src/test/java/org/geoserver/wfs/TransactionTest.java
- src/wfs/src/test/java/org/geoserver/wfs/v1_1/TransactionTest.java
- src/wfs/src/test/java/org/geoserver/wfs/v2_0/TransactionTest.java
Currently WFS XML Readers (example: org.geoserver.wfs.xml.v1_0_0.WfsXmlReader) don't have a way to set an Entity expansion limit configuration. A good improvement could be having a configuration System Property that allows to achieve this task and setting a low default (100 as example?).
See Entity Expansion limit on documentation:
https://docs.oracle.com/javase/tutorial/jaxp/limits/using.html
This PR uses improved Geotools XML Parser API and adds a org.geoserver.wfs.xml.entityExpansionLimit System Property for configuring Entity Expansion Limit with 100 as default value.
geotools/geotools#2437
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-9248
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as …
> [Backport 2.15.x][GEOS-9248] Allow setting Entity Expansion limit on WFS XML Readers.

- src/main/src/main/java/org/geoserver/data/util/TemporalUtils.java
- src/main/src/test/java/org/geoserver/data/test/TemporalData.properties
- src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/TextFeatureInfoOutputFormat.java
- src/wms/src/test/java/org/geoserver/wms/featureinfo/GetFeatureInfoJSONTest.java
- src/wms/src/test/java/org/geoserver/wms/featureinfo/TextFeatureInfoOutputFormatTest.java
The following formats: text/html, GeoJSON, text/plain don't have any special treatment for date \ times and simply do a to string regardless of the timezone or time format in WMS GetFeatureInfo.
This is PR fixes GeoJSON, text/plain temporal types formatting handling.
Text/html is managed by Freemarker template engine, but checking how to override it.
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-8356
Requires:
geotools/geotools#2477 …
> [Backport 2.16.x][GEOS-8356] WMS GetFeatureInfo formats text/plain, GeoJSON don't handle time correctly

- src/main/src/main/java/org/geoserver/data/util/TemporalUtils.java
- src/main/src/test/java/org/geoserver/data/test/TemporalData.properties
- src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/TextFeatureInfoOutputFormat.java
- src/wms/src/test/java/org/geoserver/wms/featureinfo/GetFeatureInfoJSONTest.java
- src/wms/src/test/java/org/geoserver/wms/featureinfo/TextFeatureInfoOutputFormatTest.java
The following formats: text/html, GeoJSON, text/plain don't have any special treatment for date \ times and simply do a to string regardless of the timezone or time format in WMS GetFeatureInfo.
This is PR fixes GeoJSON, text/plain temporal types formatting handling.
Text/html is managed by Freemarker template engine, but checking how to override it.
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-8356
Requires:
geotools/geotools#2477 …
> [Backport 2.15.x][GEOS-8356] WMS GetFeatureInfo formats text/plain, GeoJSON don't handle time correctly

- src/release/jetty/etc/jetty.xml
- src/web/app/src/test/java/org/geoserver/web/Start.java
This PR adds hyperspectral image configuration support in "bin" package due to form too big.
This is a draft since an hyperspectral image is required for testing purposes.
https://osgeo-org.atlassian.net/browse/GEOS-9133
> [Backport 2.16.x][GEOS-9133] hyperspectral image configuration support in "bin" package

- src/community/hz-cluster/src/main/java/org/geoserver/cluster/ConfigChangeEvent.java
- src/community/hz-cluster/src/main/java/org/geoserver/cluster/hazelcast/EventHzSynchronizer.java
- src/community/hz-cluster/src/main/java/org/geoserver/cluster/hazelcast/HzSynchronizer.java
- src/community/hz-cluster/src/test/java/org/geoserver/cluster/hazelcast/HzSynchronizerRecvTest.java
Hz-cluster: unlike for catalog items, for services only post-modify events are sent, not other events such as modify, add, delete
As a consequence the service config web pages are not cluster-safe
> GEOS-9326 Hz-cluster: fix service events

- doc/en/developer/source/release-guide/index.rst
Very minor updates to the release guide, based on differences encountered during the 2.16-RC release - just removing the en and fr doc dirs from the guide, as those dors were removed recently.
> Release guide update

- src/community/notification/src/main/java/org/geoserver/notification/NotificationTransactionListener.java
- src/community/notification/src/test/java/org/geoserver/notification/IntegrationTest.java
For the test to passed, at least the current version of guava on geoserver 2.14.x is needed
Guava on geoserver 2.16.x and 2.15.x throws this exception
org.geoserver.notification.AnonymousIntegrationTest: com.google.common.util.concurrent.Futures.addCallback(Lcom/google/common/util/concurrent/ListenableFuture;Lcom/google/common/util/concurrent/FutureCallback;)V
org.geoserver.notification.IntegrationTest: com.google.common.util.concurrent.Futures.addCallback(Lcom/google/common/util/concurrent/ListenableFuture;Lcom/google/common/util/concurrent/FutureCallback;)V
> [GEOS-9238] - The notification community module breaks WFS-T transactions

- doc/en/user/source/community/ncwms/index.rst
- doc/en/user/source/services/wms/reference.rst
- src/community/ncwms/src/main/java/org/geoserver/wms/ncwms/GetTimeSeriesResponse.java
- src/community/ncwms/src/test/java/org/geoserver/wms/ncwms/NcWmsGetTimeSeriesTest.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/RasterLayerIdentifier.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java
Tweaking a bit the nodata management on ncWMS, spitting out an empty value on csv so that we know the time was available but a nodata value was there.
> [GEOS-9330]-2: Follow up on NcWMS getTimeSeries noData management

- doc/en/api/1.0.0/workspaces.yaml
It's documented for /workspaces/{workspaceName}/datastores/{storeName} but also works for /workspaces/{workspaceName}. Thus document it.
> Document quietOnNotFound for workspaces REST-API

- src/extension/monitor/core/src/main/java/org/geoserver/monitor/auditlog/AuditLogger.java
- src/extension/monitor/core/src/test/java/org/geoserver/monitor/auditlog/AuditLoggerTest.java
This pull request synchronizes the audit logger initialization to fix a race condition that could cause the audit log files to be written to the wrong directory. https://osgeo-org.atlassian.net/browse/GEOS-9296
> [GEOS-9296] Fix race condition in audit logger initialization

- src/wfs/src/test/java/org/geoserver/wfs/remote/v2_0/WfsRemoteStoreTest.java
- src/wfs/src/test/resources/org/geoserver/wfs/remote/v2_0/tiger_roads_describe_feature_type_special_chars.xml
- src/wfs/src/test/resources/org/geoserver/wfs/remote/v2_0/tiger_roads_get_feature_resp_special_chars.xml
> [GEOS-9336] Integration test for WFSDataStore when doing a GetFeature operation having special chars in PropertyName

- doc/en/user/source/production/container.rst
* doc/en/user/source/production/container.rst: Correct max heap size, make it consistent with the other numbers.
Just one inconsistency I found while reading.
- [x ] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [-] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x ] Make sure the first PR targets the master branch, eventual …
> doc: Fix typo in memory size.

- src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/converters/ImportJSONReader.java
- src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/ImporterIntegrationTest.java
@mbarto 
addressing Mauro feedback on https://github.com/geoserver/geoserver/pull/3666
- Un-Supported charset throws exception
- fixed Unit Test
> [GEOS-9073] fixed unit test and charset support checking

- src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureTest.java
Disabling tests that are randomly failing
> Disable failing tests, see https://osgeo-org.atlassian.net/browse/GEOS-9367

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/WPSXStreamLoader.java
- src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
- src/pom.xml
- src/rest/src/main/java/org/geoserver/rest/converters/XStreamCatalogListConverter.java
This adresses GEOS-9307, bump fixes CVE-2013-7285 and CVE-2019-10173.
See also: https://x-stream.github.io/changes.html
Replaces #3761 with a build fix.
> [GEOS-9307] Bump com.thoughtworks.xstream:xstream from 1.4.10 to 1.4.11.1

- src/web/core/src/main/java/org/geoserver/web/data/store/WMTSStoreNewPage.java
Pass entered credentials to underlying WebMapTileServer component. Fixes issue of accessing WMTS server protected by Basic Authentication (same code exists for WMSStoreNewPage). 
Jira issue: https://osgeo-org.atlassian.net/browse/GEOS-9357
> [GEOS-9357] Credentials for WMTS service are not used 

- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/ScalingPolicy.java
It's already covered by a test, but the test took several seconds to enter the expected error condition because it was attempting a large rescale. This also brought the system in a near OOM condition that might have been the cause for the random WCS test failures.
Submitting the PR does not require you to check all items, but by the time it gets merged, they should be …
> [GEOS-9357] WCS 2.0 scalefactor=0 can cause excess memory usage

- doc/en/user/source/security/webadmin/csrf.rst
It would be nice if searching for "Origin does not correspond to request" and GeoServer had a chance of finding the CSRF page (rather than an old jira issue).
> [GEOS-9378] Add note to CSRF section with error message in

- doc/en/user/source/community/csw-iso/tutorial.rst
This proposal adds and example of how you might query CSW using an HTTP POST request and also demonstrates how to search the keywords and increase the number of results returned.
> Add POST example with keyword search

- src/restconfig/src/main/java/org/geoserver/rest/catalog/FeatureTypeController.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/FeatureTypeControllerTest.java
Fix a bug by which it's not possible to create a FeatureType
through the REST API on a store if another store with the same
name exists on a different Workspace (race condition: may succeed
if the FeatureTypeInfo request body deserialization picks up
the correct StoreInfo by chance) …
> [GEOS-9190]: Unable to create feature type through REST if two stores on different workspaces have the same name

- src/restconfig/src/main/java/org/geoserver/rest/catalog/DataStoreController.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/DataStoreControllerTest.java
Deleting a datastore without a recurse parameter set should
fail if there are FeatureTypes configured for that DataStore.
Instead, the logic was checking if the datastore existed
on its workspace, but fails if there are any other datastore in the same workspace, 
which is unrelated to deleting a given datastore.
This patch simplifies `DataStoreController.dataStoreDelete()`
letting the catalog comply if the DataStore cannot be deleted,
since the DataStore being empty is a precondition on
`Catalog.remove(DataStoreInfo)` anyways.
Removed the extra unnnecessary call to `Catalog.remove()`.
Removed the calls to `ResourcePool.clear()` since that's already
handled by the internal machinery.
> GEOS-9189 - Fix REST endpoint for datastore delete without recurse flag

- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCS20GetCapabilitiesTransformer.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/WCSTestSupport.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/GetCapabilitiesTest.java
- src/wcs2_0/src/test/resources/crs/requestGetCoverageOutputCRS.xml
- src/wcs2_0/src/test/resources/crs/requestGetCoverageSubsettingCRS.xml
- src/wcs2_0/src/test/resources/crs/requestGetCoverageSubsettingTrimCRS.xml
- src/wcs2_0/src/test/resources/crs/requestGetCoverageSubsettingTrimCRS2.xml
- src/wcs2_0/src/test/resources/getcapabilities/getCap.xml
- src/wcs2_0/src/test/resources/requestGetCoverageAcrossDatelineMercatorPacific.xml
- src/wcs2_0/src/test/resources/requestGetCoverageAcrossDatelinePolar.xml
fixed WCS 2 Capability document as per OGC specs [WCS.2 Specs](https://portal.opengeospatial.org/files/54209)
-wcscrs changed to crs
-added crs:CrsMetadata to wcs:Extension
-moved crsSupported(s) inside crs:CrsMetadata
-updated unit tests
-fixed namespaces in test resources
Submitting the PR does not require you to check all items, but by the time it gets merged, they …
> [GEOS-9328] WCS 2 - CRS Extension not implemented correctly

- src/main/src/main/java/org/geoserver/catalog/WMSLayerInfo.java
- src/main/src/main/java/org/geoserver/catalog/impl/WMSLayerInfoImpl.java
- src/main/src/main/java/org/geoserver/security/decorators/DecoratingWMSLayerInfo.java
- src/web/wms/src/main/java/org/geoserver/wms/web/publish/WMSLayerConfig.java
- src/web/wms/src/test/java/org/geoserver/wms/web/data/publish/WMSLayerConfigTest.java
- src/wms/src/main/java/org/geoserver/wms/GetMap.java
- src/wms/src/test/java/org/geoserver/wms/WMSCascadeTestSupport.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/WMSCascadeTest.java
-moved remote calls for styles out of getters
-remote calls for styles will only be made when configuring/reloading Cascaded WMS Layer from UI
> [GEOS-9377] Geoserver startup gets blocked with unresponsive WMSStore

- src/rest/src/main/java/org/geoserver/rest/util/RESTUtils.java
> Follow up on previous commit 635c405 that broke rest config tests on Windows only

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SRSReprojectionTest.java
- src/wfs/src/main/java/org/geoserver/wfs/GetFeature.java
Fixes declared CRS reprojection support for AppSchema complex features, on WFS GetFeature requests.
https://osgeo-org.atlassian.net/browse/GEOS-9369
> [GEOS-9369] Fix declared CRS reprojection on AppSchema complex features

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SRSReprojectionTest.java
- src/wfs/src/main/java/org/geoserver/wfs/GetFeature.java
Fixes declared CRS reprojection support for AppSchema complex features, on WFS GetFeature requests.
https://osgeo-org.atlassian.net/browse/GEOS-9369
> [2.15.x backport][GEOS-9369] Fix declared CRS reprojection on AppSchema complex features

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SRSReprojectionTest.java
- src/wfs/src/main/java/org/geoserver/wfs/GetFeature.java
Fixes declared CRS reprojection support for AppSchema complex features, on WFS GetFeature requests.
https://osgeo-org.atlassian.net/browse/GEOS-9369
> [2.16.x backport][GEOS-9369] Fix declared CRS reprojection on AppSchema complex features

- src/community/wps-remote/src/main/java/org/geoserver/wps/remote/RemoteProcessClient.java
- src/community/wps-remote/src/main/java/org/geoserver/wps/remote/plugin/XMPPCannotExecuteMessage.java
- src/community/wps-remote/src/main/java/org/geoserver/wps/remote/plugin/XMPPClient.java
- src/community/wps-remote/src/main/java/org/geoserver/wps/remote/plugin/XMPPCompletedMessage.java
- src/community/wps-remote/src/main/java/org/geoserver/wps/remote/plugin/XMPPErrorMessage.java
- src/community/wps-remote/src/main/resources/applicationContext.xml
- Fixes GEOS-9398 : [Community][wps-remote] Async Request Management Proposal
> [Fixes GEOS-9398] [Community][wps-remote] Async Request Management Proposal

- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/api/features/Queryable.java
- src/web/wms/src/main/java/org/geoserver/wms/web/publish/WMSLayerConfig.html
- src/web/wms/src/main/java/org/geoserver/wms/web/publish/WMSLayerConfig.java
- src/web/wms/src/main/resources/GeoServerApplication.properties
- src/web/wms/src/test/java/org/geoserver/wms/web/data/publish/WMSLayerConfigTest.java
-added UI legends
-fixed indenting/formatting/descriptions
https://osgeo-org.atlassian.net/browse/GEOS-9394
> [GEOS-9394] Cascaded WMS UI improvements

- src/platform/pom.xml
- src/platform/src/main/java/org/geoserver/platform/resource/FileSystemResourceStore.java
- src/platform/src/main/java/org/geoserver/platform/resource/FileSystemWatcher.java
- src/platform/src/main/java/org/geoserver/platform/resource/ResourceNotification.java
- src/platform/src/test/java/org/geoserver/platform/resource/FileSystemResourceStoreTest.java
- src/platform/src/test/java/org/geoserver/platform/resource/FileSystemResourceTheoryTest.java
- src/pom.xml
Running against a rather large data directory leads `FileSystemWatcher`'s polling thread to be fixed at  100% usage on one CPU core (which one varies every a handful of seconds).
The bellow [data_dir_100k.tgz](https://drive.google.com/open?id=13nhQz_0QGm459muwQ2Qgcre_5HaXvshM) archive contains a data directory with +86K layers and has been used to conduct the testing for this patch.
This performance issue with `FileSystemWatcher` reveals itself since `DefaultTileLayerCatalog` started listening to changes to the `<data_dir>/gwc-layers` directory (which contains tile layer config files, not tile images) in order to update tile layer configs when they're updated externally on a cluster deployment (added at   https://github.com/geoserver/geoserver/commit/966a8af90fc6b68725a78b09829c3cbc7360242 …
> [GEOS-9191] FileSystemWatcher: 100% CPU usage while idle running on a large data directory

- doc/en/api/1.0.0/owsservices.yaml
- doc/en/user/source/rest/api/services.rst
- doc/en/user/source/rest/index.rst
- src/pom.xml
- src/restconfig-wmts/pom.xml
- src/restconfig-wmts/src/main/java/org/geoserver/rest/service/WMTSSettingsController.java
- src/restconfig-wmts/src/main/java/org/geoserver/rest/service/ftl-templates/wmtsSettings.ftl
- src/restconfig-wmts/src/test/java/org/geoserver/rest/service/LocalWMTSSettingsControllerTest.java
- src/restconfig-wmts/src/test/java/org/geoserver/rest/service/WMTSSettingsControllerTest.java
- src/restconfig-wmts/src/test/resources/org/geoserver/rest/service/wmts.xml
- src/web/app/pom.xml
Core module (`restconfig-wmts`) to enable configuring basic WMTS service metadata (global and workspace-local) through the REST API just like it's done for WMS, WFS, and WCS.
> [GEOS-9395] restconfig module for WMTS service configuration

- src/platform/pom.xml
- src/platform/src/main/java/org/geoserver/platform/resource/FileSystemResourceStore.java
- src/platform/src/main/java/org/geoserver/platform/resource/FileSystemWatcher.java
- src/platform/src/main/java/org/geoserver/platform/resource/ResourceNotification.java
- src/platform/src/test/java/org/geoserver/platform/resource/FileSystemResourceStoreTest.java
- src/platform/src/test/java/org/geoserver/platform/resource/FileSystemResourceTheoryTest.java
- src/pom.xml
re-applies #3860 fixing a bug that resulted in an NPE when the watched directory didn't exist at the time of registering a directory listener.
> [GEOS-9191] (Fixed) FileSystemWatcher: 100% CPU usage while idle running on a large data directory

- src/gwc/src/main/java/org/geoserver/gwc/config/GWCInitializer.java
- src/gwc/src/main/java/org/geoserver/gwc/layer/CatalogConfiguration.java
- src/gwc/src/main/java/org/geoserver/gwc/layer/DefaultTileLayerCatalog.java
- src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
- src/gwc/src/main/java/org/geoserver/gwc/layer/StyleParameterFilter.java
- src/gwc/src/test/java/org/geoserver/gwc/RESTIntegrationTest.java
- src/gwc/src/test/java/org/geoserver/gwc/layer/CatalogConfigurationLayerConformanceTest.java
- src/gwc/src/test/java/org/geoserver/gwc/layer/DefaultTileLayerCatalogTest.java
- src/main/src/main/java/org/geoserver/config/AsynchResourceIterator.java
- src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/AbstractParameterFilterSubform.java
- src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/RegexParameterFilterSubform.java
- src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/StringParameterFilterSubform.java
See [GEOS-9385](https://osgeo-org.atlassian.net/browse/GEOS-9385) for a more in depth description of the issue and how this PR improves it.
* Avoid `DefaultTileLayerCatalog` initialization thrashing the filesystem `DefaultTileLayerCatalog.initialize()` loads `GeoServerTileLayerInfo` objects from the gwc-layers datadirectory sub folder concurrently, on the common pool, thrashing the file system if there are many cores.    
Instead of using `ForkJoinPool.commonPool()`, set up a short-lived `ForkJoinPool` with limited parallelism, and make it respect the `org.geoserver.catalog.loadingThreads` system property, following the same settings as `AsynchResourceIterator`.
* Reduce resource usage of `GWCInitializer`
* Overcome XStream poor concurrency at `DefaultTileLayerCatalog` parallel …
> [GEOS-9385] GWC initialization thrashes CPU and filesystem at startup 

- src/web/core/src/main/java/org/geoserver/web/publish/PublishedConfigurationPage.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/CachedLayersPageTest.java
-fixed, clicking coming to layer page from Tile layers list selects 'Tile
Caching'
When clicking a layer from Tiles Admin list, the tab selected by default was Publishing when it should have been Tile Caching.
https://osgeo-org.atlassian.net/browse/GEOS-8940
Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either …
> [GEOS-8940] Tile Layers page layer names bring to the "Publishing" tab by default

- src/wms/src/main/java/org/geoserver/wms/capabilities/DimensionHelper.java
- src/wms/src/main/java/org/geoserver/wms/dimension/AbstractDefaultValueSelectionStrategy.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DimensionsVectorCapabilitiesTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/DimensionsVectorCapabilitiesTest.java
- src/wms/src/test/resources/org/geoserver/wms/TimeElevation.properties
There are data format issues on on Custom vector dimensions GetCapabilities response document, described as following:
1. Date format: Dates are displayed on Locale format instead ISO8601 format on default attribute.
2. Interval representation: The end point of the interval representation seems to be the start point (e.g., values 1,2,3,4 -> 1/1 instead of 1/4), also integer numbers are showed as doubles.
This PR introduces a fix for the GetCapabilities format issues.
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-9406 …
> [GEOS-9406] Data format issues on Custom vector dimensions GetCapabilities

- src/wms/src/main/java/org/geoserver/wms/map/RenderedImageMapOutputFormat.java
This PR simply add support for a wms.raster.showChain=true JAVA_OPT to be used in debugging/testing mode. It supports RenderedImageBrowser usage on RenderedImageMapOutputFormat when the wms request has an additional "&showchain=true" vendor param specified
Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either …
> Add debug flag and vendor param to show imageprocessing chain

- doc/en/user/source/tutorials/freemarker.rst
- src/wms/src/main/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormat.java
- src/wms/src/test/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormatTest.java
- src/wms/src/test/resources/org/geoserver/wms/featureinfo/test_static_content.ftl
Master PR:https://github.com/geoserver/geoserver/pull/3814
JIRA:https://osgeo-org.atlassian.net/browse/GEOS-9361
> [GEOS-9361] Add Math support on freemarker template

- src/web/app/pom.xml
This allows use of the cross-origin filter in web.xml. Without it you will get the error `java.lang.ClassNotFoundException: org.eclipse.jetty.servlets.CrossOriginFilter`.
> Run mvn jetty:run in test scope

- doc/en/user/source/extensions/authkey/index.rst
https://osgeo-org.atlassian.net/browse/GEOS-9427
> [GEOS-9427] Fix authkey regex examples for capturing username

- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
backport of : https://github.com/geoserver/geoserver/pull/3931
> [2.16.x Backport] [GEOS-9420] GeoFenceAccessManager leaks HTTP clients #413

- src/community/security/oauth2-geonode/src/main/java/org/geoserver/security/oauth2/services/GeoNodeTokenServices.java
- src/community/security/oauth2-geonode/src/test/java/org/geoserver/security/oauth2/OAuth2RestTemplateTest.java
- Fixes GEOS-9435 : [community - oauth2] Include basic auth header for Oauth2 token instrospection requests
> [GEOS-9435] [community - oauth2] Include basic auth header for Oauth2 token instrospection requests

- src/gwc/src/main/java/org/geoserver/gwc/GWC.java
- src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
Integrated WMS requests not qualified for any workspace get ignored by Integrated GWC, since it expects layers to be always prefixed with workspace. The bug has been fixed and GWC will fall back to catalog if it is unable to find a layer in TileLayerDispatcher on first attempt.
JIRA:https://osgeo-org.atlassian.net/browse/GEOS-9431
Submitting the PR does not require you to …
> [GEOS-9431] Integrated GWC does not kick in when making request not qualified by workspace

- src/extension/app-schema/app-schema-mongo-test/src/test/java/org/geoserver/test/onlineTest/ComplexMongoDBSupport.java
This PR fixes a WMS test threshold parameter on AppSchema MongoDB testing module.
> [GEOS-9430] Fix AppSchema MongoDB WMS test threshold.

- src/extension/sldService/src/main/java/org/geoserver/sldservice/rest/RasterizerController.java
- src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/RasterizerTest.java
Fixes SLD produced by rasterize service, to include a generic FeatureTypeName with value Feature, instead of the original layer name, that is not correct for raster layer.
> [GEOS-9444]: SLDService rasterize service includes a wrong FeatureTypeName in produced SLD

- src/release/ext-authkey.xml
backport of https://github.com/geoserver/geoserver/pull/3937
JIRA https://osgeo-org.atlassian.net/browse/GEOS-9428
> [backport 2.15.x][GEOS-9428] Authkey role service filters broken on 2.16+

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/Gsml30WfsTest.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NamespacesWfsTest.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NestedElementsFilteringTest.java
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/nestedElements/persons.xml
- src/wfs/src/main/java/org/geoserver/wfs/xml/FeatureTypeSchemaBuilder.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/GML3OutputFormat.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/WFSXmlUtils.java
App-Schema WFS GetFeature GML 3.1 and 3.2 responses include namespaces from all workspaces on isolated workspace (virtual service) request. This PR fixes this issue.
Requires:
https://github.com/geotools/geotools/pull/2742
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9388 …
> [2.16.x backport][GEOS-9388] App-Schema WFS GetFeature includes namespaces for all workspaces on isolated workspace

- doc/en/developer/source/quickstart/checkout.txt
- src/community/script/core/src/main/java/org/geoserver/script/ScriptManager.java
- src/web/core/src/main/java/org/geoserver/web/ToolPage.java
- src/web/core/src/test/java/org/geoserver/web/GeoServerSecuredPageTest.java
The tools page lists all instances of ToolLinkExternalInfo, some recent work to make the Layer Preview page extendable reused this as a base class without testing the tools page.
This patch double checks that an instance has a description before including it in the tools page, this has the effect of filtering out all the CommonFormatLink instances.
> Fix tools page (GEOS-9348)

- .travis.yml
> [2.16.x backport] Travis CI - use HTTPS for Takari pull from maven

- doc/en/developer/source/quickstart/checkout.txt
- src/community/script/core/src/main/java/org/geoserver/script/ScriptManager.java
- src/web/core/src/main/java/org/geoserver/web/ToolPage.java
- src/web/core/src/test/java/org/geoserver/web/GeoServerSecuredPageTest.java
> [backport 2.16][GEOS-9348] Fix tools page to ignore external links without descriptionKey

- src/extension/importer/web/src/main/java/org/geoserver/importer/web/ImporterConfigPage.java
- src/extension/importer/web/src/test/java/org/geoserver/importer/web/ImporterConfigPageTest.java
JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9438
-fixed serialization
-added unit tests
> [GEOS-9438] Serializer errors when using the Importer GUI

- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TilesService.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/GetTileTest.java
- src/extension/vectortiles/src/test/java/org/geoserver/wms/vector/VectorTilesIntegrationTest.java
> OGC Tiles API NPE when the filtered mapbox tile is empty

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/ConnectionUsageTest.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/FeatureChainingSharedConnectionTest.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/LayersNamesAliasingTest.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/StationsMockData.java
- src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
- src/main/src/main/java/org/vfny/geoserver/global/GeoserverComplexFeatureSource.java
This PR adds support for layer definition CQL filter on complex features data sources, in the same approach as simple features layers support it already.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9478
> [GEOS-9478] Layer definition cql filter doesnt work for complex features

- .github/workflows/macos.yml
- .github/workflows/windows.yml
As it is now the cache is only ever stored but never restored because the key used to save (`gs-${{ runne....`) is different to the key used to restore (`${{ runne....`), note the **gs-**
- fix caching key for GH MacOS workflow
- fix caching key for GH Windows workflow
Submitting the PR does not require you to check all items, but by the time it gets merged, they should be …
> fix caching key for GH workflows

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/ConnectionUsageTest.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/FeatureChainingSharedConnectionTest.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/LayersNamesAliasingTest.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/StationsMockData.java
- src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
- src/main/src/main/java/org/vfny/geoserver/global/GeoserverComplexFeatureSource.java
This PR adds support for layer definition CQL filter on complex features data sources, in the same approach as simple features layers support it already.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9478
> [2.16.x backport][GEOS-9478] Layer definition cql filter doesnt work for complex features

- .travis.yml
- src/wfs/src/main/java/org/geoserver/wfs/WFSWorkspaceQualifier.java
- src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureJoinTest.java
Backport of #3971
Improve org.geoserver.wfs.WFSWorkspaceQualifier to resolve
typenames on the local workspace when a WFS request with
multiple elements in the 'typeNames' (not 'typeName') parameter
are specified.
checkOriginallyUnqualified() was only looking at TYPENAME (WFS 1.0),
and not TYPENAMES (2.0).
Since by the time TypeNameKvpParser resolves the requested type names,
the LocalWorkspace is not set, it may either resolve to an unqualified
QName, or one on any other workspace than the requested one (due to the
lenient resolution in TypeNameKvpParser.parseToken() calling
Catalog.getFeatureTypeByName(String), which in turns returns a feature
type in the default workspace or any other workspace if none is found).
This lead to either trying to use the wrong FeatureType or not finding
it …
> [backport-2.15.x] [GEOS-9458] Fix WFS 2.0 join queries with unqualified typenames

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NormalizedMultiValuesTest.java
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/measurements.properties
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/stations.properties
App-schema is getting "IllegalArgumentException: Could not find working property accessor for attribute" when it gets an empty collection on a 1..n cardinality attribute (jdbc multivalue).
This issue is replicated using Postgresql and a jdbc configuration following same steps and mappings as Geoserver documentation, but having no items for a root feature multivalue declared element:
https://docs.geoserver.org/stable/en/user/data/app-schema/mapping-file.html#attributes-with-cardinality-1-n
This PR adds testing for the fix PR added on Geotools:
https://github.com/geotools/geotools/pull/2790
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9483 …
> [GEOS-9483] Add testing for jdbc multi-value issue on empty collection

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NormalizedMultiValuesTest.java
- src/wfs/src/main/java/org/geoserver/wfs/json/ComplexGeoJsonWriter.java
When GeoJSON encoder tries to handle an xml attribute with other type than string, in this case an integer, Geoserver throws a class cast exception due to complex GeoJSON writer is handling all xml attributes as string.  On GML output this issue is not present and numeric typed attributes are encoded without exceptions.
This was reproduced using a app-schema jdbc multi value element with an integer typed attribute and executing a WFS GetFeature requesting GeoJSON output.
https://docs.geoserver.org/stable/en/user/data/app-schema/mapping-file.html#attributes-with-cardinality-1-n
This PR adds a fix for this issue.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9493
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small …
> [GEOS-9493] WFS GeoJSON complex features output issue on numeric typed xml attributes

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NormalizedMultiValuesTest.java
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/measurements.properties
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/stations.properties
App-schema is getting "IllegalArgumentException: Could not find working property accessor for attribute" when it gets an empty collection on a 1..n cardinality attribute (jdbc multivalue).
This issue is replicated using Postgresql and a jdbc configuration following same steps and mappings as Geoserver documentation, but having no items for a root feature multivalue declared element:
https://docs.geoserver.org/stable/en/user/data/app-schema/mapping-file.html#attributes-with-cardinality-1-n
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9483
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you …
> [2.16.x backport][GEOS-9483] Add testing for jdbc multi-value issue on empty collection

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NormalizedMultiValuesTest.java
- src/wfs/src/main/java/org/geoserver/wfs/json/ComplexGeoJsonWriter.java
When GeoJSON encoder tries to handle an xml attribute with other type than string, in this case an integer, Geoserver throws a class cast exception due to complex GeoJSON writer is handling all xml attributes as string. On GML output this issue is not present and numeric typed attributes are encoded without exceptions.
This was reproduced using a app-schema jdbc multi value element with an integer typed attribute and executing a WFS GetFeature requesting GeoJSON output.
https://docs.geoserver.org/stable/en/user/data/app-schema/mapping-file.html#attributes-with-cardinality-1-n
This PR adds a fix for this issue.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9493
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small …
> [2.16.x backport][GEOS-9493] WFS GeoJSON complex features output issue on numeric typed xml attributes

- src/extension/app-schema/app-schema-oracle-test/pom.xml
- src/extension/app-schema/app-schema-postgis-test/pom.xml
- src/extension/app-schema/app-schema-test/pom.xml
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NormalizedMultiValuesTest.java
- src/wfs/src/main/java/org/geoserver/wfs/json/ComplexGeoJsonWriter.java
When using App-Schema JDBC multivalue 1..n cardinality, GeoJSON output produces repeated keys instead locate the objects inside a json array. This PR introduces a fix for this issue.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9501 …
> [GEOS-9501] WFS GeoJSON complex features output returns duplicated key names instead a JSON array

- src/extension/app-schema/app-schema-oracle-test/pom.xml
- src/extension/app-schema/app-schema-postgis-test/pom.xml
- src/extension/app-schema/app-schema-test/pom.xml
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NormalizedMultiValuesTest.java
- src/wfs/src/main/java/org/geoserver/wfs/json/ComplexGeoJsonWriter.java
When using App-Schema JDBC multivalue 1..n cardinality, GeoJSON output produces repeated keys instead locate the objects inside a json array. This PR introduces a fix for this issue.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9501 …
> [2.16.x backport][GEOS-9501] WFS GeoJSON complex features output returns duplicated key names instead a JSON array

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/APIFilterParser.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/api/features/FeatureService.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/api/features/FeatureTest.java
Right now it was left to the wrapped service, which would have ended up using native CRS, eventually in EPSG native order.
> Default spatial CQL filters to WGS84 unless otherwise specified, following OGC API guidance

- doc/en/user/source/installation/index.rst
Below the list of available binaries, I added a note which:
- states GeoServer not longer provides the Windows Installers
- tells the user can create the Windows Installer themselves when needed
This way we hope to get fewer questions about the 'missing' Windows Installer in the download section.
> GEOS-9457: Restore the usage instruction of Windows Installer (only add ref to dev manual)

- src/main/src/main/java/org/geoserver/catalog/LayerGroupHelper.java
- src/main/src/main/java/org/geoserver/catalog/impl/LayerInfoImpl.java
- src/wms/src/test/java/org/geoserver/wms/WMSCascadeTestSupport.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/WMSCascadeTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/WMSCascadeTest.java
- src/wms/src/test/resources/org/geoserver/wms/caps111.xml
- src/wms/src/test/resources/org/geoserver/wms/caps130.xml
backport https://github.com/geoserver/geoserver/pull/4047
> [Backport 2.16.x][GEOS-9498] Add Backward compatibility on Layergroups with legacy Cascaded WMS Layers (#4047)

- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/AccessManagerTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/CacheReaderTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/GeofenceBaseTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/ServicesTest.java
- src/extension/geofence/src/test/java/org/geoserver/geoserver/authentication/filter/GeofenceFilterConfigTest.java
GeofenceAccessManager fails to cut geometries in coverages
When Geofence returns limits containing a limiting area, coverages not in 4326 are not properly cut.
The limited area is properly reprojected when handling vector layers, but not when handling coverages.
https://osgeo-org.atlassian.net/browse/GEOS-9559
Tests were not passing.
Most of them are integration tests, and were not run since long. 
Old tests were fixed, new test has been added.
- [-] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [-] Commits changing the REST API, or any configuration …
> [Backport to 2.15.x][GEOS-9559] GeofenceAccessManager fails to cut geometries in coverages (2.15.x)

- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/AccessManagerTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/AccessManagerWMTSLayerTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/CacheReaderTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/GeofenceBaseTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/ServicesTest.java
- src/extension/geofence/src/test/java/org/geoserver/geoserver/authentication/filter/GeofenceFilterConfigTest.java
GeofenceAccessManager fails to cut geometries in coverages
When Geofence returns limits containing a limiting area, coverages not in 4326 are not properly cut.
The limited area is properly reprojected when handling vector layers, but not when handling coverages.
https://osgeo-org.atlassian.net/browse/GEOS-9559
Tests were not passing.
Most of them are integration tests, and were not run since long. 
Old tests were fixed, new test has been added.
- [-] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [-] Commits changing the REST API, or any configuration …
> [GEOS-9559] GeofenceAccessManager fails to cut geometries in coverages

- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/AccessManagerTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/AccessManagerWMTSLayerTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/CacheReaderTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/GeofenceBaseTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/ServicesTest.java
- src/extension/geofence/src/test/java/org/geoserver/geoserver/authentication/filter/GeofenceFilterConfigTest.java
GeofenceAccessManager fails to cut geometries in coverages
When Geofence returns limits containing a limiting area, coverages not in 4326 are not properly cut.
The limited area is properly reprojected when handling vector layers, but not when handling coverages.
https://osgeo-org.atlassian.net/browse/GEOS-9559
- [-] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [-] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.
Submitting the PR does not …
> [Backport to 2.17.x][GEOS-9559] GeofenceAccessManager fails to cut geometries in coverages (2.17.x)

- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/AccessManagerTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/AccessManagerWMTSLayerTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/CacheReaderTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/GeofenceBaseTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/ServicesTest.java
- src/extension/geofence/src/test/java/org/geoserver/geoserver/authentication/filter/GeofenceFilterConfigTest.java
GeofenceAccessManager fails to cut geometries in coverages
When Geofence returns limits containing a limiting area, coverages not in 4326 are not properly cut.
The limited area is properly reprojected when handling vector layers, but not when handling coverages.
https://osgeo-org.atlassian.net/browse/GEOS-9559
Tests were not passing.
Most of them are integration tests, and were not run since long. 
Old tests were fixed, new test has been added.
- [-] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [-] Commits changing the REST API, or any configuration …
> [Backport to 2.16.x][GEOS-9559] GeofenceAccessManager fails to cut geometries in coverages (2.16.x)

- src/community/taskmanager/core/bin/pom.xml
- src/extension/geofence/pom.xml
- src/pom.xml
As part of the [ongoing repository migration](https://trac.osgeo.org/osgeo/ticket/2410), the main GeoServer pom needs to be updated with the new repo. 
See GeoServer [Migrate to OSGeo Infrastructure](https://github.com/geoserver/geoserver/wiki/Migrate-to-OSGeo-Infrastructure) wiki page for details.
I've tested locally, seems to be working.
> [GEOS-9566] Switch from repo.boundlessgeo.com to repo.osgeo.org

- build/build_release.sh
Use build_release to update documentation pom.xml version
> Use build_release to update documentation pom.xml version

- src/release/ext-authkey.xml
- src/release/ext-cas.xml
- src/release/ext-css.xml
Based on review of 2.17.0 plugin contents.
> Fix license details for authkey, cas and css plugins

- src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/ImportController.java
It was reporting the datastore name instead of the workspace name
> [GEOS-9572] Importer logs incorrectly when workspace is wrong

- src/community/csw-iso/src/main/java/org/geoserver/csw/records/iso/MetaDataDescriptor.java
The wrong xsd file is used to start parsing the gmd scheme, which causes issues when that same scheme is used by mapping files in app-schema, with elements missing.
> CSW-iso (community module): fix gmd scheme

- doc/en/user/source/community/jdbcconfig/configuration.rst
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/JDBCGeoServerLoader.java
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/DbMappings.java
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/JDBCConfigProperties.java
https://osgeo-org.atlassian.net/browse/GEOS-9603
Adds a feature to jdbcconfig to repopulate all the queryable properties in the database.
This can be used if you want to manually add a queryable property to the database. For example, the metadata module allows any number of custom attributes to be added to layers. For efficiency reasons you might want to make one of them queryable.
> [GEOS-9603] JDBCConfig (community module): repopulate

- src/restconfig/src/main/java/org/geoserver/rest/catalog/FeatureTypeController.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/FeatureTypeControllerTest.java
Backport #3794, for some reason missed to backport to 2.16.x at the time, and backported only to 2.15.x, and missed the 2.16.2 release timeframe. Adding for completeness.
> [Backport 2.16.x] [GEOS-9190]: Unable to create feature type through REST if two stores on different workspaces have the same name

- doc/en/developer/source/policies/gsip.rst
- doc/en/developer/source/policies/gsip_template.txt
- doc/en/developer/source/policies/gsip_voting.txt
- doc/en/developer/source/policies/psc.rst
See [GSIP-190](https://github.com/geoserver/geoserver/wiki/GSIP-190) for policy change:
> Assume +0 vote after 10 days
It has been some time since these pages were updated:
> [GSIP-190] assume +0 vote after 10 days

- src/restconfig/src/main/java/org/geoserver/rest/catalog/FeatureTypeController.java
This is a very minor change, with only affect that there is no unnecessary stacktrace logged when you use REST to publish an app-schema layer.
Difficult to test, because effect is only in logging (it /does/ move on and work otherwise).
Didn't make jira issue because of how trivial this is / no new features or bug fixed.
> REST FeatureType: use qualified name to get source

- src/web/core/src/main/java/org/geoserver/web/js/jquery.fullscreen.js
This change prevents the JavaScript error:
Uncaught TypeError: Cannot set property 'disabled' of null
at resizeStylePage (VM840 jquery.fullscreen-ver-D69DCBA0FF6B036BBEEE78538C81855F.js:22)
when resizing the web admin gui.
Submitting the PR does not require you to check all items, but by the time …
> [GEOS-9626] FIX Uncaught TypeError: Cannot set property 'disabled' of null

- doc/en/user/source/data/database/oracle.rst
- src/community/importer-jdbc/pom.xml
- src/community/jdbcconfig/pom.xml
- src/community/wps-jdbc/pom.xml
- src/extension/app-schema/app-schema-oracle-test/pom.xml
- src/extension/app-schema/app-schema-test/pom.xml
- src/extension/importer/core/pom.xml
- src/extension/oracle/pom.xml
- src/pom.xml
- src/release/OracleFUTC.txt
- src/release/ext-oracle.xml
- src/release/extensions/oracle/oracle-readme.txt
- src/web/app/pom.xml
Upgrade the Oracle JDBC driver to the latest version hosted on Maven Central, add the "Oracle Free Use Terms and Conditions" (FUTC), remove the now defunct `oracleDriver` profile
see:
- [GEOS-9535](https://osgeo-org.atlassian.net/browse/GEOS-9535)
- https://github.com/geotools/geotools/pull/2832
Submitting the PR does not require you to check all items, but by the time it …
> GEOS-9535 Update Oracle JDBC driver

- src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/CRSRequestHandler.java
- src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/GridGeometryProvider.java
- src/community/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
[GEOS-9583] DownloadProcess can return data with inaccurate bboxes wh…
> [2.17.x backport] DownloadProcess can return data with inaccurate bboxes when querying heterogeneous CRS mosaics

- src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/VectorTileMapOutputFormat.java
- src/extension/vectortiles/src/test/java/org/geoserver/wms/vector/VectorTileMapOutputFormatTest.java
This fixes an issue with oversampling (default is 16*) and the "extra" buffer around the tile to account for "wide" styles.  Before, it wasn't taking into account the oversampling, which meant the buffer was too small.
> [GEOS-9627] vector tiles - buffer around tile is too small

- doc/en/user/source/community/json-ld/configuration.rst
- src/community/json-ld/pom.xml
- src/community/json-ld/src/main/java/org/geoserver/jsonld/JsonLdGenerator.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/AbstractJsonBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/SourceBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/impl/CompositeBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/impl/DynamicValueBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/impl/IteratingBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/impl/RootBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/impl/StaticBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/configuration/JsonLdConfiguration.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/configuration/JsonLdTemplateReader.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/expressions/JsonLdCQLManager.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/expressions/JsonLdCqlManager.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/request/JsonLdPathVisitor.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/request/JsonLdTemplateCallBackOGC.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/validation/JsonLdValidator.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/validation/ValidateExpressionVisitor.java
- src/community/json-ld/src/test/java/org/geoserver/jsonld/response/JSONLDComplexTestSupport.java
- src/community/json-ld/src/test/java/org/geoserver/jsonld/response/JSONLDGetComplexFeaturesResponseFilteringTest.java
- src/community/json-ld/src/test/java/org/geoserver/jsonld/response/JSONLDGetComplexFeaturesResponseTest.java
- src/community/json-ld/src/test/resources/org/geoserver/jsonld/response/GeologicUnitDynamicStaticFilter.json
- src/community/json-ld/src/test/resources/org/geoserver/jsonld/response/MappedFeatureIteratingAndCompositeFilter.json
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9625
This pull request add filtering capabilities in the Json-ld  module to have control over the final output.
Supported syntax is the following:
- Arrays below the source attribute, `"$filter":"{some filter}"`
- Object below the source attribute, `"$filter":"{some filter}"`
- Attribute before the static or dynamic attribute: `"key": "$filter{some filter},"static value or expression"` …
> [GEOS-9625] Add filtering support in json-ld module

- src/release/bin/startup.bat
See mailing list topic https://sourceforge.net/p/geoserver/mailman/message/37027845/.
Fix works for me with system java located at:
C:\Program Files\AdoptOpenJDK\jdk-11.0.5.10-hotspot\bin\java.exe
Should be safe to backport into 2.17.1 release.
> Startup.bat: detect java from "Program Files"

- doc/en/developer/source/release-guide/index.rst
Minor change to release instructions.
> Reminder to update LDAP_SERVER_PORT in release guide

- doc/en/user/source/data/database/oracle.rst
- src/community/importer-jdbc/pom.xml
- src/community/jdbcconfig/pom.xml
- src/community/wps-jdbc/pom.xml
- src/extension/app-schema/app-schema-oracle-test/pom.xml
- src/extension/app-schema/app-schema-test/pom.xml
- src/extension/importer/core/pom.xml
- src/extension/oracle/pom.xml
- src/pom.xml
- src/release/OracleFUTC.txt
- src/release/ext-oracle.xml
- src/release/extensions/oracle/oracle-readme.txt
- src/web/app/pom.xml
backports #4119
see also: https://osgeo-org.atlassian.net/browse/GEOS-9535?focusedCommentId=81482
checked contents of file `geoserver-2.17-SNAPSHOT-oracle-plugin.zip`
which is as expected
> [2.17.x backport][GEOS-9535] Update Oracle JDBC driver

- src/community/geopkg/src/test/java/org/geoserver/geopkg/GeoPackageMimeTypeTest.java
- src/community/geopkg/src/test/java/org/geoserver/geopkg/wps/gs/GeoPackageProcessTest.java
- src/wfs/src/main/java/org/geoserver/wfs/FeatureBoundsFeatureCollection.java
A couple of tests are failing in the geopkg community module (hosting the WMS/WFS/WPS output formats generating GeoPackages). This PR restores the build in that module.
> Make geopkg community module tests pass again

- src/pom.xml
Update Spring Framework from 5.1.14 to 5.1.16 and update Spring Security from 5.1.9 to 5.1.11.
Resolves CVE-2020-5408: Dictionary attack with Spring Security queryable text encryptor .Geoserver seems not te be vulnerable as there is no use of `Encryptors#queryableText(CharSequence, CharSequence)`
- https://github.com/spring-projects/spring-framework/releases/tag/v5.1.16.RELEASE
- https://github.com/spring-projects/spring-framework/releases/tag/v5.1.15.RELEASE
- https://github.com/spring-projects/spring-security/releases/tag/5.1.11.RELEASE
- https://github.com/spring-projects/spring-security/releases/tag/5.1.10.RELEASE
- https://osgeo-org.atlassian.net/browse/GEOS-9650
- https://github.com/GeoWebCache/geowebcache/pull/857
- https://tanzu.vmware.com/security/cve-2020-5408
> Reviewing is a …
> [GEOS-9650] Update spring-security to 5.1.11 and spring-framework to 5.1.16

- .travis.yml
There seems to be a typo here, assuming these directories should not be part of the cache which is why they are deleted
see also: https://docs.travis-ci.com/user/caching#before_cache-phase
backports #4320
> [2.17.x backport] Fix a typo in before caching on travis

- .travis.yml
There seems to be a typo here, assuming these directories should not be part of the cache which is why they are deleted
see also: https://docs.travis-ci.com/user/caching#before_cache-phase
backports #4320
> [2.16.x backport] Fix a typo in before caching on travis

- src/community/json-ld/src/main/java/org/geoserver/jsonld/JsonLdGenerator.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/AbstractJsonBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/SourceBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/impl/DynamicValueBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/configuration/JsonLdConfiguration.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/configuration/JsonLdTemplateReader.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/request/JsonLdPathVisitor.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/request/JsonLdTemplateCallback.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/response/JSONLDGetFeatureResponse.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/validation/JsonLdValidator.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/validation/ValidateExpressionVisitor.java
- src/community/json-ld/src/test/java/org/geoserver/jsonld/response/JSONLDComplexTestSupport.java
- src/community/json-ld/src/test/java/org/geoserver/jsonld/response/JSONLDGetComplexFeaturesResponseTest.java
- src/community/json-ld/src/test/resources/org/geoserver/jsonld/response/FirstParentFeature_invalid.json
- src/community/json-ld/src/test/resources/org/geoserver/jsonld/response/GeoLogicUnit_invalid.json
- src/community/json-ld/src/test/resources/org/geoserver/jsonld/response/MappedFeature.json
JIRA Ticket https://osgeo-org.atlassian.net/browse/GEOS-9656
This pr fixes bugs on json-ld validation that prevent the validation process to consistely or entirely validate the json-ld template.
Moreover there are some fixes on qa failings highlighted during the attempted backport to 2.16.x of this pr https://github.com/geoserver/geoserver/pull/4248.
The …
> [GEOS-9656] JSON-LD validation will not try to validate the entire template

- src/pom.xml
backports #4313
Update Spring Framework from 5.1.14 to 5.1.16 and update Spring Security from 5.1.9 to 5.1.11.
- https://github.com/spring-projects/spring-framework/releases/tag/v5.1.16.RELEASE
- https://github.com/spring-projects/spring-framework/releases/tag/v5.1.15.RELEASE
- https://github.com/spring-projects/spring-security/releases/tag/5.1.11.RELEASE
- https://github.com/spring-projects/spring-security/releases/tag/5.1.10.RELEASE
- https://osgeo-org.atlassian.net/browse/GEOS-9650
- https://github.com/GeoWebCache/geowebcache/pull/857
- https://tanzu.vmware.com/security/cve-2020-5408
> [2.16.x backport] [GEOS-9650] Update spring-security to 5.1.11 and spring-framework to 5.1.16

- src/pom.xml
backports #4313
Update Spring Framework from 5.1.14 to 5.1.16 and update Spring Security from 5.1.9 to 5.1.11.
- https://github.com/spring-projects/spring-framework/releases/tag/v5.1.16.RELEASE
- https://github.com/spring-projects/spring-framework/releases/tag/v5.1.15.RELEASE
- https://github.com/spring-projects/spring-security/releases/tag/5.1.11.RELEASE
- https://github.com/spring-projects/spring-security/releases/tag/5.1.10.RELEASE
- https://osgeo-org.atlassian.net/browse/GEOS-9650
- https://github.com/GeoWebCache/geowebcache/pull/857
- https://tanzu.vmware.com/security/cve-2020-5408
> [2.17.x backport] [GEOS-9650] Update spring-security to 5.1.11 and spring-framework to 5.1.16

- doc/en/developer/source/release-guide/index.rst
- src/security/ldap/src/test/java/org/geoserver/security/ldap/LDAPAuthenticationProviderTest.java
- src/security/ldap/src/test/java/org/geoserver/security/ldap/LDAPBaseTest.java
- src/security/ldap/src/test/java/org/geoserver/security/ldap/LDAPRoleServiceTest.java
- src/security/ldap/src/test/java/org/geoserver/security/ldap/LDAPTestUtils.java
- src/security/ldap/src/test/java/org/geoserver/security/ldap/LDAPUserGroupServiceTest.java
- src/web/security/ldap/src/test/java/org/geoserver/web/security/ldap/LDAPAuthProviderPanelTest.java
- src/web/security/ldap/src/test/java/org/geoserver/web/security/ldap/LDAPRoleServicePanelTest.java
- src/web/security/ldap/src/test/java/org/geoserver/web/security/ldap/LDAPUserGroupServicePanelTest.java
This PR makes LDAP testing use a random port instead a fixed one.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9644
> [GEOS-9644] Make LDAP testing use random port

- src/ows/src/main/java/org/geoserver/ows/kvp/URLKvpParser.java
- src/ows/src/test/java/org/geoserver/ows/kvp/URLKvpParserTest.java
> [2.17.x backport][GEOS-9539] URLKvpParser encodes urls also when not needed + System variable for legacy behaviour

- src/ows/src/main/java/org/geoserver/ows/kvp/URLKvpParser.java
- src/ows/src/test/java/org/geoserver/ows/kvp/URLKvpParserTest.java
> [2.16.x backport] [GEOS-9539] URLKvpParser encodes urls also when not needed + System variable for legacy behaviour

- doc/en/user/source/services/wms/vendor.rst
See https://sourceforge.net/p/geoserver/mailman/message/37050631/
I do not know why Edit in GitHub also re-created the last line "Currently this parameter is ignored for layers with Complex features."
> Correct format option "antialising"->"antialias"

- src/pom.xml
Remove double-specified org.geotools.jdbc:gt-jdbc-h2:${gt.version} which is specified on both line 279 as well as line 355
This will clear up the warning from maven on building:
```
[WARNING] Some problems were encountered while building the effective model for org.geoserver:gs-platform:jar:2.18-SNAPSHOT
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.geotools.jdbc:gt-jdbc-h2:jar -> duplicate declaration of version ${gt.version} @ org.geoserver:geoserver:2.18-SNAPSHOT, /home/travis/build/geoserver/geoserver/src/pom.xml, line 353, column 16
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.geoserver:geoserver:pom:2.18-SNAPSHOT
[WARNING] …
```
> Remove double-specified org.geotools.jdbc:gt-jdbc-h2 from dependencyManagement

- src/main/src/main/java/org/geoserver/util/NearestMatchFinder.java
- src/wms/src/test/java/org/geoserver/wms/dimension/VectorTimeDimensionDefaultValueTest.java
- src/wms/src/test/resources/org/geoserver/wms/dimension/TimeElevationTruncated.properties
This PR introduces a fix for a NullPointerException got when using Nearest Match on time dimension.
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-9482
> [GEOS-9482] Nearest Match NPE if source database table is empty

- src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/LayerEditCacheOptionsTabPanelInfo.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/LayerEditCacheOptionsTabPanelInfoTest.java
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-6467
This pr fixes a bug caused by wicket model creation overriding caching enable parameter with true, everytime layer configuration page is accesed.
> [GEOS-6467] UI bug in disabling tile caching for layers

- src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/LayerEditCacheOptionsTabPanelInfo.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/LayerEditCacheOptionsTabPanelInfoTest.java
> [2.17.x backport][GEOS-6467] UI bug in disabling tile caching for layers

- src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/LayerEditCacheOptionsTabPanelInfo.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/LayerEditCacheOptionsTabPanelInfoTest.java
> [2.16.x backport][GEOS-6467] UI bug in disabling tile caching for layers

- src/wms/src/main/java/org/geoserver/wms/NearestMatchFinder.java
- src/wms/src/test/java/org/geoserver/wms/dimension/VectorTimeDimensionDefaultValueTest.java
- src/wms/src/test/resources/org/geoserver/wms/dimension/TimeElevationTruncated.properties
This PR introduces a fix for a NullPointerException got when using Nearest Match on time dimension.
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-9482
> [2.16.x backport][GEOS-9482] Nearest Match NPE if source database table is empty

- src/main/src/main/java/org/geoserver/util/NearestMatchFinder.java
- src/wms/src/test/java/org/geoserver/wms/dimension/VectorTimeDimensionDefaultValueTest.java
- src/wms/src/test/resources/org/geoserver/wms/dimension/TimeElevationTruncated.properties
This PR introduces a fix for a NullPointerException got when using Nearest Match on time dimension.
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-9482
> [2.17.x backport][GEOS-9482] Nearest Match NPE if source database table is empty

- src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java
- src/main/src/main/java/org/vfny/geoserver/util/DataStoreUtils.java
- src/web/core/src/main/java/org/geoserver/web/wicket/SRSProvider.java
- src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9680
This pr fixes a bug on WMTS configuration SRS display. In the otherSRS panel where displayed srs with the urn format elided
and EPSG:4326 was added even if not supported.
> [GEOS-9680] WMTS othersSrs always add EPSG:4326 and shows wrong CRS code

- .github/workflows/macos.yml
- .github/workflows/windows.yml
- src/extension/wps/wps-core/pom.xml
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/ImportProcessTest.java
- src/gwc/src/main/java/org/geoserver/gwc/GWC.java
- src/gwc/src/test/java/org/geoserver/gwc/ConfigurableBlobStoreTest.java
- src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
- src/main/src/test/java/org/geoserver/security/GeoServerSecurityTestSupport.java
- src/main/src/test/java/org/geoserver/test/GeoServerBaseTestSupport.java
- src/security/security-tests/pom.xml
- src/security/security-tests/src/test/java/org/geoserver/security/GroupAdminServiceTest.java
- src/web/security/core/pom.xml
We tried to reproduce these tests locally, failing to do so.
The continous presence of red x failures makes any other new regression
ignored, which defeats the purpose of having these builds (cover the
OSs that we do not have dedicated maintainers for, and alert us of
regressions).
Added a fix for a legit failure in GWC, it's a test design issue, it was checking no tasks were left pending, but did not check if there was any left running. …
> Skipping tests failing on Windows and OSX, but only on the PR checks.

- src/wms/src/main/java/org/geoserver/wms/RasterCleaner.java
- src/wms/src/test/java/org/geoserver/wms/map/MetaTileOutputFormatTest.java
- src/wms/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Fixes a memory issue when a `RenderedImageAdapter` image (output of `PlanarImage.wrapRenderedImage(metaTile)`) is added to the `RasterCleaner`. This results in the image reader `dispose()` method not being called in `ImageUtils` since the image will not be of type `RenderedOp`. A conditional has been added to extract the `RenderedImageTimeDecorator` from the wrapped image.
A unit test has been added which shows that the reader is not being disposed when `RasterCleaner` is used with a `RenderedImageAdapter`. …
> [GEOS-9667] GDAL Store memory management

- src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogStylesFileHandler.java
During my debug, I found loader (an object of GeoServerResourceLoader) will return the relative path when the style inside existing workspaces, and will start with workspaces. This will result in styleAbsolutePath.indexOf("workspaces")==0, but the code on line 5 will ignore this situation. So that, the result is when sync the style inside existing workspaces, the sld file will be synced to the root directory of styles. Eventually it will cause that the slave cannot see the sld file.
> GEOS-9425 fix the bug: sync the style inside existing workspaces, the slave will cannot see the sld file.

- doc/en/user/source/tutorials/GetFeatureInfo/html.rst
- src/wms/src/main/java/org/geoserver/wms/featureinfo/FreeMarkerTemplateManager.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/FreemarkerStaticsAccessRule.java
- src/wms/src/test/java/org/geoserver/wms/featureinfo/FreemarkerStaticsAccessRuleTest.java
- src/wms/src/test/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormatTest.java
- src/wms/src/test/resources/org/geoserver/wms/featureinfo/test_custom_static_content.ftl
- src/wms/src/test/resources/org/geoserver/wms/featureinfo/test_custom_static_content_specified.ftl
PR enable the usage of static methods in GetFeatureInfo HTML templates as requested by [GEOS-9657](https://osgeo-org.atlassian.net/browse/GEOS-9657).
> [GEOS-9657] Allow static method calls in GetFeatureInfo templates

- src/pom.xml
Reverting change so `xsd` is used as a library, simplify to accept transitive dependences from GeoTools `gt-xsd-core` (so we do not have the challenge of keeping these in sync over time resolving the original GEOS-9700 issue).
Modified https://github.com/geoserver/geoserver/pull/4419
> [GEOS-9700] Use EMF and XSD via GeoTools dependencies

- src/extension/web-resource/src/main/java/org/geoserver/web/resources/ResourceNode.java
- src/extension/web-resource/src/test/java/org/geoserver/web/resources/PageResourceBrowserTest.java
This PR fixes uses Base64 encoding for file paths that contain special characters that are not allowed in Wicket component IDs.
https://osgeo-org.atlassian.net/browse/GEOS-9545
> [GEOS-9545] Web Resource Page fails to load with WicketRuntimeException

- doc/en/user/source/data/database/postgis.rst
Adds documentation regarding jsonPointer function encoding to postgreSQL query.
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9696
> [GEOS-9696] Add documentation regarding JsonPointerFunction support

- doc/en/user/source/production/container.rst
- doc/en/user/source/production/java.rst
Taking discussion from https://github.com/geoserver/geoserver/pull/4243 into a pull request with concrete changes.
> Java 8 recommendation [GEOS-9619]

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NormalizedMultiValuesTest.java
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/measurements.xml
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/measurements.xsd
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/requests/station_tag_code_filter_wfs11.xml
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/requests/station_tag_code_filter_wfs20.xml
This PR provides testing for the fixed issue on App-Schema module not supporting jdbcMultipleValue mappings on Oracle database.
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-9075
> [2.17.x backport][GEOS-9075] Fix jdbc multi value support on Oracle database

- src/extension/web-resource/src/main/java/org/geoserver/web/resources/ResourceNode.java
- src/extension/web-resource/src/test/java/org/geoserver/web/resources/PageResourceBrowserTest.java
2.17.x backport for [GEOS-9545] Web Resource Page fails to load with WicketRuntimeException when a resource contains : or ~ in its name
> [2.17.x][GEOS-9545] Web Resource Page fails to load with WicketRuntimeException when a resource contains : or ~ in its name

- src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerMetaTile.java
- src/gwc/src/test/java/org/geoserver/gwc/layer/GeoServerTileLayerTest.java
Fixes very similar memory issue to https://osgeo-org.atlassian.net/browse/GEOS-9667 occuring when previewing a layer using geowebcache. 
This issue originates from the gs-gwc package, where the metatile `ImageReader` is not being disposed and `InputStream` is not being closed when of type `RenderedImageTimeDecorator`.  
Code has been added to `GeoServerMetaTile` to check if the `metaTileImage` is of type `RenderedImageTimeDecorator`. If it is, it sets `metaTileImage` to the delegate `RenderedOp` image. Two unit tests have been added to test firstly if the reader is disposed and secondly if the input stream is closed. 
Another patch is also needed in geowebcache to add the reader `dispose()` call as part of the `Metatile` disposal method. See …
> [GEOS-9684] Geowebcache layer preview memory issue

- src/community/script/py/src/misc/xml_values_replacer.py
xml_values_replacer.py - This script replaces the tile size (or other parameter) on all the layers of a selected workspace
I wrote it to workaround this bug: https://github.com/CesiumGS/cesium/issues/7994 but I guess it can be used for other purposes.
> a script that replaces the tile size (or other parameter) on all the layers of a selected workspace

- src/community/wfs3/src/main/java/org/geoserver/wfs3/response/GetFeatureMapboxOutputFormat.java
- src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/PipelineBuilder.java
- src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/VectorTileMapOutputFormat.java
- src/extension/vectortiles/src/test/java/org/geoserver/wms/vector/VectorTileMapOutputFormatTest.java
Hi, 
[following up the discussion from the users mailing list](http://osgeo-org.1560.x6.nabble.com/Pregeneralized-DataStore-and-Vector-tyle-td5437747.html)
The PR is a first draft just to show what is missing related to [GEOS-9633](https://osgeo-org.atlassian.net/browse/GEOS-9633?atlOrigin=eyJpIjoiMTA5YWFlMTBhN2MyNGNjNGI2NjM4YjE5NjJiNzE2ZTEiLCJwIjoiaiJ9) feel free to comment and share your thoughts.
I've started looking at org.geotools.renderer.lite.StreamingRenderer and most of the code comes from there, I've tryied to simplify it as much as possible removing features not strictly related to this feature.
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing …
> [GEOS-9633] Pregeneralized DataStore and Vector-tile

- src/community/pom.xml
The web-resource module graduated from community to extension at commit
583b0c52 but missed removing the web-resource maven profile from
community/pom.xml, which makes it imposible to build with
`mvn install -Pweb-resource` as maven complains there's no such module
(`org.geoserver.community:web-resource`).
**Submitting the PR does not require you to check all …
> Remove web-resource profile from community/pom.xml

- src/main/src/main/java/org/geoserver/catalog/CascadeDeleteVisitor.java
Delete LayerGroups first when deleting a WorkspaceInfo. Potentially
saves a bunch of unnecessary LayerGroup updates in the visitor chain
`Stores <- Resources <- Layers`, since `visit(LayerInfo layer)` will
update all the LayerGroups that reference the layer to then remove the
LayerGroup when `visit(WorkspaceInfo)` proceeds to it.
**Submitting the PR does not …
> CascadeDeleteVisitor.visit(WorkspaceInfo) small(ish) speed-up

- src/web/demo/src/main/java/org/geoserver/web/demo/PreviewLayer.java
- src/web/demo/src/test/java/org/geoserver/web/demo/MapPreviewPageTest.java
- src/web/demo/src/test/java/org/geoserver/web/demo/PreviewLayerProviderTest.java
JIRA issue: https://osgeo-org.atlassian.net/browse/GEOS-9646
Fix to: https://github.com/geoserver/geoserver/pull/4300
This PR fixes a new issue caused by the [[GEOS-9646] PR](https://github.com/geoserver/geoserver/pull/4300). It adds to the PreviewLayer WMS GetMap link the mandatory STYLES parameter. …
> [GEOS-9646]: INSPIRE validation get errors of GetMapRequest parameters (2)

- doc/en/user/source/community/wfs-templating/querying.rst
- src/community/wfs-templating/src/main/java/org/geoserver/wfstemplating/builders/AbstractTemplateBuilder.java
- src/community/wfs-templating/src/main/java/org/geoserver/wfstemplating/readers/JsonTemplateReader.java
- src/community/wfs-templating/src/main/java/org/geoserver/wfstemplating/request/JsonPathVisitor.java
- src/community/wfs-templating/src/main/java/org/geoserver/wfstemplating/validation/TemplateValidator.java
- src/community/wfs-templating/src/main/java/org/geoserver/wfstemplating/writers/CommonJsonWriter.java
- src/community/wfs-templating/src/test/java/org/geoserver/wfstemplating/response/FlatGeoJSONComplexFeaturesResponseTest.java
- src/community/wfs-templating/src/test/java/org/geoserver/wfstemplating/response/JSONLDGetComplexFeaturesResponseTest.java
- src/community/wfs-templating/src/test/java/org/geoserver/wfstemplating/writers/JsonWriterTest.java
- src/community/wfs-templating/src/test/resources/org/geoserver/wfstemplating/response/MappedFeature.json
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9731
This pull request:
- add the capability to handle with array in template in the form "array":["${xpath}","$${cql}",....]
- fix a small bug concering an error in the template writing process regarding URI and URL objects. …
> [GEOS-9731] Wfs-templating allow Iterating Builder to handle also json array without source

- src/main/pom.xml
- src/pom.xml
backports #4473 to 2.17.x
see also https://github.com/geotools/geotools/pull/3146
> [backport 2.17.x][GEOS-9309] Bump commons-beanutils from 1.9.2 to 1.9.4

- src/main/pom.xml
- src/pom.xml
backports #4473 to 2.18.x
see also https://github.com/geotools/geotools/pull/3145
> [backport 2.18.x][GEOS-9309] Bump commons-beanutils from 1.9.2 to 1.9.4

- src/wms/src/main/java/org/geoserver/wms/WMSWorkspaceQualifier.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapIntegrationTest.java
JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9729
- added rawKvp null check in WMSWorkspaceQualifier.java
- added unit test to assert WMS POST request with workspace qualifier in post URL …
> [GEOS-9729] WMS XML Post request fails with Workspace qualifier in url

- doc/en/user/source/community/wfs-templating/querying.rst
- src/community/wfs-templating/src/main/java/org/geoserver/wfstemplating/builders/AbstractTemplateBuilder.java
- src/community/wfs-templating/src/main/java/org/geoserver/wfstemplating/readers/JsonTemplateReader.java
- src/community/wfs-templating/src/main/java/org/geoserver/wfstemplating/request/JsonPathVisitor.java
- src/community/wfs-templating/src/main/java/org/geoserver/wfstemplating/validation/TemplateValidator.java
- src/community/wfs-templating/src/main/java/org/geoserver/wfstemplating/writers/CommonJsonWriter.java
- src/community/wfs-templating/src/test/java/org/geoserver/wfstemplating/response/FlatGeoJSONComplexFeaturesResponseTest.java
- src/community/wfs-templating/src/test/java/org/geoserver/wfstemplating/response/JSONLDGetComplexFeaturesResponseTest.java
- src/community/wfs-templating/src/test/java/org/geoserver/wfstemplating/writers/JsonWriterTest.java
- src/community/wfs-templating/src/test/resources/org/geoserver/wfstemplating/response/MappedFeature.json
* [GEOS-9731] Wfs-templating allow Iterating Builder to handle also json array without source
* reviewer's suggestion applied
The following are required only for core and extension modules (they …
> [2.17.x backport] [GEOS-9731] Wfs-templating allow Iterating Builder to handle also json array without source

- doc/en/user/source/community/features-templating/configuration.rst
- doc/en/user/source/community/features-templating/output.rst
- doc/en/user/source/community/geopkg/output.rst
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/BuilderFactory.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/AttributeNameHelper.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/FlatCompositeBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/FlatDynamicBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/FlatIteratingBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/FlatStaticBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/geojson/GeoJsonRootBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/impl/RootBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/readers/JsonTemplateReader.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/writers/CommonJsonWriter.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/writers/GeoJsonWriter.java
- src/community/features-templating/src/test/java/org/geoserver/featurestemplating/response/FlatGeoJSONComplexFeaturesResponseTest.java
- src/community/features-templating/src/test/resources/org/geoserver/featurestemplating/response/FlatGeoJSONMappedFeature.json
- src/community/features-templating/src/test/resources/org/geoserver/featurestemplating/response/FlatGeologicUnitWIthSeparator.json
- src/web/app/pom.xml
This pr add the possibilities to customize the separator for attribute names in geoJSON inspire output format, by means of a VendorOptions in the template file.
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9738
> [GEOS-9738] Add possibility to customize attributeName separator for GeoJSON INSPIRE output

- doc/en/user/source/community/features-templating/querying.rst
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/AttributeNameHelper.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/request/JsonPathVisitor.java
- src/community/features-templating/src/test/java/org/geoserver/featurestemplating/response/FlatGeoJSONComplexFeaturesResponseTest.java
- src/community/features-templating/src/test/java/org/geoserver/featurestemplating/response/JSONLDGetComplexFeaturesResponseTest.java
- src/community/features-templating/src/test/resources/org/geoserver/featurestemplating/response/FlatGeoJSONMappedFeature.json
This pr fixes an issue regarding backward mapping failure when a geoJSON template has a "_" separator in attribute names
JIRA ticket https://osgeo-org.atlassian.net/browse/GEOS-9739
> [GEOS-9739] Features-templating backwards mapping not working for geoJSON INSPIRE format with "_" separator

- src/web/demo/src/main/java/org/geoserver/web/demo/PreviewLayer.java
- src/web/demo/src/test/java/org/geoserver/web/demo/MapPreviewPageTest.java
- src/web/demo/src/test/java/org/geoserver/web/demo/PreviewLayerProviderTest.java
Backport to 2.18.x of https://github.com/geoserver/geoserver/pull/4456
This PR fixes a new issue caused by the [GEOS-9646] PR. It adds to the PreviewLayer WMS GetMap link the mandatory STYLES parameter.
> [2.18.x backport][GEOS-9646]: INSPIRE validation get errors of GetMapRequest parameters (2)

- .github/workflows/windows.yml
Add some options to close TCP connection for Maven, log with a timestamp so we can see if something stalled and update workflow items while here.
backports #4496
> [2.17.x backport] Update GH Windows workflow

- .github/workflows/windows.yml
Add some options to close TCP connection for Maven, log with a timestamp so we can see if something stalled and update workflow items while here.
backports #4496
> [2.18.x backport] Update GH Windows workflow

- doc/en/user/source/data/raster/imagemosaic/configuration.rst
Updating imageMosaic properties file with suggestedFormat property
> Minor update on imagemosaic doc (Follow up on GEOT-6694)

- doc/en/user/source/data/cascaded/wms.rst
- Inform users that WMS versions 1.1.1 and 1.3.0 are supported for cascading.
- Update the usage of URL field according to current behavior and add example URLs.
> Docs: Clarifications to WMS cascading

- src/web/core/src/main/java/org/geoserver/web/data/resource/BasicResourceConfig.java
- src/web/core/src/main/java/org/geoserver/web/wicket/CRSPanel.java
- src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
- src/web/core/src/test/resources/wfs_cap_110.xml
JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9758
- updated CRS panel class with new flag and constructor
- flag will bind the text field to SRS literals known to CRSPanel only
- updated existing unit test
For …
> [GEOS-9758] CRS Panel overrides URN SRS format with EPSG:XXXX format

- src/web/demo/src/main/java/org/geoserver/web/demo/PreviewLayer.java
Use the held reference to `LayerInfo` inside `PreviewLayer.hasServiceSupport(String serviceName)` instead of re-loading
the layer from the `Catalog` on each call.
With 25 rows per page and 3 `CommonFormatLink` implementations available, it's 75 less queries to the Catalog.
The following are required only for core and extension modules (they are welcomed, …
> MapPreviewPage performance improvement with less catalog queries

- src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/GeoServerKeycloakFilter.java
- src/community/security/keycloak/src/test/java/org/geoserver/security/keycloak/GeoServerKeycloakFilterTest.java
This issue is referencing to this GeoServer-dev-mailing-list-post: http://osgeo-org.1560.x6.nabble.com/Keycloak-plugin-wrong-role-mapping-td5449169.html 
> [GEOS-9788] Keycloak-plugin wrong role mapping

- src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
- src/wfs/src/test/java/org/geoserver/wfs/json/GeoJSONTest.java
JIRA ticket https://osgeo-org.atlassian.net/browse/GEOS-9791
fix a bug causing the axis order switching to east-north not happening in geoJSON output collection's bbox, when the requested crs has north-east axis order.
> [GEOS-9791] GeoJSON bounding box axis order wrongly encoded when CRS axis order is NORTH-EAST

- src/pom.xml
Both of these have had some patch releases, so they should be updated.
```
com.oracle.database.jdbc:ojdbc8 ................. 19.7.0.0 -> 19.8.0.0
org.postgresql:postgresql ......................... 42.2.14 -> 42.2.18
```
backports #4573 to 2.18.x
resolves [GEOS-9793](https://osgeo-org.atlassian.net/browse/GEOS-9793)
see also https://github.com/geotools/geotools/pull/3208 (geotools 24.x PR)
> [2.18.x backport] [GEOS-9793] Update PostgreSQL (to 42.2.18) and Oracle (to 19.8.0.0) JDBC drivers

- src/pom.xml
Both of these have had some patch releases, so they should be updated.
```
com.oracle.database.jdbc:ojdbc8 ................. 19.7.0.0 -> 19.8.0.0
org.postgresql:postgresql ......................... 42.2.14 -> 42.2.18
```
backports #4573 to 2.17.x
resolves [GEOS-9793](https://osgeo-org.atlassian.net/browse/GEOS-9793)
see also https://github.com/geotools/geotools/pull/3209 (geotools 23.x PR)
> [2.17.x backport] [GEOS-9793] Update PostgreSQL (to 42.2.18) and Oracle (to 19.8.0.0) JDBC drivers

- src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
- src/wfs/src/test/java/org/geoserver/wfs/json/GeoJSONTest.java
> [2.18.x backport][GEOS-9791] GeoJSON bounding box axis order wrongly encoded when CRS axis order is NORTH-EAST

- src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
- src/wfs/src/test/java/org/geoserver/wfs/json/GeoJSONTest.java
> [2.17.x backport][GEOS-9791] GeoJSON bounding box axis order wrongly encoded when CRS axis order is NORTH-EAST

- src/gwc/src/test/java/org/geoserver/gwc/layer/DefaultTileLayerCatalogTest.java
Noticed random but frequent failures on this test, relaxed the timeouts a bit (they are a maximum wait time, won't slow the build on faster machines).
> Relax maximum wait time for events, the current short amount is causing failures on GitHub actions

- src/pom.xml
In the Jackson project the following CVE was fixed CVE-2020-25649 , as well as various bugfixes in the used libs. See: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10
resolves [GEOS-9840](https://osgeo-org.atlassian.net/browse/GEOS-9840)
Related GeoTools PR: https://github.com/geotools/geotools/pull/3266
The following are required only …
> [GEOS-9840] Update Jackson 2 libraries from 2.10.1 to 2.10.5 / 2.10.5.1

- src/pom.xml
In the Jackson project the following CVE was fixed CVE-2020-25649 , as well as various bugfixes in the used libs. See: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10
backports #4607, resolves [GEOS-9840](https://osgeo-org.atlassian.net/browse/GEOS-9840) for 2.17.5
Related GeoTools PR: https://github.com/geotools/geotools/pull/3276
> [2.17.x backport][GEOS-9840] Update Jackson 2 libraries from 2.10.1 to 2.10.5 / 2.10.5.1

- src/pom.xml
In the Jackson project the following CVE was fixed CVE-2020-25649 , as well as various bugfixes in the used libs. See: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10
backports #4607, resolves [GEOS-9840](https://osgeo-org.atlassian.net/browse/GEOS-9840) for 2.18.2
Related GeoTools PR: https://github.com/geotools/geotools/pull/3275
> [2.18.x backport][GEOS-9840] Update Jackson 2 libraries from 2.10.1 to 2.10.5 / 2.10.5.1

- src/pom.xml
Updating to imageio-ext 1.3.5 to get in a minor bug fix on COG urls parsing.
> Updating to imageio-ext 1.3.5

- src/extension/wps/web-wps/src/main/java/org/geoserver/wps/web/WPSExecuteTransformer.java
Cleanup of old code (ticket picked at random).
See https://osgeo-org.atlassian.net/browse/GEOS-6903
Note that there is still a dependency on hsqldb in wps-core (because of https://github.com/geoserver/geoserver/blob/master/src/extension/wps/wps-core/src/main/java/org/geoserver/wps/validator/MultiplicityValidator.java#L7). Happy to take hints on fixing that as a subsequent ticket - this only deals with web-wps.
- [N/A] New unit tests have been added covering the changes
- [N/A] Commits changing the …
> [GEOS-6903] Unwanted dependency on HSQLDB in gs-web-wps

- .github/workflows/linux.yml
Addressing warning from workflow action.
> clean up ~/.m2/repository artifacts

- doc/en/user/source/configuration/raster_access.rst
Adding doc for the max oversampling factor set with GEOT-6789
> [GEOT-6789]:Follow up on documentation for max oversampling

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/ConformanceClass.java
- src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/api/images/ImagesService.java
- src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/api/images/ConformanceTest.java
- src/community/ogcapi/ogcapi-tiled-features/src/main/java/org/geoserver/api/features/tiled/TiledFeaturesExtension.java
- src/community/ogcapi/ogcapi-tiled-features/src/test/java/org/geoserver/api/features/tiled/ConformanceTest.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TilesService.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/ConformanceTest.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/GetTileTest.java
The OGC API specs are pretty fluid, but it looks (from https://github.com/opengeospatial/ogcapi-tiles/issues/20 and https://github.com/opengeospatial/ogcapi-tiles/pull/24 amongst other places) like the conformance classes have `conf` rather than `req`. This PR updates the implementation to refer to common correctly.
I also had to add a bit of pixel tolerance to one test.
- [N/A] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and …
> update conformance statements

- src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendGraphicBuilder.java
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/BufferedImageLegendGraphicOutputFormatTest.java
According to my bug report [GEOS-9834](https://osgeo-org.atlassian.net/browse/GEOS-9834) I opened this pr to fix the scaling of the image.
> [GEOS-9834] GetLegendGraphic results in java.lang.NegativeArraySizeException or OutOfMemory

- doc/en/developer/source/policies/community-process.rst
https://osgeo-org.atlassian.net/browse/GEOS-9864
This PR documents the inclusion of major dependency upgrades in the definition of an API change for the purposes of backporting, to avoid breaking downstream projects when upgrading the minor version of a stable GeoTools branch. …
> [GEOS-9864] Include dependencies in definition of API change when backporting

- src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendGraphicBuilder.java
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/BufferedImageLegendGraphicOutputFormatTest.java
backporting #4606 fix for LegendGraphicBuilder style resizing issue [GEOS-9834]
> [Backport-2.18.x][GEOS-9834] GetLegendGraphic results in java.lang.NegativeArraySizeException or OutOfMemory

- src/community/release/ext-cog.xml
For some reason, the backport was missing that single dependency.
Fixing it.
> [GEOS-9867] Added missing dependency in community module, assembly descriptor

- .github/workflows/docs.yml
- .github/workflows/linux_jdk11.yml
- .github/workflows/linux_jdk8.yml
- .github/workflows/qa.yml
When migrating from Travis to GH actions, the Linux build was four jobs. However when one of those jobs fails for a transient issue (like a transfer problem from repo), all four jobs need to be restarted - you can't do just the failing one. That is annoying, but also runs the risk of using up more build time than we need to.
- [N/A] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [N/A] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [N/A] New unit tests have been added …
> ci: split linux build into separate jobs

- src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorServletRequest.java
- src/extension/monitor/core/src/test/java/org/geoserver/monitor/MonitorServletRequestTest.java
This pr fixes a bug in monitor plugin involving NPE when MaxBodiSize is set to unbounded
jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9880
> [GEOS-9880] Monitor plugin throws NPE when maxSize is set to unbound

- src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/RasterSymbolizerBuilder.java
- src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/ClassifierTest.java
fix a bug in the SldService causing an IndexOutOfBoundException when continuous and percentages options are both set to true.
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9881 
The …
> [GEOS-9881] SldService throws IndexOutOfBoundException when percentages and continuous parameters are both set to true

- src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/RasterSymbolizerBuilder.java
- src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/ClassifierTest.java
> [2.17.x backport][GEOS-9881] SldService throws IndexOutOfBoundException when percentages and continuous parameters are both set to true

- src/pom.xml
Spring has resolved CVE-2020-5421
resolves [GEOS-9884](https://osgeo-org.atlassian.net/browse/GEOS-9884), related GWC PR: https://github.com/GeoWebCache/geowebcache/pull/921
> [GEOS-9884] Update Spring to v5.1.20.RELEASE and Spring security to 51.13.RELEASE

- src/pom.xml
Spring has resolved CVE-2020-5421
backports #4687 to 2.18.x
related https://github.com/GeoWebCache/geowebcache/pull/922
> [2.18.x backport][GEOS-9884] Update Spring to v5.1.20.RELEASE and Spring security to 51.13.RELEASE

- src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorServletRequest.java
- src/extension/monitor/core/src/test/java/org/geoserver/monitor/MonitorServletRequestTest.java
> [2.17.x backport][GEOS-9880] Monitor plugin throws NPE when maxSize is set to unbound 

- src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorServletRequest.java
- src/extension/monitor/core/src/test/java/org/geoserver/monitor/MonitorServletRequestTest.java
> [2.18.x backport][GEOS-9880] Monitor plugin throws NPE when maxSize is set to unbound

- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/ogcapi/dggs/CollectionDocument.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIDispatcher.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AbstractCollectionDocument.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AbstractDocument.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AbstractHTMLMessageConverter.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/QueryablesDocument.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/SimpleHTTPMessageConverter.java
- src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/OGCApiTestSupport.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/CollectionDocument.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/FeatureTest.java
- src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/ogcapi/images/ImageListener.java
- src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/ogcapi/images/ImageListenerSupport.java
- src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/ogcapi/images/ImageResponseMessageConverter.java
- src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/ogcapi/images/ImagesAPIBuilder.java
- src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/ogcapi/images/ImagesCollectionDocument.java
- src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/ogcapi/images/ImagesService.java
- src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/ogcapi/images/ImagesTestSupport.java
- src/community/ogcapi/ogcapi-styles/src/main/java/org/geoserver/ogcapi/styles/StylesService.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/TiledCollectionDocument.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/TiledCollectionsDocument.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/TilesAPIBuilder.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/TilesDocument.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/TilesService.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/VectorLayerMetadata.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/VolatileGeoServerTileLayer.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/tiles/CollectionTest.java
Minor code cleanups:
- Fixes title issue in queryables for Tiles (also added unit test coverage for this)
- Updates some deprecated uses of `Stream.stream(Collection ...)`, and one use of `URLEncoder.encode(String)` (updated existing case too)
- Switches a few raw types to parameterised version.
- Fixes some documentation typos.
- Removes a couple of loggers on abstract base classes (which didn't need them directly) and adds one lower level logger
- Adds some final markers for methods called from constructors, and for a few private member variables.
- Renames a couple of variables that shadowed member variables.
- Removes an unneeded unboxing.
- Updates the license header on tiles VectorLayerMetadata to be GS GPL (was GeoTools LGPL)
The following are required only …
> ogcapi: fix deprecated usage, unchecked warnings, minor typos

- src/web/demo/src/main/java/org/geoserver/web/demo/KMLFormatLink.java
- src/web/demo/src/main/java/org/geoserver/web/demo/PreviewLayer.java
- src/web/demo/src/test/java/org/geoserver/web/demo/MapPreviewPageTest.java
See https://osgeo-org.atlassian.net/browse/GEOS-9459
Fixes broken KML preview link.
- [ X PR for bug fixes and small new features are presented as a single commit
- [N/A] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.
> [GEOS-9459] Layer preview in KML format broken in version 2.16

- src/community/monitor-hibernate/pom.xml
- src/extension/geofence-server/pom.xml
- src/pom.xml
Fix GeoFence dependencies in order to support JTS 1.17.
Long description:
Since GeoServer 2.17.3, JTS has been upgraded to 1.17.0
JTS 1.17 breaks API compatibility (see https://github.com/locationtech/jts/blob/master/doc/JTS_Version_History.md#api-changes-1).  
This break happens within the postgis driver for hibernate spatial 1.1.3.1 used by GeoFence.  
This means that if GeoFence runs as a standalone webapp, the JTS version will be the one declared within the GeoFence deps and everything will work. When GeoFence is run within GeoServer, it will use the GeoServer version, and hibernate spatial will break.
A new version of hibernate spatial (1.1.3.2) has been built with support to JTS 1.17.
Since GeoServer 2.17.x relies on GeoFence 2.4.6, a new release (2.4.6.1) has been done, using the …
> [2.17.x backport][GEOS-9897] JTS upgrade breaks geofence integration

- src/community/monitor-hibernate/pom.xml
- src/extension/geofence-server/pom.xml
- src/pom.xml
Fix GeoFence dependencies in order to support JTS 1.17.
Long description:
Since GeoServer 2.17.3, JTS has been upgraded to 1.17.0
JTS 1.17 breaks API compatibility (see https://github.com/locationtech/jts/blob/master/doc/JTS_Version_History.md#api-changes-1).  
This break happens within the postgis driver for hibernate spatial 1.1.3.1 used by GeoFence.  
This means that if GeoFence runs as a standalone webapp, the JTS version will be the one declared within the GeoFence deps and everything will work. When GeoFence is run within GeoServer, it will use the GeoServer version, and hibernate spatial will break.
A new version of hibernate spatial (1.1.3.2) has been built with support to JTS 1.17.
Since GeoServer 2.17.x and 2.18.x rely on GeoFence 2.4.6, a new release (2.4.6.1) has been done, …
> [2.18.x backport][GEOS-9897] JTS upgrade breaks geofence integration

- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/listener/RestoreJobExecutionListener.java
- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/processor/CatalogItemProcessor.java
- src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java
Restore process rewrites always a new Workspace and Namespace ID even if the same Workspace name and Namespace prefix already exists in the GeoServer catalog.  This broke some resources(stores and layers) linked by these IDs on partial restores.
This fix checks for existing Workspaces and Namespaces adding them with the same IDs to the resulting new catalog.
Jira issue:
https://osgeo-org.atlassian.net/browse/GEOS-9898
**Submitting the PR does not require you to check all items, but by the time it gets merged, they …
> [GEOS-9898] Make Restore process respect original workspaces IDs

- src/community/monitor-hibernate/pom.xml
- src/extension/geofence-server/pom.xml
- src/pom.xml
Fix GeoFence dependencies in order to support JTS 1.17.
Long description:
Since GeoServer 2.17.3, JTS has been upgraded to 1.17.0
JTS 1.17 breaks API compatibility (see https://github.com/locationtech/jts/blob/master/doc/JTS_Version_History.md#api-changes-1).  
This break happens within the postgis driver for hibernate spatial 1.1.3.1 used by GeoFence.  
This means that if GeoFence runs as a standalone webapp, the JTS version will be the one declared within the GeoFence deps and everything will work. When GeoFence is run within GeoServer, it will use the GeoServer version, and hibernate spatial will break.
A new version of hibernate spatial (1.1.3.2) has been built with support to JTS 1.17.
Since GeoServer 2.17.x and 2.18.x rely on GeoFence 2.4.6, a new release (2.4.6.1) has been done, …
> [GEOS-9897] JTS upgrade breaks geofence integration

- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/listener/RestoreJobExecutionListener.java
- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/processor/CatalogItemProcessor.java
- src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java
Restore process rewrites always a new Workspace and Namespace ID even if the same Workspace name and Namespace prefix already exists in the GeoServer catalog. This broke some resources(stores and layers) linked by these IDs on partial restores.
This fix checks for existing Workspaces and Namespaces adding them with the same IDs to the resulting new catalog.
Jira issue:
https://osgeo-org.atlassian.net/browse/GEOS-9898
**Submitting the PR does not require you to check all items, but by the time it gets merged, they …
> [2.17.x backport][GEOS-9898] Make Restore process respect original workspaces IDs

- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/listener/RestoreJobExecutionListener.java
- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/processor/CatalogItemProcessor.java
- src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java
Restore process rewrites always a new Workspace and Namespace ID even if the same Workspace name and Namespace prefix already exists in the GeoServer catalog. This broke some resources(stores and layers) linked by these IDs on partial restores.
This fix checks for existing Workspaces and Namespaces adding them with the same IDs to the resulting new catalog.
Jira issue:
https://osgeo-org.atlassian.net/browse/GEOS-9898
**Submitting the PR does not require you to check all items, but by the time it gets merged, they …
> [2.18.x backport][GEOS-9898] Make Restore process respect original workspaces IDs

- src/community/params-extractor/src/main/java/org/geoserver/params/extractor/UrlMangler.java
- src/community/params-extractor/src/test/java/org/geoserver/params/extractor/UrlManglerTest.java
> [2.17.x backport][GEOS-9911] Params-extractor plugin, wrong url in getCapabilities when having context with addition /

- src/community/params-extractor/src/main/java/org/geoserver/params/extractor/UrlMangler.java
- src/community/params-extractor/src/test/java/org/geoserver/params/extractor/UrlManglerTest.java
> [2.18.x backport][GEOS-9911] Params-extractor plugin, wrong url in getCapabilities when having context with addition /

- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/ogcapi/dggs/DGGSService.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/resources/org/geoserver/ogcapi/dggs/landingPage.ftl
- src/community/ogcapi/dggs/ogcapi-dggs/src/test/java/org/geoserver/ogcapi/dggs/ConformanceTest.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/test/java/org/geoserver/ogcapi/dggs/LandingPageTest.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/ConformanceDocument.java
- src/community/ogcapi/ogcapi-core/src/main/resources/org/geoserver/ogcapi/conformance.ftl
- src/community/ogcapi/ogcapi-core/src/main/resources/org/geoserver/ogcapi/landingpage-conformance.ftl
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/FeatureService.java
- src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/features/landingPage.ftl
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/ConformanceTest.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/LandingPageTest.java
- src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/ogcapi/images/ImagesService.java
- src/community/ogcapi/ogcapi-images/src/main/resources/org/geoserver/ogcapi/images/landingPage.ftl
- src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/ogcapi/images/ConformanceTest.java
- src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/ogcapi/images/LandingPageTest.java
- src/community/ogcapi/ogcapi-styles/src/main/java/org/geoserver/ogcapi/styles/StylesService.java
- src/community/ogcapi/ogcapi-styles/src/main/resources/org/geoserver/ogcapi/styles/landingPage.ftl
- src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/ogcapi/styles/ConformanceTest.java
- src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/ogcapi/styles/LandingPageTest.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/TilesService.java
- src/community/ogcapi/ogcapi-tiles/src/main/resources/org/geoserver/ogcapi/tiles/landingPage.ftl
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/tiles/ConformanceTest.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/tiles/LandingPageTest.java
Adds a HTML version of the conformance statement for various OGC API services, and links for the conformance page off the main landing page. Only affects community modules.
Includes tests.
- [N/A] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.
> add HTML conformance page for ogcapi implementations

- doc/en/user/source/extensions/cas/index.rst
This fixes the error shown below. Perhaps my sphinx is more picky than others
```
└─ $ ▶ which sphinx-build
/usr/bin/sphinx-build
└─ $ ▶ /usr/bin/sphinx-build --version
sphinx-build 1.8.5
```
```
sphinx:
[echo] Running sphinx-build -D release=2.19-SNAPSHOT -W -b html -d "/home/mark/dev/projects/geoserver/doc/en/target/user/doctrees" . "/home/mark/dev/projects/geoserver/doc/en/target/user/html"
[exec] /home/mark/dev/projects/geoserver/doc/en/user/source/community/wps-jdbc/index.rst:27: WARNING: Error in "code-block" directive:
[exec] 1 argument(s) required, 0 supplied.
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.101 s
[INFO] …
```
> fix a `code-block::` directive

- src/release/ext-db2.xml
- src/release/extensions/IBM-IPLA.txt
- src/release/extensions/db2/db2-readme.txt
backports #4763 to 2.18.x
depends on https://github.com/geotools/geotools/pull/3362
> [2.18.x backport][GEOS-9922] include Db2 JDBC driver dependency

- src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
Rename inner class `StoreContents` as `SingleResourceContents`, and use it
also for the async loading of styles and layer groups, so the log
message can include the resource name when an error occurrs loading them.
> Note no test case added, doesn't seem easily feasible to unit test a log message? …
> [GEOS-9920] Log resource name when failing to load a style or layer group

- src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
2.18.x backport of #4758
Rename inner class `StoreContents` as `SingleResourceContents`, and use it
also for the async loading of styles and layer groups, so the log
message can include the resource name when an error occurrs loading them.
> Note no test case added, doesn't seem easily feasible to unit test a log message?
The following are required only …
> [backport 2.18.x][GEOS-9920] Log resource name when failing to load a style or layer group

- src/wms/src/main/java/org/geoserver/wms/map/RenderedImageMapOutputFormat.java
- src/wms/src/test/java/org/geoserver/wms/map/RenderedImageMapOutputFormatTest.java
When GetMap fails due to timeout, max error count reached, or other
non-ignorable exception, include the requested layer names in the error
message.
This exceptions get logged and otherwise it's difficult for an admin to
figure out which layers are causing trouble.
The following are required only for core and extension modules (they are welcomed, but …
> [GEOS-9921] Include layer name(s) in WMS ServiceException

- doc/en/user/source/configuration/globalsettings.rst
- src/community/backup-restore/extension/src/main/java/org/geoserver/backuprestore/imagemosaic/reader/ImageMosaicAdditionalResourceReader.java
- src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/GeoServerKeycloakFilterConfig.java
- src/extension/authkey/src/main/java/org/geoserver/security/AuthenticationKeyFilterConfig.java
- src/extension/authkey/src/test/java/org/geoserver/security/AuthKeyAuthenticationTest.java
- src/gwc/src/main/java/org/geoserver/gwc/GWC.java
- src/gwc/src/test/java/org/geoserver/gwc/GWCTest.java
- src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
- src/main/src/main/java/org/geoserver/ows/ProxifyingURLMangler.java
- src/main/src/main/java/org/geoserver/security/config/BaseSecurityNamedServiceConfig.java
- src/main/src/main/java/org/geoserver/security/config/BruteForcePreventionConfig.java
- src/main/src/main/java/org/geoserver/security/config/SecurityManagerConfig.java
- src/main/src/main/java/org/geoserver/security/password/MasterPasswordConfig.java
- src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java
- src/main/src/test/java/org/geoserver/ows/URLManglersTest.java
- src/main/src/test/resources/geoserver-environment.properties
- src/platform/src/main/java/org/geoserver/platform/GeoServerEnvironment.java
- src/platform/src/test/java/org/geoserver/platform/GeoServerEnvironmentTest.java
- src/platform/src/test/java/org/geoserver/platform/SystemEnvironmentTest.java
- src/security/security-tests/src/test/java/org/geoserver/security/GeoServerSecurityManagerTest.java
- src/web/core/src/main/java/org/geoserver/web/data/store/DefaultDataStoreEditPanel.java
- src/web/core/src/main/java/org/geoserver/web/data/store/WMSStoreNewPage.java
- src/web/core/src/main/java/org/geoserver/web/data/store/WMTSStoreNewPage.java
- src/web/core/src/main/java/org/geoserver/web/data/workspace/WorkspaceEditPage.java
- src/web/core/src/main/java/org/geoserver/web/services/BaseServiceAdminPage.java
Currently GeoServer Proxy Base setting doesn't handle environment parameters from geoserver-environment.properties configuration.  The target for this enhancement is to add support for ENV parameters in Proxy Base when ALLOW_ENV_PARAMETRIZATION system property is set to "true".
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-9894
The following …
> [GEOS-9894] Enable GeoServer environment parametrization in Base Proxy configuration

- src/wms/src/main/java/org/geoserver/wms/map/RenderedImageMapOutputFormat.java
- src/wms/src/test/java/org/geoserver/wms/map/RenderedImageMapOutputFormatTest.java
2.18.x backport of #4760
When GetMap fails due to timeout, max error count reached, or other
non-ignorable exception, include the requested layer names in the error
message.
This exceptions get logged and otherwise it's difficult for an admin to
figure out which layers are causing trouble.
The following are required only for core and extension modules …
> [backport 2.18.x][GEOS-9921] Include layer name(s) in WMS ServiceException for GetMap

- src/extension/netcdf-out/src/main/java/org/geoserver/wcs/responses/NetCDFCoverageResponseDelegate.java
- src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/WCSMultiDimSubsetTest.java
- src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/WCSNetCDFMosaicTest.java
- src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/WCSResponseInterceptor.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/GetCoverage.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/MultidimensionalCoverageResponse.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCSDimensionsSubsetHelper.java
- Fixing WCSDimensionSubsetHelper splitting request in nondeterministic order.
- also slightly modified the multidim capability check for easier testing
> [GEOS-9932]: Multidim-Dimensions subset split in nondeterministic order

- doc/en/user/source/configuration/globalsettings.rst
- src/community/backup-restore/extension/src/main/java/org/geoserver/backuprestore/imagemosaic/reader/ImageMosaicAdditionalResourceReader.java
- src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/GeoServerKeycloakFilterConfig.java
- src/extension/authkey/src/main/java/org/geoserver/security/AuthenticationKeyFilterConfig.java
- src/extension/authkey/src/test/java/org/geoserver/security/AuthKeyAuthenticationTest.java
- src/gwc/src/main/java/org/geoserver/gwc/GWC.java
- src/gwc/src/test/java/org/geoserver/gwc/GWCTest.java
- src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
- src/main/src/main/java/org/geoserver/ows/ProxifyingURLMangler.java
- src/main/src/main/java/org/geoserver/security/config/BaseSecurityNamedServiceConfig.java
- src/main/src/main/java/org/geoserver/security/config/BruteForcePreventionConfig.java
- src/main/src/main/java/org/geoserver/security/config/SecurityManagerConfig.java
- src/main/src/main/java/org/geoserver/security/password/MasterPasswordConfig.java
- src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java
- src/main/src/test/java/org/geoserver/ows/URLManglersTest.java
- src/main/src/test/resources/geoserver-environment.properties
- src/platform/src/main/java/org/geoserver/platform/GeoServerEnvironment.java
- src/platform/src/test/java/org/geoserver/platform/GeoServerEnvironmentTest.java
- src/platform/src/test/java/org/geoserver/platform/SystemEnvironmentTest.java
- src/security/security-tests/src/test/java/org/geoserver/security/GeoServerSecurityManagerTest.java
- src/web/core/src/main/java/org/geoserver/web/data/store/DefaultDataStoreEditPanel.java
- src/web/core/src/main/java/org/geoserver/web/data/store/WMSStoreNewPage.java
- src/web/core/src/main/java/org/geoserver/web/data/store/WMTSStoreNewPage.java
- src/web/core/src/main/java/org/geoserver/web/data/workspace/WorkspaceEditPage.java
- src/web/core/src/main/java/org/geoserver/web/services/BaseServiceAdminPage.java
Currently GeoServer Proxy Base setting doesn't handle environment parameters from geoserver-environment.properties configuration. The target for this enhancement is to add support for ENV parameters in Proxy Base when ALLOW_ENV_PARAMETRIZATION system property is set to "true".
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-9894
The following …
> [2.17.x backport][GEOS-9894] Enable GeoServer environment parametrization in Base Proxy configuration

- doc/en/user/source/configuration/globalsettings.rst
- src/community/backup-restore/extension/src/main/java/org/geoserver/backuprestore/imagemosaic/reader/ImageMosaicAdditionalResourceReader.java
- src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/GeoServerKeycloakFilterConfig.java
- src/extension/authkey/src/main/java/org/geoserver/security/AuthenticationKeyFilterConfig.java
- src/extension/authkey/src/test/java/org/geoserver/security/AuthKeyAuthenticationTest.java
- src/gwc/src/main/java/org/geoserver/gwc/GWC.java
- src/gwc/src/test/java/org/geoserver/gwc/GWCTest.java
- src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
- src/main/src/main/java/org/geoserver/ows/ProxifyingURLMangler.java
- src/main/src/main/java/org/geoserver/security/config/BaseSecurityNamedServiceConfig.java
- src/main/src/main/java/org/geoserver/security/config/BruteForcePreventionConfig.java
- src/main/src/main/java/org/geoserver/security/config/SecurityManagerConfig.java
- src/main/src/main/java/org/geoserver/security/password/MasterPasswordConfig.java
- src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java
- src/main/src/test/java/org/geoserver/ows/URLManglersTest.java
- src/main/src/test/resources/geoserver-environment.properties
- src/platform/src/main/java/org/geoserver/platform/GeoServerEnvironment.java
- src/platform/src/test/java/org/geoserver/platform/GeoServerEnvironmentTest.java
- src/platform/src/test/java/org/geoserver/platform/SystemEnvironmentTest.java
- src/security/security-tests/src/test/java/org/geoserver/security/GeoServerSecurityManagerTest.java
- src/web/core/src/main/java/org/geoserver/web/data/store/DefaultDataStoreEditPanel.java
- src/web/core/src/main/java/org/geoserver/web/data/store/WMSStoreNewPage.java
- src/web/core/src/main/java/org/geoserver/web/data/store/WMTSStoreNewPage.java
- src/web/core/src/main/java/org/geoserver/web/data/workspace/WorkspaceEditPage.java
- src/web/core/src/main/java/org/geoserver/web/services/BaseServiceAdminPage.java
Currently GeoServer Proxy Base setting doesn't handle environment parameters from geoserver-environment.properties configuration. The target for this enhancement is to add support for ENV parameters in Proxy Base when ALLOW_ENV_PARAMETRIZATION system property is set to "true".
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-9894
The following …
> [2.18.x backport][GEOS-9894] Enable GeoServer environment parametrization in Base Proxy configuration

- src/main/src/main/java/org/geoserver/template/FeatureWrapper.java
- src/main/src/main/java/org/geoserver/template/TemplateUtils.java
- src/pom.xml
- src/rest/src/main/java/org/geoserver/rest/IndexController.java
- src/rest/src/main/java/org/geoserver/rest/ObjectToMapWrapper.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/AboutStatusController.java
- src/web/wms/src/main/java/org/geoserver/wms/web/data/OpenLayersPreviewPanel.java
- src/wms/src/main/java/org/geoserver/wms/decoration/TextDecoration.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/FeatureTemplate.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/FreeMarkerTemplateManager.java
- src/wms/src/main/java/org/geoserver/wms/map/AbstractOpenLayersMapOutputFormat.java
- src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapOutputFormatTest.java
- src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapTemplateTest.java
Upgrades the freemarker library to the latest version. The planted a "bomb" in the 2.3.21 version that was difficult to figure out, a change in behavior that was meant to be an improvement, but turned out to be very damaging in GeoServer. Thankfully, once figured out the nature of the issue, it was not difficult to work around it.
The following are …
> [GEOS-9331] Upgrade Freemarker to 2.3.31

- src/main/src/main/java/org/geoserver/config/DefaultGeoServerLoader.java
- src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
- src/main/src/main/java/org/geoserver/config/GeoServerLoaderListener.java
- src/main/src/test/java/applicationContext.xml
- src/main/src/test/java/org/geoserver/config/GeoServerRootStartupTest.java
- src/main/src/test/java/org/geoserver/config/RootStartupListener.java
GeoServer is not Root/Admin during startup process, making it fails to load secured workspaces settings (WMS, WFS, ...).  Current workaround is to reload catalog from Admin user UI.  This PR introduces a fix to this issue, making GeoServer uses the root user and admin role during its startup loading process.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9928
For all …
> [GEOS-9928] Make GeoServer runs its startup loading process as root

- src/main/src/main/java/org/geoserver/config/DefaultGeoServerLoader.java
- src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
- src/main/src/main/java/org/geoserver/config/GeoServerLoaderListener.java
- src/main/src/test/java/applicationContext.xml
- src/main/src/test/java/org/geoserver/config/GeoServerRootStartupTest.java
- src/main/src/test/java/org/geoserver/config/RootStartupListener.java
GeoServer is not Root/Admin during startup process, making it fails to load secured workspaces settings (WMS, WFS, ...). Current workaround is to reload catalog from Admin user UI. This PR introduces a fix to this issue, making GeoServer uses the root user and admin role during its startup loading process.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9928
For all …
> [2.18.x backport][GEOS-9928] Make GeoServer runs its startup catalog loading process as root user

- src/web/wms/src/main/java/org/geoserver/wms/web/data/AbstractStylePage.java
- src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleComponentInfo.java
- src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleComponentBean.xml
- src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java
This adds a new entry point for extensions to be instantiated in the AbstractStylePage and thus get access to the style edit pages. For more information, see https://osgeo-org.atlassian.net/browse/GEOS-9927
> [GEOS-9927] Add StyleComponentInfo in AbstractStylePage

- src/release/ext-mapml.xml
- src/release/extensions/mapml/mapml-LICENSE.txt
I noticed that the gs-mapml*.jar was missing from the RC candidate, so I hope this change will get it in there.  I compared with another extension and this seems to be the way it is done.  
- [X ] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [X ] You have sent a Contribution …
> Change source directory for gs-mapml*.jar artifact in assembly

- doc/en/user/source/extensions/netcdf-out/nc4.rst
Fix a broken link in the docs for installing the native netcdf4 C libraries for the netcdf-out plugin.
> Fix broken links in docs for native netcdf4 docs

- doc/en/user/source/services/wfs/outputformats.rst
- doc/en/user/source/services/wfs/vendor.rst
- src/community/geopkg/src/main/java/org/geoserver/geopkg/GeoPackageGetFeatureOutputFormat.java
- src/community/geopkg/src/test/java/org/geoserver/geopkg/GeoPackageGetFeatureOutputFormatTest.java
- src/extension/dxf/core/src/main/java/org/geoserver/wfs/response/DXFOutputFormat.java
- src/extension/excel/src/main/java/org/geoserver/wfs/response/ExcelOutputFormat.java
- src/extension/ogr/ogr-wfs/src/main/java/org/geoserver/wfs/response/Ogr2OgrOutputFormat.java
- src/extension/xslt/src/main/java/org/geoserver/wfs/xslt/XSLTOutputFormat.java
- src/kml/src/main/java/org/geoserver/kml/WFSKMLOutputFormat.java
- src/wfs/src/main/java/org/geoserver/wfs/WFSGetFeatureOutputFormat.java
- src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
- src/wfs/src/main/java/org/geoserver/wfs/response/CSVOutputFormat.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/GML2OutputFormat.java
- src/wfs/src/test/java/org/geoserver/wfs/response/CSVOutputFormatTest.java
- src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureJoinTest.java
Changing this to a bug report where depending on the version of geoserver and output format used GML3 content showing up as ``geoserver-GetFeature.application`` or ``features.xml`` where I expect something based on the typename requested ``kust_1915.xml`` or ``kust_1915.gml``.
> [GEOS-9944] Revise generated filenames, extension, and format_option

- src/pom.xml
The Jetty project has resolved CVE-2020-27223
backports #4859 to 2.19.x
> [2.19.x backport][GEOS-9972] Update Jetty to 9.4.38.v20210224

- src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
- src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesLegendURLTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/LegendCapabilitiesTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/LegendCapabilitiesTest.java
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9726
Fixes a bug causing the legend width and height be always the default 20 in onlineResource element of getCapabilities, when dealing with static images.
Tests that were wrongly checking for the default value have been modified accordingly. …
> [GEOS-9726] External Legend Graphic reported size incorrect in WMS

- src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
- src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesLegendURLTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/LegendCapabilitiesTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/LegendCapabilitiesTest.java
* [GEOS-9726] External Legend Graphic reported size incorrect in WMS
* review feedback applied
The following are required only for core and extension modules (they are welcomed, but not …
> [2.19.x backport][GEOS-9726] External Legend Graphic reported size incorrect in WMS (#4864)

- src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
- src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesLegendURLTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/LegendCapabilitiesTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/LegendCapabilitiesTest.java
* [GEOS-9726] External Legend Graphic reported size incorrect in WMS
* review feedback applied
The following are required only for core and extension modules (they are welcomed, but not …
> [2.18.x backport][GEOS-9726] External Legend Graphic reported size incorrect in WMS (#4864)

- src/community/release/ext-cov-json.xml
[backport to 2.19.x] fixing assembly of cov-json plugin
> [2.19.x-backport] Fixing cov-json community zip

- src/ows/pom.xml
- src/platform/pom.xml
- src/pom.xml
[GEOS-9983](https://osgeo-org.atlassian.net/browse/GEOS-9983)
The root pom forces a number of transitive dependencies an all modules,
which prevents having modules that don't depend on spring-webmvc, or
gt-main, etc.
This is the list of changes required to remove those direct dependencies
forced by the root pom down to all modules (- is a dependency removed,
+ a dependency added):
```
* root:
- spring-beans
- spring-core
- spring-context
- spring-webmvc
- gt-main
* platform:
- spring-webmvc
+ spring-web
+ gt-metadata
* ows:
+ spring-webmvc
```
---
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you …
> [GEOS-9983] Sanitize transitive dependencies coming from root pom

- src/extension/importer/core/src/main/java/org/geoserver/importer/format/GMLFileFormat.java
- src/main/src/main/java/org/geoserver/catalog/SLDHandler.java
- src/ows/pom.xml
- src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
- src/ows/src/main/java/org/geoserver/ows/Request.java
- src/ows/src/main/java/org/geoserver/ows/util/RequestUtils.java
- src/ows/src/test/java/org/geoserver/ows/DispatcherTest.java
- src/pom.xml
- src/wfs/src/test/java/org/geoserver/wfs/v2_0/TransactionTest.java
Remove dependency on xpp3 and use the standard StAX API instead.
[xpp3](https://mvnrepository.com/artifact/xpp3/xpp3) is an XML pull parser. Last released version is 14 years old. The
JRE comes with a standard StAX pull parser since Java 1.6.
Relates to https://github.com/geotools/geotools/pull/3382
---
The following are required only for core and …
> [GEOS-9942] Remove dependency on xpp3, use standard StAX API

- .github/pr-badge.yml
[![GEOS-1](https://badgen.net/badge/JIRA/GEOS-1/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-1)
Hello 👋 
I've noticed that geoserver is heavily leveraging the JIRA issue tracker and most pull requests add a link to the related issue. You might be interested in the GitHub App I wrote to automate this process https://pullrequestbadge.com. 
If a pull request title or the branch name starts with an issue prefix e.g. `GEOS-123`, the [Pull Request Badge GitHub App](https://github.com/marketplace/pull-request-badge) does automatically insert a badge to the pull request descriptions based on the config provided in this pull request. 
Pull Request Badge is always free for public repositories. If you have any questions please let me know. 
1. Go to the [GitHub Marketplace …
> Add pullrequestbadge.com config

- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCSDimensionsSubsetHelper.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/xml/GetCoverageTest.java
- src/wcs2_0/src/test/resources/trimming/requestGetCoverageTrimmingSlicingNativeCRSXML.xml
[![GEOS-9991](https://badgen.net/badge/JIRA/GEOS-9991/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9991) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Fixing WCS 2.0 slicing on lat/lon sometime returning bad pixels …
> [GEOS-9991]: WCS 2.0 slicing lat/lon fix

- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCSDimensionsSubsetHelper.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/xml/GetCoverageTest.java
- src/wcs2_0/src/test/resources/trimming/requestGetCoverageTrimmingSlicingNativeCRSXML.xml
[![GEOS-9991](https://badgen.net/badge/JIRA/GEOS-9991/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9991) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [Backport-2.17.x][GEOS-9991]: WCS 2.0 slicing lat/lon fix

- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCSDimensionsSubsetHelper.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/xml/GetCoverageTest.java
- src/wcs2_0/src/test/resources/trimming/requestGetCoverageTrimmingSlicingNativeCRSXML.xml
[![GEOS-9991](https://badgen.net/badge/JIRA/GEOS-9991/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9991) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [Backport-2.19.x][GEOS-9991]: WCS 2.0 slicing lat/lon fix

- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCSDimensionsSubsetHelper.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/xml/GetCoverageTest.java
- src/wcs2_0/src/test/resources/trimming/requestGetCoverageTrimmingSlicingNativeCRSXML.xml
[![GEOS-9991](https://badgen.net/badge/JIRA/GEOS-9991/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9991) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [Backport 2.18.x][GEOS-9991]: WCS 2.0 slicing lat/lon fix

- src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureEncoder.java
- src/community/gsr/src/test/java/org/geoserver/gsr/translate/feature/FeatureEncoderTest.java
Fix for issue with GSR FeatureEncoder converting number based attribute values to strings. This was preventing Attribute based SLD styles using tags like <ogc:PropertyIsLessThan> from working in some clients as all numbers were strings in the GeoServices REST JSON output.
> Fix for issue with GSR FeatureEncoder converting number based attributes to strings

- src/web/core/src/main/java/org/geoserver/web/data/store/StoreProvider.java
- src/web/core/src/test/java/org/geoserver/web/data/store/StorePageTest.java
[![GEOS-9652](https://badgen.net/badge/JIRA/GEOS-9652/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9652) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This is another serialization bug that only comes to surface when using hz-cluster.
When you first load the page, you do get the links. But once you filter or sort, they are gone.
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have …
> [GEOS-9652] stores page without links when using hz-cluster

- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/BackupRestoreItem.java
- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/processor/CatalogItemProcessor.java
Break up the 272 lines long CatalogItemProcessor.process() method into
smaller chunks for each CatalogInfo type needing specialized processing.
Fix a bug in processing ResourceInfo, where a ResourceInfo class was
used as argument to get a StoreInfo from the Catalog.
--- 
The following are required only for core and extension modules (they are welcomed, …
> backup-restore/CatalogItemProcessor: Improve code readability

- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/listener/RestoreJobExecutionListener.java
- src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java
[![GEOS-9948](https://badgen.net/badge/JIRA/GEOS-9948/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9948) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backup and Restore replaces not involved layers during restore process, generating new IDs and hence breaking GWC layers definitions since they are layer-ID linked. This PR introduces a fix for this issue.
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-9948
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us …
> [2.19.x backport][GEOS-9948]Fix existing layers ID overwrite on Backup & Restore plugin

- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/listener/RestoreJobExecutionListener.java
- src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java
[![GEOS-9948](https://badgen.net/badge/JIRA/GEOS-9948/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9948) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backup and Restore replaces not involved layers during restore process, generating new IDs and hence breaking GWC layers definitions since they are layer-ID linked. This PR introduces a fix for this issue.
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-9948
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us …
> [2.17.x backport][GEOS-9948]Fix existing layers ID overwrite on Backup & Restore plugin

- src/community/flatgeobuf/pom.xml
- src/community/flatgeobuf/src/main/java/org/geoserver/wfs/flatgeobuf/FlatGeobufOutputFormat.java
[![GEOS-10017](https://badgen.net/badge/JIRA/GEOS-10017/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10017) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Migrate to gt-flatgeobuf to make flatgeobuf a transitive dependency via geotools instead of the older flatgeobuf version which had a geotools dependency causing potential version clashes.
> [GEOS-10017] Depend on gt-flatgeobuf instead of flatgeobuf

- src/main/src/main/java/org/geoserver/security/decorators/SecuredFeatureTypeInfo.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DimensionsVectorCapabilitiesTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/DimensionsVectorCapabilitiesTest.java
[![GEOS-10014](https://badgen.net/badge/JIRA/GEOS-10014/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10014) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR introduces a fix and some Junit WMS GetCapabilities integration tests for issue: Layers with dimensions are missing on WMS GetCapabilites output when catalog security is set to Challenge.
Jira ticket:
https://osgeo-org.atlassian.net/browse/GEOS-10014 …
> [GEOS-10014] Layers with dimensions are missing on WMS GetCapabilites output when catalog security is set to Challenge

- doc/en/api/1.0.0/workspaces.yaml
- src/restconfig/src/main/java/org/geoserver/rest/catalog/WorkspaceController.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/WorkspaceTest.java
[![GEOS-10007](https://badgen.net/badge/JIRA/GEOS-10007/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10007) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
* Change the http status code from 401(UNAUTHORIZED) to 409(CONFLICT) when adding an already exist workspace
* Update the http status code description in doc/en/api/1.0.0/workspaces.yaml
Maybe 409 is more suiteable than 401 when adding an already exist workspace?
> …
> [GEOS-10007] Update http status code when adding an already exist workspace

- src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureEncoder.java
- src/community/gsr/src/test/java/org/geoserver/gsr/translate/feature/FeatureEncoderTest.java
GSR extension enhancement to support properly encoding additional numeric data types
> GSR extension enhancement to support properly encoding additional numeric data types

- src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureEncoder.java
- src/community/gsr/src/test/java/org/geoserver/gsr/translate/feature/FeatureEncoderTest.java
[2.19.x Backport] GSR extension enhancement to support properly encoding additional numeric data types
> [2.19.x Backport] GSR extension enhancement to support properly encoding additional numeric data types

- src/main/src/main/java/org/geoserver/security/decorators/SecuredFeatureTypeInfo.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DimensionsVectorCapabilitiesTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/DimensionsVectorCapabilitiesTest.java
[![GEOS-10014](https://badgen.net/badge/JIRA/GEOS-10014/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10014) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR introduces a fix and some JUnit WMS GetCapabilities integration tests for issue: Layers with dimensions are missing on WMS GetCapabilites output when catalog security is set to Challenge.
Jira ticket:
https://osgeo-org.atlassian.net/browse/GEOS-10014 …
> [2.19.x backport][GEOS-10014] Layers with dimensions are missing on WMS GetCapabilites output when catalog security is set to Challenge

- src/main/src/main/java/org/geoserver/security/decorators/SecuredFeatureTypeInfo.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DimensionsVectorCapabilitiesTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/DimensionsVectorCapabilitiesTest.java
[![GEOS-10014](https://badgen.net/badge/JIRA/GEOS-10014/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10014) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR introduces a fix and some JUnit WMS GetCapabilities integration tests for issue: Layers with dimensions are missing on WMS GetCapabilites output when catalog security is set to Challenge.
Jira ticket:
https://osgeo-org.atlassian.net/browse/GEOS-10014 …
> [2.18.x backport][GEOS-10014] Layers with dimensions are missing on WMS GetCapabilites output when catalog security is set to Challenge

- src/community/flatgeobuf/README.md
- src/community/flatgeobuf/pom.xml
As of https://github.com/geoserver/geoserver/pull/4952 the FlatGeobuf extension is no longer only providing WFS output format but also adds itself as a GeoServer compatible DataStore. This PR fixes the description of the extension accordingly and removes "prototype" I now see it as complete.
> Improve description of FlatGeobuf extension

- src/community/release/ext-flatgeobuf.xml
Follow up to https://github.com/geoserver/geoserver/pull/4952, needs `gs-flatgeobuf` in the release builder project to properly include in the built zip artifact.
> Fix list of dependencies for ext-flatgeobuf

- src/main/src/main/java/org/geoserver/catalog/CoverageReaderFileConverter.java
- src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java
[![GEOS-10027](https://badgen.net/badge/JIRA/GEOS-10027/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10027) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-10027
fix a regression caused  by the CoverageReaderFileConverter preventing a coverage file name to be retrieved when saving the store and automatically set as the layer name.
Before the introduction of the CoverageReaderFileConverter [the check on the input string](https://github.com/geoserver/geoserver/blob/2.17.x/src/main/src/main/java/org/geoserver/catalog/Resource …
> [GEOS-10027] CoverageReaderFileConverter fails to convert valid input file path or url

- src/main/src/main/java/org/geoserver/catalog/CoverageReaderFileConverter.java
- src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java
[![GEOS-10027](https://badgen.net/badge/JIRA/GEOS-10027/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10027) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
* [GEOS-10027] CoverageReaderFileConverter fails to convert valid input file path or url
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help …
> [2.19.x backport][GEOS-10027] CoverageReaderFileConverter fails to convert valid input file path or url (#4986)

- src/main/src/main/java/org/geoserver/catalog/CoverageReaderFileConverter.java
- src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java
[![GEOS-10027](https://badgen.net/badge/JIRA/GEOS-10027/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10027) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
* [GEOS-10027] CoverageReaderFileConverter fails to convert valid input file path or url
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help …
> [2.18.x backport][GEOS-10027] CoverageReaderFileConverter fails to convert valid input file path or url (#4986)

- src/wfs/pom.xml
- src/wfs/src/main/java/org/geoserver/wfs/json/ComplexGeoJsonWriter.java
- src/wfs/src/main/java/org/geoserver/wfs/json/ComplexGeoJsonWriterOptions.java
- src/wfs/src/main/java/org/geoserver/wfs/json/DefaultComplexGeoJsonWriterOptions.java
- src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
- src/wfs/src/test/java/org/geoserver/wfs/json/ComplexGeoJsonWriterTest.java
[![GEOS-10028](https://badgen.net/badge/JIRA/GEOS-10028/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10028) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-10028
This pr add an extension point to allow extensions that serve complex features and are not using app-schema to customize the ComplexGeoJsonWriter behaviour when nested element are encoded. …
> [GEOS-10028] Allow to customize ComplexGeoJsonWriter encoding of nested element and non mandatory attributes

- src/release/bin/shutdown.sh
- src/release/bin/startup.sh
[![GEOS-10033](https://badgen.net/badge/JIRA/GEOS-10033/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10033) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
On linux, I tried to launch a fresh copy of Geoserver from a path containing spaces. It failed.
I looked at the startup.sh and shutdown.sh scripts and fixed quoting issues then linted those files [shellcheck](https://www.shellcheck.net/) and fixed warning.
I hope it will ease the onboarding process for new users :)
[JIRA ticket 10033](https://osgeo-org.atlassian.net/browse/GEOS-10033#)
> Reviewing is a process done by …
> [GEOS-10033] Update startup and shutdown scripts to handle spaces in paths

- src/extension/wmts-multi-dimensional/pom.xml
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/MultiDimensionalExtension.java
- src/extension/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/MultiDimensionalExtensionTest.java
[![GEOS-10037](https://badgen.net/badge/JIRA/GEOS-10037/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10037) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Fixing the WMS-Multi-dimensional extension throwing a ServiceException when encoding a TileLayer not being instance of GeoServerTileLayer
**Submitting …
> [GEOS-10037] WMTS Multidimensional extension make layers encoding fail on TileLayers not being GeoServerTileLayers

- src/extension/vectortiles/src/test/java/org/geoserver/wms/topojson/TopoJSONEncoderTest.java
- src/pom.xml
[![GEOS-10040](https://badgen.net/badge/JIRA/GEOS-10040/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10040) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Bump commons-io:commons-io from 2.7 to 2.8.0
Commons IO resolved CVE-2021-29425 in 2.7: https://issues.apache.org/jira/browse/IO-556
backports #5007 to 2.19.x
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of …
> [2.19.x backport][GEOS-10040] Bump commons-io from 2.6 to 2.8.0

- src/gwc/src/main/java/org/geoserver/gwc/layer/CatalogLayerEventListener.java
- src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
- src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
- src/gwc/src/test/java/org/geoserver/gwc/layer/GeoServerTileLayerTest.java
[![GEOS-100031](https://badgen.net/badge/JIRA/GEOS-100031/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-100031) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or …
> [GEOS-100031] GWC loses GridSets bounds when importing data through the Importer plugin (2.18.x)

- src/wfs/pom.xml
- src/wfs/src/main/java/org/geoserver/wfs/json/ComplexGeoJsonWriter.java
- src/wfs/src/main/java/org/geoserver/wfs/json/ComplexGeoJsonWriterOptions.java
- src/wfs/src/main/java/org/geoserver/wfs/json/DefaultComplexGeoJsonWriterOptions.java
- src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
- src/wfs/src/test/java/org/geoserver/wfs/json/ComplexGeoJsonWriterTest.java
[![GEOS-10028](https://badgen.net/badge/JIRA/GEOS-10028/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10028) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
* [GEOS-10028] Allow to customize ComplexGeoJsonWriter encoding of nested element and non mandatory attributes …
> [2.19.x backport][GEOS-10028] Allow to customize ComplexGeoJsonWriter encoding of nested element and non mandatory attributes (#4987)

- src/wfs/pom.xml
- src/wfs/src/main/java/org/geoserver/wfs/json/ComplexGeoJsonWriter.java
- src/wfs/src/main/java/org/geoserver/wfs/json/ComplexGeoJsonWriterOptions.java
- src/wfs/src/main/java/org/geoserver/wfs/json/DefaultComplexGeoJsonWriterOptions.java
- src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
- src/wfs/src/test/java/org/geoserver/wfs/json/ComplexGeoJsonWriterTest.java
[![GEOS-10028](https://badgen.net/badge/JIRA/GEOS-10028/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10028) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
* [GEOS-10028] Allow to customize ComplexGeoJsonWriter encoding of nested element and non mandatory attributes …
> [2.18.x backport][GEOS-10028] Allow to customize ComplexGeoJsonWriter encoding of nested element and non mandatory attributes (#4987)

- src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java
- src/wms/src/test/java/org/geoserver/wms/map/GetMapKvpRequestReaderTest.java
[![GEOS-10044](https://badgen.net/badge/JIRA/GEOS-10044/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10044) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Allows layergroups to be properly cacheable by GWC when a requestParamFilter for FILTER is configured for the TileLayer and a cql_filter is specified on the WMS GetMap request.
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have …
> GEOS-10044: allows GWC to cache layergroups when a cql_filter is specified and a requestParamFilter for FILTER is configured in the tile layer

- src/community/schemaless-features/schemaless-mongo/src/main/java/org/geoserver/schemalessfeatures/mongodb/response/MongoComplexGeoJsonWriterOptions.java
- src/community/schemaless-features/schemaless-mongo/src/main/resources/applicationContext.xml
- src/community/schemaless-features/schemaless-mongo/src/test/java/org/geoserver/schemalessfeatures/mongodb/WFSSchemalessMongoTest.java
> [2.19.x backport] Add custom ComplexGeoJsonWriterOptions to encode nested features as properties (#4988)

- src/community/schemaless-features/schemaless-mongo/src/main/java/org/geoserver/schemalessfeatures/mongodb/response/MongoComplexGeoJsonWriterOptions.java
- src/community/schemaless-features/schemaless-mongo/src/main/resources/applicationContext.xml
- src/community/schemaless-features/schemaless-mongo/src/test/java/org/geoserver/schemalessfeatures/mongodb/WFSSchemalessMongoTest.java
> [2.18.x backport] Add custom ComplexGeoJsonWriterOptions to encode nested features as properties (#4988)

- src/web/demo/src/main/java/org/geoserver/web/demo/SRSDescriptionPage.java
- src/web/demo/src/test/java/org/geoserver/web/demo/SRSDescriptionPageTest.java
[![GEOS-10055](https://badgen.net/badge/JIRA/GEOS-10055/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10055) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Updated the SRS description demo page to escape user input in the rendered page.
https://osgeo-org.atlassian.net/browse/GEOS-10055
**Submitting the PR …
> [GEOS-10055] Escape SRS demo page user input

- src/ows/src/main/java/org/geoserver/ows/kvp/ElevationParser.java
- src/ows/src/test/java/org/geoserver/ows/kvp/ElevationKvpParserTest.java
[![GEOS-10051](https://badgen.net/badge/JIRA/GEOS-10051/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10051) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Added a check that will exit the loop when attempting to parse certain invalid inputs.
https://osgeo-org.atlassian.net/browse/GEOS-10051
**Submitting …
> [GEOS-10051] Fix edge cases in the elevation parser

- src/web/demo/src/main/java/org/geoserver/web/demo/SRSDescriptionPage.java
- src/web/demo/src/test/java/org/geoserver/web/demo/SRSDescriptionPageTest.java
[![GEOS-10055](https://badgen.net/badge/JIRA/GEOS-10055/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10055) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
2.18.x backport for https://github.com/geoserver/geoserver/pull/5037 …
> [2.18.x][GEOS-10055] Escape SRS demo page user input

- src/web/wms/src/main/java/org/geoserver/wms/web/data/AbstractStylePage.java
- src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleNewPageTest.java
[![GEOS-10057](https://badgen.net/badge/JIRA/GEOS-10057/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10057) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
2.19.x backport for https://github.com/geoserver/geoserver/pull/5042 …
> [2.19.x][GEOS-10057] Escape style editor page user input

- src/web/wms/src/main/java/org/geoserver/wms/web/data/AbstractStylePage.java
- src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleNewPageTest.java
[![GEOS-10057](https://badgen.net/badge/JIRA/GEOS-10057/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10057) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
2.18.x backport for https://github.com/geoserver/geoserver/pull/5042 …
> [2.18.x][GEOS-10057] Escape style editor page user input

- src/ows/src/main/java/org/geoserver/ows/kvp/ElevationParser.java
- src/ows/src/test/java/org/geoserver/ows/kvp/ElevationKvpParserTest.java
[![GEOS-10051](https://badgen.net/badge/JIRA/GEOS-10051/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10051) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
2.19.x backport for https://github.com/geoserver/geoserver/pull/5029 …
> [2.19.x][GEOS-10051] Fix edge cases in the elevation parser

- doc/en/user/source/extensions/netcdf/netcdf.rst
- src/extension/importer/core/src/test/java/org/geoserver/importer/mosaic/ImporterMosaicTest.java
- src/extension/netcdf/src/main/java/org/geoserver/netcdf/NetCDFUnitsConfigurator.java
[![GEOT-6902](https://badgen.net/badge/JIRA/GEOT-6902/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6902)
backporting doc updates and cache cleanup for [GEOT-6902] (NetCDF caching) to 2.19.x
Depends on 
https://github.com/geotools/geotools/pull/3556
> [Backport-2.19.x][GEOT-6902]: Follow up on NetCDF performances improvement - caching

- src/community/saml/pom.xml
- src/community/saml/src/main/java/org/geoserver/security/saml/GeoServerPreAuthenticatedCompositeUserNameFilter.java
- src/community/saml/src/main/java/org/geoserver/security/saml/LoggingHTTPMetadataProvider.java
- src/community/saml/src/main/java/org/geoserver/security/saml/SAMLAuthenticationFilter.java
- src/community/saml/src/main/java/org/geoserver/security/saml/SAMLSecurityProvider.java
- src/community/saml/src/main/java/org/geoserver/security/saml/SAMLUserDetailsServiceImpl.java
- src/community/saml/src/main/java/org/geoserver/security/web/saml/SAMLAuthFilterPanel.java
- src/community/saml/src/test/java/org/geoserver/security/saml/test/SAMLAuthFilterPanelTest.java
- src/community/saml/src/test/java/org/geoserver/security/saml/test/SAMLAuthenticationTest.java
- src/community/saml/src/test/java/org/geoserver/security/saml/test/SSLUtilities.java
- src/community/saml/src/test/java/org/geoserver/security/saml/test/StringSamlDecoder.java
[![GEOS-10137](https://badgen.net/badge/JIRA/GEOS-10137/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10137)
This pr
- fix bug on the filter UI preventing the password fields to be reload when editing the filter.
- fix a small bug preventing global logout to be handled from idp that requires it to be signed
**Submitting the PR does not require you to …
> [GEOS-10137] SAML community module UI fixes

- src/community/geopkg/src/main/java/org/geoserver/geopkg/GeoPackageGetFeatureOutputFormat.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/GeoPkg.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoPackageProcess.java
- src/community/geopkg/src/main/resources/GeoServerApplication.properties
- src/community/geopkg/src/main/resources/GeoServerApplication_es.properties
- src/community/geopkg/src/main/resources/GeoServerApplication_ko.properties
- src/community/geopkg/src/main/resources/GeoServerApplication_pl.properties
- src/community/geopkg/src/main/resources/GeoServerApplication_ru.properties
- src/community/geopkg/src/main/resources/GeoServerApplication_tr.properties
- src/community/geopkg/src/test/java/org/geoserver/geopkg/GeoPackageMimeTypeTest.java
[![GEOS-10126](https://badgen.net/badge/JIRA/GEOS-10126/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10126)
Within GeoServer the mediatype for GeoPackage is  application/x-gpkg
However application/x-gpkg is a deprecated media-type, GeoPackage is now officially listed at https://www.iana.org/assignments/media-types/media-types.xhtml as application/geopackage+sqlite3
Resolves https://osgeo-org.atlassian.net/browse/GEOS-10126
- [N/A] Commits changing the REST API, or any configuration object, …
> [GEOS-10126] Mediatype x-gpkg is deprecated

- doc/en/user/source/extensions/geofence-server/gui.rst
- doc/en/user/source/filter/function_reference.rst
> [backport 2.19.x]Updating GeoFence documentation with example on CQL read filter limits on time range

- src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java
- src/security/security-tests/src/test/java/org/geoserver/security/impl/AbstractAuthorizationTest.java
- src/security/security-tests/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java
[![GEOS-10032](https://badgen.net/badge/JIRA/GEOS-10032/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10032)
This pull request solves the issue, that layergroups are not output to capabilities in catalog mode hide, when the user is not the admin user. The reason lies in a not applicable filter put on layergroups by DefaultResourceAccessManager. …
> [GEOS-10032] Group Layer in Catalag Mode Hide not in capabilities when unauthenticated

- doc/en/user/source/services/internationalization/index.rst
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/GetCapabilitiesTest.java
- src/main/src/main/java/applicationContext.xml
- src/main/src/main/java/org/geoserver/ows/LanguageURLMangler.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/GetCapabilitiesTest.java
- src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetCapabilitiesTest.java
- src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesReponseTest.java
[![GEOS-10160](https://badgen.net/badge/JIRA/GEOS-10160/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10160)
This pull request adds the possibility to have the language parameter in the URL in the GetCapabilities response.
> [GEOS-10160] Requested Language in GetCapabilities

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NormalizedMultiValuesTest.java
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/stations.properties
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/stations.xml
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/stations.xsd
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/use.properties
[![GEOS-10144](https://badgen.net/badge/JIRA/GEOS-10144/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10144)
Provides test coverage for [GEOT-6937]( https://github.com/geotools/geotools/pull/3579) by modifying existing app-schema mappings in multivalues/stations.xml in order to have one of the two jdbcMultipleValue relations defained using the primary key of the target column. …
> [GEOS-10144] Integration test AppSchema JdbcMultipleValue will fill wrong values if targeColumn is a PK

- src/main/src/main/java/org/geoserver/catalog/CoverageViewReader.java
- src/security/security-tests/src/test/java/org/geoserver/security/decorators/SecuredGridCoverage2DReaderTest.java
[![GEOS-10173](https://badgen.net/badge/JIRA/GEOS-10173/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10173)
CoverageViewReader instantiates an anonymous Format implementation resulting into not being secured by Secured Factories
> [GEOS-10173]: Fixing securing CoverageViewReader's format class

- src/main/src/main/java/org/geoserver/catalog/CoverageViewReader.java
- src/security/security-tests/src/test/java/org/geoserver/security/decorators/SecuredGridCoverage2DReaderTest.java
[![GEOS-10173](https://badgen.net/badge/JIRA/GEOS-10173/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10173)
Backporting GEOS-10173 to 2.19.x
> [backport-2.19.x][GEOS-10173]: Fixing securing CoverageViewReader's format class

- src/main/src/main/java/org/geoserver/catalog/CoverageViewReader.java
- src/security/security-tests/src/test/java/org/geoserver/security/decorators/SecuredGridCoverage2DReaderTest.java
[![GEOS-10173](https://badgen.net/badge/JIRA/GEOS-10173/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10173)
Backporting GEOS-10173 to 2.18.x
> [backport-2.18.x][GEOS-10173]: Fixing securing CoverageViewReader's format class

- src/community/geomesa/pom.xml
Fix a typo in `src/community/geomesa/pom.xml` (small changes):
The element `<name>` should be closed
Please review this PR, thanks @jnh5y @anthonyccri @LocationTech @geomesa
> fix a typo in community/geomesa/pom.xml

- src/community/features-templating/features-templating-web/src/main/java/org/geoserver/featurestemplating/web/TemplateInfoPage.java
- src/community/features-templating/features-templating-web/src/test/java/org/geoserver/featurestemplating/web/TemplateInfoPageTest.java
[![GEOS-10188](https://badgen.net/badge/JIRA/GEOS-10188/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10188)
> [2.19.x backport][GEOS-10188] Features templating when deleting a templateInfo all the template contents will be deleted

- src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
- src/extension/importer/core/src/test/java/org/geoserver/importer/ImporterDataTest.java
[![GEOS-10193](https://badgen.net/badge/JIRA/GEOS-10193/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10193)
> [GEOS-10193] Indirect imports will drop the target table if there is any failure during the import process (2.19.x)

- src/pom.xml
[![GEOS-10202](https://badgen.net/badge/JIRA/GEOS-10202/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10202)
> [GEOS-10202] Bump bcprov-jdk15on (aka. Bouncycastle Crypto) from 1.67 ➜ 1.69

- src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/LayerControllerTest.java
[![GEOS-9937](https://badgen.net/badge/JIRA/GEOS-9937/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9937)
In the current implementation, it looks that anything present before the colon in style name is considered as a workspace name. It proceeds even if the workspace with the given name is not present. This fix assigns workspace name only if one with the given name exists
> [GEOS-9937] Name of styles with colons are incorrect in REST API

- src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/CapabilityUtil.java
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReader.java
- src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReaderTest.java
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/JSONLegendGraphicOutputFormatTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetMapIntegrationTest.java
[![GEOS-10213](https://badgen.net/badge/JIRA/GEOS-10213/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10213)
> [GEOS-10213] WMS requests fail on LayerGroup default style names, when used (2.18.x)

- src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/CapabilityUtil.java
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReader.java
- src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReaderTest.java
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/JSONLegendGraphicOutputFormatTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetMapIntegrationTest.java
[![GEOS-10213](https://badgen.net/badge/JIRA/GEOS-10213/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10213)
> [GEOS-10213] WMS requests fail on LayerGroup default style names, when used (2.19.x)

- src/pom.xml
Updating to imageio-ext-1.3.10 version including support for TIFF ZSTD decompression
> Updating to imageio-ext-1.3.10 version

- src/pom.xml
[backport to 2.19.x]Updating to imageio-ext 1.3.10 for ZSTD support
> [Backport 2.19.x] Updating to imageio-ext 1.3.10 for ZSTD decompression support

- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLGenerator.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLGetFeatureInfoOutputFormat.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLGetFeatureOutputFormat.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLGeneratorTest.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLGetFeatureOutputFormatTest.java
[![GEOS-10206](https://badgen.net/badge/JIRA/GEOS-10206/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10206)
Allows the MapML extension to respect the WFS settings that the user can change: forcedDecimals, numDecimal, padWithZeros.
> [GEOS-10206] MapML extension support forcedDecimal, numDecimal, padWithZeros

- doc/en/user/source/services/wfs/outputformats.rst
- doc/en/user/source/services/wfs/vendor.rst
- src/wfs/src/main/java/org/geoserver/wfs/response/CSVOutputFormat.java
- src/wfs/src/test/java/org/geoserver/wfs/response/CSVOutputFormatTest.java
[![GEOS-10222](https://badgen.net/badge/JIRA/GEOS-10222/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10222)
> [GEOS-10222] WFS CSV OutputFormat delimiter

- doc/en/user/source/filter/function_reference.rst
This adds a hint for the usage of the env function in dynamic symbolizers (online resource in external graphic).
In that case one needs to put single quotes around the first argument to make things work.
> Enhance the env-function documentation

- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteTest.java
- src/main/src/main/java/org/geoserver/ows/HTTPHeadersCollector.java
- src/main/src/main/java/org/geoserver/ows/ProxifyingURLMangler.java
- src/main/src/test/java/org/vfny/geoserver/util/URLProxifyingTest.java
[![GEOS-10158](https://badgen.net/badge/JIRA/GEOS-10158/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10158)
This is backport of [5263](https://github.com/geoserver/geoserver/pull/5263) for branch 2.19.x
> [2.19.x backport][GEOS-10158] POST request -> j_spring_security_check is in http plain even if proxy base url is in https

- doc/en/user/source/services/internationalization/index.rst
This is a documentation change and not a functional commit, please backport to 2.20.x branch also.
> Update headings and work on accepts language examples

- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteTest.java
- src/main/src/main/java/org/geoserver/ows/HTTPHeadersCollector.java
- src/main/src/main/java/org/geoserver/ows/ProxifyingURLMangler.java
- src/main/src/test/java/org/vfny/geoserver/util/URLProxifyingTest.java
[![GEOS-10158](https://badgen.net/badge/JIRA/GEOS-10158/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10158)
> [2.18.x backport][GEOS-10158] POST request -> j_spring_security_check is in http plain even if proxy base url is in https

- doc/en/user/source/community/ogc-api/features/index.rst
This clarification describes the functionality now, if the handling of common-header.ftl is fixed in the future this documentation can be updated.
- x ] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md) 
The following are required only for core and extension modules (they are welcomed, but not required, for community modules)
This is a small clarification to docs for a community module.
> clarification on use of common-header.ftl

- src/wfs/src/main/java/org/geoserver/wfs/response/CSVOutputFormat.java
- src/wfs/src/test/java/org/geoserver/wfs/response/CSVOutputFormatTest.java
[![GEOS-10235](https://badgen.net/badge/JIRA/GEOS-10235/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10235)
> [GEOS-10235] Prevent double-quote to be specified as CSV separator

- src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
- src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java
[![GEOS-10226](https://badgen.net/badge/JIRA/GEOS-10226/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10226)
Added some code that cleans up the file created during a failing writeStyle call.
> [GEOS-10226] ResourcePool leaves empty files on failure

- src/extension/authkey/src/main/java/org/geoserver/security/GeoServerRestRoleService.java
- src/extension/authkey/src/test/java/org/geoserver/security/GeoServerRestRoleServiceTest.java
[![GEOS-10116](https://badgen.net/badge/JIRA/GEOS-10116/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10116)
[GEOS-9198](https://osgeo-org.atlassian.net/browse/GEOS-9198) / #3477 added  support for resolving env parameters in the authkey module configuration, but not for the REST role service. 
This extends support for resolving parameters in the following `GeoServerRESTRoleServiceConfig` properties:
* `baseUrl`
* `authApiKey`
> [GEOS-10116] authkey: Resolve REST role service config from environment

- doc/en/user/source/services/wms/get_legend_graphic/index.rst
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendUtils.java
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/BufferedImageLegendGraphicOutputFormatTest.java
[![GEOS-10228](https://badgen.net/badge/JIRA/GEOS-10228/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10228)
> [GEOS-10228] Wrap the category text values of a legend

- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/FeaturesSampleDataProvider.java
- src/community/ogcapi/ogcapi-styles/src/main/resources/org/geoserver/ogcapi/styles/styleMetadata.ftl
- src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/ogcapi/styles/StyleMetadataTest.java
Fixing a HTML representation in community module ogcapi-styles
> OGC API - Styles metadata representation throws exception

- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/TileJSONBuilder.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/TilesService.java
- src/community/ogcapi/ogcapi-tiles/src/main/resources/org/geoserver/ogcapi/tiles/tileMatrixSets.ftl
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/tiles/GetTileTest.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/tiles/TilesetDescriptionTest.java
OGC-API Tiles get some updates on July, modifying a couple of URL resources.
Code has been updated to reflect the current state.
> Revisiting OGC-API Tiles links based on current status of the spec

- src/community/ogcapi/ogcapi-tiles/pom.xml
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/TileJSONBuilder.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/Tileset.java
- src/community/ogcapi/ogcapi-tiles/src/main/resources/org/geoserver/ogcapi/tiles/tileMatrixSet.ftl
- src/community/ogcapi/ogcapi-tiles/src/main/resources/org/geoserver/ogcapi/tiles/tileset-include.ftl
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/tiles/GetTileTest.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/tiles/TileJSONBuilderTest.java
[![GEOS-10223](https://badgen.net/badge/JIRA/GEOS-10223/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10223)
This is backport of [5288](https://github.com/geoserver/geoserver/pull/5288) for 2.20.x
> [2.20.x backport][GEOS-10223] Support MBTiles in OGC Tiles API

- src/wfs/src/main/java/org/geoserver/wfs/response/CSVOutputFormat.java
- src/wfs/src/test/java/org/geoserver/wfs/response/CSVOutputFormatTest.java
[![GEOS-10235](https://badgen.net/badge/JIRA/GEOS-10235/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10235)
This is backport of [5285](https://github.com/geoserver/geoserver/pull/5285) for 2.20.x
> [2.20.x backport][GEOS-10235] Prevent double-quote to be specified as CSV separator

- doc/en/user/source/community/features-templating/directives.rst
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/EncodingHints.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/VendorOptions.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/JSONTemplateReader.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/CommonJSONWriter.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/GeoJSONWriter.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/JSONLDWriter.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/writers/JsonWriterTest.java
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/FirstParentFeature_invalid.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/GeologicUnitDynamicStaticFilter.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/GeologicUnit_invalid.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/ManagedMappedFeatureJSONLD.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/MappedFeatureIteratingAndCompositeFilter.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/MfJsonLdDefEncoding.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/NamedPlaces.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/SimplifiedPropertyNames.json
- src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/wfs/JSONLDGetFeatureResponse.java
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/JSONLDGetComplexFeaturesResponseWFSTest.java
[![GEOS-10254](https://badgen.net/badge/JIRA/GEOS-10254/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10254)
> [GEOS-10252] Features templating JSON-LD output should not encode all attributes as string

- src/main/src/main/java/org/geoserver/config/util/XStreamPersisterFactory.java
- src/main/src/main/java/org/geoserver/security/GeoServerSecurityManager.java
- src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java
- src/main/src/test/java/org/geoserver/catalog/impl/FeatureTypeInfoImplTest.java
- src/main/src/test/java/org/geoserver/config/GeoServerDataDirectoryTest.java
- src/main/src/test/java/org/geoserver/config/GeoServerImplTest.java
- src/main/src/test/java/org/geoserver/config/util/XStreamPersisterIntegrationTest.java
- src/main/src/test/java/org/geoserver/config/util/XStreamPersisterTest.java
- src/main/src/test/java/org/geoserver/data/test/SystemTestData.java
- src/main/src/test/java/org/geoserver/security/impl/LayerGroupContainmentCacheTest.java
- src/platform/src/main/java/org/geoserver/platform/GeoServerExtensions.java
This is not intended as a functional change, although some private methods have been introduced.
I tried reducing the `warning` to `fine` detail, but on careful review this warning was correctly reporting two issues on application startup:
XStreamPersisterFactory is being used prior to extensions being made available:
```
getInitializers:72, XStreamPersisterFactory (org.geoserver.config.util)
buildPersister:65, XStreamPersisterFactory (org.geoserver.config.util)
createXMLPersister:53, XStreamPersisterFactory (org.geoserver.config.util)
getLogging:118, LoggingStartupContextListener (org.geoserver.logging)
contextInitialized:71, LoggingStartupContextListener (org.geoserver.logging)
```
* XStreamPersisterFactory is being constructed directly here
Security manager is trying to obtain security …
> GeoServer Extensions warnings cleanup

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
- src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/catalog/CatalogImplWithJDBCFacadeTest.java
[![GEOS-10245](https://badgen.net/badge/JIRA/GEOS-10245/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10245)
> [GEOS-10245] jdbcconfig: prefixedName filter field not updated

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
- src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/catalog/CatalogImplWithJDBCFacadeTest.java
[![GEOS-10245](https://badgen.net/badge/JIRA/GEOS-10245/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10245)
https://osgeo-org.atlassian.net/browse/GEOS-10245
> [GEOS-10245] jdbcconfig: prefixedName filter field not updated (backport)

- src/web/core/src/main/java/org/geoserver/web/InternationalStringPanel.html
- src/web/core/src/main/java/org/geoserver/web/StringAndInternationalStringPanel.html
- src/web/core/src/main/java/org/geoserver/web/css/geoserver.css
- src/web/core/src/main/java/org/geoserver/web/data/resource/TitleAndAbstractPanel.html
[![GEOS-10255](https://badgen.net/badge/JIRA/GEOS-10255/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10255)
This code provides some fixes to the new i18n fragments allowing layout using csss (rather than hard coded styles and br).
> [GEOS-10255] i18n use classes, selfclear and leftwise for layout

- doc/en/user/source/community/features-templating/directives.rst
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/EncodingHints.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/VendorOptions.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/JSONTemplateReader.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/CommonJSONWriter.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/GeoJSONWriter.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/JSONLDWriter.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/writers/JsonWriterTest.java
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/FirstParentFeature_invalid.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/GeologicUnitDynamicStaticFilter.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/GeologicUnit_invalid.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/ManagedMappedFeatureJSONLD.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/MappedFeatureIteratingAndCompositeFilter.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/MfJsonLdDefEncoding.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/NamedPlaces.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/SimplifiedPropertyNames.json
- src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/wfs/JSONLDGetFeatureResponse.java
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/JSONLDGetComplexFeaturesResponseWFSTest.java
[![GEOS-10254](https://badgen.net/badge/JIRA/GEOS-10254/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10254)
> [2.19.x backport][GEOS-10254] Features templating JSON-LD output should not encode all attributes as string (#5304)

- src/extension/wps/web-wps/src/test/java/org/geoserver/wps/web/WPSRequestBuilderTest.java
[![GEOS-10263](https://badgen.net/badge/JIRA/GEOS-10263/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10263)
> [GEOS-10263] WPSRequestBuilderTest assumes that JTS:area is the first process in the list

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
[![GEOS-10246](https://badgen.net/badge/JIRA/GEOS-10246/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10246)
https://osgeo-org.atlassian.net/browse/GEOS-10246
> [GEOS-10246] Jdbc performance improvement from unnecessary transactions

- src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.java
- src/web/demo/src/test/java/org/geoserver/web/demo/MapPreviewPageTest.java
[![GEOS-9950](https://badgen.net/badge/JIRA/GEOS-9950/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9950)
This avoids filling up the logs if a localization is not available for a given output format.
Experimented with skipping output formats that did not have a localization, but that was not fair to third-party output formats being developed. 
> [GEOS-9950] LayerPreview use format string if translation not available

- src/web/core/src/main/java/org/geoserver/web/css/geoserver.css
- src/web/core/src/main/java/org/geoserver/web/data/layer/LayerPage.html
- src/web/core/src/main/java/org/geoserver/web/data/layer/NewFeatureTypePage.html
- src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupEntryPanel.html
- src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupPage.html
- src/web/core/src/main/java/org/geoserver/web/data/store/StorePage.html
- src/web/core/src/main/java/org/geoserver/web/data/workspace/WorkspacePage.html
- src/web/gwc/src/main/java/org/geoserver/gwc/web/blob/BlobStoresPage.html
- src/web/gwc/src/main/java/org/geoserver/gwc/web/gridset/GridSetsPage.html
- src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayersPage.html
- src/web/security/core/src/main/java/org/geoserver/security/web/SecurityNamedServicesPanel.html
- src/web/security/core/src/main/java/org/geoserver/security/web/auth/SecurityFilterChainsPanel.html
- src/web/security/core/src/main/java/org/geoserver/security/web/data/DataSecurityPage.html
- src/web/security/core/src/main/java/org/geoserver/security/web/group/GroupPanel.html
- src/web/security/core/src/main/java/org/geoserver/security/web/role/RolePanel.html
- src/web/security/core/src/main/java/org/geoserver/security/web/service/ServiceAccessRulePage.html
- src/web/security/core/src/main/java/org/geoserver/security/web/user/UserPanel.html
- src/web/wms/src/main/java/org/geoserver/wms/web/data/StylePage.html
[![GEOS-10259](https://badgen.net/badge/JIRA/GEOS-10259/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10259)
[![GEOS-10260](https://badgen.net/badge/JIRA/GEOS-10259/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10260)
A small user interface change that makes me happy.
Documentation not updated as part of this change as the screen snaps are close enough not to confuse anyone.
1) workspaces
2) stores
3) layers, layer groups, styles etc...
4) security 
5) security panels (separate commit as title is introduced to provide visual separator)
These ones had heading breaks already:
User/Group page has expanding sections for each service, made use of panel title to provide a visual separation (now that action group does not provide a block of empty space.
Similar for role service …
> [GEOS-10259][GEOS-10260] Use class action-group to align actions horizontally across table

- src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/TemplateCallback.java
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/GetFeatureInfoGroupTest.java
[![GEOS-10266](https://badgen.net/badge/JIRA/GEOS-10266/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10266)
> [GEOS-10266] Features Templating makes getfeatureinfo fail for raster data

- doc/en/user/source/community/opensearch-eo/STAC.rst
- doc/en/user/source/community/opensearch-eo/configuration.rst
- src/community/oseo/oseo-service/src/main/java/org/geoserver/opensearch/eo/response/TemplatesProcessor.java
- src/community/oseo/oseo-service/src/test/java/org/geoserver/opensearch/eo/SearchTest.java
- src/community/oseo/oseo-service/src/test/resources/org/geoserver/opensearch/eo/product-LANDSAT8.ftl
- src/community/oseo/oseo-service/src/test/resources/org/geoserver/opensearch/eo/readAndEval.json
- src/community/oseo/oseo-service/src/test/resources/org/geoserver/opensearch/eo/readAndEvalNestedDir.json
[![GEOS-10287](https://badgen.net/badge/JIRA/GEOS-10287/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10287)
Freemarker templates now have the ability to read properties from JSON files.
> [GEOS-10287] JSON read support for freemarker templates

- src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
- src/main/src/main/java/org/geoserver/coverage/CoverageAccessInitializer.java
- src/main/src/test/java/org/geoserver/coverage/CoverageAccessInitializerTest.java
[![GEOS-10292](https://badgen.net/badge/JIRA/GEOS-10292/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10292)
This is due to the API of changing thread pool core and max size being tricky (no method to change core and max size at the same time, the others checking that the relationship core < max is always maintained).
See also the ticket for more description.
> [GEOS-10292] Changing worker pool size in raster access is not actually applied (silent error)

- src/pom.xml
[![GEOS-10282](https://badgen.net/badge/JIRA/GEOS-10282/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10282)
Follows up with GEOS-10282, adding a QA rule that should prevent improperly encoded files from landing in GeoServer (was not the issue, but we had a few).
> [GEOS-10282] Follow up, add enforcer check

- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/DynamicMergeBuilder.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/builders/impl/DynamicMergeBuilderTest.java
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/stac/items.json
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/ItemsTest.java
- src/community/oseo/oseo-stac/src/test/resources/items-LANDSAT8.json
[![GEOS-10269](https://badgen.net/badge/JIRA/GEOS-10269/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10269)
Handled dynamic merge when evaluated part is base.
> [GEOS-10269] Dynamic merge when evaluated part is base

- src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
- src/main/src/main/java/org/geoserver/coverage/CoverageAccessInitializer.java
- src/main/src/test/java/org/geoserver/coverage/CoverageAccessInitializerTest.java
[![GEOS-10292](https://badgen.net/badge/JIRA/GEOS-10292/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10292)
Backport to 2.20.x
> [GEOS-10292] Changing worker pool size in raster access is not actually applied (silent error) (2.20.x)

- src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
- src/main/src/main/java/org/geoserver/coverage/CoverageAccessInitializer.java
- src/main/src/test/java/org/geoserver/coverage/CoverageAccessInitializerTest.java
[![GEOS-10292](https://badgen.net/badge/JIRA/GEOS-10292/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10292)
2.19.x backport
> [GEOS-10292] Changing worker pool size in raster access is not actually applied (silent error) (2.19.x)

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/XStreamPPIO.java
- src/pom.xml
[![GEOS-10296](https://badgen.net/badge/JIRA/GEOS-10296/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10296)
> [GEOS-10296] Upgrade to ErrorProne 2.10.0

- src/web/core/src/main/java/org/geoserver/web/wicket/CRSPanel.java
- src/web/core/src/test/java/org/geoserver/web/wicket/CRSPanelTest.java
- src/web/core/src/test/java/org/geoserver/web/wicket/CRSPanelTestPage.java
- src/wms/src/main/java/org/geoserver/wms/map/AbstractOpenLayersMapOutputFormat.java
- src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapOutputFormatTest.java
- src/wms/src/test/resources/OL_LOGGING.properties
Backport of https://github.com/geoserver/geoserver/pull/5391
> A couple of improvements to handle AUTO codes in GeoServer reprojection console and map preview  (2.19.x)

- src/web/core/src/main/java/org/geoserver/web/wicket/CRSPanel.java
- src/web/core/src/test/java/org/geoserver/web/wicket/CRSPanelTest.java
- src/web/core/src/test/java/org/geoserver/web/wicket/CRSPanelTestPage.java
- src/wms/src/main/java/org/geoserver/wms/map/AbstractOpenLayersMapOutputFormat.java
- src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapOutputFormatTest.java
- src/wms/src/test/resources/OL_LOGGING.properties
Backport of https://github.com/geoserver/geoserver/pull/5391
> A couple of improvements to handle AUTO codes in GeoServer reprojection console and map preview  (2.20.x)

- src/community/ogcapi/ogcapi-core/pom.xml
- src/community/wfs3/pom.xml
- src/community/wfs3/src/test/java/org/geoserver/wfs3/StyleTest.java
- src/pom.xml
[![GEOS-10301](https://badgen.net/badge/JIRA/GEOS-10301/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10301)
This replaces woodstox-core-asl 4.1.2 initialy brought in to assist with xmlns="" for community modules wfs3.
See https://github.com/FasterXML/jackson-dataformat-xml/issues/32
> [GEOS-10301] Upgrade ogcapi and wfs3 to woodstox-core 6.2.6

- src/community/ogcapi/ogcapi-core/pom.xml
- src/community/wfs3/pom.xml
- src/pom.xml
[![GEOS-10301](https://badgen.net/badge/JIRA/GEOS-10301/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10301)
Backport of https://github.com/geoserver/geoserver/pull/5396
> [GEOS-10301] Upgrade to woodstox-core 6.2.6 [2.20.x backport]

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AbstractHTMLMessageConverter.java
- src/community/oseo/oseo-service/src/main/java/org/geoserver/opensearch/eo/response/TemplatesProcessor.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/LoadJSONTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/STACTestSupport.java
- src/community/oseo/oseo-stac/src/test/resources/collection.ftl
- src/community/oseo/oseo-stac/src/test/resources/collections.ftl
- src/community/oseo/oseo-stac/src/test/resources/readAndEval.json
- src/community/oseo/oseo-stac/src/test/resources/readAndEvalNestedDir.json
[![GEOS-10287](https://badgen.net/badge/JIRA/GEOS-10287/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10287)
loadJSON functionality is added to OSEO-STAC module which enables to load a JSON file in geoserver data directory.
> [GEOS-10287] loadJSON function is added to OSEO-STAC

- doc/en/user/source/community/geopkg/output.rst
- src/community/geopkg/src/main/java/applicationContext.xml
- src/community/geopkg/src/main/java/org/geoserver/geopkg/GeoPackageGetMapOutputFormat.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoPackageProcess.java
- src/community/geopkg/src/test/java/org/geoserver/geopkg/GeoPackageGetMapOutputFormatTest.java
- src/community/geopkg/src/test/java/org/geoserver/geopkg/wps/GeoPackageProcessTest.java
- src/community/geopkg/src/test/resources/GPKG_LOGGING.properties
- src/community/geopkg/src/test/resources/org/geoserver/geopkg/wps/fillenv.sld
- src/community/mbtiles/src/main/java/org/geoserver/mbtiles/MBTilesGetMapOutputFormat.java
- src/community/mbtiles/src/main/java/org/geoserver/mbtiles/gs/wps/MBTilesProcess.java
- src/community/mbtiles/src/main/java/org/geoserver/tiles/AbstractTilesGetMapOutputFormat.java
- src/community/mbtiles/src/test/java/org/geoserver/mbtiles/MBTilesGetMapOutputFormatTest.java
Backports 3 commits from main, all improving the GeoPackage community module:
- [GEOS-10311] GeoPackage process cannot use layer groups and vendor parameters like the WMS output format does
- [GEOS-8262] GeoPackage tile matrix set extents not set correctly
- [GEOS-10313] Support WMS rendering timeout in GeoPackage WMS output, support cancellation in WPS process
> GeoPackage community module improvemets, cumulative 2.20.x backport

- src/wfs/src/main/java/org/geoserver/wfs/response/CSVOutputFormat.java
- src/wfs/src/test/java/org/geoserver/wfs/response/CSVOutputFormatTest.java
[![GEOS-10318](https://badgen.net/badge/JIRA/GEOS-10318/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10318)
When we activate complex to simple features automatic transformation, CSV output format for complex features doesn't resolve namespace URIs to prefixes on attributes names, making the attributes output use the entire URLs even having the namespace prefix registered on GeoServer catalog.
This PR introduce a resolving method to allow having attributes with prefixes.
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-10318
> [GEOS-10318] Resolve attribute prefix name from GeoServer catalog on CSV output for complex features

- src/wms/src/main/java/org/geoserver/wms/featureinfo/LayerIdentifier.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/RasterLayerIdentifier.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/VectorBasicLayerIdentifier.java
- src/wms/src/main/java/org/geoserver/wms/map/RasterSymbolizerVisitor.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java
- src/wms/src/test/resources/org/geoserver/wms/wms_1_1_1/footprints.sld
- src/wms/src/test/resources/org/geoserver/wms/wms_1_1_1/rainContour.sld
[![GEOS-10320](https://badgen.net/badge/JIRA/GEOS-10320/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10320)
Will not compile until https://github.com/geotools/geotools/pull/3695 is merged.
> [GEOS-10320] Support GetFeatureInfo on raster layers with transformations turning the output into vector

- src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
- src/gwc/src/test/java/org/geoserver/gwc/layer/GeoServerTileLayerTest.java
[![GEOS-10249](https://badgen.net/badge/JIRA/GEOS-10249/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10249)
2.20.x backport of https://github.com/geoserver/geoserver/pull/5301
> [GEOS-10249] GWC produce NPE when it comes to race condition (2.20.x)

- src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
- src/main/src/test/java/org/geoserver/config/util/XStreamPersisterTest.java
[![GEOS-10332](https://badgen.net/badge/JIRA/GEOS-10332/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10332)
> [GEOS-10332] GrowableInternationalStringConverter can cause random XStream conversion failures

- src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
- src/main/src/test/java/org/geoserver/config/util/XStreamPersisterTest.java
[![GEOS-10332](https://badgen.net/badge/JIRA/GEOS-10332/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10332)
> [GEOS-10332] GrowableInternationalStringConverter can cause random XStream conversion failures (2.20.x)

- src/pom.xml
[![GEOS-10335](https://badgen.net/badge/JIRA/GEOS-10335/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10335)
See ticket, and also http://geoserver.org/announcements/2021/12/13/logj4-rce-statement.html
Re-packaged log4j-1.2.17 comes from here: https://github.com/aaime/log4j/tree/1.2.17.x
> [GEOS-10335] Update GeoServer to a log4j version that does not support RCEs

- src/web/wfs/src/main/resources/GeoServerApplication.properties
This pull request is part of the effort to enable synchronisation with Transifex in order to improve the translations of GeoServer. To make sure that the file is detected as ISO-8859-1, we test to add a comment with ISO-8859-1 character in one of the property file.
> [Transifex] Add specific character to force file encoding

- src/pom.xml
[![GEOS-10338](https://badgen.net/badge/JIRA/GEOS-10338/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10338)
Dependency upgrade from 2.6.0 to 2.6.0.1.
See http://www.jdom.org/news/index.html for the list of changes.
The key users of this dependency are app-schema and netcdf/grib.
> [GEOS-10338] Upgrade jdom dependency

- src/extension/importer/core/src/main/java/org/geoserver/importer/ImportContext.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
- src/extension/importer/core/src/test/java/org/geoserver/importer/ImporterDataTest.java
[![GEOS-10337](https://badgen.net/badge/JIRA/GEOS-10337/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10337)
Backport from main (does not contain the new COMPLETE_ERROR state to avoid introducing behavioral changes in a stable series).
> [GEOS-10337] Harden importer against failed imports, make failures more evident (2.19.x)

- src/extension/importer/core/src/main/java/org/geoserver/importer/ImportContext.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
- src/extension/importer/core/src/test/java/org/geoserver/importer/ImporterDataTest.java
[![GEOS-10337](https://badgen.net/badge/JIRA/GEOS-10337/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10337)
Backport from main (does not contain the new COMPLETE_ERROR state to avoid introducing behavioral changes in a stable series).
> [GEOS-10337] Harden importer against failed imports, make failures more evident (2.20.x)

- src/wms/src/main/java/org/geoserver/wms/map/DirectRasterRenderer.java
- src/wms/src/test/java/org/geoserver/wms/map/RenderedImageMapOutputFormatExtendedTest.java
[![GEOS-10341](https://badgen.net/badge/JIRA/GEOS-10341/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10341)
[GEOS-10341]
> [GEOS-10341]: Interpolation not being propagated to the reader when a renderingTransformation is involved

- src/wms/src/main/java/org/geoserver/wms/map/DirectRasterRenderer.java
- src/wms/src/test/java/org/geoserver/wms/map/RenderedImageMapOutputFormatExtendedTest.java
[![GEOS-10341](https://badgen.net/badge/JIRA/GEOS-10341/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10341)
backporting GEOS-10341 to 2.20.x
> [Backport-2.20.x][GEOS-10341]: Interpolation not being propagated to the reader when a renderingTransformation is involved

- .github/workflows/macos.yml
- .github/workflows/windows.yml
Noticed build failing in OSX only, which could be explained by stale jars.
In theory the cached repo should not have any SNAPSHOT, but in practice I don't see jar downloads in the build logs so... forcing the update like in the Linux builds might be a good idea.
Noticed it was missing in the Windows builds too, so added it there as well.
> Unlike Linux builds, Windows and OSX ones do not force an update of snapshots

- doc/en/developer/source/programming-guide/wps-services/design-guide.rst
- doc/en/user/source/installation/war.rst
Do not make it too easy for the script-kiddy attacker and hide the tomcat version.
There is no related GEOS-xxxxxx ticket, because the PR is due to the mail to your security list.
> Tomcat hardening added

- src/extension/feature-pregeneralized/src/main/java/org/geoserver/data/gen/DSFinderRepository.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/FreeMarkerTemplateManager.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/FreemarkerStaticsAccessRule.java
Some classes used log4j loggers directly instead of following
GeoServer's convention of using jul logging and obtaining them
from GeoTools' Logging.getLogger() utility.
> Replace direct use of log4j loggers by j.u.l through GeoTools Logging utility class

- src/community/netcdf-ghrsst/pom.xml
- src/extension/netcdf-out/pom.xml
[![GEOS-10350](https://badgen.net/badge/JIRA/GEOS-10350/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10350)
Upgrade NetCDF to 4.6.19 to address security vulnerabilities in third-party libraries in Dependency Check scans.
Related to https://github.com/geotools/geotools/pull/3728
gs-netcdf extension already inherits its NETCDF dependencies from gt-netcdf and doesn't define its own NETCDF version so it didn't need any changes.
gs-netcdf-out extension had all of its NETCDF dependencies removed so that they are now inherited from gs-netcdf and it no longer needs the netcdf.version property.
gs-netcdf-ghrsst community module had all of its NETCDF dependencies removed so that they are now inherited from gs-netcdf-out but it still needs the netcdf.version property to put in a properties …
> [GEOS-10350] Upgrade NetCDF to 4.6.19

- doc/en/user/source/community/features-templating/directives.rst
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/TemplateBuilderMaker.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/DynamicIncludeFlatBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/DynamicMergeBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/DynamicValueBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/JSONTemplateReader.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/RecursiveJSONParser.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/builders/impl/DynamicIncludeFlatBuilderTest.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/readers/JSONIncludesTest.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/writers/JsonWriterTest.java
- src/community/features-templating/features-templating-core/src/test/resources/jsonIncludes/dynamicIncludeFlat.json
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/ItemsTest.java
- src/community/oseo/oseo-stac/src/test/resources/items-LANDSAT8.json
[![GEOS-10319](https://badgen.net/badge/JIRA/GEOS-10319/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10319)
Backport of [GEOS-10319](https://github.com/geoserver/geoserver/pull/5418/commits) includeFlat a JSON database field to a features template
> [2.20.x][GEOS-10319] includeFlat a JSON database field to a features template

- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/AccessManagerTest.java
[![GEOS-10183](https://badgen.net/badge/JIRA/GEOS-10183/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10183)
JIRA TICKET: [GEOS-10183](https://osgeo-org.atlassian.net/browse/GEOS-10183)
> [GEOS-10183] Geofence-server extension seems to not work as expected with Chrome

- src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
- src/wms/src/test/java/org/geoserver/wms/LegendNonValidCapabilitiesTest.java
- src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesLegendURLTest.java
- src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesReponseTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/LegendCapabilitiesTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/LegendCapabilitiesTest.java
[![GEOS-10336](https://badgen.net/badge/JIRA/GEOS-10336/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10336)
WMS Version propagation issue in the Legend URL has been fixed.
> [GEOS-10336]-INSPIRE failure: version not propagated in GetCapabilities LegendURL

- src/main/src/main/java/org/geoserver/catalog/impl/AttributeTypeInfoImpl.java
- src/main/src/test/java/org/geoserver/catalog/impl/FeatureTypeInfoImplTest.java
Fix AttributeTypeInfoImpl.equals() and hashCode() after new source property
> Fix AttributeTypeInfoImpl.equals() and hashCode() after new source and nillable properties

- doc/en/user/source/rest/api/featuretypes.rst
[![GEOS-10101](https://badgen.net/badge/JIRA/GEOS-10101/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10101)
> [GEOS-10101] Recalculating a featuretype via geoserver rest, fails if the SRS handling is set to Keep Native

- src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
- src/main/src/test/java/org/geoserver/config/util/XStreamPersisterTest.java
[![GEOS-10332](https://badgen.net/badge/JIRA/GEOS-10332/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10332)
Growable International String and Simple International String conversion failure in XStreamPersister has been fixed.
> [GEOS-10332]-GrowableInternationalStringConverter can cause random XStream conversion failures

- src/main/src/main/java/org/geoserver/security/decorators/SecuredWebMapTileServer.java
Follows up with https://github.com/geotools/geotools/pull/3737
> Fixing QA build after method deprecation in WMTSServer

- src/community/ncwms/src/main/java/org/geoserver/wms/ncwms/NcWmsService.java
- src/community/ncwms/src/test/java/org/geoserver/wms/ncwms/NcWmsGetTimeSeriesTest.java
- src/main/src/main/java/org/geoserver/catalog/util/ReaderDimensionsAccessor.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DimensionsRasterGetFeatureInfoTest.java
[![GEOS-10373](https://badgen.net/badge/JIRA/GEOS-10373/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10373)
See ticket.
> [GEOS-10373] GetTimeSeries does not work on source data with time ranges

- src/community/ncwms/src/main/java/org/geoserver/wms/ncwms/NcWmsService.java
- src/community/ncwms/src/test/java/org/geoserver/wms/ncwms/NcWmsGetTimeSeriesTest.java
- src/main/src/main/java/org/geoserver/catalog/util/ReaderDimensionsAccessor.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DimensionsRasterGetFeatureInfoTest.java
[![GEOS-10373](https://badgen.net/badge/JIRA/GEOS-10373/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10373)
> [GEOS-10373] GetTimeSeries does not work on source data with time ranges (2.20.x)

- src/main/src/main/java/org/geoserver/security/SecuredResourceNameChangeListener.java
- src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java
- src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
[![GEOS-10371](https://badgen.net/badge/JIRA/GEOS-10371/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10371)
When a `LayerGroup` that belongs to a `Workspace` is removed,
its associated data access rules are removed.
When a root `LayerGropup` (i.e. null workspace) is removed,
its associated data access rules are not removed. Instead,
a `NullPointerException` is logged.
`SecuredResourceNameChangeListener` doesn’t check if a
`LayerGroup.getWorkspace()` is null, resuling in an NPE,
logged as a warning.
This patch simplifies the logic in `SecuredResourceNameChangeListener` that
would otherwise result in even more if-else clauses, makes sure
root layer group rules are treated properly, and adds test cases
for that, and for the rename cases, which weren't covered at all.
For core and …
> [GEOS-10371] Removing LayerGroup does not remove associated data access rules

- src/community/mbtiles/src/main/java/org/geoserver/mbtiles/gs/wps/MBTilesProcess.java
- src/ows/src/main/java/org/geoserver/ows/KvpParser.java
- src/ows/src/main/java/org/geoserver/ows/kvp/URIKvpParser.java
- src/ows/src/main/java/org/geoserver/ows/kvp/URLKvpParser.java
- src/ows/src/test/java/org/geoserver/ows/kvp/URIKvpParserTest.java
- src/wms/src/main/java/applicationContext.xml
- src/wms/src/main/java/org/geoserver/wms/GetMapRequest.java
- src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java
- src/wms/src/test/java/org/geoserver/wms/WMSRequestsTest.java
- src/wms/src/test/java/org/geoserver/wms/map/GetMapKvpRequestReaderTest.java
[![GEOS-10384](https://badgen.net/badge/JIRA/GEOS-10384/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10384)
By using URI we can avoid creating URL until needed for connection.
> [GEOS-10384] Change GetMap to URIKvpParser

- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/DynamicIncludeFlatBuilder.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/readers/JSONIncludesTest.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/readers/JSONMergesTest.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/readers/XmlTemplateReaderTest.java
- src/community/oseo/oseo-core/src/test/resources/product_test_data.sql
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACQueryablesBuilder.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/TemplatePropertyVisitor.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/STACQueryablesBuilderTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/STACSortablesMapperTest.java
- src/community/oseo/oseo-stac/src/test/resources/items-SAS1.json
[![GEOS-10388](https://badgen.net/badge/JIRA/GEOS-10388/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10388)
See ticket. Also includes a build fix in features templating test.
> [GEOS-10388] STAC cannot extract queryables/sortables when a dynamic includeFlat is used in the items template

- src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
- src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformerTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesIntegrationTest.java
[![GEOS-10377](https://badgen.net/badge/JIRA/GEOS-10377/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10377)
This PR is a backport to 2.20.x.
> [GEOS-10377] Emitting an empty Abstract element when no abstract set on Layer or LayerGroup.

- src/wms/src/test/java/org/geoserver/wms/wms_1_3/WMSCascadeTest.java
[![GEOS-9770](https://badgen.net/badge/JIRA/GEOS-9770/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9770)
This changes are made to fix GEOS-9770.
- The fix is made in geotools but there is a test adaptation to this fix. The old test had unreasonable I and J values, they would have been way outside of the GetMap extents.
- A mocked httpClient has to respond to a different GET parameters
Depends on https://github.com/geotools/geotools/pull/3777, build won't be green until that one is merged.
For core and extension modules: (not applicable for this PL)
> [GEOS-9770] Cascading WMS server sets invalid I and J when doing GetFeatureInfo calls

- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterEstimator.java
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
[![GEOS-9785](https://badgen.net/badge/JIRA/GEOS-9785/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9785)
[GEOS-9785]Wps download fails estimate (Invalid argument type=null when trying to use gs:Download WPS identifier)
> [GEOS-9785] Wps download fails estimate (2.19.X)

- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterEstimator.java
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
[![GEOS-9785](https://badgen.net/badge/JIRA/GEOS-9785/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9785)
[GEOS-9785]Wps download fails estimate (Invalid argument type=null when trying to use gs:Download WPS identifier)
> [GEOS-9785] Wps download fails estimate (2.20.X)

- src/wms/src/test/java/org/geoserver/wms/wms_1_3/WMSCascadeTest.java
[![GEOS-9770](https://badgen.net/badge/JIRA/GEOS-9770/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9770)
Backported from https://github.com/geoserver/geoserver/pull/5675
*For this PL to pass check, geotools 26.x must be built and deployed before*
> [GEOS-9770] Cascading WMS server sets invalid I and J when using EPSG:3006 on GetFeatureInfo calls(2.20.X)

- src/main/src/main/java/org/geoserver/util/AllowListEntityResolver.java
[![GEOS-10389](https://badgen.net/badge/JIRA/GEOS-10389/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10389)
Checking URI vs URL is not required, and use of URL may cause DNS resolution
> [GEOS-10389] Use URI for AllowListEntityResolver

- doc/en/user/source/services/wms/webadmin.rst
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReader.java
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReaderTest.java
[![GEOS-10400](https://badgen.net/badge/JIRA/GEOS-10400/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10400)
This PR updates WMS GetLegendGraphic requests to use the existing WMS setting for disabling dynamic styling.
> [GEOS-10400] Disabling WMS dynamic styling does not affect GetLegendGraphic requests

- src/community/security/keycloak/pom.xml
- src/pom.xml
[![GEOS-7606](https://badgen.net/badge/JIRA/GEOS-7606/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-7606)
The current version 4.5.13 remains unchanged, the community keycloak module had hardcoded a prior version by accident.
Note gs-main continues to require classic commons-httpclient 3.1 for some reason.
> [GEOS-7606] Manage httpclient version using dependency managaement and httpclient.version property

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/resource/WPSResourceManager.java
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/response/StoredResourceResponse.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/GetExecutionResultTest.java
[![GEOS-10401](https://badgen.net/badge/JIRA/GEOS-10401/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10401)
2.20.x backport for https://github.com/geoserver/geoserver/pull/5701
> [2.20.x][GEOS-10401] WPS GetExecutionResult doesn't validate the mimetype parameter

- doc/en/user/source/services/wms/webadmin.rst
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReader.java
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReaderTest.java
[![GEOS-10400](https://badgen.net/badge/JIRA/GEOS-10400/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10400)
2.20.x backport for https://github.com/geoserver/geoserver/pull/5700
> [2.20.x][GEOS-10400] Disabling WMS dynamic styling does not affect GetLegendGraphic requests

- src/wms/src/main/java/org/geoserver/wms/clip/ClipWMSGetMapCallBack.java
- src/wms/src/test/java/org/geoserver/wms/map/GetMapIntegrationTest.java
[![GEOS-9978](https://badgen.net/badge/JIRA/GEOS-9978/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9978)
See ticket
> [GEOS-9978] WMS vendor parameter CLIP - ignores TIME/CQL_FILTER and other parameters when using with ImageMosaic

- src/wms/src/main/java/org/geoserver/wms/clip/ClipWMSGetMapCallBack.java
- src/wms/src/test/java/org/geoserver/wms/map/GetMapIntegrationTest.java
[![GEOS-9978](https://badgen.net/badge/JIRA/GEOS-9978/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9978)
> [GEOS-9978] WMS vendor parameter CLIP - ignores TIME/CQL_FILTER and other parameters when using with ImageMosaic ( 2.20.x backport)

- src/extension/inspire/src/main/java/org/geoserver/inspire/ServicesUtils.java
- src/extension/inspire/src/test/java/org/geoserver/inspire/wms/WMSExtendedCapabilitiesTest.java
[![GEOS-10411](https://badgen.net/badge/JIRA/GEOS-10411/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10411)
> [GEOS-10411] Incorrect Encoding of Language in INSPIRE extension

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIFilterParser.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/FeatureService.java
- src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/features/openapi.yaml
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/ApiTest.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/FeatureTest.java
[![GEOS-10404](https://badgen.net/badge/JIRA/GEOS-10404/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10404)
This PR adds support for the `filter-crs` query parameter for `OGC API - Features` service.
> [GEOS-10404]-OGCAPI Support `filter-crs` query parameter

- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceGetMapIntegrationTest.java
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceWMSTestSupport.java
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GetLegendGraphicGeofenceTest.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
[![GEOS-10274](https://badgen.net/badge/JIRA/GEOS-10274/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10274)
> [2.20.x backport] [GEOS-10274] Geofence follow up LayerGroup Style addition

- src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
- src/main/src/main/java/org/geoserver/config/util/XStreamPersisterFactory.java
- src/pom.xml
- src/rest/src/main/java/org/geoserver/rest/converters/XStreamCatalogListConverter.java
- src/rest/src/main/java/org/geoserver/rest/converters/XStreamJSONMessageConverter.java
- src/restconfig/src/main/java/org/geoserver/rest/resources/ResourceController.java
- src/restconfig/src/main/java/org/geoserver/rest/resources/ResourceDirectoryInfoJSONConverter.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/CoverageControllerTest.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/StyleControllerTest.java
- src/restconfig/src/test/java/org/geoserver/rest/resources/ResourceControllerTest.java
- src/restconfig/src/test/java/org/geoserver/rest/security/XStreamParserTest.java
- src/restconfig/src/test/java/org/geoserver/rest/system/status/MonitorRestTest.java
Upgrading to XStream 1.4.19/Jettison 1.4.1.
Jettison 1.4.1 changes its deafult behavior when
encoding single-element collections as JSON.
While it used to encode such collections as a JSON
object, it now (correctly/consistently) encodes
them as single-element JSON arrays.
Such change would break backwards compatibility
in several GeoServer REST API responses, despite
JSON collection encoding being consistent, we can't
know for sure it wouldn't break exising API clients.
Therefore, measures are taken to preserve the old
behavior where single-element collections are serialized
as a JSON object instead of a single-element JSON array.
For instance:
- `XStreamCatalogListConverter$JSONXStreamListConverter` will
recognize a single-element list, and use a surrogate object to
force serialization …
> Dependency upgrade: xstream 1.4.11.1 -> 1.4.19, jettison 1.0.1 -> 1.4.1

- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceGetMapIntegrationTest.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
[![GEOS-10418](https://badgen.net/badge/JIRA/GEOS-10418/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10418)
> [GEOS-10418] Bad request sent to GeoFence when matching roles only

- doc/en/user/source/extensions/geofence/configuration.rst
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceGetMapIntegrationTest.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
[![GEOS-10420](https://badgen.net/badge/JIRA/GEOS-10420/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10420)
> [GEOS-10420] GeoFence group list is too limiting

- src/community/csw-iso/src/main/java/org/geoserver/csw/records/iso/MetaDataDescriptor.java
- src/community/csw-iso/src/main/resources/net/opengis/schemas/iso/19139/20070417/srv/serviceMetadata.xsd
- src/community/csw-iso/src/main/resources/net/opengis/schemas/iso/19139/20070417/srv/serviceModel.xsd
- src/community/csw-iso/src/main/resources/schemas/iso/19139/20070417/srv/serviceMetadata.xsd
- src/community/csw-iso/src/main/resources/schemas/iso/19139/20070417/srv/serviceModel.xsd
- src/community/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/GetRecordByIdTest.java
- src/community/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/GetRecordsTest.java
- src/community/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/MDTestSupport.java
- src/community/csw-iso/src/test/resources/org/geoserver/csw/store/internal/MD_Metadata.properties
[![GEOS-10447](https://badgen.net/badge/JIRA/GEOS-10447/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10447)
> [GEOS-10447] support Metadata for Services (SRV) in csw-iso (backport)

- doc/en/user/source/extensions/importer/rest_reference.rst
- src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
- src/extension/importer/core/src/test/java/org/geoserver/importer/ImporterDataTest.java
[![GEOS-10444](https://badgen.net/badge/JIRA/GEOS-10444/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10444)
Importer: Add support for UpdateMode.REPLACE  on raster too
- x ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
> [GEOS-10444]: Supporting REPLACE UpdateMode on rasters import

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/gs/ImportProcess.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/ImportProcessTest.java
[![GEOS-10427](https://badgen.net/badge/JIRA/GEOS-10427/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10427)
2.20.x backport for https://github.com/geoserver/geoserver/pull/5735
> [2.20.x][GEOS-10427] Improve access check in ImportProcess

- src/pom.xml
- src/release/bin.xml
- src/release/pom.xml
[![GEOS-10442](https://badgen.net/badge/JIRA/GEOS-10442/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10442)
This removes the obsolete jasper dependency.
That is an old tomcat entity for JSP support, which we don't appear to need. It was packaged in the bin (jetty) release package, and I have verified that it the -bin package is still OK without it.
This is an alternative …
> [GEOS-10442] Upgrade or remove jasper dependencies

- src/community/ncwms/src/main/java/org/geoserver/wms/ncwms/NcWmsService.java
- src/community/ncwms/src/test/java/org/geoserver/wms/ncwms/NcWmsGetTimeSeriesTest.java
[![GEOS-10448](https://badgen.net/badge/JIRA/GEOS-10448/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10448)
See ticket
> [GEOS-10448] GetTimeSeries does not limit number of dates when using a time range request (without period)

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIFilterParser.java
- src/community/oseo/oseo-service/src/test/java/org/geoserver/opensearch/eo/SearchTest.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/SearchQuery.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/SearchTest.java
[![GEOS-10451](https://badgen.net/badge/JIRA/GEOS-10451/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10451)
added tests
> [GEOS-10451] Support in OSEO for POST queries with CQL

- src/pom.xml
[![GEOS-10446](https://badgen.net/badge/JIRA/GEOS-10446/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10446)
Bumps commons-codec from 1.9 to 1.15 (current release). https://commons.apache.org/proper/commons-codec/changes-report.html shows the changes per release.
> [GEOS-10446] Upgrade commons-codec version

- src/community/ncwms/src/main/java/org/geoserver/wms/ncwms/NcWmsService.java
- src/community/ncwms/src/test/java/org/geoserver/wms/ncwms/NcWmsGetTimeSeriesTest.java
[![GEOS-10448](https://badgen.net/badge/JIRA/GEOS-10448/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10448)
> [GEOS-10448] GetTimeSeries does not limit number of dates when using a time range request (without period) (2.20.x)

- src/pom.xml
Upgrading spotless `2.20.0` to `2.20.21`, which supports
`git worktree` checkouts as of https://github.com/diffplug/spotless/pull/1119.
2.20.0 fails with an exception like the following for each module:
```
[INFO] --- spotless-maven-plugin:2.20.0:apply (default) @ geoserver---
[ERROR] /git/geoserver/main/.git/config: Not a directory
java.nio.file.FileSystemException: /home/groldan/git/geoserver/geoserver/master/.git/config: Not a directory
at sun.nio.fs.UnixException.translateToIOException (UnixException.java:100)
at sun.nio.fs.UnixException.rethrowAsIOException (UnixException.java:111)
at sun.nio.fs.UnixException.rethrowAsIOException (UnixException.java:116)
```
> Upgrade spotless-maven-plugin to latest version supporting git worktree checkouts

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIConfigurationSupport.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIDispatcher.java
With this change the OGC API and REST API seem to be both functional.
> Allow OGC API and REST to coexist

- src/community/metadata/pom.xml
- src/community/ogcapi/ogcapi-core/pom.xml
- src/pom.xml
[![GEOS-10308](https://badgen.net/badge/JIRA/GEOS-10308/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10308)
Centralizes versions management of a couple of Jackson jars.
Backport from main, it fixes both the OGC API and the COG issues reported by users:
* https://osgeo-org.atlassian.net/browse/GEOS-10459
* https://osgeo-org.atlassian.net/browse/GEOS-10461
> [GEOS-10308] GeoServer with OGCAPI fails to deploy (2.20.x)

- src/community/release/ext-backup-restore.xml
[![GEOS-10432](https://badgen.net/badge/JIRA/GEOS-10432/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10432)
> [GEOS-10432] Missing dependency in Backup/Restore plugin assembly (2.20.x)

- src/community/oseo/oseo-core/pom.xml
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/OSEOInfoImpl.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/OSEOXStreamLoader.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/OseoEvent.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/Indexable.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCIndex.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccess.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/OpenSearchAccess.java
- src/community/oseo/oseo-core/src/test/java/org/geoserver/opensearch/eo/OSEOXStreamLoaderTest.java
- src/community/oseo/oseo-core/src/test/resources/postgis.sql
- src/community/oseo/oseo-rest/src/main/java/org/geoserver/opensearch/rest/CollectionsController.java
- src/community/oseo/oseo-service/src/test/java/org/geoserver/opensearch/eo/SearchTest.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/CollectionsCache.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACOseoListener.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACQueryablesBuilder.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/STACQueryableIndexTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/STACQueryablesBuilderTest.java
First two commits avoid NPEs on un-configured queryables at the global and per collection level.
The third is a set of improvements on automatic index management:
* Do a diff of queryables on reconfiguration, touch only the indexes that need to be created/destroyed
* Make sure all code paths map back to database properties (json path did, simple properties didn't)
* General code simplification (try-with-resouces, exception handling)
@turingtestfail could you have a look?
> STAC queryables and indexing handling improvements

- src/main/src/main/resources/schemas/sld/StyledLayerDescriptor.xsd
- src/main/src/test/java/org/geoserver/catalog/StylesTest.java
- src/main/src/test/java/org/geoserver/data/test/normalized.sld
[![GEOS-10477](https://badgen.net/badge/JIRA/GEOS-10477/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10477)
> [GEOS-10477] validation error on normalize node

- src/main/src/main/resources/schemas/sld/StyledLayerDescriptor.xsd
- src/main/src/test/java/org/geoserver/catalog/StylesTest.java
- src/main/src/test/java/org/geoserver/data/test/normalized.sld
[![GEOS-10477](https://badgen.net/badge/JIRA/GEOS-10477/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10477)
> [GEOS-10477] validation error on normalize node (2.20.x)

- src/main/src/main/resources/schemas/sld/StyledLayerDescriptor.xsd
- src/main/src/test/java/org/geoserver/catalog/StylesTest.java
- src/main/src/test/java/org/geoserver/data/test/normalized.sld
[![GEOS-10477](https://badgen.net/badge/JIRA/GEOS-10477/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10477)
> [GEOS-10477] validation error on normalize node (#5844) (2.19.x)

- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceAccessManagerIntegrationTest.java
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceIntegrationTestSupport.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/GeoFenceConfigurationManagerTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/GeofenceAccessManagerTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/GeofenceAccessManager_WMTSLayerTest.java
[![GEOS-10074](https://badgen.net/badge/JIRA/GEOS-10074/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10074)
Admin rules grant ADMIN access to unauthorized user
Rules didn't filter properly on user/roles and there were no tests for them.
[ticket](https://osgeo-org.atlassian.net/browse/GEOS-10074)
[reported as geofence issue](https://github.com/geoserver/geofence/issues/140)
- Fix `GeoFenceAccessManager.isWorkspaceAdmin()`: When a user name is
not provided, using a `RuleFilter` with `SpecialFilterType.ANY`
instead of `SpecialFilterType.DEFAULT` results in admin access to all
workspaces that have an AdminRule set, regardless of the user/role.
- Add `AdminRule` tests, introduce `GeofenceIntegrationTestSupport`
class to group utility methods and setup/cleanup.
> Reviewing is a process …
> [GEOS-10074] GeoFence "Admin rules" grant "ADMIN" access to unauthorized users

- doc/en/user/source/extensions/wmts-multidimensional/usage.rst
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/DescribeDomainsTransformer.java
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/MultiDimensionalExtension.java
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/ComparableRange.java
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/CoverageDimensionsReader.java
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/Dimension.java
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/DimensionsUtils.java
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/HistogramUtils.java
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/VectorDimension.java
- src/extension/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/MultiDimensionalExtensionTest.java
- src/extension/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/TestsSupport.java
- src/extension/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/VectorElevationDimensionTest.java
- src/extension/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/VectorTimeDimensionTest.java
- src/extension/wmts-multi-dimensional/src/test/resources/TimeElevationWithStartEnd.properties
[![GEOS-10471](https://badgen.net/badge/JIRA/GEOS-10471/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10471)
> [GEOS-10471] WMTS MultiDim - Support also endAttribute

- doc/en/user/source/extensions/geofence/configuration.rst
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceGetMapIntegrationTest.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
[![GEOS-10420](https://badgen.net/badge/JIRA/GEOS-10420/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10420)
> [2.20.x backport] [GEOS-10420] GeoFence group list is too limiting (#5766)

- src/restconfig/src/test/java/org/geoserver/rest/resources/ResourceControllerTest.java
[![GEOS-10484](https://badgen.net/badge/JIRA/GEOS-10484/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10484)
While I was at it, made the method name follow Java conventions.
> [GEOS-10484] JDK 17 failure in ResourceControllerTest#testDirectoryJSON_multiple_children

- src/restconfig/src/test/java/org/geoserver/rest/resources/ResourceControllerTest.java
[![GEOS-10484](https://badgen.net/badge/JIRA/GEOS-10484/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10484)
> [GEOS-10484] JDK 17 failure in ResourceControllerTest#testDirectoryJSON_multiple_children (2.21.x)

- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/ogcapi/dggs/DGGSGeoJSONResponse.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIRequestInfo.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/RFCGeoJSONFeaturesResponse.java
ogc-features introduce two GeoJSON output formats:
- RFCGeoJSONFeaturesResponse
- DGGSGeoJSONResponse
As such, they're listed in WFS GetCapabilities as GetFeature
operation's output formats, besides the usual 'application/json'
one.
When feature collection is requested through WFS with output
format application/geo+json, an NPE exeption is thrown once
it streamed the features and calls writeLinks(), resulting
in an XML exception report mixed up with the JSON output.
This patch checks whether APIRequestInfo.get() returns null,
which means the response being produced by these new encoders
is not coming from an ogc-api endpoint, and avoids using
APIRequestInfo to write json links.
Longer term it'd probably be better for these ogcapi-specific output formats be
ignored by WFS, but that's at …
> ogcapi's geo+json output formats cause NPE when request comes from WFS

- src/wfs/src/main/java/org/vfny/geoserver/wfs/servlets/TestWfsPost.java
- src/wfs/src/test/java/org/vfny/geoserver/wfs/servlets/TestWfsPostTest.java
[![GEOS-10479](https://badgen.net/badge/JIRA/GEOS-10479/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10479)
This PR blocks using the ".." sequence in the URL and also reverts some weakening of the URL validation from https://github.com/geoserver/geoserver/commit/5facd7a786b817a08036e9a8d07776bc7b5b5f97 by adding back validation of the URL protocol, port and path instead of only validating the host.
> [GEOS-10479] Improve TestWfsPost URL validation

- src/wfs/src/main/java/org/vfny/geoserver/wfs/servlets/TestWfsPost.java
- src/wfs/src/test/java/org/vfny/geoserver/wfs/servlets/TestWfsPostTest.java
[![GEOS-10479](https://badgen.net/badge/JIRA/GEOS-10479/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10479)
2.21.x backport for https://github.com/geoserver/geoserver/pull/5848
> [2.21.x][GEOS-10479] Improve TestWfsPost URL validation

- src/extension/wps/wps-kml-ppio/src/main/java/org/geoserver/wps/ppio/KMLPPIO.java
- src/extension/wps/wps-kml-ppio/src/main/resources/applicationContext.xml
- src/extension/wps/wps-kml-ppio/src/test/java/org/geoserver/wps/ppio/KMLPPIOTest.java
[![GEOS-10481](https://badgen.net/badge/JIRA/GEOS-10481/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10481)
This PR sets the entity resolver in the KML PPIO.
> [GEOS-10481] KML PPIO does not set the entity resolver

- src/extension/wps/wps-kml-ppio/src/main/java/org/geoserver/wps/ppio/KMLPPIO.java
- src/extension/wps/wps-kml-ppio/src/main/resources/applicationContext.xml
- src/extension/wps/wps-kml-ppio/src/test/java/org/geoserver/wps/ppio/KMLPPIOTest.java
[![GEOS-10481](https://badgen.net/badge/JIRA/GEOS-10481/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10481)
2.21.x backport for https://github.com/geoserver/geoserver/pull/5859
> [2.21.x][GEOS-10481] KML PPIO does not set the entity resolver

- src/community/release/ext-oauth2-openid-connect.xml
[![GEOS-10488](https://badgen.net/badge/JIRA/GEOS-10488/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10488)
> [GEOS-10488] OpenId Connect - Missing spring jwt jar in release package

- src/community/release/ext-oauth2-openid-connect.xml
[![GEOS-10488](https://badgen.net/badge/JIRA/GEOS-10488/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10488)
> [2.20.x backport][GEOS-10488] OpenId Connect - Missing spring jwt jar in release package

- doc/en/user/source/community/index.rst
- doc/en/user/source/community/keycloak/authentication.rst
- doc/en/user/source/community/keycloak/index.rst
- doc/en/user/source/community/keycloak/installation.rst
- doc/en/user/source/community/keycloak/keycloak_role_service.rst
The two tutorials appeard as distinct community modules list the list
> gather keycloak docs so they do not appear as two modules

- src/extension/geofence-server/pom.xml
- src/extension/geofence-server/src/main/java/org/geoserver/geofence/internal/InternalUserResolver.java
- src/extension/geofence-server/src/main/java/org/geoserver/geofence/internal/SecurityContextUserResolver.java
- src/extension/geofence-server/src/main/resources/applicationContext.xml
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/internal/InternalUserResolverTest.java
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/internal/SecurityContextUserResolverTest.java
[![GEOS-10492](https://badgen.net/badge/JIRA/GEOS-10492/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10492)
This PR contains a fix for slowness in retrieving role for the logged in user. Instead of depending on the backend to get the role, we will get the user role from the Spring security context as the user is already logged in.
Here is the corresponding JIRA: https://osgeo-org.atlassian.net/browse/GEOS-10492
> [GEOS-10492] GeoFence InternalServer - InternalUserResolver unnecessarily reload Roles from services

- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACService.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/SearchQuery.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/SearchTest.java
[![GEOS-10498](https://badgen.net/badge/JIRA/GEOS-10498/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10498)
> [GEOS-10498] STAC API Search implementation looks for an intersection property in the request, while it should be intersects (2.21.x)

- src/wfs/src/main/java/org/geoserver/wfs/xml/GML2OutputFormat.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/GML3OutputFormat.java
- src/wfs/src/test/java/org/geoserver/wfs/xml/GMLOutputFormatTest.java
This PR makes the GMLFormatters (both 2 and 3.0/3.2) honour the verbose/Pretty print setting in the global settings page.
> [GEOS-10502] GML3 output is not pretty printed when pretty print is turned on in global settings.

- src/wfs/src/main/java/org/geoserver/wfs/xml/GML2OutputFormat.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/GML3OutputFormat.java
- src/wfs/src/test/java/org/geoserver/wfs/xml/GMLOutputFormatTest.java
> [GEOS-10502] Backport to 2.21.x - Honour verbose setting for GML output

- src/wfs/src/main/java/org/geoserver/wfs/xml/GML2OutputFormat.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/GML3OutputFormat.java
- src/wfs/src/test/java/org/geoserver/wfs/xml/GMLOutputFormatTest.java
> [GEOS-10502] Backport to 2.20.x - Honour verbose setting for GML output

- src/wfs/src/main/java/org/geoserver/wfs/xml/GML2OutputFormat.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/GML3OutputFormat.java
- src/wfs/src/test/java/org/geoserver/wfs/xml/GMLOutputFormatTest.java
> [GEOS-10502] Backport to 2.19.x - Honour verbose setting for GML output

- src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
- src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java
[![GEOS-10514](https://badgen.net/badge/JIRA/GEOS-10514/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10514)
> [GEOS-10514]: Better capture catalog configuration issue on layergroup with a layer without resource

- src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
- src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java
[![GEOS-10514](https://badgen.net/badge/JIRA/GEOS-10514/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10514)
Backporting GEOS-10514 to 2.21.x
> [Backport to 2.21.x][GEOS-10514]: Better capture catalog configuration issue on layergroup with a layer without resource

- src/platform/src/main/java/org/geoserver/platform/resource/FileSystemWatcher.java
- src/rest/src/main/java/org/geoserver/rest/RestControllerAdvice.java
- src/rest/src/test/java/org/geoserver/rest/ExceptionHandlingTest.java
- src/rest/src/test/java/org/geoserver/rest/ExceptionThrowingController.java
[![GEOS-10522](https://badgen.net/badge/JIRA/GEOS-10522/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10522)
Check RestControllerAdvise handling of exceptions with null message, added an example to ExceptionHandlingTest (and quieted log messages for this test).
> [GEOS-10522] RestControllerAdvice report exception with null message

- src/community/backup-restore/pom.xml
This PR fixes a Backup & Restore community module issue with JDK 11 build, by adding JAXB dependencies.
> Fix Backup & Restore JDK 11 build adding JAXB dependencies

- .github/workflows/backport.yml
Resurrecting the backport bot, this version runs as a Github action, on PR merge, and uses labels to target the backports.
See https://github.com/tibdex/backport
> Adding backport bot from https://github.com/tibdex/backport

- .github/workflows/backport.yml
Try 2, using same version as QGIS (one difference, they are using a custom token likely related to this user https://github.com/qgis-bot).
> Adding backport bot (same version used by QGIS)

- src/main/src/main/java/org/geoserver/logging/GeoServerXMLConfiguration.java
- src/main/src/test/java/org/geoserver/logging/LoggingStartupContextListenerTest.java
[![GEOS-10487](https://badgen.net/badge/JIRA/GEOS-10487/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10487)
The log4j configuration is case-insenstive, adjusting GeoServerXmlConfiguration to pre-process in a case-insenstive manner.
> [GEOS-10487] Log4J custom logging XML configuration is case-insenstive

- src/wms/src/main/java/org/geoserver/wms/featureinfo/FreeMarkerTemplateManager.java
[![GEOS-10532](https://badgen.net/badge/JIRA/GEOS-10532/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10532)
[GEOS-10532]: FreemarkerTemplateManager changes for subclassing
> [GEOS-10532] FreeMarkerTemplateManager: a few changes for subclassing

- src/wfs/src/main/java/org/geoserver/wfs/DeleteElementHandler.java
- src/wfs/src/test/java/org/geoserver/wfs/TransactionTest.java
[![GEOS-10534](https://badgen.net/badge/JIRA/GEOS-10534/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10534)
> [GEOS-10534] a badly formed delete transaction will get a NPE instead of an informative error message

- src/wfs/src/main/java/org/geoserver/wfs/DeleteElementHandler.java
- src/wfs/src/test/java/org/geoserver/wfs/TransactionTest.java
[![GEOS-10534](https://badgen.net/badge/JIRA/GEOS-10534/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10534)
> [GEOS-10534] avoid NPE when deleting fails (#5935)

- doc/en/user/source/styling/sld/reference/filters.rst
remove duplicated spatial operator
> [doc] Remove duplicate spatial operator from list of operators

- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CoveragesService.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/DomainSetBuilder.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/TimeDimensionHelper.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/cis/GeneralGrid.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/cis/IndexAxis.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/cis/IrregularAxis.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/cis/RegularAxis.java
- src/community/ogcapi/ogcapi-coverages/src/main/resources/org/geoserver/ogcapi/coverages/collection_include.ftl
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/CollectionTest.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/CoverageTest.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/CoveragesTestSupport.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/DomainSetTest.java
[![GEOS-10513](https://badgen.net/badge/JIRA/GEOS-10513/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10513)
Adds temporal representation in the CIS domain set and fixes an issue with low-resolution time specs in time retrieval
> [GEOS-10513] Coverage API Temporal Problems With Input and Retrieval

- src/community/security/oauth2-core/pom.xml
- src/community/security/oauth2-openid-connect/pom.xml
- src/community/security/oauth2-openid-connect/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java
- src/community/security/oauth2-openid-connect/src/test/java/org/geoserver/security/oauth2/OAuth2FilterConfigValidatorTest.java
[![GEOS-10536](https://badgen.net/badge/JIRA/GEOS-10536/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10536)
I tested the current oauth2-openid-connect community module against keycloak acting as an oidc server.
There were two problems (GEOS-10536);
a) The spring oauth2 library was giving an error with the token that keycloak was returning - "enc (use) is currently not supported"
+ This is fixed in later spring oauth2 libraries (it ignores these types of tokens)
+ FIX: update to a newer (2.0.16.RELEASE -> 2.5.2.RELEASE) spring oauth2 library
+ The spring oauth2 module is only used in the oauth2 community modules, so this should be "safe" for the rest of GS
b) Keycloak, by default, will put the roles in the ID Token in a path like "resource_access.CLIENT_NAME.roles"
+ The current …
> [GEOS-10536] Security - oauth2 oidc - changes for keycloak server

- src/main/src/main/java/org/geoserver/security/impl/AbstractRoleStore.java
- src/security/security-tests/src/test/java/org/geoserver/security/xml/XMLRoleServiceTest.java
[![GEOS-10528](https://badgen.net/badge/JIRA/GEOS-10528/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10528)
We noticed that, in when using XML storage for roles, pressing `Remove Selected and remove role associations`, truly removes the group and role associations, but on inspecting the `roles.xml` file, we found an empty user groups tag is still there.
This can create confusion for the system administrators, since the empty tag need not be there anymore.
In this PR, we remove the `groupList` in the above-mentioned case.
> [GEOS-10528] Empty groupList tag remains after group deletion

- src/extension/geofence-server/pom.xml
- src/extension/geofence-server/src/main/java/org/geoserver/geofence/internal/InternalUserResolver.java
- src/extension/geofence-server/src/main/java/org/geoserver/geofence/internal/SecurityContextUserResolver.java
- src/extension/geofence-server/src/main/resources/applicationContext.xml
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/internal/InternalUserResolverTest.java
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/internal/SecurityContextUserResolverTest.java
[![GEOS-10492](https://badgen.net/badge/JIRA/GEOS-10492/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10492)
This PR contains a fix for slowness in retrieving role for the logged in user. Instead of depending on the backend to get the role, we will get the user role from the Spring security context as the user is already logged in.
Here is the corresponding JIRA: https://osgeo-org.atlassian.net/browse/GEOS-10492
> [GEOS-10492] GeoFence InternalServer - InternalUserResolver unnecessarily reload Roles from services (2.20.x)

- src/extension/geofence-server/pom.xml
- src/extension/geofence-server/src/main/java/org/geoserver/geofence/internal/InternalUserResolver.java
- src/extension/geofence-server/src/main/java/org/geoserver/geofence/internal/SecurityContextUserResolver.java
- src/extension/geofence-server/src/main/resources/applicationContext.xml
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/internal/InternalUserResolverTest.java
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/internal/SecurityContextUserResolverTest.java
[![GEOS-10492](https://badgen.net/badge/JIRA/GEOS-10492/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10492)
This PR contains a fix for slowness in retrieving role for the logged in user. Instead of depending on the backend to get the role, we will get the user role from the Spring security context as the user is already logged in.
Here is the corresponding JIRA: https://osgeo-org.atlassian.net/browse/GEOS-10492
> [GEOS-10492] GeoFence InternalServer - InternalUserResolver unnecessarily reload Roles from services (2.21.x)

- doc/en/user/source/geowebcache/index.rst
The link for GeoWebCache wasn't correct and lead to a non-existent website. This fixes it.
> Fix GeoWebCache URL

- doc/en/user/source/extensions/geofence-server/gui.rst
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceAccessManagerIntegrationTest.java
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceGetMapIntegrationTest.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/ContainerLimitResolver.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeoFenceAreaHelper.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
[![GEOS-10548](https://badgen.net/badge/JIRA/GEOS-10548/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10548)
This pr fix GeoFence behaviour when dealing with layer groups. This code changes allow the following handling:
When a LayerGroup is requested:
* a limit applied to the layer groups (allowed area or grant type) will be applied to all the contained layers.
* if the access rule a contained layer is denying the access to the layer for the user requesting group, the layer will not be present in the output.
* if the access rule of the layer has limits on its own, they will be merged in a restrictive way (intersection) with the one of the layer group if both the limits have been defined for the same role.
* if the access rule of the layer has limits on its own, they will be merged …
> [GEOS-10548] GeoFence layer group handling is inconsistent

- doc/en/user/source/extensions/geofence-server/gui.rst
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceAccessManagerIntegrationTest.java
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceGetMapIntegrationTest.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/ContainerLimitResolver.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeoFenceAreaHelper.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
[![GEOS-10548](https://badgen.net/badge/JIRA/GEOS-10548/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10548)
* [GEOS-10548] GeoFence layer group handling is inconsistent
* review feedback applied
> [2.20.x backport][GEOS-10548] GeoFence layer group handling is inconsistent (#5969)

- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
- src/extension/geofence/src/main/resources/applicationContext.xml
- src/main/pom.xml
- src/main/src/main/java/applicationContext.xml
- src/main/src/main/java/org/geoserver/security/SecureCatalogImpl.java
- src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java
- src/main/src/main/java/org/geoserver/security/impl/LayerGroupContainmentCache.java
- src/main/src/test/java/org/geoserver/security/impl/LayerGroupContainmentCacheTest.java
- src/security/security-tests/src/test/java/org/geoserver/security/impl/AbstractAuthorizationTest.java
- src/security/security-tests/src/test/java/org/geoserver/security/impl/SecureCatalogImplGroupsTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapIntegrationTest.java
[![GEOS-10545](https://badgen.net/badge/JIRA/GEOS-10545/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10545)
* [GEOS-10545] Layer Group cache not initialized
> [2.20.x backport] [GEOS-10545] Layer Group cache not initialized (#5985)

- src/main/src/main/java/org/geoserver/GeoServerConfigurationLock.java
- src/main/src/test/java/org/geoserver/GeoServerConfigurationLockTest.java
[![GEOS-10560](https://badgen.net/badge/JIRA/GEOS-10560/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10560)
`GeoServerConfigurationLock` uses reentrant read/write locks
internally but does not preserve that behavior.
Since the lock can't know about the call chain that results
in a lock request, it's important that reentrancy is preserved.
A typical scenario is component A acquires a write lock to
perform a bunch of operations through component B, which also
acquires a write lock to perform more granular operations.
Component B unlocks, and then component A unlocks. Currently,
the `ThreadLocal<LockType>` is cleared on the first unlock,
leaving open locks when the next call to
`GeoServerConfigurationLock.unlock()` arrives.
Also, if a write lock is already held, and a read lock is …
> [GEOS-10560] Make GeoServerConfigurationLock reentrant

- src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java
- src/wms/src/test/java/org/geoserver/wms/map/GetMapKvpRequestReaderTest.java
[![GEOS-10559](https://badgen.net/badge/JIRA/GEOS-10559/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10559)
`GetMapKvpRequestReader` creates an apache
`CloseableHttpClient` on its constructor.
To do so, it needs to get the stles cache configuration from the
`org.geoserver.wms.WMS facade.`
Depending on the bootstrap conditions, this triggers an eager initialization
of beans, that can lead to a circular reference error.
This issue is observed in GeoServer Cloud.
Also, the eager initialization of the HTTP client can result in a waste
of resources, because it may never use it, and because there are subclasses
that definitely won’t use it.
Some of these subclasses are not spring beans, but created on-demand,
such as `WMSRequests.LayerParser`, which currently adds a …
> GEOS-10559 Lazy initialization of GetMapKvpRequestReader's HTTP client used to fetch remote styles

- src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java
- src/wms/src/test/java/org/geoserver/wms/map/GetMapKvpRequestReaderTest.java
[![GEOS-10559](https://badgen.net/badge/JIRA/GEOS-10559/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10559)
Backport of #5986 to `2.21.x`
`GetMapKvpRequestReader` creates an apache
`CloseableHttpClient` on its constructor.
To do so, it needs to get the stles cache configuration from the
`org.geoserver.wms.WMS facade.`
Depending on the bootstrap conditions, this triggers an eager initialization
of beans, that can lead to a circular reference error.
This issue is observed in GeoServer Cloud.
Also, the eager initialization of the HTTP client can result in a waste
of resources, because it may never use it, and because there are subclasses
that definitely won’t use it.
Some of these subclasses are not spring beans, but created on-demand,
such as `WMSRequests.LayerParser`, which …
> [backport 2.21.x][GEOS-10559] Lazy initialization of GetMapKvpRequestReader's HTTP client

- src/main/src/main/java/org/geoserver/GeoServerConfigurationLock.java
- src/main/src/test/java/org/geoserver/GeoServerConfigurationLockTest.java
[![GEOS-10560](https://badgen.net/badge/JIRA/GEOS-10560/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10560)
Backport of #5990 to `2.21.x`
> [backport 2.21.x][GEOS-10560] Make GeoServerConfigurationLock reentrant

- src/community/jms-cluster/jms-commons/pom.xml
- src/community/jms-cluster/jms-commons/src/main/java/org/geoserver/cluster/JMSXStreamPersisterInitializer.java
- src/community/jms-cluster/jms-commons/src/main/resources/applicationContext.xml
[![GEOS-10563](https://badgen.net/badge/JIRA/GEOS-10563/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10563)
References: [GEOS-10563](https://osgeo-org.atlassian.net/browse/GEOS-10563)
> [Fixes GEOS-10563] XStream persister serializer exception on JMS clustering messages exchange

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/TimeExtentCalculator.java
- src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/TimeExtentCalculatorTest.java
- src/community/ogcapi/ogcapi-core/src/test/resources/org/geoserver/ogcapi/TimeElevation.properties
- src/community/ogcapi/ogcapi-core/src/test/resources/org/geoserver/ogcapi/TimeElevationEmpty.properties
[![GEOS-10566](https://badgen.net/badge/JIRA/GEOS-10566/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10566)
See ticket.
> [GEOS-10566] Coverage API time range calculation needs to be hardened

- src/wms/src/main/java/org/geoserver/wms/WMS.java
- src/wms/src/test/java/org/geoserver/wms/WMSDimensionsTestSupport.java
- src/wms/src/test/java/org/geoserver/wms/WMSTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DimensionsVectorCapabilitiesTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/DimensionsVectorCapabilitiesTest.java
- src/wms/src/test/resources/org/geoserver/wms/TimeElevationWithStartEnd.properties
[![GEOS-10516](https://badgen.net/badge/JIRA/GEOS-10516/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10516)
This PR updates WMS GetCapabilities dimension representations to use the end attribute for feature types with a configured end attribute when the dimension presentation is not List.  I had problems running the WMSTest that uses TimeElevationWithStartEnd.properties in a machine with a non-UTC timezone so I had to update that too for all of the tests to pass on my machine.
> [GEOS-10516] WMS GetCapabilities dimension representations ignores the end attribute

- src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/ogcapi/images/STACItemFeaturesResponse.java
`STACItemFeaturesResponse.getCapabilitiesElementName()` throws
an `UnsupportedOperationException` instead of returning `null`,
producing a `ServiceExceptionReport` when requesting a WFS 1.0.0
`GetCapabilities` document.
`null` is a valid return value for this method, that results
in `WFSGetFeatureOutputFormat.getCapabilitiesElementNames()`
not contributing an output format name for the
`WFSGetFeatureOutputFormat` in question.
> ogcapi-images: Avoid ServiceException in WFS GetCapabilities

- src/gwc-rest/pom.xml
- src/gwc-rest/src/main/java/org.geoserver.gwc.layer/GWCGeoServerRESTConfigurationProvider.java
- src/gwc-rest/src/main/resources/applicationContext.xml
- src/gwc-rest/src/test/java/org/geoserver/gwc/RESTIntegrationTest.java
- src/gwc/pom.xml
- src/gwc/src/main/resources/geowebcache-geoserver-context.xml
- src/gwc/src/main/resources/geowebcache-servlet.xml
- src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
- src/pom.xml
- src/web/app/pom.xml
[![GEOS-10568](https://badgen.net/badge/JIRA/GEOS-10568/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10568)
We separated the REST APIs into another module. The new module name is `gs-gwc-rest`.
> [GEOS-10568] Fix module modularity for GWC

- src/main/src/main/java/org/geoserver/filters/BufferedRequestStream.java
- src/main/src/main/java/org/geoserver/filters/BufferedRequestWrapper.java
- src/main/src/main/java/org/geoserver/filters/LoggingFilter.java
- src/main/src/test/java/org/geoserver/filters/BufferedRequestStreamTest.java
- src/main/src/test/java/org/geoserver/filters/LoggingFilterTest.java
[![GEOS-10584](https://badgen.net/badge/JIRA/GEOS-10584/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10584)
BufferedRequestStream now respects close() clearing internal myInputStream reference.
> [GEOS-10584] Do not close origional inputstream when logging request body
