geoserver/geoserver

- src/community/ogcapi/ogcapi-changeset/src/test/java/org/geoserver/api/changeset/ChangesetTest.java
- src/community/ogcapi/ogcapi-changeset/src/test/java/org/geoserver/api/changeset/TilesExtensionsTest.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/Link.java
- src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/api/OGCApiTestSupport.java
- src/community/ogcapi/ogcapi-tiled-features/src/main/java/org/geoserver/api/features/tiled/TiledFeatureService.java
- src/community/ogcapi/ogcapi-tiled-features/src/test/java/org/geoserver/api/features/tiled/LandingPageTest.java
- src/community/ogcapi/ogcapi-tiled-features/src/test/java/org/geoserver/api/features/tiled/TileDescriptionTest.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TileJSON.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TileJSONBuilder.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TiledCollectionDocument.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TilesDocument.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TilesService.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/VectorLayerMetadata.java
- src/community/ogcapi/ogcapi-tiles/src/main/resources/org/geoserver/api/tiles/tiles.ftl
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/LandingPageTest.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/TileDescriptionTest.java
- src/pom.xml
Added as an experimental describedBy link for the tiles resource. Just checking the build is sane.
> TileJSON support in OGC Tiles API

- src/pom.xml
Current assemblies for nightly builds contain  ${project-version} insead of the version name, should have been ${project.version} in the file.
> Fix project version reference in assembly instructions

- .github/PULL_REQUEST_TEMPLATE.md
> Typo fixes to PR template

- src/pom.xml
- src/wms/src/main/java/org/geoserver/wms/map/RenderedImageMapOutputFormat.java
> Updating to jai-ext 1.1.14

- src/pom.xml
> Updating to jai-ext 1.1.14 - 2.17

- src/pom.xml
> Updating to jai-ext 1.1.14 -2.16

- src/ows/src/main/java/org/geoserver/ows/kvp/URLKvpParser.java
- src/ows/src/test/java/org/geoserver/ows/kvp/URLKvpParserTest.java
URLKvpParser fixes every url, also non broken ones, introducing a wrong encoding in some cases.
This fix tries to use the url right away, and fix it only if it is not valid. …
> [GEOS-9539]: avoid fixing correct urls in URLKvpParser

- src/community/notification/pom.xml
> [GEOS-9550] Notification community plugin tests fails

- src/main/src/main/java/org/geoserver/catalog/impl/WMSLayerInfoImpl.java
GeoServer configuration objects do not use JPA/J2EE, these annotations should be unecessary.
> Removing un-necessary transient annotations

- src/community/notification/pom.xml
- src/community/notification/src/main/java/org/geoserver/notification/NotificationTransactionListener.java
- src/community/notification/src/test/java/org/geoserver/notification/IntegrationTest.java
> [2.16.x backport][GEOS-9550-GEOS-9238] Notification community plugin tests fails-The notification community module breaks WFS-T transactions

- src/community/notification/pom.xml
> [2.17.x backport][GEOS-9550] Notification community plugin tests fails

- src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupRestoreTestSupport.java
- src/community/backup-restore/rest/src/main/java/org/geoserver/backuprestore/rest/AbstractBackupRestoreController.java
- src/community/backup-restore/rest/src/test/java/org/geoserver/backuprestore/rest/RESTBackupTest.java
ref. https://osgeo-org.atlassian.net/browse/GEOS-9567
> [Fixes JIRA GEOS-9567] [Backup/Restore] Rest Controller not able to backup secured resources

- src/community/taskmanager/core/bin/pom.xml
- src/extension/geofence/pom.xml
- src/pom.xml
Backport of https://github.com/geoserver/geoserver/pull/4165
Depends on https://github.com/geotools/geotools/pull/2866
> [GEOS-9566] Switch from repo.boundlessgeo.com to repo.osgeo.org (#4165)

- doc/en/release/htmldoc.xml
- src/community/pom.xml
- src/community/release/pom.xml
- src/community/script/pom.xml
- src/release/bin.xml
- src/release/ext-control-flow.xml
- src/release/ext-oracle.xml
- src/release/javadoc.xml
- src/release/war.xml
This PR checks that everything is able to be released after recent repository changes:
> review build_release script and assembly definitions

- src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
- src/main/src/main/java/org/geoserver/catalog/RetypeFeatureTypeCallback.java
- src/main/src/test/java/org/geoserver/catalog/RetypeFeatureTypeCallbackTest.java
- src/main/src/test/resources/org/geoserver/catalog/longlat.properties
GSIP : https://github.com/geoserver/geoserver/wiki/GSIP-187
JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9487
> [2.16.x backport][GEOS-9487] GSIP 187 - New extension point in ResourcePool for retyping feature types and features

- src/release/ext-authkey.xml
- src/release/ext-cas.xml
- src/release/ext-css.xml
> Fix license details for authkey, cas and css plugins (#4192) Backport

- src/community/security/keycloak/pom.xml
- src/community/security/keycloak/src/main/resources/GeoServerApplication.properties
- src/community/security/keycloak/src/main/resources/GeoServerApplication_ko.properties
- src/community/security/keycloak/src/main/resources/applicationContext.xml
- src/community/security/oauth2-core/pom.xml
- src/community/security/oauth2-core/src/main/resources/GeoServerApplication.properties
- src/community/security/oauth2-core/src/main/resources/GeoServerApplication_ko.properties
- src/community/security/oauth2-core/src/main/resources/GeoServerException.properties
- src/community/security/oauth2-geonode/pom.xml
- src/community/security/oauth2-geonode/src/main/resources/GeoServerApplication.properties
- src/community/security/oauth2-geonode/src/main/resources/GeoServerApplication_ko.properties
- src/community/security/oauth2-geonode/src/main/resources/applicationContext.xml
- src/community/security/oauth2-geonode/src/test/java/org/geoserver/web/security/oauth2/GeoNodeAuthProviderPanelTest.java
- src/community/security/oauth2-github/pom.xml
- src/community/security/oauth2-github/src/main/resources/GeoServerApplication.properties
- src/community/security/oauth2-github/src/main/resources/GeoServerApplication_ko.properties
- src/community/security/oauth2-github/src/main/resources/applicationContext.xml
- src/community/security/oauth2-github/src/test/java/org/geoserver/web/security/oauth2/GitHubAuthProviderPanelTest.java
- src/community/security/oauth2-google/pom.xml
- src/community/security/oauth2-google/src/main/resources/GeoServerApplication.properties
- src/community/security/oauth2-google/src/main/resources/GeoServerApplication_ko.properties
- src/community/security/oauth2-google/src/main/resources/applicationContext.xml
- src/community/security/oauth2-google/src/test/java/org/geoserver/web/security/oauth2/GoogleAuthProviderPanelTest.java
- src/community/security/oauth2-openid-connect/src/main/resources/applicationContext.xml
- src/community/security/oauth2-openid-connect/src/test/java/org/geoserver/security/oauth2/OpenIdConnectLoginButtonTest.java
- src/community/security/pom.xml
- ref. https://osgeo-org.atlassian.net/browse/GEOS-9568
> [GEOS-9568] [OAuth2 Community Plugin] Increase Test Coverage > 60%

- doc/en/user/source/community/jdbcstore/configuration.rst
- src/community/jdbcstore/src/main/java/org/geoserver/jdbcstore/JDBCResourceStore.java
- src/community/jdbcstore/src/main/java/org/geoserver/jdbcstore/JDBCResourceStoreFactoryBean.java
- src/community/jdbcstore/src/main/java/org/geoserver/jdbcstore/internal/JDBCDirectoryStructure.java
- src/community/jdbcstore/src/main/java/org/geoserver/jdbcstore/internal/JDBCResourceStoreProperties.java
- src/community/jdbcstore/src/test/java/org/geoserver/jdbcstore/AbstractJDBCResourceStoreTest.java
- src/community/jdbcstore/src/test/java/org/geoserver/jdbcstore/AbstractJDBCResourceTheoryTest.java
- src/community/jdbcstore/src/test/java/org/geoserver/jdbcstore/H2JDBCResourceTheoryTest.java
- src/community/jdbcstore/src/test/java/org/geoserver/jdbcstore/PostgresJDBCResourceTheoryTest.java
https://osgeo-org.atlassian.net/browse/GEOS-9606
Community module patch
> [GEOS-9606] JdbcStore: allow directories to be automatically cached

- src/wfs/src/main/java/org/geoserver/wfs/xml/filter/v1_1/PropertyNameTypeBinding.java
accompanies https://github.com/geotools/geotools/pull/2908
checks won't work -> can be redone when geotools issue is merged
> [GEOT-6551] SLD 1.1 doesn't support namespaces in OGC PropertyName

- doc/en/user/source/community/backuprestore/usagerest.rst
- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/Backup.java
- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/tasklet/AbstractCatalogBackupRestoreTasklet.java
- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/tasklet/CatalogBackupRestoreTasklet.java
- src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java
> [GEOS-9589][Backup & Restore] Introduce an option allowing a user to specify some paths to be excluded by the backup / restore explicitlty.

- doc/en/user/source/community/gsr/functionality.rst
- src/community/gsr/src/main/java/org/geoserver/gsr/GSRDispatcher.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/feature/FeatureControllerTest.java
> [GEOS-9598] Add support in GSR module for clients requesting pjson

- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureLayerListController.java
- src/community/gsr/src/main/resources/org/geoserver/gsr/api/feature/featurelayers.ftl
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/ServiceTest.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/feature/FeatureLayerListControllerTest.java
> [GEOS-9596] Added Feature Service layers list endpoint in GSR module

- src/restconfig/src/main/java/org/geoserver/rest/catalog/DataStoreController.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/DataStoreControllerTest.java
https://osgeo-org.atlassian.net/browse/GEOS-9593
> [GEOS-9593] REST: allow changing name and workspace of datastores

- doc/en/user/source/extensions/authkey/index.rst
Moved a left out closing curly bracket `}` to inside of code block.
> Update authkey doc page code block

- src/pom.xml
Bump spring.version: 5.1.13.RELEASE ➞ 5.1.14.RELEASE
Bump spring.security.version: 5.1.8.RELEASE ➞ 5.1.9.RELEASE
Spring release notes:
- https://github.com/spring-projects/spring-framework/releases/tag/v5.1.14.RELEASE
- https://github.com/spring-projects/spring-security/releases/tag/5.1.9.RELEASE
Jira: [GEOS-9600](https://osgeo-org.atlassian.net/browse/GEOS-9600) …
> [GEOS-9600] Update Spring/Spring security libraries to 5.1.14/5.1.9

- doc/en/user/source/community/metadata/uiconfiguration.rst
> Metadata community module: documentation update

- src/extension/mongodb/pom.xml
This PR adds module maintainers information to MongoDB module.
> Add MongoDB module maintainers

- src/extension/geofence-server/src/main/resources/applicationContext.xml
- src/extension/geofence-server/src/main/resources/geofence-default-override.properties
- src/extension/geofence-server/src/test/resources/geofence-default-override.properties
https://osgeo-org.atlassian.net/browse/GEOS-9613
geofence-server tests fail on windows
Config files have been modified so that the DB for testing is created in memory and not on filesystem.
```
2020-04-30T09:22:44.3945219Z [ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 3, Time elapsed: 38.289 s <<< FAILURE! - in org.geoserver.geofence.internal.InternalServicesTest
2020-04-30T09:22:44.4010007Z [ERROR] org.geoserver.geofence.internal.InternalServicesTest  Time elapsed: 25.443 s  <<< ERROR!
2020-04-30T09:22:44.4260724Z java.io.IOException: Failed to clean up test data dir after 100 attempts
2020-04-30T09:22:44.4675265Z Caused by: java.io.IOException: 
2020-04-30T09:22:44.6221154Z Failed to delete tree:
2020-04-30T09:22:44.6541485Z .\target\default6282193771497574626data …
```
> [GEOS-9613] Fix geofence-server build on windows

- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureLayerListController.java
- src/community/gsr/src/main/resources/org/geoserver/gsr/api/feature/featurelayers.ftl
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/ServiceTest.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/feature/FeatureLayerListControllerTest.java
> [2.17.x backport][GEOS-9596] Added Feature Service layers list endpoint in GSR module

- doc/en/user/source/community/gsr/functionality.rst
- src/community/gsr/src/main/java/org/geoserver/gsr/GSRDispatcher.java
- src/community/gsr/src/test/java/org/geoserver/gsr/controller/feature/FeatureControllerTest.java
> [2.17.x backport][GEOS-9598] Add support in GSR module for clients requesting pjson

- src/platform/src/main/java/org/geoserver/platform/resource/Resources.java
- src/platform/src/test/java/org/geoserver/platform/GeoServerResourceLoaderTest.java
https://osgeo-org.atlassian.net/browse/GEOS-9196
> [GEOS-9196] decode special characters with relative paths

- src/extension/geofence-server/src/main/resources/applicationContext.xml
- src/extension/geofence-server/src/main/resources/geofence-default-override.properties
- src/extension/geofence-server/src/test/resources/geofence-default-override.properties
> [GEOS-9613][2.17.x backport] Fix geofence-server build on windows (#4234)

- src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/ImportBaseController.java
- src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/ImportController.java
- src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/ImportTaskController.java
> [GEOS-6888] Importer Tasks errors are not logged

- src/release/ext-mongodb.xml
JIRA ticket https://osgeo-org.atlassian.net/browse/GEOS-9632
This pr add the include for bson.jar in `ext-mongodb.xml`, needed since the update of mongo java driver to 4.2. See https://osgeo-org.atlassian.net/browse/GEOT-6590
> [GEOS-9632] Mongo-db plugin zip miss a dependency jar

- src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/CRSRequestHandler.java
- src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/GridGeometryProvider.java
- src/community/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
[GEOS-9583] DownloadProcess can return data with inaccurate bboxes wh…
> [2.16.x backport] [GEOS-9583] DownloadProcess can return data with inaccurate bboxes when querying heterogeneous CRS mosaics

- src/web/app/pom.xml
See: https://github.com/geotools/geotools/pull/2957
> Follow up GeoTools GEOT-6613, removing last reference to OGR-Bridj

- src/web/app/pom.xml
> Follow up GeoTools GEOT-6613, removing last reference to OGR-Bridj - 2.16.x backport

- src/wms/src/main/java/applicationContext.xml
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendUtils.java
- src/wms/src/main/java/org/geoserver/wms/map/AbstractMapOutputFormat.java
- src/wms/src/main/java/org/geoserver/wms/map/PDFMapOutputFormat.java
- src/wms/src/main/java/org/geoserver/wms/map/PDFMapResponse.java
- src/wms/src/main/java/org/geoserver/wms/map/RenderedImageMapOutputFormat.java
- src/wms/src/test/java/org/geoserver/wms/map/PDFGetMapTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java
- src/wms/src/test/resources/org/geoserver/wms/map/testLayout.xml
This patch adds the ability for WMS decorations to be displayed on PDF output as well as Images.
> [GEOS-8573] Add WMS decorations to PDF output

- src/release/bin/startup.bat
Backport of https://github.com/geoserver/geoserver/pull/4279
> [GEOS-9641] Windows startup.bat won't auto-detect Java in path with spaces - 2.17.x backport

- src/release/bin/startup.bat
Backport of https://github.com/geoserver/geoserver/pull/4287
> [GEOS-9641] Windows startup.bat won't auto-detect Java in path with spaces - 2.16.x backport

- src/release/ext-mongodb.xml
Depends on gt 23.x backport pr https://github.com/geotools/geotools/pull/2983
> [2.17.x backport] [GEOS-9632] Mongo-db plugin zip miss a dependency jar (#4263)

- src/release/ext-mongodb.xml
depends on gt backport pr https://github.com/geotools/geotools/pull/2984
> [2.16.x backport][GEOS-9632] Mongo-db plugin zip miss a dependency jar (#4263)

- doc/en/user/source/styling/sld/reference/textsymbolizer.rst
> doc: fix typo

- doc/en/user/source/data/raster/imagemosaic/configuration.rst
[GEOS-9634] Update documentation on ImageMosaic configuration with SQ…
Depends on https://github.com/geotools/geotools/pull/2980
> [2.17.x backport] [GEOS-9634] Update documentation on ImageMosaic configuration with SQLServer details

- doc/en/user/source/data/raster/imagemosaic/configuration.rst
[GEOS-9634] Update documentation on ImageMosaic configuration with SQ…
Depends on https://github.com/geotools/geotools/pull/2981
> [2.16.x backport] [GEOS-9634] Update documentation on ImageMosaic configuration with SQLServer details #4296

- src/pom.xml
- src/wfs/pom.xml
Just adds gt-jdbc-h2 to the dependency management section like other geotools dependencies are.
> Add entry for org.geotools.jdbc:gt-jdbc-h2 in dependency resolution.

- doc/en/user/source/filter/function_reference.rst
> Follow up on GEOT-6616. Updating GeoServer Doc

- src/extension/app-schema/pom.xml
Updates App-Schema modules maintainers, officializing Nuno Oliveira and Fernando Miño as the module maintainers.
> Update App-Schema modules maintainers

- .travis.yml
There seems to be a typo here, assuming these directories should not be part of the cache which is why they are deleted
see also: https://docs.travis-ci.com/user/caching#before_cache-phase
> Fix a typo in "before caching" on Travis-CI

- doc/en/user/source/data/database/sqlserver.rst
Minor documentation change to align with https://osgeo-org.atlassian.net/browse/GEOS-9460
I did ponder removing the Microsoft JDBC section entirely as it is no longer required for stable Geoserver installations.
- [] There is a …
> GEOS-9460 change to SQL server installation steps

- src/pom.xml
Update the PostgreSQL jdbc driver from 42.2.5 to 42.2.14, resolves CVE-2020-13692 (PostgreSQL JDBC Driver (aka PgJDBC) before 42.2.13 allows XXE) .
- https://jdbc.postgresql.org/documentation/changelog.html#version_42.2.13
- https://osgeo-org.atlassian.net/browse/GEOS-9651
The following are required only for core and extension modules (they are welcomed, …
> [GEOS-9651] Update PostgreSQL driver to 42.2.14

- src/pom.xml
> Upgrading to jai-ext 1.1.15

- src/pom.xml
> [2.17.x backport] [GEOS-9651] Update PostgreSQL driver to 42.2.14

- src/pom.xml
> [2.16.x backport] [GEOS-9651] Update PostgreSQL driver to 42.2.14

- doc/en/user/source/community/json-ld/configuration.rst
- src/community/json-ld/pom.xml
- src/community/json-ld/src/main/java/org/geoserver/jsonld/JsonLdGenerator.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/AbstractJsonBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/SourceBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/impl/CompositeBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/impl/DynamicValueBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/impl/IteratingBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/impl/RootBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/impl/StaticBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/configuration/JsonLdConfiguration.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/configuration/JsonLdTemplateReader.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/expressions/JsonLdCQLManager.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/expressions/JsonLdCqlManager.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/request/JsonLdPathVisitor.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/request/JsonLdTemplateCallBackOGC.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/request/JsonLdTemplateCallback.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/response/JSONLDGetFeatureResponse.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/validation/JsonLdValidator.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/validation/ValidateExpressionVisitor.java
- src/community/json-ld/src/test/java/org/geoserver/jsonld/response/JSONLDComplexTestSupport.java
- src/community/json-ld/src/test/java/org/geoserver/jsonld/response/JSONLDGetComplexFeaturesResponseFilteringTest.java
- src/community/json-ld/src/test/java/org/geoserver/jsonld/response/JSONLDGetComplexFeaturesResponseTest.java
- src/community/json-ld/src/test/resources/org/geoserver/jsonld/response/FirstParentFeature_invalid.json
- src/community/json-ld/src/test/resources/org/geoserver/jsonld/response/GeoLogicUnit_invalid.json
- src/community/json-ld/src/test/resources/org/geoserver/jsonld/response/GeologicUnitDynamicStaticFilter.json
- src/community/json-ld/src/test/resources/org/geoserver/jsonld/response/MappedFeature.json
- src/community/json-ld/src/test/resources/org/geoserver/jsonld/response/MappedFeatureIteratingAndCompositeFilter.json
> [2.16.x backport] [GEOS-9625] Add filtering support in json-ld module - [GEOS-9656] JSON-LD validation will not try to validate the entire template

- doc/en/user/source/community/json-ld/configuration.rst
- src/community/json-ld/pom.xml
- src/community/json-ld/src/main/java/org/geoserver/jsonld/JsonLdGenerator.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/AbstractJsonBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/SourceBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/impl/CompositeBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/impl/DynamicValueBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/impl/IteratingBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/impl/RootBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/builders/impl/StaticBuilder.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/configuration/JsonLdConfiguration.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/configuration/JsonLdTemplateReader.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/expressions/JsonLdCQLManager.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/expressions/JsonLdCqlManager.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/request/JsonLdPathVisitor.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/request/JsonLdTemplateCallBackOGC.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/request/JsonLdTemplateCallback.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/response/JSONLDGetFeatureResponse.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/validation/JsonLdValidator.java
- src/community/json-ld/src/main/java/org/geoserver/jsonld/validation/ValidateExpressionVisitor.java
- src/community/json-ld/src/test/java/org/geoserver/jsonld/response/JSONLDComplexTestSupport.java
- src/community/json-ld/src/test/java/org/geoserver/jsonld/response/JSONLDGetComplexFeaturesResponseFilteringTest.java
- src/community/json-ld/src/test/java/org/geoserver/jsonld/response/JSONLDGetComplexFeaturesResponseTest.java
- src/community/json-ld/src/test/resources/org/geoserver/jsonld/response/FirstParentFeature_invalid.json
- src/community/json-ld/src/test/resources/org/geoserver/jsonld/response/GeoLogicUnit_invalid.json
- src/community/json-ld/src/test/resources/org/geoserver/jsonld/response/GeologicUnitDynamicStaticFilter.json
- src/community/json-ld/src/test/resources/org/geoserver/jsonld/response/MappedFeature.json
- src/community/json-ld/src/test/resources/org/geoserver/jsonld/response/MappedFeatureIteratingAndCompositeFilter.json
> [2.17.x backport] [GEOS-9625] Add filtering support in json-ld module - [GEOS-9656] JSON-LD validation will not try to validate the entire template

- src/extension/csw/core/src/main/java/org/geoserver/csw/store/internal/CatalogStoreFeatureCollection.java
- src/extension/csw/core/src/main/java/org/geoserver/csw/store/internal/CatalogStoreFeatureIterator.java
This change changes performances, and does not resolve a bug or add new functionality. That is why there is no new unit test. However, the existing unit tests are there to prove that this new implementation preserves functionality.
The change also simplifies the code.
The following are required only for core and extension modules (they are welcomed, but …
> [GEOS-9594] CSW: performance issue: every page loads entire catalog

- src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java
- src/wms/src/test/java/org/geoserver/wms/map/GetMapKvpRequestReaderTest.java
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9646
The [INSPIRE validator](https://inspire.ec.europa.eu/validator) throws some errors testing GeoServer WMS Services.
The GetMap validation report shows three errors, all of them about input parameters:
We get these error messages:
- A GetMap was requested without mandatory parameter 'STYLES' and the service did not throw an exception.
- A GetMap was requested without mandatory parameter 'CRS' and the service did not throw an exception.
- A GetMap was requested using parameter 'TRANSPARENT' with an invalid value and the service did not throw an exception.
This code fixes all of them taking care of CITE compliant mode.
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as …
> [GEOS-9646]: INSPIRE validation get errors of GetMapRequest parameters

- doc/en/developer/source/source.rst
Fixed a pair of typos in developer documentation
> Typos in documentation fix

- src/extension/wps/wps-core/pom.xml
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/UniqueProcessTest.java
- src/wfs/src/main/java/org/geoserver/wfs/TypeInfoCollectionWrapper.java
See https://osgeo-org.atlassian.net/browse/GEOS-9668
> [GEOS-9668] UniqueProcess call against a JDBC store does not result in a 'select distinct' anymore

- src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java
- src/main/src/main/java/org/vfny/geoserver/util/DataStoreUtils.java
- src/web/core/src/main/java/org/geoserver/web/data/resource/BasicResourceConfig.java
- src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
- src/web/core/src/test/resources/wmtsLayer.xml
- src/web/core/src/test/resources/wmtsLayerInfo.xml
- src/web/core/src/test/resources/wmts_getCaps.xml
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9655
This pull request makes possible to select from the find button in the layer configuration page, the other native srs when configuring a WMTS layer.
> [GEOS-9655] WMTS layer configuration page doesn't show all the native srs in getCapabilties document

- src/extension/wps/wps-core/pom.xml
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/UniqueProcessTest.java
- src/wfs/src/main/java/org/geoserver/wfs/TypeInfoCollectionWrapper.java
2.17.x backport of https://github.com/geoserver/geoserver/pull/4348
> [GEOS-9668] UniqueProcess call against a JDBC store does not result in a 'select distinct' anymore - 2.17.x

- src/extension/wps/wps-core/pom.xml
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/UniqueProcessTest.java
- src/wfs/src/main/java/org/geoserver/wfs/TypeInfoCollectionWrapper.java
2.16.x backport of https://github.com/geoserver/geoserver/pull/4348
> [GEOS-9668] UniqueProcess call against a JDBC store does not result in a 'select distinct' anymore - 2.16.x

- src/community/netcdf-ghrsst/pom.xml
- src/extension/netcdf-out/pom.xml
Upgrade NetCDF to 4.6.15 to address security vulnerabilities in third-party libraries.
https://osgeo-org.atlassian.net/browse/GEOS-9660
> [GEOS-9660] Upgrade NetCDF to 4.6.15

- src/main/src/main/java/org/geoserver/catalog/Predicates.java
- src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java
- src/security/security-tests/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java
See also https://osgeo-org.atlassian.net/browse/GEOS-9654
> [GEOS-9654] Layer preview layer count and paging off base when secured layers are not visible

- src/main/src/main/java/org/geoserver/catalog/Predicates.java
- src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java
- src/security/security-tests/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java
Backport of https://github.com/geoserver/geoserver/pull/4379
> [GEOS-9654] Layer preview layer count and paging off base when secured layers are not visible - 2.16.x

- src/main/src/main/java/org/geoserver/catalog/Predicates.java
- src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java
- src/security/security-tests/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java
Backport of https://github.com/geoserver/geoserver/pull/4379
> [GEOS-9654] Layer preview layer count and paging off base when secured layers are not visible - 2.17.x

- src/pom.xml
backports #4351
see also #4253
> [2.17.x backport][GEOS-9669] Upgrade Oracle JDBC driver to 19.7.0.0

- src/pom.xml
A new version of the Oracle JDBC driver was released recently.
Update com.oracle.database.jdbc:ojdbc8 19.6.0.0 ➜ 19.7.0.0
see also: 
- https://github.com/geotools/geotools/pull/3023
- https://osgeo-org.atlassian.net/browse/GEOS-9669
No 2.16.x backport because GEOS-9535/#4119 was not backported to 2.16.x
The following are required only for core and …
> [GEOS-9669] Upgrade Oracle JDBC driver to 19.7.0.0

- src/community/gsr/src/main/java/org/geoserver/gsr/translate/geometry/AbstractGeometryEncoder.java
- src/extension/imagemap/src/main/java/org/vfny/geoserver/wms/responses/map/htmlimagemap/holes/HolesRemover.java
- src/pom.xml
Signed-off-by: Jim Hughes <jnh5y@ccri.com>
> Upgrading to JTS 1.17.0. using JAI-EXT 1.1.16

- doc/en/user/source/community/geopkg/output.rst
- src/community/geopkg/src/main/java/applicationContext.xml
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoPackageProcess.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoPackageProcessRequestPPIO.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoPkgAnnotationReference.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoPkgSemanticAnnotation.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoPkgStyle.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoPkgStyleSheet.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoPkgSymbol.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoPkgSymbolImage.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/PortrayalExtension.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/SemanticAnnotationsExtension.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/StyleResourceCollector.java
- src/community/geopkg/src/main/resources/META-INF/services/org.geotools.geopkg.GeoPkgExtensionFactory
- src/community/geopkg/src/main/resources/org/geoserver/geopkg/wps/geopkg_portrayal_extension.sql
- src/community/geopkg/src/main/resources/org/geoserver/geopkg/wps/geopkg_sa_extension.sql
- src/community/geopkg/src/test/java/org/geoserver/geopkg/wps/gs/GeoPackageProcessTest.java
- src/community/geopkg/src/test/resources/org/geoserver/geopkg/wps/gs/burg.sld
- src/community/geopkg/src/test/resources/org/geoserver/geopkg/wps/gs/burg02.svg
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/geometry/AbstractGeometryEncoder.java
- src/main/src/main/java/org/geoserver/config/GeoServerDataDirectory.java
Add support for style inclusion in the generated GeoPackage, using VTP2 portrayal extension to export styles and symbology, and the VTP2 semantic annotations extension to link them. See also http://docs.opengeospatial.org/dp/19-047.html
(yes, no QGIS style support, it's not even on the table, sorry) …
> Geopkg WPS processs: download styles

- src/web/core/src/main/java/org/geoserver/web/data/resource/BasicResourceConfig.java
- src/web/core/src/main/java/org/geoserver/web/wicket/CRSPanel.java
- src/web/core/src/main/java/org/geoserver/web/wicket/SRSProvider.java
- src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9639
Issue : https://github.com/geosolutions-it/C061-2019-COWI-GS-ENH/issues/45
added support for SRID in URN OGC format
(e.g urn:ogc:def:crs:EPSG::4326)
For all pull …
> [GEOS-9639] Add OGC URN synatax support for Native SRS selection

- .github/workflows/macos.yml
- .github/workflows/windows.yml
- src/extension/wps/wps-core/pom.xml
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/ImportProcessTest.java
- src/gwc/src/main/java/org/geoserver/gwc/GWC.java
- src/gwc/src/test/java/org/geoserver/gwc/ConfigurableBlobStoreTest.java
- src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
- src/main/src/test/java/org/geoserver/security/GeoServerSecurityTestSupport.java
- src/main/src/test/java/org/geoserver/test/GeoServerBaseTestSupport.java
- src/security/security-tests/pom.xml
- src/security/security-tests/src/test/java/org/geoserver/security/GroupAdminServiceTest.java
- src/web/security/core/pom.xml
Backport of https://github.com/geoserver/geoserver/pull/4322/commits
> Skipping tests failing on Windows and OSX, but only on the PR checks - 2.17.x

- src/community/release/ext-gsr.xml
This pr add missing jar in the plugin zip.
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9687
> [GEOS-9687] Geoserver fails starting when I install the GSR plugin

- src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
- src/wfs/src/test/java/org/geoserver/wfs/json/GeoJSONTest.java
- src/wfs/src/test/resources/org/geoserver/wfs/json/nanInfinite.properties
- src/wms/src/main/java/org/geoserver/wms/featureinfo/RasterLayerIdentifier.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java
Fixes both:
* [[GEOS-9682] GetFeatureInfo on raster layers ignores rendering transformations](https://osgeo-org.atlassian.net/browse/GEOS-9682)
* [[GEOS-8569] JSON encoding on NaN values fails](https://osgeo-org.atlassian.net/browse/GEOS-8569)
The latter is related as Jiffle sets NaN as output values when the script does not assign an explicit value.
The …
> Handle raster to raster rendering transformations in GetFeatureInfo, and NaN/Infinite in JSON encoding

- src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
- src/wfs/src/test/java/org/geoserver/wfs/json/GeoJSONTest.java
- src/wfs/src/test/resources/org/geoserver/wfs/json/nanInfinite.properties
- src/wms/src/main/java/org/geoserver/wms/featureinfo/RasterLayerIdentifier.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java
Backport of https://github.com/geoserver/geoserver/pull/4411
> Handle raster to raster rendering transformations in GetFeatureInfo, and NaN/Infinite in JSON encoding - 2.16.x

- src/community/release/ext-gsr.xml
> [2.17.x backport][GEOS-9687] Geoserver fails starting when I install the GSR plugin

- src/pom.xml
Signed-off-by: Jim Hughes <jnh5y@ccri.com>
> [GEOT-6664] Cleaning up use of Eclipse EMF dependencies.

- doc/en/user/source/production/container.rst
- src/web/app/src/main/webapp/WEB-INF/web.xml
Proposed Tomcat CORS example for documentation. 
Update existing page where appropriate.
I could not find an equivalent to `<param-name>chainPreflight</param-name>` for Tomcat.
> Add Tomcat CORS configuration

- src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java
- src/wms/src/test/java/org/geoserver/wms/map/GetMapKvpRequestReaderTest.java
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9646
Backport of PR merged in master: https://github.com/geoserver/geoserver/pull/4300
The [INSPIRE validator](https://inspire.ec.europa.eu/validator) throws some errors testing GeoServer WMS Services. The GetMap validation report shows three errors, all of them about input parameters:
- A GetMap was requested without mandatory parameter 'STYLES' and the service did not throw an exception.
- A GetMap was requested without mandatory parameter 'CRS' and the service did not throw an exception.
- A GetMap was requested using parameter 'TRANSPARENT' with an invalid value and the service did not throw an exception.
This code fixes all of them taking care of CITE compliant mode.
> Reviewing is a process done by project maintainers, mostly …
> [Backport 2.17.x][GEOS-9646]: INSPIRE validation get errors of GetMapRequest parameters

- doc/en/user/source/tutorials/tomcat-jndi/tomcat-jndi.rst
In MSSQL Server SYSDATE and DUAL are not valid keywords
> Fix MSSQL Server JNDI example

- doc/en/user/source/production/identify.rst
- src/main/src/main/java/org/geoserver/GeoServerNodeData.java
- src/main/src/test/java/org/geoserver/GeoServerNodeDataTest.java
Adds $host_short_name and $host_compact_name tokens to GEOSERVER_NODE_OPTS
> [GEOS-9688] Option to shorten the hostname in a node identifier

- src/web/core/src/main/java/org/geoserver/web/data/resource/BasicResourceConfig.java
- src/web/core/src/main/java/org/geoserver/web/wicket/CRSPanel.java
- src/web/core/src/main/java/org/geoserver/web/wicket/SRSProvider.java
- src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9639
master : https://github.com/geoserver/geoserver/pull/4397 …
> [GEOS-9639] Add OGC URN synatax support for Native SRS selection (#4397) (2.16.x)

- src/web/core/src/main/java/org/geoserver/web/data/resource/BasicResourceConfig.java
- src/web/core/src/main/java/org/geoserver/web/wicket/CRSPanel.java
- src/web/core/src/main/java/org/geoserver/web/wicket/SRSProvider.java
- src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9639
master : https://github.com/geoserver/geoserver/pull/4397 …
> [Backport 2.17.x][GEOS-9639] Add OGC URN syntax support for Native SRS selection (#4397)

- doc/en/user/source/production/identify.rst
- src/main/src/main/java/org/geoserver/GeoServerNodeData.java
- src/main/src/test/java/org/geoserver/GeoServerNodeDataTest.java
> [Backport 2.17.x][GEOS-9688] Option to shorten the hostname in a node identifier

- doc/en/developer/source/win-installer.rst
added missing files LICENSE.txt, GPL.txt to the list of files list to copy (which are required by the builder script).
updated NSIS plugins folder name (as of NSIS version 3.0 and above).
> win-installer.rst fix

- src/extension/importer/core/pom.xml
See: https://osgeo-org.atlassian.net/browse/GEOS-9702
> [GEOS-9702] Importer should not depend on ArcSDE

- src/pom.xml
See https://osgeo-org.atlassian.net/browse/GEOS-9704 and https://osgeo-org.atlassian.net/browse/GEOS-9704
> [GEOS-9704] Support multiband output in Jiffle

- src/community/geopkg/pom.xml
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoPackageProcess.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/MetadataManager.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/OWSContextWriter.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/SemanticAnnotationsExtension.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/StyleWorker.java
- src/community/geopkg/src/main/resources/org/geoserver/geopkg/wps/owsContextFeature.ftl
- src/community/geopkg/src/main/resources/org/geoserver/geopkg/wps/owsContextRequest.ftl
- src/community/geopkg/src/main/resources/org/geoserver/geopkg/wps/owsContextStylesheet.ftl
- src/community/geopkg/src/test/java/org/geoserver/geopkg/wps/gs/GeoPackageProcessTest.java
- src/community/geopkg/src/test/resources/org/geoserver/geopkg/wps/gs/fakeMetadata.xml
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/xml/ComplexDataTypeBinding.java
- src/main/src/main/java/org/geoserver/catalog/impl/MetadataLinkInfoImpl.java
See: https://osgeo-org.atlassian.net/browse/GEOS-9705
> [GEOS-9705] Allow GeoPackage WPS process to inline metadata and add OWS contexts for request and data

- src/community/gsr/src/main/java/org/geoserver/gsr/GSRExceptionHandler.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/GSRModelReader.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/RelationshipModelReader.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/feature/FeatureLayerController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/api/map/IdentifyServiceResult.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/controller/ImageResourceController.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/Field.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/feature/ServiceEdits.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/map/AbstractLayerOrTable.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/map/LayersAndTables.java
- src/community/gsr/src/main/java/org/geoserver/gsr/model/map/LegendEntry.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureDAO.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/feature/FeatureEncoder.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/geometry/AbstractGeometryEncoder.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/geometry/QuantizedGeometryEncoder.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/geometry/SpatialReferenceEncoder.java
- src/community/gsr/src/main/java/org/geoserver/gsr/translate/relationship/RelationshipDAO.java
- src/community/gsr/src/test/java/org/geoserver/gsr/model/feature/DomainSchemaTest.java
This pr fixes qa errors in GSR module highlighted by the qa tool.
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9693
> [GEOS-9693] Fix qa errors on GSR plugin

- src/main/src/main/java/org/geoserver/security/WrapperPolicy.java
- src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
- src/wfs/src/main/java/org/geoserver/wfs/Transaction.java
- src/wfs/src/test/java/org/geoserver/wfs/ResourceAccessManagerWFSTest.java
See: https://osgeo-org.atlassian.net/browse/GEOS-8282
> [GEOS-8282] Catalog Mode in Data Security doesn't work for insert and update transactions

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NormalizedMultiValuesTest.java
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/measurements.xml
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/measurements.xsd
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/requests/station_tag_code_filter_wfs11.xml
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/requests/station_tag_code_filter_wfs20.xml
This PR provides testing for the fixed issue on App-Schema module not supporting jdbcMultipleValue mappings on Oracle database.
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-9075
> [GEOS-9075] Fix jdbc multi value support on Oracle database

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NormalizedMultiValuesTest.java
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/measurements.xml
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/measurements.xsd
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/requests/station_tag_code_filter_wfs11.xml
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/requests/station_tag_code_filter_wfs20.xml
Backport of https://github.com/geoserver/geoserver/pull/4433.
> [GEOS-9075] Fix jdbc multi value support on Oracle database (2.16.x Backport)

- src/extension/importer/core/pom.xml
Backport of https://github.com/geoserver/geoserver/pull/4430
> [GEOS-9702] Importer should not depend on ArcSDE - 2.16.x

- src/extension/importer/core/pom.xml
Backport of https://github.com/geoserver/geoserver/pull/4430
> [GEOS-9702] Importer should not depend on ArcSDE - 2.17.x

- src/community/netcdf-ghrsst/pom.xml
- src/extension/netcdf-out/pom.xml
2.17.x backport for [GEOS-9660] Upgrade NetCDF to 4.6.15
> [2.17.x][GEOS-9660] Upgrade NetCDF to 4.6.15

- src/community/netcdf-ghrsst/pom.xml
- src/extension/netcdf-out/pom.xml
2.16.x backport for [GEOS-9660] Upgrade NetCDF to 4.6.15
> [2.16.x][GEOS-9660] Upgrade NetCDF to 4.6.15

- src/wms/src/main/java/org/geoserver/wms/RasterCleaner.java
- src/wms/src/test/java/org/geoserver/wms/map/MetaTileOutputFormatTest.java
- src/wms/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
> [Backport 2.17.x] [GEOS-9667] GDAL Store memory management

- src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPRoleService.java
- src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPUserGroupService.java
- src/security/ldap/src/test/java/org/geoserver/security/ldap/LDAPRoleServiceTest.java
- src/security/ldap/src/test/java/org/geoserver/security/ldap/LDAPUserGroupServiceTest.java
- src/security/ldap/src/test/resources/data4.ldif
This PR introduces a fix for a LDAP hierarchical group search bug.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9488
> [GEOS-9488] LDAP hierarchical group search generates error due to ConcurrentModificationException

- doc/en/developer/source/programming-guide/security/index.rst
> Minor spelling & grammar corrections

- src/community/gsr/src/main/java/org/geoserver/gsr/translate/geometry/AbstractGeometryEncoder.java
- src/extension/imagemap/src/main/java/org/vfny/geoserver/wms/responses/map/htmlimagemap/holes/HolesRemover.java
- src/pom.xml
Backport of:
- https://github.com/geoserver/geoserver/pull/4372
- https://github.com/geoserver/geoserver/pull/4431
> JTS and JAI-EXT upgrades

- src/extension/mongodb/src/main/java/org/geoserver/rest/service/AppSchemaUtils.java
- src/extension/mongodb/src/main/java/org/geoserver/rest/service/MongoStoreRestController.java
This PR fixes an Spring initialization methods scan issue with optional AppSchema dependencies classes.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9403
> [GEOS-9403] MongoDB Plugin breaks GeoServer Admin UI

- doc/en/user/source/styling/css/tutorial.rst
> Fix spelling mistake and grammar

- doc/en/user/source/styling/css/properties.rst
> Update spelling & grammar

- doc/en/developer/source/win-installer.rst
- src/release/installer/win/win-installer-builder.ps1
win-installer-builder.ps1 - added a PowerShell script that automate the installation building on Windows
win-installer.rst - added a link to the above script from the docs
> PowerShell script that automate the installation building on Windows

- src/community/jdbcconfig/pom.xml
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
- src/community/release/ext-jdbcconfig.xml
Remove usage of wicket's `Strings` utility class from jdbcconfig's
internal code, so it the module can/could be used even if web-core is
excluded as a dependency.
> Remove dependency on a wicket class from jdbcconfig.internal.ConfigDatabase

- doc/en/user/source/production/config.rst
JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9717
update documentation 
> [GEOS-9717] Disabling Web Admin Password Autocomplete documentation

- src/main/src/main/java/org/geoserver/catalog/CascadeDeleteVisitor.java
> Fix typo: visit(NamespaceInfo workspace) -> visit(NamespaceInfo namespace)

- doc/en/user/source/production/config.rst
JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9717
master : geoserver/geoserver#4452
> [Backport 2.17.x][GEOS-9717] Disabling Web Admin Password Autocomplete documentation

- src/community/wfs3/src/main/java/org/geoserver/wfs3/response/GetFeatureMapboxOutputFormat.java
- src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/PipelineBuilder.java
- src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/VectorTileMapOutputFormat.java
- src/extension/vectortiles/src/test/java/org/geoserver/wms/vector/VectorTileMapOutputFormatTest.java
Hi,
as announced this is the candidate for the early backport of [this pull req](https://github.com/geoserver/geoserver/pull/4264).
> [GEOS-9633][2.17.x] BACKPORT: Provide Pre-Generalized support to VectorTile extension

- src/community/flatgeobuf/pom.xml
- src/pom.xml
Signed-off-by: Jim Hughes <jnh5y@ccri.com>
> Updating to JTS 1.17.1 (GEOS-9725)

- doc/en/api/1.0.0/coverages.yaml
- doc/en/api/1.0.0/coveragestores.yaml
- doc/en/api/1.0.0/datastores.yaml
- doc/en/api/1.0.0/featuretypes.yaml
- doc/en/api/1.0.0/gwcblobstores.yaml
- doc/en/api/1.0.0/styles.yaml
> Fix spelling mistakes & grammar

- src/web/wms/src/main/java/org/geoserver/wms/web/publish/StyleNameComparator.java
- src/web/wms/src/test/java/org/geoserver/wms/web/publish/StylesModelTest.java
See: https://osgeo-org.atlassian.net/browse/GEOS-9727
> [GEOS-9727] Layer's additional styles in palette control are sorted by name, but not by prefixed name

- src/main/pom.xml
- src/pom.xml
Upgrades commons-beanutils to the current release (which includes a fix for CVE-2019-10086). This gets rid of the custom `noclassprop` version that fixed CVE-2019-10086 and gets GeoServer back on the mainstream release.
fixes [GEOS-9309](https://osgeo-org.atlassian.net/browse/GEOS-9309)
see also #3717  and https://github.com/geotools/geotools/pull/3139 (and discussion in https://github.com/geotools/geotools/pull/3004)
**Submitting the PR does not require you to check all items, but by the time it gets merged, they …
> [GEOS-9309] Bump commons-beanutils from 1.9.2 to 1.9.4

- src/wms/src/main/java/org/geoserver/wms/CacheConfiguration.java
- src/wms/src/test/java/org/geoserver/wms/WMSInfoImplTest.java
https://osgeo-org.atlassian.net/browse/GEOS-9730
> [GEOS-9730] WMSInfoImpl cannot be serialized any more

- doc/en/user/source/community/geopkg/output.rst
> Fix capitalisation and typo

- src/web/app/pom.xml
fix an issue with web-app pom.xml: app-schema profile points to a not existing artifact id app-schema-web
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9736
> [GEOS-9736] App-schema profile not building with maven

- doc/en/user/source/community/features-templating/configuration.rst
- doc/en/user/source/community/features-templating/output.rst
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/BuilderFactory.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/AttributeNameHelper.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/FlatCompositeBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/FlatDynamicBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/FlatIteratingBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/FlatStaticBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/geojson/GeoJsonRootBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/impl/RootBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/readers/JsonTemplateReader.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/writers/CommonJsonWriter.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/writers/GeoJsonWriter.java
- src/community/features-templating/src/test/java/org/geoserver/featurestemplating/response/FlatGeoJSONComplexFeaturesResponseTest.java
- src/community/features-templating/src/test/resources/org/geoserver/featurestemplating/response/FlatGeoJSONMappedFeature.json
- src/community/features-templating/src/test/resources/org/geoserver/featurestemplating/response/FlatGeologicUnitWIthSeparator.json
> [2.17.x backport] [GEOS-9738] Add possibility to customize attributeName separator for GeoJSON INSPIRE output 

- src/web/app/pom.xml
> [2.18.x backport][GEOS-9736] App-schema profile not building with maven (#4486)

- doc/en/user/source/community/features-templating/configuration.rst
- doc/en/user/source/community/features-templating/output.rst
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/BuilderFactory.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/AttributeNameHelper.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/FlatCompositeBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/FlatDynamicBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/FlatIteratingBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/FlatStaticBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/geojson/GeoJsonRootBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/impl/RootBuilder.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/readers/JsonTemplateReader.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/writers/CommonJsonWriter.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/writers/GeoJsonWriter.java
- src/community/features-templating/src/test/java/org/geoserver/featurestemplating/response/FlatGeoJSONComplexFeaturesResponseTest.java
- src/community/features-templating/src/test/resources/org/geoserver/featurestemplating/response/FlatGeoJSONMappedFeature.json
- src/community/features-templating/src/test/resources/org/geoserver/featurestemplating/response/FlatGeologicUnitWIthSeparator.json
> [2.18.x backport][GEOS-9738] Add possibility to customize attributeName separator for GeoJSON INSPIRE output

- doc/en/user/source/community/features-templating/querying.rst
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/AttributeNameHelper.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/request/JsonPathVisitor.java
- src/community/features-templating/src/test/java/org/geoserver/featurestemplating/response/FlatGeoJSONComplexFeaturesResponseTest.java
- src/community/features-templating/src/test/java/org/geoserver/featurestemplating/response/JSONLDGetComplexFeaturesResponseTest.java
- src/community/features-templating/src/test/resources/org/geoserver/featurestemplating/response/FlatGeoJSONMappedFeature.json
> [backport 2.17.x][GEOS-9739] Features-templating backwards mapping not working for geoJSON INSPIRE format with "_" separator (#4498)

- doc/en/user/source/community/features-templating/querying.rst
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/builders/flat/AttributeNameHelper.java
- src/community/features-templating/src/main/java/org/geoserver/featurestemplating/request/JsonPathVisitor.java
- src/community/features-templating/src/test/java/org/geoserver/featurestemplating/response/FlatGeoJSONComplexFeaturesResponseTest.java
- src/community/features-templating/src/test/java/org/geoserver/featurestemplating/response/JSONLDGetComplexFeaturesResponseTest.java
- src/community/features-templating/src/test/resources/org/geoserver/featurestemplating/response/FlatGeoJSONMappedFeature.json
> [2.18.x backport][GEOS-9739] Features-templating backwards mapping not working for geoJSON INSPIRE format with "_" separator (#4498)

- doc/en/developer/source/eclipse-guide/index.rst
> Fix spelling mistakes

- src/community/geopkg/pom.xml
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoHashCalculator.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoHashCollection.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoPackageProcess.java
- src/community/geopkg/src/test/java/org/geoserver/geopkg/wps/GeoHashCalculatorTest.java
- src/community/geopkg/src/test/java/org/geoserver/geopkg/wps/GeoHashCollectionTest.java
- src/community/geopkg/src/test/java/org/geoserver/geopkg/wps/GeoPackageProcessTest.java
See also: https://osgeo-org.atlassian.net/browse/GEOS-9745
> [GEOS-9745] Add support for GeoPackage sorting while dumping in WPS GeoPackageProcess

- src/release/ext-wps.xml
Make sure that the WPS extension includes gt-csv and it's dependency.
> [GEOS-9750] add gt-csv and dependency to WPS extension

- SECURITY.md
Filling in the SECURITY.md suggested by GitHub with the same text from our website.
> Security policy file

- src/release/ext-wps.xml
Make sure that the WPS extension includes gt-csv and it's dependency.
> [GEOS-9750] fix gt-csv and dependency in WPS backport to 18.x

- src/release/ext-wps.xml
Make sure that the WPS extension includes gt-csv and it's dependency.
> [GEOS-9750] fix gt-csv and dependency in WPS backport to 17.x

- .github/workflows/windows.yml
Add some options to close TCP connection for Maven and update workflow items while here.
Windows builds have been failing for a while due to connection resets.
Apparently this is caused by Azure hanging up the connection after 4mins. without proper notification as described here: https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080
For all pull …
> Update GH Windows workflow

- src/release/ext-mongodb.xml
This pr add the necessary app-schema jar to the mongo plug-in descriptor
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9755
> [GEOS-9755] Mongo-db plugin zip missing app-schema dependecy jar

- CODE_OF_CONDUCT.md
Including OSGeo email address form this page https://www.osgeo.org/code_of_conduct/
> Update code of conduct with additional OSGeo email address

- src/web/core/src/main/java/org/geoserver/web/css/geoserver.css
This PR fixes the bug where the sticky toolbar conflicts with the editor window. Both are displayed 'through' each other. A small fix is made by adding a `z-index` so the toolbar is always displayed on top of the editor.
Related to: https://osgeo-org.atlassian.net/browse/GEOS-9741 …
> [GEOS-9741] Fix for sticky toolbar displaying 'through' the editor

- src/web/core/src/main/java/org/geoserver/web/data/resource/BasicResourceConfig.java
- src/web/core/src/main/java/org/geoserver/web/wicket/CRSPanel.java
- src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
- src/web/core/src/test/resources/wfs_cap_110.xml
backport of https://github.com/geoserver/geoserver/pull/4525
> [Backport 2.18.x][GEOS-9758] CRS Panel overrides URN SRS format with EPSG:XXXX format 

- src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
This does not fix the issue reported at https://osgeo-org.atlassian.net/browse/GEOS-9756, it simply adds additional logging for when the problem occurs.
> Additional logging for missing style

- doc/en/user/source/community/hana/index.rst
The HANA GeoTools module supports HANA Cloud as well. This change
updates the documentation to reflect that.
> [GEOS-9764] Add HANA Cloud to supported HANA versions

- src/wms/src/main/java/org/geoserver/wms/WMSWorkspaceQualifier.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapIntegrationTest.java
backport of : https://github.com/geoserver/geoserver/pull/4478
> [Backport 2.17.x][GEOS-9729] WMS XML Post request fails with Workspace qualifier in url

- doc/en/user/source/production/data.rst
Replace information about compression for geotiff.
It did not exactly looked right to me :P
The following are required only for core and extension modules (they are welcomed, but not required, …
> Replace information about compression for geotiff

- src/wms/src/main/java/org/geoserver/wms/WMSWorkspaceQualifier.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapIntegrationTest.java
backport of : https://github.com/geoserver/geoserver/pull/4478
> [Backport 2.18.x][GEOS-9729] WMS XML Post request fails with Workspace qualifier in url

- src/web/core/src/main/java/org/geoserver/web/css/geoserver.css
Related to https://osgeo-org.atlassian.net/browse/GEOS-9741
This PR contains a fix for the (connection parameters) dropdown falling 'behind' the sticky toolbar as reported here: https://osgeo-org.atlassian.net/browse/GEOS-9741?focusedCommentId=81910
The sticky toolbar has a `z-index`, the dropdown wicket didn't have a `z-index` so it was falling behind the toolbar. By adding a `z-index` to the wicket container this problem is fixed.
**Screenshot after the fix**
**Submitting the PR does not require you to check all …
> [GEOS-9741] Fix for connection parameters dropdown falling 'behind' sticky toolbar

- src/community/csw-iso/src/main/resources/org/geoserver/csw/store/internal/MD_Metadata.default.properties
I noticed the name of layers is always returned as the title in the ISO schema, this seems to correct it.
> - Made it to return title when not null

- src/community/notification-common/pom.xml
- src/community/notification/pom.xml
> [GEOS-9744] Upgrade of rabbitmq library to 4.8.0 or newer

- LICENSE.txt
- src/main/src/main/java/org/geoserver/system/status/OSHISystemInfoCollector.java
- src/main/src/test/java/org/geoserver/system/status/SystemInfoCollectorTest.java
- src/pom.xml
Resolves:
- [GEOS-9779](https://osgeo-org.atlassian.net/browse/GEOS-9779) Upgrade OSHI libraries to 5.3.3
- [GEOS-9780](https://osgeo-org.atlassian.net/browse/GEOS-9780) status page shows (read-only) loopback partitions
> [GEOS-9779][GEOS-9780] Upgrade OSHI from 3.13.3 to 5.3.3

- LICENSE.txt
- src/main/src/main/java/org/geoserver/system/status/OSHISystemInfoCollector.java
- src/main/src/test/java/org/geoserver/system/status/SystemInfoCollectorTest.java
- src/pom.xml
> [Backport 2.18.x][GEOS-9779][GEOS-9780] Upgrade OSHI from 3.13.3 to 5.3.3

- LICENSE.txt
- src/main/src/main/java/org/geoserver/system/status/OSHISystemInfoCollector.java
- src/main/src/test/java/org/geoserver/system/status/SystemInfoCollectorTest.java
- src/pom.xml
> [Backport 2.17.x][GEOS-9779][GEOS-9780] Upgrade OSHI from 3.13.3 to 5.3.3

- src/community/ogcapi/dggs/dggs-clickhouse/src/main/java/org/geootols/dggs/clickhouse/ClickHouseDGGSDataStore.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/api/dggs/AggregateConverter.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/api/dggs/CollectionDAPA.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/api/dggs/CollectionDocument.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/api/dggs/DGGSDAPAExtension.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/api/dggs/DGGSFeatureHTMLMessageConverter.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/api/dggs/DGGSGeometryFilterParser.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/api/dggs/DGGSService.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/resources/org/geoserver/api/dggs/collection_include.ftl
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/resources/org/geoserver/api/dggs/dapa.ftl
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/resources/org/geoserver/api/dggs/zones-content.ftl
- src/community/ogcapi/dggs/ogcapi-dggs/src/test/java/org/geoserver/api/dggs/DAPATest.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/test/java/org/geoserver/api/dggs/LandingPageTest.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/PropertiesParser.java
- src/wfs/src/main/java/org/geoserver/wfs/AliasedQuery.java
- src/wfs/src/main/java/org/geoserver/wfs/request/Query.java
Adds the "position" based endpoints in addition to the area ones, adds ability to select properties in DGGS too.
> DGGS DAPA position endpoints

- src/community/ogcapi/dggs/dggs-clickhouse/src/main/java/org/geootols/dggs/clickhouse/DGGSFeatureCollection.java
- src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/gstore/DGGSGeometryFeatureSource.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/api/dggs/CollectionDAPA.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/api/dggs/CollectionDocument.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/api/dggs/DGGSDAPAExtension.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/api/dggs/FeatureCollectionMessageConverter.java
- src/wfs/src/main/java/org/geoserver/wfs/response/CSVOutputFormat.java
More DGGS DAPA related improvementes 
> Better DAPA output, wire CSV output too

- doc/en/user/source/services/wfs/reference.rst
Add missing ampersands (and incorporate MS Word's grammar improvement)
> Improve documentation

- src/community/ogcapi/dggs/dggs-clickhouse/src/main/java/org/geootols/dggs/clickhouse/ClickHouseDialect.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/api/dggs/CollectionDAPA.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/api/dggs/CollectionDocument.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/api/dggs/DAPAVariables.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/api/dggs/DGGSDAPAExtension.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/api/dggs/DGGSService.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/api/dggs/FeatureCollectionMessageConverter.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/resources/org/geoserver/api/dggs/collection_include.ftl
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/resources/org/geoserver/api/dggs/dapa.ftl
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/resources/org/geoserver/api/dggs/dapaVariables.ftl
- src/community/ogcapi/dggs/ogcapi-dggs/src/main/resources/org/geoserver/api/dggs/openapi.yaml
- src/community/ogcapi/dggs/ogcapi-dggs/src/test/java/org/geoserver/api/dggs/LandingPageTest.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/APIDispatcher.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/APIRequestInfo.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/MessageConverterResponseAdapter.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/api/features/FeatureResponseMessageConverter.java
- src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/api/images/ImageResponseMessageConverter.java
> Some API fixes and improvements, better OpenAPI document, better links from the DAPA resource, make paging work on area/position endpoints

- src/community/ogcapi/dggs/dggs-clickhouse/src/main/java/org/geootols/dggs/clickhouse/ClickHouseDGGStoreFactory.java
- src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/DGGSFactory.java
- src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/DGGSFactoryFinder.java
- src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/gstore/DGGSGeometryStoreFactory.java
- src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/h3/H3DGGSFactory.java
- src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/rhealpix/RHealPixDGGSFactory.java
- src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/MultiDimDataStoreFactory.java
Follow up to https://github.com/geotools/geotools/pull/3195
Won't build until that PR is merged and jars updated in the repos.
> Follow up on GeoTools change of DataStore parameter representation

- doc/en/user/source/styling/sld/extensions/rendering-transform.rst
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9784
Add documentation regarding GroupCandidateSelection rendering transformation
> [GEOS-9784] Documentation for GroupCandidateSelection Rendering transformation

- doc/en/user/source/community/cog/index.rst
- src/pom.xml
Simple update of the imageio-ext release version
> Updating ImageIO-Ext release for latest COG improvements and doc updates

- doc/en/user/source/styling/sld/extensions/rendering-transform.rst
> [2.18.x backport][GEOS-9784] Documentation for GroupCandidateSelection Rendering transformation

- src/pom.xml
Both of these have had some patch releases, so they should be updated.
```
com.oracle.database.jdbc:ojdbc8 ................. 19.7.0.0 -> 19.8.0.0
org.postgresql:postgresql ......................... 42.2.14 -> 42.2.18
```
resolves [GEOS-9793](https://osgeo-org.atlassian.net/browse/GEOS-9793)
see also: https://github.com/geotools/geotools/pull/3207
The …
> [GEOS-9793] Update PostgreSQL (to 42.2.18) and Oracle (to 19.8.0.0) JDBC drivers

- doc/en/user/source/data/database/sqlserver.rst
The types "LINE", "COLLECTION", "MULTILINE", "GEOMETRY" are not supported.
Supported Simple types are:
-Point
-LineString
-CircularString
-CompoundCurve
-Polygon
-CurvePolygon
Collection types are:
-MultiPoint
-MultiLineString
-MultiPolygon
-GeometryCollection
Source: https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-data-types-overview?view=sql-server-ver15
**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or …
> Fixing GEOMETRY_COLUMNS create table code snippit

- src/gwc/src/main/java/org/geoserver/gwc/GWC.java
- src/wms/src/main/java/org/geoserver/wms/map/RenderedImageMapResponse.java
See:
* https://osgeo-org.atlassian.net/browse/GEOS-9800
* https://osgeo-org.atlassian.net/browse/GEOS-9801
As optimizations, they are covered by the existing tests. I've also done some load tests.
> GWC seeding scalability and performance improvements

- src/wms/pom.xml
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/BufferedImageLegendGraphicOutputFormatTest.java
This failure is not getting addressed, and has broken enough builds already.
> Skip WMS GitHub Action OSX build failure that we cannot reproduce on the actual hardware

- src/pom.xml
> Upgrading to jai-ext 1.1.18, better scalability from BufferedImageAdapter

- src/gwc/src/main/java/org/geoserver/gwc/GWC.java
- src/pom.xml
- src/wms/src/main/java/org/geoserver/wms/map/RenderedImageMapResponse.java
Backport of a few scalability improvements landed on master
> GWC seeding scalability improvements, backport to 2.18.x

- src/wms/pom.xml
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/BufferedImageLegendGraphicOutputFormatTest.java
> Skip WMS GitHub Action OSX build failure that we cannot reproduce on the full hardware (2.18.x backport)

- src/wms/pom.xml
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/BufferedImageLegendGraphicOutputFormatTest.java
> Skip WMS GitHub Action OSX build failure that we cannot reproduce on the full hardware (2.17.x backport)

- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteTest.java
- src/main/src/main/java/applicationContext.xml
- src/main/src/main/java/org/geoserver/ows/HTTPHeadersCollector.java
- src/main/src/main/java/org/geoserver/ows/ProxifyingURLMangler.java
- src/main/src/test/java/org/vfny/geoserver/util/URLProxifyingTest.java
See details at: https://osgeo-org.atlassian.net/browse/GEOS-9816
> [GEOS-9816] Download links from the result of an asynch process will not honor the proxy base URL, if it uses HTTP header variables

- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteTest.java
- src/main/src/main/java/applicationContext.xml
- src/main/src/main/java/org/geoserver/ows/HTTPHeadersCollector.java
- src/main/src/main/java/org/geoserver/ows/ProxifyingURLMangler.java
- src/main/src/test/java/org/vfny/geoserver/util/URLProxifyingTest.java
2.18.x backport of https://github.com/geoserver/geoserver/pull/4592
> [GEOS-9816] Download links from the result of an asynch process will not honor the proxy base URL, if it uses HTTP header variables (2.18.x backport)

- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteTest.java
- src/main/src/main/java/applicationContext.xml
- src/main/src/main/java/org/geoserver/ows/HTTPHeadersCollector.java
- src/main/src/main/java/org/geoserver/ows/ProxifyingURLMangler.java
- src/main/src/test/java/org/vfny/geoserver/util/URLProxifyingTest.java
> [GEOS-9816] Download links from the result of an asynch process will not honor the proxy base URL, if it uses HTTP header variables (2.17.x backport)

- src/community/security/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuth2SecurityConfiguration.java
- src/community/security/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilter.java
- src/community/security/oauth2-openid-connect/pom.xml
- src/community/security/oauth2-openid-connect/src/main/java/org/geoserver/security/oauth2/DiscoveryClient.java
- src/community/security/oauth2-openid-connect/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java
- src/community/security/oauth2-openid-connect/src/main/java/org/geoserver/security/oauth2/OpenIdConnectFilterConfig.java
- src/community/security/oauth2-openid-connect/src/main/java/org/geoserver/security/oauth2/OpenIdConnectSecurityConfiguration.java
- src/community/security/oauth2-openid-connect/src/main/java/org/geoserver/security/oauth2/ValidatingOAuth2RestTemplate.java
- src/community/security/oauth2-openid-connect/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.html
- src/community/security/oauth2-openid-connect/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.java
- src/community/security/oauth2-openid-connect/src/main/resources/GeoServerApplication.properties
- src/community/security/oauth2-openid-connect/src/test/java/org/geoserver/security/oauth2/DiscoveryClientTest.java
See: https://osgeo-org.atlassian.net/browse/GEOS-9822
> [GEOS-9822] Add Id Token signature validation in the OpenId Connect flow

- src/pom.xml
The Apache project has resolved CVE-2020-13956
resolves: https://osgeo-org.atlassian.net/browse/GEOS-9842
see also: https://github.com/geotools/geotools/pull/3286
> [GEOS-9842] Update Apache HTTP components to 4.5.13

- src/pom.xml
> [2.18.x backport][GEOS-9842] Update Apache HTTP components to 4.5.13

- src/pom.xml
> [2.17.x backport][GEOS-9842] Update Apache HTTP components to 4.5.13

- build/qa/dependency-check-suppression.xml
- src/pom.xml
though currently not used AFIAK in the geoserver builds, it's nice to have this up-to-date
> Update dependencycheck plugin

- src/main/src/main/java/org/geoserver/catalog/SLDPackageHandler.java
- src/pom.xml
- src/restconfig/src/main/java/org/geoserver/rest/catalog/StyleController.java
Guava fixed CVE-2020-8908 (a temp directory creation vulnerability)
resolves https://osgeo-org.atlassian.net/browse/GEOS-9843
see also https://github.com/geotools/geotools/pull/3289
> [GEOS-9843] Update Guava to 30.1-jre

- src/main/src/main/java/org/geoserver/catalog/SLDPackageHandler.java
- src/pom.xml
- src/restconfig/src/main/java/org/geoserver/rest/catalog/StyleController.java
> [2.17 backport][GEOS-9843] Update Guava to 30.1-jre

- src/main/src/main/java/org/geoserver/catalog/SLDPackageHandler.java
- src/pom.xml
- src/restconfig/src/main/java/org/geoserver/rest/catalog/StyleController.java
> [2.18 backport][GEOS-9843] Update Guava to 30.1-jre

- src/pom.xml
- src/web/app/src/test/java/org/geoserver/web/Start.java
> [2.18.x backport][GEOS-9850] Bump jetty.version from 9.4.18.v20190429 to 9.4.35.v20201120

- src/pom.xml
- src/web/app/src/test/java/org/geoserver/web/Start.java
> [2.17.x backport][GEOS-9850] Bump jetty.version from 9.4.18.v20190429 to 9.4.35.v20201120

- src/pom.xml
Update to the latest JTS 1.18.0 release matching GeoTools.
> [GEOS-9857]  Upgrade to JTS Topology Suite 1.18.0

- build/qa/pmd-ruleset.xml
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/onlineTest/support/DatabaseUtil.java
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/gs/GridCoverage2DRIA.java
- src/main/src/main/java/org/geoserver/GeoserverInitStartupListener.java
- src/main/src/main/java/org/geoserver/security/RESTfulPathBasedFilterInvocationDefinitionMap.java
- src/wms/src/main/java/org/geoserver/wms/map/RenderedImageTimeDecorator.java
- src/wms/src/test/java/org/geoserver/wms/map/RenderedImageMapOutputFormatTest.java
> [GEOS-9854] Remove usave of Vector/Hashtable, replace with ArrayList and HashMap, add PMD rule to enforce it

- src/community/security/oauth2-core/src/main/java/org/geoserver/security/oauth2/OAuth2AccessTokenURLMangler.java
- src/community/security/oauth2-geonode/src/test/java/org/geoserver/security/oauth2/OAuth2RestTemplateTest.java
> [Fixes GEOS-9836] [OAUTH2] Mangler enabled by default exposes "access_token" to OWS URLs

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/validator/MultiplicityValidator.java
This follows up https://github.com/geoserver/geoserver/pull/4643 for a "wrong import" identified by @aaime .
- [N/A] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [N/A] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
> fix WPS validator Collection usage

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/JDBCLifecycleHandler.java
- src/community/jdbcconfig/src/main/resources/applicationContext.xml
- src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/catalog/CatalogImplWithJDBCFacadeTest.java
See:
* [JDBCConfig does not drop its caches on a GeoServer reset call](https://osgeo-org.atlassian.net/browse/GEOS-9863)
* [JDBCConfig is deadlock prone](https://osgeo-org.atlassian.net/browse/GEOS-9838)
* [JDBCConfig throws concurrent modification exceptions if hit by high concurrent load right after startup](https://osgeo-org.atlassian.net/browse/GEOS-9519)
For all pull …
> JDBCConfig load and concurrency improvements

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/JDBCLifecycleHandler.java
- src/community/jdbcconfig/src/main/resources/applicationContext.xml
- src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/catalog/CatalogImplWithJDBCFacadeTest.java
[GEOS-9863] [GEOS-9838] [GEOS-9519]
JDBCConfig does not drop its caches on a GeoServer reset call
JDBCConfig is deadlock prone
JDBCConfig throws concurrent modification exceptions if hit by high concurrent load right after startup …
> JDBCConfig load and concurrency improvements (2.18.x)

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/JDBCLifecycleHandler.java
- src/community/jdbcconfig/src/main/resources/applicationContext.xml
- src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/catalog/CatalogImplWithJDBCFacadeTest.java
[GEOS-9863] [GEOS-9838] [GEOS-9519]
JDBCConfig does not drop its caches on a GeoServer reset call
JDBCConfig is deadlock prone
JDBCConfig throws concurrent modification exceptions if hit by high concurrent load right after startup …
> JDBCConfig load and concurrency improvements (2.17.x)

- src/pom.xml
- src/web/app/src/test/java/org/geoserver/web/Start.java
Reverts geoserver/geoserver#4631
> Revert "[2.17.x backport][GEOS-9850] Bump jetty.version from 9.4.18.v20190429 to 9.4.35.v20201120"

- src/pom.xml
- src/web/app/src/test/java/org/geoserver/web/Start.java
Reverts geoserver/geoserver#4632
> Revert "[2.18.x backport][GEOS-9850] Bump jetty.version from 9.4.18.v20190429 to 9.4.35.v20201120"

- src/pom.xml
- src/web/app/src/test/java/org/geoserver/web/Start.java
Reverts geoserver/geoserver#4595
> Revert "[GEOS-9850] Bump jetty.version from 9.4.18.v20190429 to 9.4.35.v20201120"

- src/release/ext-geofence-server.xml
Add missing deps to `geofence-server` zip plugin.
> [GEOS-9845] [2.18.x] GeoFence Server Dependency Issue

- src/release/ext-geofence-server.xml
Add missing deps to `geofence-server` zip plugin.
> [GEOS-9845] GeoFence Server Dependency Issue

- src/pom.xml
Upgrade to version 5.4.0 of the Oshi library that provides OpenBSD support
fixes https://osgeo-org.atlassian.net/browse/GEOS-9851
> GEOS-9851 fix GeoServer fails to start on OpenBSD

- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapIntegrationTest.java
See https://osgeo-org.atlassian.net/browse/GEOS-9870
This changes the target pixels to the vertical bar on the left side of the scale box, which
looks like its more stable (based on test files in GEOS-6482).
- [N/A] New unit tests have been added covering the changes
- [N/A] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.
> [GEOS-9870] Make WMS GetMapIntegrationTest work with OpenJDK 11

- src/pom.xml
Updating jai-ext to 1.1.19 to include this fix: geosolutions-it/jai-ext#175
The fix is about transparent color encofing is paletted images (e.g. PNG8)
> [GEOS-9873]: updated jai-ext to 1.1.19

- src/main/src/main/resources/org/geoserver/catalog/impl/CatalogPropertyAccessor_FullTextProperties.properties
- src/web/core/src/main/java/org/geoserver/web/wicket/GeoServerTablePanel.java
- src/web/wms/src/test/java/org/geoserver/wms/web/data/StylePageTest.java
- src/web/wms/src/test/resources/org/geoserver/wms/web/data/simplePoint.sld
See: https://osgeo-org.atlassian.net/browse/GEOS-9885
> [GEOS-9885] Allow for workspace filtering in the style page

- src/pom.xml
This is a change to the jacoco version, which is only developer-visible.
This picks up a few bug fixes, but is also important for being able to check coverage on future JDK versions.
This won't be tested by CI, but I did do a local release build with JDK11, and checked a few generated results.
- [N/A] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [N/A] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [N/A] New unit tests have been added covering the changes
- [N/A] …
> update Jacoco to 0.8.6

- src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/RasterSymbolizerBuilder.java
- src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/ClassifierTest.java
> [2.18.x backport][GEOS-9881] SldService throws IndexOutOfBoundException when percentages and continuous parameters are both set to true

- doc/en/user/source/community/jms-cluster/installation.rst
> Update installation.rst fixed the path

- build/qa/dependency-check-suppression.xml
- src/pom.xml
update this Maven plugin to the currently supported release
> Bump org.owasp:dependency-check-maven plugin

- doc/en/user/source/data/app-schema/wfs-2.0-support.rst
- src/extension/app-schema/app-schema-test/pom.xml
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/GetFeaturesHitsTest.java
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/FirstParentFeature.json
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/ParentFeature.json
This pr:
- add tests for count query in app-schema;
- add documentation regarding a new parameter to allow or disable count queries.
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9879
blocked by https://osgeo-org.atlassian.net/browse/GEOT-6794
The following are required only for core and extension modules (they are welcomed, but not required, …
> [GEOS-9879] Integration test for AppSchema count query

- doc/en/user/source/data/app-schema/wfs-2.0-support.rst
- src/extension/app-schema/app-schema-test/pom.xml
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/GetFeaturesHitsTest.java
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/FirstParentFeature.json
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/ParentFeature.json
> [2.18.x backport][GEOS-9879] Integration test for AppSchema count query (#4676)

- doc/en/user/source/data/app-schema/wfs-2.0-support.rst
- src/extension/app-schema/app-schema-test/pom.xml
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/GetFeaturesHitsTest.java
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/FirstParentFeature.json
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/ParentFeature.json
> [2.17.x backport][GEOS-9879] Integration test for AppSchema count query

- src/restconfig/src/main/java/org/geoserver/rest/security/AbstractAclController.java
- src/restconfig/src/main/java/org/geoserver/rest/security/CatalogModeController.java
- src/restconfig/src/main/java/org/geoserver/rest/security/MasterPasswordController.java
- src/restconfig/src/main/java/org/geoserver/rest/security/UserPasswordController.java
> Rest log typo

- src/ows/src/main/java/org/geoserver/ows/util/KvpUtils.java
- src/ows/src/test/java/org/geoserver/ows/kvp/KvpUtilsTest.java
Adding a NPE check to KVPUtils
> [GEOS-9900]:KVPUtils Fixing KVP parsing NPE check

- src/community/security/oauth2-openid-connect/src/main/java/org/geoserver/security/oauth2/services/OpenIdConnectTokenServices.java
- src/community/security/oauth2-openid-connect/src/test/java/org/geoserver/security/oauth2/OpenIdConnectIntegrationTest.java
See: https://osgeo-org.atlassian.net/browse/GEOS-9896
> [GEOS9869] OpenId connect authorization fails when the authentication token is too large

- .github/workflows/docs.yml
- .github/workflows/linux_jdk11.yml
- .github/workflows/linux_jdk8.yml
- .github/workflows/qa.yml
The split landed on master, it's useful, backporting to 2.18.x
> ci: split linux build into separate jobs - 2.18.x

- src/gwc/src/test/java/org/geoserver/gwc/layer/DefaultTileLayerCatalogTest.java
This test keeps on randomly failing on GitHub actions, the max wait time is too short
> [GEOS-9966] DefaultTileLayerCatalogTest.testEvents randomly fails on PR GitHub actions

- src/pom.xml
keep this maven pugin up-to-date eventhough it is currently not used in any CI jobs
> Update dependency-check-maven plugin to 6.1.1

- src/pom.xml
fixes https://osgeo-org.atlassian.net/browse/GEOS-9908
> [GEOS-9908] Bump com.github.oshi:oshi-core from 5.4.0 to 5.5.0 for new Apple hardware support 

- src/web/app/pom.xml
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9910
> [GEOS-9910] Wrong groupId for params-extractor profile in web-app pom.xml

- src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/UrlMangler.java
- src/extension/params-extractor/src/test/java/org/geoserver/params/extractor/UrlManglerTest.java
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9911
> [GEOS-9911] Params-extractor plugin, wrong url in getCapabilities when having context with addition /

- src/community/security/oauth2-openid-connect/src/main/java/org/geoserver/security/oauth2/services/OpenIdConnectTokenServices.java
- src/community/security/oauth2-openid-connect/src/test/java/org/geoserver/security/oauth2/OpenIdConnectIntegrationTest.java
> [GEOS-9869] OpenId connect authorization fails when the authentication token is too large (2.18.x)

- src/gwc/src/test/java/org/geoserver/gwc/layer/DefaultTileLayerCatalogTest.java
> Random test failures in DefaultTileLayerCatalogTest (2.17.x backport)

- doc/en/user/source/rest/index.rst
As per discussion on the list.
> Warn users about trying to generate clients from the swagger files

- .github/workflows/docs.yml
- .github/workflows/linux_jdk11.yml
- .github/workflows/linux_jdk8.yml
- .github/workflows/qa.yml
Backport to 2.17.x of a change already happened on master
> ci: split linux build into separate jobs - 2.17.x

- doc/en/user/source/community/elasticsearch/index.rst
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticConfigurationPage.java
Updates the UI and documentation to reflect changes to the elasticsearch community module.
Coincides with GeoTools PR: https://github.com/geotools/geotools/pull/2953
> [GEOT-6577] Allow plugin to handle multiple valid date formats from elastic

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NoIdExpressionTest.java
This pr adds an integration test for [GEOT-6804](https://osgeo-org.atlassian.net/browse/GEOT-6804)
Jira ticket: https://osgeo-org.atlassian.net/browse/GEOS-9893
> [GEOS-9893] Integration test AppSchema without IdExpression and startIndex param

- doc/en/README.md
- doc/en/user/source/community/backuprestore/installation.rst
update to current GS version, remove reference to three (?) zip files
The following are required only for core and extension modules (they are welcomed, but not required, for community …
> Update backup module installation.rst

- src/extension/app-schema/app-schema-solr-test/src/test/java/org/geoserver/test/onlineTest/ComplexSolrTest.java
- src/extension/app-schema/app-schema-test/pom.xml
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/GetFeatureNumberMatchedFeatureChainingTest.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/GetFeaturesNumberMatchedTest.java
Integration postgis online test for Binary Nested filters for AppSchema count query
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9918
> [GEOS-9918] Integration test nested binary filter for AppSchema count query

- src/extension/app-schema/app-schema-solr-test/src/test/java/org/geoserver/test/onlineTest/ComplexSolrTest.java
- src/extension/app-schema/app-schema-test/pom.xml
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/GetFeatureNumberMatchedFeatureChainingTest.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/GetFeaturesNumberMatchedTest.java
> [2.18.x backport][GEOS-9918] Integration test nested binary filter for AppSchema count query

- src/extension/app-schema/app-schema-solr-test/src/test/java/org/geoserver/test/onlineTest/ComplexSolrTest.java
- src/extension/app-schema/app-schema-test/pom.xml
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/GetFeatureNumberMatchedFeatureChainingTest.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/GetFeaturesNumberMatchedTest.java
> [2.17.x backport][GEOS-9918] Integration test nested binary filter for AppSchema count query

- src/community/ogcapi/dggs/ogcapi-dggs/src/test/java/org/geoserver/ogcapi/dggs/LandingPageTest.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AbstractLandingPageDocument.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AbstractLandingPageDocumentNoConformance.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/Link.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/FeaturesLandingPage.java
- src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/ogcapi/images/ImagesLandingPage.java
- src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/ogcapi/images/LandingPageTest.java
- src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/ogcapi/styles/LandingPageTest.java
- src/community/ogcapi/ogcapi-tiled-features/src/main/java/org/geoserver/ogcapi/features/tiled/TiledFeaturesExtension.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/TilesLandingPage.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/tiles/LandingPageTest.java
This updates ogcapi implementations to reflect changes to OGC API Common that require different link `rel` values. Basically, all the non-IANA stuff has moved to a URI form.
I assume this doesn't (yet) impact on Features, because it isn't derived from Common. So there is a bit of finessing the Landing Page classes to make sure that still uses the old values.
- [N/A] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic …
> Update link rel values to reflect commons changes

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/FreemarkerTemplateSupport.java
Issue found while writing docs.
> Prefix template lookup to prevent conflict between ogcapi services

- doc/en/user/source/data/database/db2.rst
- src/release/extensions/db2/db2-readme.txt
Update db2.rst describing DB2 extension installation.
Update db2-readme.txt to correct JDBC driver files required.
fixes [GEOS-9915](https://osgeo-org.atlassian.net/browse/GEOS-9915)
> [GEOS-9915] DB2 installation documentation and readme are outdated

- src/extension/IBM-IPLA.txt
- src/release/ext-db2.xml
- src/release/extensions/db2/db2-readme.txt
Adds the IBM Db2 jdbc driver provided by the Geotools transitive dependency to the zip file so it is no longer required to get that seperately.
Adds the IBM IPLA which governs redistribution of the driver.
depends on https://github.com/geotools/geotools/pull/3361
closes [GEOS-9922](https://osgeo-org.atlassian.net/browse/GEOS-9922)
/cc @dwadler
The …
> [GEOS-9922] include Db2 JDBC driver dependency

- src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/maps/MapsLandingPage.java
- src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/maps/MapsService.java
- src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/maps/ConformanceTest.java
- src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/maps/LandingPageTest.java
- src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/maps/MapsTestSupport.java
- src/community/ogcapi/pom.xml
- src/community/release/pom.xml
Adds it into the build.
Includes minor fixes and tests.
> Minor cleanups for ogcapi-maps

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIRequestInfo.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AbstractLandingPageDocument.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AbstractLandingPageDocumentNoConformance.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AttributeType.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/CollectionExtents.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/InvalidParameterValueException.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/LocalWorkspaceURLPathHelper.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/OpenAPICallback.java
Figured this was a good cleanup activity, making a best guess at public javadocs (corrections welcome).
> Update attribute type enum and model javadocs

- src/pom.xml
Includes this fix: geosolutions-it/jai-ext#278
The fix is related to color encoding in paletted images
Requires https://github.com/geotools/geotools/pull/3364 to be merged first
The following …
> [GEOS-9925] update jaiext to 1.1.20

- src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/maps/CollectionsDocument.java
- src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/maps/HTMLMapMessageConverter.java
- src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/maps/MapsService.java
- src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/maps/CollectionsTest.java
- src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/maps/ConformanceTest.java
- src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/maps/StylesTest.java
Continue work on ogcapi-maps community module.
I'm not 100% convinced on compliance for the extensions (more because the spec is still fluid), however I assume we'd want those when it gets to ETS time, so adding.
> More tests and minor cleanups for ogcapi-maps

- src/extension/csw/simple-store/src/test/java/org/geoserver/csw/store/simple/SimpleCatalogStoreTest.java
- src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/WCSMultiDimSubsetTest.java
- src/extension/sldService/src/main/java/org/geoserver/sldservice/rest/ClassifierController.java
- src/extension/wps/web-wps/src/main/java/org/geoserver/wps/web/ProcessStatusProvider.java
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/ArcGridPPIO.java
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/SLDStylePPIO.java
- src/kml/src/main/java/org/geoserver/kml/regionate/ExternalSortRegionatingStrategy.java
- src/kml/src/main/java/org/geoserver/kml/regionate/NativeSortRegionatingStrategy.java
- src/kml/src/main/java/org/geoserver/kml/regionate/RandomRegionatingStrategy.java
- src/main/src/main/java/org/geoserver/catalog/util/ReaderDimensionsAccessor.java
- src/web/wms/src/main/java/org/geoserver/wms/web/data/DataPanel.java
- src/wms/src/test/java/org/geoserver/wms/map/RenderedImageMapOutputFormatTest.java
- src/wms/src/test/java/org/geoserver/wms/svg/SVGMapProducerTest.java
Follows up with (and requires) https://github.com/geotools/geotools/pull/3317
(automatic refactors made by IntelliJ)
> Follow up GeoTools varaargs introduction

- src/community/metadata/src/main/java/org/geoserver/metadata/web/MetadataTemplateDataProvider.java
> Metadata community module: upstream upgrade

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NoIdExpressionTest.java
> [2.18.x backport][GEOS-9893] Integration test AppSchema without IdExpression and startIndex param

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NoIdExpressionTest.java
> [2.17.x backport][GEOS-9893] Integration test AppSchema without IdExpression and startIndex param

- src/extension/geofence-server/src/test/java/org/geoserver/geofence/rest/RulesRestControllerTest.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/rest/xml/JaxbRule.java
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9909
> [GEOS-9909] Geofence spatialFilterType and CRS in allowed area not included in restOutput

- src/pom.xml
Update PostgreSQL and Oracle JDBC drivers:
```
com.oracle.database.jdbc:ojdbc8 ...........19.8.0.0 -> 19.10.0.0
org.postgresql:postgresql ................... 42.2.18 -> 42.2.19
```
see also https://github.com/geotools/geotools/pull/3371
The following are required only for core and extension modules (they are welcomed, but not required, for community …
> [GEOS-9933] [GEOS-9934] Update JDBC drivers: PostgreSQL (to 42.2.19), Oracle (to 19.10.0.0)

- src/pom.xml
Update PostgreSQL and Oracle JDBC drivers:
```
com.oracle.database.jdbc:ojdbc8 ...........19.8.0.0 -> 19.10.0.0
org.postgresql:postgresql ................... 42.2.18 -> 42.2.19
```
backports #4790 to 2.18.x
see https://github.com/geotools/geotools/pull/3372
The following are required only for core and extension modules (they are welcomed, but not …
> [Backport 2.18.x] [GEOS-9933] [GEOS-9934] Update JDBC drivers: PostgreSQL (to 42.2.19), Oracle (to 19.10.0.0)

- src/community/geogig/pom.xml
- src/pom.xml
Upgrade mockito from 2.23.0 (Oct, 2018) to 3.8.0 (Feb, 2021)
> [GEOS-9939] Upgrade mockito 2.23.0 -> 3.8.0

- src/pom.xml
to fix a regression in Windows version parsing
resolves https://osgeo-org.atlassian.net/browse/GEOS-9941
> [GEOS-9411] Bump com.github.oshi:oshi-core from 5.5.0 to 5.5.1

- src/pom.xml
Signed-off-by: Jim Hughes <jhughes@ccri.com>
depends on https://github.com/geotools/geotools/pull/3377
> [GEOS-9940] Upgrade to JTS Topology Suite 1.18.1

- src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
- src/main/src/main/java/org/geoserver/security/decorators/SecuredWebMapTileServer.java
- src/main/src/test/java/org/geoserver/security/decorators/SecuredWMTSLayerTest.java
- src/main/src/test/java/org/geoserver/security/decorators/SecuredWebMapTileServerTest.java
- src/web/core/src/main/java/org/geoserver/web/data/store/WMTSStoreNewPage.java
- src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
- src/wfs/src/test/java/org/geoserver/wfs/remote/v2_0/WfsRemoteStoreTest.java
- src/wfs/src/test/java/org/geoserver/wfs/v1_1/WfsRemoteStoreTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapIntegrationTest.java
Removes a null argument to avoid a compiling error.
> Geos 9903 - Fix issue with http headers missing

- src/community/jdbcstore/src/main/java/org/geoserver/jdbcstore/internal/JDBCDirectoryStructure.java
> GEOS-9930 resource contains outdated metadata

- src/community/cov-json/pom.xml
- src/community/cov-json/src/main/java/applicationContext.xml
- src/community/cov-json/src/main/java/org/geoserver/wcs/responses/CoverageJsonEncoder.java
- src/community/cov-json/src/main/java/org/geoserver/wcs/responses/CoverageJsonResponseDelegate.java
- src/community/cov-json/src/main/java/org/geoserver/wcs/responses/covjson/Axis.java
- src/community/cov-json/src/main/java/org/geoserver/wcs/responses/covjson/Coverage.java
- src/community/cov-json/src/main/java/org/geoserver/wcs/responses/covjson/CoverageJson.java
- src/community/cov-json/src/main/java/org/geoserver/wcs/responses/covjson/Domain.java
- src/community/cov-json/src/main/java/org/geoserver/wcs/responses/covjson/Grid.java
- src/community/cov-json/src/main/java/org/geoserver/wcs/responses/covjson/NdArray.java
- src/community/cov-json/src/main/java/org/geoserver/wcs/responses/covjson/Parameter.java
- src/community/cov-json/src/main/java/org/geoserver/wcs/responses/covjson/PointSeries.java
- src/community/cov-json/src/main/java/org/geoserver/wcs/responses/covjson/Referencing.java
- src/community/cov-json/src/main/java/org/geoserver/wcs/responses/covjson/Sampler.java
- src/community/cov-json/src/test/java/org/geoserver/wcs2_0/CoverageJsonTest.java
- src/community/pom.xml
- src/web/app/pom.xml
cov-json community module.
more tests and doc will follow.
> Cov-json community module

- doc/en/user/source/community/cov-json/index.rst
- doc/en/user/source/community/index.rst
- src/community/release/ext-cov-json.xml
Adding some doc and ext descriptor for nightly build
> [cov-json]:Doc and build file

- src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/WCSNetCDFMosaicTest.java
Fixing WCSNetCDFMosaicTest getTime test
> [GEOS-9945] WCSNetCDFMosaicTest getTime test is timezone dependent

- src/community/flatgeobuf/pom.xml
Upgrade flatgeobuf 3.4.0 -> 3.10.1
> [GEOS-9955] Upgrade flatgeobuf 3.4.0 -> 3.10.1

- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/listener/RestoreJobExecutionListener.java
- src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java
Backup and Restore replaces not involved layers during restore process, generating new IDs and hence breaking GWC layers definitions since they are layer-ID linked.  This PR introduces a fix for this issue.
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-9948
The following are required only for core and extension modules (they are welcomed, but …
> [GEOS-9948] Fix existing layers ID overwrite on Backup & Restore plugin

- doc/en/user/source/configuration/logging.rst
> Typo in 'logging.rst'

- src/community/flatgeobuf/pom.xml
> [GEOS-9955][2.19.x backport] Upgrade flatgeobuf 3.4.0 -> 3.10.1

- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLController.java
> [GEOS-9962] MapML extension won't start on linux

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/DuplicateTypeTest.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/FeatureChainingWfsTest.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/GetPropertyValueTest.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/IdFunctionWfsTest.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/PagingTest.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SortByTest.java
- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/XlinkWfsTest.java
https://osgeo-org.atlassian.net/browse/GEOT-6691
> [GEOT-6691] encodeifempty bij feature chaining - fix app-schema tests

- src/community/release/ext-geopkg.xml
Adding missing jars on geopackage zip.
> [GEOS-9963]: Fixing missing jars on geopackage zip archive

- doc/en/user/source/security/layer.rst
> Fix group name for consistency, and grammar correction

- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/listener/RestoreJobExecutionListener.java
- src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java
Backup and Restore replaces not involved layers during restore process, generating new IDs and hence breaking GWC layers definitions since they are layer-ID linked. This PR introduces a fix for this issue.
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-9948
The following are required only for core and extension modules (they are welcomed, but …
> [2.18.x backport][GEOS-9948]Fix existing layers ID overwrite on Backup & Restore plugin

- src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/functions/MaxXFunction.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/functions/MaxYFunction.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/functions/MinXFunction.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/functions/MinYFunction.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/functions/ServiceLinkFunction.java
- src/extension/dxf/core/src/main/java/org/geoserver/wfs/response/DXFOutputFormat.java
- src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
Some `@Override`s missing on methods added after the pull request was
merged, hence the QA build didn't catch them.
---
> [GEOS-9957] Add missing @Override annotations

- doc/en/docguide/source/install.rst
ant seems obsolete to me.  All other build commands are for maven.
> Update build command from ant to maven

- src/community/pom.xml
- src/community/release/ext-cov-json.xml
- src/community/release/pom.xml
Simple fix of the cov-json zip community packaging
> Fixing cov-json assembly zip

- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLGetFeatureOutputFormat.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLGetFeatureOutputFormatTest.java
Fix bug in tagging output CRS code with MapML citation. Add test for that condition.
> [GEOS-9970] MapML GetFeature bug fix for CRS authority

- src/pom.xml
The Jetty project has resolved CVE-2020-27223
resolves [GEOS-9972](https://osgeo-org.atlassian.net/browse/GEOS-9972)
> [GEOS-9972] Update Jetty to 9.4.38.v20210224

- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/response/GeoJSONGetComplexFeaturesResponseTest.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/response/JSONLDGetComplexFeaturesResponseTest.java
- src/community/features-templating/features-templating-ogcapi/src/test/java/org/geoserver/featurestemplating/response/FlatGeoJSONComplexFeaturesResponseAPITest.java
- src/community/features-templating/features-templating-ogcapi/src/test/java/org/geoserver/featurestemplating/response/GeoJSONGetComplexFeaturesResponseAPITest.java
- src/community/features-templating/features-templating-ogcapi/src/test/java/org/geoserver/featurestemplating/response/JSONLDGetComplexFeaturesResponseAPITest.java
- src/community/features-templating/features-templating-wfs/src/test/java/org/geoserver/featurestemplating/response/FilteringFlatGeoJSONComplexFeaturesResponseTest.java
- src/community/features-templating/features-templating-wfs/src/test/java/org/geoserver/featurestemplating/response/FlatGeoJSONComplexFeaturesResponseWFSTest.java
- src/community/features-templating/features-templating-wfs/src/test/java/org/geoserver/featurestemplating/response/GeoJSONGetComplexFeaturesResponseWFSTest.java
- src/community/features-templating/features-templating-wfs/src/test/java/org/geoserver/featurestemplating/response/JSONLDGetComplexFeaturesResponseFilteringWFSTest.java
- src/community/features-templating/features-templating-wfs/src/test/java/org/geoserver/featurestemplating/response/JSONLDGetComplexFeaturesResponseWFSTest.java
Test data used by tests changed in https://github.com/geotools/geotools/pull/3366
This PR updates expectations.
> Adapting features-template tests to modified test data in GeoTools, due to GEOT-6691

- src/pom.xml
Just updating pom of the latest GS to depend on latest GWC version (since it was behind of 1 version)
> [GEOS-9973]: Updating latest GS to depend on latest GWC

- src/release/ext-app-schema.xml
- src/release/ext-css.xml
Resolves https://osgeo-org.atlassian.net/browse/GEOS-9966
Those two modules have release configurations that `<include>LGPL.txt</include>`.  However we don't have that file. It should be LGPL.md.
To test this, build the release modules (`mvn assembly:single -N`) and inspect zip contents.
- [N/A] New unit tests have been added covering the changes
- [N/A] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to …
> [GEOS-9966] Update CSS + AppSchema release modules to include LGPL

- src/extension/geofence-server/src/test/java/org/geoserver/geofence/rest/RulesRestControllerTest.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/rest/xml/JaxbRule.java
> [backport 2.18.x][GEOS-9909] Geofence spatialFilterType and CRS in allowed area not included in restOutput

- doc/en/user/source/services/wfs/outputformats.rst
- doc/en/user/source/services/wfs/vendor.rst
- src/community/geopkg/src/main/java/org/geoserver/geopkg/GeoPackageGetFeatureOutputFormat.java
- src/community/geopkg/src/test/java/org/geoserver/geopkg/GeoPackageGetFeatureOutputFormatTest.java
- src/extension/dxf/core/src/main/java/org/geoserver/wfs/response/DXFOutputFormat.java
- src/extension/excel/src/main/java/org/geoserver/wfs/response/ExcelOutputFormat.java
- src/extension/ogr/ogr-wfs/src/main/java/org/geoserver/wfs/response/Ogr2OgrOutputFormat.java
- src/extension/xslt/src/main/java/org/geoserver/wfs/xslt/XSLTOutputFormat.java
- src/kml/src/main/java/org/geoserver/kml/WFSKMLOutputFormat.java
- src/wfs/src/main/java/org/geoserver/wfs/WFSGetFeatureOutputFormat.java
- src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
- src/wfs/src/main/java/org/geoserver/wfs/response/CSVOutputFormat.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/GML2OutputFormat.java
- src/wfs/src/test/java/org/geoserver/wfs/response/CSVOutputFormatTest.java
- src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureJoinTest.java
Backport of https://github.com/geoserver/geoserver/pull/4791
> [2.19.x-backport][GEOS-9944] Revise generated filenames, extension, and format_option

- src/pom.xml
Reverts geoserver/geoserver#4860
> Revert "[2.19.x backport][GEOS-9972] Update Jetty to 9.4.38.v20210224"

- src/community/backup-restore/pom.xml
- src/extension/sldService/pom.xml
- src/restconfig/pom.xml
- src/restconfig/src/main/java/org/geoserver/rest/catalog/AvailableResourcesConverter.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/MapXMLConverter.java
- src/restconfig/src/main/java/org/geoserver/rest/security/RuleMapXMLConverter.java
- src/wms/pom.xml
- src/wms/src/main/java/org/geoserver/wms/decoration/MapDecorationLayout.java
[JDOM](https://mvnrepository.com/artifact/org.jdom/jdom/2.0.2) latest version is from 2012.
[JDOM-2](https://mvnrepository.com/artifact/org.jdom/jdom2/2.0.6) latest version is from 2015.
Nothing they provide can't be done without standard XML APIs.
Remove direct jdom dependencies in release modules:
Out of scope:
- community module `gs-jms-geoserver`
- community module  `gs-backup-restore`
- community module `gs-taskmanager`
--- …
> [GEOS-9943] Remove dependency on jdom, use standard XML APIs

- src/pom.xml
Reverts geoserver/geoserver#4859
> Revert "[GEOS-9972] Update Jetty to 9.4.38.v20210224"

- src/main/src/main/java/org/geoserver/template/FeatureWrapper.java
- src/main/src/main/java/org/geoserver/template/TemplateUtils.java
- src/pom.xml
- src/rest/src/main/java/org/geoserver/rest/IndexController.java
- src/rest/src/main/java/org/geoserver/rest/ObjectToMapWrapper.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/AboutStatusController.java
- src/web/wms/src/main/java/org/geoserver/wms/web/data/OpenLayersPreviewPanel.java
- src/wms/src/main/java/org/geoserver/wms/decoration/TextDecoration.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/FeatureTemplate.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/FreeMarkerTemplateManager.java
- src/wms/src/main/java/org/geoserver/wms/map/AbstractOpenLayersMapOutputFormat.java
- src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapOutputFormatTest.java
- src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapTemplateTest.java
Backport of https://github.com/geoserver/geoserver/pull/4782
> [GEOS-9331] Upgrade Freemarker to 2.3.31 (2.18.x backport)

- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/ogcapi/dggs/CollectionDocument.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/test/java/org/geoserver/ogcapi/dggs/DGGSTestSupport.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/TimeExtentCalculator.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/CollectionDocument.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/FeatureService.java
Usual community plugin changes, checking it builds fine on server before merging.
> Adding date range support in DGGS collections (and tentative impl in features too)

- src/community/release/ext-cov-json.xml
simple fix on the assembly of the cov-json community plugin
> Fixing cov-json community zip

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
- src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/ConfigDatabaseTest.java
- src/community/jdbcconfig/src/test/resources/capabilities.xml
- src/main/src/main/java/org/geoserver/catalog/impl/StyleInfoImpl.java
- src/main/src/main/java/org/geoserver/catalog/impl/WMSLayerInfoImpl.java
- src/web/core/src/main/java/org/geoserver/web/data/resource/ResourceConfigurationPage.java
- src/web/core/src/main/java/org/geoserver/web/publish/PublishedConfigurationPage.java
See: https://osgeo-org.atlassian.net/browse/GEOS-9985
One set of changes makes JDBCConfig with the StyleInfo created on the fly by WMS cascaded layers, the other is making the GUI a bit more robust and more likely to report issues.
The following are required only for core and extension modules (they are welcomed, but not required, for community …
> [GEOS-9985] Impossible to configure a WMS cascading layer with JDBCConfig

- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadAnimationProcess.java
See: https://osgeo-org.atlassian.net/browse/GEOS-9982
> [GEOS-9982] DownloadAnimation process can lead to OOM

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
- src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/ConfigDatabaseTest.java
- src/community/jdbcconfig/src/test/resources/capabilities.xml
- src/main/src/main/java/org/geoserver/catalog/impl/StyleInfoImpl.java
- src/main/src/main/java/org/geoserver/catalog/impl/WMSLayerInfoImpl.java
- src/web/core/src/main/java/org/geoserver/web/data/resource/ResourceConfigurationPage.java
- src/web/core/src/main/java/org/geoserver/web/publish/PublishedConfigurationPage.java
> [GEOS-9985] Impossible to configure a WMS cascading layer with JDBCConfig (2.19.x backport)

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
- src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/ConfigDatabaseTest.java
- src/community/jdbcconfig/src/test/resources/capabilities.xml
- src/main/src/main/java/org/geoserver/catalog/impl/StyleInfoImpl.java
- src/main/src/main/java/org/geoserver/catalog/impl/WMSLayerInfoImpl.java
- src/web/core/src/main/java/org/geoserver/web/data/resource/ResourceConfigurationPage.java
- src/web/core/src/main/java/org/geoserver/web/publish/PublishedConfigurationPage.java
> [GEOS-9985] Impossible to configure a WMS cascading layer with JDBCConfig (2.18.x backport) 

- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadAnimationProcess.java
2.19.x backport of https://github.com/geoserver/geoserver/pull/4879
> [GEOS-9982] DownloadAnimation process can lead to OOM (2.19.x backport)

- src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadAnimationProcess.java
> [GEOS-9982] DownloadAnimation process can lead to OOM (2.18.x backport)

- doc/en/user/source/community/oauth2/index.rst
> Update OAuth2 to explain what xxxx means

- src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/GeoServerKeycloakFilter.java
- src/community/security/keycloak/src/test/java/org/geoserver/security/keycloak/GeoServerKeycloakFilterTest.java
This adds support for the x-forwarded-proto header to the keycloak community extension.
See https://osgeo-org.atlassian.net/browse/GEOS-9989
> Use x-forwarded-for header

- doc/en/user/source/extensions/inspire/using.rst
- src/extension/inspire/src/main/java/org/geoserver/inspire/InspireSchema.java
- src/extension/inspire/src/test/java/org/geoserver/inspire/wms/WMSExtendedCapabilitiesTest.java
[![GEOS-10002](https://badgen.net/badge/JIRA/GEOS-10002/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10002) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-10002
this pr udpates the Inspire schemas url from http to https.
**Submitting the PR does not …
> [GEOS-10002] Update url for Inspire Schemas in gs-inspire extension

- doc/en/user/source/extensions/inspire/using.rst
- src/extension/inspire/src/main/java/org/geoserver/inspire/InspireSchema.java
- src/extension/inspire/src/test/java/org/geoserver/inspire/wms/WMSExtendedCapabilitiesTest.java
[![GEOS-10002](https://badgen.net/badge/JIRA/GEOS-10002/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10002) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
* [GEOS-10002] Update url for Inspire Schemas in gs-inspire extension …
> [2.18.x backport][GEOS-10002] Update url for Inspire Schemas in gs-inspire extension

- doc/en/user/source/extensions/inspire/using.rst
- src/extension/inspire/src/main/java/org/geoserver/inspire/InspireSchema.java
- src/extension/inspire/src/test/java/org/geoserver/inspire/wms/WMSExtendedCapabilitiesTest.java
[![GEOS-10002](https://badgen.net/badge/JIRA/GEOS-10002/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10002) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
* [GEOS-10002] Update url for Inspire Schemas in gs-inspire extension …
> [2.19.x backport][GEOS-10002] Update url for Inspire Schemas in gs-inspire extension

- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccess.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/OpenSearchAccess.java
- src/community/oseo/oseo-core/src/test/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccessTest.java
- src/community/oseo/oseo-core/src/test/resources/collection_test_data.sql
- src/community/oseo/oseo-core/src/test/resources/postgis.sql
- src/community/oseo/oseo-core/src/test/resources/product_test_data.sql
- src/community/oseo/oseo-rest/src/main/java/org/geoserver/opensearch/rest/AbstractOpenSearchController.java
- src/community/oseo/oseo-rest/src/test/java/org/geoserver/opensearch/rest/CollectionsControllerTest.java
- src/community/oseo/oseo-rest/src/test/java/org/geoserver/opensearch/rest/ProductsControllerTest.java
- src/community/oseo/oseo-service/src/main/java/org/geoserver/opensearch/eo/DefaultOpenSearchEoService.java
- src/community/oseo/oseo-service/src/test/java/org/geoserver/opensearch/eo/DescriptionTest.java
- src/community/oseo/oseo-service/src/test/java/org/geoserver/opensearch/eo/SearchTest.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACAPIBuilder.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACService.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/CollectionsTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/ItemsTest.java
- src/platform/src/main/java/org/geoserver/platform/OWS20Exception.java
Just checking if it builds fine before merging.
> Allow disabling collections and products in OpenSearch for EO and STAC

- doc/en/user/source/community/pgraster/pgraster.rst
Trivial typo fix in docs for a community module.
> Trivial docs typo fix

- doc/en/user/source/tutorials/GetFeatureInfo/index.rst
- doc/en/user/source/tutorials/GetFeatureInfo/raster.rst
- src/wms/src/main/java/org/geoserver/wms/featureinfo/ColorMapLabelMatcher.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/ColorMapLabelMatcherExtractor.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/RasterLayerIdentifier.java
- src/wms/src/test/java/org/geoserver/wms/featureinfo/ColorMapLabelMatcherExtractorTest.java
- src/wms/src/test/java/org/geoserver/wms/featureinfo/ColorMapLabelMatcherTest.java
- src/wms/src/test/java/org/geoserver/wms/featureinfo/GetFeatureInfoJSONTest.java
- src/wms/src/test/resources/org/geoserver/wms/featureinfo/labelCustomNameTazDem.sld
- src/wms/src/test/resources/org/geoserver/wms/featureinfo/labelInFeatureInfoTazBm.sld
- src/wms/src/test/resources/org/geoserver/wms/featureinfo/labelInFeatureInfoTazBmMultipleSymbolizers.sld
- src/wms/src/test/resources/org/geoserver/wms/featureinfo/labelInFeatureInfoTazDem.sld
- src/wms/src/test/resources/org/geoserver/wms/featureinfo/labelInFeatureInfoTazDemColorMapValues.sld
- src/wms/src/test/resources/org/geoserver/wms/featureinfo/labelInFeatureInfoTazDemMultipleSymbolizers.sld
- src/wms/src/test/resources/org/geoserver/wms/featureinfo/labelInFeatureInfoTazDemNone.sld
- src/wms/src/test/resources/org/geoserver/wms/featureinfo/labelInFeatureInfoTazDemReplace.sld
[![GEOS-9984](https://badgen.net/badge/JIRA/GEOS-9984/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9984) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Early backport request [here](https://sourceforge.net/p/geoserver/mailman/message/37251754/)
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9984
* [GEOS-9984] ColorMap labels in raster layer GetFeatureInfo response
* review feedback applied
> Reviewing is a …
> [2.18.x backport][GEOS-9984] ColorMap labels in raster layer GetFeatureInfo response

- src/platform/src/main/java/org/geoserver/platform/resource/FileLockProvider.java
- src/platform/src/main/java/org/geoserver/platform/resource/MemoryLockProvider.java
[![GEOS-10009](https://badgen.net/badge/JIRA/GEOS-10009/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10009) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Helps debugging locking issues
**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either …
> [GEOS-10009] Improve logging on lock providers

- src/platform/src/main/java/org/geoserver/platform/resource/FileLockProvider.java
- src/platform/src/main/java/org/geoserver/platform/resource/MemoryLockProvider.java
[![GEOS-10009](https://badgen.net/badge/JIRA/GEOS-10009/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10009) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport of https://github.com/geoserver/geoserver/pull/4946 …
> [GEOS-10009] Improve logging on lock providers (2.19.x)

- src/platform/src/main/java/org/geoserver/platform/resource/FileLockProvider.java
- src/platform/src/main/java/org/geoserver/platform/resource/MemoryLockProvider.java
[![GEOS-10009](https://badgen.net/badge/JIRA/GEOS-10009/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10009) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport of #4946 …
> [GEOS-10009] Improve logging on lock providers (2.18.x)

- src/community/pom.xml
- src/community/schemaless-features/pom.xml
- src/community/schemaless-features/schemaless-core/pom.xml
- src/community/schemaless-features/schemaless-mongo/pom.xml
- src/pom.xml
- src/web/app/pom.xml
[![GEOS-9986](https://badgen.net/badge/JIRA/GEOS-9986/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9986) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Current verification behavior only covered element order, make it verify also formatting. Also upgraded to the latest version.
**Submitting the PR does not …
> [GEOS-9986] Sortpom upgrade, make verification strict

- src/pom.xml
[![GEOS-9986](https://badgen.net/badge/JIRA/GEOS-9986/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9986) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport of https://github.com/geoserver/geoserver/pull/4945
**Submitting the PR does not require you to check all items, but by the time it gets merged, …
> [GEOS-9986] Upgrade sortpom to latest, make verification strict (2.19.x)

- src/release/pom.xml
[![GEOS-10016](https://badgen.net/badge/JIRA/GEOS-10016/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10016) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
App-Schema-core module (gs-app-schema-core.jar artifact) is currently not included on App-Schema zip release distribution, making extensions like simple output feature doesn't work.
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-10016 …
> [GEOS-10016] Fix app-schema-core jar not included on app-schema module zip distribution

- src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/Filter.java
- src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/RulesDao.java
- src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/UrlMangler.java
[![GEOS-10019](https://badgen.net/badge/JIRA/GEOS-10019/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10019) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Improves parameters extractor logging to give us more info about the plugin initialization and at DEBUG level to allow to understand when no rules where matched or the request was ignored.
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if …
> [GEOS-10019] Improve parameters extractor log

- src/community/params-extractor/src/main/java/org/geoserver/params/extractor/Filter.java
- src/community/params-extractor/src/main/java/org/geoserver/params/extractor/RulesDao.java
- src/community/params-extractor/src/main/java/org/geoserver/params/extractor/UrlMangler.java
[![GEOS-10019](https://badgen.net/badge/JIRA/GEOS-10019/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10019) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info) …
> [GEOS-10019] Improve parameters extractor log (backport 2.18.x)

- src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/Filter.java
- src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/RulesDao.java
- src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/UrlMangler.java
[![GEOS-10019](https://badgen.net/badge/JIRA/GEOS-10019/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10019) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info) …
> [GEOS-10019] Improve parameters extractor log (backport 2.19.x)

- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACLandingPage.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACService.java
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/stac/collections.json
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/stac/items.json
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/CollectionsTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/LandingPageTest.java
Bunch of updates to align to 1.0-RC2 version of the spec.
> Upgrading STAC to RC2

- src/release/pom.xml
[![GEOS-10016](https://badgen.net/badge/JIRA/GEOS-10016/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10016) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
App-Schema-core module (gs-app-schema-core.jar artifact) is currently not included on App-Schema zip release distribution, making extensions like simple output feature doesn't work.
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-10016 …
> [2.19.x backport][GEOS-10016] Fix app-schema-core jar not included on app-schema module zip distribution

- src/release/pom.xml
[![GEOS-10016](https://badgen.net/badge/JIRA/GEOS-10016/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10016) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
App-Schema-core module (gs-app-schema-core.jar artifact) is currently not included on App-Schema zip release distribution, making extensions like simple output feature doesn't work.
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-10016 …
> [2.18.x backport][GEOS-10016] Fix app-schema-core jar not included on app-schema module zip distribution

- doc/en/developer/source/policies/index.rst
- doc/en/developer/source/policies/service_providers.rst
[![GSIP-199](https://badgen.net/badge/JIRA/GSIP-199/0052CC)](https://osgeo-org.atlassian.net/browse/GSIP-199) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Document the process to add a service provider to our website, and associated osgeo project page.
Please see https://github.com/geoserver/geoserver/wiki/GISP-199 for details.
Developer documentation process documentation not visible to end users.
> [GSIP-199] Document process to add service providers

- src/main/src/main/java/org/geoserver/catalog/SLDHandler.java
- src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java
[![GEOS-10013](https://badgen.net/badge/JIRA/GEOS-10013/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10013) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-10013 …
> [GEOS-10013] Mark invalid error while validating or saving a Style

- doc/en/user/source/community/gwc-mbtiles/index.rst
- doc/en/user/source/community/index.rst
- src/community/gwc-mbtiles/pom.xml
- src/community/gwc-mbtiles/src/main/java/org/geoserver/gwc/mbtiles/MBTilesLayerIconCustomizer.java
- src/community/gwc-mbtiles/src/main/resources/applicationContext.xml
- src/community/pom.xml
- src/community/release/ext-gwc-mbtiles.xml
- src/community/release/pom.xml
- src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
- src/gwc/src/test/java/org/geoserver/gwc/layer/GeoServerTileLayerTest.java
- src/web/app/pom.xml
- src/web/gwc/src/main/java/org/geoserver/gwc/web/GWCIconFactory.java
- src/web/gwc/src/main/java/org/geoserver/gwc/web/GWCTileLayerIconCustomizer.java
[![GEOS-9995](https://badgen.net/badge/JIRA/GEOS-9995/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9995) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Community module for GWC-MBTiles
**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either …
> [GEOS-9995]: GWC-MBTiles community module

- doc/en/user/source/community/opensearch-eo/STAC.rst
- doc/en/user/source/community/opensearch-eo/configuration.rst
- doc/en/user/source/community/opensearch-eo/index.rst
- doc/en/user/source/community/opensearch-eo/templates.rst
Community modules, checking it's not breaking the build.
> Documentation about templates usage in OpenSearch and STAC

- src/community/release/ext-gwc-mbtiles.xml
Fixing the gs-gwc-mbtiles zip file 
> updating packaged jars on gs-gwc-mbtiles community module

- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/TemplatesReloader.java
- src/community/oseo/oseo-service/src/test/java/org/geoserver/opensearch/eo/GeoJSONSearchTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/CollectionsTest.java
Community module, just making sure not breaking the build.
> OpenSearch: ensure templates are copied over to the data directory on startup (as per documentation)

- doc/en/developer/source/conf.py
- doc/en/docguide/source/conf.py
- doc/en/user/source/conf.py
- doc/zhCN/user/source/conf.py
The link on the right hand side of the docs allows direct edit on github.
That currently goes to the `master` branch. This PR changes to `main`.
> doc: update github 'edit' link branch to main

- src/pom.xml
[![GEOS-10030](https://badgen.net/badge/JIRA/GEOS-10030/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10030) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Title says it all …
> [GEOS-10030] Upgrade imageio-ext to 1.3.6 (geotiff 32bit, deflate/lzw compressed, with predictor = 2)

- src/pom.xml
[![GEOS-10030](https://badgen.net/badge/JIRA/GEOS-10030/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10030) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
2.19.x backport of https://github.com/geoserver/geoserver/pull/4999 …
> [GEOS-10030] Upgrade imageio-ext to 1.3.6 (geotiff 32bit, deflate/lzw compressed, with predictor = 2) (1.19.x)

- src/gwc/src/main/java/org/geoserver/gwc/layer/CatalogLayerEventListener.java
- src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
- src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
- src/gwc/src/test/java/org/geoserver/gwc/layer/GeoServerTileLayerTest.java
[![GEOS-100031](https://badgen.net/badge/JIRA/GEOS-100031/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-100031) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
For …
> [GEOS-100031] GWC loses GridSets bounds when importing data through the Importer plugin

- src/community/oseo/oseo-core/src/test/resources/postgis.sql
[![GEOS-10041](https://badgen.net/badge/JIRA/GEOS-10041/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10041) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Add multicolumn index to speed up WMS requests on the opensearch schema.
https://osgeo-org.atlassian.net/browse/GEOS-10041 …
> [GEOS-10041] Add index to opensearch schema

- src/gwc/src/main/java/org/geoserver/gwc/layer/CatalogLayerEventListener.java
- src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
- src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
- src/gwc/src/test/java/org/geoserver/gwc/layer/GeoServerTileLayerTest.java
[![GEOS-100031](https://badgen.net/badge/JIRA/GEOS-100031/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-100031) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or …
> [GEOS-100031] GWC loses GridSets bounds when importing data through the Importer plugin (2.19.x)

- build/qa/pmd-ruleset.xml
- src/gwc/src/main/java/org/geoserver/gwc/ConfigurableQuotaStoreProvider.java
- src/gwc/src/main/java/org/geoserver/gwc/wms/CachingExtendedCapabilitiesProvider.java
- src/main/src/main/java/org/geoserver/catalog/util/ReaderUtils.java
- src/main/src/main/java/org/geoserver/filters/LoggingFilter.java
- src/main/src/main/java/org/vfny/geoserver/servlets/ServiceStrategyFactory.java
- src/platform/src/main/java/org/geoserver/util/ReaderUtils.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/GMLTransformer.java
- src/web/security/core/src/test/java/org/geoserver/security/web/passwd/PasswordPolicyDetailsPanelTest.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/DimensionHelper.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/ColorMapLabelMatcher.java
[![GEOS-10035](https://badgen.net/badge/JIRA/GEOS-10035/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10035) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
See: https://pmd.github.io/latest/pmd_rules_java_performance.html#unnecessarywrapperobjectcreation
**Submitting the PR does not require you to check all …
> [GEOS-10035] Avoid unnecessary object wrapper creation, add a PMD rule to check it

- doc/en/themes/geoserver/layout.html
[![GEOS-10026](https://badgen.net/badge/JIRA/GEOS-10026/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10026) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
For …
> [GEOS-10026] Link from user documentation to issue tracker

- src/community/oseo/oseo-core/src/test/resources/postgis.sql
[![GEOS-10041](https://badgen.net/badge/JIRA/GEOS-10041/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10041) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Add multicolumn index to speed up WMS requests on the opensearch schema.
https://osgeo-org.atlassian.net/browse/GEOS-10041 …
> [2.19.x backport][GEOS-10041] Add index to opensearch schema

- doc/en/user/source/community/features-templating/installing.rst
- doc/en/user/source/community/mbtiles/installing.rst
- doc/en/user/source/community/ogc-api/install.rst
- doc/en/user/source/community/schemaless-features/install.rst
- doc/en/user/source/community/smart-data-loader/install.rst
- doc/en/user/source/community/web-service-auth/install.rst
- doc/en/user/source/conf.py
- doc/zhCN/user/source/conf.py
[![GEOS-10045](https://badgen.net/badge/JIRA/GEOS-10045/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10045) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This pr
- fix conf.py to use main instead of master for :download_community: and :dowload_extensions: directives
- Fix some install sections for community modules that needed it (eg. :download_extensions:<name>-plugin instead of :download_extensions:<name>). …
> [GEOS-10045] Community module documentation download links point still to master

- doc/en/build.xml
- doc/en/user/source/community/features-templating/installing.rst
- doc/en/user/source/community/mbtiles/installing.rst
- doc/en/user/source/community/schemaless-features/install.rst
- doc/en/user/source/community/smart-data-loader/install.rst
- doc/en/user/source/community/web-service-auth/install.rst
- doc/zhCN/user/source/conf.py
[![GEOS-10045](https://badgen.net/badge/JIRA/GEOS-10045/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10045) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
* [GEOS-10045] Community module documentation download links point still to master
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to …
> [2.18.x backport][GEOS-10045] Community module documentation download links point still to master (#5017)

- doc/en/user/source/community/features-templating/installing.rst
- doc/en/user/source/community/mbtiles/installing.rst
- doc/en/user/source/community/ogc-api/install.rst
- doc/en/user/source/community/schemaless-features/install.rst
- doc/en/user/source/community/smart-data-loader/install.rst
- doc/en/user/source/community/web-service-auth/install.rst
- doc/en/user/source/conf.py
- doc/zhCN/user/source/conf.py
[![GEOS-10045](https://badgen.net/badge/JIRA/GEOS-10045/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10045) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
* [GEOS-10045] Community module documentation download links point still to master
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to …
> [2.19.x backport] [GEOS-10045] Community module documentation download links point still to master (#5017)

- .github/stale.yml
> Adding configuration for stale, https://probot.github.io/apps/stale/

- src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
[![GEOS-10062](https://badgen.net/badge/JIRA/GEOS-10062/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10062) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
A test is not provided since the problem cannot be reproduced in a test environment and the fix implies a small refact of the current  code. Details on the Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-10062.
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. …
> [GEOS-10062] LayerCache CatalogLinester might not be attached to the catalog at startup

- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceGetMapIntegrationTest.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
- src/wms/src/test/java/org/geoserver/wms/WMSTestSupport.java
[![GEOS-10061](https://badgen.net/badge/JIRA/GEOS-10061/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10061) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-10061 …
> [GEOS-10061] Geofence-Server-NPE is thrown when directly accessing layer contained  in a workspace group

- doc/en/user/source/security/tutorials/digest/index.rst
fix typos in documents:
```
curl --digest -v -u admin:geoserver -G "http://localhost:8080/geoserver/wfs?request=getcapabilities"
``` …
> fix: typos in documentation

- src/web/demo/src/main/java/org/geoserver/web/demo/SRSDescriptionPage.java
- src/web/demo/src/test/java/org/geoserver/web/demo/SRSDescriptionPageTest.java
[![GEOS-10055](https://badgen.net/badge/JIRA/GEOS-10055/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10055) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
2.19.x backport for https://github.com/geoserver/geoserver/pull/5037 …
> [2.19.x][GEOS-10055] Escape SRS demo page user input

- src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
[![GEOS-10062](https://badgen.net/badge/JIRA/GEOS-10062/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10062) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info) …
> [2.18.x backport][GEOS-10062] LayerCache CatalogLinester might not be attached to the catalog at startup

- src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
[![GEOS-10062](https://badgen.net/badge/JIRA/GEOS-10062/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10062) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info) …
> [2.19.x backport][GEOS-10062] LayerCache CatalogLinester might not be attached to the catalog at startup

- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceGetMapIntegrationTest.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
- src/wms/src/test/java/org/geoserver/wms/WMSTestSupport.java
[![GEOS-10061](https://badgen.net/badge/JIRA/GEOS-10061/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10061) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info) …
> [2.18.x backport][GEOS-10061] Geofence-Server-NPE is thrown when directly accessing layer contained  in a workspace group

- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceGetMapIntegrationTest.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
- src/wms/src/test/java/org/geoserver/wms/WMSTestSupport.java
[![GEOS-10061](https://badgen.net/badge/JIRA/GEOS-10061/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10061) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info) …
> [2.19.x backport][GEOS-10061] Geofence-Server-NPE is thrown when directly accessing layer contained  in a workspace group

- doc/en/user/source/extensions/wps-download/rawDownload.rst
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadProcess.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/LimitedImageOutputStream.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterDownload.java
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/VerticalResampleTest.java
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/RawDataEncoderDelegate.java
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/RawDataPPIO.java
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/resource/WPSResourceManager.java
- src/platform/src/main/java/org/geoserver/util/IOUtils.java
- src/pom.xml
[![GEOS-10064](https://badgen.net/badge/JIRA/GEOS-10064/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10064)
https://osgeo-org.atlassian.net/browse/GEOS-10064
> [GEOS-10064]: WPS-Download improvements

- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterDownload.java
[![GEOS-10064](https://badgen.net/badge/JIRA/GEOS-10064/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10064)
Fixing an estimator tests on WPS-Download
> [GEOS-10064]: Follow up on WPS-Download. Fixing Estimator tests

- doc/en/user/source/community/jms-cluster/installation.rst
It seems that the java variables in the sampels are the wrong one, it stated the GEOSERVER_DATA_DIR while it should have been the CLUSTER_CONFIG_DIR if I am right. In this PR, these lines in the documentation are updated.
> Docs update: error on JMS based clustering installation page

- doc/en/user/source/community/opensearch-eo/STAC.rst
- doc/en/user/source/community/opensearch-eo/configuration.rst
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/request/TemplatePathVisitor.java
- src/community/oseo/oseo-service/src/main/java/org/geoserver/opensearch/eo/OpenSearchTemplates.java
- src/community/oseo/oseo-service/src/main/java/org/geoserver/opensearch/eo/response/GeoJSONSearchResponse.java
- src/community/oseo/oseo-service/src/test/java/org/geoserver/opensearch/eo/GeoJSONSearchTest.java
- src/community/oseo/oseo-service/src/test/java/org/geoserver/opensearch/eo/OSEOTestSupport.java
- src/community/oseo/oseo-service/src/test/java/org/geoserver/opensearch/eo/SearchTest.java
- src/community/oseo/oseo-service/src/test/resources/org/geoserver/opensearch/eo/products-LANDSAT8.json
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/FilterMerger.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACPathVisitor.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACService.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACTemplates.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/TemplatePropertyMapper.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/TemplatedItemConverter.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/TemplatedItemsConverter.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/CollectionsTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/ItemsTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/QueryablesTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/STACTestSupport.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/SearchTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/TemplatePropertyMapperTest.java
- src/community/oseo/oseo-stac/src/test/resources/items-LANDSAT8.json
- src/main/src/main/java/org/geoserver/config/GeoServerDataDirectory.java
As per title. Leads to annoying levels of duplication though, will have to develop an import mechanism between templates (like in Freemaker). Just making a PR to check I'm not gonna break the build, 99.9% of the changes are in community modules.
The following are required only for core and extension modules (they are welcomed, but not required, for …
> Collection specific templates for products, both in OpenSearch and STAC

- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/processor/CatalogItemProcessor.java
- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/writer/CatalogItemWriter.java
[![GEOS-10065](https://badgen.net/badge/JIRA/GEOS-10065/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10065)
This PR adds logging to have hints of root cause during problems on Backup and restore processes.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-10065 …
> [GEOS-10065] Improve Backup and Restore logging to show exceptions

- src/main/src/main/java/org/geoserver/catalog/impl/ProxyUtils.java
- src/main/src/test/java/org/geoserver/catalog/impl/LocalWorkspaceCatalogTest.java
[![GEOS-10077](https://badgen.net/badge/JIRA/GEOS-10077/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10077)
See tickets for details, but it boils down to creating proxies around an object, and only exposing the direct interfaces, rather than including also the inherited ones.
The following are required only for core and extension modules (they …
> [GEOS-10077] OGC API maps/tiles won't work in a workspace specific service

- SECURITY.md
> fix a typo in Supported Versions of Security Policy

- src/community/release/ext-metadata.xml
[![GEOS-10078](https://badgen.net/badge/JIRA/GEOS-10078/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10078)
Resolves https://osgeo-org.atlassian.net/browse/GEOS-10078
- [N/A] New unit tests have been added covering the …
> [GEOS-10078] The Metadata extension breaks Geoserver

- doc/en/user/source/extensions/wps-download/rawDownload.rst
Added a minor comment on WPS-Download doc related to quality writing param
> [WPS-Download-doc]: Clarification on quality writing param on raw download

- src/ows/src/main/java/org/geoserver/ows/kvp/ElevationParser.java
- src/ows/src/test/java/org/geoserver/ows/kvp/ElevationKvpParserTest.java
[![GEOS-10051](https://badgen.net/badge/JIRA/GEOS-10051/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10051)
2.18.x backport for https://github.com/geoserver/geoserver/pull/5029
> [2.18.x][GEOS-10051] Fix edge cases in the elevation parser

- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/BackupRestoreItem.java
- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/processor/CatalogItemProcessor.java
- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/writer/CatalogItemWriter.java
[![GEOS-10065](https://badgen.net/badge/JIRA/GEOS-10065/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10065)
This PR adds logging to have hints of root cause during problems on Backup and restore processes.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-10065 …
> [2.19.x backport][GEOS-10065] Improve Backup and Restore logging to show exceptions

- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/BackupRestoreItem.java
- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/processor/CatalogItemProcessor.java
- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/writer/CatalogItemWriter.java
[![GEOS-10065](https://badgen.net/badge/JIRA/GEOS-10065/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10065)
This PR adds logging to have hints of root cause during problems on Backup and restore processes.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-10065 …
> [2.18.x backport][GEOS-10065] Improve Backup and Restore logging to show exceptions

- doc/en/user/source/extensions/gwc-s3/configuration.rst
- src/extension/gwc-s3/src/main/java/org/geoserver/gwc/web/blob/S3BlobStorePanel.java
- src/extension/gwc-s3/src/main/resources/GeoServerApplication.properties
- src/extension/gwc-s3/src/test/java/org/geoserver/gwc/web/blob/S3BlobStorePageTest.java
[![GEOS-9971](https://badgen.net/badge/JIRA/GEOS-9971/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9971)
Changed AWS Credential fields to not-required. This allows using underlaying AWS authentication chain (i.e AWS profile, instance role). 
The following are required only for core and extension modules (they are welcomed, but not required, for …
> [GEOS-9971] GeoWebCache S3 plugin require AWS creds

- doc/en/user/source/extensions/wps-download/mapAnimationDownload.rst
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/AnimationMetadata.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/AnimationMetadataPPIO.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadAnimationProcess.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadMapProcess.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/FrameWarning.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterDownload.java
- src/extension/wps-download/src/main/resources/applicationContext.xml
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/BaseDownloadImageProcessTest.java
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadAnimationProcessTest.java
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
- src/extension/wps-download/src/test/resources/org/geoserver/wps/gs/download/animateBlueMarbleMetadata.xml
- src/extension/wps-download/src/test/resources/org/geoserver/wps/gs/download/animateBlueMarbleMetadataWarnings.xml
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/XStreamPPIO.java
- src/main/src/main/java/applicationContext.xml
- src/main/src/main/java/org/geoserver/util/DimensionWarning.java
[![GEOS-10073](https://badgen.net/badge/JIRA/GEOS-10073/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10073)
See ticket.
> [GEOS-10073] Animation download process should report about eventual time mis-matches

- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccess.java
- src/community/oseo/oseo-core/src/test/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccessTest.java
[![GEOS-10105](https://badgen.net/badge/JIRA/GEOS-10105/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10105)
See tickets for details. All changes in community modules.
> [GEOS-10105] OSEO: handle same named columns in product and collection tables

- doc/en/user/source/extensions/netcdf/netcdf.rst
- src/extension/netcdf/src/main/java/org/geoserver/netcdf/NetCDFUnitsConfigurator.java
[![GEOT-6902](https://badgen.net/badge/JIRA/GEOT-6902/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6902)
Follow up on GEOT-6902:
Documentation update and clear cache
> [GEOT-6902]: Follow up on NetCDF performances improvement - caching

- src/community/jms-cluster/jms-commons/pom.xml
- src/community/notification-common/pom.xml
- src/community/pom.xml
[![GEOS-10106](https://badgen.net/badge/JIRA/GEOS-10106/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10106)
Remove forced dependencies on `gs-platform`/`gt-cql` for all community modules.
The root community modules pom (`src/community/pom.xml`) sets a
direct dependency on `gs-platform` and `gt-cql` to all community modules.
This carries over a lot of transitive dependencies (including spring,
geotools, jai, emf, etc).
Some may not need to depend on those, and yet are forced to carry them over as transitive deps.
Note this patch has been checked to work when building with the `communityRelease` profile. Not sure how/if to check the modules that are not part of it.
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small …
> [GEOS-10106] Remove direct dependency on gs-platform and gt-cql from all community modules

- src/extension/importer/core/src/test/java/org/geoserver/importer/mosaic/ImporterMosaicTest.java
- [x The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
> Fixing the importer test reconfiguring the same layer on same NetCDF data. clearing the cache

- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/AbstractMappingStore.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccess.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCProductFeatureStore.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/OpenSearchAccess.java
- src/community/oseo/oseo-core/src/test/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccessTest.java
- src/community/oseo/oseo-rest/src/main/java/org/geoserver/opensearch/rest/AbstractOpenSearchController.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACService.java
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/stac/item_include.ftl
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/stac/items.json
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/STACTestSupport.java
- src/community/oseo/oseo-stac/src/test/resources/items-test.json
[![GEOS-10112](https://badgen.net/badge/JIRA/GEOS-10112/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10112)
See ticket for description. Needs to be merged after https://github.com/geotools/geotools/pull/3548
> [GEOS-10112] STAC: allow access to collection properties from item templates

- src/extension/gwc-s3/src/test/java/org/geoserver/gwc/web/blob/S3BlobStoresPageTest.java
- src/pom.xml
- src/web/core/src/main/java/org/geoserver/web/GeoServerApplication.java
- src/web/core/src/main/java/org/geoserver/web/GeoServerBasePage.java
- src/web/core/src/main/java/org/geoserver/web/wicket/GeoServerTablePanel.java
- src/web/core/src/test/java/org/geoserver/web/GeoServerWicketOnlineTestSupport.java
- src/web/core/src/test/java/org/geoserver/web/GeoServerWicketTestSupport.java
- src/web/core/src/test/java/org/geoserver/web/data/layer/LayerPageTest.java
- src/web/gwc/src/main/java/org/geoserver/gwc/web/blob/BlobStorePage.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/blob/BlobStorePageTest.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/blob/BlobStoresPageTest.java
[![GEOS-10098](https://badgen.net/badge/JIRA/GEOS-10098/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10098) …
> [GEOS-10098] Upgrade version of wicket and JQuery

- src/extension/wmts-multi-dimensional/pom.xml
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/MultiDimensionalExtension.java
- src/extension/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/MultiDimensionalExtensionTest.java
[![GEOS-10037](https://badgen.net/badge/JIRA/GEOS-10037/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10037)
Backporting fix for GEOS-10037 on 2.19.x
> [Backport-2.19.x][GEOS-10037]: WMTS-Multi-dimensional extension failing on layers encoding

- doc/en/user/source/extensions/wps-download/rawDownload.rst
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadProcess.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/LimitedImageOutputStream.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterDownload.java
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/VerticalResampleTest.java
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/RawDataEncoderDelegate.java
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/RawDataPPIO.java
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/resource/WPSResourceManager.java
- src/platform/src/main/java/org/geoserver/util/IOUtils.java
- src/pom.xml
[![GEOS-10064](https://badgen.net/badge/JIRA/GEOS-10064/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10064)
* [GEOS-10064]: WPS-Download improvements backport to 2.19.x
Depends on https://github.com/geotools/geotools/pull/3550
> [Backport-2.19.x][GEOS-10064]: WPS-Download improvements (#5061)

- src/extension/gwc-s3/src/test/java/org/geoserver/gwc/web/blob/S3BlobStoresPageTest.java
- src/pom.xml
- src/web/core/src/main/java/org/geoserver/web/GeoServerApplication.java
- src/web/core/src/main/java/org/geoserver/web/GeoServerBasePage.java
- src/web/core/src/main/java/org/geoserver/web/wicket/GeoServerTablePanel.java
- src/web/core/src/test/java/org/geoserver/web/GeoServerWicketOnlineTestSupport.java
- src/web/core/src/test/java/org/geoserver/web/GeoServerWicketTestSupport.java
- src/web/core/src/test/java/org/geoserver/web/data/layer/LayerPageTest.java
- src/web/gwc/src/main/java/org/geoserver/gwc/web/blob/BlobStorePage.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/blob/BlobStorePageTest.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/blob/BlobStoresPageTest.java
[![GEOS-10098](https://badgen.net/badge/JIRA/GEOS-10098/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10098) …
> [GEOS-10098] Wicket and JQuery Upgrade backport to 2.19.x

- src/pom.xml
- src/web/core/src/main/java/org/geoserver/web/GeoServerApplication.java
- src/web/core/src/main/java/org/geoserver/web/GeoServerBasePage.java
- src/web/core/src/main/java/org/geoserver/web/wicket/GeoServerTablePanel.java
- src/web/core/src/test/java/org/geoserver/web/GeoServerWicketOnlineTestSupport.java
- src/web/core/src/test/java/org/geoserver/web/GeoServerWicketTestSupport.java
- src/web/core/src/test/java/org/geoserver/web/data/layer/LayerPageTest.java
- src/web/gwc/src/main/java/org/geoserver/gwc/web/blob/BlobStorePage.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/blob/BlobStorePageTest.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/blob/BlobStoresPageTest.java
[![GEOS-10098](https://badgen.net/badge/JIRA/GEOS-10098/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10098) …
> [GEOS-10098] Wicket and JQuery Upgrade backport to 2.18.x

- doc/en/user/source/community/features-templating/configuration.rst
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/flat/FlatIteratingBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/DynamicValueBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/IteratingBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/expressions/ItemFunction.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/expressions/TemplateCQLManager.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/CommonJSONWriter.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/GeoJSONWriter.java
- src/community/features-templating/features-templating-core/src/main/resources/META-INF/services/org.opengis.filter.expression.Function
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/writers/JsonWriterTest.java
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/writers/arrayTemplate.json
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/OpenSearchQueries.java
- src/community/oseo/oseo-core/src/test/resources/collection_test_data.sql
- src/community/oseo/oseo-core/src/test/resources/postgis.sql
- src/community/oseo/oseo-rest/src/test/java/org/geoserver/opensearch/rest/CollectionsControllerTest.java
- src/community/oseo/oseo-rest/src/test/resources/collection.json
- src/community/oseo/oseo-service/src/main/java/org/geoserver/opensearch/eo/DefaultOpenSearchEoService.java
- src/community/oseo/oseo-service/src/main/resources/org/geoserver/opensearch/eo/collections.json
- src/community/oseo/oseo-service/src/main/resources/org/geoserver/opensearch/eo/products.json
- src/community/oseo/oseo-service/src/test/java/org/geoserver/opensearch/eo/GeoJSONSearchTest.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACService.java
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/stac/items.json
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/STACTestSupport.java
- src/community/oseo/oseo-stac/src/test/resources/items-LANDSAT8.json
All community module changes, checking build is not broken.
> Add ability to use array columns in features-templating, use it in STAC/OpenSearch

- src/community/metadata/src/main/java/org/geoserver/metadata/data/model/impl/ComplexMetadataAttributeImpl.java
[![GEOS-10130](https://badgen.net/badge/JIRA/GEOS-10130/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10130)
Update import to use `java.util.Arrays`. Just looks like wrong pick from the IDE.
- [N/A] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.
> [GEOS-10130] Correct import of wrong Arrays class in community metadata module

- doc/en/user/source/filter/function_reference.rst
Updating the FilterFunction documentation section with recently modified temporal functions (now and dateDifference)
> Updating FilterFunction documentation with temporal functions

- doc/en/user/source/extensions/geofence-server/gui.rst
- doc/en/user/source/filter/function_reference.rst
Updating GeoFence documentation with examples on how to limit access to a specific layer by setting up a CQL Filter to only access a specific time range.
> Updating GeoFence documentation with example on CQL read filter limits on time range

- src/main/src/main/java/org/geoserver/filters/SessionDebugFilter.java
- src/main/src/test/java/org/geoserver/filters/SessionDebugFilterTest.java
[![GEOS-10136](https://badgen.net/badge/JIRA/GEOS-10136/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10136)
> [GEOS-10136] Create Session might throw NPE if pathInfo is Null

- doc/en/user/source/community/features-templating/configuration.rst
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/RecursiveJSONParser.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/RecursiveTemplateResourceParser.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/readers/JSONIncludesTest.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/readers/JSONMergesTest.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/readers/XmlTemplateReaderTest.java
- src/community/features-templating/features-templating-core/src/test/resources/jsonMerge/dangling.json
- src/community/features-templating/features-templating-core/src/test/resources/jsonMerge/eoBase.json
- src/community/features-templating/features-templating-core/src/test/resources/jsonMerge/eoOverride.json
- src/community/features-templating/features-templating-core/src/test/resources/jsonMerge/ping.json
- src/community/features-templating/features-templating-core/src/test/resources/jsonMerge/pong.json
- src/community/features-templating/features-templating-core/src/test/resources/jsonMerge/recurse.json
- src/community/features-templating/features-templating-core/src/test/resources/jsonMerge/simpleBase.json
- src/community/features-templating/features-templating-core/src/test/resources/jsonMerge/simpleOverride.json
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/ItemsTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/QueryablesTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/SearchTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/TemplatePropertyMapperTest.java
- src/community/oseo/oseo-stac/src/test/resources/items-LANDSAT8.json
- src/community/oseo/oseo-stac/src/test/resources/mandatoryLinks.json
[![GEOS-10138](https://badgen.net/badge/JIRA/GEOS-10138/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10138)
See ticket. Basically allows a different extension mechanism, which unlike include allows to start from a base and override some of its contents. The first commit changes features templating, the second uses the machinery to simplify some test resources in the STAC service. …
> [GEOS-10138] Allow for template extension via a inheritance/extension/merge mechanism

- src/main/src/main/java/org/geoserver/catalog/impl/LayerGroupInfoImpl.java
- src/main/src/main/java/org/geoserver/catalog/impl/ResourceInfoImpl.java
- src/main/src/main/java/org/geoserver/config/impl/ServiceInfoImpl.java
- src/main/src/test/java/org/geoserver/catalog/impl/FeatureTypeInfoImplTest.java
- src/main/src/test/java/org/geoserver/catalog/impl/LayerGroupInfoImplTest.java
- src/wms/src/main/java/org/geoserver/wms/WMSInfoImpl.java
- src/wms/src/test/java/org/geoserver/wms/WMSInfoImplTest.java
[![GEOS-10139](https://badgen.net/badge/JIRA/GEOS-10139/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10139)
> [GEOS-10139] i18n setters throw NPE on null method parameter

- doc/en/user/source/community/geopkg/output.rst
[![GEOS-10140](https://badgen.net/badge/JIRA/GEOS-10140/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10140)
See jira ticket.
> [GEOS-10140] Update GeoPackage download process documentation

- src/extension/inspire/src/main/java/org/geoserver/inspire/LanguagesDispatcherCallback.java
- src/extension/inspire/src/test/java/org/geoserver/inspire/LanguageDispatcherCallbackTest.java
[![GEOS-10141](https://badgen.net/badge/JIRA/GEOS-10141/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10141)
> [GEOS-10141] Inspire extension better error message on language not found

- doc/en/user/source/filter/function_reference.rst
backporting temporal filter function doc updates
> Updating FilterFunction document with temporal functions

- doc/en/user/source/community/opensearch-eo/STAC.rst
- doc/en/user/source/community/opensearch-eo/configuration.rst
- src/community/oseo/oseo-service/src/main/java/org/geoserver/opensearch/eo/OpenSearchTemplates.java
- src/community/oseo/oseo-service/src/main/java/org/geoserver/opensearch/eo/response/GeoJSONSearchResponse.java
- src/community/oseo/oseo-service/src/test/java/org/geoserver/opensearch/eo/GeoJSONSearchTest.java
- src/community/oseo/oseo-service/src/test/java/org/geoserver/opensearch/eo/SearchTest.java
- src/community/oseo/oseo-service/src/test/resources/org/geoserver/opensearch/eo/collections-LANDSAT8.json
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACTemplates.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/TemplatedCollectionConverter.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/TemplatedCollectionsConverter.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/CollectionsTest.java
- src/community/oseo/oseo-stac/src/test/resources/collections-LANDSAT8.json
- src/community/oseo/oseo-stac/src/test/resources/collections-SENTINEL1.json
- src/community/oseo/oseo-stac/src/test/resources/collections-SENTINEL2.json
[![GEOS-10147](https://badgen.net/badge/JIRA/GEOS-10147/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10147)
Community module changes check.
> [GEOS-10147] STAC: allow JSON templates specific per collection (for collections too)

- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACService.java
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/stac/collections.json
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/stac/items.json
- src/community/oseo/oseo-stac/src/test/resources/collections-LANDSAT8.json
- src/community/oseo/oseo-stac/src/test/resources/collections-SENTINEL1.json
- src/community/oseo/oseo-stac/src/test/resources/collections-SENTINEL2.json
- src/community/oseo/oseo-stac/src/test/resources/items-LANDSAT8.json
- src/community/oseo/oseo-stac/src/test/resources/items-SAS1.json
- src/community/oseo/oseo-stac/src/test/resources/items-test.json
[![GEOS-10151](https://badgen.net/badge/JIRA/GEOS-10151/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10151)
Change in the oseo/stac community module, checking it builds fine. 
> [GEOS-10151] Update STAC implementation to v 1.0.0

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/catalog/JDBCCatalogFacade.java
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
- src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/config/JDBCGeoServerImplTest.java
[![GEOS-9797](https://badgen.net/badge/JIRA/GEOS-9797/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9797)
> GEOS-9797 jdbc-config: removing workspace with service breaks geoserver

- src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/GMLTransformer.java
- src/web/core/src/main/java/org/geoserver/web/data/resource/CoverageBandsConfigurationPanel.java
[![GEOT-6709](https://badgen.net/badge/JIRA/GEOT-6709/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6709) …
> [GEOT-6709] Adjust GeoServer to changes in GeoTools

- src/community/pom.xml
Very simple cleanup for community pom.xml, removing profile that is no longer useful.
> mbstyle is no longer a community module

- doc/en/user/source/community/features-templating/configuration.rst
- doc/en/user/source/community/features-templating/directives.rst
[![GEOS-10153](https://badgen.net/badge/JIRA/GEOS-10153/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10153)
Applies feedback on features-templating documentation made on this pr https://github.com/geoserver/geoserver/pull/5157
The following are required only for core and extension modules (they are welcomed, but not required, for community …
> [GEOS-10153] review feedback on features-templating documentation

- doc/en/developer/source/quickstart/checkout.txt
> update devloper doc from 'master' to 'main'

- src/community/ogcapi/ogcapi-coverages/pom.xml
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CollectionDocument.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CollectionsDocument.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CoverageResponseMessageConverter.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CoveragesLandingPage.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CoveragesResponse.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CoveragesService.java
- src/community/ogcapi/ogcapi-coverages/src/main/resources/applicationContext.xml
- src/community/ogcapi/ogcapi-coverages/src/main/resources/org/geoserver/ogcapi/coverages/collection.ftl
- src/community/ogcapi/ogcapi-coverages/src/main/resources/org/geoserver/ogcapi/coverages/collection_include.ftl
- src/community/ogcapi/ogcapi-coverages/src/main/resources/org/geoserver/ogcapi/coverages/collections.ftl
- src/community/ogcapi/ogcapi-coverages/src/main/resources/org/geoserver/ogcapi/coverages/landingPage.ftl
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/CollectionsTest.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/CoveragesTestSupport.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/LandingPageTest.java
- src/community/ogcapi/pom.xml
- src/wcs2_0/pom.xml
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCS20GetCoverageResponse.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/response/WCS20GetCoverageResponseTest.java
- src/web/app/pom.xml
> OGC API coverages: landing page and collections listing

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/ConformanceClass.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CoveragesService.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/CollectionTest.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/CollectionsTest.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/ConformanceTest.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/CoveragesTestSupport.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/LandingPageTest.java
> OGC API coverages: single coverage description and conformance classes

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/MessageConverterResponseAdapter.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/TimeExtentCalculator.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CollectionsDocument.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CoverageResponseMessageConverter.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CoveragesService.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/CoverageTest.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/LandingPageTest.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/FeatureResponseMessageConverter.java
- src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/ogcapi/images/ImageResponseMessageConverter.java
- src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/maps/MapResponseMessageConverter.java
- src/wcs/src/main/java/org/geoserver/wcs/responses/GeoTIFFCoverageResponseDelegate.java
- src/wcs/src/main/java/org/geoserver/wcs/responses/IMGCoverageResponseDelegate.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/util/EnvelopeAxesLabelsMapper.java
Another baby step.. basic raster extraction.
> OGC API Coverages - basic GetCoverage support

- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CoveragesAPIBuilder.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CoveragesService.java
- src/community/ogcapi/ogcapi-coverages/src/main/resources/org/geoserver/ogcapi/coverages/openapi.yaml
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/ApiTest.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/LandingPageTest.java
[![GEOS-10157](https://badgen.net/badge/JIRA/GEOS-10157/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10157)
One more step, adding a basic OpenAPI description to the service.
> [GEOS-10157] Basic OpenAPI document for OGC API - Coverages

- src/wms/src/main/java/org/geoserver/wms/describelayer/DescribeLayerKvpRequestReader.java
fix a typo + grammar in the error messages
> fix a typo + grammar in the error messages

- doc/en/user/source/community/oauth2/index.rst
> Update to add details of where to find the files

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/DefaultAPIExceptionHandler.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CollectionDocument.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CoveragesService.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/SubsetsParser.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/WCS20ExceptionHandler.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/cis/Axis.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/cis/DomainSet.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/cis/GeneralGrid.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/cis/GridLimits.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/cis/IndexAxis.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/cis/RegularAxis.java
- src/community/ogcapi/ogcapi-coverages/src/main/resources/org/geoserver/ogcapi/coverages/collection.ftl
- src/community/ogcapi/ogcapi-coverages/src/main/resources/org/geoserver/ogcapi/coverages/openapi.yaml
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/ConformanceTest.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/CoverageTest.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/DomainSetTest.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/LandingPageTest.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/kvp/SubsetKvpParser.java
[![GEOS-10157](https://badgen.net/badge/JIRA/GEOS-10157/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10157)
One last step, and with this, the sprint time ends.
> [GEOS-10157] Add a basic OGC API Coverages implementation. Subset support, along with domainset description

- .github/PULL_REQUEST_TEMPLATE.md
Making the PR template shorter and easier to understand.
> Simplify the PR template, make it more approachable

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
[![GEOS-9929](https://badgen.net/badge/JIRA/GEOS-9929/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9929)
The recent repopulate function in jdbcconfig appears buggy: with types inherited from abstract types, it uses the ID's of the abstract properties instead of the correct properties.
repopulate is an experimental feature in community module and is currently not covered by tests. (It is really only useful in specific circumstances of very complex environments - see docs. )
**Submitting the PR does not require …
> [GEOS-9929] jdbc-config: repopulate populates wrong properties

- doc/en/user/source/community/features-templating/configuration.rst
- doc/en/user/source/community/features-templating/directives.rst
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/AbstractTemplateBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/flat/AttributeNameHelper.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/flat/FlatCompositeBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/flat/FlatDynamicBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/flat/FlatIteratingBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/flat/FlatStaticBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/CompositeBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/DynamicValueBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/IteratingBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/StaticBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/configuration/TemplateLoader.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/configuration/TemplateReloader.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/request/TemplatePathVisitor.java
- src/community/features-templating/features-templating-core/src/main/resources/applicationContext.xml
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/readers/JsonTemplateReaderTest.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/readers/XmlTemplateReaderTest.java
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/NamedPlacesDynKeyGeoJSON.json
- src/community/features-templating/features-templating-wfs/src/main/java/org/geoserver/featurestemplating/wfs/TemplateCallback.java
- src/community/features-templating/features-templating-wfs/src/test/java/org/geoserver/featurestemplating/response/GeoJSONGetSimpleFeaturesResponseWFSTest.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACQueryablesBuilder.java
[![GEOS-10152](https://badgen.net/badge/JIRA/GEOS-10152/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10152)
Set of community module changes. @taba90 could you review?
> [GEOS-10152] Features templating: allow also keys to depend on feature attributes

- src/community/security/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilter.java
- src/community/security/oauth2-core/src/test/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilterTest.java
[![GEOS-10162](https://badgen.net/badge/JIRA/GEOS-10162/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10162) …
> [GEOS-10162] GeoServerOAuthAuthenticationFilter creates Anonymous authentication when preAuthenticated principal is not present

- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/OSEOInfo.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/OSEOInfoImpl.java
- src/community/oseo/oseo-service/src/main/java/org/geoserver/opensearch/eo/response/DescriptionTransformer.java
- src/community/oseo/oseo-service/src/test/java/org/geoserver/opensearch/eo/DescriptionTest.java
- src/community/oseo/oseo-service/src/test/java/org/geoserver/opensearch/eo/OSEOTestSupport.java
- src/community/oseo/web-oseo/src/main/java/org/geoserver/opensearch/eo/web/OSEOAdminPage.html
- src/community/oseo/web-oseo/src/main/java/org/geoserver/opensearch/eo/web/OSEOAdminPage.java
- src/community/oseo/web-oseo/src/main/resources/GeoServerApplication.properties
- src/community/oseo/web-oseo/src/test/java/org/geoserver/opensearch/eo/web/OSEOAdminPageTest.java
[![GEOS-10168](https://badgen.net/badge/JIRA/GEOS-10168/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10168)
See attacked ticket. Community module change, checking everything is building fine?
> [GEOS-10168] Add attribution to OpenSearch for EO OSDD document

- src/community/security/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilter.java
- src/community/security/oauth2-core/src/test/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilterTest.java
[![GEOS-10162](https://badgen.net/badge/JIRA/GEOS-10162/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10162)
[GEOS-10162] GeoServerOAuthAuthenticationFilter creates Anonymous authentication when preAuthenticated principal is not present
> [2.19.x backport] [GEOS-10162] GeoServerOAuthAuthenticationFilter creates Anonymous authentication when preAuthenticated principal is not present

- src/community/security/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilter.java
- src/community/security/oauth2-core/src/test/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilterTest.java
[![GEOS-10162](https://badgen.net/badge/JIRA/GEOS-10162/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10162)
[GEOS-10162] GeoServerOAuthAuthenticationFilter creates Anonymous authentication when preAuthenticated principal is not present
> [2.18.x backport] [GEOS-10162] GeoServerOAuthAuthenticationFilter creates Anonymous authentication when preAuthenticated principal is not present

- src/web/core/src/main/java/org/geoserver/web/data/resource/LocalesDropdown.java
[![GEOS-10123](https://badgen.net/badge/JIRA/GEOS-10123/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10123)
Small update for LocalesDropdown to render both the language tag and the
localized display name for each locale. Makes it easier to search for a
specific language, since you often don't know the language code.
| Before      | After |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/207423/126084991-af6a6bc5-eb0b-467e-9b97-574a20ff2c8a.png)  | ![image](https://user-images.githubusercontent.com/207423/126084947-3b0e8e44-a94b-4b9f-8f47-02d5c1efc553.png) |
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the …
> [GEOS-10123] Use localized display name in locales dropdown

- src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NormalizedMultiValuesTest.java
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/stations.properties
- src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/multiValues/stations.xml
[![GEOS-10144](https://badgen.net/badge/JIRA/GEOS-10144/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10144)
> [GEOS-10144] add missing modification on tests

- src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/domain/DomainModelBuilder.java
- src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/domain/entities/DomainAttributeType.java
- src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/visitors/gml/GmlSchemaUtils.java
- src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/domain/DomainModelBuilderTest.java
- src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/metadata/jdbc/JDBCDataStoreMetadataTest.java
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/domain/meteo-observations-logvisitor.txt
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/domain/meteo-stations-logvisitor.txt
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/postgis/mockdata/meteo_db.sql
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/visitors/meteo-maintainers-appschema.xml
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/visitors/meteo-maintainers-gml.xsd
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/visitors/meteo-observations-appschema.xml
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/visitors/meteo-observations-gml.xsd
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/visitors/meteo-parameters-appschema.xml
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/visitors/meteo-parameters-gml.xsd
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/visitors/meteo-stations-appschema.xml
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/visitors/meteo-stations-gml.xsd
[![GEOS-10161](https://badgen.net/badge/JIRA/GEOS-10161/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10161)
This pr add missing type mappings between postgis and xsd in smart data loader community module.
> [GEOS-10161] Smart data loader missing PostgreSQL type in DomainModelBuilder

- src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/domain/DomainModelBuilder.java
- src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/domain/entities/DomainAttributeType.java
- src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/visitors/gml/GmlSchemaUtils.java
- src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/domain/DomainModelBuilderTest.java
- src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/metadata/jdbc/JDBCDataStoreMetadataTest.java
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/domain/meteo-observations-logvisitor.txt
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/domain/meteo-stations-logvisitor.txt
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/postgis/mockdata/meteo_db.sql
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/visitors/meteo-maintainers-appschema.xml
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/visitors/meteo-maintainers-gml.xsd
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/visitors/meteo-observations-appschema.xml
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/visitors/meteo-observations-gml.xsd
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/visitors/meteo-parameters-appschema.xml
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/visitors/meteo-parameters-gml.xsd
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/visitors/meteo-stations-appschema.xml
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/visitors/meteo-stations-gml.xsd
[![GEOS-10161](https://badgen.net/badge/JIRA/GEOS-10161/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10161)
* [GEOS-10161] Smart data loader missing PostgreSQL type in DomainModelBuilder
> [2.19.x backport][GEOS-10161] Smart data loader missing PostgreSQL type in DomainModelBuilder (#5180)

- src/community/features-templating/features-templating-ogcapi/src/test/java/org/geoserver/featurestemplating/response/HTMLSimpleFeaturesResponseAPITest.java
- src/community/features-templating/features-templating-wfs/src/main/java/org/geoserver/featurestemplating/wfs/HTMLTemplateResponse.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/MessageConverterResponseAdapter.java
[![GEOS-10181](https://badgen.net/badge/JIRA/GEOS-10181/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10181)
* [GEOS-10181] Features-templatings avoid replacing OGCAPI HTML response if template do not exists
> [2.19.x backport][GEOS-10181] Features-templatings avoid replacing OGCAPI HTML response if template do not exists (#5191)

- src/community/features-templating/features-templating-web/src/main/java/org/geoserver/featurestemplating/web/TemplateInfoPage.java
- src/community/features-templating/features-templating-web/src/test/java/org/geoserver/featurestemplating/web/TemplateInfoPageTest.java
[![GEOS-10188](https://badgen.net/badge/JIRA/GEOS-10188/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10188)
> [GEOS-10188] Features templating when deleting a templateInfo all the template contents will be deleted

- doc/en/user/source/extensions/wps-download/rawDownload.rst
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/CoverageRenderSupport.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/GeopkgPPIO.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/GeopkgRasterPPIO.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/GeopkgVectorPPIO.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/MetaGridCoverage2D.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterDownload.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/VectorDownload.java
- src/extension/wps-download/src/main/resources/applicationContext.xml
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
- src/wms/src/main/java/org/geoserver/wms/map/png/PNGJWriter.java
[![GEOS-10172](https://badgen.net/badge/JIRA/GEOS-10172/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10172)
Backport from main, depends on https://github.com/geotools/geotools/pull/3596
> [GEOS-10172] Add support for GeoPackage output in WPS download (2.19.x)

- src/extension/inspire/src/main/java/org/geoserver/inspire/ServicesUtils.java
- src/extension/inspire/src/test/java/org/geoserver/inspire/wms/WMSExtendedCapabilitiesTest.java
[![GEOS-10192](https://badgen.net/badge/JIRA/GEOS-10192/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10192)
> [GEOS-10192] Inspire extension consistent outputResponse element

- src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
- src/extension/importer/core/src/test/java/org/geoserver/importer/ImporterDataTest.java
[![GEOS-10193](https://badgen.net/badge/JIRA/GEOS-10193/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10193)
See ticket
> [GEOS-10193] Indirect imports will drop the target table if there is any failure during the import process

- doc/en/user/source/extensions/inspire/using.rst
- src/extension/inspire/src/main/java/org/geoserver/inspire/InspireSchema.java
[![GEOS-10163](https://badgen.net/badge/JIRA/GEOS-10163/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10163)
Ticket [GEOS-10002](https://osgeo-org.atlassian.net/browse/GEOS-10002) incorrectly changed the inspire namespace URIs to https://. Due this change, inspire validators fail. 
This pull request reverts the namespace url  to the currect URI.
See also https://osgeo-org.atlassian.net/browse/GEOS-10163
> GEOS-10163 Incorrect INSPIRE namespace URI

- src/community/release/ext-elasticsearch.xml
[![GEOS-10195](https://badgen.net/badge/JIRA/GEOS-10195/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10195)
As easy as adding the missing dependency. This is a community module.
> [GEOS-10195] ElasticSearch packaging misses gt-geojsonstore, causes spatial filters encoding to break

- doc/en/user/source/extensions/inspire/using.rst
- src/extension/inspire/src/main/java/org/geoserver/inspire/InspireSchema.java
[![GEOS-10163](https://badgen.net/badge/JIRA/GEOS-10163/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10163)
This is a backport of #5201 for branch 2.19.x
> GEOS-10163 Incorrect INSPIRE namespace URI (backport to 2.19.x of #5201)

- doc/en/user/source/extensions/inspire/using.rst
- src/extension/inspire/src/main/java/org/geoserver/inspire/InspireSchema.java
[![GEOS-10163](https://badgen.net/badge/JIRA/GEOS-10163/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10163)
This is a backport of #5201 for branch 2.18.x
> GEOS-10163 Incorrect INSPIRE namespace URI (backport to 2.18.x of #5201)

- src/extension/importer/core/src/main/java/org/geoserver/importer/Database.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/FileData.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/ImportContext.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/ImportTask.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/MemoryImportStore.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/Table.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AbstractTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AttributeComputeTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AttributeRemapTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AttributesToPointGeometryTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/CreateIndexTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/DateFormatTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/GdalAddoTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/GdalTranslateTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/GdalWarpTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/KMLPlacemarkTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/PostScriptTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/ReprojectTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/TransformChain.java
[![GEOS-10194](https://badgen.net/badge/JIRA/GEOS-10194/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10194)
> [GEOS-10194] Improve importer LOGGING

- src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
- src/extension/importer/core/src/test/java/org/geoserver/importer/ImporterDataTest.java
[![GEOS-10193](https://badgen.net/badge/JIRA/GEOS-10193/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10193)
> [GEOS-10193] Indirect imports will drop the target table if there is any failure during the import process (2.18.x)

- src/extension/importer/core/src/main/java/org/geoserver/importer/Database.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/FileData.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/ImportContext.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/ImportTask.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/MemoryImportStore.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/Table.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AbstractTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AttributeComputeTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AttributeRemapTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AttributesToPointGeometryTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/CreateIndexTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/DateFormatTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/GdalAddoTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/GdalTranslateTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/GdalWarpTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/KMLPlacemarkTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/PostScriptTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/ReprojectTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/TransformChain.java
[![GEOS-10194](https://badgen.net/badge/JIRA/GEOS-10194/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10194)
> [GEOS-10194] Improve importer LOGGING  (2.18.x)

- src/extension/importer/core/src/main/java/org/geoserver/importer/Database.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/FileData.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/ImportContext.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/ImportTask.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/MemoryImportStore.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/Table.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AbstractTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AttributeComputeTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AttributeRemapTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AttributesToPointGeometryTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/CreateIndexTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/DateFormatTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/GdalAddoTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/GdalTranslateTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/GdalWarpTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/KMLPlacemarkTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/PostScriptTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/ReprojectTransform.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/TransformChain.java
[![GEOS-10194](https://badgen.net/badge/JIRA/GEOS-10194/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10194)
> [GEOS-10194] Improve importer LOGGING (2.19.x)

- src/main/src/main/java/org/geoserver/data/InternationalContentHelper.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/xml/GetCapabilitiesTest.java
[![GEOS-10204](https://badgen.net/badge/JIRA/GEOS-10204/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10204)
See jira for description.
> [GEOS-10204] Default locale is not being used while producing internationalized outputs in Capabilities document

- src/main/src/main/java/org/geoserver/catalog/impl/ResourceInfoImpl.java
- src/main/src/main/java/org/geoserver/config/impl/ServiceInfoImpl.java
- src/main/src/test/java/org/geoserver/catalog/impl/FeatureTypeInfoImplTest.java
- src/main/src/test/java/org/geoserver/config/impl/ServiceInfoImplTest.java
- src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesReponseTest.java
[![GEOS-10205](https://badgen.net/badge/JIRA/GEOS-10205/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10205)
See Jira for details
> [GEOS-10205] Layer with i18n title might appear twice in the capabiliies, while being contained in a named tree

- doc/en/user/source/styling/sld/language.rst
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/DisabledRulesRemover.java
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendGraphicBuilder.java
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/JSONLegendGraphicOutputFormatTest.java
- src/wms/src/test/resources/org/geoserver/wms/legendgraphic/multiLanguageRaster.sld
- src/wms/src/test/resources/org/geoserver/wms/legendgraphic/multiLanguageVector.sld
[![GEOS-10207](https://badgen.net/badge/JIRA/GEOS-10207/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10207)
See tickets for deails. Comes with documentation updates with examples.
> [GEOS-10207] Allow creation of internationalized raster legends

- doc/en/user/source/community/dds/index.rst
[![GEOS-10208](https://badgen.net/badge/JIRA/GEOS-10208/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10208)
Update link to community plugins for the DDS/BIL plugin
> [GEOS-10208] Fix link to community plugins in the DDS/BIL plugin doc for stable

- build/qa/dependency-check-suppression.xml
- src/community/oseo/web-oseo/pom.xml
- src/pom.xml
And update the config to suppress false positives in some of the community modules.
While here also remove a duplicate dependency declaration in `src/community/oseo/wb-oseo/pom.xml` that maven complains about.
> Bump org.owasp:dependency-check-maven to 6.2.2

- src/pom.xml
[![GEOS-10201](https://badgen.net/badge/JIRA/GEOS-10201/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10201)
Bump OSHI from 5.5.1 to 5.8.1 and also bump the transitive dependency JNA to 5.9.0, which should make it possible to run on Windows 11
I don't have access to Windows 11 (beta) so cannot test if this actually fixes the problem. (Windows 11 won't be availaible for a couple of months)
see also https://github.com/oshi/oshi/issues/1699
> [GEOS-10201] Geoserver fails to start on Windows 11 beta

- src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/LayerControllerTest.java
[![GEOS-9937](https://badgen.net/badge/JIRA/GEOS-9937/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-9937)
This is backport of [5244](https://github.com/geoserver/geoserver/pull/5244) for branch 2.19.x
> [2.19.x backport][GEOS-9937] Name of styles with colons are incorrect in REST API

- src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/CapabilityUtil.java
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReader.java
- src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReaderTest.java
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/JSONLegendGraphicOutputFormatTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetMapIntegrationTest.java
[![GEOS-10213](https://badgen.net/badge/JIRA/GEOS-10213/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10213)
See details in ticket
> [GEOS-10213] WMS requests fail on LayerGroup default style names, when used

- src/pom.xml
[![GEOS-10216](https://badgen.net/badge/JIRA/GEOS-10216/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10216)
Signed-off-by: Jim Hughes <jhughes@ccri.com>
> [GEOS-10216] Upgrade to JTS Topology Suite 1.18.2

- doc/en/README.md
- doc/en/index.html
[![GEOS-10221](https://badgen.net/badge/JIRA/GEOS-10221/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10221)
Refer to https://osgeo-org.atlassian.net/browse/GEOS-10221
Thanks to @rcoup for [providing](https://gist.github.com/rcoup/1e06bd54db2073450933787ad47dcb4c) the updated index.html with fixed links.
> [GEOS-10221] Add online documentation root to version control

- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/RecursiveJSONParser.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/TemplateReaderConfiguration.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/TemplateReaderProvider.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACTemplates.java
- src/community/oseo/oseo-stac/src/test/resources/collections-LANDSAT8.json
- src/community/oseo/oseo-stac/src/test/resources/collections-SENTINEL1.json
- src/community/oseo/oseo-stac/src/test/resources/collections-SENTINEL2.json
- src/community/oseo/oseo-stac/src/test/resources/collections.json
[![GEOS-10224](https://badgen.net/badge/JIRA/GEOS-10224/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10224)
> [GEOS-10224] Feature templating merge directive does not work on STAC collections template

- src/web/gwc/src/main/java/org/geoserver/gwc/web/DefaultGridsetsEditor.java
- src/web/gwc/src/main/java/org/geoserver/gwc/web/gridset/GridSetsPage.java
- src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/GridSubsetsEditor.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/GWCSettingsPageTest.java
[![GEOS-10210](https://badgen.net/badge/JIRA/GEOS-10210/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10210)
See description in linked ticket. Depends on https://github.com/GeoWebCache/geowebcache/pull/980
> [GEOS-10210] Follow up on addition of OGC TMS gridsets in GWC

- doc/en/user/source/community/smart-data-loader/data-store.rst
- doc/en/user/source/community/smart-data-loader/index.rst
- doc/en/user/source/community/smart-data-loader/install.rst
Edits for documentation for a community module.
@taba90 Can you have a quick check to make sure I didn't get it wrong?
> doc: minor fixes for Smart Data Loader user guide

- doc/en/user/source/tutorials/GetFeatureInfo/geojson.rst
[![GEOS-10218](https://badgen.net/badge/JIRA/GEOS-10218/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10218)
Jira ticket: [GEOS-10218](https://osgeo-org.atlassian.net/browse/GEOS-10218)
> [GEOS-10218] GetFeatureInfo documentation example template generates invalid JSON

- src/wms/src/main/java/applicationContext.xml
- src/wms/src/main/java/org/geoserver/wms/CiteComplianceCallback.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapIntegrationTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesSystemTest.java
[![GEOS-10211](https://badgen.net/badge/JIRA/GEOS-10211/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10211)
> [GEOS-10211] Unable to pass INSPIRE validation: Version is mandatory

- doc/en/developer/source/release-guide/index.rst
- doc/en/index.html
[![GEOS-10221](https://badgen.net/badge/JIRA/GEOS-10221/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10221)
Follow-up to https://github.com/geoserver/geoserver/pull/5264
The documentation index page from that PR is now deploying automatically, and the updates can be seen on [docs.geoserver.org](https://docs.geoserver.org)
However, when adding the links for 2.14.x through 2.19.x to that PR, I neglected to test them - turns out the doc link structure changed between 2.13 and 2.14, corresponding with the doc server move. This PR fixes that error, and also adds a step to the release guide for adding a new link (with the correct structure) when a new RC branch is created.
See also https://osgeo-org.atlassian.net/browse/GEOS-10221
> [GEOS-10221] Fix broken links in Release versions, add section on updating these links to release guide

- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/configuration/Template.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/configuration/TemplateLoader.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/JSONTemplateReader.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/RecursiveTemplateResourceParser.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/XMLRecursiveTemplateReader.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/readers/JSONIncludesTest.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/readers/JSONMergesTest.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/readers/XmlTemplateReaderTest.java
[![GEOS-10227](https://badgen.net/badge/JIRA/GEOS-10227/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10227)
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-10227
> [GEOS-10227] Features Templating - Included templates are not reloaded on file modifications

- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/configuration/Template.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/configuration/TemplateLoader.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/JSONTemplateReader.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/RecursiveTemplateResourceParser.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/XMLRecursiveTemplateReader.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/readers/JSONIncludesTest.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/readers/JSONMergesTest.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/readers/XmlTemplateReaderTest.java
[![GEOS-10227](https://badgen.net/badge/JIRA/GEOS-10227/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10227)
* [GEOS-10227] Features Templating - Included templates are not reloaded on file modifications
> [2.19.x backport][GEOS-10227] Features Templating - Included templates are not reloaded on file modifications (#5273)

- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/RecursiveJSONParser.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/TemplateReaderConfiguration.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/TemplateReaderProvider.java
[![GEOS-10224](https://badgen.net/badge/JIRA/GEOS-10224/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10224)
This pr pick only the features templating related modification from the main pr to keep it aligned with the main branch.
STAC related modifications  have not been picked up because the 2.19.x STAC is far behind in history comparing to the main version.
> [2.19.x] [GEOS-10224] Feature templating merge directive does not work on STAC collections template

- doc/en/user/source/services/wfs/outputformats.rst
- doc/en/user/source/services/wfs/vendor.rst
- src/wfs/src/main/java/org/geoserver/wfs/response/CSVOutputFormat.java
- src/wfs/src/test/java/org/geoserver/wfs/response/CSVOutputFormatTest.java
[![GEOS-10222](https://badgen.net/badge/JIRA/GEOS-10222/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10222)
This is backport of [5265](https://github.com/geoserver/geoserver/pull/5265) and [5285](https://github.com/geoserver/geoserver/pull/5285) for branch 2.19.x
> [2.19.x backport][GEOS-10222] WFS CSV OutputFormat delimiter

- src/README.txt
- src/release/README.txt
- src/release/developer_README.txt
This is a non functional change based on feedback from 2.20-RC testing
> Update developer readme formatting and https links

- src/web/core/src/main/java/org/geoserver/web/data/layer/SQLViewAbstractPage.html
- src/web/core/src/main/java/org/geoserver/web/data/layer/SQLViewAbstractPage.java
- src/web/core/src/main/resources/GeoServerApplication.properties
[![GEOS-10232](https://badgen.net/badge/JIRA/GEOS-10232/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10232)
> [GEOS-10232]SQL views are not saved if the layer is not saved too

- src/community/ogcapi/ogcapi-tiles/pom.xml
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/TileJSONBuilder.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/Tileset.java
- src/community/ogcapi/ogcapi-tiles/src/main/resources/org/geoserver/ogcapi/tiles/tileMatrixSet.ftl
- src/community/ogcapi/ogcapi-tiles/src/main/resources/org/geoserver/ogcapi/tiles/tileset-include.ftl
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/tiles/GetTileTest.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/tiles/TileJSONBuilderTest.java
[![GEOS-10223](https://badgen.net/badge/JIRA/GEOS-10223/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10223)
> [GEOS-10223] Support MBTiles in OGC Tiles API

- src/web/core/src/main/java/org/geoserver/web/data/layer/SQLViewAbstractPage.html
- src/web/core/src/main/java/org/geoserver/web/data/layer/SQLViewAbstractPage.java
- src/web/core/src/main/resources/GeoServerApplication.properties
[![GEOS-10232](https://badgen.net/badge/JIRA/GEOS-10232/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10232)
This is backport of [5283](https://github.com/geoserver/geoserver/pull/5283) for branch 2.19.x
> [2.19.x backport][GEOS-10232] SQL views are not saved if the layer is not saved too

- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/TileJSONBuilder.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/TilesService.java
- src/community/ogcapi/ogcapi-tiles/src/main/resources/org/geoserver/ogcapi/tiles/tileMatrixSets.ftl
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/tiles/GetTileTest.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/tiles/TilesetDescriptionTest.java
Backporting revisit of ogc-api tiles based on latest version of the spec.
> OGC-API Tiles: Revisiting links based on current status of the spec

- src/web/core/src/main/java/org/geoserver/web/data/layer/SQLViewAbstractPage.html
- src/web/core/src/main/java/org/geoserver/web/data/layer/SQLViewAbstractPage.java
- src/web/core/src/main/resources/GeoServerApplication.properties
[![GEOS-10232](https://badgen.net/badge/JIRA/GEOS-10232/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10232)
This is backport of [5283](https://github.com/geoserver/geoserver/pull/5283) for branch 2.20.x
> [2.20.x backport][GEOS-10232] SQL views are not saved if the layer is not saved too

- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadProcess.java
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
[![GEOS-10256](https://badgen.net/badge/JIRA/GEOS-10256/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10256)
https://osgeo-org.atlassian.net/browse/GEOS-10256
> [GEOS-10256]:WPS-Download geopackage, fixing returned file extension

- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadProcess.java
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
[![GEOS-10256](https://badgen.net/badge/JIRA/GEOS-10256/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10256)
2.19.x-backport for GEOS-10256
> [2.19.x-backport][GEOS-10256]:WPS-Download geopackage, fixing returned file extension

- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadProcess.java
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
[![GEOS-10256](https://badgen.net/badge/JIRA/GEOS-10256/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10256)
2.20.x-backport for GEOS-10256
> [2.20.x-backport][GEOS-10256]:WPS-Download geopackage, fixing returned file extension

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
[![GEOS-10246](https://badgen.net/badge/JIRA/GEOS-10246/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10246)
https://osgeo-org.atlassian.net/browse/GEOS-10246
> [GEOS-10246] Jdbc performance improvement from unnecessary transactions (backport)

- src/extension/monitor/core/src/test/java/org/geoserver/monitor/ows/MonitorCallbackTest.java
- src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/ClassifierTest.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadAnimationProcess.java
- src/pom.xml
- src/restconfig/src/test/java/org/geoserver/rest/catalog/AboutControllerTest.java
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReader.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/WMSCascadeTest.java
[![GEOS-10293](https://badgen.net/badge/JIRA/GEOS-10293/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10293)
> [GEOS-10293] Upgrade ErrorProne to 2.9.0

- src/community/backup-restore/web/src/main/java/org/geoserver/backuprestore/web/BackupRestoreDataPage.java
> Correct spelling mistake

- doc/en/user/source/data/vector/directory.rst
- src/web/core/src/main/java/org/geoserver/web/data/store/shape/ShapefileDirectoryEditPanel.html
- src/web/core/src/main/java/org/geoserver/web/data/store/shape/ShapefileDirectoryEditPanel.java
- src/web/core/src/main/java/org/geoserver/web/data/store/shape/ShapefileStoreEditPanel.html
- src/web/core/src/main/resources/GeoServerApplication.properties
- src/web/core/src/test/java/org/geoserver/web/data/store/ShapefileDirectoryStorePageTest.java
[![GEOS-10289](https://badgen.net/badge/JIRA/GEOS-10289/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10289)
[Backport-2.20.x][GEOS-10289]
> [Backport-2.20.x][GEOS-10289]: Improve Shapefiles Directory datastore performances with huge amount of files

- doc/en/user/source/community/backuprestore/usagerest.rst
> Fix minor grammatical and spelling errors

- doc/en/user/source/data/vector/directory.rst
- src/web/core/src/main/java/org/geoserver/web/data/store/shape/ShapefileDirectoryEditPanel.html
- src/web/core/src/main/java/org/geoserver/web/data/store/shape/ShapefileDirectoryEditPanel.java
- src/web/core/src/main/java/org/geoserver/web/data/store/shape/ShapefileStoreEditPanel.html
- src/web/core/src/main/resources/GeoServerApplication.properties
- src/web/core/src/test/java/org/geoserver/web/data/store/ShapefileDirectoryStorePageTest.java
[![GEOS-10289](https://badgen.net/badge/JIRA/GEOS-10289/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10289)
[Backport-2.19.x][GEOS-10289]
Needs https://github.com/geotools/geotools/pull/3661 to be merged, first
> [Backport-2.19.x][GEOS-10289]: Improve Shapefiles Directory datastore performances with huge amount of files

- doc/en/user/source/community/features-templating/directives.rst
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/DynamicValueBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/IteratingBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/GMLTemplateReader.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/JSONTemplateReader.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/XMLRecursiveTemplateReader.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/CommonJSONWriter.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/TemplateOutputWriter.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/XMLTemplateWriter.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/builders/impl/DynamicValueBuilderTest.java
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/ManagedMappedFeatureGML32.xml
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/ManagedMappedFeatureGeoJSON.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/ManagedMappedFeatureJSONLD.json
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/ComplexGetFeatureInfoTest.java
[![GEOS-10268](https://badgen.net/badge/JIRA/GEOS-10268/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10268)
Backport of GEOS-10268 2.20.x
> [2.20.x backport][GEOS-10268] null support is added with ! string

- doc/en/user/source/community/features-templating/directives.rst
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/DynamicValueBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/IteratingBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/GMLTemplateReader.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/JSONTemplateReader.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/XMLRecursiveTemplateReader.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/CommonJSONWriter.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/TemplateOutputWriter.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/XMLTemplateWriter.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/builders/impl/DynamicValueBuilderTest.java
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/ManagedMappedFeatureGML32.xml
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/ManagedMappedFeatureGeoJSON.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/ManagedMappedFeatureJSONLD.json
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/ComplexGetFeatureInfoTest.java
[![GEOS-10268](https://badgen.net/badge/JIRA/GEOS-10268/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10268)
Backport of GEOS-10268 2.19.x
> [2.19.x backport][GEOS-10268] null support is added with ! string 

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIDispatcher.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AttributeType.java
- src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/OGCApiTestSupport.java
Simple update on community module to remove CBOR format support (being unused)
> OGC-API: Removing unused CBOR format support

- src/web/core/src/main/java/org/geoserver/web/wicket/CRSPanel.java
- src/web/core/src/test/java/org/geoserver/web/wicket/CRSPanelTest.java
- src/web/core/src/test/java/org/geoserver/web/wicket/CRSPanelTestPage.java
- src/wms/src/main/java/org/geoserver/wms/map/AbstractOpenLayersMapOutputFormat.java
- src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapOutputFormatTest.java
- src/wms/src/test/resources/OL_LOGGING.properties
See:
* https://osgeo-org.atlassian.net/browse/GEOS-10300
* https://osgeo-org.atlassian.net/browse/GEOS-10299
> A couple of improvements to handle AUTO codes in GeoServer reprojection console and map preview

- doc/en/user/source/community/opensearch-eo/configuration.rst
[![GEOS-10287](https://badgen.net/badge/JIRA/GEOS-10287/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10287)
Documentation update for freemarker functionality. Created a new PR since [the old pr](https://github.com/geoserver/geoserver/pull/5355) is already merged.
> [GEOS-10287] Documentation fix for the freemarker loadJSON function

- src/community/metadata/pom.xml
- src/community/ogcapi/ogcapi-core/pom.xml
- src/pom.xml
[![GEOS-10308](https://badgen.net/badge/JIRA/GEOS-10308/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10308)
Centralizes the version number. Have run the tests in ``community/metadata`` with a ``mvn clean install``, full pass.
> [GEOS-10308] GeoServer with OGCAPI fails to deploy

- doc/en/user/source/community/geopkg/output.rst
- src/community/geopkg/src/main/java/applicationContext.xml
- src/community/geopkg/src/main/java/org/geoserver/geopkg/GeoPackageGetMapOutputFormat.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoPackageProcess.java
- src/community/geopkg/src/test/java/org/geoserver/geopkg/GeoPackageGetMapOutputFormatTest.java
- src/community/geopkg/src/test/java/org/geoserver/geopkg/wps/GeoPackageProcessTest.java
- src/community/geopkg/src/test/resources/org/geoserver/geopkg/wps/fillenv.sld
> GeoPackage: fix tile matrix bounds for tile layers, support groups and vendor options in tile layers

- src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java
- src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
- src/web/core/src/test/resources/wms_getCaps_CRS.xml
[![GEOS-10309](https://badgen.net/badge/JIRA/GEOS-10309/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10309)
WMS cascade layer returns wrong native CRS to GeoServer. The returned SRS and bounding boxes are unordered making hard to GeoServer to pick the first native CRS to use during rendering when the source GetCapabilities document root layer reports more supported CRSs and bounding boxes.
This PR add a test update due to this bug fix done on GeoTools PR and fix an issue on default native CRS when loading a new layer.  Requires merged:
https://github.com/geotools/geotools/pull/3679
https://osgeo-org.atlassian.net/browse/GEOS-10309
> [GEOS-10309] Fix cascade WMS layer wrong native CRS selection

- src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java
- src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
- src/web/core/src/test/resources/wms_getCaps_CRS.xml
[![GEOS-10309](https://badgen.net/badge/JIRA/GEOS-10309/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10309)
WMS cascade layer returns wrong native CRS to GeoServer. The returned SRS and bounding boxes are unordered making hard to GeoServer to pick the first native CRS to use during rendering when the source GetCapabilities document root layer reports more supported CRSs and bounding boxes.
This PR add a test update due to this bug fix done on GeoTools PR and fix an issue on default native CRS when loading a new layer.
https://osgeo-org.atlassian.net/browse/GEOS-10309
> [2.20.x backport][GEOS-10309] Fix cascade WMS layer wrong native CRS selection

- src/community/geopkg/src/main/java/org/geoserver/geopkg/GeoPackageGetMapOutputFormat.java
- src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoPackageProcess.java
- src/community/geopkg/src/test/java/org/geoserver/geopkg/GeoPackageGetMapOutputFormatTest.java
- src/community/geopkg/src/test/java/org/geoserver/geopkg/wps/GeoPackageProcessTest.java
- src/community/geopkg/src/test/resources/GPKG_LOGGING.properties
- src/community/mbtiles/src/main/java/org/geoserver/mbtiles/MBTilesGetMapOutputFormat.java
- src/community/mbtiles/src/main/java/org/geoserver/mbtiles/gs/wps/MBTilesProcess.java
- src/community/mbtiles/src/main/java/org/geoserver/tiles/AbstractTilesGetMapOutputFormat.java
- src/community/mbtiles/src/test/java/org/geoserver/mbtiles/MBTilesGetMapOutputFormatTest.java
[![GEOS-10313](https://badgen.net/badge/JIRA/GEOS-10313/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10313)
> [GEOS-10313] Support WMS rendering timeout in GeoPackage WMS output, support cancellation in WPS process

- src/pom.xml
> [QA] Bump org.owasp:dependency-check-maven from 6.2.2 to 6.5.0

- .github/workflows/docs.yml
- .github/workflows/linux_jdk11.yml
- .github/workflows/linux_jdk8.yml
- .github/workflows/macos.yml
- .github/workflows/qa.yml
- .github/workflows/windows.yml
> [CI] Update Github workflow actions

- src/community/elasticsearch/pom.xml
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticConfigurationPage.java
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticConfigurationPanel.java
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticConfigurationPanelInfo.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticConfigurationPanelInfoTest.java
[![GEOS-10317](https://badgen.net/badge/JIRA/GEOS-10317/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10317)
> [GEOS-10317] ElasticSearch GUI goes NPE when using stores without a declared type (plus some QA)

- src/pom.xml
Follows up with:
- https://github.com/geotools/geotools/pull/3693 (GeoTools)
- https://github.com/GeoWebCache/geowebcache/pull/990 (GeoWebCache)
> Update JAI-EXT to 1.1.21 (2.20.x backport)

- src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
- src/gwc/src/test/java/org/geoserver/gwc/layer/GeoServerTileLayerTest.java
[![GEOS-10249](https://badgen.net/badge/JIRA/GEOS-10249/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10249)
2.18.x backport of https://github.com/geoserver/geoserver/pull/5301
> [GEOS-10249] GWC produce NPE when it comes to race condition (2.18.x)

- src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
- src/gwc/src/test/java/org/geoserver/gwc/layer/GeoServerTileLayerTest.java
[![GEOS-10249](https://badgen.net/badge/JIRA/GEOS-10249/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10249)
2.19.x backport of https://github.com/geoserver/geoserver/pull/5301
> [GEOS-10249] GWC produce NPE when it comes to race condition (2.19.x)

- src/release/bin/shutdown.sh
- src/release/bin/startup.sh
[![GEOS-10316](https://badgen.net/badge/JIRA/GEOS-10316/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10316)
This PR aims to fix issue GEOS-10316 introduced by GEOS-10033.
startup.sh and shutdown.sh scripts were not working as expected when using multiples java options in JAVA_OPTS environment variable.
> [GEOS-10316] Fix startup.sh to handle multiple java options

- src/pom.xml
[![GEOS-10335](https://badgen.net/badge/JIRA/GEOS-10335/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10335)
> [GEOS-10335] Update GeoServer to a log4j version that does not support RCEs (2.18.x)

- src/pom.xml
[![GEOS-10335](https://badgen.net/badge/JIRA/GEOS-10335/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10335)
> [GEOS-10335] Update GeoServer to a log4j version that does not support RCEs (2.20.x)

- .github/workflows/docs.yml
- .github/workflows/linux_jdk11.yml
- .github/workflows/linux_jdk17.yml
- .github/workflows/linux_jdk8.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
> [CI] optimize builds

- src/pom.xml
> [QA] Bump dependency-check-maven from 6.5.0 to 6.5.1

- src/community/jms-cluster/activemqBroker/pom.xml
[![GEOS-10339](https://badgen.net/badge/JIRA/GEOS-10339/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10339)
Minor cleanup to activemq part of jms-cluster community module.
> [GEOS-10339] jms-cluster: switch to using managed dependency for log4j

- doc/en/user/source/community/jdbcconfig/configuration.rst
- doc/en/user/source/community/jdbcstore/configuration.rst
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcloader/DataSourceFactoryBean.java
- src/community/jdbcconfig/src/main/resources/jdbcconfig.properties
- src/community/jdbcconfig/src/main/resources/jdbcconfig.properties.h2
- src/community/jdbcconfig/src/main/resources/jdbcconfig.properties.postgres
- src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/DataSourceFactoryBeanTest.java
- src/community/jdbcstore/src/main/resources/jdbcstore.properties
- src/community/jdbcstore/src/main/resources/jdbcstore.properties.h2
[![GEOS-10322](https://badgen.net/badge/JIRA/GEOS-10322/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10322)
> [2.19.x backport][GEOS-10322] JDBCConfig community module does not deal with stale connections to the database 

- doc/en/user/source/community/jdbcconfig/configuration.rst
- doc/en/user/source/community/jdbcstore/configuration.rst
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcloader/DataSourceFactoryBean.java
- src/community/jdbcconfig/src/main/resources/jdbcconfig.properties
- src/community/jdbcconfig/src/main/resources/jdbcconfig.properties.h2
- src/community/jdbcconfig/src/main/resources/jdbcconfig.properties.postgres
- src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/DataSourceFactoryBeanTest.java
- src/community/jdbcstore/src/main/resources/jdbcstore.properties
- src/community/jdbcstore/src/main/resources/jdbcstore.properties.h2
[![GEOS-10322](https://badgen.net/badge/JIRA/GEOS-10322/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10322)
> [2.20.x backport][GEOS-10322] JDBCConfig community module does not deal with stale connections to the database #5427

- src/wfs/src/main/java/org/geoserver/wfs/response/CSVOutputFormat.java
- src/wfs/src/test/java/org/geoserver/wfs/response/CSVOutputFormatTest.java
[![GEOS-10327](https://badgen.net/badge/JIRA/GEOS-10327/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10327)
Jira Ticket: [GEOS-10327](https://osgeo-org.atlassian.net/browse/GEOS-10327)
> [GEOS-10327] CSV Outputformat - Allow list of values to be returned as a comma separated string

- doc/en/user/source/extensions/importer/rest_reference.rst
- src/extension/importer/core/src/main/java/org/geoserver/importer/ImportContext.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
- src/extension/importer/core/src/test/java/org/geoserver/importer/ImporterDataTest.java
[![GEOS-10337](https://badgen.net/badge/JIRA/GEOS-10337/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10337)
See ticket.
> [GEOS-10337] Harden importer against failed imports, make failures more evident

- .github/workflows/linux_jdk17.yml
setting to 512MB which is about half the size of the default value doesn't seem right.
this attempts to resolve build failures for java 17 builds caused by 
```
Error: 5,941 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:3.3.2:war (default-war) on project activemqBroker: Error assembling WAR: Problem creating war: Execution exception: Java heap space -> [Help 1]
Error: 5,941 [ERROR] Java heap space -> [Help 2]
Error: 5,943 [ERROR] java.lang.OutOfMemoryError: Java heap space
```
eg https://github.com/geoserver/geoserver/runs/4693697806?check_suite_focus=true
> [CI] don't set max heap space for java 17

- doc/en/user/source/styling/ysld/cookbook/lines.rst
- doc/en/user/source/styling/ysld/cookbook/points.rst
- doc/en/user/source/styling/ysld/cookbook/polygons.rst
- doc/en/user/source/styling/ysld/cookbook/rasters.rst
- doc/en/user/source/styling/ysld/reference/featurestyles.rst
- doc/en/user/source/styling/ysld/reference/index.rst
- doc/en/user/source/styling/ysld/reference/rules.rst
- doc/en/user/source/styling/ysld/reference/symbolizers/include/composite.txt
- doc/en/user/source/styling/ysld/reference/symbolizers/include/inclusion.txt
- doc/en/user/source/styling/ysld/reference/symbolizers/include/misc.txt
- doc/en/user/source/styling/ysld/reference/symbolizers/include/symbol.txt
- doc/en/user/source/styling/ysld/reference/symbolizers/index.rst
- doc/en/user/source/styling/ysld/reference/symbolizers/line.rst
- doc/en/user/source/styling/ysld/reference/symbolizers/point.rst
- doc/en/user/source/styling/ysld/reference/symbolizers/polygon.rst
- doc/en/user/source/styling/ysld/reference/symbolizers/raster.rst
- doc/en/user/source/styling/ysld/reference/symbolizers/text.rst
- doc/en/user/source/styling/ysld/reference/variables.rst
Some cleanup for YSLD documentation to reflect https://github.com/geotools/geotools/pull/3694 improvements.
Also included some code examples (rather than see duplication) and revised the examples for yaml variable definition and reuse. 
This is a non functional change improving documentation.
> Update ysld documentation for x-include vendor option, variable definition, and yaml examples.

- src/kml/pom.xml
- src/platform/pom.xml
- src/web/core/src/main/java/org/geoserver/web/data/store/NewDataPage.java
- src/web/security/jdbc/pom.xml
- src/wms/pom.xml
[![GEOS-10348](https://badgen.net/badge/JIRA/GEOS-10348/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10348)
Remove dependency on h2 database from gs-platform and gs-wms
Also fix an unnecessary import on `web-core`'s `NewDataPage`
for `org.h2.DataPage`.
> [GEOS-10348] Remove dependency on h2 database from gs-platform and gs-wms

- doc/en/developer/source/programming-guide/wps-services/design-guide.rst
- doc/en/user/source/installation/war.rst
* Tomcat hardening added
Do not make it too easy for the script-kiddy attacker and hide the tomcat version.
* literal blocks fixed
removed unexpected indentation
* corrected code-block:: java to xml
This was not my change, but due to this warning:
``` 
[exec] /home/runner/work/geoserver/geoserver/doc/en/developer/source/programming-guide/wps-services/design-guide.rst:102: WARNING: Could not lex literal_block as "java". Highlighting skipped.
```
> [2.19.x backport] Tomcat hardening added (#5560)

- src/community/oseo/oseo-rest/src/main/java/org/geoserver/opensearch/rest/AbstractOpenSearchController.java
Fix failing tests by updating the geom name after change in gt GeoJSONReader.
> Follow up gt GeoJSONReader geometry name changed

- doc/en/user/source/configuration/status.rst
[![GEOS-10243](https://badgen.net/badge/JIRA/GEOS-10243/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10243)
The issue is already fixed in PR: [5542](https://github.com/geoserver/geoserver/pull/5542), Updating documentation here.
> [GEOS-10243] OSHI may generate high CPU load on Windows

- doc/en/user/source/community/features-templating/directives.rst
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/TemplateBuilderMaker.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/DynamicIncludeFlatBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/DynamicMergeBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/DynamicValueBuilder.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/JSONTemplateReader.java
- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/readers/RecursiveJSONParser.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/builders/impl/DynamicIncludeFlatBuilderTest.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/readers/JSONIncludesTest.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/writers/JsonWriterTest.java
- src/community/features-templating/features-templating-core/src/test/resources/jsonIncludes/dynamicIncludeFlat.json
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/ItemsTest.java
- src/community/oseo/oseo-stac/src/test/resources/items-LANDSAT8.json
[![GEOS-10319](https://badgen.net/badge/JIRA/GEOS-10319/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10319)
includeFlat keyword now loads a JSON database field in freemarker templates.
For example, if we have the following JSON property:
```
myJSONProperty
{
a: 10;
b: 20;
}
```
and the following template:
```
flat:
{
"properties": {
c: 20;
"$includeFlat": "${myJSONProperty};
}
}
```
the result will be this:
```
"properties": {
c: 20;
a: 10;
b: 20;
}
```
> [GEOS-10319] includeFlat a JSON database field to a features template

- src/wms/src/main/java/org/geoserver/wms/GetFeatureInfo.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/RasterLayerIdentifier.java
- src/wms/src/main/java/org/geoserver/wms/map/RasterSymbolizerVisitor.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java
- src/wms/src/test/resources/org/geoserver/wms/wms_1_1_1/footprints.sld
See tickets:
* [GEOS-10358](https://osgeo-org.atlassian.net/browse/GEOS-10358)
* [GEOS-10359](https://osgeo-org.atlassian.net/browse/GEOS-10359)
> Fix GetFeatureInfo on layers using mosaic footprint extraction

- src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
- src/wms/src/test/java/org/geoserver/wms/LegendNonValidCapabilitiesTest.java
- src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesLegendURLTest.java
- src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesReponseTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/LegendCapabilitiesTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/LegendCapabilitiesTest.java
[![GEOS-10336](https://badgen.net/badge/JIRA/GEOS-10336/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10336)
* [GEOS-10336]-INSPIRE failure: version not propagated in GetCapabilities LegendURL
Co-authored-by: Mark Prins <1165786+mprins@users.noreply.github.com>
> [2.20.x Backport] [GEOS-10336]-INSPIRE failure: version not propagated in GetCapabilities LegendURL

- src/community/gsr/NOTICE.md
- src/pom.xml
- src/release/NOTICE.md
- src/wms/pom.xml
- src/wms/src/main/java/org/geoserver/wms/map/PDFMapOutputFormat.java
- src/wms/src/main/java/org/geoserver/wms/map/PDFMapResponse.java
[![GEOS-10363](https://badgen.net/badge/JIRA/GEOS-10363/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10363)
Switches the WMS dependency to OpenPDF, which is basically a drop-in replacement.
There is one code change that was needed, to dispose of a graphics entity that we were not previously handling. There is also a switch to try-with-resources on the document, required to pass PMD checks.
This PR also includes some minor documentation updates,.
- [N/A] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have …
> [GEOS-10363] Switch from itextpdf to openpdf for PDF map rendering

- src/community/features-templating/features-templating-core/pom.xml
- src/community/ogcapi/ogcapi-core/pom.xml
- src/community/oseo/oseo-rest/pom.xml
- src/community/release/ext-elasticsearch.xml
- src/community/release/ext-features-templating.xml
- src/community/release/ext-ogcapi.xml
- src/community/release/ext-opensearch-eo.xml
- src/extension/importer/core/src/main/java/org/geoserver/importer/format/GeoJSONFormat.java
- src/extension/importer/pom.xml
- src/extension/ogr/ogr-wps/src/test/java/org/geoserver/wps/ogr/WPSOgrTest.java
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
- src/extension/wps/wps-core/pom.xml
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/gs/PagedUniqueProcessPPIO.java
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/GeoJSONPPIO.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteTest.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/AggregateProcessTest.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/jts/GeometryProcessWPSTest.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ppio/GeoJSONPPIOTest.java
- src/restconfig/pom.xml
- src/restconfig/src/main/java/org/geoserver/rest/catalog/FeatureCollectionConverter.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/FormatCollectionWrapperConverter.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/SimpleFeatureCollectionConverter.java
- src/wms/pom.xml
- src/wms/src/main/java/org/geoserver/wms/featureinfo/GeoJSONTemplateManager.java
[![GEOS-13345](https://badgen.net/badge/JIRA/GEOS-13345/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-13345)
Updated based on discussion, with split module. Depends on https://github.com/geotools/geotools/pull/3747
> [GEOS-13345] Switch from gt-geojson to gt-geojson-core

- src/release/bin/shutdown.sh
- src/release/bin/startup.sh
[![GEOS-10316](https://badgen.net/badge/JIRA/GEOS-10316/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10316)
2.20.x Backport of [GEOS-10316](https://osgeo-org.atlassian.net/browse/GEOS-10316)
I just cherry-picked the commit from #5415.
JAVA_OPTS works with multiple parameters for both paths with and without spaces.
> [GEOS-10316] Fix spaces backport for 2.20.x

- src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/UnconfiguredCachedLayersProvider.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/NewCachedLayerPageTest.java
[![GEOS-10374](https://badgen.net/badge/JIRA/GEOS-10374/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10374)
Fix `java.io.NotSerializableException` log flooding at
`NewCachedLayerPage.java` due to its inner class `CachedSize`
not implementing `Serializable`, introduced at commit cf77a0baef4.
> [GEOS-10374] Log exception flooding opening GWC's NewCachedLayerPage

- doc/en/api/1.0.0/logging.yaml
- doc/en/user/source/rest/api/index.rst
- doc/en/user/source/rest/api/logging.rst
- doc/en/user/source/rest/index.rst
- src/restconfig/src/main/java/org/geoserver/rest/LoggingController.java
- src/restconfig/src/main/java/org/geoserver/rest/ftl-templates/logging.ftl
- src/restconfig/src/test/java/org/geoserver/rest/LoggingControllerTest.java
[![GEOS-10368](https://badgen.net/badge/JIRA/GEOS-10368/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10368)
Logging controller is added to the /logging endpoint. It fetches and updates logging info using below json syntax.
```
{
"logging": {
"level": "GEOSERVER_DEVELOPER_LOGGING.properties",
"location": "logs/geoserver2.log",
"stdOutLogging": true
}
}
```
> [GEOS-10368] Logging controller is added

- src/release/ext-mbstyle.xml
[![GEOS-10385](https://badgen.net/badge/JIRA/GEOS-10385/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10385)
GeoServer used to jave json-simple packaged in the war, but not any longer (the library has been dead for a number of years).
> [GEOS-10385] GeoServer with MBStyles plugin fails to start, lacks JSON parsing library

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/SortByConverter.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/SourcePropertyMapper.java
- src/community/oseo/oseo-core/src/test/resources/custom_product_class.sql
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACQueryablesBuilder.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACService.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACSortablesMapper.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/TemplateBuilderUtils.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/TemplatePropertyVisitor.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/ItemsTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/STACQueryablesBuilderTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/STACSortablesMapperTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/SearchTest.java
- src/community/release/ext-ogcapi.xml
[![GEOS-10386](https://badgen.net/badge/JIRA/GEOS-10386/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10386)
As per ticket title... checking community build is fine.
> [GEOS-10386] STAC sorting, initial implementation

- doc/en/user/source/security/webadmin/ugr.rst
- src/main/src/main/java/org/geoserver/security/impl/AbstractRoleStore.java
- src/security/security-tests/src/test/java/org/geoserver/security/impl/AbstractUserDetailsServiceTest.java
- src/security/security-tests/src/test/java/org/geoserver/security/xml/XMLRoleServiceTest.java
[![GEOS-10362](https://badgen.net/badge/JIRA/GEOS-10362/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10362)
Remove selected and remove role associations removes user and user's roles from roles.xml.
> [GEOS-10362] Remove selected and remove role associations removes user and the roles from roles.xml

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/Sortables.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACLandingPage.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACService.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACSortablesMapper.java
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/stac/collection.ftl
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/stac/collections.json
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/stac/items.json
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/stac/landingPage.ftl
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/stac/openapi.yaml
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/stac/sortables-collection.ftl
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/stac/sortables-common.ftl
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/stac/sortables-global.ftl
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/ApiTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/CollectionsTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/LandingPageTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/STACQueryablesBuilderTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/STACSortablesMapperTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/STACTestSupport.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/SearchTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/SortablesTest.java
[![GEOS-10386](https://badgen.net/badge/JIRA/GEOS-10386/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10386)
Complete work done in previous PR
> [GEOS-10386] STAC sorting, add missing bits

- doc/en/user/source/extensions/authkey/index.rst
ref: https://sourceforge.net/p/geoserver/mailman/message/37602011/
> Add limitation: User Enabled checkbox does not affect Authkey module

- doc/en/user/source/security/webadmin/ugr.rst
- src/main/src/main/java/org/geoserver/security/impl/AbstractRoleStore.java
- src/security/security-tests/src/test/java/org/geoserver/security/xml/XMLRoleServiceTest.java
[![GEOS-10362](https://badgen.net/badge/JIRA/GEOS-10362/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10362)
2.19.x backport of https://github.com/geoserver/geoserver/pull/5598
> [2.19.x][GEOS-10362] Remove selected and remove role associations removes user and the roles from roles.xml

- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/builders/impl/DynamicIncludeFlatBuilder.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACService.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/ConformanceTest.java
Simple build check on community modules
> Advertising sort and filter STAC search extensions. Adding forgotten javadoc too

- doc/en/user/source/production/config.rst
Fixed wording on entity resolution, and then noticed how out of date the entire page was (recommending users edit ``info.xml`` file directly, when control available in web admin)
Many of the recommndations are from much earlier in the project history, before some facilities such as security were introduced.
> Update production recommendations

- src/community/teradata/pom.xml
Seems to be an oversight at #5688, but the build breaks if there's no `org.geoserver.extension:gs-teratata` in the local maven repo
> Fix parent pom for community/teradata after being downgraded from extensions

- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/CRSRequestHandler.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterDirectDownloader.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterDownload.java
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
- src/wcs/src/main/java/org/geoserver/wcs/responses/GeoTIFFCoverageResponseDelegate.java
[![GEOS-10399](https://badgen.net/badge/JIRA/GEOS-10399/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10399)
See ticket
> [GEOS-10399] Allow wps-download to perform a straight copy of the source raster, when the request is not altering it in any way

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/resource/WPSResourceManager.java
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/response/StoredResourceResponse.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/GetExecutionResultTest.java
[![GEOS-10401](https://badgen.net/badge/JIRA/GEOS-10401/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10401)
This PR stores the mime type of the WPS Execute request and checks that the mimetype parameter in the WPS GetExecutionResult request matches the stored mime type.
> [GEOS-10401] WPS GetExecutionResult doesn't validate the mimetype parameter

- src/wfs/pom.xml
- src/wfs/src/main/java/org/geoserver/wfs/Transaction.java
- src/wfs/src/main/java/org/geoserver/wfs/request/Delete.java
- src/wfs/src/main/java/org/geoserver/wfs/request/Insert.java
- src/wfs/src/main/java/org/geoserver/wfs/request/TransactionRequest.java
- src/wfs/src/test/java/org/geoserver/wfs/BatchManagerTest.java
- src/wfs/src/test/java/org/geoserver/wfs/TransactionTest.java
[![GEOS-10393](https://badgen.net/badge/JIRA/GEOS-10393/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10393)
Hi there,
here is the PR for [GEOS-10393](https://osgeo-org.atlassian.net/browse/GEOS-10393).
I have also removed methods from "org.geoserver.wfs.request.Delete" and "org.geoserver.wfs.request.Insert" classes which where introduced for BatchManager but not any longer required.
I would be glad if you could port it back when merging. I guess is much less overhead for you.
Thank you very much for taking care!
Best regards,
Andreas
PS: As a side note: I find the new code formatting rules a little hard to get used to.
> [GEOS-10393] Improve WFS-T BatchManager

- src/main/src/test/java/org/geoserver/catalog/impl/CatalogProxiesTest.java
> Fix resource leak in CatalogProxiesTest

- build/qa/pmd-junit-ruleset.xml
- build/qa/pmd-ruleset.xml
- src/extension/grib/src/test/java/org/geoserver/catalog/CoverageViewReaderTest.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLControllerTest.java
- src/extension/web-resource/src/main/java/org/geoserver/web/resources/PageResourceBrowser.java
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/ScaleToTargetTest.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/BufferFeatureCollectionTest.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/InclusionFeatureCollectionTest.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/UnionFeatureCollectionTest.java
- src/gwc/src/test/java/org/geoserver/gwc/layer/CatalogConfigurationLayerConformanceTest.java
- src/kml/src/test/java/org/geoserver/kml/GeoSearchKMLTest.java
- src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java
- src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
- src/pom.xml
- src/security/security-tests/src/test/java/org/geoserver/security/password/GeoserverPasswordEncoderTest.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/WCSTestSupport.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/xml/GetCoverageTest.java
- src/web/core/src/test/java/org/geoserver/web/data/layergroup/LayerGroupEditPageTest.java
- src/web/core/src/test/java/org/geoserver/web/security/AccessDataRuleInfoManagerTest.java
- src/wms/src/test/java/org/geoserver/wms/map/RenderedImageMapOutputFormatTest.java
[![GEOS-10410](https://badgen.net/badge/JIRA/GEOS-10410/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10410)
Updates to recent PMD, simplify rule set, remove deprecated rules.
> [GEOS-10410] Update to PMD 6.42

- doc/en/user/source/filter/function_reference.rst
- doc/en/user/source/services/wcs/webadmin.rst
> update NumberFormat docs to mention optional locale

- src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
- src/wms/src/test/java/org/geoserver/wms/LegendNonValidCapabilitiesTest.java
- src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesLegendURLTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/LegendCapabilitiesTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/LegendCapabilitiesTest.java
[![GEOS-10336](https://badgen.net/badge/JIRA/GEOS-10336/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10336)
* [GEOS-10336]-INSPIRE failure: version not propagated in GetCapabilities LegendURL
Co-authored-by: Mark Prins <1165786+mprins@users.noreply.github.com>
> [2.19.x Backport] [GEOS-10336]-INSPIRE failure: version not propagated in GetCapabilities LegendURL

- src/wfs/pom.xml
- src/wfs/src/main/java/org/geoserver/wfs/Transaction.java
- src/wfs/src/main/java/org/geoserver/wfs/request/Delete.java
- src/wfs/src/main/java/org/geoserver/wfs/request/Insert.java
- src/wfs/src/main/java/org/geoserver/wfs/request/TransactionRequest.java
- src/wfs/src/test/java/org/geoserver/wfs/BatchManagerTest.java
- src/wfs/src/test/java/org/geoserver/wfs/TransactionTest.java
[![GEOS-10393](https://badgen.net/badge/JIRA/GEOS-10393/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10393)
Pull request for backporting [GEOS-10393](https://osgeo-org.atlassian.net/browse/GEOS-10393) to 2.20.x
Pull request for main has been merged already:
https://github.com/geoserver/geoserver/pull/5687
> [GEOS-10393] Improve WFS-T BatchManager (#5687) - backport to 2.20.x

- src/main/src/main/java/org/geoserver/security/impl/AbstractAccessRuleDAO.java
[![GEOS-10390](https://badgen.net/badge/JIRA/GEOS-10390/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10390)
Follow-up to https://github.com/geoserver/geoserver/pull/5705. That fix was missing a null check that I noticed is causing exception dumps in unit tests. (Should never cause issues in real live environment, because then there is always a layer security file.)
> [GEOS-10390] add null check to avoid NPE in unit tests

- src/community/release/ext-backup-restore.xml
[![GEOS-10432](https://badgen.net/badge/JIRA/GEOS-10432/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10432)
Add dependency on JDOM in assembly generation configuration file
> [GEOS-10432]Missing dependency in Backup/Restore plugin assembly

- src/pom.xml
[![GEOS-10303](https://badgen.net/badge/JIRA/GEOS-10303/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10303)
See ticket
> [GEOS-10303] Upgrade to jackson 2.13.2

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIFilterParser.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/FeatureService.java
- src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/features/openapi.yaml
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/ApiTest.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/FeatureTest.java
[![GEOS-10404](https://badgen.net/badge/JIRA/GEOS-10404/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10404)
* [GEOS-10404] Support filter-crs query parameter
* [GEOS-10404] Improve filter-crs parameter handling
* [GEOS-10404] Add invalid filter crs test
* [GEOS-10404] Resolve format violations
> [2.20.x backport] [GEOS-10404] OGCAPI Support `filter-crs` query parameter (#5711)

- src/pom.xml
Updating to imageio-ext 1.4.1 for better supports to S3 Urls
https://github.com/geosolutions-it/imageio-ext/issues/256
> Updating to imageio-ext 1.4.1 for better supports to S3 Urls

- src/restconfig/src/main/java/org/geoserver/rest/catalog/StyleController.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/StyleControllerTest.java
[![GEOS-10437](https://badgen.net/badge/JIRA/GEOS-10437/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10437)
See ticket.
> [GEOS-10437] Breaking SLD 1.1 style by REST upload

- src/community/release/ext-hz-cluster.xml
[![GEOS-10436](https://badgen.net/badge/JIRA/GEOS-10436/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10436)
> [GEOS-10436] Remove jackson jars from the hz-cluster packaging (2.20.x)

- doc/en/user/source/datadirectory/configtemplate.rst
- src/platform/src/main/java/org/geoserver/platform/GeoServerEnvironment.java
- src/platform/src/test/java/org/geoserver/platform/GeoServerEnvironmentTest.java
- src/platform/src/test/resources/org/geoserver/platform/GeoServerTesting.properties
[![GEOS-10434](https://badgen.net/badge/JIRA/GEOS-10434/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10434)
> [GEOS-10434]-Externalized geoserver-environment.properties.

- src/restconfig/src/main/java/org/geoserver/rest/catalog/StyleController.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/StyleControllerTest.java
[![GEOS-10437](https://badgen.net/badge/JIRA/GEOS-10437/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10437)
> [GEOS-10437] Breaking SLD 1.1 style by REST upload (2.20.x)

- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceGetMapIntegrationTest.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
[![GEOS-10418](https://badgen.net/badge/JIRA/GEOS-10418/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10418)
This is backport of [5756](https://github.com/geoserver/geoserver/pull/5756) for 2.20.x
> [2.20.x Backport][GEOS-10418] Bad request sent to GeoFence when matching roles only

- src/pom.xml
which is the current version of this plugin
> Bump `org.owasp:dependency-check-maven` from 6.5.1 to 7.0.4

- src/community/csw-iso/src/main/java/org/geoserver/csw/records/iso/MetaDataDescriptor.java
- src/community/csw-iso/src/main/resources/net/opengis/schemas/iso/19139/20070417/srv/serviceMetadata.xsd
- src/community/csw-iso/src/main/resources/net/opengis/schemas/iso/19139/20070417/srv/serviceModel.xsd
- src/community/csw-iso/src/main/resources/schemas/iso/19139/20070417/srv/serviceMetadata.xsd
- src/community/csw-iso/src/main/resources/schemas/iso/19139/20070417/srv/serviceModel.xsd
- src/community/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/GetRecordByIdTest.java
- src/community/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/GetRecordsTest.java
- src/community/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/MDTestSupport.java
- src/community/csw-iso/src/test/resources/org/geoserver/csw/store/internal/MD_Metadata.properties
[![GEOS-10447](https://badgen.net/badge/JIRA/GEOS-10447/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10447)
> [GEOS-10447] support Metadata for Services (SRV) in csw-iso

- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceGetMapIntegrationTest.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
[![GEOS-10418](https://badgen.net/badge/JIRA/GEOS-10418/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10418)
This PR fixes the change added in [5756](https://github.com/geoserver/geoserver/pull/5756)
> [GEOS-10418] Bad request sent to GeoFence when matching roles only

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIDispatcher.java
- src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/ImportTaskController.java
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadAnimationProcessTest.java
- src/main/src/main/java/org/geoserver/config/GeoServerPropertyConfigurer.java
- src/pom.xml
- src/restconfig/src/main/java/org/geoserver/rest/catalog/StyleController.java
[![GEOS-10445](https://badgen.net/badge/JIRA/GEOS-10445/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10445)
Backport #5772 to `2.20.x`
Depends on https://github.com/GeoWebCache/geowebcache/pull/1041
* [GEOS-10445] Bump spring.version from 5.1.20.RELEASE to 5.2.20.RELEASE
* [GEOS-10445] Bump spring.version from 5.1.20.RELEASE to 5.2.20.RELEASE
* [GEOS-10445] Fix QA build due to deprecated spring class
* [GEOS-10445] Fix ogc-api community module compilation failure
> [backport 2.20.x][GEOS-10445] Bump spring.version from 5.1.20.RELEASE to 5.2.20.RELEASE

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIDispatcher.java
- src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/ImportTaskController.java
- src/main/src/main/java/org/geoserver/config/GeoServerPropertyConfigurer.java
- src/pom.xml
- src/restconfig/src/main/java/org/geoserver/rest/catalog/StyleController.java
[![GEOS-10445](https://badgen.net/badge/JIRA/GEOS-10445/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10445)
Backport #5772 to `2.19.x`
Depends on https://github.com/GeoWebCache/geowebcache/pull/1040
* [GEOS-10445] Bump spring.version from 5.1.20.RELEASE to 5.2.20.RELEASE
* [GEOS-10445] Bump spring.version from 5.1.20.RELEASE to 5.2.20.RELEASE
* [GEOS-10445] Fix QA build due to deprecated spring class
* [GEOS-10445] Fix ogc-api community module compilation failure
> [backport 2.19.x][GEOS-10445] Bump spring.version from 5.1.20.RELEASE to 5.2.20.RELEASE

- doc/en/user/source/datadirectory/configtemplate.rst
- src/platform/src/main/java/org/geoserver/platform/GeoServerEnvironment.java
- src/platform/src/test/java/org/geoserver/platform/GeoServerEnvironmentTest.java
- src/platform/src/test/resources/org/geoserver/platform/GeoServerTesting.properties
[![GEOS-10434](https://badgen.net/badge/JIRA/GEOS-10434/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10434)
Early backport request was sent to devel list and has been approved.
* [GEOS-10434] Externalized geoserver-environment.properties.
Co-authored-by: Yashwanth Anand S <yashwanthanands@outlook.com>
> [2.20.x backport][GEOS-10434]-Externalized geoserver-environment.properties

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/gs/ImportProcess.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/ImportProcessTest.java
[![GEOS-10427](https://badgen.net/badge/JIRA/GEOS-10427/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10427)
This PR adds a check to ensure that users executing the Import process have sufficient privileges to modify the target workspace.
> [GEOS-10427] Improve access check in ImportProcess

- doc/en/user/source/community/index.rst
Following several questions and issues raised by the community about missing dependencies when working with community modules and stable versions of GeoServer, try to make the documentation more explciit.
> Documentation - Add precision on community modules download availability

- src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
- src/extension/importer/core/src/test/java/org/geoserver/importer/ImporterDataTest.java
[![GEOS-10444](https://badgen.net/badge/JIRA/GEOS-10444/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10444)
Follow up on [GEOS-10444]
> [GEOS-10444]:Follow up on importer. do a copy of the replacing data file

- src/pom.xml
[![GEOS-10458](https://badgen.net/badge/JIRA/GEOS-10458/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10458)
Updating to latest jai-ext
> [GEOS-10458] Update jai-ext to 1.1.22

- src/pom.xml
[![GEOS-10458](https://badgen.net/badge/JIRA/GEOS-10458/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10458)
> [GEOS-10458] Update jai-ext to 1.1.22 (2.19.x)

- doc/en/user/source/extensions/importer/rest_reference.rst
- src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
- src/extension/importer/core/src/test/java/org/geoserver/importer/ImporterDataTest.java
[![GEOS-10444](https://badgen.net/badge/JIRA/GEOS-10444/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10444)
Backporting [GEOS-10444] to 2.20.x
> [Bkp-2.20.x][GEOS-10444]: Supporting REPLACE UpdateMode on rasters

- doc/en/user/source/extensions/importer/rest_reference.rst
- src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
- src/extension/importer/core/src/test/java/org/geoserver/importer/ImporterDataTest.java
[![GEOS-10444](https://badgen.net/badge/JIRA/GEOS-10444/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10444)
> [Backport-2.19.x][GEOS-10444]: Supporting REPLACE UpdateMode on rasters

- src/main/src/main/java/org/geoserver/ows/LanguageURLMangler.java
- src/main/src/test/java/org/geoserver/ows/LanguageURLManglerTest.java
- src/main/src/test/java/org/geoserver/ows/URLManglersTest.java
[![GEOS-10454](https://badgen.net/badge/JIRA/GEOS-10454/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10454)
[GEOS-10454] use raw kv params detached from servlet request because of tomcat request lifecycle that cause the reset of a finished request
> [GEOS-10454] Make LanguageUrl mangler using rawKvp instead of HttpServletRequest params

- src/extension/wps/wps-kml-ppio/src/test/resources/org/geoserver/wps/ppio/ogckml22.xsd
- src/extension/wps/wps-kml-ppio/src/test/resources/org/geoserver/wps/ppio/xAL.xsd
[![GEOS-10443](https://badgen.net/badge/JIRA/GEOS-10443/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10443)
@jodygarnett reported build failures that can be tracker to resolving a schema file from the network. 
Including the file among the sources, hopefully the test will now run offline.
> [GEOS-10443] Graduate kml-ppio to extension. Follow up, isolate tests from network

- src/community/release/ext-cog.xml
[![GEOS-10461](https://badgen.net/badge/JIRA/GEOS-10461/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10461)
The issue is happening because the packaging brings in a lot of Jackson jars that are not actually needed, and which in turn need more dependencies (which are missing, the jackson-dataformat-xml module needs the stax api and implementation, e.g. woodstox).
Checking what is actually needed by the plugin, in terms of Jackson, reports:
```
~/devel/git-gs/src/community/cog (cog_jackson_deps)> mvn dependency:tree -nsu -fae -Dscope=compile  | grep jackson
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.13.2:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.2:compile
[INFO] |     +- …
```
> [GEOS-10461] 2.20.x GeoServer startup failure with 503 error after adding  COG plugin

- src/main/src/main/java/org/geoserver/security/DataAccessLimits.java
- src/security/security-tests/src/test/java/org/geoserver/security/TestAccessLimitsSerialization.java
[![GEOS-1906](https://badgen.net/badge/JIRA/GEOS-1906/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-1906)
Fix serialization of filters when access on Layer configuration page
> [GEOS-1906] DataAccessLimits serialization issue

- src/extension/importer/core/src/main/java/org/geoserver/importer/DataStoreFormat.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/ImportTask.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/format/GMLFileFormat.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/format/GeoJSONFormat.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/format/KMLFileFormat.java
- src/extension/importer/core/src/test/java/org/geoserver/importer/ImporterTest.java
[![GEOS-10464](https://badgen.net/badge/JIRA/GEOS-10464/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10464)
made recalculate a constant
Changed constant to be more accurately named
cleanup
- [ x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect …
> [GEOS-10464] Improve logging and check for NPEs and other issues in Importer Module

- src/main/src/main/java/org/geoserver/logging/GeoServerXMLConfiguration.java
- src/main/src/main/java/org/geoserver/logging/LoggingUtils.java
> Address PMD violations on log4j branch

- src/community/release/ext-oauth2-openid-connect.xml
[![GEOS-10474](https://badgen.net/badge/JIRA/GEOS-10474/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10474)
This pr refact the assembly for open-id to import just the needed dependency.
> [GEOS-10474] OpenID Connect fails with error Provider for javax.xml.stream.XMLOutputFactory cannot be found

- src/community/release/ext-oauth2-openid-connect.xml
[![GEOS-10474](https://badgen.net/badge/JIRA/GEOS-10474/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10474)
* [GEOS-10474] OpenID Connect fails with error Provider for javax.xml.stream.XMLOutputFactory cannot be found
> [2.20.x backport][GEOS-10474] OpenID Connect fails with error Provider for javax.xml.stream.XMLOutputFactory cannot be found (#5837)

- src/extension/importer/core/src/main/java/org/geoserver/importer/DataStoreFormat.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/ImportTask.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/format/GMLFileFormat.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/format/GeoJSONFormat.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/format/KMLFileFormat.java
- src/extension/importer/core/src/test/java/org/geoserver/importer/ImporterTest.java
[![GEOS-10464](https://badgen.net/badge/JIRA/GEOS-10464/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10464)
made recalculate a constant
Changed constant to be more accurately named
cleanup
> [GEOS-10464] Improve logging and check for NPEs and other issues in Importer Module (2.20.x)

- src/extension/importer/core/src/main/java/org/geoserver/importer/DataStoreFormat.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/ImportTask.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/format/GMLFileFormat.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/format/GeoJSONFormat.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/format/KMLFileFormat.java
- src/extension/importer/core/src/test/java/org/geoserver/importer/ImporterTest.java
[![GEOS-10464](https://badgen.net/badge/JIRA/GEOS-10464/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10464)
made recalculate a constant
Changed constant to be more accurately named
cleanup
cleanup
> [GEOS-10464] Improve logging and check for NPEs and other issues in Importer Module (2.19.x)

- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceAccessManagerIntegrationTest.java
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceIntegrationTestSupport.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/GeoFenceConfigurationManagerTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/GeofenceAccessManagerTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/GeofenceAccessManager_WMTSLayerTest.java
[![GEOS-10074](https://badgen.net/badge/JIRA/GEOS-10074/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10074)
Backport #5109 to `2.19.x`
- Fix `GeoFenceAccessManager.isWorkspaceAdmin()`: When a user name is
not provided, using a `RuleFilter` with `SpecialFilterType.ANY`
instead of `SpecialFilterType.DEFAULT` results in admin access to all
workspaces that have an AdminRule set, regardless of the user/role.
- Add `AdminRule` tests, introduce `GeofenceIntegrationTestSupport`
class to group utility methods and setup/cleanup.
Update GeofenceAccessManager.java
> [backport 2.19.x][GEOS-10074] GeoFence "Admin rules" grant "ADMIN" access to unauthorized users

- doc/en/user/source/extensions/netcdf/netcdf.rst
- src/extension/netcdf/pom.xml
- src/pom.xml
- src/release/ext-netcdf.xml
[![GEOS-10483](https://badgen.net/badge/JIRA/GEOS-10483/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10483)
See ticket for details. Also fixes a couple of missing dependencies, not needed to use NetCDF files, but required for the indexer and migration tools described in the guide.
> [GEOS-10483] Improve documentation on how to setup a mosaic of NetCDF files

- src/main/src/main/java/org/geoserver/security/decorators/DefaultSecureCatalogFactory.java
- src/main/src/test/java/org/geoserver/security/decorators/DefaultSecureCatalogFactoryTest.java
[![GEOS-10430](https://badgen.net/badge/JIRA/GEOS-10430/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10430)
This PR contains a fix for failures in calling /rest/workspaces GET endpoint. Now, the WMS and WMTS store info are both supported.
JIRA ticket is: https://osgeo-org.atlassian.net/browse/GEOS-10430
> [GEOS-10430] REST API failures

- src/pom.xml
[![GEOS-10493](https://badgen.net/badge/JIRA/GEOS-10493/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10493)
Backport from main.
> [GEOS-10493] Upgrade to jai-ext 1.1.23 (20.x)

- src/pom.xml
[![GEOS-10493](https://badgen.net/badge/JIRA/GEOS-10493/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10493)
See ticket.
> [GEOS-10493] Upgrade to jai-ext 1.1.23

- src/pom.xml
[![GEOS-10493](https://badgen.net/badge/JIRA/GEOS-10493/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10493)
> [GEOS-10493] Upgrade to jai-ext 1.1.23 (21.x)

- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACService.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/SearchQuery.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/SearchTest.java
[![GEOS-10498](https://badgen.net/badge/JIRA/GEOS-10498/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10498)
Community module, just checking the are no build issues.
> [GEOS-10498] STAC API Search implementation looks for an intersection property in the request, while it should be intersects

- src/wfs/src/main/java/org/geoserver/wfs/xml/GML2OutputFormat.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/GML3OutputFormat.java
- src/wfs/src/test/java/org/geoserver/wfs/xml/GMLOutputFormatTest.java
Reverts geoserver/geoserver#5875
> Revert "[GEOS-10502] GML3 output is not pretty printed when pretty print is turned on in global settings."

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/QueryablesBuilder.java
- src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/QueryablesBuilderTest.java
[![GEOS-10486](https://badgen.net/badge/JIRA/GEOS-10486/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10486)
This PR fixes the problem that database `Date` and `Time` fields are incorrectly labeled as `date-time` in the `Queryables` response.
This means that in the `Queryables` response the `format` keyword for a database 
- `Date` field is now set to `date`
- `Time` field is now set to `time`
> [GEOS-10486] Correctly label `Date` and `Time` fields in the `Queryables response

- doc/en/user/source/extensions/wmts-multidimensional/usage.rst
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/DescribeDomainsTransformer.java
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/MultiDimensionalExtension.java
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/ComparableRange.java
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/CoverageDimensionsReader.java
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/Dimension.java
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/DimensionsUtils.java
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/HistogramUtils.java
- src/extension/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/VectorDimension.java
- src/extension/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/MultiDimensionalExtensionTest.java
- src/extension/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/TestsSupport.java
- src/extension/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/VectorElevationDimensionTest.java
- src/extension/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/VectorTimeDimensionTest.java
- src/extension/wmts-multi-dimensional/src/test/resources/TimeElevationWithStartEnd.properties
[![GEOS-10471](https://badgen.net/badge/JIRA/GEOS-10471/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10471)
* [GEOS-10471] WMTS MultiDim - Support also endAttribute
> [2.20.x backport] [GEOS-10471] WMTS MultiDim - Support also endAttribute (#5826)

- src/pom.xml
Bumping up imageio-ext version
> Updating to imageio-ext 1.3.13

- src/pom.xml
Bumping up imageio-ext to 1.4.5 for better S3 COG support (IAM ROLES support)
> Updating to imageio-ext-1.4.5

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/QueryablesBuilder.java
- src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/QueryablesBuilderTest.java
[![GEOS-10486](https://badgen.net/badge/JIRA/GEOS-10486/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10486)
* [GEOS-10486] Correctly label Date and Time fields
* [GEOS-10486] Resolve format violations
* [GEOS-10486] Add missing license 
> [2.20.x backport] [GEOS-10486] Correctly label `Date` and `Time` fields in the `Queryables` response (#5866)

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/QueryablesBuilder.java
- src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/QueryablesBuilderTest.java
[![GEOS-10486](https://badgen.net/badge/JIRA/GEOS-10486/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10486)
* [GEOS-10486] Correctly label Date and Time fields
* [GEOS-10486] Resolve format violations
* [GEOS-10486] Add missing license header
> [2.21.x backport] [GEOS-10486] Correctly label `Date` and `Time` fields in the `Queryables` response (#5866)

- src/gwc/pom.xml
- src/gwc/src/main/java/org/geoserver/gwc/GWC.java
- src/gwc/src/main/java/org/geoserver/gwc/layer/CatalogLayerEventListener.java
[![GEOS-10515](https://badgen.net/badge/JIRA/GEOS-10515/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10515)
This PR updates any remaining code in the GWC module that still uses the old commons-httpclient 3.1 library to use the newer httpclient.
> [GEOS-10515] Refactor commons-httpclient usage in the GWC module

- doc/en/developer/source/conf.py
- doc/en/user/source/conf.py
- doc/zhCN/user/source/conf.py
[![GEOS-10519](https://badgen.net/badge/JIRA/GEOS-10519/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10519)
See ticket.
> [GEOS-10519] Sphinx build failure with extlinks (new warnings in Sphinx build)

- doc/en/developer/source/conf.py
- doc/en/user/source/conf.py
- doc/zhCN/user/source/conf.py
[![GEOS-10519](https://badgen.net/badge/JIRA/GEOS-10519/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10519)
Backport from main 
> [GEOS-10519] Sphinx build failure with extlinks (new warnings in Sphinx build) (2.21.x)

- src/pom.xml
[![PR-5891](https://badgen.net/badge/JIRA/PR-5891/0052CC)](https://osgeo-org.atlassian.net/browse/PR-5891)
backport https://github.com/geoserver/geoserver/pull/5891 to 2.21.x
Bumps [spring-core](https://github.com/spring-projects/spring-framework) from 5.2.20.RELEASE to 5.2.22.RELEASE.
- [Release notes](https://github.com/spring-projects/spring-framework/releases)
- [Commits](https://github.com/spring-projects/spring-framework/compare/v5.2.20.RELEASE...v5.2.22.RELEASE)
---
updated-dependencies:
- dependency-name: org.springframework:spring-core
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
> [2.21.x] Bump spring-core from 5.2.20.RELEASE to 5.2.22.RELEASE in /src

- src/extension/wps/web-wps/src/main/resources/GeoServerApplication_fr.properties
- src/extension/wps/web-wps/src/main/resources/GeoServerApplication_ko.properties
- src/security/ldap/src/main/resources/GeoServerApplication_fr.properties
- src/web/core/src/main/resources/GeoServerApplication_fr.properties
- src/web/wcs/src/main/resources/GeoServerApplication_fr.properties
- src/web/wms/src/main/resources/GeoServerApplication_fr.properties
Regular sync of the translation work done in Transifex.
> Update of the translations from Transifex

- doc/en/google0de0c8ffb164bba6.html
See geoserver/geoserver#5785 (comment)
Not sure if/how this will show up in docs.geoserver.org; alternatively the template could have a meta tag added after this line: https://github.com/geoserver/geoserver/blob/6163bb454d920f583d5ef267dc8d6589bef1b015/doc/en/themes/geoserver/layout.html#L94
> Add google site verification file for https://docs.geoserver.org/

- src/wms/src/main/java/org/geoserver/wms/featureinfo/FreeMarkerTemplateManager.java
[![GEOS-10532](https://badgen.net/badge/JIRA/GEOS-10532/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10532)
Backporting GEOS-10532 to 2.21.x
> [Backport-2.21.x][GEOS-10532]: FreeMarkerTemplateManager a few changes for subclassing

- src/wfs/src/main/java/org/geoserver/wfs/DeleteElementHandler.java
- src/wfs/src/main/java/org/geoserver/wfs/UpdateElementHandler.java
- src/wfs/src/test/java/org/geoserver/wfs/TransactionTest.java
[![GEOS-10535](https://badgen.net/badge/JIRA/GEOS-10535/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10535)
Reverts geoserver/geoserver#5938
> Revert "[GEOS-10535] WFS Update request throw NPE on bad namespace"

- src/web/core/src/main/java/org/geoserver/web/admin/AbstractStatusPage.java
- src/web/core/src/main/java/org/geoserver/web/system/status/ConsoleInfoUtils.java
- src/web/core/src/main/java/org/geoserver/web/system/status/JVMConsolePanel.html
- src/web/core/src/main/java/org/geoserver/web/system/status/JVMConsolePanel.java
- src/web/core/src/main/resources/GeoServerApplication.properties
- src/web/core/src/test/java/org/geoserver/web/admin/StatusPageTest.java
- src/web/core/src/test/java/org/geoserver/web/system/status/JVMConsolePanelTest.java
[![GEOS-4613](https://badgen.net/badge/JIRA/GEOS-4613/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-4613)
Add new tab `JVM Console` under the Server Status page with the possibility to see and download dumps for Threads and Heap
> [GEOS-4613] - Expose more JVM statistics on the web gui

- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceAccessManagerIntegrationTest.java
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceIntegrationTestSupport.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/GeoFenceConfigurationManagerTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/GeofenceAccessManagerTest.java
- src/extension/geofence/src/test/java/org/geoserver/geofence/GeofenceAccessManager_WMTSLayerTest.java
[![GEOS-10074](https://badgen.net/badge/JIRA/GEOS-10074/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10074)
- Fix `GeoFenceAccessManager.isWorkspaceAdmin()`: When a user name is
not provided, using a `RuleFilter` with `SpecialFilterType.ANY`
instead of `SpecialFilterType.DEFAULT` results in admin access to all
workspaces that have an AdminRule set, regardless of the user/role.
- Add `AdminRule` tests, introduce `GeofenceIntegrationTestSupport`
class to group utility methods and setup/cleanup.
Update GeofenceAccessManager.java
> [2.20.x backport] [GEOS-10074] GeoFence "Admin rules" grant "ADMIN" access to unauthorized users

- src/pom.xml
[![GEOS-10562](https://badgen.net/badge/JIRA/GEOS-10562/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10562)
with better native memory management and support for macOS 13
> [GEOS-10562] Bump oshi-core from 5.8.6 to 6.2.0

- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteTest.java
- src/main/src/main/java/org/geoserver/config/GeoServerInfo.java
- src/main/src/main/java/org/geoserver/config/SettingsInfo.java
- src/main/src/main/java/org/geoserver/config/impl/GeoServerInfoImpl.java
- src/main/src/main/java/org/geoserver/config/impl/SettingsInfoImpl.java
- src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
- src/main/src/main/java/org/geoserver/ows/ProxifyingURLMangler.java
- src/main/src/test/java/org/vfny/geoserver/util/ResponseUtilsTest.java
- src/main/src/test/java/org/vfny/geoserver/util/URLProxifyingTest.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/AdminRequestTest.java
- src/web/core/src/main/java/org/geoserver/web/data/workspace/WorkspaceEditPage$SettingsPanel.html
- src/web/core/src/main/java/org/geoserver/web/data/workspace/WorkspaceEditPage.java
- src/web/core/src/main/resources/GeoServerApplication.properties
[![GEOS-10542](https://badgen.net/badge/JIRA/GEOS-10542/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10542)
This PR aims at adding a new checkbox on the workspace level to allow adding headers for the proxy URL. This will allow end users to override the disabled checkbox "Use headers for Proxy URL" on the global settings page, by checking this option per workspace.
> [GEOS-10542] Use headers for proxy URL on workspace level

- src/wms/src/main/java/org/geoserver/wms/describelayer/DescribeLayerTransformer.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DescribeLayerTest.java
[![GEOS-10539](https://badgen.net/badge/JIRA/GEOS-10539/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10539)
> [GEOS-10539] DescribeLayer typeName is no longer workspace qualified

- src/pom.xml
[![GEOS-10579](https://badgen.net/badge/JIRA/GEOS-10579/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10579)
#5995 upgraded to a version that may exhibit buggy behaviour on some localized Windows when trying to access performance counters, that should be fixed now.
> [GEOS-10579] Bump oshi-core from 6.2.0 to 6.2.1

- src/main/src/main/java/org/geoserver/config/GeoServerResourcePersister.java
- src/main/src/test/java/org/geoserver/config/GeoServerPersistersTest.java
[![GEOS-10570](https://badgen.net/badge/JIRA/GEOS-10570/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10570)
This PR adds a check to removeStyle to skip renaming the file if the style's filename points to a directory instead of a regular file.
> [GEOS-10570] Deleting a style in a Hazelcast cluster renames the styles directory

- doc/en/user/source/configuration/tools/bulk/index.rst
> Fix spelling

- src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/pom.xml
[![GEOS-10567](https://badgen.net/badge/JIRA/GEOS-10567/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10567)
Failures on openid-web tests after refactoring due GEOS-10567. A depedency was skipped when refactoring.
> [GEOS-10567] failing tests on openid web submodule

- src/extension/wmts-multi-dimensional/src/main/resources/GeoServerApplication_fr.properties
- src/web/core/src/main/resources/GeoServerApplication_fr.properties
> Synchronize translation with Transifex content

- src/pom.xml
[![GEOS-10585](https://badgen.net/badge/JIRA/GEOS-10585/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10585)
see https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.48.v20220622
replaces / closes #6039 (Jetty 10 requires Java 11)
> [GEOS-10585] Upgrade to Jetty from 9.4.44 to 9.4.48

- src/pom.xml
Use an up-2-date version of the OWASP dependency scanner plugin
> Bump org.owasp:dependency-check-maven from 7.0.4 to 7.1.1

- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/reader/CatalogFileReader.java
- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/reader/CatalogMultiResourceItemReader.java
- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/writer/CatalogFileWriter.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/gwc/gridset/MapMLGridsets.java
- src/gwc/src/main/java/org/geoserver/gwc/config/GeoserverXMLResourceProvider.java
- src/gwc/src/main/java/org/geoserver/gwc/layer/CatalogConfiguration.java
- src/gwc/src/main/java/org/geoserver/gwc/layer/DefaultTileLayerCatalog.java
- src/main/src/main/java/org/geoserver/GeoserverInitStartupListener.java
- src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
- src/main/src/main/java/org/geoserver/logging/LoggingUtilsDelegate.java
- src/main/src/main/java/org/geoserver/security/IncludeQueryStringAntPathRequestMatcher.java
- src/main/src/main/java/org/geoserver/security/RESTfulDefinitionSource.java
- src/main/src/main/java/org/geoserver/security/RESTfulPathBasedFilterInvocationDefinitionMap.java
- src/main/src/main/java/org/geoserver/system/status/OSHISystemInfoCollector.java
- src/platform/src/main/java/org/geoserver/platform/GeoServerResourceLoader.java
- src/security/ldap/src/main/java/org/geoserver/security/ldap/BindingLdapAuthoritiesPopulator.java
- src/security/ldap/src/main/java/org/geoserver/security/ldap/GeoserverLdapBindAuthenticator.java
- src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayersPage.java
[![GEOS-10533](https://badgen.net/badge/JIRA/GEOS-10533/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10533)
Also cut back on shutdown messages
Message on the management of threads and calling of destroy() are intended for developers and have been reduced to fine logging level.
See also https://github.com/GeoWebCache/geowebcache/pull/1073
> [GEOS-10533] Review startup warning, info and config logging

- doc/en/user/source/datadirectory/configtemplate.rst
> Fix spelling & capitalisation

- doc/en/user/source/data/database/sqlview.rst
- src/main/src/main/java/applicationContext.xml
- src/ows/pom.xml
- src/ows/src/main/java/org/geoserver/ows/kvp/CharSeparatedViewParamsFormatParser.java
- src/ows/src/main/java/org/geoserver/ows/kvp/ViewParamsFormatParser.java
- src/ows/src/main/java/org/geoserver/ows/kvp/ViewParamsKvpParser.java
- src/ows/src/main/java/org/geoserver/ows/kvp/XMLViewParamsFormatParser.java
- src/ows/src/main/java/org/geoserver/ows/kvp/view/LayerParams.java
- src/ows/src/main/java/org/geoserver/ows/kvp/view/Parameter.java
- src/ows/src/main/java/org/geoserver/ows/kvp/view/ViewParamsRoot.java
- src/ows/src/main/java/org/geoserver/ows/kvp/view/XMLViewParamsUtils.java
- src/wfs/src/test/java/org/geoserver/wfs/SQLViewTest.java
- src/wfs/src/test/java/org/geoserver/wfs/kvp/GetFeatureKvpRequestReaderTest.java
- src/wms/src/test/java/org/geoserver/wms/map/GetMapKvpRequestReaderTest.java
[![GEOS-10591](https://badgen.net/badge/JIRA/GEOS-10591/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10591)
JIRA issue:  
https://osgeo-org.atlassian.net/browse/GEOS-10591
XML view parameters alternative format implementation.
> [GEOS-10591] XML view params format implementation

- src/community/pom.xml
- src/community/release/ext-stac-datastore.xml
- src/community/release/pom.xml
- src/pom.xml
- src/web/app/pom.xml
Packaging for the gt-stac-store module.
> STAC datastore nightly build packaging

- doc/en/user/source/extensions/geofence-server/index.rst
- doc/en/user/source/extensions/geofence-server/rest-batch-op.rst
- src/extension/geofence-server/src/main/java/org/geoserver/geofence/server/rest/BatchRestController.java
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/rest/BatchRestControllerTest.java
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/rest/RulesRestControllerTest.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/rest/xml/AbstractPayload.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/rest/xml/Batch.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/rest/xml/BatchOperation.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/rest/xml/JaxbAdminRule.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/rest/xml/JaxbRule.java
- src/extension/geofence/src/main/java/org/geoserver/geoserver/xstream/BatchOpXtreamConverter.java
- src/extension/geofence/src/main/java/org/geoserver/geoserver/xstream/GeoFenceXStreamPersisterInitializer.java
- src/extension/geofence/src/main/resources/applicationContext.xml
- src/extension/geofence/src/test/java/org/geoserver/geoserver/xstream/GeofencePersisterSerializationTest.java
- src/extension/geofence/src/test/resources/org/geoserver/geoserver/xstream/batch.json
- src/extension/geofence/src/test/resources/org/geoserver/geoserver/xstream/batch.xml
[![GEOS-10507](https://badgen.net/badge/JIRA/GEOS-10507/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10507)
* [GEOS-10507] GeoFence Internal - Support Batch operations for Rules and AdminRules
* Minor improvements to rst doc
* fix qa failure
Co-authored-by: Emanuele Tajariol <e.tajariol@gmail.com>
Co-authored-by: Emanuele Tajariol <e.tajariol@gmail.com>
> [2.21.x backport][GEOS-10507] GeoFence Internal - Support Batch operations for Rules and AdminRules

- doc/en/user/source/gettingstarted/postgis-quickstart/index.rst
- doc/en/user/source/gettingstarted/shapefile-quickstart/index.rst
This is a quick typo in the documentation fix for `a identifier` to `an identifier` in two spots in the getting started documentation.  
> typo: `a identifier` to `an identifier`

- src/main/src/test/java/org/geoserver/logging/TestAppender.java
- src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapIntegrationTest.java
[![GEOS-10608](https://badgen.net/badge/JIRA/GEOS-10608/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10608)
> [bkp-2.21.x][GEOS-10608]:Stop flooding logs with InvalidDate (and similar) at Severe

- src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapIntegrationTest.java
[![GEOS-10608](https://badgen.net/badge/JIRA/GEOS-10608/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10608)
> [bkp-2.20.x][GEOS-10608]:Stop flooding logs with InvalidDate (and similar) at Severe

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/catalog/JDBCCatalogFacade.java
- src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/catalog/CatalogImplWithJDBCFacadeTest.java
[![GEOS-10609](https://badgen.net/badge/JIRA/GEOS-10609/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10609)
This PR introduces a fix for the reported issue:
https://osgeo-org.atlassian.net/browse/GEOS-10609
"We found an issue when GeoServer use JDBC config catalog implementation, making it unable to use a workspace based style without using the prefix.  JDBC config catalog should follow the same business logic as the default GeoServer catalog implementation."
> [GEOS-10609][2.20.x backport] Fix Issue retrieving a workspace style without prefix on JDBCConfig

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/catalog/JDBCCatalogFacade.java
- src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/catalog/CatalogImplWithJDBCFacadeTest.java
[![GEOS-10609](https://badgen.net/badge/JIRA/GEOS-10609/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10609)
This PR introduces a fix for the reported issue:
https://osgeo-org.atlassian.net/browse/GEOS-10609
"We found an issue when GeoServer use JDBC config catalog implementation, making it unable to use a workspace based style without using the prefix.  JDBC config catalog should follow the same business logic as the default GeoServer catalog implementation."
> [GEOS-10609][2.21.x backport] Fix Issue retrieving a workspace style without prefix on JDBCConfig

- src/community/oseo/oseo-integration-tests/pom.xml
- src/community/oseo/oseo-integration-tests/src/test/java/org/geoserver/oseo/test/RESTIntegrationTest.java
- src/community/oseo/oseo-rest/src/test/java/org/geoserver/opensearch/rest/OSEORestTestSupport.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACOseoListener.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/SampleFeatures.java
- src/community/oseo/pom.xml
[![GEOS-10617](https://badgen.net/badge/JIRA/GEOS-10617/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10617)
See ticket
> [GEOS-10617] STAC module will throw exception on creation of a new collection

- src/pom.xml
[![GEOS-10620](https://badgen.net/badge/JIRA/GEOS-10620/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10620)
> [GEOS-10620] Update oshi to 6.2.2 to support Apple M2 CPU

- src/community/release/ext-saml.xml
- src/community/saml/pom.xml
- src/extension/importer/rest/pom.xml
- src/main/pom.xml
[![GEOS-10462](https://badgen.net/badge/JIRA/GEOS-10462/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10462)
This PR attempts to remove the old commons-httpclient dependency from the main GeoServer package.  commons-httpclient is removed from the main module, added to the Importer extension as a test dependency and added to the SAML community module.  Assuming that there aren't any unexpected transitive dependencies, commons-httpclient should only be included when the SAML module is installed.
> [GEOS-10462] Upgrade commons-httpclient 3.1 to org.apache.httpcomponents:httpclient:4.5.13

- doc/en/user/source/services/wms/googleearth/features/customizingplacemarks.rst
[![GEOS-10615](https://badgen.net/badge/JIRA/GEOS-10615/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10615)
The workspace wide templates are stored in the same 'workspaces' folder as the layer specific templates.
> [GEOS-10615] Fix KML placemark template path in documentation

- src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java
- src/main/src/test/java/org/geoserver/security/impl/DefaultResourceAccessManagerTest.java
- src/web/core/src/main/java/org/geoserver/web/WorkspaceAdminComponentAuthorizer.java
[![GEOS-10607](https://badgen.net/badge/JIRA/GEOS-10607/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10607)
Whenever a user has been assigned to two roles, or even the same role, and one of those roles has ".admin" power on some data, while the other (or even the same) has ".write" power on the data, whenever you click on the "Layer Preview" link the others disappear.  
We add a new check to make sure that admin access is taken into account when retrieving Workspace Access limits.
> [GEOS-10607] Links disappearing for the Admin user

- doc/en/user/source/styling/ysld/cookbook/lines.rst
Incorrect YSLD line cookbook examples - "stroke-graphic-stroke" should be "stroke-graphic".
Cook book example YSLD for stroke graphics was incorrect, does not work!  
> Fix cookbook YSLD line examples

- doc/en/user/source/styling/ysld/cookbook/artifacts/line_dashdot.ysld
- doc/en/user/source/styling/ysld/cookbook/artifacts/line_dashspace.ysld
- doc/en/user/source/styling/ysld/cookbook/artifacts/line_railroad.ysld
Cookbox example files have "stroke-graphic-stroke", should be just "stroke-graphic".
> Cookbook YSLD line example files fix

- src/main/pom.xml
- src/pom.xml
- src/web/core/src/main/java/org/geoserver/web/EmailAddressValidator.java
- src/web/core/src/main/java/org/geoserver/web/GeoServerHomePage.java
- src/web/core/src/main/java/org/geoserver/web/StringAndInternationalStringPanel.java
- src/web/core/src/main/java/org/geoserver/web/admin/ContactPanel.java
- src/web/core/src/test/java/org/geoserver/web/EmailAddressValidatorTest.java
In this PR, we preform output encoding to protect against XSS attacks. Furthermore, we do validation on the email field to reduce the risk of attacks. Several techniques, to protect against these attacks can be found here: https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html 
> [GEOS-10598] XSS vulnerability in the email address field

- src/gwc/src/main/java/org/geoserver/gwc/GWC.java
- src/gwc/src/test/java/org/geoserver/gwc/GWCTest.java
[![GEOS-10628](https://badgen.net/badge/JIRA/GEOS-10628/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10628)
The GWC properties are always null on startup as they do not get synced with geoserver properties. Hence added a check to sync gwc properties when they are null.
> [GEOS-10628] GWC Environment parameterization does not work on geoserver startup

- src/main/pom.xml
- src/pom.xml
- src/web/core/src/main/java/org/geoserver/web/EmailAddressValidator.java
- src/web/core/src/main/java/org/geoserver/web/GeoServerHomePage.java
- src/web/core/src/main/java/org/geoserver/web/StringAndInternationalStringPanel.java
- src/web/core/src/main/java/org/geoserver/web/admin/ContactPanel.java
- src/web/core/src/test/java/org/geoserver/web/EmailAddressValidatorTest.java
> [GEOS-10598] XSS vulnerability in the email address field (2.20.x backport)

- doc/en/api/1.0.0/coverages.yaml
- doc/en/api/1.0.0/coveragestores.yaml
- doc/en/api/1.0.0/datastores.yaml
- doc/en/api/1.0.0/featuretypes.yaml
- src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java
- src/main/src/main/java/org/geoserver/catalog/CoverageDimensionCustomizerReader.java
- src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/AbstractCatalogController.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/CoverageController.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/CoverageStoreController.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/DataStoreController.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/FeatureTypeController.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/CatalogRESTTestSupport.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/CoverageControllerTest.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/CoverageStoreControllerTest.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/DataStoreControllerTest.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/FeatureTypeControllerTest.java
- src/web/core/src/main/java/org/geoserver/web/data/resource/CoverageBandsConfigurationPanel.java
[![GEOS-10610](https://badgen.net/badge/JIRA/GEOS-10610/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10610)
Authorization to merge pending on devel-list
> [2.21.x backport] [GEOS-10610] Selective cache reset on stores and resources, via REST API

- doc/en/user/source/tutorials/georss/georss.rst
> Trivial typo fix in GeoRSS tutorial

- doc/en/user/source/extensions/geofence/configuration.rst
- src/extension/geofence-server/src/test/java/org/geoserver/geofence/integration/GeofenceGetMapIntegrationTest.java
- src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
- src/pom.xml
[![GEOS-10625](https://badgen.net/badge/JIRA/GEOS-10625/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10625)
Improve role filtering in GeoFence (see https://github.com/geoserver/geofence/issues/222)
Needs GeoFence 3.5.1 (PR https://github.com/geoserver/geofence/pull/223)
> [GEOS-10625] GeoFence: improve filtering by role

- src/main/src/main/java/org/geoserver/config/impl/GeoServerInfoImpl.java
- src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
- src/main/src/test/java/org/geoserver/config/util/XStreamPersisterIntegrationTest.java
- src/main/src/test/resources/org/geoserver/config/util/global.xml
[![GEOS-10636](https://badgen.net/badge/JIRA/GEOS-10636/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10636)
See ticket for details. @mprins any chance you can do a round of interactive testing to this one? I don't have a ready to use proxy server on my dev machine.
> [GEOS-10636] (proxied) Login is broken after upgrade to 2.22-M0 and 2.21.1

- src/main/src/main/java/org/vfny/geoserver/global/GeoServerFeatureSource.java
[![GEOT-7219](https://badgen.net/badge/JIRA/GEOT-7219/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7219)
Working on https://github.com/geotools/geotools/pull/4014 I've made a trivial fix to Query, that used to clone hints by shallow copy, and that caused a downstream build failure in GeoServer.. There is a one-liner bug in GeoServer that depends on that shallow copy to work... this PR fixes it.
I don't see a way to write a test for it until Query is modified, because changing either Query object will modify the same shared hints, but once the GeoTools PR is merged, then a test in GeoServer will fail (GetFeatureCurvesTest.testLinearizeWFS10).
> Follow up to GEOT-7219

- src/community/release/ext-cog.xml
[![GEOS-10642](https://badgen.net/badge/JIRA/GEOS-10642/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10642)
> [GEOS-10642]: Follow up - update zip packaging for cog community module

- src/main/src/main/java/org/geoserver/security/concurrent/LockingRoleService.java
- src/main/src/main/java/org/geoserver/security/concurrent/LockingUserGroupService.java
- src/main/src/main/java/org/geoserver/security/xml/XMLRoleService.java
- src/restconfig/src/main/java/org/geoserver/rest/security/UsersRestController.java
- src/restconfig/src/main/java/org/geoserver/rest/security/xml/JaxbUser.java
- src/restconfig/src/test/java/org/geoserver/rest/security/SequentialExecutionControllerTest.java
[![GEOS-10671](https://badgen.net/badge/JIRA/GEOS-10671/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10671)
See ticket
> [GEOS-10671] Parallel REST API calls failures (users)

- src/extension/feature-pregeneralized/src/main/java/org/geoserver/data/gen/info/GeneralizationInfosProviderImpl.java
- src/extension/feature-pregeneralized/src/test/java/org/geoserver/data/gen/ModuleStatusTest.java
- src/extension/feature-pregeneralized/src/test/java/org/geoserver/data/gen/PreGeneralizedDataStoreFactoryTest.java
- src/extension/feature-pregeneralized/src/test/resources/geninfo1.xml
[![GEOS-10622](https://badgen.net/badge/JIRA/GEOS-10622/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10622)
The goal of this PR is to make the pregeneralized feature datastore compatible with the JDBCStore.
> [GEOS-10622] PregeneralizedFeature extension does not work with JDBCStore

- src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/WCSMultiDimSubsetTest.java
- src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/WCSNetCDFMosaicTest.java
- src/extension/wcs2_0-eo/core/src/main/java/org/geoserver/wcs2_0/eo/response/GranuleCoverageInfo.java
- src/main/src/test/java/org/geoserver/data/test/SystemTestData.java
- src/wcs/pom.xml
- src/wcs/src/main/java/org/vfny/geoserver/util/WCSUtils.java
- src/wcs/src/test/java/org/vfny/geoserver/util/WCSUtilsTest.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/GetCoverage.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/GMLTransformer.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCS20DescribeCoverageTransformer.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCS20GetCapabilitiesTransformer.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCSDefaultValuesHelper.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCSDimensionsSubsetHelper.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/util/RequestUtils.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/GetCoverageTest.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/WCSTestSupport.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/DescribeCoverageTest.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/GetCapabilitiesTest.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/GetCoverageKvpTest.java
[![GEOS-10684](https://badgen.net/badge/JIRA/GEOS-10684/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10684)
> [GEOS-10684] WCS 2.0 is ignoring declared bounds and CRS

- src/web/core/src/main/java/org/geoserver/web/ServiceDescriptionProvider.java
- src/web/gwc/src/main/java/org/geoserver/gwc/web/GWCServiceDescriptionProvider.java
- src/web/wcs/src/main/java/org/geoserver/wcs/web/WCSServiceDescriptionProvider.java
- src/web/wfs/src/main/java/org/geoserver/wfs/web/WFSServiceDescriptionProvider.java
[![GEOS-10647](https://badgen.net/badge/JIRA/GEOS-10647/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10647)
This fixes some issues on the Geoserver Home (welcome) page.
1. There were some minor issues with the urls - see https://osgeo-org.atlassian.net/browse/GEOS-10647
2. Sometime the same service would appear twice
3. For GWC-based services, it was sometimes thinking the service wasn't enabled when it was (isAvalable)
4. Urls for GWC-based getcapabilities were incorrect
- [n/a] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [n/a] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing …
> [GEOS-10647]fixes for issues with welcome/home page

- src/community/monitor-hibernate/pom.xml
- src/community/taskmanager/core/bin/pom.xml
- src/extension/geofence-server/pom.xml
- src/pom.xml
This PR covers fixes/improvements when changing to Java 11 as my daily driver:
Despite increasing ulimit -n value a full build will encounter "too many open files". 
These are non-functional changes to the build system only and may be back ported.
- [ x I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
> Just build please: address too many open files and use of osgeo-releases for third-party jars

- doc/en/user/source/extensions/vectortiles/tutorial.rst
[![GEOS-10658](https://badgen.net/badge/JIRA/GEOS-10658/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10658)
This PR contains integrations in Geoserver docs to include an example for creating an OpenLayers map using Geoserver, Openlayers with a on overlay vectortiles based layer using WMS 
> [GEOS-10658] - Added OpenLayers example using vectortiles in WMS for vector tiles tutorial

- src/web/wcs/pom.xml
[![GEOS-10706](https://badgen.net/badge/JIRA/GEOS-10706/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10706)
See ticket for description.
> [GEOS-10706] Maven reports a duplicate declaration of dependency in web/wcs

- src/pom.xml
[![CVE-2022](https://badgen.net/badge/JIRA/CVE-2022/0052CC)](https://osgeo-org.atlassian.net/browse/CVE-2022)
commons-text fixed CVE-2022-42889; this is not a vulnerability that applies to GeoServer as GeoServer does not use the vulnerable `StringLookup` class.
> Bump org.apache.commons:commons-text from 1.9 to 1.10.0

- doc/en/developer/source/programming-guide/testing/index.rst
> add note on how to add a custom layer to the developer manual

- src/main/src/main/resources/DEFAULT_LOGGING.xml
- src/main/src/main/resources/GEOSERVER_DEVELOPER_LOGGING.xml
- src/main/src/main/resources/GEOTOOLS_DEVELOPER_LOGGING.xml
- src/main/src/main/resources/PRODUCTION_LOGGING.xml
- src/main/src/main/resources/QUIET_LOGGING.xml
- src/main/src/main/resources/TEST_LOGGING.xml
- src/main/src/main/resources/VERBOSE_LOGGING.xml
- src/main/src/test/java/org/geoserver/logging/LoggingStartupContextListenerTest.java
[![GEOS-10701](https://badgen.net/badge/JIRA/GEOS-10701/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10701)
See ticket.
> [GEOS-10701] Logging profiles timestamp reports minutes where it should report months

- src/main/src/main/java/org/geoserver/security/SecuredResourceNameChangeListener.java
- src/main/src/main/java/org/geoserver/security/impl/AbstractAccessRuleDAO.java
- src/main/src/main/java/org/geoserver/security/impl/DataAccessRule.java
- src/main/src/main/java/org/geoserver/security/impl/DataAccessRuleDAO.java
- src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java
- src/main/src/main/java/org/geoserver/security/impl/RESTAccessRuleDAO.java
- src/main/src/main/java/org/geoserver/security/impl/ServiceAccessRuleDAO.java
- src/security/security-tests/src/test/java/org/geoserver/security/impl/AbstractAccesRuleDAOConcurrencyTest.java
- src/security/security-tests/src/test/java/org/geoserver/security/impl/DataAccesRuleDAOConcurrencyTest.java
- src/security/security-tests/src/test/java/org/geoserver/security/impl/RESTAccessRuleDAOTest.java
- src/security/security-tests/src/test/java/org/geoserver/security/impl/ServiceAccessRuleDAOTest.java
[![GEOS-10711](https://badgen.net/badge/JIRA/GEOS-10711/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10711)
> [GEOS-10711] ConcurrentModificationException can happen while modifying data access rules with concurrent WMS traffic

- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/request/TemplatePathVisitor.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/request/TemplatePathVisitorTest.java
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/request/testTemplateBackwardMapping.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/MappedFeatureStreamFun.json
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/GeoJSONGetComplexFeaturesResponseWFSTest.java
[![GEOS-10710](https://badgen.net/badge/JIRA/GEOS-10710/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10710)
> [GEOS-10710] Features Templating backward mapping with back xpath ('../my/property/name') doesn't work

- src/web/gwc/src/main/java/org/geoserver/gwc/web/GWCServiceDescriptionProvider.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/GWCServiceLinksTest.java
[![GEOS-10647](https://badgen.net/badge/JIRA/GEOS-10647/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10647)
The GWC-based getcapabilities links were using "services=" instead of "service=" (plural).
This PR fixes that typo.
cf https://osgeo-org.atlassian.net/browse/GEOS-10647
- [n/a] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [n/a] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
> [GEOS-10647] Welcome page links to GetCapabilities do not follow the OGC standards

- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectFilterConfig.java
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdConnectIntegrationTest.java
[![GEOS-10718](https://badgen.net/badge/JIRA/GEOS-10718/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10718)
References: https://osgeo-org.atlassian.net/browse/GEOS-10718
> [Fixes GEOS-10718] the OIDC plugin does not currently take into account the id_token_hint parameter

- src/web/core/pom.xml
- src/web/core/src/main/java/org/geoserver/web/data/layer/SQLViewAbstractPage.java
- src/web/core/src/test/java/org/geoserver/web/data/layer/SqlViewEditPageTest.java
[![GEOS-4727](https://badgen.net/badge/JIRA/GEOS-4727/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-4727)
See ticket
> [GEOS-4727] Editing SQL views seems to be leaking connections

- doc/en/user/source/data/database/oracle.rst
- src/wfs/src/main/java/org/geoserver/wfs/xml/FeatureTypeSchemaBuilder.java
- src/wfs/src/test/java/org/geoserver/wfs/xml/FeatureTypeInfoSchemaBuilderTest.java
[![GEOS-10716](https://badgen.net/badge/JIRA/GEOS-10716/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10716)
> [GEOS-10716] Build simple feature types schema using column descriptions if available

- src/community/oseo/oseo-rest/src/test/java/org/geoserver/opensearch/rest/ProductsControllerTest.java
- src/community/oseo/oseo-rest/src/test/resources/productDate.json
[![GEOS-10736](https://badgen.net/badge/JIRA/GEOS-10736/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10736)
See ticket. 
Depends on https://github.com/geotools/geotools/pull/4101 (although build will likely be green, as community module tests are not run)
> [GEOS-10736] OSEO product creation via REST API fails if the product id starts with a valid ISO date

- src/extension/gwc-s3/src/main/java/org/geoserver/gwc/web/blob/S3BlobStorePanel.html
- src/extension/gwc-s3/src/main/java/org/geoserver/gwc/web/blob/S3BlobStorePanel.java
- src/extension/gwc-s3/src/test/java/org/geoserver/gwc/web/blob/S3BlobStorePageTest.java
- src/web/core/src/main/java/org/geoserver/web/data/store/PasswordTextFieldWriteOnlyModel.java
- src/web/core/src/main/java/org/geoserver/web/data/store/panel/PasswordParamPanel.java
[![GEOS-10735](https://badgen.net/badge/JIRA/GEOS-10735/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10735)
> [GEOS-10735] Obfuscate secret key in S3 Blob Store, avoiding requiring reentry when editing and HTML source visibility

- src/restconfig/src/main/java/org/geoserver/rest/security/AbstractAclController.java
[![GEOS-10729](https://badgen.net/badge/JIRA/GEOS-10729/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10729)
Follows up to https://github.com/geoserver/geoserver/pull/6318, with more concurrency fixes. I could not write a test, runnable in the build, that would successfully replicate the issue. I have a large integration one, that works against tens of thousands of rules, and tens of concurrent threads, that managed to make the issue occur a handful of times over the course of a 30 minutes run. After these fixes, I cannot get it to lose rules anymore (finger crossed).
For reference, here is the test class I've used (it's really a REST client talking to a live GeoServer):
https://gist.github.com/aaime/4bc441ece59a7cb31a0abf71110a5d51
> [GEOS-10729] Concurrent access on data access rules (authorization) can lead to loss of configured catalog mode, and lost rules. Follow up, more fixes

- doc/en/developer/source/quickstart/intellij.rst
> Update capitalisation and other minor changes

- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/GMLTransformer.java
[![GEOS-10755](https://badgen.net/badge/JIRA/GEOS-10755/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10755)
This PR refactors code in the WCS 2.0 module that was using string concatenation to build XML output.  The existing unit test cover the changes in this PR.
> [GEOS-10755] WCS 2.0 module should not use string concatenation to build XML

- doc/en/user/source/data/database/oracle.rst
- src/wfs/src/main/java/org/geoserver/wfs/xml/FeatureTypeSchemaBuilder.java
- src/wfs/src/test/java/org/geoserver/wfs/xml/FeatureTypeInfoSchemaBuilderTest.java
[![GEOS-10716](https://badgen.net/badge/JIRA/GEOS-10716/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10716)
2.21.x backport
…descriptions, when available
unit test
documentation
PR Cleanup
pr update doc link
> [Geos-10716] build simple feature types schema using column descriptions (2.21.x)

- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLController.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLDocumentBuilder.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLControllerTest.java
[![GEOS-10773](https://badgen.net/badge/JIRA/GEOS-10773/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10773)
> [GEOS-10773] Enable localized MapML responses

- doc/en/user/source/installation/upgrade.rst
> Fixed broken URL

- src/pom.xml
[![GEOS-10775](https://badgen.net/badge/JIRA/GEOS-10775/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10775)
Minor version bump of xmlunit from 1.3 to 1.6, which is the latest in the 1.x branch. Migration to 2.x is a larger task.
> [GEOS-10775] Update xmlunit to 1.6

- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectFilterConfig.java
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectSecurityConfiguration.java
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/ValidatingOAuth2RestTemplate.java
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.html
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.java
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/resources/GeoServerApplication.properties
- src/community/security/oauth2/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuth2FilterConfig.java
- src/community/security/oauth2/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilter.java
- src/community/security/oauth2/oauth2-core/src/main/java/org/geoserver/security/oauth2/OAuth2FilterConfig.java
[![GEOS-10738](https://badgen.net/badge/JIRA/GEOS-10738/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10738)
This adds some logging for troubleshooting OIDC issues.
Adds button on UI to turn on the logging.  If this is turned on, then more logging will take place (turn on VERBOSE logging).
This attempts to not log too sensitive information - 
+ CODE is logged AFTER its been used (its single-use)
+ JWT ID/ACCESS tokens only log the Claims (not the header/signature)
+ non-JWT tokens are not logged (that would be insecure)
+ some personal information will likely be logged (i.e. token claims include email/name/etc...)
Do not turn this on in a production environment.
- [n/a] New unit tests have been added covering the changes.
- [n/a] …
> GEOS-10738 Better logging for OIDC

- doc/en/user/source/community/taskmanager/user.rst
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/data/Batch.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/data/LatestBatchRun.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/data/TaskManagerDao.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/data/impl/BatchImpl.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/data/impl/LatestBatchRunImpl.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/data/impl/RunImpl.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/data/impl/TaskManagerDaoImpl.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/impl/FileReferenceImpl.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/impl/PostgisDialectImpl.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/schedule/BatchJobService.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/schedule/impl/BatchJobImpl.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/schedule/impl/BatchJobServiceImpl.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/schedule/impl/BatchJobServiceStarter.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/tasks/AbstractRemotePublicationTaskTypeImpl.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/tasks/DbRemotePublicationTaskTypeImpl.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/tasks/FileRemotePublicationTaskTypeImpl.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/tasks/MetadataSyncTaskTypeImpl.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/util/CatalogUtil.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/web/model/BatchesModel.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/web/panel/BatchesPanel.java
- src/community/taskmanager/core/src/main/resources/applicationContext.xml
- src/community/taskmanager/core/src/test/java/org/geoserver/taskmanager/tasks/CopyTableTaskTest.java
- src/community/taskmanager/core/src/test/java/org/geoserver/taskmanager/tasks/FileRemotePublicationTaskTest.java
- src/community/taskmanager/core/src/test/java/org/geoserver/taskmanager/tasks/MetaDataSyncTaskTest.java
- src/community/taskmanager/core/src/test/java/org/geoserver/taskmanager/tasks/TimestampTaskTest.java
This community module is no longer in initial development stage so from now on individual issues will be logged in jira for tracking purposes.
> Taskmanager community module: upgrade PR

- doc/en/user/source/security/usergrouprole/roleservices.rst
- doc/en/user/source/security/webadmin/settings.rst
> Make finding how to set the default role service easier

- src/platform/src/main/java/org/geoserver/platform/ServiceException.java
- src/wms/src/main/java/org/geoserver/wms/WMSInfo.java
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/BufferedImageLegendGraphicBuilder.java
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/ColorMapLegendCreator.java
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/ImageList.java
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/ImageQueue.java
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendGraphicBuilder.java
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendMerger.java
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/RasterLayerLegendHelper.java
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/Tally.java
- src/wms/src/main/java/org/geoserver/wms/map/RenderedImageMapOutputFormat.java
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/ImageListTest.java
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/ImageQueueTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetLegendGraphicTest.java
[![GEOS-10632](https://badgen.net/badge/JIRA/GEOS-10632/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10632)
Supercedes https://github.com/geoserver/geoserver/pull/6130
> [GEOS-10632] Make sure GetLegendGraphics honors the WMS memory service limits

- src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/WCSTestSupport.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/DescribeCoverageTest.java
[![GEOS-10808](https://badgen.net/badge/JIRA/GEOS-10808/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10808)
The following two tests show differences in floating point implementation on ARM / Apple M1. Switch to using assertEquals(expected,actual,delta) rather than string comparison.
There is no functional change here.
> [GEOS-10808] Relax reprojection delta for IEEE differences on M1

- doc/en/developer/source/translation.rst
[![GEOS-10798](https://badgen.net/badge/JIRA/GEOS-10798/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10798)
update outdated url http://sphinx.pocoo.org/ to
https://www.sphinx-doc.org/
Closes #GEOS-10798
> [GEOS-10798] [Sphinx site url](http://sphinx.pocoo.org/) is outdate

- src/pom.xml
[![GEOS-10812](https://badgen.net/badge/JIRA/GEOS-10812/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10812)
Micro version dependency bump (we currently have ~~1.5.1~~ 1.5.2).
Obsoletes #6468.
> [GEOS-10812] Update Jettison to 1.5.3

- src/pom.xml
[![GEOS-10812](https://badgen.net/badge/JIRA/GEOS-10812/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10812)
backports #6469 
Co-authored-by: Mark Prins <1165786+mprins@users.noreply.github.com>
> [Backport 2.22.x][GEOS-10812] Update Jettion to 1.5.3 (#6469)

- src/community/gsr/src/test/java/org/geoserver/gsr/controller/ControllerTest.java
- src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/OGCApiTestSupport.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/ComplexFeaturesTest.java
- src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
[![GEOS-10816](https://badgen.net/badge/JIRA/GEOS-10816/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10816)
> [GEOS-10816] OGC API Features complex features test fails since introduction of <meta> tag in HTML templates

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/DbMappings.java
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/Dialect.java
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/FilterToCatalogSQL.java
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/OracleDialect.java
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/QueryBuilder.java
- src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/QueryBuilderTest.java
[![GEOS-10814](https://badgen.net/badge/JIRA/GEOS-10814/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10814)
This PR updates the JDBC Config module to use consistent capitalization and spacing in all of its SQL queries.
> [GEOS-10814] Update jdbc config to use consistent SQL formatting

- doc/en/user/source/data/raster/imagemosaic/configuration.rst
[![GEOS-10827](https://badgen.net/badge/JIRA/GEOS-10827/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10827)
Follow up on GeoTool updates
> [GEOS-10827] Document property selection in image mosaic

- doc/en/user/source/data/raster/imagemosaic/configuration.rst
Small clarifications on the usage of regular expressions and property file syntax.
> Clarification on mosaic property configuration files and regexes

- doc/en/user/source/services/generic_vendor_options.txt
- doc/en/user/source/services/wcs/vendor.rst
- doc/en/user/source/services/wfs/vendor.rst
- doc/en/user/source/services/wms/vendor.rst
[![GEOS-10841](https://badgen.net/badge/JIRA/GEOS-10841/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10841)
These options are provided as overrides by the dispatcher and are applicable to all open web service operations (as an override for the preference provided by response)
> [GEOS-10841] Docs for filename and content-disposition vendor options

- doc/en/user/source/services/generic_vendor_options.txt
- doc/en/user/source/services/wcs/vendor.rst
- doc/en/user/source/services/wfs/vendor.rst
- doc/en/user/source/services/wms/vendor.rst
[![GEOS-10841](https://badgen.net/badge/JIRA/GEOS-10841/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10841)
Backport #6541
> [Backport 2.22.x] [GEOS-10841] Docs for filename and content-disposition vendor options

- doc/en/user/source/services/generic_vendor_options.txt
- doc/en/user/source/services/wcs/vendor.rst
- doc/en/user/source/services/wfs/vendor.rst
- doc/en/user/source/services/wms/vendor.rst
[![GEOS-10841](https://badgen.net/badge/JIRA/GEOS-10841/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10841)
Backport #6541
> [Backport 2.21.x] [GEOS-10841] Docs for filename and content-disposition vendor options

- src/community/ogcapi/ogcapi-core/pom.xml
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/MappingJackson2HttpMessageConverter.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/MappingJackson2YAMLMessageConverter.java
- src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/ApiConfigurationSupportTest.java
- src/rest/src/main/java/org/geoserver/rest/converters/XStreamJSONMessageConverter.java
- src/rest/src/main/java/org/geoserver/rest/converters/XStreamXMLMessageConverter.java
[![GEOS-10828](https://badgen.net/badge/JIRA/GEOS-10828/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10828)
See ticket
> [GEOS-10828] OGC API - Features - Plugin breaks core /rest API with JSON payloads

- src/community/ogcapi/ogcapi-core/pom.xml
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/MappingJackson2HttpMessageConverter.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/MappingJackson2YAMLMessageConverter.java
- src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/ApiConfigurationSupportTest.java
- src/rest/src/main/java/org/geoserver/rest/converters/XStreamJSONMessageConverter.java
- src/rest/src/main/java/org/geoserver/rest/converters/XStreamXMLMessageConverter.java
[![GEOS-10828](https://badgen.net/badge/JIRA/GEOS-10828/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10828)
Backport #6543
> [Backport 2.22.x] [GEOS-10828] OGC API - Features - Plugin breaks core /rest API with JSON payloads

- src/community/ogcapi/ogcapi-core/pom.xml
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/MappingJackson2HttpMessageConverter.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/MappingJackson2YAMLMessageConverter.java
- src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/ApiConfigurationSupportTest.java
- src/rest/src/main/java/org/geoserver/rest/converters/XStreamJSONMessageConverter.java
- src/rest/src/main/java/org/geoserver/rest/converters/XStreamXMLMessageConverter.java
[![GEOS-10828](https://badgen.net/badge/JIRA/GEOS-10828/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10828)
Backport #6543
> [Backport 2.21.x] [GEOS-10828] OGC API - Features - Plugin breaks core /rest API with JSON payloads

- doc/en/user/source/webadmin/welcome.rst
- src/main/src/main/java/org/geoserver/catalog/Predicates.java
- src/main/src/main/java/org/geoserver/catalog/impl/CatalogPropertyAccessor.java
- src/main/src/main/java/org/geoserver/security/impl/DataAccessRuleDAO.java
- src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java
- src/web/core/src/main/java/org/geoserver/web/AdminRequestWicketCallback.java
- src/web/core/src/main/java/org/geoserver/web/BoundedCatalogLoader.java
- src/web/core/src/main/java/org/geoserver/web/GeoServerBasePage.java
- src/web/core/src/main/java/org/geoserver/web/GeoServerHomePage.html
- src/web/core/src/main/java/org/geoserver/web/GeoServerHomePage.java
- src/web/core/src/main/java/org/geoserver/web/HomePageSelection.java
- src/web/core/src/main/resources/GeoServerApplication.properties
- src/web/core/src/test/java/org/geoserver/web/GeoServerHomePageTest.java
- src/web/demo/src/main/java/org/geoserver/web/catalogstresstool/CatalogStressTester.java
> [Backport 2.22.x] Improve homepage performance, fall back on simpler selection modes for large catalogs

- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/FeatureService.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/ConformanceTest.java
[![GEOS-10853](https://badgen.net/badge/JIRA/GEOS-10853/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10853)
Simple fix on conformance classes
> [GEOS-10853] Adjust the OGC API Features conformance classes

- src/community/ogcapi/dggs/ogcapi-dggs/src/test/java/org/geoserver/ogcapi/dggs/LandingPageTest.java
- src/community/ogcapi/ogcapi-changeset/src/test/java/org/geoserver/ogcapi/changeset/TilesExtensionsTest.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIContentNegotiationManager.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AbstractLandingPageDocumentNoConformance.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/GeoServerOpenAPI.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/MappingJackson2YAMLMessageConverter.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CoveragesService.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/ApiTest.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/LandingPageTest.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/FeatureService.java
- src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/features/openapi.yaml
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/ApiTest.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/LandingPageTest.java
- src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/ogcapi/images/ImagesService.java
- src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/ogcapi/images/ApiTest.java
- src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/ogcapi/images/LandingPageTest.java
- src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/maps/LandingPageTest.java
- src/community/ogcapi/ogcapi-styles/src/main/java/org/geoserver/ogcapi/styles/StylesService.java
- src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/ogcapi/styles/ApiTest.java
- src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/ogcapi/styles/LandingPageTest.java
- src/community/ogcapi/ogcapi-tiled-features/src/test/java/org/geoserver/ogcapi/features/tiled/ApiTest.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/TilesService.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/tiles/ApiTest.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/tiles/LandingPageTest.java
[![GEOS-10854](https://badgen.net/badge/JIRA/GEOS-10854/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10854)
Set ticket for details
> [GEOS-10854] Move the OGC API OpenAPI definitions to the openapi resource

- src/extension/wps/web-wps/pom.xml
- src/ows/pom.xml
- src/wms/pom.xml
[![GEOS-10844](https://badgen.net/badge/JIRA/GEOS-10844/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10844)
I had some problems when importing Geoserver into Eclipse. Excluding xml-apis fixed that.
> [GEOS-10844] Exclude xml-apis from build

- src/web/wfs/src/test/java/org/geoserver/wfs/web/WFSServiceDescriptionProviderTest.java
- src/wfs/src/main/java/org/geoserver/wfs/WFSResourceVoter.java
[![GEOS-10847](https://badgen.net/badge/JIRA/GEOS-10847/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10847)
Backport #6558
> [Backport 2.22.x] [GEOS-10847] WFSResourceVoter should only vote on WFS content

- doc/en/user/source/community/opensearch-eo/STAC.rst
Backport #6560
**Authored by:** @ktiits
> [Backport 2.22.x] STAC extension: fix item.json path

- src/main/src/main/java/org/geoserver/system/status/BaseSystemInfoCollector.java
- src/main/src/main/java/org/geoserver/system/status/MetricInfo.java
- src/main/src/main/java/org/geoserver/system/status/Metrics.java
- src/main/src/main/java/org/geoserver/system/status/OSHISystemInfoCollector.java
- src/main/src/main/java/org/geoserver/system/status/OSHISystemInfoMonitor.java
- src/main/src/main/java/org/geoserver/system/status/SystemInfoCollector.java
- src/main/src/test/java/org/geoserver/system/status/SystemInfoCollectorTest.java
[![GEOS-10689](https://badgen.net/badge/JIRA/GEOS-10689/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10689)
Backport #6540
**Authored by:** @dieterstueken
> [Backport 2.21.x] [GEOS-10689] OSHISystemInfoCollector holds non daemon threads, prevents clean shutdown of Tomcat

- src/main/src/main/java/org/geoserver/system/status/BaseSystemInfoCollector.java
- src/main/src/main/java/org/geoserver/system/status/MetricInfo.java
- src/main/src/main/java/org/geoserver/system/status/Metrics.java
- src/main/src/main/java/org/geoserver/system/status/OSHISystemInfoCollector.java
- src/main/src/main/java/org/geoserver/system/status/OSHISystemInfoMonitor.java
- src/main/src/main/java/org/geoserver/system/status/SystemInfoCollector.java
- src/main/src/test/java/org/geoserver/system/status/SystemInfoCollectorTest.java
[![GEOS-10689](https://badgen.net/badge/JIRA/GEOS-10689/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10689)
Backport #6540
**Authored by:** @dieterstueken
> [Backport 2.22.x] [GEOS-10689] OSHISystemInfoCollector holds non daemon threads, prevents clean shutdown of Tomcat

- doc/en/user/source/services/wfs/outputformats.rst
- src/wfs/src/main/java/org/geoserver/wfs/response/ShapeZipOutputFormat.java
- src/wfs/src/main/java/org/geoserver/wfs/response/shapezip.ftl
- src/wfs/src/test/java/org/geoserver/wfs/response/ShapeZipTest.java
[![GEOS-10857](https://badgen.net/badge/JIRA/GEOS-10857/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10857)
Requires changes in https://github.com/geotools/geotools/pull/4188 to compile.
> [GEOS-10857] Improve shape-zip output format to handle feature types with multiple geometry columns

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AbstractHTMLMessageConverter.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/FreemarkerTemplateSupport.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/HTMLExtensionCallback.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/SimpleHTMLMessageConverter.java
- src/community/ogcapi/ogcapi-core/src/main/resources/org/geoserver/ogcapi/common-header.ftl
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/GetFeatureHTMLMessageConverter.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/ApiTest.java
- src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/maps/HTMLMapMessageConverter.java
- src/community/ogcapi/ogcapi-tiled-features/src/main/java/org/geoserver/ogcapi/features/tiled/TiledFeaturesExtension.java
[![GEOS-10726](https://badgen.net/badge/JIRA/GEOS-10726/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10726)
Backport #6542
> [Backport 2.22.x] [GEOS-10726] ogc-api: add encoding tag with charset taken from geoserver settings
