src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/ConformanceClass.java, src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/FeatureService.java, src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/features/openapi.yaml, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/ApiTest.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/ConformanceTest.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/FeatureTest.java, src/wfs/src/main/java/org/geoserver/wfs/AliasedQuery.java, src/wfs/src/main/java/org/geoserver/wfs/request/Query.java
[![GEOS-10569](https://badgen.net/badge/JIRA/GEOS-10569/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10569)
=> [GEOS-10569] Features API support sortby query parameter

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/ConformanceClass.java, src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/FeatureService.java, src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/features/openapi.yaml, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/ApiTest.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/ConformanceTest.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/FeatureTest.java, src/wfs/src/main/java/org/geoserver/wfs/AliasedQuery.java, src/wfs/src/main/java/org/geoserver/wfs/request/Query.java
[![GEOS-10569](https://badgen.net/badge/JIRA/GEOS-10569/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10569)
Backport to 2.21.x for #6076.
=> [Backport-2.21.x] [GEOS-10569] Features API support sortby query parameter

doc/en/user/source/extensions/geofence-server/index.rst, doc/en/user/source/extensions/geofence-server/rest-batch-op.rst, src/extension/geofence-server/src/main/java/org/geoserver/geofence/server/rest/BatchRestController.java, src/extension/geofence-server/src/test/java/org/geoserver/geofence/rest/BatchRestControllerTest.java, src/extension/geofence-server/src/test/java/org/geoserver/geofence/rest/RulesRestControllerTest.java, src/extension/geofence/src/main/java/org/geoserver/geofence/rest/xml/AbstractPayload.java, src/extension/geofence/src/main/java/org/geoserver/geofence/rest/xml/Batch.java, src/extension/geofence/src/main/java/org/geoserver/geofence/rest/xml/BatchOperation.java, src/extension/geofence/src/main/java/org/geoserver/geofence/rest/xml/JaxbAdminRule.java, src/extension/geofence/src/main/java/org/geoserver/geofence/rest/xml/JaxbRule.java, src/extension/geofence/src/main/java/org/geoserver/geoserver/xstream/BatchOpXtreamConverter.java, src/extension/geofence/src/main/java/org/geoserver/geoserver/xstream/GeoFenceXStreamPersisterInitializer.java, src/extension/geofence/src/main/resources/applicationContext.xml, src/extension/geofence/src/test/java/org/geoserver/geoserver/xstream/GeofencePersisterSerializationTest.java, src/extension/geofence/src/test/resources/org/geoserver/geoserver/xstream/batch.json, src/extension/geofence/src/test/resources/org/geoserver/geoserver/xstream/batch.xml
[![GEOS-10507](https://badgen.net/badge/JIRA/GEOS-10507/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10507)
* [GEOS-10507] GeoFence Internal - Support Batch operations for Rules and AdminRules
* Minor improvements to rst doc
* fix qa failure
Co-authored-by: Emanuele Tajariol <e.tajariol@gmail.com>
=> [2.20.x backport][GEOS-10507] GeoFence Internal - Support Batch operations for Rules and AdminRules (#6072)

src/gwc-rest/pom.xml, src/gwc-rest/src/main/java/org.geoserver.gwc.layer/GWCGeoServerRESTConfigurationProvider.java, src/gwc-rest/src/main/resources/applicationContext.xml, src/gwc-rest/src/test/java/org/geoserver/gwc/RESTIntegrationTest.java, src/gwc/pom.xml, src/gwc/src/main/resources/geowebcache-geoserver-context.xml, src/gwc/src/main/resources/geowebcache-servlet.xml, src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java, src/pom.xml, src/web/app/pom.xml
[![GEOS-10568](https://badgen.net/badge/JIRA/GEOS-10568/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10568)
=> [2.21.x backport][GEOS-10568] Fix module modularity for GWC (#6021)

src/gwc-rest/pom.xml, src/gwc-rest/src/main/java/org.geoserver.gwc.layer/GWCGeoServerRESTConfigurationProvider.java, src/gwc-rest/src/main/resources/applicationContext.xml, src/gwc-rest/src/test/java/org/geoserver/gwc/RESTIntegrationTest.java, src/gwc/pom.xml, src/gwc/src/main/resources/geowebcache-geoserver-context.xml, src/gwc/src/main/resources/geowebcache-servlet.xml, src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java, src/pom.xml, src/web/app/pom.xml
[![GEOS-10568](https://badgen.net/badge/JIRA/GEOS-10568/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10568)
=> [2.20.x backport][GEOS-10568] Fix module modularity for GWC (#6021)

src/main/src/test/java/org/geoserver/logging/TestAppender.java, src/ows/src/main/java/org/geoserver/ows/Dispatcher.java, src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapIntegrationTest.java
[![GEOS-10608](https://badgen.net/badge/JIRA/GEOS-10608/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10608)
=> [GEOS-10608]:Stop flooding logs with InvalidDate (and similar) at Severe

doc/en/user/source/rest/stores.rst
Documentation on Adding an external WMTS & Configuring external WMTS layers via REST for this reference
https://docs.geoserver.org/stable/en/user/data/cascaded/wmts.html
=> Update documentation on WMTS Store & WMTS Layer

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/catalog/JDBCCatalogFacade.java, src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/catalog/CatalogImplWithJDBCFacadeTest.java
[![GEOS-10609](https://badgen.net/badge/JIRA/GEOS-10609/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10609)
This PR introduces a fix for the reported issue:
https://osgeo-org.atlassian.net/browse/GEOS-10609
"We found an issue when GeoServer use JDBC config catalog implementation, making it unable to use a workspace based style without using the prefix.  JDBC config catalog should follow the same business logic as the default GeoServer catalog implementation."
=> [GEOS-10609] Fix Issue retrieving a workspace style without prefix on JDBCConfig

doc/en/api/1.0.0/coverages.yaml, doc/en/api/1.0.0/coveragestores.yaml, doc/en/api/1.0.0/datastores.yaml, doc/en/api/1.0.0/featuretypes.yaml, src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java, src/main/src/main/java/org/geoserver/catalog/CoverageDimensionCustomizerReader.java, src/main/src/main/java/org/geoserver/catalog/ResourcePool.java, src/restconfig/src/main/java/org/geoserver/rest/catalog/AbstractCatalogController.java, src/restconfig/src/main/java/org/geoserver/rest/catalog/CoverageController.java, src/restconfig/src/main/java/org/geoserver/rest/catalog/CoverageStoreController.java, src/restconfig/src/main/java/org/geoserver/rest/catalog/DataStoreController.java, src/restconfig/src/main/java/org/geoserver/rest/catalog/FeatureTypeController.java, src/restconfig/src/test/java/org/geoserver/rest/catalog/CatalogRESTTestSupport.java, src/restconfig/src/test/java/org/geoserver/rest/catalog/CoverageControllerTest.java, src/restconfig/src/test/java/org/geoserver/rest/catalog/CoverageStoreControllerTest.java, src/restconfig/src/test/java/org/geoserver/rest/catalog/DataStoreControllerTest.java, src/restconfig/src/test/java/org/geoserver/rest/catalog/FeatureTypeControllerTest.java, src/web/core/src/main/java/org/geoserver/web/data/resource/CoverageBandsConfigurationPanel.java
[![GEOS-10610](https://badgen.net/badge/JIRA/GEOS-10610/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10610)
See [GSIP-214](https://github.com/geoserver/geoserver/wiki/GSIP-214)
@jodygarnett regarding [GEOS-6637](https://osgeo-org.atlassian.net/browse/GEOS-6637), the ability to recalculate the bounding boxes was already built into the rest API, using a "calculate" attribute on coverages, and a "recalculate" one on feature types. I've added "attributes" and "dimensions" (aka bands) for completeness, and to address some asymmetry between feature types and coverages (feature types may have attributes configured, but often just reflect on the storage setup, coverages always have band configured instead, and won't reload them unless explicitly required... I've made sure one can force …
=> [GEOS-10610] Selective cache reset on stores and resources, via REST API

src/pom.xml, src/release/data.xml
[![GEOS-10618](https://badgen.net/badge/JIRA/GEOS-10618/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10618)
A quick assembly to package up the ``release`` geoserver data directory for use with the official docker image. Zip structured with ``geoserver_dir`` folder to match Dockerfile.
I have manually created a ``zip`` for the most recent 2.21.1 release to allow documentation to be written:
* https://sourceforge.net/projects/geoserver/files/GeoServer/2.21.1/geoserver-2.21.1-data.zip/download
=> [GEOS-10618] Assemble release geoserver_dir for Docker use

src/pom.xml
[![GEOS-10583](https://badgen.net/badge/JIRA/GEOS-10583/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10583)
@taba90 @prushforth @fernandor777 the modules using this spring-oxm dependencies are GeoFence, MapML and backup-restore. I did not see any new build failure with the upgrade, but could you check if this upgrade is ok?
=> [GEOS-10583] Align spring-oxm with the other Spring dependencies

doc/en/user/source/installation/docker.rst, doc/en/user/source/installation/index.rst
[![GEOS-10618](https://badgen.net/badge/JIRA/GEOS-10618/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10618)
This is some quick instructions for using the new Geoserver Docker Image.
- [n/a] New unit tests have been added covering the changes.
- [n/a] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [will squash] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [n/a] Bug fixes and small new features are presented as a single commit.
=> [GEOS-10618] DOCS: Official GeoServer Docker Image (GSIP-192)

doc/en/api/1.0.0/usergroup.yaml
Add missing swagger docs for associating users with groups. 
Also fixed (broken) plural endpoints to (working) singular
=> Add missing swagger docs for associating users with groups.

src/main/src/main/java/org/geoserver/security/SecureCatalogImpl.java, src/main/src/test/java/org/geoserver/security/impl/ResourceAccessManagerLookupTest.java
[![GEOS-10631](https://badgen.net/badge/JIRA/GEOS-10631/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10631)
=> [GEOS-10631] AccessManager will not be looked up if multiple beans are of type DefaultResourceAccessManager

src/pom.xml, src/web/core/src/main/java/org/geoserver/web/GeoServerHomePage.java, src/web/core/src/test/java/org/geoserver/web/GeoServerHomePageTest.java, src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java, src/web/core/src/test/java/org/geoserver/web/data/store/WMSStoreNewPageTest.java, src/web/core/src/test/java/org/geoserver/web/data/store/WMTSStoreNewPageTest.java
The recent fix for GEOS-10598 had a tad too eager HTML escaping, resulting in:
This change also reduces the verboseness of a couple of tests that were literally flooding the console.
=> [GEOS-10598] XSS vulnerability in the email address field - fix too eager escape

src/ows/src/main/java/org/geoserver/ows/ClasspathPublisher.java, src/ows/src/test/java/org/geoserver/ows/ClasspathPublisherTest.java
[![GEOS-10643](https://badgen.net/badge/JIRA/GEOS-10643/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10643)
This PR updates ClasspathPublisher to prevent path traversal.  The URL decoding and the exception is the same behavior used by FilePublisher and StylePublisher.
=> [GEOS-10643] Improve validation when publishing classpath resources

src/extension/geofence/src/main/java/org/geoserver/geofence/GeoFenceAreaHelper.java, src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
[![GEOS-10635](https://badgen.net/badge/JIRA/GEOS-10635/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10635)
Tests `testArea900913Vector` and `testArea900913Raster` are failing since 9cda0eb5.
These are the test that are now fixed
https://github.com/geoserver/geoserver/blob/9cda0eb558a4301f9ad22632f8caf29013188166/src/extension/geofence/src/test/java/org/geoserver/geofence/GeofenceAccessManagerTest.java#L237-L318
They assume that a standalone test GeoFene is running, according to https://github.com/geoserver/geofence/wiki/Devs%3A-running-integration-tests#geoserver-integration-geofence-standalone
=> [GEOS-10635] GeoFence: area reprojection tests are failing

src/gwc/src/main/java/org/geoserver/gwc/layer/StyleParameterFilter.java, src/gwc/src/test/java/org/geoserver/gwc/layer/StyleParameterFilterTest.java
[![GEOS-10649](https://badgen.net/badge/JIRA/GEOS-10649/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10649)
This PR fixes the issue in `StyleParameterFilter#setLayer()` method which is being called concurrently and can cause out of memory problems due to the corruption of `TreeHashMap` that can occur in scenarios when map is being modified by more than one thread.
I did not go into analysis of why the instances of this class are being concurrently updated in the first place, however the changes made in this PR are at least fixing the OOM that its current implementation can cause.
=> [GEOS-10649] Concurrent modification to GWC style parameter filter can lead to OOM

src/pom.xml, src/web/core/src/main/java/org/geoserver/web/GeoServerHomePage.java, src/web/core/src/test/java/org/geoserver/web/GeoServerHomePageTest.java, src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
=> [GEOS-10598] XSS vulnerability in the email address field - fix too eager escape (2.20.x backport)

src/pom.xml, src/web/core/src/main/java/org/geoserver/web/GeoServerHomePage.java, src/web/core/src/test/java/org/geoserver/web/GeoServerHomePageTest.java, src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
=> [GEOS-10598] XSS vulnerability in the email address field - fix too eager escape (2.21.x backport)

doc/en/user/source/gettingstarted/postgis-quickstart/index.rst
=> typo in doc - fix copy-paste typo (shapefile --> database)

src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/FeatureService.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/FeatureTest.java
[![GEOS-10641](https://badgen.net/badge/JIRA/GEOS-10641/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10641)
The method arguments were in the wrong order.
=> [GEOS-10641] OGC API - Features - Failure on feature item CRS

src/pom.xml
[![GEOS-10666](https://badgen.net/badge/JIRA/GEOS-10666/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10666)
Follows up to https://github.com/geotools/geotools/pull/4020, on this side there is just a dependency update.
=> [GEOS-10666] Mosaic uses excess memory when mosaicking many small images

src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACService.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/ConformanceTest.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/SearchTest.java
[![GEOS-10669](https://badgen.net/badge/JIRA/GEOS-10669/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10669)
=> [GEOS-10669] The STAC API does not declare suppport for the search fields extension

src/pom.xml
[![GEOS-10666](https://badgen.net/badge/JIRA/GEOS-10666/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10666)
=> [GEOS-10666] Mosaic uses excess memory when mosaicking many small images (2.21.x backport)

doc/en/user/source/security/passwd.rst, src/main/src/main/java/org/geoserver/security/auth/EnvPwdResolverUserGroupServiceWrapper.java, src/main/src/main/java/org/geoserver/security/auth/EnvironmentUserDetailService.java, src/main/src/main/java/org/geoserver/security/auth/UsernamePasswordAuthenticationProvider.java, src/main/src/main/java/org/geoserver/security/impl/GeoServerUser.java, src/security/security-tests/src/test/java/org/geoserver/security/auth/PwdEnvParametrizationTest.java
[![GEOS-10655](https://badgen.net/badge/JIRA/GEOS-10655/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10655)
Allow to use env parametrization for users' passwords.
See related jira ticket for details.  
=> [GEOS-10665] - Parametrize Users' passwords

doc/en/user/source/community/oauth2/index.rst, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/MSGraphRolesResolver.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationProvider.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectFilterConfig.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/bearer/AudienceAccessTokenValidator.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/bearer/MultiTokenValidator.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/bearer/SubjectTokenValidator.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/bearer/TokenValidator.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/resources/applicationContext.xml, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/MSGraphRolesResolverTest.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/bearer/AudienceAccessTokenValidatorTest.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/bearer/MultiTokenValidatorTest.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/bearer/SubjectTokenValidatorTest.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.html, src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/resources/GeoServerApplication.properties, src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/resources/GeoServerApplication_ko.properties, src/community/security/oauth2/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerAccessTokenConverter.java, src/community/security/oauth2/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilter.java
[![GEOS-10646](https://badgen.net/badge/JIRA/GEOS-10646/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10646)
This PR is improving the support for Bearer Tokens.  See the updated GS OpenID documentation for setup and usage.
Issue: https://osgeo-org.atlassian.net/browse/GEOS-10646 
Summary: attach an Access Token to your HTTP requests - useful for automated (i.e. desktop/remote web) access of the REST api.
There was already some partial support for Bearer tokens.  This PR improves it.
1. There is now better token validation (see GS doc + OIDC specification).  This improves security.
2. Since you cannot use ID Tokens with attached access tokens, I added two new ways to get user groups:
a) from the "userinfo" endpoint (recommended for KeyCloak)
b) from the MS Graph API (only for MS …
=> [GEOS-10646] OAuth access tokens

doc/en/user/source/community/vector-mosaic/delegate.rst
[![GEOS-10673](https://badgen.net/badge/JIRA/GEOS-10673/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10673)
=> Add example of using FlatGeobuf granules to the Vector Mosaic documentation

src/main/src/main/java/org/geoserver/feature/retype/FidTransformerVisitor.java, src/main/src/main/java/org/geoserver/feature/retype/RetypingDataStore.java
[![GEOS-10692](https://badgen.net/badge/JIRA/GEOS-10692/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10692)
[GEOS-10680](https://osgeo-org.atlassian.net/browse/GEOS-10692)
While the file reads as FidTransformerVisitor.java, the class itself  is misspelled as FidTransformeVisitor.
=> [GEOS-10680] FidTransformeVisitor misspelled

src/main/src/main/java/applicationContext.xml, src/ows/src/main/java/org/geoserver/ows/Dispatcher.java, src/ows/src/main/java/org/geoserver/ows/FileItemCleanupCallback.java, src/ows/src/test/java/org/geoserver/ows/FileItemCleanupCallbackTest.java, src/ows/src/test/java/org/geoserver/ows/applicationContext.xml, src/pom.xml
[![GEOS-10677](https://badgen.net/badge/JIRA/GEOS-10677/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10677)
This PR updates the OWS dispatcher to close streams and remove temp files for multipart/form-data requests without relying on the garbage collector.  Unnecessary input streams are no longer opened for requests that contain multiple file uploads and an NPE is fixed if the dispatcher couldn't find a field to read the input from.  This PR also fixes a race condition where the GC could try to delete a file while the stream is still open which would fail on Windows or could delete the file before GeoServer finished parsing it on Linux. The commons-fileupload upgrade fixes some edge cases where invalid input could leave streams open so it is relevant to this PR.
For core and …
=> [GEOS-10677] Improve cleanup of multi part form upload to the dispatcher

src/main/src/main/java/org/geoserver/config/GeoServerLoader.java, src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java, src/main/src/test/java/org/geoserver/config/util/XStreamPersisterTest.java
[![GEOS-10678](https://badgen.net/badge/JIRA/GEOS-10678/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10678)
[GEOS-10678](https://osgeo-org.atlassian.net/browse/GEOS-10678)
When using `data/minimal/global.xml` no `<settings>` element is defined.
This causes a NPE on `XStreamPersister.doUnmarshal()`.
`XStreamPersister.doMarshal()` looks similar, so I also added a precaution null check here.
If the initialization fails, spring destroys its singleton beans again. 
This causes an other NPE on`GeoServerLoader.destroy()` since it was not fully initialized. 
So I added an other NP check here.
=> [GEOS-10678]: NPE if <settings> element is missing

src/wcs2_0/src/main/java/org/geoserver/wcs2_0/WCSEnvelope.java, src/wcs2_0/src/test/java/org/geoserver/wcs2_0/WCSEnvelopeTest.java
[![GEOS-10699](https://badgen.net/badge/JIRA/GEOS-10699/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10699)
See tickets
=> [GEOS-10699] WCS 2.0 latitude subsetting may fail if the source data has longitudes spanning both datelines

src/main/src/main/java/org/geoserver/logging/LoggingStartupContextListener.java, src/main/src/test/java/org/geoserver/logging/LoggingStartupContextListenerTest.java
[![GEOS-10685](https://badgen.net/badge/JIRA/GEOS-10685/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10685)
[GEOS-10694](https://osgeo-org.atlassian.net/browse/GEOS-10694)
[GEOS-10693](https://osgeo-org.atlassian.net/browse/GEOS-10693)
Starting on an empty context without any logging.xml generates an error. 
Even worse: an empty logging.xml file is generated instead. This raises future future errors.
(The possibly deeper problem here is, that `Resource.in()` creates an empty new file.)
Expected behavior: silently ignore the empty logging.xml and don't create an empty one.
Committed a unit test to demonstrate the error an a fix to resolve it.
=> [GEOS-10694] Suppress stacktrace on startup when logging.xml is missing.

src/community/taskmanager/metadata/pom.xml
[![GEOS-10704](https://badgen.net/badge/JIRA/GEOS-10704/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10704)
=> [GEOS-10704] Task Manager Metadata wrong gs-metadata dependency

src/community/ogcapi/ogcapi-core/pom.xml, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIConfigurationSupport.java, src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/ApiConfigurationSupportTest.java
[![GEOS-10698](https://badgen.net/badge/JIRA/GEOS-10698/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10698)
=> [GEOS-10698] - OGCAPI and REST API coexistence issue

.github/workflows/backport.yml, .github/workflows/linux_jdk8.yml
Backport bot is failing with this message:
```
This is a scheduled Ubuntu-18.04 brownout. The Ubuntu-18.04 environment is deprecated and will be removed on December 1st, 2022. For more details, see https://github.com/actions/runner-images/issues/6002
```
So trying to update the builds still using 18.04 to 20.04
=> Update Ubuntu 18.04 workflows to 20.04

doc/en/docguide/source/workflow.rst
Wrong directory specified for building help with Ant.
=> Wrong dir for building help with Ant

doc/en/user/source/configuration/logging.rst, src/main/src/main/java/org/geoserver/logging/LoggingStartupContextListener.java, src/main/src/main/java/org/geoserver/logging/LoggingUtils.java, src/main/src/main/java/org/geoserver/logging/LoggingUtilsDelegate.java, src/main/src/test/java/org/geoserver/logging/LoggingStartupContextListenerTest.java
[![GEOS-10700](https://badgen.net/badge/JIRA/GEOS-10700/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10700)
This restores the default functionality of allowing customization of built-in logging profiles. In addition the documentation is updated with a manual procedure for updating built-in profiles and an optional flag ``UPDATE_BUILT_IN_LOGGING_PROFILES`` to allow the automatic management of built-in logging profiles.
This replaces:
- https://github.com/geoserver/geoserver/pull/6234
- https://github.com/geoserver/geoserver/pull/6242
=> [GEOS-10700] Restore ability to customize built-in logging profiles along with profile update procedure

.github/workflows/linux_jdk8.yml
To handle the scheduled brownout.
=> Upgrading the JDK 8 GitHub action build to Ubuntu 20.40

doc/en/user/source/configuration/logging.rst, src/main/src/main/java/org/geoserver/logging/LoggingStartupContextListener.java, src/main/src/main/java/org/geoserver/logging/LoggingUtils.java, src/main/src/main/java/org/geoserver/logging/LoggingUtilsDelegate.java, src/main/src/test/java/org/geoserver/logging/LoggingStartupContextListenerTest.java
[![GEOS-10700](https://badgen.net/badge/JIRA/GEOS-10700/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10700)
Backport of https://github.com/geoserver/geoserver/pull/6254
=> [Backport 2.21.x] [GEOS-10700] Restore ability to customize built-in logging profiles along with profile update procedure

src/community/schemaless-features/mongodb-schemaless/src/test/java/org/geoserver/schemalessfeatures/mongodb/SchemalessCollectionTest.java, src/community/schemaless-features/schemaless-core/src/main/java/org/geoserver/schemalessfeatures/filter/SchemalessPropertyAccessorFactory.java
[![GEOS-10709](https://badgen.net/badge/JIRA/GEOS-10709/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10709)
=> [GEOS-10709] Schemaless Features - Simplified property access might return values for wrong property names

src/web/gwc/src/main/java/org/geoserver/gwc/web/GWCServiceDescriptionProvider.java, src/web/gwc/src/test/java/org/geoserver/gwc/web/GWCServiceLinksTest.java
[![GEOS-10647](https://badgen.net/badge/JIRA/GEOS-10647/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10647)
Backport of https://github.com/geoserver/geoserver/pull/6282
=> [Backport 2.22.x] [GEOS-10647] Welcome page links to GetCapabilities do not follow the OGC standards

src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java, src/security/security-tests/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java
[![GEOS-10715](https://badgen.net/badge/JIRA/GEOS-10715/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10715)
See [GEOS-10715](https://osgeo-org.atlassian.net/browse/GEOS-10715)
To reproduce - 
a) create a user with only access to NE workspace
b) got to GS Homepage  or Layer Preview
c) you would expect to see 5 “layers” - 4 real layers and one LayerGroup (“world”)
d) You don’t see the “world” LayerGroup
Underlying cause is the security filter for the catalog uses layer-specific check ([ resource.store.workspace.name = topp ]) that doesn’t work on a layerGroup.
Solution - use a filter that handles both LayerGroup and Layer - “[[ workspace.name = topp ] OR [ resource.store.workspace.name = topp ]]”
NOTE: one of the test cases (SecureCatalogImplTest#testSecurityFilterComplex) relies on …
=> [GEOS-10715] - Workspace Filter for PublishedInfo does not include LayerGroups

src/main/src/main/java/org/geoserver/config/util/XStreamServiceLoader.java, src/main/src/test/java/org/geoserver/config/util/XStreamServiceLoaderTest.java
[![GEOS-10717](https://badgen.net/badge/JIRA/GEOS-10717/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10717)
`XStreamServiceLoader` creates and initializes a new `XStreamPersister` every time it has to save or load a ServiceInfo, which comes with considerable overhead when depersisting thousands of service files.
Since `load()` receives a `GeoServer` argument, which has to be set to the `XStreamPersiter`, a new `XStreamPersister` instance will be created if `load()` is called with a different `GeoServer` reference.
=> GEOS-10717: XStreamServiceLoader performance improvement with XstreamPersister caching

doc/en/user/source/community/index.rst, doc/en/user/source/community/spatialjson/development.rst, doc/en/user/source/community/spatialjson/index.rst, doc/en/user/source/community/spatialjson/installation.rst, doc/en/user/source/community/spatialjson/schema.rst, src/community/pom.xml, src/community/release/ext-spatialjson.xml, src/community/release/pom.xml, src/community/spatialjson/README.md, src/community/spatialjson/pom.xml, src/community/spatialjson/src/main/java/org/geoserver/wfs/json/SpatialJSONGetFeatureResponse.java, src/community/spatialjson/src/main/resources/GeoServerApplication.properties, src/community/spatialjson/src/main/resources/applicationContext.xml, src/web/app/pom.xml, src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
This module adds the SpatialJSON WFS output format. The SpatialJSON format is a more compact and memory-friendly variant of GeoServer's GeoJSON format. It aims to save space by applying several optimizations to traditional GeoJSON format for  simple feature results. Most of these optimizations work by removing redundand information from the JSON-encoded features.
A service exception is thrown if the result contains complex features as the SpatialJSON format does not handle those.
See the [README.md](https://github.com/cklein05/geoserver/tree/spatialjson/src/community/spatialjson) for a more detailed description of the format.
=> New community module: SpatialJSON WFS Output Format

src/web/core/src/main/java/org/geoserver/web/data/layer/SQLViewAbstractPage.java
[![GEOS-4727](https://badgen.net/badge/JIRA/GEOS-4727/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-4727)
Backport from main. Removed test as it cannot be written in this branch, lacks a support method in SQLDialect not available in the GeoTools 2.20.x depends onto.
=> [GEOS-4727] Editing SQL views seems to be leaking connections (2.20.x backport)

src/web/core/src/main/java/org/geoserver/web/data/layer/SQLViewAbstractPage.java
[![GEOS-4727](https://badgen.net/badge/JIRA/GEOS-4727/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-4727)
Backport from main. Removed test as it cannot be written in this branch, lacks a support method in SQLDialect not available in the GeoTools 2.21.x depends onto.
=> [GEOS-4727] Editing SQL views seems to be leaking connections (2.21.x backport)

src/main/src/main/java/org/geoserver/security/impl/AbstractAccessRuleDAO.java, src/main/src/main/java/org/geoserver/security/impl/DataAccessRuleDAO.java, src/main/src/test/java/org/geoserver/security/impl/MemoryDataAccessRuleDAO.java, src/security/security-tests/src/test/java/org/geoserver/security/impl/AbstractAccesRuleDAOConcurrencyTest.java, src/security/security-tests/src/test/java/org/geoserver/security/impl/DataAccesRuleDAOConcurrencyTest.java, src/security/security-tests/src/test/java/org/geoserver/security/impl/DataAccesRuleDAOFileConcurrencyTest.java
[![GEOS-10729](https://badgen.net/badge/JIRA/GEOS-10729/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10729)
=> [GEOS-10729] Concurrent access on data access rules (authorization) can lead to loss of configured catalog mode, and lost rules

doc/en/user/source/community/spatialjson/attributes.rst, doc/en/user/source/community/spatialjson/development.rst, doc/en/user/source/community/spatialjson/index.rst, src/community/spatialjson/README.md, src/community/spatialjson/pom.xml, src/community/spatialjson/src/main/java/org/geoserver/wfs/json/SpatialJSONGetFeatureResponse.java
Optimization no. 2 of the SpatialJSON WFS output format is now available. See this [brief description](https://github.com/cklein05/geoserver/tree/spatialjson-sst/src/community/spatialjson#opt-2-removing-redundant-attribute-values) of the new feature.
=> SpatialJSON Shared String Table Feature

doc/en/user/source/community/index.rst, doc/en/user/source/community/spatialjson/attributes.rst, doc/en/user/source/community/spatialjson/development.rst, doc/en/user/source/community/spatialjson/index.rst, doc/en/user/source/community/spatialjson/installation.rst, doc/en/user/source/community/spatialjson/schema.rst, src/community/pom.xml, src/community/release/ext-spatialjson.xml, src/community/release/pom.xml, src/community/spatialjson/README.md, src/community/spatialjson/pom.xml, src/community/spatialjson/src/main/java/org/geoserver/wfs/json/SpatialJSONGetFeatureResponse.java, src/community/spatialjson/src/main/resources/GeoServerApplication.properties, src/community/spatialjson/src/main/resources/applicationContext.xml, src/web/app/pom.xml, src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
[![GEOS-10733](https://badgen.net/badge/JIRA/GEOS-10733/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10733)
This module adds the SpatialJSON WFS output format. The SpatialJSON format is a more compact and memory-friendly variant of GeoServer's GeoJSON format. It aims to save space by applying several optimizations to traditional GeoJSON format for  simple feature results. Most of these optimizations work by removing redundand information from the JSON-encoded features.
A service exception is thrown if the result contains complex features as the SpatialJSON format does not handle those.
See the [README.md](https://github.com/cklein05/geoserver/tree/spatialjson/src/community/spatialjson) for a more detailed description of the format.
Backport the community module to 2.22.x. It's …
=> [GEOS-10733] Backport SpatialJSON WFS Output Format (2.22.x)

src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/ogcapi/images/STACItemFeaturesResponse.java
`STACItemFeaturesResponse.getCapabilitiesElementName()` throws an `UnsupportedOperationException` instead of returning `null`, producing a `ServiceExceptionReport` when requesting a WFS 1.0.0 `GetCapabilities` document.
`null` is a valid return value for this method, that results in `WFSGetFeatureOutputFormat.getCapabilitiesElementNames()` not contributing an output format name for the
`WFSGetFeatureOutputFormat` in question.
=> [2.21.x backport] ogcapi-images: Avoid ServiceException in WFS GetCapabilities

doc/en/user/source/community/index.rst, doc/en/user/source/community/spatialjson/attributes.rst, doc/en/user/source/community/spatialjson/development.rst, doc/en/user/source/community/spatialjson/index.rst, doc/en/user/source/community/spatialjson/installation.rst, doc/en/user/source/community/spatialjson/schema.rst, src/community/pom.xml, src/community/release/ext-spatialjson.xml, src/community/release/pom.xml, src/community/spatialjson/README.md, src/community/spatialjson/pom.xml, src/community/spatialjson/src/main/java/org/geoserver/wfs/json/SpatialJSONGetFeatureResponse.java, src/community/spatialjson/src/main/resources/GeoServerApplication.properties, src/community/spatialjson/src/main/resources/applicationContext.xml, src/web/app/pom.xml, src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
[![GEOS-10734](https://badgen.net/badge/JIRA/GEOS-10734/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10734)
This module adds the SpatialJSON WFS output format. The SpatialJSON format is a more compact and memory-friendly variant of GeoServer's GeoJSON format. It aims to save space by applying several optimizations to traditional GeoJSON format for  simple feature results. Most of these optimizations work by removing redundand information from the JSON-encoded features.
A service exception is thrown if the result contains complex features as the SpatialJSON format does not handle those.
See the [README.md](https://github.com/cklein05/geoserver/tree/spatialjson/src/community/spatialjson) for a more detailed description of the format.
Backport the community module to 2.21.x. It's …
=> [GEOS-10734] Backport SpatialJSON WFS Output Format (2.21.x)

doc/en/user/source/styling/css/properties.rst
[![GEOS-10737](https://badgen.net/badge/JIRA/GEOS-10737/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10737)
Documentation update, actual fix done in GeoTools.
=> [GEOS-10737] GeoCSS misses support for labelInFeatureInfo and labelAttributeName vendor options

src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/EchoParametersDao.java, src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/Filter.java, src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/RulesDao.java, src/extension/params-extractor/src/main/java/org/geoserver/params/extractor/UrlMangler.java, src/extension/params-extractor/src/test/java/org/geoserver/params/extractor/EchoParametersDaoTest.java, src/extension/params-extractor/src/test/java/org/geoserver/params/extractor/RulesDaoTest.java, src/extension/params-extractor/src/test/java/org/geoserver/params/extractor/TestSupport.java
GEOS-10723
This is a revised pull request replacing [PR #6304](https://github.com/geoserver/geoserver/pull/6304). 
This one focus on the primary problem of using `Resource.in()` and verifies `resource.getType() == Resource.Type.RESOURCE`.
Some confirmed simplifications of the test classes are picked up, too.
Additional aspects of #6304 will be done in a separate issue/PR.
=> [GEOS-10723] params.extractor Resource

doc/en/user/source/installation/docker.rst
In the docker documentation, the mount option was incorrectly -mount instead of --mount.
Also, the release name of docker container is incorrect :
`docker.osgeo.org/geoserver:2.22-SNAPSHOT` does not exist and should be replaced by `docker.osgeo.org/geoserver:2.22-RC` but I did not find where to change this.
=> Fix --mount option

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/QueryablesBuilder.java, src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccess.java, src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccessFactory.java, src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/QueryResultBuilder.java, src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACQueryablesBuilder.java, src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACService.java, src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACSortablesMapper.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/STACSortablesMapperTest.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/STACTestSupport.java, src/community/oseo/oseo-stac/src/test/resources/items-test.json, src/community/oseo/web-oseo/src/main/java/org/geoserver/opensearch/eo/web/OSEOAdminPage.java
[![GEOS-10746](https://badgen.net/badge/JIRA/GEOS-10746/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10746)
=> [GEOS-10476] STAC Sortables should be the same as the configured queryables

doc/en/user/source/gettingstarted/geopkg-quickstart/index.rst
I fixed a typo (Boces --> Boxes)
=> Fix documentation typo

src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java, src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformerTest.java
[![GEOS-10757](https://badgen.net/badge/JIRA/GEOS-10757/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10757)
The WMS DTD specifies that the order of tags inside the <Style> element must be Name, Title, ...
However, Geoserver was putting them in Title, Abstract, Name order.
<!ELEMENT Style ( Name, Title, Abstract?,
LegendURL*, StyleSheetURL?, StyleURL? ) >
This PR just puts the Name (correctly) first.
This is tested by CITE tests WMS 1.1.1.
I have added a test case that will validate the GetCapabilities against the DTD.
While doing this I noticed another problem - for nested Layers the nested Layer tag must be the last tag.
`Element Layer content does not follow the DTD, expecting (Name? , Title , Abstract? , KeywordList? , SRS* , LatLonBoundingBox? , BoundingBox* , Dimension* , …
=> [GEOS-10757] CITE: WMS <Style> has elements in wrong order (DTD validation)

src/wfs/src/test/java/org/geoserver/wfs/xml/GMLOutputFormatTest.java, src/wfs/src/test/resources/org/geoserver/wfs/xml/invalid_character.properties, src/wfs/src/test/resources/org/geoserver/wfs/xml/invalid_namespace.properties
[![GEOS-10753](https://badgen.net/badge/JIRA/GEOS-10753/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10753)
2.22.x backport for https://github.com/geoserver/geoserver/pull/6364
=> [2.22.x][GEOS-10753] GeoServer can create GML output that is not valid XML

src/wfs/src/test/java/org/geoserver/wfs/xml/GMLOutputFormatTest.java, src/wfs/src/test/resources/org/geoserver/wfs/xml/invalid_character.properties, src/wfs/src/test/resources/org/geoserver/wfs/xml/invalid_namespace.properties
[![GEOS-10753](https://badgen.net/badge/JIRA/GEOS-10753/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10753)
2.21.x backport for https://github.com/geoserver/geoserver/pull/6364
=> [2.21.x][GEOS-10753] GeoServer can create GML output that is not valid XML

src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/CollectionDocument.java, src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/FeatureResponseMessageConverter.java, src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/FeatureService.java, src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/features/collection_include.ftl, src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/features/openapi.yaml, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/CollectionTest.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/CollectionsTest.java
[![GEOS-10758](https://badgen.net/badge/JIRA/GEOS-10758/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10758)
=> [GEOS-10578] OGCAPI - Features - Add `storageCrs` property for Collections

doc/en/user/source/community/oauth2/index.rst, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/bearer/AudienceAccessTokenValidator.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/bearer/AudienceAccessTokenValidatorTest.java
[![GEOS-10770](https://badgen.net/badge/JIRA/GEOS-10770/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10770)
According to [RFC 6750](https://www.rfc-editor.org/rfc/rfc6750) Bearer Tokens are allowed to contain a list of audience claims. This PR extends gs-sec-oauth2-openid-connect-core validation of Bearer Tokens introduced in [PR 6167](https://github.com/geoserver/geoserver/pull/6167) to also support a list in JWT attribute "aud".
see also: https://osgeo-org.atlassian.net/browse/GEOS-10770
=> [GEOS-10770] support list of audiences in access token

src/main/src/test/java/org/geoserver/config/GeoServerDataDirectoryTest.java
GeoServerDataDirectoryTest doesn't properly clean up the application context after it is finished.  This causes more than 2,000 stack traces in the logs about "BeanFactory not initialized or already closed" when running the gs-main unit tests.
=> Fix GeoServerDataDirectoryTest clean up after running tests

src/wfs/src/main/java/org/geoserver/wfs/response/HitsOutputFormat.java, src/wfs/src/test/java/org/geoserver/wfs/response/HitsOutputFormatTest.java
[![GEOS-10782](https://badgen.net/badge/JIRA/GEOS-10782/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10782)
For WFS 1.1.0 GetFeature (HITS) must return a mime type of  "text/xml; subtype=gml/3.1.1" according to the spec.
JIRA: https://osgeo-org.atlassian.net/browse/GEOS-10782
9.3 Response
The format of the response to a GetFeature request is controlled by the outputFormat
attribute. The default value for the outputFormat attribute shall be the MIME type
text/xml; subtype=gml/3.1.1.
The CITE tests check this;
https://github.com/opengeospatial/ets-wfs11/blob/master/src/main/scripts/ctl/basic/GetFeature/GetFeature-GET.xml#L193
(there are several checks)
Before Geoserver was always returning "text/xml" (without the subtype)
=> [GEOS-10782] CITE WFS 1.1 - HITS mimetype is incorrect

src/main/src/main/java/org/geoserver/catalog/ResourcePool.java, src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java
[![GEOS-10783](https://badgen.net/badge/JIRA/GEOS-10783/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10783)
While running CITE tests, i was unable to lock any features.
JIRA: https://osgeo-org.atlassian.net/browse/GEOS-10783
Tracking this down, what was happening is that this was being called:
` fs = (SimpleFeatureSource) transformer.wrapFeatureSource(info, fs);`
This was returning a non-locking SimpleFeatureSource.  This was then wrapped in another non-lock SimpleFeatureSource.
This was because the Feature Info had a list of attributes in it.  I'm not sure if this is particular to the CITE configuration or if GS locking is completely broken for everyone.
Test cases have getAttributes() returning an empty list, while the actual catalog returns a full list of attributes.
For core …
=> [GEOS-10783] CITE WFS 1.1 - unable to lock features

src/wcs1_1/src/main/java/org/geoserver/wcs/kvp/GetCoverageRequestReader.java, src/wcs1_1/src/test/java/org/geoserver/wcs/kvp/GetCoverageReaderTest.java
[![GEOS-10787](https://badgen.net/badge/JIRA/GEOS-10787/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10787)
According to WFS 1.1 spec, the “store” parameter must be "True" or "False". 
CITE test "GetCoverage_Store_Bogus" tests that an exception is thrown when its set to something else.
Geoserver treats an unknown value (ie. “bogus”) as false.
JIRA: https://osgeo-org.atlassian.net/browse/GEOS-10787  
NOTE: an alternative place to fix this would be in `BooleanKvpParser`. However, I think this would cause some side-effects.
=> [GEOS-10787] CITE WCS 1.1.1 - Throw exception on bad 'store' parameter

src/wfs/src/main/java/org/geoserver/wfs/UpdateElementHandler.java, src/wfs/src/test/java/org/geoserver/wfs/TransactionTest.java, src/wfs/src/test/java/org/geoserver/wfs/UpdateElementHandlerTest.java
[![GEOS-10784](https://badgen.net/badge/JIRA/GEOS-10784/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10784)
One of the CITE tests attempts to put the wrong geometry type (multicurve (linestring) into a polygon).
JIRA: https://osgeo-org.atlassian.net/browse/GEOS-10784
Geoserver would convert this linestring to a polygon and do the insert.
The Polygon that it created just appended all the line's coordinates together, so it wasnt a very good conversion.
CITE test explicitly check that this situation throws an exception. 
This change allows for most geometry xforms, but doesn't allow dimensional changes (i.e. 2d to 1d).
Here is the CITE test:
https://github.com/opengeospatial/ets-wfs11/blob/master/src/main/scripts/ctl/wfs-transaction/Transaction/Transaction-XML.xml#L815
- [x ] All the …
=> [GEOS-10784] CITE WFS 1.1 - don't do illegal geometry conversions

doc/en/api/1.0.0/coverages.yaml, doc/en/api/1.0.0/featuretypes.yaml, doc/en/user/source/data/webadmin/layers.rst, restput.xml, src/main/src/main/java/org/geoserver/catalog/DimensionInfo.java, src/main/src/main/java/org/geoserver/catalog/impl/DimensionInfoImpl.java, src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java, src/web/core/src/main/java/org/geoserver/web/data/resource/DimensionEditor.html, src/web/core/src/main/java/org/geoserver/web/data/resource/DimensionEditorBase.java, src/web/core/src/main/java/org/geoserver/web/data/resource/VectorCustomDimensionEditor.html, src/web/core/src/main/java/org/geoserver/web/data/resource/VectorCustomDimensionEntry.java, src/web/core/src/main/resources/GeoServerApplication.properties, src/wms/src/main/java/org/geoserver/wms/WMS.java, src/wms/src/main/java/org/geoserver/wms/capabilities/DimensionHelper.java, src/wms/src/test/java/org/geoserver/wms/dimension/DimensionInfoSerializationTest.java, src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DimensionsRasterCapabilitiesTest.java, src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DimensionsVectorCapabilitiesTest.java, src/wms/src/test/java/org/geoserver/wms/wms_1_3/DimensionsRasterCapabilitiesTest.java, src/wms/src/test/java/org/geoserver/wms/wms_1_3/DimensionsVectorCapabilitiesTest.java
[![GEOS-10756](https://badgen.net/badge/JIRA/GEOS-10756/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10756)
This adds two new input fields in the Dimensions Tab of a layer.
The fields allow to manually specify the start and end datetime GeoServer should use when generating the capabilities for this layer:
Values have to be ISO8601 or the string `PRESENT` to reflect the current DateTime in the Capabilities.
The settings from the screenshot above lead to the following capabilities for that layer:
When specifying start and end times, the automatic detection of those which GeoServer usually does is skipped and the given values are used.
This is especially useful when working with layers that are based on very large datasets, as the auto detection may become very slow / unresponding …
=> [GEOS-10756] Add support for manual configuration of start and end value in WMS Layer Dimensions

src/extension/geofence/geofence-server/src/main/java/org/geoserver/geofence/server/rest/GeofenceJaxbRestConfiguration.java, src/extension/geofence/geofence-server/src/test/java/org/geoserver/geofence/server/rest/AdminRulesRestControllerTest.java, src/extension/geofence/geofence-server/src/test/java/org/geoserver/geofence/server/rest/RulesRestControllerTest.java, src/rest/src/main/java/org/geoserver/rest/RestConfiguration.java
[![GEOS-10760](https://badgen.net/badge/JIRA/GEOS-10760/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10760)
Fix a regression in encoding GeoFence JAXB message payloads introduced by [GEOS-10591](https://osgeo-org.atlassian.net/browse/GEOS-10591) at commit cf57b56edcfc22080fe73c3951b01b3408088a10 (`2.22.x` series), which adds the `jackson-dataformat-xml` dependency to `gs-ows`.
As a result, `WebMvcConfigurationSupport.addDefaultHttpMessageConverters()` will not add a Jaxb2RootElementHttpMessageConverter`, but a `MappingJackson2XmlHttpMessageConverter` instead, rendering the JAXB2 annotations in Geofence's REST object model useless.
This patch makes `org.geoserver.rest.RestConfiguration` extend `DelegatingWebMvcConfiguration` instead of WebMvcConfigurationSupport`, which is a …
=> [GEOS-10760] GeoFence XML REST API broken: wrong element names

src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/KeycloakUrlBuilder.java, src/community/security/keycloak/src/test/java/org/geoserver/security/keycloak/KeycloakUrlBuilderTest.java
[![GEOS-10809](https://badgen.net/badge/JIRA/GEOS-10809/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10809)
When using geoserver secured via keycloak, an error is thrown if the user has a username containing at least one space.
This PR should fix this.
=> [GEOS-10809] : Keycloak : add support for usernames with spaces

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/QueryBuilder.java
This PR updates jdbcconfig with debug logging when a filter is not supported because it uses properties that are not encodable. I didn't create a JIRA ticket for this.
=> jdbcconfig - add logging of non-encodable property names

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/DbUtils.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/FilterToCatalogSQL.java
This PR updates the jdbcconfig debug logging to log the parameter values in the same order that they appear in the SQL query.  I didn't create a JIRA ticket for this.
=> jdbcconfig - log parameter values in order they appear in query

src/pom.xml
[![GEOS-10812](https://badgen.net/badge/JIRA/GEOS-10812/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10812)
backports https://github.com/geoserver/geoserver/pull/6469
Co-authored-by: Mark Prins <1165786+mprins@users.noreply.github.com>
=> [Backport 2.21.x][GEOS-10812] Update Jettison to 1.5.3 (#6469)

src/web/core/src/main/java/org/geoserver/web/data/store/panel/DropDownChoiceParamPanel.java, src/web/core/src/test/java/org/geoserver/web/data/store/WFSStoreNewPageTest.java
[![GEOS-10794](https://badgen.net/badge/JIRA/GEOS-10794/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10794)
Support for proper auto-completion when having multiple select 2 dropdowns had side effects on the WFS config panel, because of the param titles in that store (looks like a wrong component path to jQuery).
I've added a test to make sure we have simple yet unique identifier that won't confused jQuery, but the actual reported issue can only be tested interactively in a browser (used to throw exceptions only visible in the javascript console)
=> [GEOS-10794] Add a new vector data source (Web Feature Server (NG)) Filter compliance level bug

src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/JDBCConfigTestSupport.java
This PR updates the jdbcconfig unit tests to not attempt to connect to the Oracle and PostgreSQL databases by default when running unit tests in an IDE which will make the tests run faster. I didn't create a JIRA ticket for this.
=> jdbcconfig - make unit tests run faster in IDE

src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java, src/restconfig/src/test/java/org/geoserver/rest/catalog/LayerGroupControllerTest.java
[![GEOS-10807](https://badgen.net/badge/JIRA/GEOS-10807/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10807)
See jira ticket for details.
=> [GEOS-10807] LayerGroup with nested group POST rest op fails with null styles attribute

src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/XHTMLTemplateWriter.java, src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/XMLTemplateWriter.java, src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/HTMLMappedFeature.xhtml, src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/wfs/TemplateGetFeatureResponseHelper.java, src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/HTMLGetComplexFeatureResponseTest.java
[![GEOS-10817](https://badgen.net/badge/JIRA/GEOS-10817/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10817)
=> [GEOS-10817] Features Templating - XML HTML output doesn't escape all html and xml symbols

src/wcs1_1/src/main/java/org/geoserver/wcs/DefaultWebCoverageService111.java, src/wcs1_1/src/test/java/org/geoserver/wcs/GetCoverageTest.java
[![GEOS-10788](https://badgen.net/badge/JIRA/GEOS-10788/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10788)
While running the WCS 1.1.1 CITE tests, GS wasn't passing some of the interpolationMethod tests.
This was discussed with OGC CITE - https://github.com/opengeospatial/ets-wcs11/issues/76
Because the spec is not specific, the CITE test will be changed to only check for an exception report.
The PR only addresses the outstanding problem - ensuring that GS throws an exception where there is a blank interpolationMethod.
Here is an example CITE test;
https://github.com/opengeospatial/ets-wcs11/blob/master/src/main/scripts/ctl/GetCoverage.xml#L5586
=> [GEOS-10788] CITE WCS 1.1.1 -  Empty InterpolationMethod should throw exception

src/community/schemaless-features/mongodb-schemaless/src/test/java/org/geoserver/schemalessfeatures/mongodb/SchemalessCollectionTest.java, src/community/schemaless-features/schemaless-core/src/main/java/org/geoserver/schemalessfeatures/filter/SchemalessPropertyAccessorFactory.java
[![GEOS-10818](https://badgen.net/badge/JIRA/GEOS-10818/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10818)
=> [GEOS-10818] Schemaless Property Accessor returns emptylist instead of null for null/not existing properties

src/community/ogcapi/dggs/dggs-clickhouse/src/test/java/org/geotools/dggs/clickhouse/ClickHouseOnlineTestCase.java, src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/PolygonFunction.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIFilterParser.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/QueryablesBuilder.java, src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/CollectionsTest.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/ApiTest.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/CollectionsTest.java, src/community/ogcapi/ogcapi-styles/src/main/resources/org/geoserver/ogcapi/styles/openapi.yaml, src/community/ogcapi/ogcapi-styles/src/test/resources/org/geoserver/ogcapi/styles/tasmania.sld, src/community/ogcapi/ogcapi-tiles/pom.xml, src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/TilesSampleDataProvider.java, src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/tiles/TileJSONBuilderTest.java, src/community/ogcapi/ogcapi-tiles/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Just a set of clean ups to make a build of ``ogcapi`` fully pass even with ``-Dqa`` enabled.
=> Make all OGC API modules pass QA checks, update test dependencies to work on Java 11, fix a few tests

doc/en/user/source/community/oauth2/index.rst, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectFilterConfig.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdConnectIntegrationTest.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdFilterConfigTest.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.html, src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/resources/GeoServerApplication.properties, src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/test/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanelTest.java
[![GEOS-10821](https://badgen.net/badge/JIRA/GEOS-10821/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10821)
=> [GEOS-10821] OpenID - Allow configuration of post_login_redirect_uri

doc/en/user/source/community/oauth2/index.rst, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectFilterConfig.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdConnectIntegrationTest.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdFilterConfigTest.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.html, src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/resources/GeoServerApplication.properties, src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/test/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanelTest.java
[![GEOS-10821](https://badgen.net/badge/JIRA/GEOS-10821/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10821)
=> [2.21.x backport][GEOS-10821] OpenID - Allow configuration of post_login_redirect_uri

doc/en/user/source/community/oauth2/index.rst, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectFilterConfig.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdConnectIntegrationTest.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdFilterConfigTest.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.html, src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.java, src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/resources/GeoServerApplication.properties, src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/test/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanelTest.java
[![GEOS-10821](https://badgen.net/badge/JIRA/GEOS-10821/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10821)
=> [2.20.x backport][GEOS-10821] OpenID - Allow configuration of post_login_redirect_uri

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java, src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
[![GEOS-10813](https://badgen.net/badge/JIRA/GEOS-10813/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10813)
See jira ticket for details.
=> [GEOS-10813] -- jdbcconfig cache bug,changed the workspace name

src/platform/src/test/java/org/geoserver/platform/resource/FileWrapperResourceTheoryTest.java, src/platform/src/test/java/org/geoserver/platform/resource/ResourceTheoryTest.java
[![GEOS-10683](https://badgen.net/badge/JIRA/GEOS-10683/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10683)
Adjust test to use relative paths, to avoid complications with ResourceAdaptor use of absolute paths internally.
This is a backport of the test case fix from https://github.com/geoserver/geoserver/pull/6370 only allowing this java 8 branch to be built with Java 11 on a windows environment (by avoid some ill-advised relative path tests that are actually intended to be absolute paths).
See https://github.com/geoserver/geoserver/pull/6447 for a fix addressing the Resource API use of relative vs absolute paths.
=> [Backport 2.22.x] [GEOS-10683] FileWrapperResourceTheoryTest fix for Java 11

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/DbUtils.java, src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/DbUtilsTest.java
This PR breaks up the jdbcconfig debug logging code into smaller methods and fixes logging incorrect statements for complex filters where a numbered parameters gets up to 10+ (e.g., ptype10).  I didn't create a ticket since this is a debug logging change.
=> jdbcconfig - fixed incorrect logging for queries with complex filters

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/DbMappings.java
This PR adds debug logging to some jdbcconfig queries run during GeoServer startup or the jdbcconfig import that weren't being logged.  I didn't create a ticket since this is a debug logging change.
=> jdbcconfig - added debug logging to all database queries

src/main/src/main/java/org/geoserver/catalog/ResourcePool.java, src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java, src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleAdminPanel.java
[![GEOS-10743](https://badgen.net/badge/JIRA/GEOS-10743/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10743)
[GEOS-10743](https://osgeo-org.atlassian.net/browse/GEOS-10743)
[ResourcePool.readStyle](https://github.com/geoserver/geoserver/blob/main/src/main/src/main/java/org/geoserver/catalog/ResourcePool.java#L2165) calls `Resource.in()` without any checking if the file exists.
The decision what to do, if the resource does not exist should be done at higher level. Unfortunately, it is directly turned into a character reader (even a BufferedReader) already. I think this not a good idea to do that at this level. For instance, the encoding is unclear at this point especially for SLD/XML files (same for writing). But I think this is again a refactoring going far beyond this issue.
To …
=> [GEOS-10743] read missing style files

doc/en/user/source/filter/function_reference.rst
XML element containing the list of functions differs for the different WFS versions. Also the function to compare values not being equal, the correctfunction name is `notEqualTo` instead of `notEqual`.
=> Documentation: Filter function is notEqualTo iso notEqual.

doc/en/user/source/filter/function_reference.rst
Backport #6538
**Authored by:** @emacgillavry
=> [Backport 2.21.x] Documentation: Filter function is notEqualTo iso notEqual.

doc/en/user/source/filter/function_reference.rst
Backport #6538
**Authored by:** @emacgillavry
=> [Backport 2.22.x] Documentation: Filter function is notEqualTo iso notEqual.

src/release/bin/shutdown.bat
The original `for /f %f in ('where java')` truncates "Program Files" into "Program". PR adds "tokens=*"
Fixes https://osgeo-org.atlassian.net/browse/GEOS-7506
=> Shutdown.bat: support java path with spaces

src/release/bin/shutdown.bat
Backport #6536
**Authored by:** @jratike80
=> [Backport 2.21.x] Shutdown.bat: support java path with spaces

src/release/bin/shutdown.bat
Backport #6536
**Authored by:** @jratike80
=> [Backport 2.22.x] Shutdown.bat: support java path with spaces

src/main/src/main/java/org/geoserver/config/SpringResourceAdaptor.java, src/main/src/test/java/org/geoserver/config/GeoServerPropertyConfigurerTest.java, src/main/src/test/java/org/geoserver/config/SpringResourceAdaptorTest.java
[![GEOS-10724](https://badgen.net/badge/JIRA/GEOS-10724/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10724)
The `SpringResourceAdaptor` wraps an `org.geoserver.platform.resource.Resource` into a `org.springframework.core.io.Resource`.
Both are quite similar, but while the geoserver Resource wraps any `IOException` into an `IllegalStateException`  
(which is fine to use it in λ-expressions), the spring Resource however can and should throw the `IOException` itself.
Looking at [GeoServerPropertyConfigurer:104](https://github.com/geoserver/geoserver/blob/190f8849b9a2da54f709f227f3ad3e93a1194f41/src/main/src/main/java/org/geoserver/config/GeoServerPropertyConfigurer.java#L104) it seems, the missing config file shall be created and filled.
However, `super.loadProperties` indirectly …
=> [GEOS-10724] SpringResourceAdaptor should throw a FileNotFoundException instead of creating any missing file

doc/en/user/source/webadmin/welcome.rst, src/main/src/main/java/org/geoserver/catalog/Predicates.java, src/main/src/main/java/org/geoserver/catalog/impl/CatalogPropertyAccessor.java, src/main/src/main/java/org/geoserver/security/impl/DataAccessRuleDAO.java, src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java, src/web/core/src/main/java/org/geoserver/web/AdminRequestWicketCallback.java, src/web/core/src/main/java/org/geoserver/web/BoundedCatalogLoader.java, src/web/core/src/main/java/org/geoserver/web/GeoServerBasePage.java, src/web/core/src/main/java/org/geoserver/web/GeoServerHomePage.html, src/web/core/src/main/java/org/geoserver/web/GeoServerHomePage.java, src/web/core/src/main/java/org/geoserver/web/HomePageSelection.java, src/web/core/src/main/resources/GeoServerApplication.properties, src/web/core/src/test/java/org/geoserver/web/GeoServerHomePageTest.java, src/web/demo/src/main/java/org/geoserver/web/catalogstresstool/CatalogStressTester.java
Based on two separate items:
* Allow the home page controls and description to fall back on [simpler, cheaper to initialize GUI controls](https://osgeo-org.atlassian.net/browse/GEOS-10833)
* [Speed up DefaultResourceAccessManager filters](https://osgeo-org.atlassian.net/browse/GEOS-10838) to speed up the above counts/fills (and along with it, layer preview and capabilities document generation)
[GEOS-10838](https://osgeo-org.atlassian.net/browse/GEOS-10838) makes the current GUI viable when relatively few items are available out of a large set of layers due to security rules. 
[GEOS-10833](https://osgeo-org.atlassian.net/browse/GEOS-10833) instead makes sure that if too many items are available, we can still have a working homepage, getting an acceptable response time (max 5 seconds by …
=> Improve homepage performance, fall back on simpler selection modes for large catalogs

src/web/core/src/main/java/org/geoserver/web/GeoServerHomePage.java, src/web/core/src/main/java/org/geoserver/web/HomePageSelection.java, src/web/core/src/test/java/org/geoserver/web/GeoServerHomePageTest.java
[![GEOS-10833](https://badgen.net/badge/JIRA/GEOS-10833/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10833)
@jodygarnett this should fix the layer selection clearing issue you saw. While I was at it, I've also made the URLs better looking (instead of an empty key, the key is removed altogether).
=> [GEOS-10833] GeoServerHomePage unresponsive against large catalogs - fix regression on layer dropdown

src/web/core/src/main/java/org/geoserver/web/GeoServerHomePage.java, src/web/core/src/main/java/org/geoserver/web/HomePageSelection.java, src/web/core/src/test/java/org/geoserver/web/GeoServerHomePageTest.java
[![GEOS-10833](https://badgen.net/badge/JIRA/GEOS-10833/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10833)
Backport #6561
=> [Backport 2.22.x] [GEOS-10833] GeoServerHomePage unresponsive against large catalogs - fix regression on layer dropdown

src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/FeatureService.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/ConformanceTest.java
[![GEOS-10853](https://badgen.net/badge/JIRA/GEOS-10853/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10853)
Backport #6564
=> [Backport 2.22.x] [GEOS-10853] Adjust the OGC API Features conformance classes

src/web/wfs/src/test/java/org/geoserver/wfs/web/WFSServiceDescriptionProviderTest.java, src/wfs/src/main/java/org/geoserver/wfs/WFSResourceVoter.java
[![GEOS-1084](https://badgen.net/badge/JIRA/GEOS-1084/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-1084)
=> [GEOS-10847] WFSResourceVoter should only vote on WFS content

doc/en/user/source/community/opensearch-eo/STAC.rst
I believe the template for item.json path was wrong in documentation, it gave 404.
=> STAC extension: fix item.json path

src/rest/src/main/java/org/geoserver/rest/RestBaseController.java, src/restconfig/src/test/java/org/geoserver/rest/SettingsControllerTest.java
[![GEOS-10846](https://badgen.net/badge/JIRA/GEOS-10846/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10846)
This PR enables FreeMarker's built-in auto-escaping functionality for REST HTML templates.  A setting to enable/disable this doesn't seem necessary since all of the REST templates are included in the JAR files and I looked at the templates in every ftl-templates directory I could find and didn't see any obvious conflicts with enabling this.
=> [GEOS-10846] Enable auto-escaping for REST HTML templates

src/main/src/main/java/org/geoserver/system/status/BaseSystemInfoCollector.java, src/main/src/main/java/org/geoserver/system/status/MetricInfo.java, src/main/src/main/java/org/geoserver/system/status/Metrics.java, src/main/src/main/java/org/geoserver/system/status/OSHISystemInfoCollector.java, src/main/src/main/java/org/geoserver/system/status/OSHISystemInfoMonitor.java, src/main/src/main/java/org/geoserver/system/status/SystemInfoCollector.java, src/main/src/test/java/org/geoserver/system/status/SystemInfoCollectorTest.java
[![GEOS-10689](https://badgen.net/badge/JIRA/GEOS-10689/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10689)
[GEOS-10689]
`OSHISystemInfoCollector`  is a singleton bean to collect system statistics. It creates some `SystemInfo` context and starts a thread to work upon them. A thread is created using an inline lambda expression to implement the collector loop.
This manifests several flaws:
- the implemented loop was taken from [some sample code](https://github.com/oshi/oshi/issues/372) to monitor a _separate_ process. However, in our loop we are observing _our self_. So, the `while (processExists)` loop runs forever.
- the thread is not a _daemon_ thread. Thus the VM will not terminate voluntarily.
- the bean runs on a different thread, so some variables must be volatile.
- the bean …
=> [GEOS-10689] OSHISystemInfoCollector holds non daemon threads, prevents clean shutdown of Tomcat

src/community/ogcapi/dggs/ogcapi-dggs/src/test/java/org/geoserver/ogcapi/dggs/LandingPageTest.java, src/community/ogcapi/ogcapi-changeset/src/test/java/org/geoserver/ogcapi/changeset/TilesExtensionsTest.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIContentNegotiationManager.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AbstractLandingPageDocumentNoConformance.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/GeoServerOpenAPI.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/MappingJackson2YAMLMessageConverter.java, src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CoveragesService.java, src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/ApiTest.java, src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/LandingPageTest.java, src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/FeatureService.java, src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/features/openapi.yaml, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/ApiTest.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/LandingPageTest.java, src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/ogcapi/images/ImagesService.java, src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/ogcapi/images/ApiTest.java, src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/ogcapi/images/LandingPageTest.java, src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/maps/LandingPageTest.java, src/community/ogcapi/ogcapi-styles/src/main/java/org/geoserver/ogcapi/styles/StylesService.java, src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/ogcapi/styles/ApiTest.java, src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/ogcapi/styles/LandingPageTest.java, src/community/ogcapi/ogcapi-tiled-features/src/test/java/org/geoserver/ogcapi/features/tiled/ApiTest.java, src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/TilesService.java, src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/tiles/ApiTest.java, src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/tiles/LandingPageTest.java
[![GEOS-10854](https://badgen.net/badge/JIRA/GEOS-10854/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10854)
Backport #6567
=> [Backport 2.22.x] [GEOS-10854] Move the OGC API OpenAPI definitions to the openapi resource

src/rest/src/main/java/org/geoserver/rest/RestBaseController.java, src/restconfig/src/test/java/org/geoserver/rest/SettingsControllerTest.java
[![GEOS-10846](https://badgen.net/badge/JIRA/GEOS-10846/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10846)
Backport #6555
=> [Backport 2.21.x] [GEOS-10846] Enable auto-escaping for REST HTML templates

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AbstractHTMLMessageConverter.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/FreemarkerTemplateSupport.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/HTMLExtensionCallback.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/SimpleHTMLMessageConverter.java, src/community/ogcapi/ogcapi-core/src/main/resources/org/geoserver/ogcapi/common-header.ftl, src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/GetFeatureHTMLMessageConverter.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/ApiTest.java, src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/maps/HTMLMapMessageConverter.java, src/community/ogcapi/ogcapi-tiled-features/src/main/java/org/geoserver/ogcapi/features/tiled/TiledFeaturesExtension.java
[![GEOS-10726](https://badgen.net/badge/JIRA/GEOS-10726/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10726)
=> [GEOS-10726] ogc-api: add encoding tag with charset taken from geoserver settings

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/JMSXStreamFactory.java, src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/DocumentFile.java, src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/CatalogUtils.java, src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogEventHandler.java, src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogModifyEventHandler.java, src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/rest/ClusterController.java, src/community/jms-cluster/jms-geoserver/src/main/resources/applicationContext.xml, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/DocumentFileTest.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogModifyEventHandlerTest.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/CatalogDiffVisitor.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/InfoDiff.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/IntegrationTest.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/IntegrationTestsUtils.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/rest/ClusterControllerTest.java, src/main/src/main/java/org/geoserver/config/util/SecureXStream.java, src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
[![GEOS-10517](https://badgen.net/badge/JIRA/GEOS-10517/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10517)
See ticket for details. While I was at it, made all tests pass again, fixing a few more things (the JMS module was completely non functional due to the XStream white list issue, don't think other tickets are useful).
=> [GEOS-10517] jms-cluster classes missing from XStream security configuration

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/Dialect.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/FilterToCatalogSQL.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/OracleDialect.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/QueryBuilder.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcloader/JDBCLoaderProperties.java, src/community/jdbcconfig/src/main/resources/applicationContext.xml, src/community/jdbcconfig/src/main/resources/jdbcconfig.properties, src/community/jdbcconfig/src/main/resources/jdbcconfig.properties.h2, src/community/jdbcconfig/src/main/resources/jdbcconfig.properties.postgres, src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/JDBCConfigTestSupport.java, src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/QueryBuilderTest.java
2.22.x backport for GEOS-10842 and also includes:
[GEOS-10839] Add JDBC Configuration parameter to disable SQL comments and pretty-printing
=> [2.22.x][GEOS-10842] Escape user inputs in SQL queries

doc/en/docguide/source/background.rst, doc/en/docguide/source/sphinx.rst, doc/en/docguide/source/workflow.rst
This PR fixes the broken reStructuredText links and makes sure all the reStructuredText links use the same URL.
The reStructuredText link using `.htm` no longer worked, and were not redirected. I replaced all reStructuredText links with the current directed link, which is `https://docutils.sourceforge.io`.
=> fix(docs): correct restructuredtext links

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/Dialect.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/FilterToCatalogSQL.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/OracleDialect.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/QueryBuilder.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcloader/JDBCLoaderProperties.java, src/community/jdbcconfig/src/main/resources/applicationContext.xml, src/community/jdbcconfig/src/main/resources/jdbcconfig.properties, src/community/jdbcconfig/src/main/resources/jdbcconfig.properties.h2, src/community/jdbcconfig/src/main/resources/jdbcconfig.properties.postgres, src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/JDBCConfigTestSupport.java, src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/QueryBuilderTest.java
2.21.x backport for GEOS-10842 and also includes:
[GEOS-10839] Add JDBC Configuration parameter to disable SQL comments and pretty-printing
=> [2.21.x][GEOS-10842] Escape user inputs in SQL queries

doc/en/developer/source/conf.py, doc/en/user/source/conf.py, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/Dialect.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/FilterToCatalogSQL.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/OracleDialect.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/QueryBuilder.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcloader/JDBCLoaderProperties.java, src/community/jdbcconfig/src/main/resources/applicationContext.xml, src/community/jdbcconfig/src/main/resources/jdbcconfig.properties, src/community/jdbcconfig/src/main/resources/jdbcconfig.properties.h2, src/community/jdbcconfig/src/main/resources/jdbcconfig.properties.postgres, src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/JDBCConfigTestSupport.java, src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/QueryBuilderTest.java
2.19.x backport for GEOS-10842.
=> [2.19.x][GEOS-10842] Escape user inputs in SQL queries

doc/en/developer/source/conf.py, doc/en/developer/source/programming-guide/wps-services/design-guide.rst, doc/en/user/source/conf.py, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/Dialect.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/FilterToCatalogSQL.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/OracleDialect.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/QueryBuilder.java, src/community/jdbcconfig/src/main/java/org/geoserver/jdbcloader/JDBCLoaderProperties.java, src/community/jdbcconfig/src/main/resources/applicationContext.xml, src/community/jdbcconfig/src/main/resources/jdbcconfig.properties, src/community/jdbcconfig/src/main/resources/jdbcconfig.properties.h2, src/community/jdbcconfig/src/main/resources/jdbcconfig.properties.postgres, src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/JDBCConfigTestSupport.java, src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/QueryBuilderTest.java
[GEOS-10839] Add JDBC Configuration parameter to disable SQL comments and pretty-printing
=> [2.18.x][GEOS-10842] Escape user inputs in SQL queries 

src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/ogcapi/dggs/DGGSService.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIContentNegotiationManager.java, src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CoveragesService.java, src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/features/FeatureService.java, src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/ogcapi/images/ImagesService.java, src/community/ogcapi/ogcapi-styles/src/main/java/org/geoserver/ogcapi/styles/StylesService.java, src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/tiles/TilesService.java
[![GEOS-10854](https://badgen.net/badge/JIRA/GEOS-10854/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10854)
The resource at "openapi.json" would not work anymore after the Spring upgrade. Fixes included.
=> [GEOS-10854] Follow up Spring upgrade, make tests pass again

src/pom.xml
=> [Backport 2.22.x] Bump commons-fileupload from 1.4 to 1.5 in /src

src/pom.xml
=> [Backport 2.21.x] Bump commons-fileupload from 1.4 to 1.5 in /src

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/JMSXStreamFactory.java, src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/DocumentFile.java, src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/CatalogUtils.java, src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogEventHandler.java, src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogModifyEventHandler.java, src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/rest/ClusterController.java, src/community/jms-cluster/jms-geoserver/src/main/resources/applicationContext.xml, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/DocumentFileTest.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogModifyEventHandlerTest.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/CatalogDiffVisitor.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/InfoDiff.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/IntegrationTest.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/IntegrationTestsUtils.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/rest/ClusterControllerTest.java, src/main/src/main/java/org/geoserver/config/util/SecureXStream.java, src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
[![GEOS-10517](https://badgen.net/badge/JIRA/GEOS-10517/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10517)
Rebased from the backport bot work
=> [GEOS-10517] jms-cluster classes missing from XStream security configuration (2.21.x backport)

src/community/oseo/oseo-service/src/main/java/org/geoserver/opensearch/eo/response/DescriptionTransformer.java, src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/AbstractItemsHTMLMessageConverter.java, src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/STACService.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/ApiTest.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/stac/LandingPageTest.java
Tests in this community module have accumulated failures due to various changes all landing in a short amount of time in GeoTools and GeoServer. This PR makes the tests pass again.
=> Restore OpenSearch build after changes in OGC API, GeoTools XML encoding and the Spring upgrade

src/community/cov-json/pom.xml, src/community/ogcapi/pom.xml, src/community/oseo/pom.xml, src/community/security/oauth2/oauth2-core/pom.xml, src/community/wmts-styles/pom.xml, src/extension/vectortiles/pom.xml, src/pom.xml, src/web/app/pom.xml
[![GEOS-10869](https://badgen.net/badge/JIRA/GEOS-10869/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10869)
Backport #6617
=> [Backport 2.22.x] [GEOS-10869] Jayway JSON Path libraries not included anymore on GeoServer packages

src/community/cov-json/pom.xml, src/community/ogcapi/pom.xml, src/community/oseo/pom.xml, src/community/security/oauth2/oauth2-core/pom.xml, src/community/wmts-styles/pom.xml, src/extension/vectortiles/pom.xml, src/pom.xml, src/web/app/pom.xml
[![GEOS-10869](https://badgen.net/badge/JIRA/GEOS-10869/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10869)
Backport #6617
=> [Backport 2.21.x] [GEOS-10869] Jayway JSON Path libraries not included anymore on GeoServer packages

doc/en/user/source/community/ogc-api/features/index.rst
Did not fail in https://github.com/geoserver/geoserver/pull/6632 because the docs build was not run
=> Align docs with new package structure of OGC APIs

src/main/src/main/java/org/geoserver/config/GeoServerLoader.java, src/main/src/main/java/org/geoserver/config/GeoServerLoaderProxy.java, src/main/src/main/java/org/geoserver/config/impl/GeoServerImpl.java, src/main/src/test/java/org/geoserver/GeoServerLifecycleShutdownTest.java, src/main/src/test/java/org/geoserver/GeoServerLifecycleTest.java, src/main/src/test/java/org/geoserver/GeoServerLifecycleTestSupport.java, src/main/src/test/java/org/geoserver/GeoServerLifecycleTests.java, src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
[![GEOS-6313](https://badgen.net/badge/JIRA/GEOS-6313/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-6313)
This is another attempt to resolve the shutdown problems of GEOS-6313 which are around since 2014. 
Similar problems are also described by [GEOS-8122]. Those are fixed by manually calling [getGeoServer().dispose()](https://github.com/geoserver/geoserver/commit/849bced5b29c2919310372af42b8d591c17e984f).
This fixed the unit tests but not the source of the problem: Calling `Geoserver.dispose()` from `applicationContext.close()` was too late to acquire the necessary `GeoServerLifecycleHandler` beans and throws an exception. This inhibits calling `catalog.dispose()` due to a missing finally block. This can be fixed easily.
A unit test `GeoServerLifecycleTests` verifies calling the …
=> GEOS-6313 Lifecycle handlers during shutdown

doc/en/user/source/extensions/importer/rest_reference.rst, src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AttributesToPointGeometryTransform.java, src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/converters/ImportJSONReader.java, src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/converters/ImportJSONWriter.java, src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/AttributesToPointGeometryTransformTest.java, src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/ImportTransformTest.java, src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/ImporterIntegrationTest.java
[![GEOS-10870](https://badgen.net/badge/JIRA/GEOS-10870/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10870)
See https://osgeo-org.atlassian.net/browse/GEOS-10870
Added support of pointFieldName to [ImportJSONReader](https://github.com/Judge73/geoserver/blob/37ccb262b1fa13741a412309273ad3597a93f332/src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/converters/ImportJSONReader.java#L350)/[Writer](https://github.com/Judge73/geoserver/blob/37ccb262b1fa13741a412309273ad3597a93f332/src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/converters/ImportJSONWriter.java#L470) to set if from REST API calls. 
Also added preserveGeometry flag to prevent [AttributesToPointGeometryTransform](https://github.com/Judge73/geoserver/blob/37ccb262b1fa13741a412309273a …
=> [GEOS-10870] Allow importer AttributesToPointGeometryTransform to preserve original geometries, and to configure the name of the target geometry

src/platform/src/main/java/org/geoserver/platform/resource/FileSystemResourceStore.java, src/platform/src/main/java/org/geoserver/platform/resource/Files.java, src/platform/src/test/java/org/geoserver/platform/resource/ResourceTheoryTest.java
[![GEOS-10705](https://badgen.net/badge/JIRA/GEOS-10705/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10705)
After merging [GEOS-10723] [GEOS-10724] and [GEOS-10743], we now can realize the idea to throw an `Exception` in `Resource.in()` if the file does not exist. 
Finally `XStreamPersister.load(InputStream)` is affected by this change, too. All usages already have some error handling block. But they are sensitive on `IOException` but not on `IllegalStateException`. So I introduced a new `XStreamPersister.load(Resource)` method which throws an `FileNotFoundException` if the resource is not of `Type.RESOURCE`.
This replaces the boilerplate try/resource blocks and integrates smoothly, since an `IOException` is already expected.
I noticed some cases where the `InputStream` was …
=> [10705] Loading missing resources creates unsolicited empty files

src/extension/pom.xml
[![GEOS-10878](https://badgen.net/badge/JIRA/GEOS-10878/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10878)
Backport #6649
=> [Backport 2.21.x] [GEOS-10878] wps-multidimensional and wps-jdbc are not being deployed on maven repo

src/extension/pom.xml
[![GEOS-10878](https://badgen.net/badge/JIRA/GEOS-10878/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10878)
Backport #6649
=> [Backport 2.22.x] [GEOS-10878] wps-multidimensional and wps-jdbc are not being deployed on maven repo

src/main/src/main/java/applicationContext.xml, src/main/src/main/java/org/geoserver/filters/HTTPMethodFilter.java, src/main/src/test/java/org/geoserver/filters/HTTPMethodFilterTest.java
[![GEOS-10879](https://badgen.net/badge/JIRA/GEOS-10879/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10879)
added tests
=> [GEOS-10879] Dispatcher should not respond to non standard HTTP methods

src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/FeatureTest.java
[![GEOS-10880](https://badgen.net/badge/JIRA/GEOS-10880/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10880)
Needs https://github.com/geotools/geotools/pull/4206 for the test to actually pass (but no build will run it, so I expect to get a green anyways)
=> [GEOS-10880] OGC API Features cannot handle crs-bbox with uri "http://www.opengis.net/def/crs/OGC/1.3/CRS84"

src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/FeatureResponseMessageConverter.java
[![GEOS-10881](https://badgen.net/badge/JIRA/GEOS-10881/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10881)
=> [GEOS-10881] Add Content-Crs header to OGC API

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIBBoxParser.java, src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/FeatureService.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/FeatureTest.java
[![GEOS-10884](https://badgen.net/badge/JIRA/GEOS-10884/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10884)
Currently returns a 500 instead.
=> [GEOS-10884] OGC API features should return a 400 when bbox-crs contains invalid content

src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/FeatureResponseMessageConverter.java, src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/HttpHeaderContentCrsAppender.java, src/community/ogcapi/ogcapi-features/src/main/resources/applicationContext.xml, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/FeatureTest.java
[![GEOS-10885](https://badgen.net/badge/JIRA/GEOS-10885/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10885)
added test
=> [GEOS-10885] Remove Axis Order from OGC API Header

src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/HttpHeaderContentCrsAppender.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/FeatureTest.java
[![GEOS-10887](https://badgen.net/badge/JIRA/GEOS-10887/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10887)
=> [GEOS-10887] Add angle brackets to OGC API CRS Header

src/pom.xml
[![GEOS-10863](https://badgen.net/badge/JIRA/GEOS-10863/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10863)
Backport #6611
=> [Backport 2.22.x] [GEOS-10863] Update Oracle JDBC driver to 19.18.0.0

src/pom.xml
[![GEOS-10863](https://badgen.net/badge/JIRA/GEOS-10863/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10863)
Backport #6611
=> [Backport 2.21.x] [GEOS-10863] Update Oracle JDBC driver to 19.18.0.0

src/release/installer/win/build/geoserver_winsetup.nsi
Backport #6669
**Authored by:** @juanluisrp
=> [Backport 2.22.x] [GEOS-10890] Wrong path for the license file in the Windows installer script

src/release/installer/win/build/geoserver_winsetup.nsi
Backport #6669
**Authored by:** @juanluisrp
=> [Backport 2.23.x] [GEOS-10890] Wrong path for the license file in the Windows installer script

doc/en/developer/source/release-guide/index.rst
The "Post the Documentation" section no longer represents current practice, we just rely on maint/stable/main (see email list from Summer 2022)
Ask in a comment if you have troubles with any of them. -->
=> Remove "Post the Documentation" from Release guide

src/extension/control-flow/src/test/java/org/geoserver/flow/controller/AbstractFlowControllerTest.java, src/extension/control-flow/src/test/java/org/geoserver/flow/controller/PriorityFlowControllerTest.java
[![GEOS-10894](https://badgen.net/badge/JIRA/GEOS-10894/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10894)
See ticket
=> [GEOS-10894] Random control-flow errors on Mac builds

src/community/ogcapi/ogcapi-core/pom.xml, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/QueryablesBuilder.java, src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/QueryablesBuilderComplexFeaturesTest.java
[![GEOS-10802](https://badgen.net/badge/JIRA/GEOS-10802/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10802)
=> GEOS-10802 OGC API: queryables page crashed on complex features

src/community/ogcapi/ogcapi-core/pom.xml, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/QueryablesBuilder.java, src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/QueryablesBuilderComplexFeaturesTest.java
[![GEOS-10802](https://badgen.net/badge/JIRA/GEOS-10802/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10802)
Backport #6565
=> [Backport 2.23.x] GEOS-10802 OGC API: queryables page crashed on complex features

src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/XMLTemplateWriter.java, src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/HTMLHtmlFeature.xhtml, src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/HTMLMappedFeature.xhtml, src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/HTMLGetSimpleFeaturesResponseWFSTest.java, src/community/features-templating/features-templating-ows/src/test/resources/org/geoserver/featurestemplating/response/HtmlFeatures.properties
[![GEOS-10899](https://badgen.net/badge/JIRA/GEOS-10899/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10899)
https://osgeo-org.atlassian.net/browse/GEOS-10899
=> [GEOS-10899] Features template escapes twice HTML produced outputs

src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/XMLTemplateWriter.java, src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/HTMLHtmlFeature.xhtml, src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/HTMLMappedFeature.xhtml, src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/HTMLGetSimpleFeaturesResponseWFSTest.java, src/community/features-templating/features-templating-ows/src/test/resources/org/geoserver/featurestemplating/response/HtmlFeatures.properties
[![GEOS-10899](https://badgen.net/badge/JIRA/GEOS-10899/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10899)
Backport #6693
=> [Backport 2.22.x] [GEOS-10899] Features template escapes twice HTML produced outputs

src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/XMLTemplateWriter.java, src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/HTMLHtmlFeature.xhtml, src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/HTMLMappedFeature.xhtml, src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/HTMLGetSimpleFeaturesResponseWFSTest.java, src/community/features-templating/features-templating-ows/src/test/resources/org/geoserver/featurestemplating/response/HtmlFeatures.properties
[![GEOS-10899](https://badgen.net/badge/JIRA/GEOS-10899/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10899)
Backport #6693
=> [Backport 2.23.x] [GEOS-10899] Features template escapes twice HTML produced outputs

src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/XMLTemplateWriter.java, src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/HTMLHtmlFeature.xhtml, src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/HTMLMappedFeature.xhtml, src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/HTMLGetSimpleFeaturesResponseWFSTest.java, src/community/features-templating/features-templating-ows/src/test/resources/org/geoserver/featurestemplating/response/HtmlFeatures.properties
[![GEOS-10899](https://badgen.net/badge/JIRA/GEOS-10899/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10899)
Backport #6693
=> [Backport 2.21.x] [GEOS-10899] Features template escapes twice HTML produced outputs

src/pom.xml
[![GEOS-10904](https://badgen.net/badge/JIRA/GEOS-10904/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10904)
Backport #6706
=> [Backport 2.23.x] [GEOS-10904] Bump jettison from 1.5.3 to 1.5.4

src/pom.xml
[![GEOS-10904](https://badgen.net/badge/JIRA/GEOS-10904/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10904)
Backport #6706
=> [Backport 2.21.x] [GEOS-10904] Bump jettison from 1.5.3 to 1.5.4

src/main/src/main/java/org/geoserver/catalog/impl/FeatureTypeValidator.java, src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java, src/restconfig/src/test/java/org/geoserver/rest/catalog/FeatureTypeControllerTest.java
[![GEOS-10593](https://badgen.net/badge/JIRA/GEOS-10593/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10593)
Backport #6702
=> [Backport 2.21.x] [GEOS-10593] Regression: Creating SQL View via REST API and explicit attribute list is no-longer possible

src/extension/csw/core/src/main/resources/org/geoserver/csw/store/internal/Record.default.properties, src/extension/csw/csw-iso/src/main/resources/org/geoserver/csw/store/internal/MD_Metadata.default.properties
[![GEOS-10905](https://badgen.net/badge/JIRA/GEOS-10905/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10905)
This PR replaces the if_then_else function call with a simple property name to allow sorting by identifiers when using the default CSW properties files.  The if_then_else identifier was probably needed a long time ago before layer groups were allowed in workspaces but every layer and layer groups now has a prefixedName value.  The default files are only used if the properties file is missing from the data directory so this PR will only affect new GeoServer installations.  
The CSW unit tests use separate properties files in the src/test/resources directory that do not use if_then_else in the identifier so hopefully unit tests aren't required for this PR since it is just …
=> [GEOS-10905] Default CSW properties do not allow sorting by identifiers

src/pom.xml
[![GEOS-10907](https://badgen.net/badge/JIRA/GEOS-10907/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10907)
Backport #6718
=> [Backport 2.23.x] [GEOS-10907] Update spring.version from 5.3.25 to 5.3.26 and spring.security.version from 5.7.6 to 5.7.7

doc/en/user/source/styling/sld/extensions/pointsymbols.rst
A small documentation change; as it was not obvious why a style would not draw (answer was the associated mark factory was not selected in WMS Settings; but there is no documentation for users on what they have to select).
=> Document what to MarkFactory to select in WMS settings for each styling extension

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/LandingPageSlashFilter.java, src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/HelloServiceTrailingSlashOffTest.java
[![GEOS-10895](https://badgen.net/badge/JIRA/GEOS-10895/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10895)
Still part of the GEOS-10895 series, found out there is an index out of bounds exception when accessing "http://localhost:8080/geoserver" due to the landing page exception filter.
=> [GEOS-10895] Fix for /geoserver path causing an out of bounds exception (when trying to get to the home page)

src/release/ext-excel.xml
[![GEOS-10920](https://badgen.net/badge/JIRA/GEOS-10920/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10920)
Backport #6750
=> [Backport 2.22.x] [GEOS-10920] Excel output format packaging misses dependencies, cannot produce .xls

src/release/ext-excel.xml
[![GEOS-10920](https://badgen.net/badge/JIRA/GEOS-10920/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10920)
Backport #6750
=> [Backport 2.21.x] [GEOS-10920] Excel output format packaging misses dependencies, cannot produce .xls

src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/XMLTemplateWriter.java, src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/HTMLMappedFeature.xhtml, src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/wfs/TemplateGetFeatureResponseHelper.java, src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/ComplexGetFeatureInfoTest.java, src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/HTMLGetComplexFeatureResponseTest.java, src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/HTMLGetSimpleFeaturesResponseWFSTest.java, src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
https://osgeo-org.atlassian.net/browse/GEOS-10921
- Fix for double escaping of html when features-templating module is enabled. Changed used for features-templating XMLFactory [here](https://github.com/geosolutions-it/geoserver/blob/44c5b94bc172e116b7bddf74e31935d5966c24eb/src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/wfs/TemplateGetFeatureResponseHelper.java#L73) to default, because previous version doesn't support non escaping property. Problem was with degree sign being escaped to \&deg; and then to \&amp;deg; by factory.
- Fixed existing tests to use Jsoup for HTML. Previously HTML responses were validated using XPath and requests were processed with getAsDom which escaped incorrect (for HTML) character \&amp;deg; from …
=> Features templating html double escaping fix

src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/JSONFGFeaturesResponse.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/FeatureTest.java
[![GEOS-10937](https://badgen.net/badge/JIRA/GEOS-10937/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10937)
Unlike GeoJSON.
=> [GEOS-10937] JSON-FG reprojected output should respect authority axis order

src/community/features-templating/features-templating-ows/pom.xml, src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/TemplateCallback.java, src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/wfs/HTMLTemplateResponse.java, src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/wfs/JSONLDGetFeatureResponse.java, src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/wfs/GetCapabilitiesTest.java, src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/wfs/WfsGetCapabilitiesTest.java, src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/wms/WmsGetCapabilitiesTest.java, src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/wms/WmsGetFeatureInfoTest.java
[![GEOS-10922](https://badgen.net/badge/JIRA/GEOS-10922/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10922)
Submitting GetCapabilities request with features-templating enabled results in exception due to 
WFSGetFeatureOutputFormat#getCapabilitiesElementName not being overriden for child classes present in features-templating (Fixed). Added test.
Features templating callback is executed for layers which doesn’t have template (for example during GetFeatureInfo) and without defined INFO_FORMAT param results in NullPointerException. Added additinal checkes to TemplateCallback's operationDispatched and responseDispatched methods to support only WMS GetFeatureInfo and WFS GetFeature requests.
Added check for ignoring template if INFO_FORMAT is text/plain (default if empty) because …
=> [GEOS-10922] Features templating exception on text/plain format

doc/en/user/source/extensions/geopkg-output/install.rst, doc/en/user/source/extensions/geopkg-output/usage.rst, src/extension/geopkg-output/src/main/java/org/geoserver/geopkg/wfs/GeoPackageGetFeatureOutputFormat.java, src/extension/geopkg-output/src/test/java/org/geoserver/geopkg/wfs/GeoPackageGetFeatureOutputFormatTest.java
[![GEOS-10837](https://badgen.net/badge/JIRA/GEOS-10837/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10837)
This allows the user to set a property (i.e. `-Dgeopackage.getfeatureoutput.tempdir=/path/to/temp`) that uses an alternative temp dir for the geopackage.  For people with the standard java temp dir being a mounted network drive, they should use this (pointing to a local drive).
GeoPKG (SQL Lite) has a lot of problems locking when writing to cloud (or network-mounted) file systems.
NOTE: I moved the test cases into the "proper" package (to match the class-under-test `GeoPackageGetFeatureOutputFormat`).
- [n/a] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end …
=> [GEOS-10837] geopackage output fails when java.io.tmpdir on network share

doc/en/user/source/extensions/geopkg-output/install.rst, doc/en/user/source/extensions/geopkg-output/usage.rst, src/extension/geopkg-output/src/main/java/org/geoserver/geopkg/wfs/GeoPackageGetFeatureOutputFormat.java, src/extension/geopkg-output/src/test/java/org/geoserver/geopkg/wfs/GeoPackageGetFeatureOutputFormatTest.java
[![GEOS-10837](https://badgen.net/badge/JIRA/GEOS-10837/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10837)
Backport #6607
**Authored by:** @davidblasby
=> [Backport 2.23.x] [GEOS-10837] geopackage output fails when java.io.tmpdir on network share

doc/en/user/source/extensions/geopkg-output/install.rst, doc/en/user/source/extensions/geopkg-output/usage.rst, src/extension/geopkg-output/src/main/java/org/geoserver/geopkg/wfs/GeoPackageGetFeatureOutputFormat.java, src/extension/geopkg-output/src/test/java/org/geoserver/geopkg/wfs/GeoPackageGetFeatureOutputFormatTest.java
[![GEOS-10837](https://badgen.net/badge/JIRA/GEOS-10837/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10837)
Backport #6607
**Authored by:** @davidblasby
=> [Backport 2.21.x] [GEOS-10837] geopackage output fails when java.io.tmpdir on network share

doc/en/user/source/extensions/geopkg-output/install.rst, doc/en/user/source/extensions/geopkg-output/usage.rst, src/extension/geopkg-output/src/main/java/org/geoserver/geopkg/wfs/GeoPackageGetFeatureOutputFormat.java, src/extension/geopkg-output/src/test/java/org/geoserver/geopkg/wfs/GeoPackageGetFeatureOutputFormatTest.java
[![GEOS-10837](https://badgen.net/badge/JIRA/GEOS-10837/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10837)
Backport #6607
**Authored by:** @davidblasby
=> [Backport 2.22.x] [GEOS-10837] geopackage output fails when java.io.tmpdir on network share

src/community/csw-iso/src/main/java/org/geoserver/csw/response/MetaDataTransformer.java, src/community/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/FeatureCatalogueTest.java
[![GEOS-10932](https://badgen.net/badge/JIRA/GEOS-10932/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10932)
Backport #6767
=> [Backport 2.21.x] [GEOS-10932] csw-iso: should only add 'xsi:nil = false' attribute

src/extension/csw/csw-iso/src/main/java/org/geoserver/csw/response/MetaDataTransformer.java, src/extension/csw/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/FeatureCatalogueTest.java
[![GEOS-10932](https://badgen.net/badge/JIRA/GEOS-10932/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10932)
Backport #6767
=> [Backport 2.22.x] [GEOS-10932] csw-iso: should only add 'xsi:nil = false' attribute

src/extension/csw/csw-iso/src/main/java/org/geoserver/csw/response/MetaDataTransformer.java, src/extension/csw/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/FeatureCatalogueTest.java
[![GEOS-10932](https://badgen.net/badge/JIRA/GEOS-10932/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10932)
Backport #6767
=> [Backport 2.23.x] [GEOS-10932] csw-iso: should only add 'xsi:nil = false' attribute

src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/catalog/CatalogImplWithJDBCFacadeTest.java, src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
[![GEOS-10858](https://badgen.net/badge/JIRA/GEOS-10858/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10858)
=> [GEOS-10858] support isolated workspaces other catalogfacades

src/main/src/main/java/org/geoserver/security/AccessLimits.java, src/main/src/main/java/org/geoserver/security/CoverageAccessLimits.java, src/main/src/main/java/org/geoserver/security/DataAccessLimits.java, src/main/src/main/java/org/geoserver/security/VectorAccessLimits.java, src/main/src/main/java/org/geoserver/security/WMSAccessLimits.java, src/main/src/main/java/org/geoserver/security/WMTSAccessLimits.java, src/main/src/main/java/org/geoserver/security/decorators/SecuredFeatureTypeInfo.java, src/main/src/test/java/org/geoserver/security/decorators/SecuredFeatureTypeInfoTest.java
[![GEOS-10957](https://badgen.net/badge/JIRA/GEOS-10957/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10957)
See ticket
=> [GEOS-10957] Support ResourceAccessManager implementations returning custom subclasess of AccessLimits

src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACTemplates.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/CollectionsTest.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/STACTestSupport.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/TemplatePropertyMapperTest.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/collections.ftl
[![GEOS-10955](https://badgen.net/badge/JIRA/GEOS-10955/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10955)
=> [GEOS-10955] STAC templates are initialised in the wrong location

src/web/app/src/test/java/org/geoserver/web/Start.java
[![GEOS-10965](https://badgen.net/badge/JIRA/GEOS-10965/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10965)
Changing from thread.run to thread.start bricked it. But calling "run" does not really start a new thread, is just executes the internal runnable, so it's easier to execute that code directly instead.
=> [GEOS-10965] Start in web/app does not work any longer

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/JMSXStreamFactory.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/IntegrationTest.java
[![GEOS-10975](https://badgen.net/badge/JIRA/GEOS-10975/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10975)
=> [GEOS-10975] JMS clustering reports error about ReferencedEnvelope type not being whitelisted in XStream

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/JMSXStreamFactory.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/IntegrationTest.java
[![GEOS-10975](https://badgen.net/badge/JIRA/GEOS-10975/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10975)
Backport #6836
=> [Backport 2.21.x] [GEOS-10975] JMS clustering reports error about ReferencedEnvelope type not being whitelisted in XStream

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/JMSXStreamFactory.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/IntegrationTest.java
[![GEOS-10975](https://badgen.net/badge/JIRA/GEOS-10975/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10975)
Backport #6836
=> [Backport 2.23.x] [GEOS-10975] JMS clustering reports error about ReferencedEnvelope type not being whitelisted in XStream

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/JMSXStreamFactory.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/IntegrationTest.java
[![GEOS-10975](https://badgen.net/badge/JIRA/GEOS-10975/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10975)
Backport #6836
=> [Backport 2.22.x] [GEOS-10975] JMS clustering reports error about ReferencedEnvelope type not being whitelisted in XStream

src/main/src/main/java/org/geoserver/ows/kvp/CQLFilterKvpParser.java, src/main/src/test/java/org/geoserver/ows/kvp/CQLFilterKvpParserTest.java, src/wfs/src/main/java/org/geoserver/wfs/kvp/BaseFeatureKvpRequestReader.java, src/wfs/src/test/java/org/geoserver/wfs/GetFeatureTest.java, src/wms/src/test/java/org/geoserver/wms/map/GetMapIntegrationTest.java
[![GEOS-10969](https://badgen.net/badge/JIRA/GEOS-10969/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10969)
Backport #6842
=> [Backport 2.23.x] [GEOS-10969] Empty CQL_FILTER-parameter should be ignored

src/main/src/main/java/org/geoserver/ows/kvp/CQLFilterKvpParser.java, src/main/src/test/java/org/geoserver/ows/kvp/CQLFilterKvpParserTest.java, src/wfs/src/main/java/org/geoserver/wfs/kvp/BaseFeatureKvpRequestReader.java, src/wfs/src/test/java/org/geoserver/wfs/GetFeatureTest.java, src/wms/src/test/java/org/geoserver/wms/map/GetMapIntegrationTest.java
[![GEOS-10969](https://badgen.net/badge/JIRA/GEOS-10969/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10969)
Backport #6842
=> [Backport 2.22.x] [GEOS-10969] Empty CQL_FILTER-parameter should be ignored

src/main/src/main/java/org/geoserver/ows/kvp/CQLFilterKvpParser.java, src/main/src/test/java/org/geoserver/ows/kvp/CQLFilterKvpParserTest.java, src/wfs/src/main/java/org/geoserver/wfs/kvp/BaseFeatureKvpRequestReader.java, src/wfs/src/test/java/org/geoserver/wfs/GetFeatureTest.java, src/wms/src/test/java/org/geoserver/wms/map/GetMapIntegrationTest.java
[![GEOS-10969](https://badgen.net/badge/JIRA/GEOS-10969/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10969)
Backport #6842
=> [Backport 2.21.x] [GEOS-10969] Empty CQL_FILTER-parameter should be ignored

doc/en/api/1.0.0/styles.yaml
Documentation update on style endpoints regarding extension precedence over content type header
=> Style endpoint doc update

src/main/src/main/java/org/geoserver/catalog/ResourcePool.java, src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java
[![GEOS-8162](https://badgen.net/badge/JIRA/GEOS-8162/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-8162)
Backport #6846
=> [Backport 2.23.x] [GEOS-8162] ResourcePool relative path processing for CVSDataStore file parameter

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/reader/CatalogFileReader.java
[![GEOS-10985](https://badgen.net/badge/JIRA/GEOS-10985/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10985)
=> [GEOS-10985] B/R of Geoserver catalog is broken with Geoserver 2.23.0

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/reader/CatalogFileReader.java
[![GEOS-10985](https://badgen.net/badge/JIRA/GEOS-10985/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10985)
Backport #6850
=> [Backport 2.23.x] [GEOS-10985] B/R of Geoserver catalog is broken with Geoserver 2.23.0

src/main/src/main/java/org/geoserver/catalog/ResourcePool.java, src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java
[![GEOS-8162](https://badgen.net/badge/JIRA/GEOS-8162/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-8162)
Backport #6846
=> [Backport 2.22.x] [GEOS-8162] ResourcePool relative path processing for CVSDataStore file parameter

src/community/schemaless-features/mongodb-schemaless/src/main/java/org/geoserver/schemalessfeatures/mongodb/data/MongoComplexContentDataAccess.java, src/community/schemaless-features/mongodb-schemaless/src/main/java/org/geoserver/schemalessfeatures/mongodb/data/MongoSchemalessFeatureSource.java, src/web/core/src/main/java/org/geoserver/web/data/layer/AttributeEditPage.html
[![GEOS-10973](https://badgen.net/badge/JIRA/GEOS-10973/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10973)
Added delegation of dwithin filter in cql to mongoDB for mongo schemaless plugin
Relies on [GEOT-7360](https://osgeo-org.atlassian.net/browse/GEOT-7360) DWITHIN support for mongo schemaless
=> [GEOS-10973] DWITHIN delegation to mongoDB

src/pom.xml
[![GEOS-10988](https://badgen.net/badge/JIRA/GEOS-10988/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10988)
Backport #6852
=> [Backport 2.23.x] [GEOS-10988] Update spring.version from 5.3.26 to 5.3.27 and spring-integration.version from 5.5.17 to 5.5.18

src/community/schemaless-features/mongodb-schemaless/src/main/java/org/geoserver/schemalessfeatures/mongodb/data/MongoComplexContentDataAccess.java, src/community/schemaless-features/mongodb-schemaless/src/main/java/org/geoserver/schemalessfeatures/mongodb/data/MongoSchemalessFeatureSource.java
[![GEOS-10973](https://badgen.net/badge/JIRA/GEOS-10973/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10973)
=> [Backport 2.22.x][GEOS-10973] DWITHIN delegation to mongoDB

src/main/src/main/java/org/geoserver/security/impl/LayerGroupContainmentCache.java
[![GEOS-10998](https://badgen.net/badge/JIRA/GEOS-10998/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10998)
[[GEOS-10998] LayerGroupContainmentCache is being rebuilt on each ApplicationEvent](https://osgeo-org.atlassian.net/browse/GEOS-10998)
Layer group cache was being rebuild on most of GS actions, which resulted in performance drop. Changed code to rebuild only on ContextRefreshedEvent
=> [GEOS-10998] LayerGroupContainmentCache is being rebuilt on each ApplicationEvent

src/kml/pom.xml, src/kml/src/main/java/org/geoserver/kml/regionate/CachedHierarchyRegionatingStrategy.java, src/kml/src/main/java/org/geoserver/kml/regionate/ExternalSortRegionatingStrategy.java, src/kml/src/main/java/org/geoserver/kml/regionate/GeometryRegionatingStrategy.java, src/kml/src/main/java/org/geoserver/kml/regionate/Tile.java, src/kml/src/test/java/org/geoserver/kml/GeoSearchKMLTest.java, src/kml/src/test/java/org/geoserver/kml/KMLReflectorTest.java, src/kml/src/test/java/org/geoserver/kml/KMLSuperOverlayTest.java, src/pom.xml
[![GEOS-10999](https://badgen.net/badge/JIRA/GEOS-10999/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10999)
Replaced H2 with HSQL for gs-kml module.
=> [GEOS-10999] Make GeoServer KML module rely on HSQLDB instead of H2

src/pom.xml
[![GEOS-11010](https://badgen.net/badge/JIRA/GEOS-11010/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11010)
Dependency upgrade with security fixes.  This PR should be backported.
=> [GEOS-11010] Upgrade guava from 30.1 to 32.0.0

src/release/ext-css.xml
[![GEOS-10980](https://badgen.net/badge/JIRA/GEOS-10980/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10980)
=> [GEOS-10980] CSS extension lacks ASM JARs as of 2.23.0, stops rendering layer when style references a file

src/pom.xml
[![GEOS-10936](https://badgen.net/badge/JIRA/GEOS-10936/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10936)
Backport #6885
=> [Backport 2.23.x] [GEOS-10936] YSLD and OGC API modules are incompatible

src/pom.xml
[![GEOS-10936](https://badgen.net/badge/JIRA/GEOS-10936/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10936)
Backport #6885
=> [Backport 2.22.x] [GEOS-10936] YSLD and OGC API modules are incompatible

src/release/ext-css.xml
[![GEOS-10980](https://badgen.net/badge/JIRA/GEOS-10980/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10980)
Backport #6884
=> [Backport 2.23.x] [GEOS-10980] CSS extension lacks ASM JARs as of 2.23.0, stops rendering layer when style references a file

src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java, src/security/security-tests/src/test/java/org/geoserver/security/impl/AbstractAuthorizationTest.java, src/security/security-tests/src/test/java/org/geoserver/security/impl/DefaultDataAccessManagerTreeTest.java, src/security/security-tests/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java, src/security/security-tests/src/test/java/org/geoserver/security/impl/complex.properties
[![GEOS-10997](https://badgen.net/badge/JIRA/GEOS-10997/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10997)
fixed reversed superclass
more fixed super
=> [GEOS-10997] Data Security Layer groups

src/community/taskmanager/core/pom.xml, src/community/taskmanager/metadata/pom.xml, src/community/taskmanager/s3/pom.xml, src/web/app/pom.xml
[![GEOS-10968](https://badgen.net/badge/JIRA/GEOS-10968/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10968)
=> [GEOS-10968] task manager: fix dependendies for java 11

src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/tasks/CopyTableTaskTypeImpl.java
[![GEOS-10931](https://badgen.net/badge/JIRA/GEOS-10931/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10931)
=> [GEOS-10931] Taskmanager: copytabletask: drop table in transaction

src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/ExtTypes.java, src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/tasks/DbLocalPublicationTaskTypeImpl.java, src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/tasks/FileLocalPublicationTaskTypeImpl.java
[![GEOS-11022](https://badgen.net/badge/JIRA/GEOS-11022/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11022)
=> [GEOS-11022] Taskmanager: support isolated catalog facades

src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/data/LatestBatchRun.java
[![GEOS-10931](https://badgen.net/badge/JIRA/GEOS-10931/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10931)
=> [GEOS-10931] taskmanager: fix missing serializable

src/extension/metadata/src/main/resources/org/geoserver/metadata/data/service/impl/featureCatalog.yaml, src/extension/metadata/src/test/java/org/geoserver/metadata/data/service/ConfigurationServiceTest.java
[![GEOS-11024](https://badgen.net/badge/JIRA/GEOS-11024/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11024)
=> [GEOS-11024] metadata: add datetime field type to feature catalog

src/pom.xml
[![GEOS-11030](https://badgen.net/badge/JIRA/GEOS-11030/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11030)
Backport #6935
=> [Backport 2.23.x] [GEOS-11030] Update jetty-server from 9.4.48.v20220622 to 9.4.51.v20230217 in /src

src/main/src/main/java/org/geoserver/GeoserverInitStartupListener.java
[![GEOS-11026](https://badgen.net/badge/JIRA/GEOS-11026/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11026)
No functional change change to logging, was missed during [GEOS-10992] activity. 
=> [GEOS-11026] Only WARN on h2 unload failure if H2 driver available

src/main/src/main/java/org/geoserver/GeoserverInitStartupListener.java
[![GEOS-11026](https://badgen.net/badge/JIRA/GEOS-11026/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11026)
Backport #6939
=> [Backport 2.23.x] [GEOS-11026] Only WARN on h2 unload failure if H2 driver available

src/extension/metadata/src/main/resources/org/geoserver/metadata/data/service/impl/featureCatalog.yaml, src/extension/metadata/src/test/java/org/geoserver/metadata/data/service/ConfigurationServiceTest.java
[![GEOS-11024](https://badgen.net/badge/JIRA/GEOS-11024/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11024)
Backport #6928
=> [Backport 2.22.x] [GEOS-11024] metadata: add datetime field type to feature catalog

src/extension/metadata/src/main/resources/org/geoserver/metadata/data/service/impl/featureCatalog.yaml, src/extension/metadata/src/test/java/org/geoserver/metadata/data/service/ConfigurationServiceTest.java
[![GEOS-11024](https://badgen.net/badge/JIRA/GEOS-11024/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11024)
Backport #6928
=> [Backport 2.23.x] [GEOS-11024] metadata: add datetime field type to feature catalog

src/extension/metadata/src/main/java/org/geoserver/metadata/web/resource/WicketResourceResourceLoader.java, src/extension/metadata/src/test/java/org/geoserver/metadata/AbstractMetadataTest.java, src/extension/metadata/src/test/java/org/geoserver/metadata/EmptyConfigurationTest.java
[![GEOS-10979](https://badgen.net/badge/JIRA/GEOS-10979/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10979)
=> [GEOS-10979] metadata: don't crash on missing properties file

doc/en/developer/source/conf.py, doc/en/docguide/source/conf.py, doc/en/user/source/conf.py
[![GEOS-11041](https://badgen.net/badge/JIRA/GEOS-11041/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11041)
=> [GEOS-11041] Use html_domain_indices = False to supress py-modindex.html

doc/en/user/source/production/config.rst
Document how to disable anonymous access to the layer preview page under topic _Running in a production environment_.
As extensively discussed on the user mailing list (_Remove Layer Preview from Login Page_), here's the documentation update recommended by @ianturton.
=> Documentation: Disable anonymous access to the layer preview page

src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/OSEOFactoryExtension.java, src/community/oseo/oseo-core/src/main/resources/applicationContext.xml, src/community/oseo/oseo-core/src/test/java/org/geoserver/opensearch/eo/OSEOFactoryExtensionTest.java
[![GEOS-11035](https://badgen.net/badge/JIRA/GEOS-11035/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11035)
tests
=> [GEOS-11035] Enabling OSEO from Workspace Edit Page Results in an NPE

doc/en/user/source/services/wms/vendor.rst, src/wms/src/main/java/applicationContext.xml, src/wms/src/main/java/org/geoserver/wms/kvp/FilterKvpParser.java, src/wms/src/test/java/org/geoserver/wms/map/png/GetMapIntegrationTest.java
[![GEOS-10903](https://badgen.net/badge/JIRA/GEOS-10903/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10903)
=> [GEOS-10903] WMS filtering with Filter 2.0 fails

src/release/ext-charts.xml, src/release/ext-sqlserver.xml
[![GEOS-11060](https://badgen.net/badge/JIRA/GEOS-11060/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11060)
Backport #6996
**Authored by:** @hyperman2
=> [Backport 2.23.x] [GEOS-11060] charts and mssql extension zips are missing the extension

src/wfs/src/main/java/org/geoserver/wfs/response/ShapeZipOutputFormat.java
Fixing spelling error from "unkwon" to "unknown" in ShapeZipOutputFormat
=> Fix spelling error

src/web/core/src/main/java/org/geoserver/web/data/resource/AttributeTypeInfoEditor.java, src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
[![GEOS-11069](https://badgen.net/badge/JIRA/GEOS-11069/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11069)
=> [GEOS-11069] Layer configuration page doesn't work for broken layers

src/community/security/keycloak/pom.xml, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml, src/community/web-service-auth/pom.xml, src/extension/wps/wps-core/pom.xml, src/pom.xml, src/web/core/pom.xml, src/wms/pom.xml
[![GEOS-11067](https://badgen.net/badge/JIRA/GEOS-11067/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11067)
Backport #7016
=> [Backport 2.23.x] [GEOS-11067] Upgrade wiremock to 2.35.0

src/community/security/keycloak/pom.xml, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml, src/community/web-service-auth/pom.xml, src/extension/wps/wps-core/pom.xml, src/pom.xml, src/web/core/pom.xml, src/wms/pom.xml
[![GEOS-11067](https://badgen.net/badge/JIRA/GEOS-11067/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11067)
Backport #7016
=> [Backport 2.22.x] [GEOS-11067] Upgrade wiremock to 2.35.0

src/web/core/src/main/java/org/geoserver/web/css/geoserver.css
[![GEOS-11033](https://badgen.net/badge/JIRA/GEOS-11033/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11033)
[GEOS-11033] WCS 2.0.1 DescribeCoverage axis order using layer projection policy (https://github.com/geoserver/geoserver/pull/6962)
Fix for the bug as mentioned in the issue above.
Change the order of CSS declarations (make it the last one) so the readonly style for the input is not overridden with other input styles.
=> [GEOS-11033] Fix the readonly style of an input field

src/web/core/src/main/java/org/geoserver/web/css/geoserver.css
[![GEOS-11084](https://badgen.net/badge/JIRA/GEOS-11084/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11084)
Backport #7035
**Authored by:** @MichelGabriel
=> [Backport 2.23.x] [GEOS-11084] Fix the readonly style of an input field

src/community/notification/pom.xml
The parent pom specifies 32.0.0-jre:
https://github.com/geoserver/geoserver/blob/f5876797ea151a63b5f1c3fae1e62aa91206da41/src/pom.xml#L1318-L1322
=> Use Guava version as specified in parent dependencyManagement (gs-notification community module)

src/pom.xml
[![GEOS-11094](https://badgen.net/badge/JIRA/GEOS-11094/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11094)
Backport #7056
=> [Backport 2.23.x] [GEOS-11094] Bump org.hsqldb:hsqldb:2.7.1 to 2.7.2

src/community/notification/pom.xml
=> [Backport 2.23.x] Use Guava version as specified in parent dependencyManagement (gs-notification community module)

src/pom.xml
[![GEOS-11095](https://badgen.net/badge/JIRA/GEOS-11095/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11095)
This upgrade fixes a problem in Eclipse.
It doesn't seem to influence the git tags within "Geoserver info" after a full build.
=> [GEOS-11095] Bump git-commit-id-plugin 4.0.3 -> 4.9.10

doc/en/user/source/community/taskmanager/user.rst, src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/DbSource.java, src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/Dialect.java, src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/GeometryTable.java, src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/impl/AbstractDbSourceImpl.java, src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/impl/DefaultDialectImpl.java, src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/impl/GenericDbSourceImpl.java, src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/impl/GeometryTableImpl.java, src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/impl/H2DbSourceImpl.java, src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/impl/InformixDbSourceImpl.java, src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/impl/PostgisDbSourceImpl.java, src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/impl/PostgisDialectImpl.java, src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/tasks/CopyTableTaskTypeImpl.java, src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/tasks/FileRemotePublicationTaskTypeImpl.java, src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/util/TaskManagerBeans.java, src/community/taskmanager/core/src/test/java/org/geoserver/taskmanager/tasks/CopyTableTaskTest.java, src/community/taskmanager/core/src/test/resources/applicationContext.xml, src/community/taskmanager/core/src/test/resources/h2/dbsource/create-source.sql, src/community/taskmanager/pom.xml
[![GEOS-11086](https://badgen.net/badge/JIRA/GEOS-11086/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11086)
=> [GEOS-11086] Taskmanager: database access improvements

src/extension/wps/wps-core/src/main/java/org/geoserver/wps/WPSInitializer.java, src/extension/wps/wps-core/src/test/java/org/geoserver/wps/WPSInitializerTest.java, src/main/src/main/java/org/geoserver/config/GeoServerLoader.java, src/main/src/main/java/org/geoserver/config/GeoServerReinitializer.java, src/main/src/main/java/org/geoserver/config/impl/GeoServerImpl.java
[![GEOS-10248](https://badgen.net/badge/JIRA/GEOS-10248/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10248)
During training / workshops I like to use the WPS module as an example of installing an extension. Sadly when this is done reloading the configuration shows a WPSInitialization error (as the listener cannot find a WPSInfo until it is available).
This pull request asks WPSInitializer to stop reinitializing itself during each global configuration event during a reload.
=> [GEOS-10248] Check WPSInitializer interaction with reload

src/main/src/main/java/org/geoserver/catalog/impl/CatalogInfoLookup.java, src/main/src/main/java/org/geoserver/catalog/impl/DefaultCatalogFacade.java, src/main/src/main/java/org/geoserver/catalog/impl/NamespaceInfoLookup.java, src/main/src/test/java/org/geoserver/catalog/impl/NamespaceInfoLookupTest.java
[![GEOS-11089](https://badgen.net/badge/JIRA/GEOS-11089/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11089)
Use a specialization of `CatalogInfoLookup` for `NamespaceInfo` that speeds up lookup of namespaces by URI.
With this patch and the one for [GEOS-11088](https://github.com/geoserver/geoserver/pull/7050), starting up from a catalog with 120k workspaces and 600k layers, goes from 18 to 4 minutes with the default geoserver loader, and down to less than a minute with the [datadir-catalog-loader](https://github.com/geoserver/geoserver/tree/580221af6da9aedcd4e0333ea205e92277ca4c44/src/community/datadir-catalog-loader) community module.
```
before   after
default loader                        1113s    294s
datadir-catalog-loader (4 trheads)     587s     98s
datadir-catalog-loader …
```
=> [GEOS-11089] Performance penalty adding namespaces while loading catalog

src/web/core/src/main/java/org/geoserver/web/data/workspace/WorkspaceProvider.java, src/web/core/src/test/java/org/geoserver/web/data/workspace/WorkspaceProviderTest.java
[![GEOS-11090](https://badgen.net/badge/JIRA/GEOS-11090/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11090)
Make webui's `WorkspaceProvider` use streaming catalog access
=> [GEOS-11090] Use Catalog streaming API in WorkspacePage

src/main/src/main/java/org/geoserver/catalog/impl/IsolatedCatalogFacade.java
[![GEOS-11087](https://badgen.net/badge/JIRA/GEOS-11087/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11087)
* Filter the iterator created by list(...) directly instead of building an ArrayList first
* Apply in-process filter to iterator in count() only if required, delegate to the proxied facade's count() method if `Dispatcher.REQUEST.get() == null`
=> [GEOS-11087] Fix IsolatedCatalogFacade unnecessary performance overhead

doc/en/user/source/extensions/monitoring/configuration.rst, src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorConfig.java, src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorFilter.java, src/extension/monitor/core/src/main/java/org/geoserver/monitor/ReverseDNSPostProcessor.java, src/extension/monitor/core/src/test/java/org/geoserver/monitor/MonitorConfigTest.java
[![GEOS-10856](https://badgen.net/badge/JIRA/GEOS-10856/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10856)
=> [GEOS-10856] geoserver monitor plugin - scaling troubles

src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/config/GeoFenceConfigurationManager.java
[![GEOS-11074](https://badgen.net/badge/JIRA/GEOS-11074/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11074)
The values in `geofence/geofence-server.properties` are not always read into the configuration class.
It happens randomly, so it seems it may a be a race condition.
The proposed fix is to programmatically load the property file using an InitializingBean:afterPropertiesSet() callback. In this way we'll also provide an entrypoint method to reload the configuration on request -- pls note that the GeoFence plugin is not realoading the configuration at runtime yet.
The basic changes are only related to the adding of the `afterPropertiesSet()` and `loadConfiguration()`, anyway prop names and save procedure have been refactored a lot, in order to allow furter clean up ASAP; we dont …
=> [GEOS-11074] GeoFence may not load property file at boot

src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/GeoServerKeycloakFilter.java, src/community/security/keycloak/src/test/java/org/geoserver/security/keycloak/GeoServerKeycloakFilterTest.java
[![GEOS-11068](https://badgen.net/badge/JIRA/GEOS-11068/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11068)
=> [GEOS-11068] Keycloak: custom admin role not picked up

src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/config/GeoFenceConfigurationManager.java
[![GEOS-11074](https://badgen.net/badge/JIRA/GEOS-11074/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11074)
Backport #7027
=> [Backport 2.23.x] [GEOS-11074] GeoFence may not load property file at boot

src/security/ldap/src/main/java/org/geoserver/security/ldap/BindingLdapAuthoritiesPopulator.java, src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPRoleService.java, src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPUserGroupService.java, src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPUtils.java, src/security/ldap/src/test/java/org/geoserver/security/ldap/LDAPUtilsTest.java
[![GEOS-10452](https://badgen.net/badge/JIRA/GEOS-10452/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10452)
This PR fixes a Role Services for LDAP/Active Directory issue [GEOS-10452].
After release 2.15.x in some cases using a LDAP Active Directory "Role Service" does not work anymore.
Tests shows when using an user defined with a CN with comma's (for example: <surname>, <firstname>), getting roles went well until release 2.15.x but after release 2.15.x getting roles results to none.
Getting roles for users etc. of a "Role Service" the GeoServer code uses a lowlevel Spring method: <ldap template>.search(...). In releases until 2.15.x when an user CN is used, the comma is "escaped" with "\". While debugging the currently master (20220619) tests shows that instead of "\" the token …
=> [GEOS-10452] Fixed Role Services for LDAP/Active Directory.

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AttributeType.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/FunctionsDocument.java, src/community/ogcapi/ogcapi-styles/src/main/java/org/geoserver/ogcapi/v1/styles/StyleAttributeExtractor.java
=> Remove unecessary org.opengis.geometry.Geometry usage from OGC API modules

src/pom.xml
[![GEOS-11070](https://badgen.net/badge/JIRA/GEOS-11070/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11070) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
A small build change to assist with https://github.com/geotools/geotools/pull/4367 testing.
This will allow GeoServer change ``mf.version`` to 2.3-SNAPSHOT which is deployed to repo.osgeo.org.
=> [GEOS-11070] Introduce mf.version to pom.xml to manage mapfish-print version

src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java, src/wms/src/test/java/org/geoserver/wms/map/GetMapKvpRequestReaderTest.java
[![GEOS-11116](https://badgen.net/badge/JIRA/GEOS-11116/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11116) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11116] GetMap/GetFeatureInfo with groups and view params can with mismatched layers/params

src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java, src/wms/src/test/java/org/geoserver/wms/map/GetMapKvpRequestReaderTest.java
[![GEOS-11116](https://badgen.net/badge/JIRA/GEOS-11116/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11116) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7107
**Authored by:** @dromagnoli
=> [Backport 2.23.x] [GEOS-11116] GetMap/GetFeatureInfo with groups and view params can with mismatched layers/params

src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java, src/wms/src/test/java/org/geoserver/wms/map/GetMapKvpRequestReaderTest.java
[![GEOS-11116](https://badgen.net/badge/JIRA/GEOS-11116/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11116) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7107
**Authored by:** @dromagnoli
=> [Backport 2.22.x] [GEOS-11116] GetMap/GetFeatureInfo with groups and view params can with mismatched layers/params (+Java8Fix)

src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/v1/maps/CollectionDocument.java, src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/v1/maps/MapsService.java, src/community/ogcapi/ogcapi-maps/src/main/resources/org/geoserver/ogcapi/v1/maps/collection_include.ftl, src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/CollectionTest.java, src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/MapsTest.java, src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/MapsTestSupport.java, src/community/ogcapi/ogcapi-maps/src/test/resources/org/geoserver/ogcapi/v1/maps/TimeElevationWithStartEnd.properties
[![GEOS-11118](https://badgen.net/badge/JIRA/GEOS-11118/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11118) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7113
=> [Backport 2.23.x] [GEOS-11118] Add Temporal Extents domain and datetime parameter to Maps API

src/pom.xml
=> [Backport 2.23.x] Bump org.eclipse.jetty:jetty-servlets from 9.4.51.v20230217 to 9.4.52.v20230823 in /src

src/pom.xml
[![GEOS-11132](https://badgen.net/badge/JIRA/GEOS-11132/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11132) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport of https://github.com/geoserver/geoserver/pull/7124
=> [GEOS-11132] Updating printing plugin to mapfish-print-lib 2.3-RC (2.24.x backport)

.github/workflows/javadoc.yml, src/pom.xml
The current javadoc:aggregate fails, despite the flag asking the javadoc plugin not to fail on errors.
This PR reverts the javadoc plugin upgrade, and adds a new javadoc aggregation build to guard against javadoc generation failure (just checks it can generate javadocs, we can switch to a strict check once the actual errors are resolved).
=> Revert javadoc maven plugin upgrade, add build to ensure aggregate works

src/web/security/core/src/main/java/org/geoserver/security/web/role/AbstractRolePage.java
[![GEOS-11130](https://badgen.net/badge/JIRA/GEOS-11130/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11130) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Return a sorted list
=> [GEOS-11130] Add a new role > parent role dropdown is not in any discernable order

src/web/security/core/src/main/java/org/geoserver/security/web/role/AbstractRolePage.java
[![GEOS-11130](https://badgen.net/badge/JIRA/GEOS-11130/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11130) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7130
=> [Backport 2.24.x] [GEOS-11130] Add a new role > parent role dropdown is not in any discernable order

src/web/security/core/src/main/java/org/geoserver/security/web/role/AbstractRolePage.java
[![GEOS-11130](https://badgen.net/badge/JIRA/GEOS-11130/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11130) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7130
=> [Backport 2.23.x] [GEOS-11130] Add a new role > parent role dropdown is not in any discernable order

src/community/geomesa/pom.xml
=> [Backport 2.22.x] Bump org.apache.avro:avro from 1.7.5 to 1.11.3 in /src/community/geomesa

src/community/geomesa/pom.xml
=> [Backport 2.23.x] Bump org.apache.avro:avro from 1.7.5 to 1.11.3 in /src/community/geomesa

src/community/geomesa/pom.xml
=> [Backport 2.24.x] Bump org.apache.avro:avro from 1.7.5 to 1.11.3 in /src/community/geomesa

src/main/src/main/java/org/geoserver/security/filter/GeoServerPreAuthenticationFilter.java
[![GEOS-11114](https://badgen.net/badge/JIRA/GEOS-11114/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11114) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
From GEOS-11114:
> We are using GeoServer in a Pre-Authentication scenario. GeoServerPreAuthenticationFilter is used as a basis for an own implementation which performs custom logic for retrieval of roles and also uses a custom principal implementation for certain reasons.
> 
> However currently we have to patch GeoServerPreAuthenticationFilter to integrate the required logic. Through a very small adjustment projects …
=> [GEOS-11114] Improve extensibility in Pre-Authentication scenarios

src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadAnimationProcess.java, src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadMapProcess.java, src/extension/wps-download/src/main/resources/applicationContext.xml, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/BaseDownloadImageProcessTest.java, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadAnimationProcessTest.java, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/RasterCleanerProcessListener.java, src/extension/wps-download/src/test/resources/TestContext.xml, src/wms/src/main/java/org/geoserver/wms/RasterCleaner.java
[![GEOS-11140](https://badgen.net/badge/JIRA/GEOS-11140/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11140) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
See Jira ticket for details
=> [GEOS-11140] WPS download can leak image references in the RasterCleaner

src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadAnimationProcess.java, src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadMapProcess.java, src/extension/wps-download/src/main/resources/applicationContext.xml, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/BaseDownloadImageProcessTest.java, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadAnimationProcessTest.java, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/RasterCleanerProcessListener.java, src/extension/wps-download/src/test/resources/TestContext.xml, src/wms/src/main/java/org/geoserver/wms/RasterCleaner.java
[![GEOS-11140](https://badgen.net/badge/JIRA/GEOS-11140/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11140) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7150
=> [Backport 2.22.x] [GEOS-11140] WPS download can leak image references in the RasterCleaner

src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadAnimationProcess.java, src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadMapProcess.java, src/extension/wps-download/src/main/resources/applicationContext.xml, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/BaseDownloadImageProcessTest.java, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadAnimationProcessTest.java, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/RasterCleanerProcessListener.java, src/extension/wps-download/src/test/resources/TestContext.xml, src/wms/src/main/java/org/geoserver/wms/RasterCleaner.java
[![GEOS-11140](https://badgen.net/badge/JIRA/GEOS-11140/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11140) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7150
=> [Backport 2.23.x] [GEOS-11140] WPS download can leak image references in the RasterCleaner

src/restconfig/src/main/java/org/geoserver/rest/resources/ResourceController.java, src/restconfig/src/test/java/org/geoserver/rest/resources/ResourceControllerTest.java
[![GEOS-11148](https://badgen.net/badge/JIRA/GEOS-11148/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11148) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR sets the "Content-Disposition: attachment" response header when getting files from the Resources REST API which mitigates a security issue and also fixes a bug where web browsers often download files as "f.txt".  The file's Content-Type is now determined from the servlet context which seems to be more robust than the URLConnection methods and is also more controllable by the server administrator.
Note that with this …
=> [GEOS-11148] Update response headers for the Resources REST API

src/pom.xml
Use the standard (since maven 3.3.1) `${maven.multiModuleProjectDirectory}` expression to resolve the `geoserverBaseDir` property, replacing the `org.commonjava.maven.plugins:directory-maven-plugin` plugin.
=> Resolve geoserverBaseDir maven property using standard means

src/web/core/src/main/java/org/geoserver/web/GeoServerBasePage.html
[![GEOS-11145](https://badgen.net/badge/JIRA/GEOS-11145/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11145) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7157
=> [Backport 2.24.x] [GEOS-11145] The GUI "wait spinner" is not visible any longer

src/web/core/src/main/java/org/geoserver/web/GeoServerBasePage.html
[![GEOS-11145](https://badgen.net/badge/JIRA/GEOS-11145/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11145) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7157
=> [Backport 2.23.x] [GEOS-11145] The GUI "wait spinner" is not visible any longer

src/restconfig/src/main/java/org/geoserver/rest/resources/ResourceController.java, src/restconfig/src/test/java/org/geoserver/rest/resources/ResourceControllerTest.java
[![GEOS-11148](https://badgen.net/badge/JIRA/GEOS-11148/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11148) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7161
=> [Backport 2.24.x] [GEOS-11148] Update response headers for the Resources REST API

src/restconfig/src/main/java/org/geoserver/rest/resources/ResourceController.java, src/restconfig/src/test/java/org/geoserver/rest/resources/ResourceControllerTest.java
[![GEOS-11148](https://badgen.net/badge/JIRA/GEOS-11148/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11148) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7161
=> [Backport 2.23.x] [GEOS-11148] Update response headers for the Resources REST API

src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadAnimationProcess.java, src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadMapProcess.java, src/extension/wps-download/src/main/resources/applicationContext.xml, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/BaseDownloadImageProcessTest.java, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadAnimationProcessTest.java, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/RasterCleanerProcessListener.java, src/extension/wps-download/src/test/resources/TestContext.xml, src/wms/src/main/java/org/geoserver/wms/RasterCleaner.java
[![GEOS-11140](https://badgen.net/badge/JIRA/GEOS-11140/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11140) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7150
=> [Backport 2.24.x] [GEOS-11140] WPS download can leak image references in the RasterCleaner

doc/en/developer/source/policies/community-modules.rst
[![GEOS-11134](https://badgen.net/badge/JIRA/GEOS-11134/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11134) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7188
=> [Backport 2.24.x] [GEOS-11134] build fix for literal include language markdown reference

src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/v1/maps/MapsService.java, src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/MapsTest.java
[![GEOS-11166](https://badgen.net/badge/JIRA/GEOS-11166/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11166) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11166] OGC API Maps HTML representation fail without datetime parameter

src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/v1/maps/MapsService.java, src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/MapsTest.java
[![GEOS-11166](https://badgen.net/badge/JIRA/GEOS-11166/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11166) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7198
=> [Backport 2.24.x] [GEOS-11166] OGC API Maps HTML representation fail without datetime parameter

doc/en/user/source/community/opensearch-eo/STAC.rst, src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/AggregateFactory.java, src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/functions/EoSummaries.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/CollectionsTest.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/functions/EoSummariesTest.java, src/community/oseo/oseo-stac/src/test/resources/collections.json
[![GEOS-11165](https://badgen.net/badge/JIRA/GEOS-11165/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11165) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11165] STAC Datacube switch eoSummaries bounds output to individual values

doc/en/user/source/community/opensearch-eo/STAC.rst, src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/AggregateFactory.java, src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/functions/EoSummaries.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/CollectionsTest.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/functions/EoSummariesTest.java, src/community/oseo/oseo-stac/src/test/resources/collections.json
[![GEOS-11165](https://badgen.net/badge/JIRA/GEOS-11165/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11165) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7195
=> [Backport 2.23.x] [GEOS-11165] STAC Datacube switch eoSummaries bounds output to individual values

doc/en/user/source/community/opensearch-eo/STAC.rst, src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/AggregateFactory.java, src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/functions/EoSummaries.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/CollectionsTest.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/functions/EoSummariesTest.java, src/community/oseo/oseo-stac/src/test/resources/collections.json
[![GEOS-11165](https://badgen.net/badge/JIRA/GEOS-11165/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11165) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7195
=> [Backport 2.24.x] [GEOS-11165] STAC Datacube switch eoSummaries bounds output to individual values

doc/en/developer/source/translation.rst
Update documentation on translation to match the migration from Transifex to WebLate
=> Update translation doc (transifex -> weblate)

src/community/notification/pom.xml
=> [Backport 2.24.x] Bump com.rabbitmq:amqp-client from 5.9.0 to 5.18.0 in /src/community/notification

src/community/notification-common/pom.xml
=> [Backport 2.24.x] Bump com.rabbitmq:amqp-client from 5.9.0 to 5.18.0 in /src/community/notification-common

doc/en/user/source/production/config.rst, src/web/app/src/main/webapp/WEB-INF/web.xml
[![GEOS-11173](https://badgen.net/badge/JIRA/GEOS-11173/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11173) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7218
=> [Backport 2.24.x] [GEOS-11173] Default to using HttpOnly session cookies

build/cite/geoserver/Dockerfile
This updates the docker base image to use a fluid  `tomcat:9-jdk11` which should be up2date when the image is built.
=> Update CITE docker Tomcat version to use 9-jdk11 as base image

src/platform/src/main/java/org/geoserver/platform/resource/Files.java, src/platform/src/main/java/org/geoserver/platform/resource/URIs.java, src/platform/src/test/java/org/geoserver/platform/resource/ResourceTheoryTest.java
[![GEOS-11176](https://badgen.net/badge/JIRA/GEOS-11176/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11176) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR validates file wrapper resource paths to prevent using '..' in the path.
=> [GEOS-11176] Add validation to file wrapper resource paths

doc/en/user/source/production/config.rst, src/main/src/main/java/org/geoserver/filters/XFrameOptionsFilter.java, src/main/src/test/java/org/geoserver/filters/XFrameOptionsFilterTest.java
[![GEOS-11155](https://badgen.net/badge/JIRA/GEOS-11155/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11155) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7181
=> [Backport 2.24.x] [GEOS-11155] Add the X-Content-Type-Options header

doc/en/user/source/production/config.rst, src/main/src/main/java/org/geoserver/filters/XFrameOptionsFilter.java, src/main/src/test/java/org/geoserver/filters/XFrameOptionsFilterTest.java
[![GEOS-11155](https://badgen.net/badge/JIRA/GEOS-11155/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11155) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7181
=> [Backport 2.23.x] [GEOS-11155] Add the X-Content-Type-Options header

doc/en/user/source/production/config.rst, src/main/src/main/java/org/geoserver/filters/XFrameOptionsFilter.java, src/main/src/test/java/org/geoserver/filters/XFrameOptionsFilterTest.java
[![GEOS-11155](https://badgen.net/badge/JIRA/GEOS-11155/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11155) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7181
=> [Backport 2.22.x] [GEOS-11155] Add the X-Content-Type-Options header

src/platform/src/main/java/org/geoserver/platform/resource/Files.java, src/platform/src/main/java/org/geoserver/platform/resource/URIs.java, src/platform/src/test/java/org/geoserver/platform/resource/ResourceTheoryTest.java
[![GEOS-11176](https://badgen.net/badge/JIRA/GEOS-11176/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11176) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7222
=> [Backport 2.24.x] [GEOS-11176] Add validation to file wrapper resource paths

src/platform/src/main/java/org/geoserver/platform/resource/Files.java, src/platform/src/main/java/org/geoserver/platform/resource/URIs.java, src/platform/src/test/java/org/geoserver/platform/resource/ResourceTheoryTest.java
[![GEOS-11176](https://badgen.net/badge/JIRA/GEOS-11176/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11176) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7222
=> [Backport 2.23.x] [GEOS-11176] Add validation to file wrapper resource paths

src/community/jms-cluster/jms-geoserver/pom.xml
=> [Backport 2.24.x] Bump org.apache.activemq:activemq-client from 5.15.11 to 5.15.16 in /src/community/jms-cluster/jms-geoserver

src/web/security/core/src/main/resources/GeoServerApplication.properties
Fixes label (was `configuration`)  
=> Fix URLcheck heading, grammar

src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/v1/features/openapi.yaml
[![GEOS-11170](https://badgen.net/badge/JIRA/GEOS-11170/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11170) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
As identified at tutorial session today. Just a left-over from the change from api -> openapi.
I also found the descriptive text was a link to the Conformance stuff, updated that too. It is a bit weak, but at least its no longer wrong.
=> [GEOS-11170] OGC API Features "/api" link is broken in OpenAPI page

src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/v1/features/openapi.yaml
[![GEOS-11170](https://badgen.net/badge/JIRA/GEOS-11170/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11170) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7214
**Authored by:** @bradh
=> [Backport 2.24.x] [GEOS-11170] OGC API Features "/api" link is broken in OpenAPI page

src/wms/src/main/java/org/geoserver/wms/featureinfo/RasterLayerIdentifier.java, src/wms/src/test/java/org/geoserver/wms/featureinfo/GetFeatureInfoJSONTest.java, src/wms/src/test/java/org/geoserver/wms/tiffspy/GeoTIFFSpyFormat.java, src/wms/src/test/java/org/geoserver/wms/tiffspy/GeoTIFFSpyFormatFactory.java, src/wms/src/test/java/org/geoserver/wms/tiffspy/GeoTIFFSpyReader.java, src/wms/src/test/resources/META-INF/services/org.geotools.coverage.grid.io.GridFormatFactorySpi, src/wms/src/test/resources/org/geoserver/wms/featureinfo/jiffleCondition.sld
[![GEOS-11200](https://badgen.net/badge/JIRA/GEOS-11200/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11200) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11200] GetFeatureInfo can fail on rendering transformations that generate a different raster

src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/VectorDownload.java, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
- Fixed the issue 
- Added test -- also overloaded test method `executeVectorDownload()` adding a new param 
=> [GEOS-11196] NPE in VectorDownload if ROI not defined

src/wms/src/main/java/org/geoserver/wms/featureinfo/RasterLayerIdentifier.java, src/wms/src/test/java/org/geoserver/wms/featureinfo/GetFeatureInfoJSONTest.java, src/wms/src/test/java/org/geoserver/wms/tiffspy/GeoTIFFSpyFormat.java, src/wms/src/test/java/org/geoserver/wms/tiffspy/GeoTIFFSpyFormatFactory.java, src/wms/src/test/java/org/geoserver/wms/tiffspy/GeoTIFFSpyReader.java, src/wms/src/test/resources/META-INF/services/org.geotools.coverage.grid.io.GridFormatFactorySpi, src/wms/src/test/resources/org/geoserver/wms/featureinfo/jiffleCondition.sld
[![GEOS-11200](https://badgen.net/badge/JIRA/GEOS-11200/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11200) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7264
=> [Backport 2.24.x] [GEOS-11200] GetFeatureInfo can fail on rendering transformations that generate a different raster

src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/VectorDownload.java, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
=> [Backport 2.20.x] [GEOS-11196] NPE in VectorDownload if ROI not defined

src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/VectorDownload.java, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
=> [Backport 2.21.x] [GEOS-11196] NPE in VectorDownload if ROI not defined

src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/VectorDownload.java, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
=> [Backport 2.22.x] [GEOS-11196] NPE in VectorDownload if ROI not defined

src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/VectorDownload.java, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
=> [Backport 2.23.x] [GEOS-11196] NPE in VectorDownload if ROI not defined

src/wms/src/main/java/org/geoserver/wms/featureinfo/RasterLayerIdentifier.java, src/wms/src/test/java/org/geoserver/wms/featureinfo/GetFeatureInfoJSONTest.java, src/wms/src/test/java/org/geoserver/wms/tiffspy/GeoTIFFSpyFormat.java, src/wms/src/test/java/org/geoserver/wms/tiffspy/GeoTIFFSpyFormatFactory.java, src/wms/src/test/java/org/geoserver/wms/tiffspy/GeoTIFFSpyReader.java, src/wms/src/test/resources/META-INF/services/org.geotools.coverage.grid.io.GridFormatFactorySpi, src/wms/src/test/resources/org/geoserver/wms/featureinfo/jiffleCondition.sld
[![GEOS-11200](https://badgen.net/badge/JIRA/GEOS-11200/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11200) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport of https://github.com/geoserver/geoserver/pull/7264 to 2.23.x
=> [Backport 2.23.x] [GEOS-11200] GetFeatureInfo can fail on rendering transformations tha t generate a different raster

src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/VectorDownload.java, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
=> [Backport 2.24.x] [GEOS-11196] NPE in VectorDownload if ROI not defined

src/community/ncwms/pom.xml
[![GEOS-11184](https://badgen.net/badge/JIRA/GEOS-11184/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11184) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7244
=> [Backport 2.24.x] [GEOS-11184] ncwms module has a compile dependency on gs-web-core test jar

src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/VectorDownload.java, src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
=> [Backport 2.19.x] [GEOS-11196] NPE in VectorDownload if ROI not defined

src/community/ncwms/pom.xml
[![GEOS-11184](https://badgen.net/badge/JIRA/GEOS-11184/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11184) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7244
=> [Backport 2.23.x] [GEOS-11184] ncwms module has a compile dependency on gs-web-core test jar

src/wms/src/main/java/org/geoserver/wms/svg/StreamingSVGMap.java, src/wms/src/test/java/org/geoserver/wms/svg/SVGMapProducerTest.java
[![GEOS-11152](https://badgen.net/badge/JIRA/GEOS-11152/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11152) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR updates the Simple SVG renderer to properly escape special characters from GeoServer catalog information.
NOTE: This PR only updates code that could be executed through actual GeoServer WMS GetMap requests and ignores any potential issues in dead code.
=> [GEOS-11152] Improve handling special characters in the Simple SVG Renderer

src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLController.java, src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLControllerTest.java
[![GEOS-11154](https://badgen.net/badge/JIRA/GEOS-11154/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11154) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7175
=> [Backport 2.24.x] [GEOS-11154] Improve handling special characters in the MapML HTML Page

src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLController.java, src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLControllerTest.java
[![GEOS-11154](https://badgen.net/badge/JIRA/GEOS-11154/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11154) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7175
=> [Backport 2.23.x] [GEOS-11154] Improve handling special characters in the MapML HTML Page

src/wms/src/main/java/org/geoserver/wms/featureinfo/FeatureInfoStylePreprocessor.java, src/wms/src/test/java/org/geoserver/wms/featureinfo/RenderingBasedFeatureInfoTest.java, src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java, src/wms/src/test/resources/org/geoserver/wms/featureinfo/geom-function.properties, src/wms/src/test/resources/org/geoserver/wms/featureinfo/geom-function.sld
[![GEOS-11203](https://badgen.net/badge/JIRA/GEOS-11203/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11203) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
https://osgeo-org.atlassian.net/browse/GEOS-11203
=> [GEOS-11203] WMS GetFeatureInfo bad WKT exception for label-geometry

src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java, src/security/security-tests/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java, src/security/security-tests/src/test/java/org/geoserver/security/impl/layerNegativeException.properties, src/security/security-tests/src/test/java/org/geoserver/security/impl/layerNegativeException2.properties, src/security/security-tests/src/test/java/org/geoserver/security/impl/layerPositiveException.properties, src/security/security-tests/src/test/java/org/geoserver/security/impl/layerPositiveException2.properties
[![GEOS-11223](https://badgen.net/badge/JIRA/GEOS-11223/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11223) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11223] Layer not visible in preview/capabilities if security closes the workspace, but allows access to the layer

src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java, src/security/security-tests/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java, src/security/security-tests/src/test/java/org/geoserver/security/impl/layerNegativeException.properties, src/security/security-tests/src/test/java/org/geoserver/security/impl/layerNegativeException2.properties, src/security/security-tests/src/test/java/org/geoserver/security/impl/layerPositiveException.properties, src/security/security-tests/src/test/java/org/geoserver/security/impl/layerPositiveException2.properties
[![GEOS-11223](https://badgen.net/badge/JIRA/GEOS-11223/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11223) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7313
=> [Backport 2.24.x] [GEOS-11223] Layer not visible in preview/capabilities if security closes the workspace, but allows access to the layer

src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java, src/security/security-tests/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java, src/security/security-tests/src/test/java/org/geoserver/security/impl/layerNegativeException.properties, src/security/security-tests/src/test/java/org/geoserver/security/impl/layerNegativeException2.properties, src/security/security-tests/src/test/java/org/geoserver/security/impl/layerPositiveException.properties, src/security/security-tests/src/test/java/org/geoserver/security/impl/layerPositiveException2.properties
[![GEOS-11223](https://badgen.net/badge/JIRA/GEOS-11223/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11223) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport to 2.23.x
=> [Backport 2.23.x] [GEOS-11223] Layer not visible in preview/capabilities if security closes the workspace, but allows access to the layer

src/main/src/main/java/org/geoserver/security/filter/GeoServerRequestHeaderAuthenticationFilter.java, src/main/src/test/java/org/geoserver/security/filter/GeoServerRequestHeaderAuthenticationFilterTest.java
[![GEOS-11235](https://badgen.net/badge/JIRA/GEOS-11235/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11235) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
or if no preauth headers are provided anymore.
See https://osgeo-org.atlassian.net/browse/GEOS-11235 for more details.
Without this change, we can end up with a persisting session across logout.
Tests: adding utests specific to this change. Runtime tested into a docker composition.
=> [GEOS-11235] preauthentication filters - session reuse even after having logout

src/main/src/main/java/org/geoserver/security/filter/GeoServerRequestHeaderAuthenticationFilter.java, src/main/src/test/java/org/geoserver/security/filter/GeoServerRequestHeaderAuthenticationFilterTest.java
[![GEOS-11235](https://badgen.net/badge/JIRA/GEOS-11235/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11235) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7326
**Authored by:** @pmauduit
=> [Backport 2.24.x] [GEOS-11235] preauthentication filters - session reuse even after having logout

src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdConnectIntegrationTest.java, src/extension/authkey/src/test/java/org/geoserver/security/AuthKeyAuthenticationTest.java, src/extension/authkey/src/test/java/org/geoserver/security/AuthenticationKeyOWSTest.java, src/main/src/main/java/org/geoserver/security/GeoServerSecurityManager.java, src/main/src/main/java/org/geoserver/security/validation/FilterConfigValidator.java, src/main/src/test/java/org/geoserver/data/test/MockCreator.java, src/security/security-tests/src/test/java/org/geoserver/security/GeoServerCustomFilterTest.java, src/security/security-tests/src/test/java/org/geoserver/security/MigrateFrom_2_2_Test.java, src/security/security-tests/src/test/java/org/geoserver/security/auth/AuthenticationFilterTest.java, src/web/core/src/main/java/org/geoserver/web/GeoServerBasePage.java, src/web/security/core/src/main/java/org/geoserver/security/web/auth/AuthenticationFiltersProvider.java, src/web/security/core/src/main/java/org/geoserver/security/web/auth/AuthenticationPage.java
[![GEOS-11051](https://badgen.net/badge/JIRA/GEOS-11051/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11051) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
**A parameterised webServiceUrl, when loaded from XML is not displayed as parameterised and when saved again, overwrites the parameterisation.  See the above issue for more details/screenshots.**
The problem is that when the filter config is cloned in order to be displayed for editing, the mapperParameters are resolved (i.e. `${...}` placeholders are converted into their real values).  This real value is then saved to the …
=> [GEOS-11051] Env parametrization does not save correctly in AuthKey extension

src/extension/csw/core/pom.xml, src/extension/csw/core/src/main/java/org/geoserver/csw/response/AcknowledgementTransformer.java, src/extension/csw/csw-iso/pom.xml, src/extension/sldService/pom.xml, src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/ClassifierTest.java, src/extension/wps/web-wps/pom.xml, src/extension/wps/web-wps/src/main/java/org/geoserver/wps/web/WPSExecuteTransformer.java, src/extension/wps/web-wps/src/test/java/org/geoserver/wps/web/WPSExecuteTransformerTest.java, src/ows/pom.xml, src/ows/src/test/java/org/geoserver/ows/OWS10ServiceExceptionHandlerTest.java, src/release/ext-wps.xml, src/wms/pom.xml, src/wms/src/main/java/org/geoserver/wms/featureinfo/RasterLayerIdentifier.java, src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformerTest.java
[![GEOS-11242](https://badgen.net/badge/JIRA/GEOS-11242/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11242) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR contains the following changes to completely remove the xalan:xalan and xalan:serializer dependencies:
1. WMS: Replaced the Xalan XMLChar class in RasterLayerIdentifier with the Eclipse EMF XMLChar class (covered by org.geoserver.wms.featureinfo.RasterLayerIdentifierTest). Updated the WMS GetCapabilities DTD unit test to be more lenient with the XML prolog.
2. OWS: Refactored unit tests to use the XPath API from …
=> [GEOS-11242] Remove the Xalan library

src/main/src/main/java/org/geoserver/catalog/impl/ModificationProxy.java, src/main/src/test/java/org/geoserver/catalog/impl/ModificationProxyTest.java
[![GEOS-11241](https://badgen.net/badge/JIRA/GEOS-11241/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11241) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
`ModificationProxy` breaks information hidding on `CatalogInfo.accept(CatalogVisitor)`, exposing the proxied object.
Follow up on commit 01bd2f2deb6fee761ca96b7035f6178996c6a16e (from GEOS-10356) which fixed it only for `FeatureTypeInfo`, by calling the appropriate `CatalogVisitor.visit(...)` overload method with the `ModificationProxy` proxy object and not with its internal `CatalogInfo`.
=> [GEOS-11241] ModificationProxy breaks information hidding on CatalogInfo.accept(CatalogVisitor)

doc/en/user/source/community/graticules/index.rst, src/community/graticule/pom.xml, src/community/graticule/src/main/java/org/geoserver/web/data/store/graticule/GraticulePanel.java, src/community/graticule/src/main/java/org/geotools/data/graticule/GraticuleDataStoreFactory.java, src/community/graticule/src/main/java/org/geotools/data/graticule/GraticuleFeatureReader.java, src/community/graticule/src/main/java/org/geotools/data/graticule/GraticuleFeatureSource.java, src/community/graticule/src/main/java/org/geotools/data/graticule/gridsupport/LineFeatureBuilder.java, src/community/graticule/src/main/java/org/geotools/process/vector/GraticuleLabelPointProcess.java, src/community/graticule/src/test/java/org/geoserver/web/data/store/graticule/GraticuleStoreEditPanelTest.java, src/community/graticule/src/test/java/org/geotools/data/graticule/GraticuleFeatureReaderTest.java, src/community/graticule/src/test/java/org/geotools/process/vector/GraticuleLabelPointProcessTest.java
Another set of improvements for the graticule subsystem, to fix: 
* A GUI issue (the envelope would always reset to the empty one on editing the store)
* Support multiple projections (graticule in one projection, display in another)
* Keep the labels always within the graticule bounds (the ones at the 4 corners fell out)
=> Graticule store/process improvements, round 2

src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/GeoServerKeycloakFilter.java, src/community/security/keycloak/src/test/java/org/geoserver/web/security/keycloak/KeycloakLoginButtonTest.java
[![GEOS-10933](https://badgen.net/badge/JIRA/GEOS-10933/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10933) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This fixes the failing logout when using the keycloak plugin. Also fixes a failing test in the plugin due do HTML changes.
=> [GEOS-10933] Fix keycloak plugin logout

src/main/src/main/java/org/geoserver/catalog/impl/ModificationProxy.java, src/main/src/test/java/org/geoserver/catalog/impl/ModificationProxyTest.java
[![GEOS-11241](https://badgen.net/badge/JIRA/GEOS-11241/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11241) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7329
=> [Backport 2.24.x] [GEOS-11241] ModificationProxy breaks information hidding on CatalogInfo.accept(CatalogVisitor)

src/wfs/src/main/java/org/geoserver/wfs/Transaction.java, src/wfs/src/test/java/org/geoserver/wfs/BatchManagerTest.java
[![GEOS-11255](https://badgen.net/badge/JIRA/GEOS-11255/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11255) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7346
**Authored by:** @iaunzu
=> [Backport 2.24.x] [GEOS-11255] Add support for multiple inserts with different idGen

src/wfs/src/main/java/org/geoserver/wfs/Transaction.java, src/wfs/src/test/java/org/geoserver/wfs/BatchManagerTest.java
[![GEOS-11255](https://badgen.net/badge/JIRA/GEOS-11255/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11255) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7346
**Authored by:** @iaunzu
=> [Backport 2.23.x] [GEOS-11255] Add support for multiple inserts with different idGen

doc/en/user/source/services/wfs/outputformats.rst, src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONBuilder.java, src/wfs/src/test/java/org/geoserver/wfs/json/GeoJSONBuilderTest.java
[![GEOS-11250](https://badgen.net/badge/JIRA/GEOS-11250/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11250) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This commit avoids a JSONException in case of a coordinate with infinite value (positive or negative). A coordinate with an infinite value will be encoded as a string "Infinity" or "-Infinity", depending on the coordinate sign.
=> [GEOS-11250] WFS GeoJSON encoder fails with an exception if an infinity number is used in the geometry

doc/en/user/source/services/wfs/outputformats.rst, src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONBuilder.java, src/wfs/src/test/java/org/geoserver/wfs/json/GeoJSONBuilderTest.java
[![GEOS-11250](https://badgen.net/badge/JIRA/GEOS-11250/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11250) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7343
**Authored by:** @mirco-romagnoli
=> [Backport 2.23.x] [GEOS-11250] WFS GeoJSON encoder fails with an exception if an infinity number is used in the geometry

doc/en/user/source/services/wfs/outputformats.rst, src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONBuilder.java, src/wfs/src/test/java/org/geoserver/wfs/json/GeoJSONBuilderTest.java
[![GEOS-11250](https://badgen.net/badge/JIRA/GEOS-11250/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11250) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7343
**Authored by:** @mirco-romagnoli
=> [Backport 2.24.x] [GEOS-11250] WFS GeoJSON encoder fails with an exception if an infinity number is used in the geometry

src/community/security/oauth2/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilter.java
[![GEOS-11290](https://badgen.net/badge/JIRA/GEOS-11290/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11290) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
As per description in GEOS issue:
With many WMS concurrent requests as anonymous user to a public layer, sometimes a request gets a 401.
This only happens when in the default filter chain there’s an oauth filter.
Problem is probably caused by a race condition where `null` is put into the SecurityContextHolder, and another thread reads it while expecting an anonymous context.
Since the error pops out once in hundred requests …
=> [GEOS-11290] With Oauth enabled, anon users get random auth requests

src/community/security/oauth2/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilter.java
[![GEOS-11290](https://badgen.net/badge/JIRA/GEOS-11290/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11290) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
As per description in GEOS issue:
With many WMS concurrent requests as anonymous user to a public layer, sometimes a request gets a 401.
This only happens when in the default filter chain there’s an oauth filter.
Problem is probably caused by a race condition where `null` is put into the SecurityContextHolder, and another thread reads it while expecting an anonymous context.
Since the error pops out once in hundred requests …
=> [Backport 2.24.x][GEOS-11290] With Oauth enabled, anon users get random auth requests

src/community/security/oauth2/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilter.java
[![GEOS-11290](https://badgen.net/badge/JIRA/GEOS-11290/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11290) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
As per description in GEOS issue:
With many WMS concurrent requests as anonymous user to a public layer, sometimes a request gets a 401.
This only happens when in the default filter chain there’s an oauth filter.
Problem is probably caused by a race condition where `null` is put into the SecurityContextHolder, and another thread reads it while expecting an anonymous context.
Since the error pops out once in hundred requests …
=> [Backport 2.23.x][GEOS-11290] With Oauth enabled, anon users get random auth requests

src/wms/src/main/java/org/geoserver/wms/legendgraphic/JSONLegendGraphicBuilder.java, src/wms/src/test/java/org/geoserver/wms/legendgraphic/JSONLegendGraphicOutputFormatTest.java
[![GEOS-11263](https://badgen.net/badge/JIRA/GEOS-11263/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11263) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Hi
This a a PR for [GEOS-11263](https://osgeo-org.atlassian.net/browse/GEOS-11263)
It applies the same strategy in ``BufferedImageLegendGraphicBuilder`` but in JSONLegendGraphicBuilder to filter out all rules with no features in the BBOX.
=> [GEOS-11263] hideEmptyRules not working in JSON LegendGraphic

src/ows/src/main/java/org/geoserver/ows/ClasspathPublisher.java, src/ows/src/test/java/org/geoserver/ows/ClasspathPublisherTest.java
[![GEOS-11288](https://badgen.net/badge/JIRA/GEOS-11288/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11288) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR updates ClasspathPublisher to prevent using backslash characters on Windows to traverse directories.
=> [GEOS-11288] Improve input validation in ClasspathPublisher

src/extension/metadata/src/main/java/org/geoserver/metadata/web/panel/MetadataPanel.java, src/extension/metadata/src/test/java/org/geoserver/metadata/data/service/ConfigurationServiceTest.java, src/extension/metadata/src/test/java/org/geoserver/metadata/web/ConditionTest.java, src/extension/metadata/src/test/java/org/geoserver/metadata/web/LayerMetadataTabTest.java, src/extension/metadata/src/test/java/org/geoserver/metadata/web/TabsTest.java, src/extension/metadata/src/test/resources/org/geoserver/metadata/metadata-ui.yaml
[![GEOS-11278](https://badgen.net/badge/JIRA/GEOS-11278/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11278) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7364
=> [Backport 2.24.x] [GEOS-11278] metadata: only selected tab is submitted

src/extension/metadata/src/main/java/org/geoserver/metadata/web/panel/MetadataPanel.java, src/extension/metadata/src/test/java/org/geoserver/metadata/data/service/ConfigurationServiceTest.java, src/extension/metadata/src/test/java/org/geoserver/metadata/web/ConditionTest.java, src/extension/metadata/src/test/java/org/geoserver/metadata/web/LayerMetadataTabTest.java, src/extension/metadata/src/test/java/org/geoserver/metadata/web/TabsTest.java, src/extension/metadata/src/test/resources/org/geoserver/metadata/metadata-ui.yaml
[![GEOS-11278](https://badgen.net/badge/JIRA/GEOS-11278/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11278) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7364
=> [Backport 2.23.x] [GEOS-11278] metadata: only selected tab is submitted

src/release/ext-geofence-server.xml
[![GEOS-11291](https://badgen.net/badge/JIRA/GEOS-11291/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11291) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Assembly files of geofence plugins still include references to log4j stuff.
=> [GEOS-11291] GeoFence: Cleanup stale log4j references

doc/en/user/source/community/wps-longitudinal-profile/index.rst, src/community/wps-longitudinal-profile/src/main/java/org/geoserver/wps/longitudinal/AltitudeReaderThread.java, src/community/wps-longitudinal-profile/src/main/java/org/geoserver/wps/longitudinal/LongitudinalProfileProcess.java, src/community/wps-longitudinal-profile/src/main/java/org/geoserver/wps/longitudinal/ProfileVertice.java
This PR modify the wps-longitudinal-profile community module to use thread for altitude reading.
This way it allow to process more points in less time, depending on available number of cores.
=> Use threads to read altitude in wps-longitudinal-profile community module

doc/en/user/source/services/wms/outputformats.rst, src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLDocumentBuilder.java, src/extension/mapml/src/main/java/org/geoserver/mapml/tcrs/TiledCRS.java, src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java, src/extension/mapml/src/test/resources/org/geoserver/mapml/scaleRange.sld, src/extension/mapml/src/test/resources/org/geoserver/mapml/scaleRangeExtremes.sld, src/extension/mapml/src/test/resources/org/geoserver/mapml/scaleRangeNoMax.sld
[![GEOS-11232](https://badgen.net/badge/JIRA/GEOS-11232/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11232) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
switched to binary search
working test for zoom input
unit tests and fix for single extent detection
GetMap tests
wms output format documentation
added some edge tests
unused var
ground resolution to scale
updated tests and fixed infinite check
Reproject bounds
- For gwc-backed GetMap request update extentZoomInput.value with the gss.getZoomStop() to match the zoom value used by the location inputs' min/max row and column …
=> [GEOS-11232] Add Zoom scaled layer templates to MapML

src/release/ext-geofence-server.xml
[![GEOS-11291](https://badgen.net/badge/JIRA/GEOS-11291/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11291) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7391
=> [Backport 2.23.x] [GEOS-11291] GeoFence: Cleanup stale log4j references

src/release/ext-geofence-server.xml
[![GEOS-11291](https://badgen.net/badge/JIRA/GEOS-11291/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11291) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7391
=> [Backport 2.24.x] [GEOS-11291] GeoFence: Cleanup stale log4j references

doc/en/user/source/styling/css/directives.rst, src/extension/css/src/test/java/org/geoserver/community/css/web/CssHandlerTest.java
[![GEOS-11276](https://badgen.net/badge/JIRA/GEOS-11276/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11276) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This commit adds a test to check that a CSS string passed as STYLE_BODY with STYLE_FORMAT=css is applied to the layer if the style name is the same of the queried layer.
Documentation is also updated for the new directive.
=> [GEOS-11276] Use style_body to define CSS style for a layer

doc/en/user/source/styling/css/directives.rst, src/extension/css/src/test/java/org/geoserver/community/css/web/CssHandlerTest.java
[![GEOS-11276](https://badgen.net/badge/JIRA/GEOS-11276/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11276) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7365
**Authored by:** @mirco-romagnoli
=> [Backport 2.23.x] [GEOS-11276] Use style_body to define CSS style for a layer

doc/en/user/source/extensions/mapml/index.rst, src/extension/importer/web/src/test/java/org/geoserver/importer/web/ImportTaskTableTest.java, src/extension/mapml/pom.xml, src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLDocumentBuilder.java, src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLGetFeatureOutputFormat.java, src/extension/mapml/src/main/java/org/geoserver/mapml/tcrs/Projection.java, src/extension/mapml/src/main/java/org/geoserver/mapml/tcrs/TiledCRSFactory.java, src/extension/mapml/src/main/java/org/geoserver/mapml/tcrs/TiledCRSParams.java, src/extension/mapml/src/main/java/org/geoserver/mapml/xml/ProjType.java, src/extension/mapml/src/main/java/org/geoserver/web/demo/MapMLFormatLink.java, src/extension/mapml/src/main/resources/META-INF/services/org.geotools.api.referencing.crs.CRSAuthorityFactory, src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLGetFeatureOutputFormatTest.java, src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java, src/extension/mapml/src/test/java/org/geoserver/mapml/tcrs/TiledCRSFactoryTest.java, src/extension/mapml/src/test/java/org/geoserver/web/demo/MapMLFormatLinkTest.java, src/extension/mapml/src/test/java/org/geoserver/web/demo/PreviewLayerTest.java, src/main/src/main/java/org/geoserver/catalog/ResourcePool.java, src/web/demo/src/main/java/org/geoserver/web/demo/PreviewLayer.java
In short, have "MapML:OSMTILE" and friends act as supported CRS instances, available in all protocols, in capabilities documents, in data and map requests.
See tickes for details.
=> First class support for MapML Tiled CRS definitions

doc/en/user/source/styling/css/directives.rst, src/extension/css/src/test/java/org/geoserver/community/css/web/CssHandlerTest.java
[![GEOS-11276](https://badgen.net/badge/JIRA/GEOS-11276/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11276) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7365
**Authored by:** @mirco-romagnoli
=> [Backport 2.24.x] [GEOS-11276] Use style_body to define CSS style for a layer

src/main/src/main/java/org/geoserver/filters/AlternativesResponseStream.java, src/main/src/main/java/org/geoserver/filters/GZIPResponseWrapper.java, src/main/src/test/java/org/geoserver/filters/GZipFilterTest.java
[![GEOS-11285](https://badgen.net/badge/JIRA/GEOS-11285/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11285) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Omit the Content-Length header in GZIPFilter
Related issue: https://osgeo-org.atlassian.net/browse/GEOS-10779
=> [GEOS-11285] GWC REST Content-Encoding gzip returns broken response

src/main/src/main/java/org/geoserver/filters/AlternativesResponseStream.java, src/main/src/main/java/org/geoserver/filters/GZIPResponseWrapper.java, src/main/src/test/java/org/geoserver/filters/GZipFilterTest.java
[![GEOS-11285](https://badgen.net/badge/JIRA/GEOS-11285/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11285) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7370
=> [Backport 2.23.x] [GEOS-11285] GWC REST Content-Encoding gzip returns broken response

src/main/src/main/java/org/geoserver/filters/AlternativesResponseStream.java, src/main/src/main/java/org/geoserver/filters/GZIPResponseWrapper.java, src/main/src/test/java/org/geoserver/filters/GZipFilterTest.java
[![GEOS-11285](https://badgen.net/badge/JIRA/GEOS-11285/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11285) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7370
=> [Backport 2.24.x] [GEOS-11285] GWC REST Content-Encoding gzip returns broken response

doc/en/user/source/installation/upgrade.rst, doc/en/user/source/production/config.rst, doc/en/user/source/services/wms/webadmin.rst, doc/en/user/source/tutorials/GetFeatureInfo/html.rst, src/wms/src/main/java/org/geoserver/wms/featureinfo/FreeMarkerTemplateManager.java, src/wms/src/test/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormatTest.java
[![GEOS-11297](https://badgen.net/badge/JIRA/GEOS-11297/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11297) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR enabled FreeMarker's HTML auto-escaping by default and adds a system property to enable/disable it.
This PR includes backward-incompatible changes and should not be backported.
=> [GEOS-11297] Escape WMS GetFeatureInfo HTML output by default

doc/en/user/source/tutorials/tomcat-jndi/tomcat-jndi.rst
[![GEOS-11260](https://badgen.net/badge/JIRA/GEOS-11260/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11260) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Avoid inducing users in a faulty pool configuration (one that Tomcat reports no warning about, too).
=> [GEOS-11260] JNDI tutorial uses outdated syntax

doc/en/user/source/tutorials/tomcat-jndi/tomcat-jndi.rst
[![GEOS-11260](https://badgen.net/badge/JIRA/GEOS-11260/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11260) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7417
=> [Backport 2.24.x] [GEOS-11260] JNDI tutorial uses outdated syntax

doc/en/user/source/tutorials/tomcat-jndi/tomcat-jndi.rst
[![GEOS-11260](https://badgen.net/badge/JIRA/GEOS-11260/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11260) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7417
=> [Backport 2.23.x] [GEOS-11260] JNDI tutorial uses outdated syntax

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/PagingTest.java, src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SRSWfsTest.java
Fix 3 out of 4 failing app schema online tests.
* Fix mimetype assertion in app-schema-test's PagingTest
* Include Postgis in app-schema-test's expectation respecting axis order
App-schema-test's `SRCWfsTest` checked only if it run against GeoPackage to assert the expected geometries respect the EPSG axis order.
Include PostGIS too and remove duplicated code.
Reprojection works fine with the PostGIS online tests and produce the same expected results.
These integration test failures are currently not detected by any of the running build jobs, and are the same errors happening with and without the https://github.com/geotools/geotools/pull/4410 geotools enhancement.
Before:
```
src $> mvn -o clean test -pl :gs-app-schema-postgis-test -Papp-schema,app-schema-online-test
...
[ERROR] Failures: …
```
=> Fix some app schema online tests

src/pom.xml
=> [Backport 2.24.x] Bump org.postgresql:postgresql from 42.6.0 to 42.7.2 in /src

src/pom.xml
=> [Backport 2.23.x] Bump org.postgresql:postgresql from 42.6.0 to 42.7.2 in /src

src/pom.xml
=> [Backport 2.22.x] Bump org.postgresql:postgresql from 42.6.0 to 42.7.2 in /src

src/main/src/main/java/org/geoserver/security/GeoServerSecurityManager.java
I tried to log in to a misconfigured GeoServer as `root` with the masterpw and was horrified when it did not work. Only via Google I found out that one needs to explicitely enable this special login: https://docs.geoserver.org/2.24.x/en/user/security/passwd.html#keystore-password
This PR simply adds another line to the `masterpw.info` file so that there is a better chance for discovery. :)
=> Mention need for config edit for root/masterpw login

src/community/pom.xml
[![GEOS-11216](https://badgen.net/badge/JIRA/GEOS-11216/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11216) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11216] add graticule assembly to assemeby list so it is built

src/community/pom.xml, src/community/release/ext-graticule.xml
[![GEOS-11216](https://badgen.net/badge/JIRA/GEOS-11216/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11216) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7478
**Authored by:** @ianturton
=> [Backport 2.25.x] [GEOS-11216] make sure gt-grid is included in the graticule plugin 

src/community/pom.xml
[![GEOS-11216](https://badgen.net/badge/JIRA/GEOS-11216/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11216) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7475
**Authored by:** @ianturton
=> [Backport 2.25.x] [GEOS-11216] add graticule assembly to assemeby list so it is built

src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml
=> [Backport 2.24.x] Bump com.nimbusds:nimbus-jose-jwt from 9.37.1 to 9.37.2 in /src/community/security/oauth2-openid-connect/oauth2-openid-connect-core

src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml
=> [Backport 2.25.x] Bump com.nimbusds:nimbus-jose-jwt from 9.37.1 to 9.37.2 in /src/community/security/oauth2-openid-connect/oauth2-openid-connect-core

src/wms/src/main/java/org/geoserver/wms/legendgraphic/BufferedImageLegendGraphicBuilder.java, src/wms/src/main/java/org/geoserver/wms/legendgraphic/Tally.java, src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetLegendGraphicTest.java
[![GEOS-11312](https://badgen.net/badge/JIRA/GEOS-11312/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11312) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Tally was doing memory calculations in the byte level, but it was not considered datatype capabilities. 
=> [GEOS-11312] Inconsistent Memory Units in Legend Image Creation

doc/en/user/source/datadirectory/index.rst, src/web/security/core/src/main/java/org/geoserver/security/web/SecurityHomePageContentProvider$SecurityWarningsPanel.html, src/web/security/core/src/main/java/org/geoserver/security/web/SecurityHomePageContentProvider.java, src/web/security/core/src/main/resources/GeoServerApplication.properties, src/web/security/core/src/test/java/org/geoserver/security/web/SecurityHomePageContentProviderTest.java
[![GEOS-11327](https://badgen.net/badge/JIRA/GEOS-11327/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11327) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR adds a warning message when administrators log in to the GeoServer home page if GeoServer is using a data directory embedded in the web application directory.  It also adds a vague clarification to the documentation that there are security reasons for using an external data directory.
=> [GEOS-11327] Add warning about using embedded data directories

src/wms/src/main/java/org/geoserver/wms/legendgraphic/BufferedImageLegendGraphicBuilder.java, src/wms/src/main/java/org/geoserver/wms/legendgraphic/Tally.java, src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetLegendGraphicTest.java
[![GEOS-11312](https://badgen.net/badge/JIRA/GEOS-11312/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11312) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7443
**Authored by:** @vuvkar
=> [Backport 2.24.x] [GEOS-11312] Inconsistent Memory Units in Legend Image Creation

src/wms/src/main/java/org/geoserver/wms/legendgraphic/BufferedImageLegendGraphicBuilder.java, src/wms/src/main/java/org/geoserver/wms/legendgraphic/Tally.java, src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetLegendGraphicTest.java
[![GEOS-11312](https://badgen.net/badge/JIRA/GEOS-11312/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11312) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7443
**Authored by:** @vuvkar
=> [Backport 2.25.x] [GEOS-11312] Inconsistent Memory Units in Legend Image Creation

src/pom.xml
=> [Backport 2.25.x] Bump org.springframework.security:spring-security-core from 5.7.11 to 5.7.12 in /src

src/pom.xml
=> [Backport 2.24.x] Bump org.springframework.security:spring-security-core from 5.7.11 to 5.7.12 in /src

doc/en/user/source/production/config.rst, src/main/src/main/java/org/geoserver/filters/XFrameOptionsFilter.java, src/main/src/test/java/org/geoserver/filters/XFrameOptionsFilterTest.java
[![GEOS-11325](https://badgen.net/badge/JIRA/GEOS-11325/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11325) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR adds system properties to allow GeoServer administrators to configure the X-XSS-Protection and Strict-Transport-Security HTTP response headers similar to how the X-Content-Type-Options and X-Frame-Options headers currently work.  All four of these headers are normally enabled by default by Spring Security but I left the two that are being added here disabled by default so there's no backwards compatibility issues. …
=> [GEOS-11325] Add properties to set additional security headers

src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACService.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/ConformanceTest.java
[![GEOS-11345](https://badgen.net/badge/JIRA/GEOS-11345/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11345) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7513
=> [Backport 2.24.x] [GEOS-11345] STAC Conformance URIs need to be updated

src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACService.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/ConformanceTest.java
[![GEOS-11345](https://badgen.net/badge/JIRA/GEOS-11345/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11345) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7513
=> [Backport 2.25.x] [GEOS-11345] STAC Conformance URIs need to be updated

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/server/JMSCatalogListener.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/JmsStylesTest.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/IntegrationTest.java
[![GEOS-11348](https://badgen.net/badge/JIRA/GEOS-11348/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11348) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7526
=> [Backport 2.23.x] [GEOS-11348] JMS cluster does not allow to publish style via REST '2 step' approach

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/server/JMSCatalogListener.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/JmsStylesTest.java, src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/IntegrationTest.java
[![GEOS-11348](https://badgen.net/badge/JIRA/GEOS-11348/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11348) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7526
=> [Backport 2.24.x] [GEOS-11348] JMS cluster does not allow to publish style via REST '2 step' approach

src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLDocumentBuilder.java, src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLStyleVisitorTest.java, src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLTestSupport.java, src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSFeatureTest.java, src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java
[![GEOS-11349](https://badgen.net/badge/JIRA/GEOS-11349/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11349) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
…image size
=> [GEOS-11349] MapML Use WMS Resource Consumption Limit to specify max image size

src/pom.xml
[![GEOS-11362](https://badgen.net/badge/JIRA/GEOS-11362/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11362) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7538
=> [Backport 2.24.x] [GEOS-11362] Upgrade Spring libs from 5.3.32 to 5.3.33

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/Link.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/OGCAPIMediaTypes.java, src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACLandingPage.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/LandingPageTest.java
[![GEOS-11347](https://badgen.net/badge/JIRA/GEOS-11347/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11347) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7525
=> [Backport 2.24.x] [GEOS-11347] STAC Landing Page links should include root link

src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTemplate.java, src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTemplateLoader.java, src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTransactionCallback.java, src/community/features-autopopulate/features-autopopulate-core/src/test/java/org/geoserver/autopopulate/AutopopulateTransactionCallbackTest.java
[![GEOS-11358](https://badgen.net/badge/JIRA/GEOS-11358/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11358) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7535
=> [Backport 2.25.x] [GEOS-11358] Feature-Autopopulate Update operation does not apply the Update Element filter

src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTemplate.java, src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTemplateLoader.java, src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTransactionCallback.java, src/community/features-autopopulate/features-autopopulate-core/src/test/java/org/geoserver/autopopulate/AutopopulateTransactionCallbackTest.java
[![GEOS-11358](https://badgen.net/badge/JIRA/GEOS-11358/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11358) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7535
=> [Backport 2.24.x] [GEOS-11358] Feature-Autopopulate Update operation does not apply the Update Element filter

src/wfs/src/main/java/org/geoserver/wfs/GetFeature.java
=> [Backport 2.25.x] [GEOS-11306] Chace GetFeature total using AtomicLong for thread safety

src/web/core/src/main/java/org/geoserver/web/system/status/ConsoleInfoUtils.java, src/web/core/src/test/java/org/geoserver/web/system/status/ConsoleInfoUtilsStackTest.java
[![GEOS-11311](https://badgen.net/badge/JIRA/GEOS-11311/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11311) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Get a usable jstack output in the JVM console, e.g.:
Before this patch each thread only had 8 lines of trace, which is most of the times not enough to figure out what the thread is doing.
=> [GEOS-11311] Show a full stack trace in the JVM stack dump panel

src/community/ogcapi/ogcapi-changeset/src/main/java/org/geoserver/ogcapi/v1/changeset/ChangesetIndexProvider.java
This PR fixes an error running the ogcapi-changeset unit tests on Windows. The class is creating an H2 datastore in a temp directory that never gets disposed so the test class can't delete the temp directory on Windows. There's no ticket since this is just to fix a unit test in a community module.
=> Fixed ogcapi-changeset unit test error on Windows

src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java
[![GEOS-11381](https://badgen.net/badge/JIRA/GEOS-11381/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11381) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
https://osgeo-org.atlassian.net/browse/GEOS-11381
Using the latest version of OIDC plugin in combination with RoleService as Role source causes a casting exception:
java.lang.ClassCastException: class org.geoserver.security.config.PreAuthenticatedUserNameFilterConfig$PreAuthenticatedUserNameRoleSource cannot be cast to class org.geoserver.security.oauth2.OpenIdConnectFilterConfig$OpenIdRoleSource …
=> [GEOS-11381] Fix error in OIDC plugin in combination with RoleService

doc/en/api/1.0.0/rat.yaml, src/extension/rat/src/main/java/org/geoserver/rat/rest/PAMController.java, src/extension/rat/src/test/java/org/geoserver/rat/rest/PAMControllerTest.java, src/extension/rat/src/test/resources/org/geoserver/rat/web/rat.tiff.aux2.xml
[![GEOS-11377](https://badgen.net/badge/JIRA/GEOS-11377/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11377) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Needs the following:
* https://github.com/geotools/geotools/pull/4732
* https://github.com/geoserver/geoserver/pull/7581
=> [GEOS-11377] RAT module: allow to reload/recompute the RAT

src/pom.xml
[![GEOS-11388](https://badgen.net/badge/JIRA/GEOS-11388/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11388) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
See ticket
=> [GEOS-11388] Update ImageIO-EXT to 1.4.10

src/community/proxy-base-ext/src/main/java/org/geoserver/proxybase/ext/ProxyBaseExtUrlMangler.java
[![GEOS-11392](https://badgen.net/badge/JIRA/GEOS-11392/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11392) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11392] ConcurrentModificationException while using proxy-base-ext

src/pom.xml
[![GEOS-11395](https://badgen.net/badge/JIRA/GEOS-11395/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11395) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7619
=> [Backport 2.24.x] [GEOS-11395] Upgrade guava from 32.0.0 to 33.2.0

src/wfs/src/main/java/org/vfny/geoserver/wfs/servlets/TestWfsPost.java, src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetCapabilitiesTest.java, src/wfs/src/test/java/org/vfny/geoserver/wfs/servlets/TestWfsPostTest.java
[![GEOS-11385](https://badgen.net/badge/JIRA/GEOS-11385/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11385) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11385] Demo Requests functionality does not honour ENV variable PROXY_BASE_URL

src/wfs/src/main/java/org/vfny/geoserver/wfs/servlets/TestWfsPost.java, src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetCapabilitiesTest.java, src/wfs/src/test/java/org/vfny/geoserver/wfs/servlets/TestWfsPostTest.java
[![GEOS-11385](https://badgen.net/badge/JIRA/GEOS-11385/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11385) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7602
=> [Backport 2.25.x] [GEOS-11385] Demo Requests functionality does not honour ENV variable PROXY_BASE_URL

src/wfs/src/main/java/org/vfny/geoserver/wfs/servlets/TestWfsPost.java, src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetCapabilitiesTest.java, src/wfs/src/test/java/org/vfny/geoserver/wfs/servlets/TestWfsPostTest.java
[![GEOS-11385](https://badgen.net/badge/JIRA/GEOS-11385/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11385) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7602
=> [Backport 2.24.x] [GEOS-11385] Demo Requests functionality does not honour ENV variable PROXY_BASE_URL

src/community/release/ext-oauth2-openid-connect.xml, src/community/security/keycloak/pom.xml, src/community/security/oauth2-geonode/pom.xml, src/community/security/oauth2-github/pom.xml, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml, src/community/security/oauth2/oauth2-core/pom.xml, src/pom.xml
=> [Backport 2.25.x] Removing unecessary jackson-mapper-asl dependency

src/gwc/pom.xml
Just a simple test dependency addition, which avoids gs-gwc build logs reporting warnings about IAU authority not being found.
=> Avoid wanings about IAU missing in GWC test logs

src/extension/security/cas/src/main/java/org/geoserver/security/cas/GeoServerCasAuthenticationFilter.java, src/extension/security/cas/src/test/java/org/geoserver/security/cas/GeoServerCasAuthenticationFilterTest.java
[![GEOS-11202](https://badgen.net/badge/JIRA/GEOS-11202/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11202) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
The service URL built by the CAS extension now respects the proxy base URL (both the system property and the config value). I accomplished this by running the URL through ResponseUtils.buildUrl to ensure it ultimately goes through ProxifyingURLManger.
Furthermore, it also preserves the end-user's path and query parameters. This is to ensure that by the time the user is redirect back to the application from CAS, they will …
=> [GEOS-11202] Respect proxy base URL when building CAS service URL.

src/platform/src/main/java/org/geoserver/util/IOUtils.java, src/platform/src/test/java/org/geoserver/util/IOUtilsTest.java
[![GEOS-11332](https://badgen.net/badge/JIRA/GEOS-11332/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11332) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Nasty little bug that causes "data loss" (as in, stylesheet loss)
=> [GEOS-11332] Renaming style with uppercase/downcase empty the sld file

src/pom.xml
[![GEOS-11402](https://badgen.net/badge/JIRA/GEOS-11402/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11402) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11402] Upgrade PostgreSQL driver from 42.7.2 to 42.7.3

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/CollectionExtents.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/TimeExtentCalculator.java, src/community/ogcapi/ogcapi-core/src/main/resources/org/geoserver/ogcapi/common-header.ftl, src/community/ogcapi/ogcapi-coverages/src/main/resources/org/geoserver/ogcapi/v1/coverages/collection_include.ftl, src/community/ogcapi/ogcapi-maps/src/main/resources/org/geoserver/ogcapi/v1/maps/collection_include.ftl, src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/CollectionTest.java, src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/MapsTest.java, src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/MapsTestSupport.java, src/community/ogcapi/ogcapi-maps/src/test/resources/org/geoserver/ogcapi/v1/maps/TimeElevationWithStartEndDate.properties, src/main/src/main/java/org/geoserver/template/FeatureWrapper.java
[![GEOS-11394](https://badgen.net/badge/JIRA/GEOS-11394/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11394) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11394] OGC APIs cannot handle time extent when the source data type is java.sql.Date

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/CollectionExtents.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/TimeExtentCalculator.java, src/community/ogcapi/ogcapi-core/src/main/resources/org/geoserver/ogcapi/common-header.ftl, src/community/ogcapi/ogcapi-coverages/src/main/resources/org/geoserver/ogcapi/v1/coverages/collection_include.ftl, src/community/ogcapi/ogcapi-maps/src/main/resources/org/geoserver/ogcapi/v1/maps/collection_include.ftl, src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/CollectionTest.java, src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/MapsTest.java, src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/MapsTestSupport.java, src/community/ogcapi/ogcapi-maps/src/test/resources/org/geoserver/ogcapi/v1/maps/TimeElevationWithStartEndDate.properties, src/main/src/main/java/org/geoserver/template/FeatureWrapper.java
[![GEOS-11394](https://badgen.net/badge/JIRA/GEOS-11394/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11394) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7621
=> [Backport 2.25.x] [GEOS-11394] OGC APIs cannot handle time extent when the source data type is java.sql.Date

src/main/src/main/java/org/geoserver/config/GeoServerInfo.java, src/main/src/main/java/org/geoserver/config/impl/GeoServerInfoImpl.java, src/main/src/main/java/org/geoserver/util/AllowListEntityResolver.java, src/main/src/main/java/org/geoserver/util/EntityResolverProvider.java, src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java, src/main/src/test/java/org/geoserver/util/EntityResolverProviderTest.java
Backport https://github.com/geoserver/geoserver/pull/7668
However since 2.24.x did not have a test case I have adapted the EntityResolverProviderTest to the expectations of 2.24.x branch (2.24.x it defaults to unrestricted http access).
=> [Backport 2.24.x] [GEOS-11398] Javadoc clarification and test cases for Entity Resolution

src/main/src/test/java/org/geoserver/util/EntityResolverProviderTest.java
=> [Backport 2.25.x] [GEOS-11398] Additional entityResolverProviderTest checks

src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/AbstractMappingStore.java, src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCProductFeatureStore.java, src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/WorkspaceFeatureSource.java, src/community/oseo/oseo-core/src/test/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccessTest.java, src/community/oseo/oseo-rest/src/test/java/org/geoserver/opensearch/rest/CollectionLayerTest.java
[![GEOS-11413](https://badgen.net/badge/JIRA/GEOS-11413/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11413) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11413] STAC uses inefficient dabase queries when asking for collections in JSON format

src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/AbstractMappingStore.java, src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCProductFeatureStore.java, src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/WorkspaceFeatureSource.java, src/community/oseo/oseo-core/src/test/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccessTest.java, src/community/oseo/oseo-rest/src/test/java/org/geoserver/opensearch/rest/CollectionLayerTest.java
[![GEOS-11413](https://badgen.net/badge/JIRA/GEOS-11413/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11413) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7690
=> [Backport 2.25.x] [GEOS-11413] STAC uses inefficient dabase queries when asking for collections in JSON format

src/community/release/ext-datadir-catalog-loader.xml
=> [Backport 2.25.x] Fix typo in datadir-catalog-loader release descriptor (s/dataird/datadir/g)

src/ows/src/main/java/org/geoserver/ows/ClientStreamAbortedException.java, src/wcs1_0/src/main/java/org/geoserver/wcs/response/Wcs10CapsTransformer.java, src/wcs1_0/src/main/java/org/geoserver/wcs/response/Wcs10DescribeCoverageTransformer.java, src/wcs1_1/src/main/java/org/geoserver/wcs/response/WCSCapsTransformer.java, src/wfs/src/main/java/org/geoserver/wfs/CapabilitiesTransformer.java, src/wfs/src/main/java/org/geoserver/wfs/DescribeFeatureType.java, src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java, src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
[![GEOS-11280](https://badgen.net/badge/JIRA/GEOS-11280/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11280) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
When `ResourceErrorHandling.SKIP_MISCONFIGURED_LAYERS` is true, and the client closed the connection, the `ClientStreamAbortedException` is ignored and the process continues until it consumed all layers.
This patch makes it short-circuit and lets the `Dispatcher` handle the `ClientStreamAbortedException` gracefully.
=> [GEOS-11280] Short-circuit request processing upon ClientStreamAbortedException when SKIP_MISCONFIGURED_LAYERS is true

src/extension/netcdf-out/src/main/java/org/geoserver/wcs/responses/DefaultNetCDFEncoder.java, src/extension/netcdf/src/main/java/org/geoserver/netcdf/NetCDFUnitsConfigurator.java, src/pom.xml
[![GEOT-7422](https://badgen.net/badge/JIRA/GEOT-7422/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7422) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Companion change to https://github.com/geotools/geotools/pull/4690.
=> [GEOT-7422] Adapt to GeoTools upgrade of java units "indriya" to version 2.2

src/ows/src/main/java/org/geoserver/ows/ClientStreamAbortedException.java, src/wcs1_0/src/main/java/org/geoserver/wcs/response/Wcs10CapsTransformer.java, src/wcs1_0/src/main/java/org/geoserver/wcs/response/Wcs10DescribeCoverageTransformer.java, src/wcs1_1/src/main/java/org/geoserver/wcs/response/WCSCapsTransformer.java, src/wfs/src/main/java/org/geoserver/wfs/CapabilitiesTransformer.java, src/wfs/src/main/java/org/geoserver/wfs/DescribeFeatureType.java, src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java, src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
[![GEOS-11280](https://badgen.net/badge/JIRA/GEOS-11280/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11280) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7699
=> [Backport 2.25.x] [GEOS-11280] Short-circuit request processing upon ClientStreamAbortedException when SKIP_MISCONFIGURED_LAYERS is true

src/main/src/main/java/org/geoserver/ows/CiteComplianceHack.java, src/ows/src/main/java/org/geoserver/ows/Dispatcher.java, src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesSystemTest.java
[![GEOS-11430](https://badgen.net/badge/JIRA/GEOS-11430/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11430) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
References: https://osgeo-org.atlassian.net/browse/GEOS-11430
=> [GEOS-11430] CiteComplianceHack not correctly parsing the context

src/main/src/main/java/org/geoserver/security/ResourceAccessManager.java, src/web/core/src/main/java/org/geoserver/web/WorkspaceAdminComponentAuthorizer.java, src/web/core/src/test/java/org/geoserver/web/WorkspaceAdminComponentAuthorizerTest.java
[![GEOS-11424](https://badgen.net/badge/JIRA/GEOS-11424/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11424) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Logging in as a user other than `admin`, and having a large amount of workspaces results in potentlially substantial delays in loading almost every webui wicket page, as `WorkspaceAdminComponentAuthorizer` will be run several times, each of them potentially doing a full scan of workspaces, to determine if the user has admin privileges in at least one workspace.
This patch addresses the long-standing TODO comment in …
=> [GEOS-11424] Speed up web-ui WorkspaceAdminComponentAuthorizer

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/PaginationLinksBuilder.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/SearchTest.java
=> [GEOS-11111] Open search for EO community module: STAC search page has wrong self link

src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACService.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/ConformanceTest.java
[![GEOS-11345](https://badgen.net/badge/JIRA/GEOS-11345/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11345) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7515
=> [Backport 2.23.x] [GEOS-11345] STAC Conformance URIs need to be updated

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/PaginationLinksBuilder.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/SearchTest.java
[![GEOS-11111](https://badgen.net/badge/JIRA/GEOS-11111/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11111) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7730
=> [Backport 2.25.x] [GEOS-11111] Open search for EO community module: STAC search page has wrong self link

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/PaginationLinksBuilder.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/SearchTest.java
[![GEOS-11111](https://badgen.net/badge/JIRA/GEOS-11111/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11111) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7730
=> [Backport 2.24.x] [GEOS-11111] Open search for EO community module: STAC search page has wrong self link

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/PaginationLinksBuilder.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/SearchTest.java
[![GEOS-11111](https://badgen.net/badge/JIRA/GEOS-11111/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11111) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7730
=> [Backport 2.23.x] [GEOS-11111] Open search for EO community module: STAC search page has wrong self link

src/community/oseo/oseo-assembly/pom.xml
[![GEOS-11438](https://badgen.net/badge/JIRA/GEOS-11438/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11438) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7735
=> [Backport 2.25.x] [GEOS-11438] OpenSearch for EO/STAC lack the service configuration panel

.github/workflows/assembly.yml, .github/workflows/backport.yml, .github/workflows/docs.yml, .github/workflows/javadoc.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/postgis_appschema_online.yml, .github/workflows/qa.yml, .github/workflows/windows.yml
This will prevent workflows from no longer working in the future and will stop messages like:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-java@v3, stCarolas/setup-maven@v4.5, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
from fouling the build logs.
Also:
- Bump Ubuntu from 20.04 to 22.04
- Update appschema workflow to use a service runner and the shared cache
**Please squash when merging**
=> [ci] update workflow actions and maven version

src/main/src/main/java/org/geoserver/security/DisabledServiceResourceFilter.java, src/wfs/src/test/java/org/geoserver/wfs/WFSDisabledTest.java
[![GEOS-111441](https://badgen.net/badge/JIRA/GEOS-111441/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-111441) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-111441] DisabledServiceResourceFilter spams debugging logs with property accesses

src/main/src/main/java/org/geoserver/security/DisabledServiceResourceFilter.java, src/wfs/src/test/java/org/geoserver/wfs/WFSDisabledTest.java
[![GEOS-111441](https://badgen.net/badge/JIRA/GEOS-111441/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-111441) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7739
=> [Backport 2.25.x] [GEOS-111441] DisabledServiceResourceFilter spams debugging logs with property accesses

src/restconfig/src/main/java/org/geoserver/rest/catalog/StyleController.java, src/restconfig/src/test/java/org/geoserver/rest/catalog/StyleControllerTest.java
Looking specifically for the temp directories created by the tested code, rather than counting files in the shared temp directory, where other tests can also put stuff (and other OS processes as well).
Ideally, it would be better to have each module run with a separate test directory, but we cannot get that, as test JVMs are getting re-used across the build.
=> Hopefully fix random build failure in style controller test

src/community/jwt-headers/gs-jwt-headers/src/assembly/assembly.xml, src/community/jwt-headers/gs-jwt-headers/src/main/java/org/geoserver/security/jwtheaders/filter/GeoServerJwtHeadersFilter.java
I ran JWT-Headers inside Tomcat and noticed a few minor problems.
1. The `assembly.xml` wasn't including the `json-smart` jar
2. I changed one of the comparisons from `==` to `.equals()`.  This didn't seem to be an issue in jetty, but was a problem in tomcat.
3. Session handling in tomcat and jetty are a bit different.  I noticed a case where there was an authorization change (i.e. adding or removing the jwt headers between requests).  This would trigger  a wicket redirect (i.e. from `/geoserver/` to `/geoserver/web` or something like `/geoserver/web/?4` to `geoserver/web/?0`).  This was fine in Jetty.  However, in tomcat, doing a session creation during a redirect isn't allowed.
The basic order of events is:
a. There is a jwt header auth change (either adding or removing the jwt from the …
=> Jwt-headers and tomcat

src/extension/inspire/src/main/java/org/geoserver/inspire/LanguagesDispatcherCallback.java, src/extension/inspire/src/main/java/org/geoserver/inspire/ServicesUtils.java, src/extension/inspire/src/main/java/org/geoserver/inspire/wms/WMSExtendedCapabilitiesProvider.java, src/extension/inspire/src/test/java/org/geoserver/inspire/wcs/WCSExtendedCapabilitiesTest.java, src/extension/inspire/src/test/java/org/geoserver/inspire/wfs/WFSExtendedCapabilitiesTest.java, src/extension/inspire/src/test/java/org/geoserver/inspire/wms/WMSExtendedCapabilitiesTest.java, src/extension/inspire/src/test/java/org/geoserver/inspire/wmts/WMTSExtendedCapabilitiesTest.java, src/main/src/main/java/org/geoserver/data/InternationalContentHelper.java, src/main/src/main/java/org/geoserver/security/impl/DigestAuthUtils.java, src/ows/src/main/java/org/geoserver/ows/util/RequestUtils.java
[![GEOS-11446](https://badgen.net/badge/JIRA/GEOS-11446/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11446) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
References: https://osgeo-org.atlassian.net/browse/GEOS-11446
=> [GEOS-11446] [INSPIRE] Incorrect behavior for unsupported languages

src/community/taskmanager/core/src/assembly/assembly.xml
[![GEOS-10690](https://badgen.net/badge/JIRA/GEOS-10690/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10690) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7761
=> [Backport 2.25.x] [GEOS-10690] Taskmanager community module: fix assembly

src/pom.xml
[![GEOS-11464](https://badgen.net/badge/JIRA/GEOS-11464/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11464) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7767
=> [Backport 2.24.x] [GEOS-11464] Update Jackson 2 libs from 2.17.1 to 2.17.2

doc/en/api/1.0.0/reload.yaml, doc/en/user/source/rest/api/reset.rst, src/main/src/main/java/applicationContext.xml, src/main/src/main/java/applicationSecurityContext.xml, src/main/src/main/java/org/geoserver/security/GeoServerSecurityManager.java, src/main/src/main/java/org/geoserver/security/auth/AuthenticationCache.java, src/main/src/main/java/org/geoserver/security/auth/AuthenticationCacheImpl.java, src/main/src/main/java/org/geoserver/security/auth/GeoServerRootAuthenticationProvider.java, src/main/src/main/java/org/geoserver/security/auth/GuavaAuthenticationCacheImpl.java, src/main/src/main/java/org/geoserver/security/auth/LRUAuthenticationCacheImpl.java, src/main/src/main/java/org/geoserver/security/auth/UsernamePasswordAuthenticationProvider.java, src/main/src/test/java/org/geoserver/security/auth/AbstractAuthenticationProviderTest.java, src/main/src/test/java/org/geoserver/security/auth/TestingAuthenticationCache.java, src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java, src/restconfig/src/main/java/org/geoserver/rest/CatalogReloadController.java, src/security/security-tests/src/test/java/org/geoserver/security/auth/AbstractAuthenticationProviderTest-context.xml
[![GEOS-11443](https://badgen.net/badge/JIRA/GEOS-11443/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11443) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
From my experience with the GeoServer REST API, e.g. adding a user to a group [GeoServer API Docs](https://docs.geoserver.org/stable/en/api/#1.0.0/usergroup.yaml) , the change happens and is written to disk immediately, however there is a 10 minute authentication cache that prevents the change from being **effective** immediately.
If I am impatient, I typically reload the configuration or use the AuthKey synchronise button …
=> [GEOS-11443] REST API does not take effect immediately due to 10 minute authentication cache

src/wfs/src/main/java/org/geoserver/wfs/response/ShapeZipOutputFormat.java
This PR fixes a typo in the zipped text file that is returned in lieu of a shapefile when a WFS query yields no results:
'unknwon' corrected to 'unknown'.
Rationale: Spelling was incorrect and this text is intended for human consumption.
- [n/a ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
I have run:
`mvn clean install -Dqa`
There were 4 unrelated PMD violations:
```
[INFO] Open Web Service Module ............................ SUCCESS [ 41.925 s]
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://pmd.sourceforge.net/report/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" …
```
=> [typo] correct spelling of unknown in empty shapefile response

src/restconfig/src/main/java/org/geoserver/rest/catalog/WMSStoreController.java, src/restconfig/src/main/java/org/geoserver/rest/catalog/WMTSStoreController.java
This PR addresses an issue in the geoserver_WMSStoreController_wmsStoreDelete.java file where the logging statement in the wmsStoreDelete method redundantly concatenated the workspace name twice, leading to unclear and inconsistent log messages. The change improves the clarity and accuracy of the logging statement to better reflect the operation being performed.
The previous logging statement did not accurately represent the action being logged, as it redundantly included the workspace name and omitted the store name. This inconsistency could lead to confusion when interpreting log messages. The updated statement enhances the readability and usefulness of the logs by clearly indicating the specific store being deleted.
=> Update Logging Statement for WMS Store Deletion

doc/en/user/source/extensions/printing/protocol.rst, src/extension/printing/src/test/resources/test.yaml, src/pom.xml
Upgrading mapfish print version, which brings:
* Bump org.jyaml.jyaml 1.3 to com.fasterxml.jackson.dataformat.jackson-dataformat-yaml 2.16.1
--> https://github.com/mapfish/mapfish-print-v2/pull/23
--> bump to jackson 2.17.2
--> removed jyaml dependency, so the vulnerabilty disappeared
* Support custom pdf layer name (sent in request JSON parameter "pdfLayerName")
--> https://github.com/mapfish/mapfish-print-v2/pull/22
--> bump to geotools 31.1
The changes were tested against geoserver 2.25.2.
=> Bump mapfish print 2.3.0 -> 2.3.1

src/main/src/main/java/org/geoserver/security/RESTfulDefinitionSource.java, src/main/src/main/java/org/geoserver/security/RESTfulDefinitionSourceDelegateMap.java, src/main/src/main/java/org/geoserver/security/filter/GeoServerSecurityContextPersistenceFilter.java, src/main/src/main/java/org/geoserver/security/filter/GeoServerSecurityInterceptorFilter.java, src/main/src/main/java/org/geoserver/security/filter/GeoServerSecurityMetadataSource.java, src/pom.xml
[![GEOS-11271](https://badgen.net/badge/JIRA/GEOS-11271/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11271) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Pull request for [GEOS-11271](https://osgeo-org.atlassian.net/browse/GEOS-11271)
Upgrades Spring Security 5.7.12 -> 5.8.13 (latest 5.8.x) and Spring 5.3.34 -> 5.3.37
**Spring Upgrade**
Spring-Security 5.8.13 depends on Spring 5.3.37, so I decided to upgrade Spring, too. The Spring upgrade is  comprising compatible release only, as per [Spring release notes](https://github.com/spring-projects/spring-framework/releases). …
=> [GEOS-11271] Upgrade spring-security to 5.8

src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLControllerTest.java, src/wms/src/test/java/org/geoserver/wms/DefaultWebMapServiceTest.java
Updates tests to match https://github.com/geotools/geotools/pull/4861. Backports the equivalent changes made on 
https://github.com/geoserver/geoserver/pull/7524
=> [Backport 2.24.x] Re-align expected outputs due to improvement in GT envelope reprojection

src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java, src/wms/src/test/java/org/geoserver/wms/DefaultWebMapServiceTest.java
Update test expectactions to match changes in https://github.com/geotools/geotools/pull/4862
Backport from main.
=> [Backport 2.25.x] Update expectactions on envelope reprojection

src/community/schemaless-features/mongodb-schemaless/pom.xml, src/community/schemaless-features/mongodb-schemaless/src/test/java/org/geoserver/schemalessfeatures/mongodb/WFSSchemalessMongoTest.java, src/community/schemaless-features/mongodb-schemaless/src/test/java/org/geoserver/schemalessfeatures/mongodb/WMSSchemalessMongoTest.java, src/community/schemaless-features/mongodb-schemaless/src/test/resources/org/geoserver/schemalessfeatures/mongodb/test-data/stations/json/stations1.json, src/community/schemaless-features/mongodb-schemaless/src/test/resources/org/geoserver/schemalessfeatures/mongodb/test-data/stations/query/postQuery.xml
[![GEOS-11470](https://badgen.net/badge/JIRA/GEOS-11470/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11470) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7776
=> [Backport 2.25.x] [GEOS-11470] Upgrade the version of Mongo driver for schemaless plugin from 4.0.6 to 4.11.2

src/wms/src/main/java/org/geoserver/wms/CustomDimensionFilterConverter.java, src/wms/src/test/java/org/geoserver/wms/WMSTest.java
[![GEOS-11453](https://badgen.net/badge/JIRA/GEOS-11453/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11453) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7777
**Authored by:** @skalesse
=> [Backport 2.25.x] [GEOS-11453] Failure to look-up default value of custom dimensions on vector layers

src/wms/src/main/java/org/geoserver/wms/CustomDimensionFilterConverter.java, src/wms/src/test/java/org/geoserver/wms/WMSTest.java
[![GEOS-11453](https://badgen.net/badge/JIRA/GEOS-11453/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11453) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7777
**Authored by:** @skalesse
=> [Backport 2.24.x] [GEOS-11453] Failure to look-up default value of custom dimensions on vector layers

src/web/core/src/main/java/org/geoserver/web/css/geoserver.css, src/web/security/core/src/main/java/org/geoserver/security/web/PaletteFormComponent.java, src/web/security/core/src/main/java/org/geoserver/security/web/role/RolePaletteFormComponent.java, src/web/security/core/src/main/java/org/geoserver/security/web/role/RuleRolesFormComponent.java, src/web/security/core/src/main/java/org/geoserver/security/web/user/UserGroupPaletteFormComponent.java
[![GEOS-11502](https://badgen.net/badge/JIRA/GEOS-11502/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11502) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
The presence of a very long role name (e.g. A_VERY_LONG_ROLE_NAME_THAT_CAUSES_THE_TEXTBOX_TO_OVERFLOW) combined with many (in my case over 1000) roles makes it difficult to find and select a role because the vertical scrollbar is “hidden” (off to the right of the “Available” textbox).
e.g.  
I propose to add a resize:both CSS to both .palette-choices and .palette-selected to allow a user to temporarily expand the size of …
=> [GEOS-11502] Permit resize on user/group/role palette textbox to allow for extra long role names

src/web/core/src/main/java/org/geoserver/web/css/geoserver.css, src/web/security/core/src/main/java/org/geoserver/security/web/PaletteFormComponent.java, src/web/security/core/src/main/java/org/geoserver/security/web/role/RolePaletteFormComponent.java, src/web/security/core/src/main/java/org/geoserver/security/web/role/RuleRolesFormComponent.java, src/web/security/core/src/main/java/org/geoserver/security/web/user/UserGroupPaletteFormComponent.java
[![GEOS-11502](https://badgen.net/badge/JIRA/GEOS-11502/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11502) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7837
=> [Backport 2.24.x] [GEOS-11502] Permit resize on user/group/role palette textbox to allow for extra long role names

src/extension/ysld/pom.xml, src/extension/ysld/src/main/java/org/geoserver/ysld/YsldHandler.java, src/extension/ysld/src/main/resources/applicationContext.xml, src/gwc/pom.xml, src/gwc/src/main/java/org/geoserver/gwc/GWCZoomContextFinder.java, src/gwc/src/main/resources/geowebcache-geoserver-context.xml, src/gwc/src/test/java/org/geoserver/gwc/GWCZoomContextFinderTest.java
[![GEOT-7633](https://badgen.net/badge/JIRA/GEOT-7633/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7633) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Follow up to https://github.com/geotools/geotools/pull/4879
In addition to adapting to the GeoTools API change and deprecations, this PR also makes the YSLD module only optionally dependent on GWC, failing back on the well known zoom context finder, in case the GWC one is missing.
=> Follow up to GEOT-7633, Move ZoomContext/ZoomContextFinder class set from YSLD to main

src/pom.xml
[![GEOS-11508](https://badgen.net/badge/JIRA/GEOS-11508/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11508) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7848
=> [Backport 2.25.x] [GEOS-11508] Update OSHI from 6.4.10 to 6.6.3

src/wms/src/test/java/org/geoserver/wms/map/RenderedImageMapOutputFormatTest.java
[![GEOT-7636](https://badgen.net/badge/JIRA/GEOT-7636/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7636) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
The changes in GeoTools corrected the axis along which the densification should be computed, shows up in these tests with very elongated area of interest.
Needs to be merged along with https://github.com/geotools/geotools/pull/4881
=> Follow up to GEOT-7636 changes 

doc/en/user/source/community/cog/mosaic.rst
Added a "." in the mosaic documentation. The ImageMosaic is confusing without the correct reference.  
- [x ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).
=> Added missing reference in ImageMosaic Example

src/extension/monitor/core/src/main/java/org/geoserver/monitor/ows/MonitorCallback.java, src/extension/monitor/core/src/main/java/org/geoserver/monitor/ows/wfs20/GetFeature20Handler.java, src/extension/monitor/core/src/test/java/org/geoserver/monitor/ows/MonitorCallbackTest.java
[![GEOS-11505](https://badgen.net/badge/JIRA/GEOS-11505/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11505) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR adds a new `GetFeature` handler to handle `net.opengis.wfs20.GetFeatureType` requests in the monitor for WFS 2.0. There are some slight changes with how the request type is structured in 2.0, so there have been slight modifications to the handler to address that. (eg. `query` -> `abstractQueryExpression`)
=> [GEOS-11505] Monitor Callback to handle WFS 2.0 `GetFeature` requests

src/main/src/main/java/org/geoserver/security/ResourceAccessManagerWrapper.java, src/main/src/test/java/org/geoserver/security/ResourceAccessManagerWrapperTest.java
Add missing delegating methods `ResourceAccessManagerWrapper.isWorkspaceAdmin()`
and `ResourceAccessManagerWrapper.getSecurityFilter()`.
=> [GEOS-11504] ResourceAccessManagerWrapper misses some delegating methods

src/community/schemaless-features/mongodb-schemaless/src/main/java/org/geoserver/schemalessfeatures/mongodb/data/MongoSchemalessFeatureSource.java, src/community/schemaless-features/mongodb-schemaless/src/main/java/org/geoserver/schemalessfeatures/mongodb/filter/SchemalessFilterToMongo.java
[![GEOS-11503](https://badgen.net/badge/JIRA/GEOS-11503/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11503) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
https://osgeo-org.atlassian.net/browse/GEOS-11503
Current implementation of DWITHIN for Mongo is being delegated to Mongo's $near operator, however, this operator accepts only points. The goal of this task is to refactor delegation to instead make use of $geoIntersects, which accepts other geometry types.
The buffer is being applied to input geometry, and resulting geometry is being used in $geoIntersects.
Depends on …
=> [GEOS-11503] Update mongo schemaless DWITHIN to support non-point geometry

src/extension/authkey/pom.xml
This ends up breaking the packaging of the CSS module, although I have no idea why it started happening just recently.
=> gs-authkey has a compile dependency towards easymock

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/RestconfigWfsTest.java, src/main/src/main/java/org/geoserver/catalog/ResourcePool.java, src/main/src/main/java/org/geoserver/catalog/util/LegacyCatalogImporter.java, src/main/src/main/java/org/vfny/geoserver/util/DataStoreUtils.java, src/main/src/test/java/META-INF/services/org.geotools.api.data.DataStoreFactorySpi, src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java, src/main/src/test/java/org/geoserver/catalog/TestDirectoryStoreFactorySpi.java, src/restconfig/src/main/java/org/geoserver/rest/catalog/DataStoreController.java, src/restconfig/src/test/java/org/geoserver/rest/catalog/DataStoreControllerTest.java
[![GEOS-10824](https://badgen.net/badge/JIRA/GEOS-10824/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10824) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
The testing adds a "fake" datastore that can work off a "URL" parameter, and makes sure the store type is used. In some tests, the store type had to be added to avoid clashes, but at the same time, having this persistence presence in all GeoServer tests helped found issues in the first round of implementation.
=> [GEOS-10824] gs-flatgeobuf extension can clash with "directory of shapefiles" datastores

src/wfs/src/main/java/org/vfny/geoserver/wfs/servlets/TestWfsPost.java, src/wfs/src/test/java/org/vfny/geoserver/wfs/servlets/TestWfsPostTest.java
[![CVE-2024-34696](https://badgen.net/badge/JIRA/CVE-2024/0052CC)](https://osgeo-org.atlassian.net/browse/CVE-2024) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Here is a vulnerability which is fixed in the main branch and 2.25.x(https://github.com/geoserver/geoserver/commit/30cf3972b48c0549e60f84aeb9e3ef94fa3cee74) but is not fixed in the branch of 2.23.x, maybe it should be backported?
=> [Backport 2.23.x] [GEOS-11385] Demo Requests functionality does not honour ENV variable PROXY_BASE_URL

src/gwc/src/main/java/org/geoserver/gwc/ConfigurableQuotaStoreProvider.java, src/gwc/src/test/java/org/geoserver/gwc/GWCQuotaStoreDisabledTest.java
[![GEOS-11556](https://badgen.net/badge/JIRA/GEOS-11556/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11556) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
When disabling the disk quota monitoring (environment variable GWC_DISKQUOTA_DISABLED set to true) there is a NullPointerException in the logs on shut down:
```
WARN 1 --- [ionShutdownHook] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'DiskQuotaStoreProvider': java.lang.NullPointerException: Cannot invoke "org.geowebcache.diskquota.QuotaStore.close()" because "this.store" …
```
=> [GEOS-11556] Fix NPE when DiskQuotaMonitor is disabled

src/main/src/main/java/org/geoserver/catalog/AttributeTypeInfo.java, src/main/src/main/java/org/geoserver/catalog/impl/AttributeTypeInfoImpl.java, src/web/core/src/main/java/org/geoserver/web/data/resource/AttributeTypeInfoEditor.java, src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
[![GEOS-11559](https://badgen.net/badge/JIRA/GEOS-11559/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11559) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
See ticket for details on how to reproduce the issue
=> [GEOS-11559] The customized attributes editor is prone to setting the  wrong attribute source

src/restconfig/src/main/java/org/geoserver/rest/catalog/StructuredCoverageController.java
This PR removes a SEVERE logging message every time a GET request with a filter is sent to StructuredCoverageController. It appears to be a debugging message that wasn't removed from the original implementation. There is no ticket or unit test.
=> Remove unnecessary SEVERE log message from StructuredCoverageController

src/extension/wps/wps-core/src/main/java/org/geoserver/wps/gs/ImportProcess.java, src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/ImportProcessTest.java
Noticed a random failure in WPS, likely due to the countdown latch not being used at all to stop the data iteration.
=> Fixing random test failure in WPS importer process test

src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/gstore/DGGSResolutionCalculator.java, src/community/ogcapi/dggs/dggs-core/src/test/java/org/geotools/dggs/gstore/DGGSResolutionCalculatorTest.java, src/community/ogcapi/dggs/web-dggs/pom.xml, src/community/ogcapi/dggs/web-dggs/src/main/java/org/geoserver/web/publish/dggs/DGGSConfigPanel.html, src/community/ogcapi/dggs/web-dggs/src/main/java/org/geoserver/web/publish/dggs/DGGSConfigPanel.java, src/community/ogcapi/dggs/web-dggs/src/main/java/org/geoserver/web/publish/dggs/DGGSConfigurationPageInfo.java, src/community/ogcapi/dggs/web-dggs/src/main/resources/GeoServerApplication.properties, src/community/ogcapi/dggs/web-dggs/src/main/resources/applicationContext.xml, src/community/ogcapi/dggs/web-dggs/src/test/java/org/geoserver/web/publish/dggs/DGGSConfigPanelTest.java
[![GEOS-11563](https://badgen.net/badge/JIRA/GEOS-11563/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11563) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11563] Allow configuring a DGGS resolution offset on a layer basis

src/community/ogcapi/web-ogcapi/src/test/java/org/geoserver/web/ogcapi/AbstractLinksEditorTest.java, src/community/proxy-base-ext/src/test/java/org/geoserver/proxybase/ext/web/ProxyBaseExtensionConfigPageTest.java, src/extension/importer/web/src/test/java/org/geoserver/importer/web/ImportTaskTableTest.java, src/extension/metadata/src/test/java/org/geoserver/metadata/web/BulkOperationsPageTest.java, src/extension/metadata/src/test/java/org/geoserver/metadata/web/LayerMetadataTabTest.java, src/extension/metadata/src/test/java/org/geoserver/metadata/web/TemplatesPageTest.java, src/extension/web-resource/src/test/java/org/geoserver/web/resources/PageResourceBrowserTest.java, src/extension/wps/web-wps/src/test/java/org/geoserver/wps/web/ProcessStatusPageTest.java, src/pom.xml, src/web/core/src/test/java/org/geoserver/web/GeoServerWicketTestSupport.java, src/web/core/src/test/java/org/geoserver/web/data/layergroup/LayerGroupEditPageTest.java, src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java, src/web/core/src/test/java/org/geoserver/web/wicket/CRSPanelTest.java, src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.java, src/web/demo/src/test/java/org/geoserver/web/demo/MapPreviewPageTest.java, src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/CachedLayersPageTest.java, src/web/security/core/src/main/java/org/geoserver/security/web/user/AbstractUserPage.java, src/web/security/core/src/test/java/org/geoserver/security/web/AbstractSecurityNamedServicePanelTest.java, src/web/security/core/src/test/java/org/geoserver/security/web/url/URLChecksPageTest.java, src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java, src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleNewPageTest.java
All the modules that received a junit-jupiter dependency during the Wicket 9 upgrade are not running their tests anymore:
```
community/monitor-kafka/pom.xml:      <artifactId>junit-jupiter-api</artifactId>
community/security/keycloak/pom.xml:      <artifactId>junit-jupiter</artifactId>
extension/css/pom.xml:      <artifactId>junit-jupiter</artifactId>
extension/csw/web-csw/pom.xml:      <artifactId>junit-jupiter</artifactId>
extension/geofence/geofence-server/pom.xml:      <artifactId>junit-jupiter</artifactId>
extension/geofence/geofence/pom.xml:      <artifactId>junit-jupiter</artifactId>
extension/geopkg-output/pom.xml:      <artifactId>junit-jupiter</artifactId>
extension/grib/pom.xml:      <artifactId>junit-jupiter</artifactId>
extension/gwc-s3/pom.xml: …
```
=> Run JUnit tests in all modules that received a JUnit 5 dependency

src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/gstore/DGGSResolutionCalculator.java, src/community/ogcapi/dggs/dggs-core/src/test/java/org/geotools/dggs/gstore/DGGSResolutionCalculatorTest.java, src/community/ogcapi/dggs/web-dggs/src/main/java/org/geoserver/web/publish/dggs/DGGSConfigPanel.html, src/community/ogcapi/dggs/web-dggs/src/main/java/org/geoserver/web/publish/dggs/DGGSConfigPanel.java, src/community/ogcapi/dggs/web-dggs/src/main/resources/GeoServerApplication.properties, src/community/ogcapi/dggs/web-dggs/src/test/java/org/geoserver/web/publish/dggs/DGGSConfigPanelTest.java, src/main/src/main/java/org/vfny/geoserver/global/GeoServerFeatureSource.java
[![GEOS-11565](https://badgen.net/badge/JIRA/GEOS-11565/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11565) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11565] Allow configuring the minimum and maximum resolution for a layer

src/extension/csw/csw-iso/src/main/java/org/geoserver/csw/records/iso/QueryableMappingRecordDescriptor.java, src/extension/csw/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/MetadataDescriptorTest.java
[![GEOS-11524](https://badgen.net/badge/JIRA/GEOS-11524/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11524) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11524] csw: default queryables mapping not generated

src/community/hz-cluster/src/main/webapp/WEB-INF/web.xml, src/security/security-tests/src/test/resources/org/geoserver/security/impl/web1.xml, src/security/security-tests/src/test/resources/org/geoserver/security/impl/web2.xml, src/web/app/src/main/webapp/WEB-INF/web.xml
[![GEOS-11562](https://badgen.net/badge/JIRA/GEOS-11562/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11562) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
The gzip filter settings for the GeoServer web application are established by the web.xml file found in the GeoServer Web App sub-project.  Additionally, copies of web.xml are found in a few other sub-projects.  This update changes the Content-Type that will be compressed by the gzip filter from 'application/x-javascript', which is generally not used anymore, to 'application/javascript', which is requested by modern …
=> [GEOS-11562] - change gzip filter to compress `application/javascript`

src/community/cog/cog-s3/src/assembly/assembly.xml
The dependency `AWS SDK` of the `cog-s3` plugin requires additional libraries after it was upgraded from version 2.24.13 to 2.27.23.
This fixes the issue discussed in https://discourse.osgeo.org/t/missing-jars-for-cog-s3-plugin-in-assembly-xml/110332
=> Add missing JARs to assembly.xml file for cog-s3 plugin

src/extension/monitor/core/src/main/java/org/geoserver/monitor/web/ActivityChartBasePanel.html, src/extension/wps/web-wps/src/main/java/org/geoserver/wps/web/WPSAccessRulePage.html, src/main/src/main/java/org/geoserver/GeoServerNodeData.java, src/web/core/src/main/java/org/geoserver/web/DefaultGeoServerNodeInfo.java, src/web/core/src/main/java/org/geoserver/web/GeoServerApplication.java, src/web/core/src/main/java/org/geoserver/web/css/geoserver.css, src/web/core/src/main/java/org/geoserver/web/data/resource/DimensionEditorBase.java, src/web/core/src/main/java/org/geoserver/web/wicket/browser/FileDataView.java, src/web/core/src/test/java/org/geoserver/web/CustomGeoServerNodeIdTest.java, src/web/demo/src/main/resources/org/geoserver/web/demo/demo-requests.css, src/web/gwc/src/main/java/org/geoserver/gwc/web/diskquota/StatusBar.java, src/web/gwc/src/main/java/org/geoserver/gwc/web/diskquota/statusbar.css, src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/GridSubsetsEditor.java, src/web/security/core/src/main/java/org/geoserver/security/web/AbstractConfirmRemovalPanel.html, src/web/security/core/src/main/java/org/geoserver/security/web/SecurityNamedServiceEditPage$ErrorPanel.html, src/web/wms/src/main/java/org/geoserver/wms/web/data/ExternalGraphicPanel.java, src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleEditPage.java, src/web/wms/src/main/java/org/geoserver/wms/web/data/StylePage.css
This PR fixes some CSP issues with after the Wicket 9 upgrade. The big one is with the node info since that has an API change.
The org.geoserver.web.csp.strict property isn't working correctly and this PR fixes it so that it actually disables blocking CSP violations by default. My separate CSP PR that Jody is reviewing allows an administrator to switch between blocking or reporting headers or completely disabling CSP through the UI.
The period in front of CSS class names actually matters and isn't just a code style issue. An easy way to to see this is that the Style Editor is missing a black border around the main text editor (at least in Chrome).
I'm only reviewing a few extensions and no community modules but besides the modal dialog and the Tile Layers page, the remaining CSP …
=> Fixed some Wicket CSP violations

doc/en/user/source/extensions/printing/protocol.rst, src/extension/printing/src/test/resources/test.yaml, src/pom.xml
[![GEOS-11587](https://badgen.net/badge/JIRA/GEOS-11587/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11587) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport https://github.com/geoserver/geoserver/pull/7794
Backport https://github.com/geoserver/geoserver/pull/7989
=> [Backport 2.25.x] [GEOS-11587] Update mapfish-print-v2 to version 2.3.2

doc/en/user/source/installation/upgrade.rst, src/gwc/pom.xml, src/gwc/src/main/java/org/geoserver/gwc/JDBCConfigurationStorage.java, src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
[![GEOS-11588](https://badgen.net/badge/JIRA/GEOS-11588/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11588) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This makes use of https://github.com/GeoWebCache/geowebcache/pull/1327
=> [GEOS-11588] Use JDBCConfiguration.validateConfiguration to provide feedback

src/pom.xml
Bumps GeoFence from 3.7-SNAPSHOT to 3.7.2.
No recent changes in 3.7.x branch.
=> Bump GeoFence to 3.7.2

src/platform/src/test/java/org/geoserver/platform/resource/FileSystemResourceTheoryTest.java
This test tends to often fail on Windows. Let's try to give it a bit more time.
=> More Windows VM tolerance for FileSystemResourceTheoryTest

doc/en/user/source/services/wms/get_legend_graphic/index.rst
The way it is stated now is misleading, because the LEGEND_OPTIONS params are required, but they are mentioned after the optional parameters.
=> Clarify the requirements for Content dependent legends parameters

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/ConformanceClass.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/FunctionsDocument.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/Queryables.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/QueryablesBuilder.java, src/community/ogcapi/ogcapi-core/src/main/resources/org/geoserver/ogcapi/queryables.ftl, src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/QueryablesBuilderTest.java, src/community/ogcapi/ogcapi-features/pom.xml, src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/FeatureService.java, src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/FeaturesAPIBuilder.java, src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/v1/features/functions.ftl, src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/v1/features/landingPage.ftl, src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/v1/features/openapi.yaml, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/ApiTest.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/CollectionTest.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/CollectionsTest.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/ConformanceTest.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/FeatureTest.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/FunctionsTest.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/LandingPageTest.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/QueryablesTest.java, src/community/ogcapi/ogcapi-features/src/test/resources/org/geoserver/ogcapi/v1/features/functions-schema.yml, src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/v1/tiles/QueryablesTest.java, src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACQueryablesBuilder.java, src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/v1/stac/queryables-common.ftl, src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/v1/stac/sortables-common.ftl, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/ApiTest.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/QueryablesTest.java, src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/SortablesTest.java, src/pom.xml
We were implementing and early draft, the finalized standard has a number of differences, closed the gap.
=> Re-align the Features - Part 3, Filtering implementation with the finalized standard

src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/CollectionDocument.java, src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/CollectionsDocument.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/CollectionTest.java
@groldan this should hopefully fix some of the OGC API - Features test failures in https://github.com/geoserver/geoserver/pull/8017
=> Make sure the storage-crs is in the target crs list

build/cite/ogcapi-features10/release/wfs.xml, build/cite/ogcapi-features10/release/workspaces/tiger/nyc/giant_polygon/featuretype.xml
`EPSG:4087` (WGS 84 / World Equidistant Cylindrical) is a global projection, while `EPSG:3857` (WGS 84 / Pseudo-Mercator) is not.
Since the `ogcapi-features-1.0` ETS fails while doing coordinate transformations on itself, despite GeoServer having returned transformed geometries (albeit outside the area of validity of the target CRS), let's use two default published CRS's that cover the whole globe.
Re-enable the `tiger:giant_polygon` layer, since now it can be reprojected across the declared global CRS's.
=> ogcapi-features10 CITE: swap default published CRS 3857 by 4087

src/community/ogcapi/ogcapi-changeset/src/main/java/org/geoserver/ogcapi/v1/changeset/ZippedChangesetMessageConverter.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIBodyMethodProcessor.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/MappingJackson2HttpMessageConverter.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/MappingJackson2YAMLMessageConverter.java, src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/Queryables.java, src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/FeatureService.java, src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/v1/features/landingPage.ftl, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/QueryablesTest.java, src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/v1/tiles/CollectionTest.java
[![GEOS-11540](https://badgen.net/badge/JIRA/GEOS-11540/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11540) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11540] OGC API queryables features call not working in JSON

src/ows/src/main/java/org/geoserver/ows/Dispatcher.java, src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetFeatureTest.java, src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureTest.java
[![GEOS-11611](https://badgen.net/badge/JIRA/GEOS-11611/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11611) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11611] When Extracting the WFS Service Name from the HTTP Request A Slash Before the Question Marks Causes Issues

.github/workflows/cite.yml, build/cite/wms13/wms-1.3.0.xml, src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java, src/platform/src/main/java/org/geoserver/platform/ServiceException.java, src/wms/src/main/java/org/geoserver/wms/WMS.java, src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetMapIntegrationTest.java
[![GEOS-11622](https://badgen.net/badge/JIRA/GEOS-11622/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11622) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Enables WMS 1.3 CITE tests too.
=> [GEOS-11622] WMS 1.3 should return InvalidCRS exception code when fed an invalid CRS

doc/en/user/source/extensions/controlflow/CONTROL_FLOW_LOGGING.xml, doc/en/user/source/extensions/controlflow/index.rst, src/extension/control-flow/src/main/java/org/geoserver/flow/ControlFlowCallback.java, src/extension/control-flow/src/main/java/org/geoserver/flow/controller/HttpHeaderPriorityProvider.java, src/extension/control-flow/src/main/java/org/geoserver/flow/controller/IpFlowController.java, src/extension/control-flow/src/main/java/org/geoserver/flow/controller/PriorityThreadBlocker.java, src/extension/control-flow/src/main/java/org/geoserver/flow/controller/QueueController.java, src/extension/control-flow/src/main/java/org/geoserver/flow/controller/SimpleThreadBlocker.java, src/extension/control-flow/src/main/java/org/geoserver/flow/controller/SingleIpFlowController.java, src/extension/control-flow/src/main/java/org/geoserver/flow/controller/UserConcurrentFlowController.java
[![GEOS-11613](https://badgen.net/badge/JIRA/GEOS-11613/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11613) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11613] Increase control-flow logging admin visibility in logs

build/cite/ogcapi-features10/build-ets.sh
Revert to build the `ogccite/ets-ogcapi-features10:1.8-SNAPSHOT-teamengine-5.4.1` docker image for ogcapi-features CITE testing from the official repository's `master` branch now that the [requried fix](https://github.com/opengeospatial/ets-ogcapi-features10/pull/255) is merged.
=> ogcapi-features CITE tests: build from official git repository

build/cite/ogcapi-features10/build-ets.sh, build/cite/ogcapi-features10/compose.override.yml
Update `build/cite/ogcapi-features10/build-ets.sh` to use the new `1.8` tag and hence the `ogccite/ets-ogcapi-features10:1.8-teamengine-5.7` docker image, which is still not published in dockerhub.
This could be left as-is from now on since at least we now have a stable git tag to build from that includes the required fixes to the test engine.
=> ogcapi-features CITE: build 1.8-teamengine-5.7 image out of the 1.8 tag upstream

src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java, src/restconfig/src/test/java/org/geoserver/rest/catalog/DataStoreControllerTest.java
One more follow up on https://github.com/geotools/geotools/pull/4973 (all QA builds in GeoServer are now failing)
@elahrvivaz when deprecating methods you should make sure that nothing is using them any longer, including in GeoServer. 
We should probably have a "downstream QA" build in GeoTools to prevent this from happening.
=> Update calls to deprecated methods in DataStoreFinder

src/main/src/main/java/org/geoserver/security/impl/DataAccessRuleDAO.java, src/security/security-tests/src/test/java/org/geoserver/security/impl/DataAccessRuleDAOTest.java, src/web/security/core/src/main/java/org/geoserver/security/web/data/DataSecurityPage.java
[![GEOS-11616](https://badgen.net/badge/JIRA/GEOS-11616/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11616) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Follow up to file system isolation, found a couple if issues in the implementation.
=> [GEOS-11616] GSIP 229 - File system access isolation. Bug fixes

src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/v1/coverages/CollectionDocument.java, src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/v1/coverages/CollectionsDocument.java, src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/v1/coverages/CollectionsTest.java, src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/CollectionsDocument.java, src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/CollectionsTest.java, src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/v1/maps/CollectionDocument.java, src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/v1/maps/CollectionsDocument.java, src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/CollectionsTest.java
[![GEOS-11621](https://badgen.net/badge/JIRA/GEOS-11621/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11621) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
…ers Setting
Got features test working
added maps collections
added coverages
cleanup
fixed features and coverages not to return null when skipping
fixed nulls for maps
Changed to non-recursion version
removed redundant check
One more redundant
[GEOS-11621] OGC API Services Not Honoring the Skip Misconfigured Layers Setting 2.25.x backport
=> [GEOS-11621] OGC API Services Not Honoring the Skip Misconfigured Layers Setting 2.25.x backport

doc/en/user/source/configuration/globalsettings.rst, doc/en/user/source/configuration/properties/index.rst, src/main/src/main/java/org/geoserver/ows/ProxifyingURLMangler.java, src/main/src/main/java/org/vfny/geoserver/util/Requests.java, src/main/src/test/java/org/geoserver/ows/URLManglersTest.java
[![GEOS-11612](https://badgen.net/badge/JIRA/GEOS-11612/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11612) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Currently, system property activation [is supported for Proxy base URL setting on GeoServer](https://docs.geoserver.org/main/en/user/configuration/globalsettings.html#proxy-base-url), but there is no option to enable the Use Headers setting using the same approach.  This task is focused on add the same flags support level in order to sync both features activation.
The proposed system property is on the example:
``` …
```
=> [GEOS-11612] Add proxy base url use headers system property support

.github/workflows/assembly.yml, src/community/security/keycloak/pom.xml, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml, src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdConnectIntegrationTest.java, src/community/web-service-auth/pom.xml, src/community/web-service-auth/src/test/java/org/geoserver/security/auth/WebAuthProviderTest.java, src/extension/mapml/pom.xml, src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLBaseProxyTest.java, src/extension/wps/wps-core/pom.xml, src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteURLCheckTest.java, src/extension/wps/wps-core/src/test/java/org/geoserver/wps/executor/RemoteRequestInputProviderTest.java, src/pom.xml, src/web/core/pom.xml, src/web/core/src/test/java/org/geoserver/web/data/store/WMSStoreNewPageTest.java, src/web/core/src/test/java/org/geoserver/web/data/store/WMTSStoreNewPageTest.java, src/wms/pom.xml, src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapURLCheckersTest.java
Upgrade the wiremock dependency to the current version. GeoServer uses the standalone JAR which includes all of its dependencies under a separate package so it isn't impacted by wiremock's Tomcat 11 and Jakarta EE dependencies.
The assembly workflow was updated to ensure that community modules are built using the root GeoServer POM from the local PR branch and not what is published in the public Maven repository which would cause invalid POM errors when a PR adds or changes a dependency's groupId/artifactId in the root POM.
One of the WPS test classes was updated to properly use the class rule which improves performance when the test classes contain a lot of tests. Some tests that programmatically handle the wiremock server weren't shutting down the server when the tests were finished and …
=> Upgrade wiremock from 2.35.1 to 3.10.0

src/community/jwt-headers/jwt-headers-util/src/main/java/org/geoserver/security/jwtheaders/token/TokenSignatureValidator.java
For some Geonetwork 5 development, it would be nice to load JWK Sets (i.e. public keys) from `"file://..."` URLs.  The underlying library doesn't allow this.
This PR uses the URL#open() stream instead of having the library read the URL.
=> JWT Headers - better handling of JWK Set URL reading

.github/workflows/cite.yml
Received a mail that v3 is going to be brownout-ed soon and then effectively removed January 30th 2025.
Updating to v4.
See:
* https://github.com/actions/download-artifact
* https://github.com/actions/upload-artifact
=> Github actions: updating artifact upload/download to v4

src/web/core/src/main/java/org/geoserver/web/GeoServerApplication.java, src/web/core/src/main/java/org/geoserver/web/data/store/AbstractCoverageStorePage.java, src/web/core/src/main/java/org/geoserver/web/data/store/AbstractDataAccessPage.java, src/web/core/src/main/java/org/geoserver/web/data/store/AbstractWMSStorePage.java, src/web/core/src/main/java/org/geoserver/web/data/store/AbstractWMTSStorePage.java, src/web/core/src/test/java/org/geoserver/web/data/store/CoverageStoreNewPageTest.java, src/web/core/src/test/java/org/geoserver/web/data/store/DataAccessEditPageTest.java, src/web/core/src/test/java/org/geoserver/web/data/store/DataAccessNewPageTest.java
[![GEOS-11636](https://badgen.net/badge/JIRA/GEOS-11636/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11636) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Same tests , different implementation in wicket 7
=> [2.26.x backport] [GEOS-11636] Store panels won't always show feedback in target panels

src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/gstore/DGGSResolutionCalculator.java, src/community/ogcapi/dggs/dggs-core/src/test/java/org/geotools/dggs/gstore/DGGSResolutionCalculatorTest.java, src/community/ogcapi/dggs/web-dggs/src/main/java/org/geoserver/web/publish/dggs/DGGSConfigPanel.html, src/community/ogcapi/dggs/web-dggs/src/test/java/org/geoserver/dggs/DGGSIntegrationTest.java
[![GEOS-11637](https://badgen.net/badge/JIRA/GEOS-11637/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11637) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Along with it, there is a quick fix for renamed DGGS layers and a GUI label fix.e
=> [GEOS-11637] DGGS min/max resolution settings stop working after restart

src/wcs/src/main/java/org/vfny/geoserver/util/WCSUtils.java, src/wcs/src/test/java/org/vfny/geoserver/util/WCSUtilsTest.java, src/wcs1_0/src/main/java/org/geoserver/wcs/DefaultWebCoverageService100.java, src/wcs1_0/src/test/java/org/geoserver/wcs/GetCoverageTest.java, src/wcs1_1/src/main/java/org/geoserver/wcs/DefaultWebCoverageService111.java, src/wcs1_1/src/test/java/org/geoserver/wcs/GetCoverageTest.java, src/wcs2_0/src/main/java/org/geoserver/wcs2_0/GetCoverage.java, src/wcs2_0/src/test/java/org/geoserver/wcs2_0/xml/GetCoverageTest.java, src/wcs2_0/src/test/resources/requestGetCoverageSlice.xml
[![GEOS-11643](https://badgen.net/badge/JIRA/GEOS-11643/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11643) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11643] WCS input read limits can be fooled by geotiff reader

doc/en/api/1.0.0/security.yaml, src/restconfig/src/main/java/org/geoserver/rest/security/CatalogSecurityController.java, src/restconfig/src/test/java/org/geoserver/rest/security/AccessControllersTest.java
[![GEOS-11644](https://badgen.net/badge/JIRA/GEOS-11644/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11644) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
By default, the rest/catalog/reload GeoServer REST endpoint only refreshes the GeoServer catalog and does not reload the Security Manager. To address this limitation, we propose adding a dedicated endpoint that allows an administrator to programmatically trigger a Security Manager reload.
This feature is particularly useful when batch operations directly modify security files on disk (e.g., adding or removing roles), and …
=> [GEOS-11644] Introducing the rest/security/acl/catalog/reload rest endpoint

src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/request/TemplatePathVisitor.java, src/extension/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIBBoxParser.java, src/extension/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/ApiTest.java, src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterDownload.java, src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java, src/main/src/main/java/org/geoserver/catalog/CoverageViewReader.java, src/main/src/main/java/org/geoserver/logging/LoggingUtilsDelegate.java, src/wcs1_0/src/main/java/org/geoserver/wcs/kvp/BBoxKvpParser.java, src/wcs1_1/src/main/java/org/geoserver/wcs/kvp/BoundingBoxKvpParser.java, src/wfs/src/main/java/org/geoserver/wfs/WFSGetFeatureOutputFormat.java, src/wfs/src/main/java/org/geoserver/wfs/kvp/BBoxKvpParser.java, src/wfs/src/test/java/org/geoserver/wfs/MaxFeaturesTest.java
https://osgeo-org.atlassian.net/browse/GEOS-11654
Multiline strings where the second line starts with a character, should end with a space in the previous line:
e.g. 
```java
throw new IllegalArgumentException(
"Requested bounding box contains wrong"
+ "number of coordinates (should have "
...
```
produces `<ows:ExceptionText>java.lang.IllegalArgumentException: Requested bounding box contains wrongnumber of coordinates (should have 4): 0
Requested bounding box contains wrongnumber of coordinates (should have 4): 0</ows:ExceptionText>`
I picked up most with `find . -type f -exec awk '/[^\\][a-zA-Z]"$/ { getline nextline; if (nextline ~ /^[ \t]*\+\s"[a-zA-Z]/) {print FILENAME, $0 "\n" nextline }}' {} +` 
i.e. a character (not preceded by a backslash \) then quotes then newline then …
=> [GEOS-11654] Fix multiline strings that are missing a space between the lines

src/rest/pom.xml, src/rest/src/main/java/org/geoserver/rest/RestControllerAdvice.java, src/rest/src/main/java/org/geoserver/rest/util/RESTUtils.java, src/rest/src/test/java/org/geoserver/rest/ExceptionHandlingTest.java, src/rest/src/test/java/org/geoserver/rest/LoggingCapturer.java
[![GEOS-11647](https://badgen.net/badge/JIRA/GEOS-11647/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11647) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
In [this commit](e57616971c4c11f6efdd7d12b855b509fbbe9ae1) from 2014, each resource lookup in the REST API would check for the configuration setting, and avoid throwing `RestletException` (which we use `ResourceNotFoundException` for those cases).
For example:
```
boolean quietOnNotFound=quietOnNotFoundEnabled(request)
if(quietOnNotFound){
return null;
}
throw new RestletException( "No such layer: " + layer, …
```
=> [GEOS-11647] Restore "quiet on not found" configuration for REST in global settings

src/web/core/src/main/java/org/geoserver/web/data/resource/DimensionEditorBase.java, src/web/core/src/test/java/org/geoserver/web/data/resource/DimensionEditorTest.java
[![GEOS-11658](https://badgen.net/badge/JIRA/GEOS-11658/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11658) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
See ticket.
Supercedes https://github.com/geoserver/geoserver/pull/8128 (the reverted commit is simply removed, QA should pass, has a Jira ticket reference). Count this PR as a review :rofl: 
=> [GEOS-11658] Time editor dumps stack trace in UI if the start or end time values are intervals

src/pom.xml
This dependency upgrade fixes a critical bug that can cause getLogger to return null.
=> Updated log4j from 2.24.1 to 2.24.3

src/main/src/main/java/org/geoserver/security/csp/CSPConfiguration.java, src/web/core/src/main/java/org/geoserver/web/GeoServerApplication.java
Using the `Content-Security-Policy-Report-Only` header was necessary to support the Wicket 9 upgrade but the `Content-Security-Policy` header which blocks CSP violations can be used now that most of the remaining CSP violations, particularly the modal window, have been resolved. This will provide a more secure default mode, make any remaining CSP violations (if there are any left) more obvious and ensure that developers do not add new CSP violations.
=> [GEOS-11346] Enable strict Content-Security-Policy by default

src/web/core/src/main/java/org/geoserver/web/wicket/ColorPickerField.java, src/web/core/src/main/java/org/geoserver/web/wicket/js/jscolor/jscolor.js
[![GEOS-11669](https://badgen.net/badge/JIRA/GEOS-11669/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11669) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR patches the jscolor library to parse the JSON using JSON.parse instead of eval which is blocked by Wicket's CSP and updates the ColorPickerField class to be valid JSON. I looked into upgrading jscolor instead but it has other CSP violations that would need to be patched anyways. The indentation only looks weird because the jscolor file uses tabs but the code I added uses spaces.
=> [GEOS-11669] Patch jscolor to work with Wicket's CSP

src/pom.xml
Using certain Spring Framework functionality without the parameters flag will cause warnings in version 6.0 and errors in 6.1.
=> Configure compiler to use -parameters flag

src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/ImportProcessTest.java, src/restconfig/src/main/java/org/geoserver/rest/catalog/StyleController.java, src/restconfig/src/test/java/org/geoserver/rest/catalog/StyleControllerTest.java
Two changes:
* One test uses the same feature type in two test methods, isolated it better
* The other checks the contents of the shared java temp directory, which other concurrently building modules might also touch (moved to isolated directory)
=> Some more attempts to remove random github failures

src/rest/src/test/java/org/geoserver/rest/util/IOUtilsTest.java
[![GEOS-11689](https://badgen.net/badge/JIRA/GEOS-11689/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11689) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Improving build stability
=> [GEOS-11689] IOUtilsTest should not ping an external web site

src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/domain/DomainModelBuilder.java, src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/JDBCFixtureHelper.java, src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/postgis/MeteoStationsPostGISTestSetUp.java, src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/postgis/PostGisDomainModelBuilderTest.java, src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/postgis/mockdata/meteo_int8_db.sql
[![GEOS-11691](https://badgen.net/badge/JIRA/GEOS-11691/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11691) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
[GEOS-11691] Smart data loader acepts bigint and bigserial but not int8 postgresql type alias
https://osgeo-org.atlassian.net/browse/GEOS-11691
This PR introduces a fix for int8 postgresql type support on smart data loader module (bug described on the JIRA issue).
=> [GEOS-11691] Smart data loader accepts bigint and bigserial but not int8 postgresql type alias

src/gwc/src/main/java/org/geoserver/gwc/dispatch/GeoServerSecurityFilter.java, src/gwc/src/test/java/org/geoserver/gwc/dispatch/GeoServerSecurityFilterTest.java
[![GEOS-11677](https://badgen.net/badge/JIRA/GEOS-11677/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11677) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR hides version information and some other internal server information from the GeoWebCache home page unless the user is logged in as an administrator. The code that determines whether to hide the information is the same as what is used for the About GeoServer page.
This PR is dependent on the GeoWebCache PR https://github.com/GeoWebCache/geowebcache/pull/1345 and will fail until that PR is merged.
For core and …
=> [GEOS-11677] Hide version info on GWC home page

src/extension/printing/pom.xml, src/pom.xml
[![GEOS-10844](https://badgen.net/badge/JIRA/GEOS-10844/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10844) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Exclude transitive dependency on xml-apis from xerces and mapfish print
Hopefully remove `xml-apis` from transitive dependencies for good.
Following up on the cruzade to remove `xml-apis` from the build. See
* [GEOS-10844] (cecc81111fd15f98d7ca96d7aa918fe4585a6ce5)
* Exclude `xml-apis` and apache `fop` in the root pom: (95852c258b59c106a2b81898ddd6812663d6e078)
* Remove dependency on xml-apis-xerces on the printing …
=> [GEOS-10844] Exclude xml-apis from build

src/security/ldap/pom.xml, src/web/security/ldap/pom.xml
[![GEOS-11713](https://badgen.net/badge/JIRA/GEOS-11713/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11713) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11713] Concurrent LDAP builds fail on Jenkins

src/web/core/src/main/java/org/geoserver/web/wicket/CRSPanel.java, src/web/core/src/main/java/org/geoserver/web/wicket/EnvelopePanel.java, src/web/wcs/src/main/java/org/geoserver/wcs/web/demo/WCSRequestBuilderPanel.java
[![GEOS-11706](https://badgen.net/badge/JIRA/GEOS-11706/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11706) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Created from @davidblasby https://github.com/geoserver/geoserver/pull/8247, breakout out as a distinct PR so it can be back ported to 2.26:
On the WCSRequest page (demos).  There are two CRSs - the `EPSG:..` is a link, but it wasn't doing anything.  This was a side effect of changing the coverage - the changes were not recognized by the two CRSPanels.
=> [GEOS-11706] fix WCS Request panel - get CRS details (both)

doc/en/user/source/extensions/vectortiles/install.rst
I think you should simply provide the actual path to the folder. For me installing a plugin first time I needed to do an 'extensive search' to get this simple information.
=> Make tutorial easier to understand by using full path to plugin folder in vectortiles tutorial.

src/wfs/src/main/java/org/geoserver/wfs/xml/WFSXmlUtils.java, src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureTest.java
[![GEOS-11716](https://badgen.net/badge/JIRA/GEOS-11716/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11716) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
If a layer is currently in an erroneous state (e.g. the backing source table has been deleted), POST requests to WFS GetFeature fail with an error, even when the request does not query the problematic layer.
These changes add the possibility to avoid failures in these cases, checking the value of global's `ResourceErrorHandling`.
=> [GEOS-11716] Added resource error handling check while initializing WFS configuration.

src/main/src/main/java/org/geoserver/catalog/CoverageViewPamResourceInfo.java, src/main/src/main/java/org/geoserver/catalog/CoverageViewReader.java, src/main/src/test/java/org/geoserver/catalog/CoverageViewTest.java
[![GEOS-11722](https://badgen.net/badge/JIRA/GEOS-11722/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11722) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Testing wise, I've verified that enabling MT does not change the result, and checked with debugging that full MT loading is happening. I don't see a reasonable and clean way to actually test full MT loading is happening.
The PR will be merged when all the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html …
=> [GEOS-11722] Coverage view reader partially ignores multithreaded loading

src/pom.xml
Enforcing Maven 3.8+ ensures consistent plugin version resolution across all environments. Different Maven versions may resolve plugin versions differently due to changes in:
- Default lifecycle plugin mappings (e.g., maven-compiler-plugin, maven-surefire-plugin)
- Dependency resolution behavior for both plugins and their transitive dependencies
- Compatibility improvements and bug fixes in newer Maven versions
By standardizing the required Maven version, we can ensure:
- Plugins work correctly with the expected Maven features
- Consistent builds in both developer machines and CI/CD environments
- Easier decision-making regarding which plugin versions to use for compatibility and stability
This change will prevent unexpected build failures or inconsistencies caused by older Maven versions …
=> Enforce Maven 3.8+ for improved plugin version resolution

src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/metadata/jdbc/utils/JdbcUrlSplitter.java, src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/metadata/jdbc/utils/JdbcUrlSplitterTest.java
[![GEOS-11620](https://badgen.net/badge/JIRA/GEOS-11620/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11620) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-11620
This PR solves the problem between smart data loader and the new postgres store JDBC URL parameters.
=> [GEOS-11620] Fix JDBC URL parsing issue on Smart data loader

src/security/jdbc/pom.xml, src/security/jdbc/src/test/java/org/geoserver/security/jdbc/H2JNDIRoleServiceTest.java, src/security/jdbc/src/test/java/org/geoserver/security/jdbc/H2JNDITestConfig.java, src/security/jdbc/src/test/java/org/geoserver/security/jdbc/H2JNDIUserDetailsServiceTest.java, src/security/jdbc/src/test/java/org/geoserver/security/jdbc/H2JNDIUserGroupServiceTest.java, src/security/jdbc/src/test/resources/jndi.properties
Re-enabled `sec-jdbc` JNDI tests by replacing the `jndi.properties` file with an in-code JNDI configuration to prevent interference when running GeoServer from `Start.java` in the `web-app` module. The presence of `jndi.properties` caused errors due to `org.osjava.sj.SimpleContextFactory` not being in the classpath during application startup, once per `DataStoreInfo`.
To resolve this, `H2JNDITestConfig` was introduced as a JUnit4 `@ClassRule` to dynamically configure JNDI properties only during test execution.
The new rule has been applied to `H2JNDIRoleServiceTest`, `H2JNDIUserDetailsServiceTest`, and `H2JNDIUserGroupServiceTest`.
Additionally, `pom.xml` has been updated to remove the `test.exclude.pattern`, allowing JNDI tests to run again, and the `simple-jndi` dependency has been …
=> Re-enable sec-jdbc module's JNDI tests without requiring jndi.properties file

src/main/src/main/java/org/geoserver/GeoserverInitStartupListener.java, src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java, src/wms/src/test/java/org/geoserver/wms/map/RenderedImageMapOutputFormatTest.java
[![GEOS-11747](https://badgen.net/badge/JIRA/GEOS-11747/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11747) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR updates GeoServer's ImagingListener to throw runtime exceptions that don't come from an OperationRegistry and don't meet the other conditions to hide an exception. It was also moved into a separate method that is called in GeoServerSystemTestSupport so that all GeoServer unit tests now use the GeoServer listener instead of the GeoTools one. The GeoTools listener has the same if statement to throw JAI runtime …
=> [GEOS-11747] GeoServer does not throw JAI runtime exceptions

src/main/src/main/java/org/geoserver/security/password/ConfigurationPasswordEncryptionHelper.java, src/main/src/test/java/org/geoserver/security/password/ConfigurationPasswordEncryptionHelperTest.java
[![GEOS-11757](https://badgen.net/badge/JIRA/GEOS-11757/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11757) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
The `ConfigurationPasswordEncryptionHelper` class has been updated to improve performance by caching encrypted fields based on the StoreInfo type when the class cache is hit.
Previously, when a DataStoreInfo object lacked a type property, the method would repeatedly invoke `getCatalog().getResourcePool().getDataStoreFactory(info)`, causing unnecessary factory lookups and expensive serialization/deserialization operations …
=> [GEOS-11757] Optimize ConfigurationPasswordEncryptionHelper to cache encrypted fields by store type

src/web/core/src/test/java/org/geoserver/web/admin/StatusPageTest.java
Avoids stack exception stack traces due to wicket storing the page in the session while running web-app's Start during development
=> Make StatusPageTest.ExtraTabDefinition serializable

src/main/src/main/java/org/geoserver/catalog/impl/AbstractCatalogFacade.java, src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java
[![GEOS-11755](https://badgen.net/badge/JIRA/GEOS-11755/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11755) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
The data directory loading process involves loading all catalog objects to a temporary catalog and then synchronizing the real catalog with the temporary one.
In doing so, AbstractCatalogFacade.resolve() does not replace the catalog property of `StyleInfoImpl`, `ResourceInfoImpl`, and `StoreInfoImpl`, with the real catalog reference, hence leaving all those objects with dangling references to the temporary Catalog instance. …
=> [GEOS-11755] AbstractCatalogFacade leaves dangling references to temporary Catalog

src/community/features-templating/features-templating-rest/src/main/java/org/geoserver/featurestemplating/rest/TemplateRestController.java, src/community/features-templating/features-templating-rest/src/test/java/org/geoserver/featurestemplating/rest/TemplateRestControllerTest.java
[![GEOS-11762](https://badgen.net/badge/JIRA/GEOS-11762/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11762) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-11762
This PR purpose is to fix the Features Template bug on REST API making it unable to list the templates by feature type as described on the issue.
The PR will be merged when all the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)), there is a code committer …
=> [GEOS-11762] Templates can not be listed via GeoServer Rest API

src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java, src/main/src/main/java/org/geoserver/catalog/LayerGroupHelper.java, src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java, src/main/src/test/java/org/geoserver/catalog/LayerGroupHelperTest.java
[![GEOS-11769](https://badgen.net/badge/JIRA/GEOS-11769/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11769) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Explicitly pass the correct catalog instance to LayerGroupHelper to ensure proper operation during startup and dynamic catalog modifications. This fixes potential race conditions where the helper might use a default catalog that is not fully initialized or is different from the one being used for current operations.
The changes include:
- Adding a two-arg constructor to LayerGroupHelper that takes an explicit catalog
- …
=> [GEOS-11769] Race conditions in LayerGroupHelper when the default catalog is not fully initialized

src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java, src/main/src/main/java/org/geoserver/catalog/LayerGroupHelper.java, src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java, src/main/src/test/java/org/geoserver/catalog/LayerGroupHelperTest.java
[![GEOS-11769](https://badgen.net/badge/JIRA/GEOS-11769/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11769) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #8414
Explicitly pass the correct catalog instance to LayerGroupHelper to ensure proper operation during startup and dynamic catalog modifications. This fixes potential race conditions where the helper might use a default catalog that is not fully initialized or is different from the one being used for current operations.
The changes include:
- Adding a two-arg constructor to LayerGroupHelper that takes an explicit …
=> [Backport 2.26.x][GEOS-11769] Race conditions in LayerGroupHelper when the default catalog is not fully initialized

doc/en/developer/source/policies/security.rst
Rationale: stable becomes maintenance the moment a new stable series is cut, but admins that updated to the last maintenance version (now dead) should not be put in a situation to jump right away to a different GeoServer series (e.g., a patch is in 2.26.0 and 2.25.x, 2.25.3 becomes maintenance on that release, and those that were on 2.24.5 would be caught off guard as that series does not contain a patch)
=> Coordinated disclosure: some consideration for admins that are up to date with mainteinance

src/main/src/main/java/org/geoserver/config/GeoServerLoader.java, src/main/src/main/java/org/geoserver/config/datadir/CatalogLoader.java, src/main/src/main/java/org/geoserver/config/datadir/ConfigLoader.java, src/main/src/main/java/org/geoserver/config/datadir/DataDirectoryGeoServerLoader.java, src/main/src/main/java/org/geoserver/config/datadir/DataDirectoryWalker.java, src/main/src/main/java/org/geoserver/config/datadir/ExecutorFactory.java, src/main/src/main/java/org/geoserver/config/datadir/MinimalConfigLoaderSupport.java, src/main/src/main/java/org/geoserver/config/datadir/XStreamLoader.java, src/main/src/test/java/org/geoserver/config/datadir/DataDirectoryGeoServerLoaderTest.java, src/main/src/test/java/org/geoserver/config/datadir/DataDirectoryLoaderTestSupport.java, src/main/src/test/java/org/geoserver/config/datadir/DefaultGeoServerLoaderCompatibilityTest.java, src/main/src/test/java/org/geoserver/config/datadir/MinimalConfigLoaderSupportIntegrationTest.java, src/main/src/test/java/org/geoserver/config/datadir/minimalConfigLoaderSupportIntegrationTestContext.xml
[![GEOS-11790](https://badgen.net/badge/JIRA/GEOS-11790/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11790) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Add proper admin authentication propagation and synchronization mechanisms that prevent race conditions during startup while loading the config (not the catalog).
Improve thread safety and consistency when running multiple GeoServer instances sharing the same data directory.
Key improvements include:
1. Authentication is now properly propagated to worker threads in the ForkJoinPool, preventing permission issues when threads …
=> [GEOS-11790] Data Directory Loader Consistency Issues

src/main/src/main/java/org/geoserver/config/datadir/DataDirectoryGeoServerLoader.java
Removes preloading of EntityResolverProvider in
DataDirectoryGeoServerLoader.initializeDependencies() to avoid circular dependency with GeoServer bean.
The EntityResolverProvider isn't needed during catalog loading as XStreamLoader disables features that would require it. ResourcePoolInitializer properly sets the EntityResolverProvider in the ResourcePool after catalog initialization.
This fixes an issue where some developers experienced circular dependency exceptions during startup.
=> Fix EntityResolverProvider circular dependency during catalog loading

doc/en/user/source/security/tutorials/httpheaderproxy/index.rst
In going through the process of using the http header auth for the first time, it was very unclear in the documentation what the header value was supposed to match. After doing a bunch of testing it became clear that it needed to match the username of a user, but that was not included anywhere in the documentation. This update adds a note at the end that makes it very clear what each part of the header ``name: value`` pair is associated with in the system.
=> Added note to clarify that the header value should match a username

doc/en/user/source/community/wps-longitudinal-profile/index.rst, src/community/wps-longitudinal-profile/src/main/java/org/geoserver/wps/longitudinal/AltitudeReaderThread.java, src/community/wps-longitudinal-profile/src/main/java/org/geoserver/wps/longitudinal/CoverageSampler.java, src/community/wps-longitudinal-profile/src/main/java/org/geoserver/wps/longitudinal/DistanceSlopeCalculator.java, src/community/wps-longitudinal-profile/src/main/java/org/geoserver/wps/longitudinal/LongitudinalProfileProcess.java, src/community/wps-longitudinal-profile/src/main/java/org/geoserver/wps/longitudinal/LongitudinalProfileProcessResultsPPIO.java, src/community/wps-longitudinal-profile/src/main/java/org/geoserver/wps/longitudinal/ProfileVertice.java, src/community/wps-longitudinal-profile/src/test/java/org/geoserver/wps/longitudinal/LongitudinalProfileProcessTest.java, src/community/wps-longitudinal-profile/src/test/java/org/geoserver/wps/longitudinal/test/LongitudinalProfileProcessTest.java, src/community/wps-longitudinal-profile/src/test/resources/templateAllParameters.xml, src/community/wps-longitudinal-profile/src/test/resources/templateBasic.xml, src/community/wps-longitudinal-profile/src/test/resources/templateChaining.xml, src/community/wps-longitudinal-profile/src/test/resources/templateNoInputLayer.xml, src/community/wps-longitudinal-profile/src/test/resources/templateTargetProjection.xml
A bunch of clean ups on the longitudinal profile process. Before the fixes it was easy to make it go OOM, was twice as slow, could not be chained with other processes on the raster input, was not checking for cancellation/timeout.
=> Longitudinal profile process improvements (memory, stability, performance)

src/main/src/main/java/org/geoserver/config/GeoServerDataDirectory.java, src/main/src/main/java/org/geoserver/config/datadir/CatalogLoader.java, src/main/src/main/java/org/geoserver/config/datadir/DataDirectoryGeoServerLoader.java, src/main/src/test/java/org/geoserver/config/datadir/MinimalConfigLoaderSupportIntegrationTest.java, src/main/src/test/resources/data_dir/nested_layer_groups/styles/namedstyle.sld, src/main/src/test/resources/data_dir/nested_layer_groups/styles/namedstyle.xml
[![GEOS-11796](https://badgen.net/badge/JIRA/GEOS-11796/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11796) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Fix deadlocks during GeoServer startup when loading data directories with style group layer groups.
The problem is a circular dependency between catalog loading and Spring bean initialization. When style group layer groups are loaded, the following call chain occurs:
- `CatalogImpl.add(LayerGroup)` triggers validation
- Validation attempts to parse SLD with `styles.get(i).getSLD()`
- XML parsing requires an `EntityResolver` …
=> [GEOS-11796] Deadlocks During GeoServer Startup When Loading Style Group Layer Groups

src/kml/src/main/java/org/geoserver/kml/decorator/PlacemarkStyleDecoratorFactory.java, src/wms/src/main/java/org/geoserver/wms/icons/IconProperties.java, src/wms/src/main/java/org/geoserver/wms/legendgraphic/JSONLegendGraphicBuilder.java, src/wms/src/test/java/org/geoserver/wms/icons/IconPropertiesTest.java, src/wms/src/test/java/org/geoserver/wms/legendgraphic/JSONLegendGraphicOutputFormatTest.java, src/wms/src/test/resources/org/geoserver/wms/legendgraphic/arealandmarks.sld
[![GEOS-11274](https://badgen.net/badge/JIRA/GEOS-11274/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11274) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR proposes a couple of improvements in the JSON legend graphic builder for styles that are within a workspace.
[GEOS-11274](https://osgeo-org.atlassian.net/browse/GEOS-11274): In case of a single external graphic, use the workspace style directory to build the URL, since it is also published (similarly to the global style directory). This was causing a NPE ("iconUrl" is null). …
=> [GEOS-11274,GEOS-11751] Generate URL for graphic inside workspace

src/extension/vectortiles/src/main/java/no/ecc/vectortile/VectorTileEncoderNoClip.java, src/extension/vectortiles/src/test/java/org/geoserver/wms/vector/VectorTileEncoderNoClipTest.java
[![GEOS-11795](https://badgen.net/badge/JIRA/GEOS-11795/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11795) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Currently GeoServer Vector Tiles extension incorrectly clips point geometries in the buffer area set by fixed buffer ("Default Rendering Buffer" setting) or style-based buffer estimation.
VectorTileEncoderNoClip is intended to provide a VectorTileEncoder that does not perform any clipping. However, it was still clipping point geometries because the clipCovers method was not overridden (point geometries are clipped by …
=> [GEOS-11795] Incorrect clipping of point geometries in vector tiles

src/web/core/src/main/java/org/geoserver/web/data/layer/CoverageViewEditor.html
[![GEOS-11797](https://badgen.net/badge/JIRA/GEOS-11797/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11797) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport to 2.27.x
=> [Backport-2.27.x][GEOS-11797]: minor fix on coverageViewEditor page (remove style)

src/web/core/src/main/java/org/geoserver/web/data/layer/CoverageViewEditor.html
[![GEOS-11797](https://badgen.net/badge/JIRA/GEOS-11797/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11797) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport to 2.26.x
=> [Backport-2.26.x][GEOS-11797]: minor fix on coverageViewEditor page (remove style)

doc/en/api/1.0.0/wmsstores.yaml, doc/en/api/1.0.0/wmtsstores.yaml
Hi all.
Here's a small PR to fix a typo on a field name: `capabilitiesUrl` should be `capabilitiesURL`.
Applies to WMS and WMST stores.
Thanks for reviewing.
=> [documentation fix] capabilitiesUrl should be capabilitiesURL

src/extension/app-schema/app-schema-core/pom.xml, src/extension/app-schema/app-schema-geopkg-test/pom.xml, src/extension/app-schema/app-schema-indexes-test/pom.xml, src/extension/app-schema/app-schema-mongo-test/pom.xml, src/extension/app-schema/app-schema-oracle-test/pom.xml, src/extension/app-schema/app-schema-postgis-test/pom.xml, src/extension/app-schema/app-schema-solr-test/pom.xml, src/extension/app-schema/app-schema-test/pom.xml, src/extension/app-schema/sample-data-access-test/pom.xml
All `app-schema` extension modules have `org.geoserver:gs-main:jar:tests:<version>:compile` where it should be `org.geoserver:gs-main:jar:tests:<version>:test`
Before:
```shell
mvn dependency:list -o -f src/extension/app-schema/ -Papp-schema,app-schema-online-test | grep gs-main:jar:tests
[INFO]    org.geoserver:gs-main:jar:tests:2.28-SNAPSHOT:compile -- module gs.main (auto)
[INFO]    org.geoserver:gs-main:jar:tests:2.28-SNAPSHOT:compile -- module gs.main (auto)
[INFO]    org.geoserver:gs-main:jar:tests:2.28-SNAPSHOT:compile -- module gs.main (auto)
[INFO]    org.geoserver:gs-main:jar:tests:2.28-SNAPSHOT:compile -- module gs.main (auto)
[INFO]    org.geoserver:gs-main:jar:tests:2.28-SNAPSHOT:compile -- module gs.main (auto)
[INFO]    org.geoserver:gs-main:jar:tests:2.28-SNAPSHOT:compile …
```
=> Fix all app-schema modules including gs-main test jar with compile scope

src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLDocumentBuilder.java, src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java
[![GEOS-11801](https://badgen.net/badge/JIRA/GEOS-11801/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11801) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
When cascading remote layers which have over-generous bounds in geographic coordinates, the location of the MapML preview (especially in MapML:CBMTILE) may seem incorrect due to projection / deprojection of the geographic bbox.  This change uses the calculated centre point of the request (preview) bbox and de-projects that point to use as the preview location, yielding slightly better results.  A narrowly-defined test is …
=> [GEOS-11801] MapML preview link zoom and extent are incorrect

doc/en/docguide/source/contributing.rst
I followed the described process for proposing a change to the documentation, which indicated patch files could be submitted, only [to be told that they are no longer accepted](https://osgeo-org.atlassian.net/browse/GEOS-11808?focusedCommentId=86607).
This change removes the reference to submitting a patch via Jira so that other people don't fall into the same wrong process.
This is according to the information I received from @aaime in the ticket GEOS-11808 (see link above for comment)
I tried not to remove any of the existing text whilst touching it up to make more sense. It now follows the flow: small change > big change > more info (matches the logic at line 6: _The following are listed roughly in order of "least involved" to "most involved"._)
The PR …
=> Quickfix - Docs - Described process for updating documentation doesn't match current working method

doc/en/user/source/configuration/properties/index.rst
Update documentation to add data dir loader related properties in application properties page
=> Documentation Update - Add Data Dir Loader related properties

.github/workflows/assembly.yml, .github/workflows/javadoc.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/postgis_appschema_online.yml, .github/workflows/qa.yml
The number of cores available in the github action runner changes over time (used to be 2 cores, now it's 4 in all runners.). Use T1C to adapt to the current builder hw.
Update: left it to T2 on windows and osx, builds are failing a lot more with -T4 there...
=> Gihub actions: use all cores available in the builder

src/wfs/src/main/java/org/geoserver/wfs/GetFeature.java, src/wfs/src/test/java/org/geoserver/wfs/response/CSVOutputFormatTest.java, src/wfs/src/test/java/org/geoserver/wfs/response/GeoJsonOutputFormatTest.java, src/wfs/src/test/java/org/geoserver/wfs/response/ShapeZipTest.java, src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeaturePagingTest.java
[![GEOS-11832](https://badgen.net/badge/JIRA/GEOS-11832/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11832) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR updates the behavior when count=0 to always query the first feature type so that the list of feature collections passed to the output format always contains at least one feature collection. The GML, JSON and KML formats are able to return an empty response without a feature collection but the CSV and shapefile formats need a feature collection to build the response. This change also allows the totalFeatures and …
=> [GEOS-11832] count=0 service exception for some formats

src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/domain/DomainModelBuilder.java, src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/domain/DomainModelBuilderTest.java, src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/postgis/mockdata/meteo_int8_db.sql
[![GEOS-11885](https://badgen.net/badge/JIRA/GEOS-11885/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11885) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Jira ticket:
https://osgeo-org.atlassian.net/browse/GEOS-11885
=> [GEOS-11885] Add UUID support on SmartDataLoader

doc/en/user/source/installation/linux.rst, doc/en/user/source/installation/win_binary.rst, src/release/bin/startup.bat, src/release/bin/startup.sh
This PR allows to modify the jetty configuration via the environment variable `JETTY_OPTS`. This eases configuration testing. My main motivation here is to be able to more easily use geoserver on NixOS where modifying files in `GEOSERVER_HOME` is usually not possible (if installed as a package).
I did not test the `startup.bat` file as I do not have Windows at hand. I changed that file for consistency. I do not now how batch files behave if an env var is not set (in Linux, I refer to `${JETTY_OPTS}` vs `${JETTY_OPTS:-}`).
I did not find any test involving an invocation of `startup.sh` and thus refrained changing any test. I tested with `JETTY_OPTS=jetty.http.port=1234 path/to/startup.sh`
- Please let me know if this is necessary
The PR will be merged when …
=> Allow to forward options to jetty using the JETTY_OPTS env var

src/web/app/pom.xml
The new ODIC module is not usable directly from an IDE or from jetty:start from web/app because there is no dependency from web/app to it. Added a profile matching the other ones in community, so that enabling "oidc" allows usage of the module from web/app too (basically mimics any other community module setup).
=> Adding new OIDC module to the web/app dependencies

src/extension/importer/web/src/test/java/org/geoserver/importer/web/ImportTaskTableTest.java, src/wms/src/main/java/org/geoserver/wms/WMS.java
[![GEOS-11900](https://badgen.net/badge/JIRA/GEOS-11900/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11900) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
=> [GEOS-11900] Amend failing tests hidden by surefire junit 5 issues

src/main/src/main/java/org/geoserver/config/util/EnumWithDefaultConverter.java, src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
Fixing CITE tests broken by imageN upgrade.
=> Fixing PngEncoderType converter for missing enum due to ImageN migration

.github/workflows/linux_locales.yml, src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/GetPropertyValueTest.java, src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/LocalResolveTest.java, src/wms/src/main/java/org/geoserver/wms/RenderingVariables.java
Fixes the issue, and adds a build to check for it. The build check also has matrix build support for languages, we can add more languages as people care about having the build working in them.
=> Build fails with italian locale (number formatting issue)

doc/en/user/source/services/features/config.rst, doc/en/user/source/services/features/status.rst, src/extension/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/ConformanceClass.java, src/extension/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/FeatureConformance.java, src/extension/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/FeatureService.java, src/extension/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/FeaturesAPIBuilder.java, src/extension/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/v1/features/openapi.yaml, src/extension/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/ApiTest.java, src/extension/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/ConformanceTest.java, src/extension/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/FeatureTest.java, src/extension/ogcapi/web-features/src/main/resources/GeoServerApplication.properties
[![GEOS-11938](https://badgen.net/badge/JIRA/GEOS-11938/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11938) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
See jira ticket for details
=> [GEOS-11938] Add support for property selection in OGC API Features

src/community/security/oidc/oidc-web/src/main/resources/applicationContext.xml, src/web/core/src/main/java/org/geoserver/web/GeoServerBasePage.html, src/web/core/src/main/java/org/geoserver/web/GeoServerBasePage.java, src/web/core/src/main/java/org/geoserver/web/LoginFormInfo.java, src/web/core/src/test/java/org/geoserver/web/GeoServerBasePageTest.java, src/web/security/core/src/test/java/org/geoserver/security/web/auth/AuthenticationPageTest.java
[![GEOS-11935](https://badgen.net/badge/JIRA/GEOS-11935/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11935) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
For external authentication (i.e. OIDC), GS's current behaviour is a form-submit-which-redirects-to-external-location (i.e. the off-site IDP provider).
Unfortunately, this isn't "legal" from the `content-security-policy` and the browser will block the redirect.  This can be solved by adding the IDP's address to the `content-security-policy` (Security -> Content Security Policy), but this is user-hostile.
Instead, this PR …
=> [GEOS-11935] GS Base Page Header: Allow non-form login to be simple links (html anchors)

.github/workflows/assembly.yml, .github/workflows/javadoc.yml, .github/workflows/linux.yml, .github/workflows/linux_locales.yml, .github/workflows/macos.yml, .github/workflows/postgis_appschema_online.yml, .github/workflows/windows.yml
The choice of if always is correct as we want this to run if job succeeds, fails, or is cancled.
This is a GitHub maintenance activity and does not have a Jira.
=> Use if always on worfklow step to clear cache
