- doc/en/user/source/services/wfs/outputformats.rst
- src/wfs/src/main/java/org/geoserver/wfs/response/ShapeZipOutputFormat.java
- src/wfs/src/main/java/org/geoserver/wfs/response/shapezip.ftl
- src/wfs/src/test/java/org/geoserver/wfs/response/ShapeZipTest.java
[![GEOS-10857](https://badgen.net/badge/JIRA/GEOS-10857/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10857)
Backport #6581
> [Backport 2.22.x] [GEOS-10857] Improve shape-zip output format to handle feature types with multiple geometry columns

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/Dialect.java
A formatting issue accidentally got snuck in with the GEOS-10842 fix.
> [GEOS-10842] fix formatting

- doc/en/user/source/security/webadmin/ugr.rst
The section is about adding a new JDBC user/group service, but in the text it mentions 'XML user/group service'. Probably a copy/paste leftover from the previous section where indeed an XML user/group service was added.
> Documentation fix

- src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/JMSXStreamFactory.java
- src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/DocumentFile.java
- src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/CatalogUtils.java
- src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogEventHandler.java
- src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogModifyEventHandler.java
- src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/rest/ClusterController.java
- src/community/jms-cluster/jms-geoserver/src/main/resources/applicationContext.xml
- src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/DocumentFileTest.java
- src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogModifyEventHandlerTest.java
- src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/CatalogDiffVisitor.java
- src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/InfoDiff.java
- src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/IntegrationTest.java
- src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/IntegrationTestsUtils.java
- src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/rest/ClusterControllerTest.java
- src/main/src/main/java/org/geoserver/config/util/SecureXStream.java
- src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
[![GEOS-10517](https://badgen.net/badge/JIRA/GEOS-10517/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10517)
Backport #6583
> [Backport 2.22.x] [GEOS-10517] jms-cluster classes missing from XStream security configuration

- src/main/src/main/java/org/geoserver/util/InternationalStringUtils.java
- src/web/core/src/main/java/org/geoserver/web/GeoServerHomePage.java
- src/web/core/src/test/java/org/geoserver/web/GeoServerHomePageTest.java
[![GEOS-10861](https://badgen.net/badge/JIRA/GEOS-10861/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10861)
Use InternationalStringUtils to combine contact info welcome and internationalWelcome to reflect the session Locale.
> [GEOS-10861] Hello world fix

- src/main/src/main/java/org/geoserver/util/InternationalStringUtils.java
- src/web/core/src/main/java/org/geoserver/web/GeoServerHomePage.java
- src/web/core/src/test/java/org/geoserver/web/GeoServerHomePageTest.java
[![GEOS-10861](https://badgen.net/badge/JIRA/GEOS-10861/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10861)
Backport #6604
> [Backport 2.22.x] [GEOS-10861] Hello world fix

- src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/GeoServerKeycloakFilter.java
[![GEOS-10843](https://badgen.net/badge/JIRA/GEOS-10843/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10843)
> [GEOS-10843] improve keycloak support logging out

- doc/en/user/source/services/wcs/reference.rst
- doc/en/user/source/services/wfs/reference.rst
- doc/en/user/source/services/wms/reference.rst
- doc/en/user/source/services/wps/index.rst
- doc/en/user/source/services/wps/operations.rst
WMS:
Remove incorrect '(optional)' description, fix Json -> JSON, JSonP -> JSONP
Remove Exceptions (not an operation) from table
Move Exceptions to bottom of page, after Operations
Indent each operation to be under Operations (replace -- with ~~)
Fix Xml -> XML
Add hyperlinks from WMS Operations table to each section to aid navigation
WFS:
Fix Json -> JSON, JSonP -> JSONP
Move Exceptions to bottom of page, after Operations
Add hyperlinks from WFS Operations table to each section to aid navigation
WCS:
Fix AcceptsVersion -> AcceptVersions, its
Indent each operation to be under Operations (replace -- with ~~)
Add hyperlinks from WCS Operations table to each section to aid navigation
WPS:
Document operations in a table (for consistency with WMS, WFS, WCS)
Add hyperlinks from WPS Operations …
> Comprehensive review of GeoServer services documentation

- src/community/cov-json/pom.xml
- src/community/ogcapi/pom.xml
- src/community/oseo/pom.xml
- src/community/security/oauth2/oauth2-core/pom.xml
- src/community/wmts-styles/pom.xml
- src/extension/vectortiles/pom.xml
- src/pom.xml
- src/web/app/pom.xml
[![GEOS-10869](https://badgen.net/badge/JIRA/GEOS-10869/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10869)
> [GEOS-10869] Jayway JSON Path libraries not included anymore on GeoServer packages

- src/wfs/src/main/java/org/geoserver/wfs/CapabilitiesTransformer.java
Pre-requisite for https://github.com/geotools/geotools/pull/4186
> Explicitly declare the namespace.

- src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
- src/main/src/main/java/org/geoserver/config/GeoServerLoaderProxy.java
- src/main/src/main/java/org/geoserver/config/impl/GeoServerImpl.java
- src/main/src/test/java/org/geoserver/GeoServerLifecycleShutdownTest.java
- src/main/src/test/java/org/geoserver/GeoServerLifecycleTest.java
- src/main/src/test/java/org/geoserver/GeoServerLifecycleTestSupport.java
- src/main/src/test/java/org/geoserver/GeoServerLifecycleTests.java
- src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
[![GEOS-6313](https://badgen.net/badge/JIRA/GEOS-6313/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-6313)
Backport #6534
**Authored by:** @dieterstueken
> [Backport 2.22.x] GEOS-6313 Lifecycle handlers during shutdown

- src/pom.xml
[![GEOS-10873](https://badgen.net/badge/JIRA/GEOS-10873/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10873)
See also https://github.com/GeoWebCache/geowebcache/pull/1125
> [GEOS-10873] Upgrade XStream to 1.4.20

- src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
- src/main/src/main/java/org/geoserver/config/GeoServerLoaderProxy.java
- src/main/src/main/java/org/geoserver/config/impl/GeoServerImpl.java
- src/main/src/test/java/org/geoserver/GeoServerLifecycleShutdownTest.java
- src/main/src/test/java/org/geoserver/GeoServerLifecycleTest.java
- src/main/src/test/java/org/geoserver/GeoServerLifecycleTestSupport.java
- src/main/src/test/java/org/geoserver/GeoServerLifecycleTests.java
- src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
[![GEOS-6313](https://badgen.net/badge/JIRA/GEOS-6313/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-6313)
Backport #6534
**Authored by:** @dieterstueken
> [Backport 2.21.x] GEOS-6313 Lifecycle handlers during shutdown

- src/pom.xml
[![GEOS-10873](https://badgen.net/badge/JIRA/GEOS-10873/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10873)
Backport #6633
> [Backport 2.22.x] [GEOS-10873] Upgrade XStream to 1.4.20

- src/pom.xml
[![GEOS-10873](https://badgen.net/badge/JIRA/GEOS-10873/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10873)
Backport #6633
> [Backport 2.21.x] [GEOS-10873] Upgrade XStream to 1.4.20

- src/main/src/test/java/org/geoserver/config/GeoServerDataDirectoryTest.java
2.22.x backport for https://github.com/geoserver/geoserver/pull/6399
> [Backport 2.22.x] Fix GeoServerDataDirectoryTest clean up after running tests

- src/main/src/test/java/org/geoserver/config/GeoServerDataDirectoryTest.java
> [Backport 2.21.x] [Backport 2.22.x] Fix GeoServerDataDirectoryTest clean up after running tests

- src/extension/pom.xml
[![GEOS-10878](https://badgen.net/badge/JIRA/GEOS-10878/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10878)
As indicated in the ticket, these two modules are not getting deployed. Will deploy by hand for the last few releases.
I don't know the reason for the two separate profiles, but between being careful, and not having time to hunt down all places that are using allExtensions, I'll just re-align the two module lists for now.
> [GEOS-10878] wps-multidimensional and wps-jdbc are not being deployed on maven repo

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIRequestInfo.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/FeatureService.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/FeaturesExceptionHandler.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/ExceptionHandlingTest.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACExceptionHandler.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACService.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/CollectionsTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/ExceptionHandlingTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/QueryablesTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/SortablesTest.java
[![GEOS-10876](https://badgen.net/badge/JIRA/GEOS-10876/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10876)
> [GEOS-10876] STAC and Features exception handlers can hide the actual cause of an exception

- src/pom.xml
[![GEOS-10863](https://badgen.net/badge/JIRA/GEOS-10863/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10863)
Blocked by https://github.com/geotools/geotools/pull/4202
> [GEOS-10863] Update Oracle JDBC driver to 19.18.0.0

- src/community/ogcapi/ogcapi-styles/src/main/resources/org/geoserver/ogcapi/v1/styles/openapi.yaml
[![GEOS-10888](https://badgen.net/badge/JIRA/GEOS-10888/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10888)
Found by accident while testing the APIs, easy fix (few remote references).
The Tiles API is also pointing to a lot of remote references, but those are still available.
> [GEOS-10888] OGC API styles OpenAPI document points to dangling remote resources

- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/ogcapi/v1/dggs/DGGSAPIBuilder.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/OpenAPIBuilder.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/v1/coverages/CoveragesAPIBuilder.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/v1/coverages/CoveragesService.java
- src/community/ogcapi/ogcapi-coverages/src/main/resources/applicationContext.xml
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/v1/coverages/ApiTest.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/v1/coverages/CoverageTest.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/v1/coverages/LandingPageTest.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/FeatureService.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/FeaturesAPIBuilder.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/ApiTest.java
- src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/ogcapi/v1/images/ImagesAPIBuilder.java
- src/community/ogcapi/ogcapi-styles/src/main/java/org/geoserver/ogcapi/v1/styles/StylesAPIBuilder.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/v1/tiles/TilesAPIBuilder.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/v1/tiles/TilesService.java
- src/community/ogcapi/ogcapi-tiles/src/main/resources/applicationContext.xml
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/v1/tiles/ApiTest.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/v1/tiles/CollectionsTest.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/v1/tiles/LandingPageTest.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACAPIBuilder.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACService.java
- src/community/oseo/oseo-stac/src/main/resources/applicationContext.xml
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/ApiTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/CollectionsTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/LandingPageTest.java
[![GEOS-10889](https://badgen.net/badge/JIRA/GEOS-10889/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10889)
As the title says.
> [GEOS-10889] OGC API info section should report the spec version, not the server version

- src/release/installer/win/build/geoserver_winsetup.nsi
Fix wrong path for the license file in the Windows installer script.
> [GEOS-10890] Wrong path for the license file in the Windows installer script

- src/release/installer/win/build/geoserver_winsetup.nsi
Files changed from md to html
Follow up to #6669 nice!
> [[GEOS-10890] Windows installer include html docs and licenses

- src/release/installer/win/build/geoserver_winsetup.nsi
> [Backport 2.22.x] [GEOS-10890] Windows installer include html docs and licenses

- src/release/installer/win/build/geoserver_winsetup.nsi
> [Backport 2.23.x] [GEOS-10890] Windows installer include html docs and licenses

- src/extension/control-flow/src/test/java/org/geoserver/flow/controller/AbstractFlowControllerTest.java
- src/extension/control-flow/src/test/java/org/geoserver/flow/controller/PriorityFlowControllerTest.java
- src/pom.xml
[![GEOS-10894](https://badgen.net/badge/JIRA/GEOS-10894/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10894)
Backport #6679
> [Backport 2.23.x] [GEOS-10894] Random control-flow errors on Mac builds

- src/extension/control-flow/src/test/java/org/geoserver/flow/controller/AbstractFlowControllerTest.java
- src/extension/control-flow/src/test/java/org/geoserver/flow/controller/PriorityFlowControllerTest.java
[![GEOS-10894](https://badgen.net/badge/JIRA/GEOS-10894/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10894)
Backport #6679
> [Backport 2.22.x] [GEOS-10894] Random control-flow errors on Mac builds

- src/web/security/core/src/main/resources/GeoServerApplication_zh.properties
Backport #6685
**Authored by:** @guxin0123
> [Backport 2.22.x] Fixed several wrong Chinese translation encodings

- src/web/security/core/src/main/resources/GeoServerApplication_zh.properties
Backport #6685
**Authored by:** @guxin0123
> [Backport 2.23.x] Fixed several wrong Chinese translation encodings

- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/request/TemplatePathVisitor.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/response/TemplateComplexTestSupport.java
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/NamedPlacesDifferentAttributesGeoJSON.json
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/GeoJSONGetSimpleFeaturesResponseWFSTest.java
[![GEOS-10896](https://badgen.net/badge/JIRA/GEOS-10896/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10896)
https://osgeo-org.atlassian.net/browse/GEOS-10896
> [GEOS-10896] Missing NULL check in the template backwards mapping

- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/request/TemplatePathVisitor.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/response/TemplateComplexTestSupport.java
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/NamedPlacesDifferentAttributesGeoJSON.json
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/GeoJSONGetSimpleFeaturesResponseWFSTest.java
[![GEOS-10896](https://badgen.net/badge/JIRA/GEOS-10896/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10896)
Backport #6689
> [Backport 2.23.x] [GEOS-10896] Missing NULL check in the template backwards mapping

- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/request/TemplatePathVisitor.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/response/TemplateComplexTestSupport.java
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/NamedPlacesDifferentAttributesGeoJSON.json
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/GeoJSONGetSimpleFeaturesResponseWFSTest.java
[![GEOS-10896](https://badgen.net/badge/JIRA/GEOS-10896/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10896)
Backport #6689
> [Backport 2.21.x] [GEOS-10896] Missing NULL check in the template backwards mapping

- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/request/TemplatePathVisitor.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/response/TemplateComplexTestSupport.java
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/NamedPlacesDifferentAttributesGeoJSON.json
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/GeoJSONGetSimpleFeaturesResponseWFSTest.java
[![GEOS-10896](https://badgen.net/badge/JIRA/GEOS-10896/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10896)
Backport #6689
> [Backport 2.22.x] [GEOS-10896] Missing NULL check in the template backwards mapping

- src/main/src/main/java/org/geoserver/catalog/impl/FeatureTypeValidator.java
- src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/FeatureTypeControllerTest.java
[![GEOS-10593](https://badgen.net/badge/JIRA/GEOS-10593/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10593)
> [GEOS-10593] Regression: Creating SQL View via REST API and explicit attribute list is no-longer possible

- src/main/src/main/java/org/geoserver/catalog/impl/FeatureTypeValidator.java
- src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/FeatureTypeControllerTest.java
[![GEOS-10593](https://badgen.net/badge/JIRA/GEOS-10593/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10593)
Backport #6702
> [Backport 2.23.x] [GEOS-10593] Regression: Creating SQL View via REST API and explicit attribute list is no-longer possible

- src/pom.xml
[![GEOS-10907](https://badgen.net/badge/JIRA/GEOS-10907/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10907)
CVE-2023-20861 was resolved in Spring core.
see also https://github.com/geoserver/geoserver/security/dependabot/159
> [GEOS-10907] Update spring.version from 5.3.25 to 5.3.26 and spring.security.version from 5.7.6 to 5.7.7

- src/pom.xml
[![GEOS-10908](https://badgen.net/badge/JIRA/GEOS-10908/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10908)
Update to the latest patch version in this minor.
Note this is a 22.x (and possibly lower) -only fix; main and 2.23.x are using a newer minor version of spring (5.3.x)
see also:
- #6718
- https://osgeo-org.atlassian.net/browse/GEOS-10907
> [GEOS-10908] Update spring version from 5.2.22 to 5.2.23

- doc/en/user/source/community/cog/cog.rst
Backport #6723
**Authored by:** @goxzy
> [Backport 2.21.x] Update cog.rst

- doc/en/user/source/community/cog/cog.rst
Backport #6723
**Authored by:** @goxzy
> [Backport 2.23.x] Update cog.rst

- doc/en/user/source/community/cog/cog.rst
Backport #6723
**Authored by:** @goxzy
> [Backport 2.22.x] Update cog.rst

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/LandingPageSlashFilter.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/LocalWorkspaceURLPathHelper.java
- src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/HelloServiceTrailingSlashOffTest.java
[![GEOS-10895](https://badgen.net/badge/JIRA/GEOS-10895/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10895)
Follow up to https://github.com/geoserver/geoserver/pull/6680 for workspace specific services
> [GEOS-10895] Landing page exception, workspace and layer specific service version

- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/CollectionDocument.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/CollectionTest.java
[![GEOS-10909](https://badgen.net/badge/JIRA/GEOS-10909/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10909)
See ticket.
> [GEOS-10909] Don't link from OGC API Features to WFS 2.0 DescribeFeatureType output, if WFS is disabled

- doc/en/api/1.0.0/styles.yaml
- doc/en/user/source/rest/styles.rst
[![GEOS-8242](https://badgen.net/badge/JIRA/GEOS-8242/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-8242)
Update CSS extension docs with mime types for POST and PUT styles and added CSS POST example
resolves issue #2623
> [GEOS-8242] CSS extensions mime types for POST and PUT styles, with example

- .github/workflows/docs.yml
- doc/zhCN/pom.xml
[![GEOS-10871](https://badgen.net/badge/JIRA/GEOS-10871/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10871)
Was using an earlier version of antrum that did not execute ``target`` (only ``task`` which was deprecated).
> [GEOS-10871] Upgrade zhCN documentation built to antrum version 3.1.0

- doc/en/api/1.0.0/styles.yaml
- doc/en/user/source/rest/styles.rst
[![GEOS-8242](https://badgen.net/badge/JIRA/GEOS-8242/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-8242)
Backport #6710
> [Backport 2.22.x] [GEOS-8242] CSS extensions mime types for POST and PUT styles, with example

- doc/en/api/1.0.0/styles.yaml
- doc/en/user/source/rest/styles.rst
[![GEOS-8242](https://badgen.net/badge/JIRA/GEOS-8242/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-8242)
Backport #6710
> [Backport 2.23.x] [GEOS-8242] CSS extensions mime types for POST and PUT styles, with example

- .github/workflows/docs.yml
- doc/zhCN/pom.xml
[![GEOS-10871](https://badgen.net/badge/JIRA/GEOS-10871/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10871)
Backport #6729
> [Backport 2.22.x] [GEOS-10871] Upgrade zhCN documentation built to antrum version 3.1.0

- .github/workflows/docs.yml
- doc/zhCN/pom.xml
[![GEOS-10871](https://badgen.net/badge/JIRA/GEOS-10871/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10871)
Backport #6729
> [Backport 2.23.x] [GEOS-10871] Upgrade zhCN documentation built to antrum version 3.1.0

- src/community/jms-cluster/jms-commons/src/main/java/org/geoserver/cluster/configuration/JMSConfiguration.java
- src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/JMSXStreamFactory.java
- src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/IntegrationTest.java
[![GEOS-10912](https://badgen.net/badge/JIRA/GEOS-10912/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10912)
Backport #6735
> [Backport 2.23.x] [GEOS-10912] jms-cluster fails to clone grid coverage layer on other nodes

- src/community/jms-cluster/jms-commons/src/main/java/org/geoserver/cluster/configuration/JMSConfiguration.java
- src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/JMSXStreamFactory.java
- src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/IntegrationTest.java
[![GEOS-10912](https://badgen.net/badge/JIRA/GEOS-10912/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10912)
Backport #6735
> [Backport 2.22.x] [GEOS-10912] jms-cluster fails to clone grid coverage layer on other nodes

- src/community/jms-cluster/jms-commons/src/main/java/org/geoserver/cluster/configuration/JMSConfiguration.java
- src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/JMSXStreamFactory.java
- src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/IntegrationTest.java
[![GEOS-10912](https://badgen.net/badge/JIRA/GEOS-10912/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10912)
Backport #6735
> [Backport 2.21.x] [GEOS-10912] jms-cluster fails to clone grid coverage layer on other nodes

- doc/en/user/source/styling/sld/extensions/pointsymbols.rst
> [Backport 2.23.x] Document what to MarkFactory to select in WMS settings for each styling extension

- src/pom.xml
> [Backport 2.21.x] Bump jackson-databind from 2.13.4.1 to 2.13.4.2 in /src

- src/pom.xml
> [Backport 2.23.x] Bump jackson-databind from 2.13.4.1 to 2.13.4.2 in /src

- src/pom.xml
> [Backport 2.22.x] Bump jackson-databind from 2.13.4.1 to 2.13.4.2 in /src

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/GeoTiffPPIO.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ppio/GeotiffPPIOTest.java
[![GEOS-10923](https://badgen.net/badge/JIRA/GEOS-10923/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10923)
> [GEOS-10923]: Supporting default writing params on GeoTIFF PPIO

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/GeoTiffPPIO.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ppio/GeotiffPPIOTest.java
[![GEOS-10923](https://badgen.net/badge/JIRA/GEOS-10923/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10923)
> [backport-2.22.x][GEOS-10923]: Supporting default writing params on GeoTIFF PPIO

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/GeoTiffPPIO.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ppio/GeotiffPPIOTest.java
[![GEOS-10923](https://badgen.net/badge/JIRA/GEOS-10923/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10923)
> [Backport-2.23.x][GEOS-10923]: Supporting default writing params on GeoTIFF PPIO

- src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/XMLTemplateWriter.java
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/HTMLMappedFeature.xhtml
- src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/wfs/TemplateGetFeatureResponseHelper.java
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/ComplexGetFeatureInfoTest.java
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/HTMLGetComplexFeatureResponseTest.java
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/HTMLGetSimpleFeaturesResponseWFSTest.java
- src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
> [Backport 2.23.x] Features templating html double escaping fix

- src/extension/csw/web-csw/src/main/java/applicationContext.xml
- src/extension/csw/web-csw/src/main/java/org/geoserver/csw/web/CSWServiceDescriptionProvider.java
- src/extension/csw/web-csw/src/test/java/org/geoserver/csw/web/CSWServiceDescriptionProviderTest.java
[![GEOS-10934](https://badgen.net/badge/JIRA/GEOS-10934/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10934)
Backport #6769
> [Backport 2.23.x] [GEOS-10934] CSW does not show title/abstract on welcome page

- src/extension/csw/web-csw/src/main/java/applicationContext.xml
- src/extension/csw/web-csw/src/main/java/org/geoserver/csw/web/CSWServiceDescriptionProvider.java
- src/extension/csw/web-csw/src/test/java/org/geoserver/csw/web/CSWServiceDescriptionProviderTest.java
[![GEOS-10934](https://badgen.net/badge/JIRA/GEOS-10934/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10934)
Backport #6769
> [Backport 2.22.x] [GEOS-10934] CSW does not show title/abstract on welcome page

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/QueryablesBuilder.java
- src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/HelloServiceTrailingSlashOffTest.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/FeatureService.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/JSONFGFeaturesResponse.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/JSONFGSchemaBuilder.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/RFCGeoJSONFeaturesResponse.java
- src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/v1/features/schema/collection.json
- src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/v1/features/schema/coordrefsys.json
- src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/v1/features/schema/feature.json
- src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/v1/features/schema/featuretype.json
- src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/v1/features/schema/geometry-objects.json
- src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/v1/features/schema/geometry.json
- src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/v1/features/schema/link.json
- src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/v1/features/schema/place.json
- src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/v1/features/schema/time.json
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/FeatureTest.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/JSONFGSchemaTest.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/LandingPageTest.java
- src/community/ogcapi/ogcapi-tiled-features/src/test/java/org/geoserver/ogcapi/v1/features/tiled/LandingPageTest.java
- src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
[![GEOS-10928](https://badgen.net/badge/JIRA/GEOS-10928/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10928)
See ticket
> [GEOS-10928] Draft JSON-FG Implementation for OGC API - Features

- src/release/src/markdown/RUNNING.txt
[![GEOS-10638](https://badgen.net/badge/JIRA/GEOS-10638/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10638)
Backport #6755
> [Backport 2.23.x] [GEOS-10638] Java 11 minimum for running GeoServer

- doc/en/api/1.0.0/featuretypes.yaml
> added "advertised: true" in featuretype defination

- src/community/features-templating/features-templating-ows/pom.xml
- src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/TemplateCallback.java
- src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/wfs/HTMLTemplateResponse.java
- src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/wfs/JSONLDGetFeatureResponse.java
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/wfs/GetCapabilitiesTest.java
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/wfs/WfsGetCapabilitiesTest.java
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/wms/WmsGetCapabilitiesTest.java
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/wms/WmsGetFeatureInfoTest.java
[![GEOS-10922](https://badgen.net/badge/JIRA/GEOS-10922/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10922)
Backport #6757
> [Backport 2.22.x] [GEOS-10922] Features templating exception on text/plain format

- src/wfs/src/main/java/org/geoserver/wfs/xml/FeatureTypeSchemaBuilder.java
- src/wfs/src/test/java/org/geoserver/wfs/v2_0/DescribeFeatureTypeTest.java
- src/wfs/src/test/java/org/geoserver/wfs/xml/FeatureTypeInfoSchemaBuilderTest.java
[![GEOS-10950](https://badgen.net/badge/JIRA/GEOS-10950/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10950)
See ticket
> [GEOS-10950] Performance regression in DescribeFeatureType across allfeature types

- src/wfs/src/main/java/org/geoserver/wfs/xml/FeatureTypeSchemaBuilder.java
- src/wfs/src/test/java/org/geoserver/wfs/v2_0/DescribeFeatureTypeTest.java
- src/wfs/src/test/java/org/geoserver/wfs/xml/FeatureTypeInfoSchemaBuilderTest.java
[![GEOS-10950](https://badgen.net/badge/JIRA/GEOS-10950/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10950)
Backport #6791
> [Backport 2.23.x] [GEOS-10950] Performance regression in DescribeFeatureType across allfeature types

- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteTest.java
> [Backport 2.21.x] Timing based test failures on Windows, allowing some tolerance between moving on the process, and getting back a progress report

- src/community/backup-restore/core/pom.xml
- src/pom.xml
Move spring-integration version to root pom and upgrade from `5.0.0` to `5.5.17`, matching the spring-core dependency version of `5.3.26` with the one currently used by GeoServer as per `${spring.version}`.
> Upgrade spring-integration-core:5.0.0 -> 5.5.17

- src/community/backup-restore/core/pom.xml
- src/pom.xml
> [Backport 2.23.x] Upgrade spring-integration-core:5.0.0 -> 5.5.17

- src/wfs/src/main/java/org/geoserver/wfs/xml/FeatureTypeSchemaBuilder.java
- src/wfs/src/test/java/org/geoserver/wfs/v2_0/DescribeFeatureTypeTest.java
- src/wfs/src/test/java/org/geoserver/wfs/xml/FeatureTypeInfoSchemaBuilderTest.java
[![GEOS-10950](https://badgen.net/badge/JIRA/GEOS-10950/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10950)
Backport https://github.com/geoserver/geoserver/pull/6791
> [Backport 2.21.x] [GEOS-10950] Performance regression in DescribeFeatureType across allfeature types

- doc/en/user/source/installation/docker.rst
> Small fix to docker docs:  correction for --mount and --env examples

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/Link.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/v1/tiles/TileMatrixSets.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/v1/tiles/TiledCollectionDocument.java
- src/community/ogcapi/ogcapi-tiles/src/main/resources/org/geoserver/ogcapi/v1/tiles/openapi.yaml
> Small fixes to the OGC API - Tiles implementation, based on the draft CITE tests for it

- src/extension/monitor/core/src/main/java/org/geoserver/monitor/GeoIPPostProcessor.java
- src/main/src/main/java/org/geoserver/security/password/RandomPasswordProvider.java
- src/pom.xml
[![GEOS-10958](https://badgen.net/badge/JIRA/GEOS-10958/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10958)
Follow up to GT/GWC upgrades
> [GEOS-10958] Upgrade Spotbugs to 4.7.3

- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACTemplates.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/CollectionsTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/STACTestSupport.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/TemplatePropertyMapperTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/collections.ftl
[![GEOS-10955](https://badgen.net/badge/JIRA/GEOS-10955/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10955)
Backport #6809
> [Backport 2.23.x] [GEOS-10955] STAC templates are initialised in the wrong location

- doc/en/user/source/production/java.rst
> Clarify Java version requirements

- src/main/src/main/java/org/geoserver/ows/kvp/CQLFilterKvpParser.java
- src/main/src/test/java/org/geoserver/ows/kvp/CQLFilterKvpParserTest.java
- src/wfs/src/main/java/org/geoserver/wfs/kvp/BaseFeatureKvpRequestReader.java
- src/wfs/src/test/java/org/geoserver/wfs/GetFeatureTest.java
- src/wms/src/test/java/org/geoserver/wms/map/GetMapIntegrationTest.java
[![GEOS-10969](https://badgen.net/badge/JIRA/GEOS-10969/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10969)
see the ticket
> [GEOS-10969] Empty CQL_FILTER-parameter should be ignored

- src/pom.xml
[![GEOS-10989](https://badgen.net/badge/JIRA/GEOS-10989/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10989)
this is in fact the backport of #6852 to 2.22.x
> [GEOS-10989] [2.22.x] Update spring.version from 5.2.23.RELEASE to 5.2.24.RELEASE

- src/pom.xml
[![GEOS-10988](https://badgen.net/badge/JIRA/GEOS-10988/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10988)
> [GEOS-10988] Update spring.version from 5.3.26 to 5.3.27 and spring-integration.version from 5.5.17 to 5.5.18

- src/extension/csw/core/pom.xml
- src/extension/csw/csw-iso/pom.xml
- src/ows/pom.xml
- src/pom.xml
- src/wms/pom.xml
[![GEOS-10987](https://badgen.net/badge/JIRA/GEOS-10987/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10987)
Backport #6849
> [Backport 2.23.x] [GEOS-10987] Bump xalan:xalan and xalan:serializer from 2.7.2 to 2.7.3

- src/extension/csw/core/pom.xml
- src/extension/csw/csw-iso/pom.xml
- src/ows/pom.xml
- src/pom.xml
- src/wms/pom.xml
[![GEOS-10987](https://badgen.net/badge/JIRA/GEOS-10987/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10987)
Backport #6849
> [Backport 2.22.x] [GEOS-10987] Bump xalan:xalan and xalan:serializer from 2.7.2 to 2.7.3

- src/community/taskmanager/core/pom.xml
- src/community/taskmanager/pom.xml
[![GEOS-10992](https://badgen.net/badge/JIRA/GEOS-10992/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10992)
> [GEOS-10992] Make GWC UI for disk quota expose HSQLDB, remove H2, automatically update existing installations - fix community build

- src/main/src/main/java/org/geoserver/security/impl/LayerGroupContainmentCache.java
[![GEOS-10998](https://badgen.net/badge/JIRA/GEOS-10998/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10998)
Backport #6871
> [Backport 2.23.x] [GEOS-10998] LayerGroupContainmentCache is being rebuilt on each ApplicationEvent

- src/main/src/main/java/org/geoserver/security/impl/LayerGroupContainmentCache.java
[![GEOS-10998](https://badgen.net/badge/JIRA/GEOS-10998/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10998)
Backport #6871
> [Backport 2.22.x] [GEOS-10998] LayerGroupContainmentCache is being rebuilt on each ApplicationEvent

- src/community/release/ext-backup-restore.xml
- src/community/release/ext-cog.xml
- src/community/release/ext-importer-fgdb.xml
- src/community/release/ext-jdbcconfig.xml
- src/community/release/ext-jdbcstore.xml
- src/community/release/ext-monitor-hibernate.xml
- src/community/release/ext-netcdf-ghrsst.xml
- src/community/release/ext-taskmanager-core.xml
- src/community/release/ext-taskmanager-s3.xml
- src/community/release/ext-wps-remote.xml
- src/release/ext-geofence-server.xml
- src/release/ext-geofence-wps.xml
- src/release/ext-grib.xml
- src/release/ext-importer.xml
- src/release/ext-netcdf-out.xml
- src/release/ext-netcdf.xml
- src/release/ext-sldservice.xml
- src/release/ext-wps-download.xml
- src/release/ext-wps-jdbc.xml
- src/release/ext-wps.xml
[![GEOS-11005](https://badgen.net/badge/JIRA/GEOS-11005/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11005)
> [GEOS-11005] Make sure H2 dependencies are included in the packages of optional modules that still need it

- doc/en/developer/source/quickstart/checkout.txt
- doc/en/developer/source/quickstart/eclipse_m2.rst
Update documentation with link to M2Eclipse website
> Update documentation with link to M2Eclipse website

- src/extension/csw/core/src/main/java/org/geoserver/csw/store/internal/CatalogStoreFeatureCollection.java
- src/extension/csw/core/src/test/java/org/geoserver/csw/store/internal/GetRecordsTest.java
[![GEOS-10993](https://badgen.net/badge/JIRA/GEOS-10993/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10993)
This PR adds filters for CSW to properly filter out disabled resources from the GetRecords response.  The structure of the CSW filter was updated to be nearly identical to other similar catalog queries, such as for the home page selection.
> [GEOS-10993] Disabled resources can cause incorrect CSW GetRecords response

- src/extension/csw/core/src/main/java/org/geoserver/csw/store/internal/CatalogStoreFeatureCollection.java
- src/extension/csw/core/src/test/java/org/geoserver/csw/store/internal/GetRecordsTest.java
[![GEOS-10993](https://badgen.net/badge/JIRA/GEOS-10993/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10993)
Backport #6872
> [Backport 2.23.x] [GEOS-10993] Disabled resources can cause incorrect CSW GetRecords response

- src/extension/csw/core/src/main/java/org/geoserver/csw/store/internal/CatalogStoreFeatureCollection.java
- src/extension/csw/core/src/test/java/org/geoserver/csw/store/internal/GetRecordsTest.java
[![GEOS-10993](https://badgen.net/badge/JIRA/GEOS-10993/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10993)
Backport #6872
> [Backport 2.22.x] [GEOS-10993] Disabled resources can cause incorrect CSW GetRecords response

- src/pom.xml
[![GEOS-11011](https://badgen.net/badge/JIRA/GEOS-11011/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11011)
Dependency upgrade with bug fixes.  Backport is optional for this PR.
> [GEOS-11011] Upgrade postgresql from 42.4.3 to 42.6.0

- src/pom.xml
[![GEOS-11011](https://badgen.net/badge/JIRA/GEOS-11011/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11011)
Backport #6887
> [Backport 2.22.x] [GEOS-11011] Upgrade postgresql from 42.4.3 to 42.6.0

- src/pom.xml
[![GEOS-11011](https://badgen.net/badge/JIRA/GEOS-11011/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11011)
Backport #6887
> [Backport 2.23.x] [GEOS-11011] Upgrade postgresql from 42.4.3 to 42.6.0

- src/pom.xml
[![GEOS-11010](https://badgen.net/badge/JIRA/GEOS-11010/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11010)
Backport #6886
> [Backport 2.22.x] [GEOS-11010] Upgrade guava from 30.1 to 32.0.0

- src/pom.xml
[![GEOS-11010](https://badgen.net/badge/JIRA/GEOS-11010/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11010)
Backport #6886
> [Backport 2.23.x] [GEOS-11010] Upgrade guava from 30.1 to 32.0.0

- src/pom.xml
[![GEOS-11012](https://badgen.net/badge/JIRA/GEOS-11012/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11012)
Dependency upgrade with bug fixes. Backport is optional for this PR.
> [GEOS-11012] Upgrade commons-collections4 from 4.2 to 4.4

- src/pom.xml
[![GEOS-11012](https://badgen.net/badge/JIRA/GEOS-11012/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11012)
Backport #6888
> [Backport 2.22.x] [GEOS-11012] Upgrade commons-collections4 from 4.2 to 4.4

- src/pom.xml
[![GEOS-11012](https://badgen.net/badge/JIRA/GEOS-11012/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11012)
Backport #6888
> [Backport 2.23.x] [GEOS-11012] Upgrade commons-collections4 from 4.2 to 4.4

- src/pom.xml
[![GEOS-10936](https://badgen.net/badge/JIRA/GEOS-10936/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10936)
> [GEOS-10936] YSLD and OGC API modules are incompatible

- doc/en/developer/source/release-guide/index.rst
> Spelling and grammar fixes

- src/pom.xml
[![GEOS-11018](https://badgen.net/badge/JIRA/GEOS-11018/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11018)
Dependency upgrade with bug fixes and new features. Backport is optional for this PR.
> [GEOS-11018] Upgrade commons-lang3 from 3.8.1 to 3.12.0

- src/community/ogcapi/ogcapi-tiles/pom.xml
- src/extension/csw/web-csw/pom.xml
- src/web/core/pom.xml
[![GEOS-11020](https://badgen.net/badge/JIRA/GEOS-11020/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11020)
This PR adds the test scope to the mockito-core dependency in pom.xml files that were missing the scope.
> [GEOS-11020] Add test scope to mockito-core dependency

- src/pom.xml
[![GEOS-11018](https://badgen.net/badge/JIRA/GEOS-11018/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11018)
Backport #6903
> [Backport 2.23.x] [GEOS-11018] Upgrade commons-lang3 from 3.8.1 to 3.12.0

- src/pom.xml
[![GEOS-11018](https://badgen.net/badge/JIRA/GEOS-11018/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11018)
Backport #6903
> [Backport 2.22.x] [GEOS-11018] Upgrade commons-lang3 from 3.8.1 to 3.12.0

- doc/en/user/source/installation/upgrade.rst
[![GEOS-10992](https://badgen.net/badge/JIRA/GEOS-10992/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10992)
> [GEOS-10992] Make GWC UI for disk quota expose HSQLDB, remove H2, automatically update existing installations - doc update

- src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java
- src/security/security-tests/src/test/java/org/geoserver/security/impl/AbstractAuthorizationTest.java
- src/security/security-tests/src/test/java/org/geoserver/security/impl/DefaultDataAccessManagerTreeTest.java
- src/security/security-tests/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java
- src/security/security-tests/src/test/java/org/geoserver/security/impl/complex.properties
[![GEOS-10997](https://badgen.net/badge/JIRA/GEOS-10997/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10997)
Backport #6877
> [Backport 2.23.x] [GEOS-10997] Data Security Layer groups

- src/community/ogcapi/ogcapi-tiles/pom.xml
- src/extension/csw/web-csw/pom.xml
- src/web/core/pom.xml
[![GEOS-11020](https://badgen.net/badge/JIRA/GEOS-11020/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11020)
> [2.23.x][GEOS-11020] Add test scope to mockito-core dependency

- src/extension/csw/web-csw/pom.xml
- src/web/core/pom.xml
[![GEOS-11020](https://badgen.net/badge/JIRA/GEOS-11020/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11020)
> [2.22.x][GEOS-11020] Add test scope to mockito-core dependency

- src/main/src/test/java/org/geoserver/data/test/TimeElevation.properties
- src/wms/src/main/java/applicationContext.xml
- src/wms/src/main/java/org/geoserver/wms/GetFeatureInfo.java
- src/wms/src/main/java/org/geoserver/wms/GetMap.java
- src/wms/src/main/java/org/geoserver/wms/WMS.java
- src/wms/src/test/java/org/geoserver/wms/WMSTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetFeatureInfoIntegrationTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetMapIntegrationTest.java
[![GEOS-10994](https://badgen.net/badge/JIRA/GEOS-10994/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10994)
extended to getfeatureinfo
unit tests
getmap integration tests
getfeatureinfo integration tests
clean
cleanup
> [GEOS-10994] OOM due to too many dimensions when range requested

- src/main/src/test/java/org/geoserver/data/test/TimeElevation.properties
- src/wms/src/main/java/applicationContext.xml
- src/wms/src/main/java/org/geoserver/wms/GetFeatureInfo.java
- src/wms/src/main/java/org/geoserver/wms/GetMap.java
- src/wms/src/main/java/org/geoserver/wms/WMS.java
- src/wms/src/test/java/org/geoserver/wms/WMSTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetFeatureInfoIntegrationTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetMapIntegrationTest.java
[![GEOS-10994](https://badgen.net/badge/JIRA/GEOS-10994/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10994)
Backport #6869
> [Backport 2.23.x] [GEOS-10994] OOM due to too many dimensions when range requested

- src/community/taskmanager/core/pom.xml
- src/community/taskmanager/metadata/pom.xml
- src/community/taskmanager/s3/pom.xml
- src/web/app/pom.xml
[![GEOS-10968](https://badgen.net/badge/JIRA/GEOS-10968/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10968)
Backport #6917
> [Backport 2.23.x] [GEOS-10968] task manager: fix dependendies for java 11

- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/tasks/CopyTableTaskTypeImpl.java
[![GEOS-10931](https://badgen.net/badge/JIRA/GEOS-10931/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10931)
Backport #6921
> [Backport 2.23.x] [GEOS-10931] Taskmanager: copytabletask: drop table in transaction

- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/data/LatestBatchRun.java
[![GEOS-10931](https://badgen.net/badge/JIRA/GEOS-10931/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10931)
Backport #6927
> [Backport 2.23.x] [GEOS-10931] taskmanager: fix missing serializable

- src/extension/geopkg-output/src/main/java/org/geoserver/geopkg/wfs/GeoPackageGetFeatureOutputFormat.java
- src/extension/geopkg-output/src/test/java/org/geoserver/geopkg/wfs/GeoPackageGetFeatureOutputFormatTest.java
[![GEOS-11015](https://badgen.net/badge/JIRA/GEOS-11015/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11015)
The contract for java temporary files is for eventual cleanup on JVM exit. In the interests of long running stability these can be cleaned up on write operation exit.
> [GEOS-11015] Clean up geopackage tmp files in even wfs output interrupted

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/QueryBuilder.java
- src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/QueryBuilderTest.java
[![GEOS-10981](https://badgen.net/badge/JIRA/GEOS-10981/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10981)
Backport #6883
> [Backport 2.23.x] [GEOS-10981] Slow CSW GetRecords requests with JDBC Configuration

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/QueryBuilder.java
- src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/QueryBuilderTest.java
[![GEOS-10981](https://badgen.net/badge/JIRA/GEOS-10981/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10981)
Backport #6883
> [Backport 2.22.x] [GEOS-10981] Slow CSW GetRecords requests with JDBC Configuration

- doc/en/user/source/extensions/gwc-s3/configuration.rst
Just to ease up finding how the default chain is supposed to work, and the various ways it can be configured.
> Provide a link to the AWS default credential provider chain

- src/main/src/test/java/org/geoserver/data/test/TimeElevation.properties
- src/wms/src/main/java/applicationContext.xml
- src/wms/src/main/java/org/geoserver/wms/GetFeatureInfo.java
- src/wms/src/main/java/org/geoserver/wms/GetMap.java
- src/wms/src/main/java/org/geoserver/wms/WMS.java
- src/wms/src/test/java/org/geoserver/wms/WMSTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetFeatureInfoIntegrationTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetMapIntegrationTest.java
[![GEOS-10994](https://badgen.net/badge/JIRA/GEOS-10994/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10994)
Backport #6869
> [Backport 2.22.x] [GEOS-10994] OOM due to too many dimensions when range requested

- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/ExtTypes.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/tasks/DbLocalPublicationTaskTypeImpl.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/tasks/FileLocalPublicationTaskTypeImpl.java
[![GEOS-11022](https://badgen.net/badge/JIRA/GEOS-11022/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11022)
Backport #6922
> [Backport 2.23.x] [GEOS-11022] Taskmanager: support isolated catalog facades

- src/web/security/core/src/main/java/org/geoserver/security/web/url/URLChecksPage.html
[![GEOS-10949](https://badgen.net/badge/JIRA/GEOS-10949/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10949)
Test button moved to be included with form fieldset, this is a non functional change.
> [GEOS-10949] URLChecksPage formatting

- src/web/security/core/src/main/java/org/geoserver/security/web/url/URLChecksPage.html
[![GEOS-10949](https://badgen.net/badge/JIRA/GEOS-10949/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10949)
Backport #6937
> [Backport 2.23.x] [GEOS-10949] URLChecksPage formatting

- src/web/security/core/src/main/java/org/geoserver/security/web/url/URLChecksPage.html
[![GEOS-10949](https://badgen.net/badge/JIRA/GEOS-10949/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10949)
Backport #6937
> [Backport 2.22.x] [GEOS-10949] URLChecksPage formatting

- src/community/security/oauth2/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuth2SecurityConfiguration.java
- src/community/security/oauth2/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilter.java
[![GEOS-11036](https://badgen.net/badge/JIRA/GEOS-11036/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11036)
> [GEOS-11036] The OAuth2*/OIDC security filters do not work as expected anymore after the spring-security-core depencency update to 5.7.8

- doc/en/user/source/extensions/geofence-server/installing.rst
[![GEOS-10872](https://badgen.net/badge/JIRA/GEOS-10872/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10872)
Backport #6957
> [Backport 2.22.x] [GEOS-10872] Document gwc.context.suffix setting for GeoFence to access `/rest` endpoint

- doc/en/user/source/extensions/geofence-server/installing.rst
[![GEOS-10872](https://badgen.net/badge/JIRA/GEOS-10872/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10872)
Backport #6957
> [Backport 2.23.x] [GEOS-10872] Document gwc.context.suffix setting for GeoFence to access `/rest` endpoint

- doc/en/user/source/rest/api/index.rst
To be consistent with https://docs.geoserver.org/latest/en/user/rest/index.html (Swagger API), use the heading Security for the 3 headings that relate to security (otherwise a Ctrl-F search for `security` doesn't work)
> Update REST API ToC for 3x Security headings

- src/extension/metadata/src/main/java/org/geoserver/metadata/data/service/impl/ConfigurationServiceImpl.java
- src/extension/metadata/src/test/java/org/geoserver/metadata/EmptyConfigurationTest.java
> Fix metadata test failures

- src/community/datadir-catalog-loader/README.md
- src/community/datadir-catalog-loader/pom.xml
- src/community/datadir-catalog-loader/src/main/java/org/geoserver/catalog/datadir/DataDirectoryGeoServerLoader.java
- src/community/datadir-catalog-loader/src/main/java/org/geoserver/catalog/datadir/config/DataDirectoryLoaderConfiguration.java
- src/community/datadir-catalog-loader/src/main/java/org/geoserver/catalog/datadir/internal/CatalogConfigLoader.java
- src/community/datadir-catalog-loader/src/main/java/org/geoserver/catalog/datadir/internal/DataDirectoryLoader.java
- src/community/datadir-catalog-loader/src/main/java/org/geoserver/catalog/datadir/internal/DataDirectoryWalker.java
- src/community/datadir-catalog-loader/src/main/java/org/geoserver/catalog/datadir/internal/GeoServerConfigLoader.java
- src/community/datadir-catalog-loader/src/main/java/org/geoserver/catalog/datadir/internal/XStreamLoader.java
- src/community/datadir-catalog-loader/src/main/resources/applicationContext.xml
- src/community/datadir-catalog-loader/src/test/java/org/geoserver/catalog/datadir/DataDirectoryGeoServerLoaderTest.java
- src/community/datadir-catalog-loader/src/test/java/org/geoserver/catalog/datadir/DataDirectoryLoaderConfigurationTest.java
- src/community/datadir-catalog-loader/src/test/java/org/geoserver/catalog/faker/CatalogFaker.java
- src/community/pom.xml
- src/community/release/ext-datadir-catalog-loader.xml
- src/community/release/pom.xml
- src/web/app/pom.xml
[![GEOS-11049](https://badgen.net/badge/JIRA/GEOS-11049/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11049)
Add gs-datadir-catalog-loader community module to mprove startup time when loading large catalogs from disk, especially over shared drives such as NFS.
The approach is to
- Parallelize both I/O calls and parsing of Catalog and Config info objects
- "Serialize" I/O calls as much as possible, trying to make a single pass over the `workspaces` directory tree, and load both catalog (workspaces, layers, etc.) and config (services, settings, etc.) files in one pass.
The point is that large Catalogs contain several thousand small XML files that need to be read and parsed, and NFS in particular is really bad at serving small files.
> [GEOS-11049] Community module "datadir catalog loader"

- doc/en/user/source/installation/docker.rst
Remove the duplicate **wps-cluster-hazelcast** extension from the list of available extensions.
> Fix the duplicate items in the list

- src/release/bin.xml
[![GEOS-10874](https://badgen.net/badge/JIRA/GEOS-10874/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10874)
Apparently, just a leftover in the assembly file, from GISP 167 (GEOS-10426). The bin file appears to be running fine without that jar (just made a quick test).
> [GEOS-10874] Log4J: Windows binary zip release file with log4j-1.2.14

- src/release/bin.xml
[![GEOS-10874](https://badgen.net/badge/JIRA/GEOS-10874/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10874)
Backport #6956
> [Backport 2.22.x] [GEOS-10874] Log4J: Windows binary zip release file with log4j-1.2.14

- src/release/bin.xml
[![GEOS-10874](https://badgen.net/badge/JIRA/GEOS-10874/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10874)
Backport #6956
> [Backport 2.23.x] [GEOS-10874] Log4J: Windows binary zip release file with log4j-1.2.14

- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/OSEOFactoryExtension.java
- src/community/oseo/oseo-core/src/main/resources/applicationContext.xml
- src/community/oseo/oseo-core/src/test/java/org/geoserver/opensearch/eo/OSEOFactoryExtensionTest.java
[![GEOS-11035](https://badgen.net/badge/JIRA/GEOS-11035/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11035)
Backport #6959
> [Backport 2.23.x] [GEOS-11035] Enabling OSEO from Workspace Edit Page Results in an NPE

- doc/en/user/source/security/urlchecks.rst
- src/main/src/main/java/org/geoserver/security/urlchecks/StyleURLChecker.java
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReader.java
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReaderTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapURLCheckersTest.java
- src/wms/src/test/resources/org/geoserver/wms/wms_1_1_1/burg03.svg
- src/wms/src/test/resources/org/geoserver/wms/wms_1_1_1/burg_fragment.sld
- src/wms/src/test/resources/org/geoserver/wms/wms_1_1_1/burg_query.sld
[![GEOS-11048](https://badgen.net/badge/JIRA/GEOS-11048/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11048)
This PR contains the following changes:
1. StyleURLChecker removes the URL query and fragment before doing its check.
1. URLChecker is applied to the WMS GetLegendGraphic SLD parameter.
1. Updated documentation to mention GetFeatureInfo and GetLegendGraphic requests.
> [GEOS-11048] Improve URL checking

- doc/en/user/source/security/urlchecks.rst
- src/main/src/main/java/org/geoserver/security/urlchecks/StyleURLChecker.java
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReader.java
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReaderTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapURLCheckersTest.java
- src/wms/src/test/resources/org/geoserver/wms/wms_1_1_1/burg03.svg
- src/wms/src/test/resources/org/geoserver/wms/wms_1_1_1/burg_fragment.sld
- src/wms/src/test/resources/org/geoserver/wms/wms_1_1_1/burg_query.sld
[![GEOS-11048](https://badgen.net/badge/JIRA/GEOS-11048/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11048)
Backport #6979
> [Backport 2.23.x] [GEOS-11048] Improve URL checking

- doc/en/user/source/security/urlchecks.rst
- src/main/src/main/java/org/geoserver/security/urlchecks/StyleURLChecker.java
- src/wms/src/main/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReader.java
- src/wms/src/test/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReaderTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapURLCheckersTest.java
- src/wms/src/test/resources/org/geoserver/wms/wms_1_1_1/burg03.svg
- src/wms/src/test/resources/org/geoserver/wms/wms_1_1_1/burg_fragment.sld
- src/wms/src/test/resources/org/geoserver/wms/wms_1_1_1/burg_query.sld
[![GEOS-11048](https://badgen.net/badge/JIRA/GEOS-11048/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11048)
Backport #6979
> [Backport 2.22.x] [GEOS-11048] Improve URL checking

- doc/en/user/source/services/wms/vendor.rst
- src/wms/src/main/java/applicationContext.xml
- src/wms/src/main/java/org/geoserver/wms/kvp/FilterKvpParser.java
- src/wms/src/test/java/org/geoserver/wms/map/png/GetMapIntegrationTest.java
[![GEOS-10903](https://badgen.net/badge/JIRA/GEOS-10903/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10903)
Backport #6968
> [Backport 2.22.x] [GEOS-10903] WMS filtering with Filter 2.0 fails

- src/web/gwc/src/main/java/org/geoserver/gwc/web/diskquota/JDBCConnectionPoolPanel.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/diskquota/JDBCConnectionPoolPanelTest.java
[![GEOS-10875](https://badgen.net/badge/JIRA/GEOS-10875/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10875)
> [GEOS-10875] Disk Quota JDBC password shown in plaintext

- doc/en/user/source/services/wms/vendor.rst
- src/wms/src/main/java/applicationContext.xml
- src/wms/src/main/java/org/geoserver/wms/kvp/FilterKvpParser.java
- src/wms/src/test/java/org/geoserver/wms/map/png/GetMapIntegrationTest.java
[![GEOS-10903](https://badgen.net/badge/JIRA/GEOS-10903/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10903)
Backport #6968
> [Backport 2.23.x] [GEOS-10903] WMS filtering with Filter 2.0 fails

- src/release/ext-charts.xml
- src/release/ext-sqlserver.xml
[![GEOS-11060](https://badgen.net/badge/JIRA/GEOS-11060/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11060)
> [GEOS-11060] charts and mssql extension zips are missing the extension

- src/pom.xml
[![GEOS-11062](https://badgen.net/badge/JIRA/GEOS-11062/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11062)
Dependency upgrade with bug fixes.  Backport is optional.
> [GEOS-11062] Upgrade httpclient from 4.5.13 to 4.5.14

- src/pom.xml
[![GEOS-11063](https://badgen.net/badge/JIRA/GEOS-11063/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11063)
Dependency upgrade with bug fixes. Backport is optional.
> [GEOS-11063] Upgrade httpcore from 4.4.10 to 4.4.16

- src/web/gwc/src/main/java/org/geoserver/gwc/web/diskquota/JDBCConnectionPoolPanel.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/diskquota/JDBCConnectionPoolPanelTest.java
[![GEOS-10875](https://badgen.net/badge/JIRA/GEOS-10875/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10875)
Backport #6993
> [Backport 2.23.x] [GEOS-10875] Disk Quota JDBC password shown in plaintext

- src/web/gwc/src/main/java/org/geoserver/gwc/web/diskquota/JDBCConnectionPoolPanel.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/diskquota/JDBCConnectionPoolPanelTest.java
[![GEOS-10875](https://badgen.net/badge/JIRA/GEOS-10875/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10875)
Backport #6993
> [Backport 2.22.x] [GEOS-10875] Disk Quota JDBC password shown in plaintext

- src/pom.xml
[![GEOS-11062](https://badgen.net/badge/JIRA/GEOS-11062/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11062)
Backport #7000
> [Backport 2.23.x] [GEOS-11062] Upgrade httpclient from 4.5.13 to 4.5.14

- src/pom.xml
[![GEOS-11062](https://badgen.net/badge/JIRA/GEOS-11062/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11062)
Backport #7000
> [Backport 2.22.x] [GEOS-11062] Upgrade httpclient from 4.5.13 to 4.5.14

- src/community/security/keycloak/pom.xml
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml
- src/community/web-service-auth/pom.xml
- src/extension/wps/wps-core/pom.xml
- src/pom.xml
- src/web/core/pom.xml
- src/wms/pom.xml
[![GEOS-11067](https://badgen.net/badge/JIRA/GEOS-11067/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11067)
This dependency upgrade includes security fixes but it is a test dependency so they may not be as important to backport.
> [GEOS-11067] Upgrade wiremock to 2.35.0

- src/community/datadir-catalog-loader/README.md
- src/community/datadir-catalog-loader/pom.xml
- src/community/datadir-catalog-loader/src/main/java/org/geoserver/catalog/datadir/DataDirectoryGeoServerLoader.java
- src/community/datadir-catalog-loader/src/main/java/org/geoserver/catalog/datadir/config/DataDirectoryLoaderConfiguration.java
- src/community/datadir-catalog-loader/src/main/java/org/geoserver/catalog/datadir/internal/CatalogConfigLoader.java
- src/community/datadir-catalog-loader/src/main/java/org/geoserver/catalog/datadir/internal/DataDirectoryLoader.java
- src/community/datadir-catalog-loader/src/main/java/org/geoserver/catalog/datadir/internal/DataDirectoryWalker.java
- src/community/datadir-catalog-loader/src/main/java/org/geoserver/catalog/datadir/internal/GeoServerConfigLoader.java
- src/community/datadir-catalog-loader/src/main/java/org/geoserver/catalog/datadir/internal/XStreamLoader.java
- src/community/datadir-catalog-loader/src/main/resources/applicationContext.xml
- src/community/datadir-catalog-loader/src/test/java/org/geoserver/catalog/datadir/DataDirectoryGeoServerLoaderTest.java
- src/community/datadir-catalog-loader/src/test/java/org/geoserver/catalog/datadir/DataDirectoryLoaderConfigurationTest.java
- src/community/datadir-catalog-loader/src/test/java/org/geoserver/catalog/faker/CatalogFaker.java
- src/community/pom.xml
- src/community/release/ext-datadir-catalog-loader.xml
- src/community/release/pom.xml
- src/web/app/pom.xml
[![GEOS-11049](https://badgen.net/badge/JIRA/GEOS-11049/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11049)
Backport #6981 to `2.23.x`
> [Backport 2.23.x] [GEOS-11049] Community module "datadir catalog loader"

- src/web/core/src/main/java/org/geoserver/web/data/resource/AttributeTypeInfoEditor.java
- src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
[![GEOS-11069](https://badgen.net/badge/JIRA/GEOS-11069/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11069)
Backport #7018
> [Backport 2.22.x] [GEOS-11069] Layer configuration page doesn't work for broken layers

- src/web/core/src/main/java/org/geoserver/web/data/resource/AttributeTypeInfoEditor.java
- src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
[![GEOS-11069](https://badgen.net/badge/JIRA/GEOS-11069/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11069)
Backport #7018
> [Backport 2.23.x] [GEOS-11069] Layer configuration page doesn't work for broken layers

- doc/en/user/source/extensions/iau/index.rst
- doc/en/user/source/extensions/iau/install.rst
- doc/en/user/source/extensions/iau/usage.rst
- doc/en/user/source/extensions/index.rst
- src/pom.xml
- src/release/ext-iau.xml
- src/release/extensions/iau/iau-readme.txt
- src/release/pom.xml
[![GEOS-11075](https://badgen.net/badge/JIRA/GEOS-11075/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11075)
See ticket, and discussion on list. This is pure packaging of the gt-iau-wkt module, with no GeoServer specific additions.
> [GEOS-11075] IAU authority, planetary CRS support

- src/main/src/main/java/org/geoserver/catalog/impl/FeatureTypeValidator.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/FeatureTypeControllerTest.java
[![GEOS-11054](https://badgen.net/badge/JIRA/GEOS-11054/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11054)
Backport #7005
> [Backport 2.22.x] [GEOS-11054] NullPointerException creating layer with REST, along with attribute list

- src/main/src/main/java/org/geoserver/catalog/impl/FeatureTypeValidator.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/FeatureTypeControllerTest.java
[![GEOS-11054](https://badgen.net/badge/JIRA/GEOS-11054/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11054)
Backport #7005
> [Backport 2.23.x] [GEOS-11054] NullPointerException creating layer with REST, along with attribute list

- doc/en/user/source/production/container.rst
- src/web/app/src/main/webapp/WEB-INF/web.xml
Fix broken link in CORS instructions, dynamically include snippet from web.xml to avoid being out of sync.
> Fix CORS documentation link and use web.xml via literalinclude

- doc/en/user/source/security/layer.rst
> Clarification concerning layers security

- doc/en/user/source/security/layer.rst
> [Backport 2.22.x] Clarification concerning layers security

- doc/en/user/source/security/layer.rst
> [Backport 2.23.x] Clarification concerning layers security

- doc/en/developer/source/tools.rst
> Fix spelling & grammar

- src/pom.xml
> [Backport 2.23.x] Bump org.springframework.security:spring-security-config from 5.7.8 to 5.7.10 in /src

- restput.xml
Added as part of commit https://github.com/geoserver/geoserver/commit/97038e6f5f9dfca1e6e33f528e55b342ae1219b9
> remove restput.xml file lurking in base directory

- restput.xml
> [Backport 2.23.x] remove restput.xml file lurking in base directory

- src/pom.xml
[![GEOS-11094](https://badgen.net/badge/JIRA/GEOS-11094/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11094)
GeoTool’s gt-epsg-hsqldb depends on org.hsqldb:hsqldb:2.7.2, but GeoServer overrides it with 2.7.1.
The only GeoServer module directly depending on hsqldb is gs-kml.
> [GEOS-11094] Bump org.hsqldb:hsqldb:2.7.1 to 2.7.2

- doc/en/api/1.0.0/workspaces.yaml
The OpenAPI/Swagger Documentation describes an invalid schema when POSTing to `/rest/workspaces`. To POST workspaces via JSON the exact same schema as used by the XML needs to be used, currently a (slightly) different schema is documented that just results in a crash of xmlstream and a HTTP 500 Error.
This PR simply fixes the Swagger schema.
See also: https://gis.stackexchange.com/questions/277837/http-500-error-when-creating-workspace-using-geoserver-rest-api
> [Documentation] Fix wrong JSON payload schema for `/rest/workspaces`

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/WPSInitializer.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/WPSInitializerTest.java
- src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
- src/main/src/main/java/org/geoserver/config/GeoServerReinitializer.java
- src/main/src/main/java/org/geoserver/config/impl/GeoServerImpl.java
[![GEOS-10248](https://badgen.net/badge/JIRA/GEOS-10248/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10248)
Backport #7036
> [Backport 2.23.x] [GEOS-10248] Check WPSInitializer interaction with reload

- src/main/src/main/java/org/geoserver/catalog/impl/CatalogInfoLookup.java
- src/main/src/main/java/org/geoserver/catalog/impl/DefaultCatalogFacade.java
- src/main/src/main/java/org/geoserver/catalog/impl/NamespaceInfoLookup.java
- src/main/src/test/java/org/geoserver/catalog/impl/NamespaceInfoLookupTest.java
[![GEOS-11089](https://badgen.net/badge/JIRA/GEOS-11089/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11089)
Backport #7051
> [Backport 2.23.x] [GEOS-11089] Performance penalty adding namespaces while loading catalog

- src/web/core/src/main/java/org/geoserver/web/data/workspace/WorkspaceProvider.java
- src/web/core/src/test/java/org/geoserver/web/data/workspace/WorkspaceProviderTest.java
[![GEOS-11090](https://badgen.net/badge/JIRA/GEOS-11090/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11090)
Backport #7053
> [Backport 2.23.x] [GEOS-11090] Use Catalog streaming API in WorkspacePage

- src/main/src/main/java/org/geoserver/catalog/impl/IsolatedCatalogFacade.java
[![GEOS-11087](https://badgen.net/badge/JIRA/GEOS-11087/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11087)
Backport #7049
> [Backport 2.23.x] [GEOS-11087] Fix IsolatedCatalogFacade unnecessary performance overhead

- doc/en/user/source/extensions/monitoring/configuration.rst
- src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorConfig.java
- src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorFilter.java
- src/extension/monitor/core/src/main/java/org/geoserver/monitor/ReverseDNSPostProcessor.java
- src/extension/monitor/core/src/test/java/org/geoserver/monitor/MonitorConfigTest.java
[![GEOS-10856](https://badgen.net/badge/JIRA/GEOS-10856/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10856)
Backport #6986
**Authored by:** @hyperman2
> [Backport 2.23.x] [GEOS-10856] geoserver monitor plugin - scaling troubles

- src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/GeoServerKeycloakFilter.java
- src/community/security/keycloak/src/test/java/org/geoserver/security/keycloak/GeoServerKeycloakFilterTest.java
[![GEOS-11068](https://badgen.net/badge/JIRA/GEOS-11068/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11068)
Backport #7030
> [Backport 2.23.x] [GEOS-11068] Keycloak: custom admin role not picked up

- src/security/ldap/src/main/java/org/geoserver/security/ldap/BindingLdapAuthoritiesPopulator.java
- src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPRoleService.java
- src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPUserGroupService.java
- src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPUtils.java
- src/security/ldap/src/test/java/org/geoserver/security/ldap/LDAPUtilsTest.java
[![GEOS-10452](https://badgen.net/badge/JIRA/GEOS-10452/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10452)
Backport #6189
**Authored by:** @escheper
> [Backport 2.23.x] [GEOS-10452] Fixed Role Services for LDAP/Active Directory.

- src/web/core/src/main/java/org/geoserver/web/data/store/DataAccessEditPage.java
> [Backport 2.22.x] Fix order of error message parameters

- src/web/core/src/main/java/org/geoserver/web/data/store/DataAccessEditPage.java
> [Backport 2.23.x] Fix order of error message parameters

- src/community/ogcapi/ogcapi-styles/src/main/java/org/geoserver/ogcapi/v1/styles/StyleLayer.java
> remove unintended org.opengis.geometry.coordinate.Polygon class

- src/community/ogcapi/ogcapi-styles/src/main/java/org/geoserver/ogcapi/v1/styles/StyleLayer.java
> remove unneeded import

- src/wfs/src/test/java/org/geoserver/wfs/response/CSVOutputFormatTest.java
[![GEOS-11102](https://badgen.net/badge/JIRA/GEOS-11102/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11102) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11102] Locale Update for Test

- src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/v1/maps/CollectionDocument.java
- src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/v1/maps/MapsService.java
- src/community/ogcapi/ogcapi-maps/src/main/resources/org/geoserver/ogcapi/v1/maps/collection_include.ftl
- src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/CollectionTest.java
- src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/MapsTest.java
- src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/MapsTestSupport.java
- src/community/ogcapi/ogcapi-maps/src/test/resources/org/geoserver/ogcapi/v1/maps/TimeElevationWithStartEnd.properties
[![GEOS-11118](https://badgen.net/badge/JIRA/GEOS-11118/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11118) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
unit tests for caps and cleanup
added datetime
cleanup
cleanup2
more cleanup
datetime info test
cleanup
> [GEOS-11118] Add Temporal Extents domain and datetime parameter to Maps API

- src/pom.xml
[![GEOS-11131](https://badgen.net/badge/JIRA/GEOS-11131/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11131) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Preparing for the release (will be backported to 2.24.x)
> [GEOS-11131] Update GeoFence to 3.7-RC

- src/pom.xml
[![GEOS-11132](https://badgen.net/badge/JIRA/GEOS-11132/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11132) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Update to the mapfish-print-lib 2.3-RC release candidate. This reflects the refacoring to GeoTools 30-RC.
> [GEOS-11132] Updating printing plugin to mapfish-print-lib 2.3-RC

- src/pom.xml
[![GEOS-11131](https://badgen.net/badge/JIRA/GEOS-11131/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11131) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7122
> [Backport 2.24.x] [GEOS-11131] Update GeoFence to 3.7-RC

- .github/workflows/javadoc.yml
- src/pom.xml
> [Backport 2.24.x] Revert javadoc maven plugin upgrade, add build to ensure aggregate works

- doc/en/user/source/community/opensearch-eo/STAC.rst
> OSEO: STAC templates, add v1 to item and collection links

- src/web/app/src/test/resources/jetty-context.xml
[![GEOS-11138](https://badgen.net/badge/JIRA/GEOS-11138/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11138) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11138] Add dtd to jetty context file

- src/web/app/src/test/resources/jetty-context.xml
[![GEOS-11138](https://badgen.net/badge/JIRA/GEOS-11138/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11138) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7143
**Authored by:** @spike83
> [Backport 2.22.x] [GEOS-11138] Add dtd to jetty context file

- src/web/app/src/test/resources/jetty-context.xml
[![GEOS-11138](https://badgen.net/badge/JIRA/GEOS-11138/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11138) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7143
**Authored by:** @spike83
> [Backport 2.23.x] [GEOS-11138] Add dtd to jetty context file

- src/web/app/src/test/resources/jetty-context.xml
[![GEOS-11138](https://badgen.net/badge/JIRA/GEOS-11138/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11138) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7143
**Authored by:** @spike83
> [Backport 2.24.x] [GEOS-11138] Add dtd to jetty context file

- src/main/src/main/java/org/geoserver/security/filter/GeoServerPreAuthenticationFilter.java
[![GEOS-11114](https://badgen.net/badge/JIRA/GEOS-11114/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11114) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7098
**Authored by:** @awaterme
> [Backport 2.23.x] [GEOS-11114] Improve extensibility in Pre-Authentication scenarios

- src/main/src/main/java/org/geoserver/security/filter/GeoServerPreAuthenticationFilter.java
[![GEOS-11114](https://badgen.net/badge/JIRA/GEOS-11114/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11114) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7098
**Authored by:** @awaterme
> [Backport 2.24.x] [GEOS-11114] Improve extensibility in Pre-Authentication scenarios

- src/main/src/main/java/org/geoserver/ows/StylePublisher.java
- src/main/src/test/java/org/geoserver/ows/StylePublisherTest.java
- src/ows/src/main/java/org/geoserver/ows/AbstractURLPublisher.java
[![GEOS-11149](https://badgen.net/badge/JIRA/GEOS-11149/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11149) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR sets the "Content-Disposition: attachment" response header to style resources with certain content types and also now uses the same default content type as the Resources REST API to mitigate a security issue.  The Style Publisher also no longer allows access to the XML configuration files even though they don't currently contain any sensitive information.
Note that with this PR and …
> [GEOS-11149] Update response headers for the Style Publisher

- src/main/src/main/java/org/geoserver/ows/StylePublisher.java
- src/main/src/test/java/org/geoserver/ows/StylePublisherTest.java
- src/ows/src/main/java/org/geoserver/ows/AbstractURLPublisher.java
[![GEOS-11149](https://badgen.net/badge/JIRA/GEOS-11149/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11149) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7162
> [Backport 2.24.x] [GEOS-11149] Update response headers for the Style Publisher

- src/main/src/main/java/org/geoserver/ows/StylePublisher.java
- src/main/src/test/java/org/geoserver/ows/StylePublisherTest.java
- src/ows/src/main/java/org/geoserver/ows/AbstractURLPublisher.java
[![GEOS-11149](https://badgen.net/badge/JIRA/GEOS-11149/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11149) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7162
> [Backport 2.23.x] [GEOS-11149] Update response headers for the Style Publisher

- src/pom.xml
Reverts geoserver/geoserver#7165
See comments in the original PR for rationale.
> Revert "Resolve geoserverBaseDir maven property using standard means"

- doc/en/user/source/production/config.rst
[![GEOS-11141](https://badgen.net/badge/JIRA/GEOS-11141/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11141) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
The idea is to add a little section to the documentation that can help users ensure the logging configuration is not missconfigured with neferious intentions even with administration access.
> [GEOS-11141] Add section about logging configuration hardening

- doc/en/user/source/production/config.rst
[![GEOS-11141](https://badgen.net/badge/JIRA/GEOS-11141/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11141) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7144
**Authored by:** @anthares101
> [Backport 2.23.x] [GEOS-11141] Add section about logging configuration hardening

- doc/en/user/source/production/config.rst
Backport #7144
**Authored by:** @anthares101
> [Backport 2.24.x] [GEOS-11141] Add section about logging configuration hardening

- src/community/mbtiles/src/test/java/org/geoserver/mbtiles/MBTilesGetMapOutputFormatTest.java
[![GEOS-11146](https://badgen.net/badge/JIRA/GEOS-11146/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11146) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
While looking at the Wicket 8 work, I hit a test failure in the MBTiles output module.
That isn't Wicket 8 specific though - it'll occur anyway. So resolve it here to simplify the Wicket 8 work, a bit.
> [GEOS-11146] Fix MBTiles output format test

- src/web/app/src/main/webapp/WEB-INF/web.xml
[![GEOS-11142](https://badgen.net/badge/JIRA/GEOS-11142/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11142) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR adds a mime type mapping for yaml files so that the Style Publisher will return a "Content-Type: text/plain" response header for YSLD styles instead of no Content-Type header.  There is no unit test since this is a web.xml change.
> [GEOS-11142] Add mime type mapping for yaml files

- src/web/app/src/main/webapp/WEB-INF/web.xml
[![GEOS-11142](https://badgen.net/badge/JIRA/GEOS-11142/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11142) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7155
> [Backport 2.24.x] [GEOS-11142] Add mime type mapping for yaml files

- src/web/app/src/main/webapp/WEB-INF/web.xml
[![GEOS-11142](https://badgen.net/badge/JIRA/GEOS-11142/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11142) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7155
> [Backport 2.23.x] [GEOS-11142] Add mime type mapping for yaml files

- src/web/demo/src/main/resources/GeoServerApplication_fr.properties
Translations update from [OSGeo Weblate](https://weblate.osgeo.org) for [GeoServer/web-core](https://weblate.osgeo.org/projects/geoserver/web-core/).
It also includes following components:
* [GeoServer/extension-printing](https://weblate.osgeo.org/projects/geoserver/extension-printing/)
* [GeoServer/community-rest-ext](https://weblate.osgeo.org/projects/geoserver/community-rest-ext/)
* [GeoServer/web-rest](https://weblate.osgeo.org/projects/geoserver/web-rest/)
* [GeoServer/web-security-core](https://weblate.osgeo.org/projects/geoserver/web-security-core/)
* [GeoServer/web-wcs](https://weblate.osgeo.org/projects/geoserver/web-wcs/)
* [GeoServer/web-wms](https://weblate.osgeo.org/projects/geoserver/web-wms/)
* [GeoServer/community-pgraster](https://weblate.osgeo.org/projects/geoserver/commu …
> Translations update from OSGeo Weblate

- doc/en/user/source/extensions/printing/configuration.rst
- doc/en/user/source/extensions/printing/faq.rst
- doc/en/user/source/extensions/printing/index.rst
- doc/en/user/source/extensions/printing/protocol.rst
- src/extension/printing/pom.xml
- src/pom.xml
[![GEOS-11159](https://badgen.net/badge/JIRA/GEOS-11159/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11159) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Based on GeoTools 30.0 release
> [GEOS-11159] Update mapfish-print-v2 2.3.0

- doc/en/user/source/extensions/printing/configuration.rst
- doc/en/user/source/extensions/printing/faq.rst
- doc/en/user/source/extensions/printing/index.rst
- doc/en/user/source/extensions/printing/protocol.rst
- src/extension/printing/pom.xml
- src/pom.xml
[![GEOS-11159](https://badgen.net/badge/JIRA/GEOS-11159/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11159) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7183
> [Backport 2.24.x] [GEOS-11159] Update mapfish-print-v2 2.3.0

- src/community/pom.xml
[![GEOS-11134](https://badgen.net/badge/JIRA/GEOS-11134/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11134) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
The build server is having failures that do not show up in GitHub workflows, this pull-request is troubleshooting the problem.
> [GEOS-11134] Confirm community assemble downloads have geoserver-*.zip finalName

- doc/en/developer/source/policies/community-modules.rst
[![GEOS-11134](https://badgen.net/badge/JIRA/GEOS-11134/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11134) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11134] build fix for literal include language markdown reference

- src/community/pom.xml
[![GEOS-11134](https://badgen.net/badge/JIRA/GEOS-11134/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11134) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7186
> [Backport 2.24.x] [GEOS-11134] Confirm community assemble downloads have geoserver-*.zip finalName

- src/wms/src/main/java/org/geoserver/wms/map/AbstractOpenLayersMapOutputFormat.java
- src/wms/src/main/resources/org/geoserver/wms/map/OpenLayers2MapTemplate.ftl
- src/wms/src/main/resources/org/geoserver/wms/map/OpenLayers3MapTemplate.ftl
- src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapOutputFormatTest.java
[![GEOS-11153](https://badgen.net/badge/JIRA/GEOS-11153/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11153) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7174
> [Backport 2.24.x] [GEOS-11153] Improve handling special characters in the WMS OpenLayers Format

- src/community/security/keycloak/pom.xml
- src/community/security/oauth2-geonode/pom.xml
- src/community/security/oauth2-github/pom.xml
- src/community/security/oauth2-google/pom.xml
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml
- src/community/security/oauth2/oauth2-core/pom.xml
- src/pom.xml
[![GEOS-11161](https://badgen.net/badge/JIRA/GEOS-11161/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11161) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Address some build warnings associated with running tests, non-functional change.
> [GEOS-11161] Address build warnings for running unit tests

- src/community/security/keycloak/pom.xml
- src/community/security/oauth2-geonode/pom.xml
- src/community/security/oauth2-github/pom.xml
- src/community/security/oauth2-google/pom.xml
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml
- src/community/security/oauth2/oauth2-core/pom.xml
- src/pom.xml
[![GEOS-11161](https://badgen.net/badge/JIRA/GEOS-11161/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11161) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7187
> [Backport 2.23.x] [GEOS-11161] Address build warnings for running unit tests

- src/community/security/keycloak/pom.xml
- src/community/security/oauth2-geonode/pom.xml
- src/community/security/oauth2-github/pom.xml
- src/community/security/oauth2-google/pom.xml
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml
- src/community/security/oauth2/oauth2-core/pom.xml
- src/pom.xml
[![GEOS-11161](https://badgen.net/badge/JIRA/GEOS-11161/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11161) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7187
> [Backport 2.24.x] [GEOS-11161] Address build warnings for running unit tests

- doc/en/user/source/production/config.rst
- src/web/app/src/main/webapp/WEB-INF/web.xml
[![GEOS-11173](https://badgen.net/badge/JIRA/GEOS-11173/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11173) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR updates the web.xml to default to using HttpOnly session cookies along with some documentation updates.
> [GEOS-11173] Default to using HttpOnly session cookies

- doc/en/user/source/production/config.rst
- src/main/src/main/java/org/geoserver/filters/XFrameOptionsFilter.java
- src/main/src/test/java/org/geoserver/filters/XFrameOptionsFilterTest.java
[![GEOS-11155](https://badgen.net/badge/JIRA/GEOS-11155/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11155) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR adds the "X-Content-Type-Options: nosniff" HTTP header to all responses with a property to disable adding the header and updates the documentation.
> [GEOS-11155] Add the X-Content-Type-Options header

- doc/en/user/source/services/csw/features.rst
- src/extension/csw/core/src/main/java/org/geoserver/csw/store/internal/CatalogStoreMapping.java
- src/extension/csw/core/src/main/java/org/geoserver/csw/store/internal/InternalCatalogStore.java
- src/extension/csw/core/src/test/java/org/geoserver/csw/store/internal/InternalCatalogStoreTest.java
- src/extension/csw/core/src/test/java/org/geoserver/csw/store/internal/ResourceAccessManagerCSWTest.java
- src/extension/csw/csw-iso/src/test/java/org/geoserver/csw/store/internal/InternalCatalogStoreTest.java
- src/extension/csw/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/MultipleMappingTest.java
- src/extension/csw/csw-iso/src/test/resources/org/geoserver/csw/store/internal/MD_Metadata-second.properties.ignore
- src/extension/csw/csw-iso/src/test/resources/org/geoserver/csw/store/internal/Record-second.properties.ignore
[![GEOS-11096](https://badgen.net/badge/JIRA/GEOS-11096/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11096) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7072
> [Backport 2.22.x] [GEOS-11096] csw: support multiple mappings

- doc/en/user/source/services/csw/features.rst
- src/extension/csw/core/src/main/java/org/geoserver/csw/store/internal/CatalogStoreMapping.java
- src/extension/csw/core/src/main/java/org/geoserver/csw/store/internal/InternalCatalogStore.java
- src/extension/csw/core/src/test/java/org/geoserver/csw/store/internal/InternalCatalogStoreTest.java
- src/extension/csw/core/src/test/java/org/geoserver/csw/store/internal/ResourceAccessManagerCSWTest.java
- src/extension/csw/csw-iso/src/test/java/org/geoserver/csw/store/internal/InternalCatalogStoreTest.java
- src/extension/csw/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/MultipleMappingTest.java
- src/extension/csw/csw-iso/src/test/resources/org/geoserver/csw/store/internal/MD_Metadata-second.properties.ignore
- src/extension/csw/csw-iso/src/test/resources/org/geoserver/csw/store/internal/Record-second.properties.ignore
[![GEOS-11096](https://badgen.net/badge/JIRA/GEOS-11096/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11096) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7072
> [Backport 2.23.x] [GEOS-11096] csw: support multiple mappings

- src/web/security/core/src/main/resources/GeoServerApplication.properties
> [Backport 2.24.x] Fix URLcheck heading, grammar

- src/web/security/core/src/main/resources/GeoServerApplication.properties
> [Backport 2.23.x] Fix URLcheck heading, grammar

- src/community/ncwms/pom.xml
[![GEOS-11184](https://badgen.net/badge/JIRA/GEOS-11184/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11184) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Simple dependency scope fix (plus adding the iau one, as there is some test data depending on it now)
> [GEOS-11184] ncwms module has a compile dependency on gs-web-core test jar

- src/pom.xml
[![GEOS-11186](https://badgen.net/badge/JIRA/GEOS-11186/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11186) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Updates build system configuration to reflect correct parameter - `fastFail` per https://maven.apache.org/enforcer/maven-enforcer-plugin/enforce-mojo.html#failFast
> [GEOS-11186] Fix maven enforcer failFast

- src/extension/geofence/geofence/src/test/java/org/geoserver/geofence/ServicesTest.java
- src/pom.xml
[![GEOS-11190](https://badgen.net/badge/JIRA/GEOS-11190/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11190) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Change dep to geofence 3.6.1 in oredr to make log4j work.
Also fix an integration test.
See also https://github.com/geoserver/geofence/issues/251
> [Backport 2.23.x][GEOS-11190] GeoFence: align log4j2 deps

- src/extension/geofence/geofence/src/test/java/org/geoserver/geofence/ServicesTest.java
- src/pom.xml
[![GEOS-11190](https://badgen.net/badge/JIRA/GEOS-11190/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11190) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Change dep to geofence 3.7.1 in order to make log4j work.
Also fix an integration test.
See also https://github.com/geoserver/geofence/issues/251
Related versions table (from geofence main repo page):
> [Backport 2.24.x][GEOS-11190] GeoFence: align log4j2 deps

- src/extension/geofence/geofence/src/test/java/org/geoserver/geofence/ServicesTest.java
- src/pom.xml
[![GEOS-11190](https://badgen.net/badge/JIRA/GEOS-11190/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11190) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Change dep to geofence 3.7-SNAPSHOT in order to make log4j work.
Also fix an integration test.
See also https://github.com/geoserver/geofence/issues/251
Related versions table (from geofence main repo page):
> [GEOS-11190] GeoFence: align log4j2 deps

- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLController.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLControllerTest.java
[![GEOS-11154](https://badgen.net/badge/JIRA/GEOS-11154/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11154) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR updates the MapML HTML Page to properly escape special characters from GeoServer catalog information.
> [GEOS-11154] Improve handling special characters in the MapML HTML Page

- src/wms/src/main/java/org/geoserver/wms/svg/StreamingSVGMap.java
- src/wms/src/test/java/org/geoserver/wms/svg/SVGMapProducerTest.java
[![GEOS-11152](https://badgen.net/badge/JIRA/GEOS-11152/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11152) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7173
> [Backport 2.24.x] [GEOS-11152] Improve handling special characters in the Simple SVG Renderer

- doc/en/user/source/community/elasticsearch/index.rst
- src/community/elasticsearch/pom.xml
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticConfigurationPage.html
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticConfigurationPage.java
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticConfigurationPanel.java
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticFeatureTypeCallback.java
- src/community/elasticsearch/src/main/resources/GeoServerApplication.properties
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticClient.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticConfigurationPanelIT.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticConfigurationPanelTest.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticMappings.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticRequest.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticTestSupport.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/RestElasticClient.java
- src/community/elasticsearch/src/test/resources/active_mappings.json
- src/community/elasticsearch/src/test/resources/active_mappings_legacy.json
- src/community/elasticsearch/src/test/resources/active_mappings_ng.json
[![GEOS-11192](https://badgen.net/badge/JIRA/GEOS-11192/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11192) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
got ajax refresh working
added check if refresh
test finally working
docs
cleanup
more cleanup
> [GEOS-11192] Make refresh button for Elasticsearch fields configuration

- doc/en/user/source/community/elasticsearch/index.rst
- src/community/elasticsearch/pom.xml
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticConfigurationPage.html
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticConfigurationPage.java
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticConfigurationPanel.java
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticFeatureTypeCallback.java
- src/community/elasticsearch/src/main/resources/GeoServerApplication.properties
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticClient.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticConfigurationPanelIT.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticConfigurationPanelTest.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticMappings.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticRequest.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticTestSupport.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/RestElasticClient.java
- src/community/elasticsearch/src/test/resources/active_mappings.json
- src/community/elasticsearch/src/test/resources/active_mappings_legacy.json
- src/community/elasticsearch/src/test/resources/active_mappings_ng.json
[![GEOS-11192](https://badgen.net/badge/JIRA/GEOS-11192/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11192) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7257
> [Backport 2.24.x] [GEOS-11192] Make refresh button for Elasticsearch fields configuration

- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/BaseDownloadImageProcessTest.java
- src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadAnimationProcessTest.java
- src/main/src/main/java/org/geoserver/util/NearestMatchFinder.java
[![GEOS-11206](https://badgen.net/badge/JIRA/GEOS-11206/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11206) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Follow up to https://github.com/geoserver/geoserver/pull/7256, restricting the exception to the WMS service (InvalidDimensionException not being defined for others)
> [GEOS-11206] Throw nearest match mismatch exceptions only for WMS

- doc/en/user/source/community/elasticsearch/index.rst
- src/community/elasticsearch/pom.xml
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticConfigurationPage.html
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticConfigurationPage.java
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticConfigurationPanel.java
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticFeatureTypeCallback.java
- src/community/elasticsearch/src/main/resources/GeoServerApplication.properties
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticClient.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticConfigurationPanelIT.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticConfigurationPanelTest.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticMappings.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticRequest.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticTestSupport.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/RestElasticClient.java
- src/community/elasticsearch/src/test/resources/active_mappings.json
- src/community/elasticsearch/src/test/resources/active_mappings_legacy.json
- src/community/elasticsearch/src/test/resources/active_mappings_ng.json
[![GEOS-11192](https://badgen.net/badge/JIRA/GEOS-11192/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11192) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
got ajax refresh working
added check if refresh
test finally working
docs
cleanup
more cleanup
PR cleanup
parent panel refresh
cleaner search for attribute panel
it
test fix
> [GEOS-11192] Make refresh button for Elasticsearch fields configuration 2.23.x

- doc/en/user/source/community/elasticsearch/index.rst
- src/community/elasticsearch/pom.xml
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticConfigurationPage.html
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticConfigurationPage.java
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticConfigurationPanel.java
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticFeatureTypeCallback.java
- src/community/elasticsearch/src/main/resources/GeoServerApplication.properties
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticClient.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticConfigurationPanelIT.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticConfigurationPanelTest.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticMappings.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticRequest.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/ElasticTestSupport.java
- src/community/elasticsearch/src/test/java/org/geoserver/elasticsearch/RestElasticClient.java
- src/community/elasticsearch/src/test/resources/active_mappings.json
- src/community/elasticsearch/src/test/resources/active_mappings_legacy.json
- src/community/elasticsearch/src/test/resources/active_mappings_ng.json
[![GEOS-11192](https://badgen.net/badge/JIRA/GEOS-11192/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11192) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
got ajax refresh working
added check if refresh
test finally working
docs
cleanup
more cleanup
PR cleanup
parent panel refresh
cleaner search for attribute panel
it
test fix
> [GEOS-11192] Make refresh button for Elasticsearch fields configuration 2.22.x

- src/wms/src/main/java/org/geoserver/wms/featureinfo/FeatureInfoStylePreprocessor.java
- src/wms/src/test/java/org/geoserver/wms/featureinfo/RenderingBasedFeatureInfoTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java
- src/wms/src/test/resources/org/geoserver/wms/featureinfo/geom-function.properties
- src/wms/src/test/resources/org/geoserver/wms/featureinfo/geom-function.sld
[![GEOS-11203](https://badgen.net/badge/JIRA/GEOS-11203/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11203) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7275
> [Backport 2.23.x] [GEOS-11203] WMS GetFeatureInfo bad WKT exception for label-geometry

- src/wms/src/main/java/org/geoserver/wms/featureinfo/FeatureInfoStylePreprocessor.java
- src/wms/src/test/java/org/geoserver/wms/featureinfo/RenderingBasedFeatureInfoTest.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java
- src/wms/src/test/resources/org/geoserver/wms/featureinfo/geom-function.properties
- src/wms/src/test/resources/org/geoserver/wms/featureinfo/geom-function.sld
[![GEOS-11203](https://badgen.net/badge/JIRA/GEOS-11203/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11203) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7275
> [Backport 2.24.x] [GEOS-11203] WMS GetFeatureInfo bad WKT exception for label-geometry

- doc/en/user/source/community/taskmanager/user.rst
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/impl/ExternalKeycloakGSImpl.java
- src/community/taskmanager/core/src/test/java/org/geoserver/taskmanager/external/ExtTypesTest.java
- src/community/taskmanager/core/src/test/java/org/geoserver/taskmanager/tasks/FileRemotePublicationTaskTest.java
- src/community/taskmanager/core/src/test/resources/applicationContext.xml
- src/community/taskmanager/pom.xml
[![GEOS-11082](https://badgen.net/badge/JIRA/GEOS-11082/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11082) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11082] Taskmanager: keycloak support

- src/wms/src/main/java/org/geoserver/wms/svg/StreamingSVGMap.java
- src/wms/src/test/java/org/geoserver/wms/svg/SVGMapProducerTest.java
[![GEOS-11152](https://badgen.net/badge/JIRA/GEOS-11152/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11152) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
2.23.x backport for https://github.com/geoserver/geoserver/pull/7173
> [2.23.x][GEOS-11152] Improve handling special characters in the Simple SVG Renderer

- src/community/taskmanager/core/bin/pom.xml
- src/community/taskmanager/core/pom.xml
- src/main/pom.xml
- src/ows/pom.xml
- src/pom.xml
- src/wcs1_0/pom.xml
- src/wcs1_1/pom.xml
- src/web/app/pom.xml
[![GEOS-11219](https://badgen.net/badge/JIRA/GEOS-11219/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11219) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
PR upgrades mail and activation libs, see https://osgeo-org.atlassian.net/browse/GEOS-11219
Please see the issue for further information about this.
> [GEOS-11219] Upgrade mail and activation libs

- src/community/taskmanager/core/bin/pom.xml
- src/community/taskmanager/core/pom.xml
- src/main/pom.xml
- src/ows/pom.xml
- src/pom.xml
- src/wcs1_0/pom.xml
- src/wcs1_1/pom.xml
- src/web/app/pom.xml
[![GEOS-11219](https://badgen.net/badge/JIRA/GEOS-11219/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11219) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7302
**Authored by:** @awaterme
> [Backport 2.23.x] [GEOS-11219] Upgrade mail and activation libs

- src/community/taskmanager/core/bin/pom.xml
- src/community/taskmanager/core/pom.xml
- src/main/pom.xml
- src/ows/pom.xml
- src/pom.xml
- src/wcs1_0/pom.xml
- src/wcs1_1/pom.xml
- src/web/app/pom.xml
[![GEOS-11219](https://badgen.net/badge/JIRA/GEOS-11219/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11219) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7302
**Authored by:** @awaterme
> [Backport 2.24.x] [GEOS-11219] Upgrade mail and activation libs

- src/wfs/src/test/java/org/geoserver/wfs/remote/v2_0/WfsRemoteStoreTest.java
> [Backport 2.23.x] Updates following up GeoTools update to pass down max features to WFS 2.0 servers

- src/main/src/main/java/org/geoserver/GeoserverInitStartupListener.java
[![GEOS-11226](https://badgen.net/badge/JIRA/GEOS-11226/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11226) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11226] Enable JTS OverlayNG by default

- src/release/bin/startup.sh
[![GEOS-11224](https://badgen.net/badge/JIRA/GEOS-11224/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11224) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11224] startup.sh determine GEOSERVER_DATA_DIR absolute path

- src/release/bin/startup.sh
[![GEOS-11224](https://badgen.net/badge/JIRA/GEOS-11224/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11224) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7317
> [Backport 2.23.x] [GEOS-11224] startup.sh determine GEOSERVER_DATA_DIR absolute path

- src/release/bin/startup.sh
[![GEOS-11224](https://badgen.net/badge/JIRA/GEOS-11224/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11224) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7317
> [Backport 2.24.x] [GEOS-11224] startup.sh determine GEOSERVER_DATA_DIR absolute path

- src/community/flatgeobuf/pom.xml
Remove unnecessary dependency on `gs-web-core`  from community/flatgeobuf
> Remove gs-web-core dependency from community/flatgeobuf

- src/community/flatgeobuf/pom.xml
> [Backport 2.24.x] Remove gs-web-core dependency from community/flatgeobuf

- doc/en/user/source/geowebcache/config.rst
- doc/en/user/source/services/wps/hazelcast-clustering.rst
- src/community/hz-cluster/pom.xml
- src/community/hz-cluster/src/main/java/org/geoserver/cluster/hazelcast/HzCluster.java
- src/community/hz-cluster/src/main/resources/org/geoserver/cluster/hazelcast/hazelcast.xml
- src/extension/wps/wps-cluster-hazelcast/src/main/java/org/geoserver/wps/hz/HazelcastLoader.java
- src/extension/wps/wps-cluster-hazelcast/src/main/resources/org/geoserver/wps/hz/hazelcast.xml
- src/pom.xml
[![GEOS-11220](https://badgen.net/badge/JIRA/GEOS-11220/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11220) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR includes a dependency upgrade that contains security fixes and updates the modules using Hazelcast to work correctly after the last Hazelcast upgrade.
This PR is dependent on the GeoTools PR: https://github.com/geotools/geotools/pull/4579
> [GEOS-11220] Upgrade Hazelcast from 5.3.1 to 5.3.6

- doc/en/user/source/geowebcache/config.rst
- doc/en/user/source/services/wps/hazelcast-clustering.rst
- src/community/hz-cluster/pom.xml
- src/community/hz-cluster/src/main/java/org/geoserver/cluster/hazelcast/HzCluster.java
- src/community/hz-cluster/src/main/resources/org/geoserver/cluster/hazelcast/hazelcast.xml
- src/extension/wps/wps-cluster-hazelcast/src/main/java/org/geoserver/wps/hz/HazelcastLoader.java
- src/extension/wps/wps-cluster-hazelcast/src/main/resources/org/geoserver/wps/hz/hazelcast.xml
- src/pom.xml
[![GEOS-11220](https://badgen.net/badge/JIRA/GEOS-11220/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11220) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7309
> [Backport 2.24.x] [GEOS-11220] Upgrade Hazelcast from 5.3.1 to 5.3.6

- src/community/backup-restore/extension/src/main/resources/applicationContext.xml
- src/community/security/oauth2-geonode/src/main/resources/applicationContext.xml
- src/community/security/oauth2-github/src/main/resources/applicationContext.xml
- src/community/security/oauth2-google/src/main/resources/applicationContext.xml
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/resources/applicationContext.xml
- src/community/web-service-auth/src/main/java/applicationContext.xml
- src/extension/importer/rest/src/main/resources/applicationContext.xml
- src/extension/importer/web/src/main/resources/applicationContext.xml
- src/extension/wps/web-wps/src/main/resources/applicationContext.xml
- src/extension/wps/wps-cluster-hazelcast/src/main/java/applicationContext.xml
- src/extension/wps/wps-core/src/main/java/applicationContext.xml
- src/kml/src/main/java/applicationContext.xml
- src/main/src/main/java/applicationContext.xml
- src/security/jdbc/src/main/java/applicationContext.xml
- src/security/ldap/src/main/java/applicationContext.xml
- src/wcs/src/main/java/applicationContext.xml
- src/wcs1_0/src/main/java/applicationContext.xml
- src/wcs1_1/src/main/java/applicationContext.xml
- src/wcs2_0/src/main/java/applicationContext.xml
- src/web/core/src/main/java/applicationContext.xml
- src/web/demo/src/main/java/applicationContext.xml
- src/web/gwc/src/main/java/applicationContext.xml
- src/web/rest/src/main/java/applicationContext.xml
- src/web/security/core/src/main/java/applicationContext.xml
- src/web/security/jdbc/src/main/java/applicationContext.xml
- src/web/security/ldap/src/main/java/applicationContext.xml
- src/web/wcs/src/main/java/applicationContext.xml
- src/web/wfs/src/main/java/applicationContext.xml
- src/web/wms/src/main/java/applicationContext.xml
- src/wms/src/main/java/applicationContext.xml
Some beans of type `org.geoserver.platform.ModuleStatusImpl` defined in `applicationContext.xml` spring beans definition files aren't named.
Add `"id"="<beanName>"` in such cases.
> Add missing extension names to ModuleStatusImpl spring beans

- src/community/backup-restore/extension/src/main/resources/applicationContext.xml
- src/community/security/oauth2-geonode/src/main/resources/applicationContext.xml
- src/community/security/oauth2-github/src/main/resources/applicationContext.xml
- src/community/security/oauth2-google/src/main/resources/applicationContext.xml
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/resources/applicationContext.xml
- src/community/web-service-auth/src/main/java/applicationContext.xml
- src/extension/importer/rest/src/main/resources/applicationContext.xml
- src/extension/importer/web/src/main/resources/applicationContext.xml
- src/extension/wps/web-wps/src/main/resources/applicationContext.xml
- src/extension/wps/wps-cluster-hazelcast/src/main/java/applicationContext.xml
- src/extension/wps/wps-core/src/main/java/applicationContext.xml
- src/kml/src/main/java/applicationContext.xml
- src/main/src/main/java/applicationContext.xml
- src/security/jdbc/src/main/java/applicationContext.xml
- src/security/ldap/src/main/java/applicationContext.xml
- src/wcs/src/main/java/applicationContext.xml
- src/wcs1_0/src/main/java/applicationContext.xml
- src/wcs1_1/src/main/java/applicationContext.xml
- src/wcs2_0/src/main/java/applicationContext.xml
- src/web/core/src/main/java/applicationContext.xml
- src/web/demo/src/main/java/applicationContext.xml
- src/web/gwc/src/main/java/applicationContext.xml
- src/web/rest/src/main/java/applicationContext.xml
- src/web/security/core/src/main/java/applicationContext.xml
- src/web/security/jdbc/src/main/java/applicationContext.xml
- src/web/security/ldap/src/main/java/applicationContext.xml
- src/web/wcs/src/main/java/applicationContext.xml
- src/web/wfs/src/main/java/applicationContext.xml
- src/web/wms/src/main/java/applicationContext.xml
- src/wms/src/main/java/applicationContext.xml
> [Backport 2.24.x] Add missing extension names to ModuleStatusImpl spring beans

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/ConformanceClass.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/FeatureService.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/ConformanceTest.java
[![GEOS-11222](https://badgen.net/badge/JIRA/GEOS-11222/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11222) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Return Search conformance class within `conformance` resource.
> [GEOS-11222] Add Search conformance class

- doc/en/developer/source/installer/index.rst
> Update intro to windows installer instructions

- .github/workflows/linux.yml
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLControllerTest.java
- src/main/pom.xml
- src/main/src/test/java/org/geoserver/GeoServerNodeDataTest.java
- src/pom.xml
Updates to make the build pass with Java 21.
```bash
java -version
openjdk version "21" 2023-09-19 LTS
OpenJDK Runtime Environment Temurin-21+35 (build 21+35-LTS)
OpenJDK 64-Bit Server VM Temurin-21+35 (build 21+35-LTS, mixed mode, sharing)
```
So far only the core modules build, haven't run `-Prelease,communityRelease`
> Build with Java 21

- src/pom.xml
[![GEOS-11245](https://badgen.net/badge/JIRA/GEOS-11245/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11245) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11245] Update OSHI from 6.2.2 to 6.4.10

- src/pom.xml
[![GEOS-11245](https://badgen.net/badge/JIRA/GEOS-11245/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11245) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7333
> [Backport 2.24.x] [GEOS-11245] Update OSHI from 6.2.2 to 6.4.10

- doc/en/user/source/services/wms/vendor.rst
From GetCapabilitiesTransformer.java
> Clarify GetCapabilities format options

- src/community/schemaless-features/schemaless-core/src/main/java/org/geoserver/schemalessfeatures/type/DynamicComplexTypeImpl.java
[![GEOS-11246](https://badgen.net/badge/JIRA/GEOS-11246/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11246) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Changed DynamicComplexTypeImpl to search attributes in LinkedHashMap instead of ArrayList for Mongo schemaless plugin.
Attributes were searched in ArrayList using contains() method and added to the list if not found, while map attributes with the same key were overwritten using put(). This caused the list to contain many entries for the same attribute name, and searching through all of them.
For my particular use case (969 …
> [GEOS-11246] Schemaless plugin performance for WFS

- src/community/schemaless-features/schemaless-core/src/main/java/org/geoserver/schemalessfeatures/type/DynamicComplexTypeImpl.java
[![GEOS-11246](https://badgen.net/badge/JIRA/GEOS-11246/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11246) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7338
> [Backport 2.24.x] [GEOS-11246] Schemaless plugin performance for WFS

- src/community/schemaless-features/schemaless-core/src/main/java/org/geoserver/schemalessfeatures/type/DynamicComplexTypeImpl.java
[![GEOS-11246](https://badgen.net/badge/JIRA/GEOS-11246/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11246) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7338
> [Backport 2.23.x] [GEOS-11246] Schemaless plugin performance for WFS

- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdConnectIntegrationTest.java
- src/extension/authkey/src/test/java/org/geoserver/security/AuthKeyAuthenticationTest.java
- src/extension/authkey/src/test/java/org/geoserver/security/AuthenticationKeyOWSTest.java
- src/main/src/main/java/org/geoserver/security/GeoServerSecurityManager.java
- src/main/src/main/java/org/geoserver/security/validation/FilterConfigValidator.java
- src/main/src/test/java/org/geoserver/data/test/MockCreator.java
- src/security/security-tests/src/test/java/org/geoserver/security/GeoServerCustomFilterTest.java
- src/security/security-tests/src/test/java/org/geoserver/security/MigrateFrom_2_2_Test.java
- src/security/security-tests/src/test/java/org/geoserver/security/auth/AuthenticationFilterTest.java
- src/web/core/src/main/java/org/geoserver/web/GeoServerBasePage.java
- src/web/security/core/src/main/java/org/geoserver/security/web/auth/AuthenticationFiltersProvider.java
- src/web/security/core/src/main/java/org/geoserver/security/web/auth/AuthenticationPage.java
[![GEOS-11051](https://badgen.net/badge/JIRA/GEOS-11051/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11051) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7336
> [Backport 2.24.x] [GEOS-11051] Env parametrization does not save correctly in AuthKey extension

- src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/GeoServerKeycloakFilter.java
- src/community/security/keycloak/src/test/java/org/geoserver/web/security/keycloak/KeycloakLoginButtonTest.java
[![GEOS-10933](https://badgen.net/badge/JIRA/GEOS-10933/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10933) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7324
**Authored by:** @hwbllmnn
> [Backport 2.23.x] [GEOS-10933] Fix keycloak plugin logout

- src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/GeoServerKeycloakFilter.java
- src/community/security/keycloak/src/test/java/org/geoserver/web/security/keycloak/KeycloakLoginButtonTest.java
[![GEOS-10933](https://badgen.net/badge/JIRA/GEOS-10933/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10933) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7324
**Authored by:** @hwbllmnn
> [Backport 2.24.x] [GEOS-10933] Fix keycloak plugin logout

- src/restconfig/src/main/java/org/geoserver/rest/catalog/AbstractStoreUploadController.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/CoverageStoreFileController.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/DataStoreFileController.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/CoverageStoreFileUploadTest.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/DataStoreFileUploadTest.java
[![GEOS-11213](https://badgen.net/badge/JIRA/GEOS-11213/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11213) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
2.23.x backport for https://github.com/geoserver/geoserver/pull/7289
> [Backport 2.23.x][GEOS-11213] Improve REST external upload method unzipping

- doc/en/user/source/community/taskmanager/user.rst
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/data/impl/TaskManagerDaoImpl.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/ExternalGS.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/impl/ExternalGSImpl.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/tasks/MetadataSyncTaskTypeImpl.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/util/CatalogUtil.java
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/web/panel/bulk/BulkInitPanel.java
- src/community/taskmanager/core/src/test/java/org/geoserver/taskmanager/data/TaskManagerDataTest.java
- src/community/taskmanager/core/src/test/java/org/geoserver/taskmanager/tasks/MetaDataSyncTaskTest.java
- src/community/taskmanager/core/src/test/java/org/geoserver/taskmanager/web/BulkOperationsTest.java
- src/community/taskmanager/pom.xml
- src/extension/metadata/src/main/java/org/geoserver/metadata/data/service/impl/CustomNativeMappingServiceImpl.java
- src/extension/metadata/src/main/java/org/geoserver/metadata/rest/MetaDataRestService.java
- src/extension/metadata/src/test/java/org/geoserver/metadata/rest/MetaDataRestServiceTest.java
[![GEOS-11163](https://badgen.net/badge/JIRA/GEOS-11163/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11163) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11163] Taskmanager: support for metadata attributes sync

- src/extension/authkey/pom.xml
- src/pom.xml
backports #7358 to 2.24.x
* Bump com.jayway.jsonpath:json-path from 2.7.0 to 2.9.0 in /src
Bumps [com.jayway.jsonpath:json-path](https://github.com/jayway/JsonPath) from 2.7.0 to 2.9.0.
- [Release notes](https://github.com/jayway/JsonPath/releases)
- [Changelog](https://github.com/json-path/JsonPath/blob/master/changelog.md)
- [Commits](https://github.com/jayway/JsonPath/compare/json-path-2.7.0...json-path-2.9.0)
---
updated-dependencies:
- dependency-name: com.jayway.jsonpath:json-path dependency-type: direct:development ...
* Add scoped override for json-smart to override the runtime scope of the json-path provided version
---------
> [Backport 2.24.x]Bump com.jayway.jsonpath:json-path from 2.7.0 to 2.9.0 in /src (#7358)

- src/extension/authkey/pom.xml
- src/pom.xml
backports #7358 to 2.23.x
* Bump com.jayway.jsonpath:json-path from 2.7.0 to 2.9.0 in /src
Bumps [com.jayway.jsonpath:json-path](https://github.com/jayway/JsonPath) from 2.7.0 to 2.9.0.
- [Release notes](https://github.com/jayway/JsonPath/releases)
- [Changelog](https://github.com/json-path/JsonPath/blob/master/changelog.md)
- [Commits](https://github.com/jayway/JsonPath/compare/json-path-2.7.0...json-path-2.9.0)
---
updated-dependencies:
- dependency-name: com.jayway.jsonpath:json-path dependency-type: direct:development ...
* Add scoped override for json-smart to override the runtime scope of the json-path provided version
---------
> [Backport 2.23.x] Bump com.jayway.jsonpath:json-path from 2.7.0 to 2.9.0 in /src (#7358)

- src/extension/metadata/src/main/java/org/geoserver/metadata/web/panel/MetadataPanel.java
- src/extension/metadata/src/test/java/org/geoserver/metadata/data/service/ConfigurationServiceTest.java
- src/extension/metadata/src/test/java/org/geoserver/metadata/web/ConditionTest.java
- src/extension/metadata/src/test/java/org/geoserver/metadata/web/LayerMetadataTabTest.java
- src/extension/metadata/src/test/java/org/geoserver/metadata/web/TabsTest.java
- src/extension/metadata/src/test/resources/org/geoserver/metadata/metadata-ui.yaml
[![GEOS-11278](https://badgen.net/badge/JIRA/GEOS-11278/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11278) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11278] metadata: only selected tab is submitted

- src/ows/src/main/java/org/geoserver/ows/ClasspathPublisher.java
- src/ows/src/test/java/org/geoserver/ows/ClasspathPublisherTest.java
[![GEOS-11288](https://badgen.net/badge/JIRA/GEOS-11288/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11288) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7368
> [Backport 2.23.x] [GEOS-11288] Improve input validation in ClasspathPublisher

- src/ows/src/main/java/org/geoserver/ows/ClasspathPublisher.java
- src/ows/src/test/java/org/geoserver/ows/ClasspathPublisherTest.java
[![GEOS-11288](https://badgen.net/badge/JIRA/GEOS-11288/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11288) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7368
> [Backport 2.24.x] [GEOS-11288] Improve input validation in ClasspathPublisher

- doc/en/user/source/community/vector-mosaic/delegate.rst
Following up https://github.com/geotools/geotools/pull/4650
> Updating documentation for vector mosaic

- src/pom.xml
> [Backport 2.24.x] Bump org.springframework.security:spring-security-config from 5.7.10 to 5.7.11 in /src

- src/pom.xml
> [Backport 2.23.x] Bump org.springframework.security:spring-security-config from 5.7.10 to 5.7.11 in /src

- src/community/jms-cluster/activemqBroker/pom.xml
Reverts geoserver/geoserver#7374
> Revert "Bump org.springframework:spring-expression from 3.2.5.RELEASE to 5.2.23.RELEASE in /src/community/jms-cluster/activemqBroker"

- doc/en/user/source/installation/upgrade.rst
- doc/en/user/source/production/config.rst
- src/main/src/main/java/org/geoserver/security/GeoServerHttpFirewall.java
- src/main/src/main/java/org/geoserver/security/GeoServerSecurityFilterChainProxy.java
- src/main/src/test/java/org/geoserver/security/GeoServerHttpFirewallTest.java
- src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
[![GEOS-11289](https://badgen.net/badge/JIRA/GEOS-11289/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11289) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR enables using the StrictHttpFirewall by default and adds a system property to disable it.  See the ticket for additional details about this.
This PR may introduce backwards-compatibility issues for some users and should not be backported.
> [GEOS-11289] Enable Spring Security StrictHttpFirewall by default

- doc/en/user/source/extensions/mapml/index.rst
[![GEOS-11136](https://badgen.net/badge/JIRA/GEOS-11136/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11136) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Update MapML documentation to remove warning regarding performance.  The performance issue was solved in [this PR](https://github.com/geoserver/geoserver/pull/7370)
Documentation update only.
> Partially revert [GEOS-11136] - Remove gzip warning, add note to MapML extension documentation

- doc/en/user/source/filter/ecql_reference.rst
This page has not been updated to reflect changes in GeoTools [ECQL BNF](https://github.com/geotools/geotools/blob/main/modules/library/cql/ECQL.md).
> Clarification of ecql_reference description of IN predicate

- doc/en/user/source/filter/ecql_reference.rst
> [Backport 2.24.x] Clarification of ecql_reference description of IN predicate

- doc/en/user/source/filter/ecql_reference.rst
- doc/en/user/source/tutorials/cql/cql_tutorial.rst
Update documentation to reflect Stack Exchange and email list findings
https://gis.stackexchange.com/a/475826/68995
Replaces https://github.com/geoserver/geoserver/pull/7414
> Clarification of ecql_reference exception for attribute id

- doc/en/user/source/filter/ecql_reference.rst
- doc/en/user/source/tutorials/cql/cql_tutorial.rst
> [Backport 2.23.x] Clarification of ecql_reference exception for attribute id

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APISearchQuery.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/FeatureTest.java
[![GEOS-11301](https://badgen.net/badge/JIRA/GEOS-11301/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11301) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Streamlines the spelling of the `sortby` parameter for the `search` and `items` resources in the OGC API Plugin.
Please backport to 2.24.x, if possible.
> Streamline sort parameter spelling in "Search" OGC API - Features Part 5 proposal

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APISearchQuery.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/FeatureTest.java
Backport #7425
**Authored by:** @sebastianfrey
> [Backport 2.24.x] Streamline sort parameter spelling in "Search" OGC API - Features Part 5 proposal

- doc/en/user/source/extensions/metadata/uiconfiguration.rst
- src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/AttributeConfiguration.java
- src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/impl/AttributeConfigurationImpl.java
- src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/impl/CommaSeparatedDeserializer.java
- src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/impl/CommaSeperatedDeserializer.java
- src/extension/metadata/src/main/java/org/geoserver/metadata/web/panel/attribute/AttributeDataProvider.java
- src/extension/metadata/src/test/java/org/geoserver/metadata/web/TabsTest.java
- src/extension/metadata/src/test/resources/org/geoserver/metadata/metadata-ui.yaml
[![GEOS-11279](https://badgen.net/badge/JIRA/GEOS-11279/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11279) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> GEOS-11279 allow one field multiple tabs

- doc/en/user/source/extensions/metadata/uiconfiguration.rst
- src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/AttributeConfiguration.java
- src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/impl/AttributeConfigurationImpl.java
- src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/impl/CommaSeparatedDeserializer.java
- src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/impl/CommaSeperatedDeserializer.java
- src/extension/metadata/src/main/java/org/geoserver/metadata/web/panel/attribute/AttributeDataProvider.java
- src/extension/metadata/src/test/java/org/geoserver/metadata/web/TabsTest.java
- src/extension/metadata/src/test/resources/org/geoserver/metadata/metadata-ui.yaml
[![GEOS-11279](https://badgen.net/badge/JIRA/GEOS-11279/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11279) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7392
> [Backport 2.24.x] GEOS-11279 allow one field multiple tabs

- doc/en/user/source/extensions/metadata/uiconfiguration.rst
- src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/AttributeConfiguration.java
- src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/impl/AttributeConfigurationImpl.java
- src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/impl/CommaSeparatedDeserializer.java
- src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/impl/CommaSeperatedDeserializer.java
- src/extension/metadata/src/main/java/org/geoserver/metadata/web/panel/attribute/AttributeDataProvider.java
- src/extension/metadata/src/test/java/org/geoserver/metadata/web/TabsTest.java
- src/extension/metadata/src/test/resources/org/geoserver/metadata/metadata-ui.yaml
[![GEOS-11279](https://badgen.net/badge/JIRA/GEOS-11279/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11279) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7392
> [Backport 2.23.x] GEOS-11279 allow one field multiple tabs

- src/pom.xml
- src/wfs/src/main/java/org/geoserver/wfs/GetFeature.java
- src/wfs/src/main/java/org/geoserver/wfs/request/FeatureCollectionResponse.java
This required an update to apache-commons-lang3 covered by [GEOS-11307].
This issue is with respect to operating in Java 17 and Java 21 environments; relying on GitHub workflows to check regressions here (rather than new test cases).
> [GEOS-11306] API Fix for GetFeature lazy JDBC count(*) in Java 21 and Java 17

- src/pom.xml
- src/wfs/src/main/java/org/geoserver/wfs/GetFeature.java
- src/wfs/src/main/java/org/geoserver/wfs/request/FeatureCollectionResponse.java
> [Backport 2.24.x] [GEOS-11306] API Fix for GetFeature lazy JDBC count(*) in Java 21 and Java 17

- src/pom.xml
> Bump Spring version to 5.3.32

- doc/en/user/source/installation/upgrade.rst
- doc/en/user/source/production/config.rst
- src/main/src/main/java/org/geoserver/util/AllowListEntityResolver.java
- src/main/src/main/java/org/geoserver/util/EntityResolverProvider.java
- src/main/src/test/java/org/geoserver/util/EntityResolverProviderTest.java
[![GEOS-10438](https://badgen.net/badge/JIRA/GEOS-10438/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10438) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Updating the parsing to use sensible default and correct reported bug on handling of empty setting.
> [GEOS-10438] ENTITY_RESOLUTION_ALLOWLIST property not parsing empty setting

- src/web/app/src/main/webapp/WEB-INF/web.xml
[![GEOS-11315](https://badgen.net/badge/JIRA/GEOS-11315/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11315) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
clean
> [GEOS-11315] Revert to CORS commented out

- src/pom.xml
[![GEOS-11316](https://badgen.net/badge/JIRA/GEOS-11316/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11316) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7448
**Authored by:** @rpuhalsk
> [Backport 2.24.x] [GEOS-11316] Bump Spring version to 5.3.32

- src/pom.xml
[![GEOS-11316](https://badgen.net/badge/JIRA/GEOS-11316/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11316) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7448
**Authored by:** @rpuhalsk
> [Backport 2.23.x] [GEOS-11316] Bump Spring version to 5.3.32

- doc/en/user/source/extensions/csw-iso/index.rst
- doc/en/user/source/extensions/csw-iso/queryables.rst
- src/extension/csw/api/src/main/java/org/geoserver/csw/records/CSWRecordDescriptor.java
- src/extension/csw/api/src/main/java/org/geoserver/csw/records/RecordDescriptor.java
- src/extension/csw/api/src/main/java/org/geoserver/csw/store/AbstractCatalogStore.java
- src/extension/csw/api/src/main/java/org/geoserver/csw/store/CatalogStore.java
- src/extension/csw/api/src/test/java/org/geoserver/csw/records/AbstractCatalogStoreTest.java
- src/extension/csw/core/src/main/java/org/geoserver/csw/GetRecords.java
- src/extension/csw/core/src/main/java/org/geoserver/csw/store/internal/InternalCatalogStore.java
- src/extension/csw/csw-iso/src/main/java/org/geoserver/csw/records/iso/FeatureCatalogueDescriptor.java
- src/extension/csw/csw-iso/src/main/java/org/geoserver/csw/records/iso/MetaDataDescriptor.java
- src/extension/csw/csw-iso/src/main/java/org/geoserver/csw/records/iso/QueryableMappingFilterVisitor.java
- src/extension/csw/csw-iso/src/main/java/org/geoserver/csw/records/iso/QueryableMappingRecordDescriptor.java
- src/extension/csw/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/GetRecordsServiceIdTest.java
- src/extension/csw/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/GetRecordsTest.java
- src/extension/csw/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/MultipleMappingTest.java
- src/extension/csw/csw-iso/src/test/resources/org/geoserver/csw/store/internal/MD_Metadata.properties
- src/extension/csw/csw-iso/src/test/resources/org/geoserver/csw/store/internal/MD_Metadata.queryables.properties
- src/extension/csw/csw-iso/src/test/resources/org/geoserver/csw/store/internal/MD_Metadata.service.queryables.properties.ignore
[![GEOS-11266](https://badgen.net/badge/JIRA/GEOS-11266/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11266) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11266] csw-iso: support multiple paths mapped to queryable

- doc/en/user/source/extensions/csw-iso/index.rst
- doc/en/user/source/extensions/csw-iso/queryables.rst
- src/extension/csw/api/src/main/java/org/geoserver/csw/records/CSWRecordDescriptor.java
- src/extension/csw/api/src/main/java/org/geoserver/csw/records/RecordDescriptor.java
- src/extension/csw/api/src/main/java/org/geoserver/csw/store/AbstractCatalogStore.java
- src/extension/csw/api/src/main/java/org/geoserver/csw/store/CatalogStore.java
- src/extension/csw/api/src/test/java/org/geoserver/csw/records/AbstractCatalogStoreTest.java
- src/extension/csw/core/src/main/java/org/geoserver/csw/GetRecords.java
- src/extension/csw/core/src/main/java/org/geoserver/csw/store/internal/InternalCatalogStore.java
- src/extension/csw/csw-iso/src/main/java/org/geoserver/csw/records/iso/FeatureCatalogueDescriptor.java
- src/extension/csw/csw-iso/src/main/java/org/geoserver/csw/records/iso/MetaDataDescriptor.java
- src/extension/csw/csw-iso/src/main/java/org/geoserver/csw/records/iso/QueryableMappingFilterVisitor.java
- src/extension/csw/csw-iso/src/main/java/org/geoserver/csw/records/iso/QueryableMappingRecordDescriptor.java
- src/extension/csw/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/GetRecordsServiceIdTest.java
- src/extension/csw/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/GetRecordsTest.java
- src/extension/csw/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/MultipleMappingTest.java
- src/extension/csw/csw-iso/src/test/resources/org/geoserver/csw/store/internal/MD_Metadata.properties
- src/extension/csw/csw-iso/src/test/resources/org/geoserver/csw/store/internal/MD_Metadata.queryables.properties
- src/extension/csw/csw-iso/src/test/resources/org/geoserver/csw/store/internal/MD_Metadata.service.queryables.properties.ignore
[![GEOS-11266](https://badgen.net/badge/JIRA/GEOS-11266/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11266) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7431
> [Backport 2.24.x] [GEOS-11266] csw-iso: support multiple paths mapped to queryable

- doc/en/user/source/community/ogc-api/features/index.rst
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AbstractHTMLMessageConverter.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/AbstractMappingStore.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCProductFeatureStore.java
- src/community/oseo/oseo-core/src/test/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccessTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/CollectionLayersTest.java
- src/community/oseo/oseo-stac/src/test/resources/collection-layers.ftl
- src/community/oseo/oseo-stac/src/test/resources/item-collection-layers.ftl
- src/community/oseo/oseo-stac/src/test/resources/item-collection-layers.json
[![GEOS-11328](https://badgen.net/badge/JIRA/GEOS-11328/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11328) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11328] STAC: expose collection layers in products too, allow supporting the wms web-map-links extension

- doc/en/user/source/extensions/csw-iso/index.rst
- doc/en/user/source/extensions/csw-iso/queryables.rst
- src/extension/csw/api/src/main/java/org/geoserver/csw/records/CSWRecordDescriptor.java
- src/extension/csw/api/src/main/java/org/geoserver/csw/records/RecordDescriptor.java
- src/extension/csw/api/src/main/java/org/geoserver/csw/store/AbstractCatalogStore.java
- src/extension/csw/api/src/main/java/org/geoserver/csw/store/CatalogStore.java
- src/extension/csw/api/src/test/java/org/geoserver/csw/records/AbstractCatalogStoreTest.java
- src/extension/csw/core/src/main/java/org/geoserver/csw/GetRecords.java
- src/extension/csw/core/src/main/java/org/geoserver/csw/store/internal/InternalCatalogStore.java
- src/extension/csw/csw-iso/src/main/java/org/geoserver/csw/records/iso/FeatureCatalogueDescriptor.java
- src/extension/csw/csw-iso/src/main/java/org/geoserver/csw/records/iso/MetaDataDescriptor.java
- src/extension/csw/csw-iso/src/main/java/org/geoserver/csw/records/iso/QueryableMappingFilterVisitor.java
- src/extension/csw/csw-iso/src/main/java/org/geoserver/csw/records/iso/QueryableMappingRecordDescriptor.java
- src/extension/csw/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/GetRecordsServiceIdTest.java
- src/extension/csw/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/GetRecordsTest.java
- src/extension/csw/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/MultipleMappingTest.java
- src/extension/csw/csw-iso/src/test/resources/org/geoserver/csw/store/internal/MD_Metadata.properties
- src/extension/csw/csw-iso/src/test/resources/org/geoserver/csw/store/internal/MD_Metadata.queryables.properties
- src/extension/csw/csw-iso/src/test/resources/org/geoserver/csw/store/internal/MD_Metadata.service.queryables.properties.ignore
[![GEOS-11266](https://badgen.net/badge/JIRA/GEOS-11266/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11266) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7431
> [Backport 2.25.x] [GEOS-11266] csw-iso: support multiple paths mapped to queryable

- doc/en/user/source/community/ogc-api/features/index.rst
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AbstractHTMLMessageConverter.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/AbstractMappingStore.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCProductFeatureStore.java
- src/community/oseo/oseo-core/src/test/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccessTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/CollectionLayersTest.java
- src/community/oseo/oseo-stac/src/test/resources/collection-layers.ftl
- src/community/oseo/oseo-stac/src/test/resources/item-collection-layers.ftl
- src/community/oseo/oseo-stac/src/test/resources/item-collection-layers.json
[![GEOS-11328](https://badgen.net/badge/JIRA/GEOS-11328/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11328) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7460
> [Backport 2.24.x] [GEOS-11328] STAC: expose collection layers in products too, allow supporting the wms web-map-links extension

- doc/en/user/source/community/ogc-api/features/index.rst
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/AbstractHTMLMessageConverter.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/AbstractMappingStore.java
- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCProductFeatureStore.java
- src/community/oseo/oseo-core/src/test/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccessTest.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/CollectionLayersTest.java
- src/community/oseo/oseo-stac/src/test/resources/collection-layers.ftl
- src/community/oseo/oseo-stac/src/test/resources/item-collection-layers.ftl
- src/community/oseo/oseo-stac/src/test/resources/item-collection-layers.json
[![GEOS-11328](https://badgen.net/badge/JIRA/GEOS-11328/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11328) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7460
> [Backport 2.25.x] [GEOS-11328] STAC: expose collection layers in products too, allow supporting the wms web-map-links extension

- src/community/pom.xml
- src/community/release/ext-graticule.xml
[![GEOS-11216](https://badgen.net/badge/JIRA/GEOS-11216/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11216) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11216] make sure gt-grid is included in the graticule plugin 

- src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
- src/main/src/test/java/org/geoserver/config/util/XStreamPersisterTest.java
[![GEOS-11335](https://badgen.net/badge/JIRA/GEOS-11335/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11335) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
See ticket for details. Affects IAU and MapML authorities.
> [GEOS-11335] A layer in an authority other than EPSG may fail to reload after restart

- src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
- src/main/src/test/java/org/geoserver/config/util/XStreamPersisterTest.java
[![GEOS-11335](https://badgen.net/badge/JIRA/GEOS-11335/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11335) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7486
> [Backport 2.25.x] [GEOS-11335] A layer in an authority other than EPSG may fail to reload after restart

- src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
- src/main/src/test/java/org/geoserver/config/util/XStreamPersisterTest.java
[![GEOS-11335](https://badgen.net/badge/JIRA/GEOS-11335/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11335) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7486
> [Backport 2.24.x] [GEOS-11335] A layer in an authority other than EPSG may fail to reload after restart

- doc/en/user/source/datadirectory/index.rst
- src/web/security/core/src/main/java/org/geoserver/security/web/SecurityHomePageContentProvider$SecurityWarningsPanel.html
- src/web/security/core/src/main/java/org/geoserver/security/web/SecurityHomePageContentProvider.java
- src/web/security/core/src/main/resources/GeoServerApplication.properties
- src/web/security/core/src/test/java/org/geoserver/security/web/SecurityHomePageContentProviderTest.java
[![GEOS-11327](https://badgen.net/badge/JIRA/GEOS-11327/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11327) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7459
> [Backport 2.23.x] [GEOS-11327] Add warning about using embedded data directories

- doc/en/user/source/datadirectory/index.rst
- src/web/security/core/src/main/java/org/geoserver/security/web/SecurityHomePageContentProvider$SecurityWarningsPanel.html
- src/web/security/core/src/main/java/org/geoserver/security/web/SecurityHomePageContentProvider.java
- src/web/security/core/src/main/resources/GeoServerApplication.properties
- src/web/security/core/src/test/java/org/geoserver/security/web/SecurityHomePageContentProviderTest.java
[![GEOS-11327](https://badgen.net/badge/JIRA/GEOS-11327/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11327) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7459
> [Backport 2.24.x] [GEOS-11327] Add warning about using embedded data directories

- doc/en/user/source/datadirectory/index.rst
- src/web/security/core/src/main/java/org/geoserver/security/web/SecurityHomePageContentProvider$SecurityWarningsPanel.html
- src/web/security/core/src/main/java/org/geoserver/security/web/SecurityHomePageContentProvider.java
- src/web/security/core/src/main/resources/GeoServerApplication.properties
- src/web/security/core/src/test/java/org/geoserver/security/web/SecurityHomePageContentProviderTest.java
[![GEOS-11327](https://badgen.net/badge/JIRA/GEOS-11327/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11327) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7459
> [Backport 2.25.x] [GEOS-11327] Add warning about using embedded data directories

- doc/en/user/source/extensions/mapml/index.rst
- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLFeatureUtil.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLFeaturesBuilder.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLGenerator.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLGetFeatureInfoOutputFormat.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLGetFeatureOutputFormat.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLStyle.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLStyleVisitor.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/xml/Feature.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/xml/HeadContent.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLStyleVisitorTest.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSFeatureTest.java
- src/extension/mapml/src/test/resources/org/geoserver/mapml/lakeScale.sld
- src/extension/mapml/src/test/resources/org/geoserver/mapml/lineSymbolizer.sld
- src/extension/mapml/src/test/resources/org/geoserver/mapml/pointSymbolizer.sld
- src/extension/mapml/src/test/resources/org/geoserver/mapml/polygonFilter.sld
- src/extension/mapml/src/test/resources/org/geoserver/mapml/polygonOneFilter.sld
- src/extension/mapml/src/test/resources/org/geoserver/mapml/polygonSymbolizer.sld
- src/extension/mapml/src/test/resources/org/geoserver/mapml/simpleLineSymbolizer.sld
- src/extension/mapml/src/test/resources/org/geoserver/mapml/simplePointSymbolizer.sld
- src/extension/mapml/src/test/resources/org/geoserver/mapml/simplePolygonSymbolizer.sld
[![GEOS-11324](https://badgen.net/badge/JIRA/GEOS-11324/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11324) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [Geos-11324] MapML WMS Vector Representation Style Classes

- doc/en/user/source/community/features-autopopulate/index.rst
- doc/en/user/source/community/index.rst
- src/community/features-autopopulate/features-autopopulate-core/pom.xml
- src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTemplate.java
- src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTemplateLoader.java
- src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTransactionCallback.java
- src/community/features-autopopulate/features-autopopulate-core/src/main/resources/applicationContext.xml
- src/community/features-autopopulate/features-autopopulate-core/src/test/java/org/geoserver/autopopulate/AutopopulateTransactionCallbackTest.java
- src/community/features-autopopulate/features-autopopulate-core/src/test/java/org/geoserver/autopopulate/test-data/transactionCustomizer.properties
- src/community/features-autopopulate/pom.xml
- src/community/pom.xml
- src/community/release/ext-features-autopopulate.xml
- src/community/release/pom.xml
- src/web/app/pom.xml
> [Backport to 2.25.x][Community Plugin] Features-Autopopulate

- doc/en/user/source/community/features-autopopulate/index.rst
- doc/en/user/source/community/index.rst
- src/community/features-autopopulate/features-autopopulate-core/pom.xml
- src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTemplate.java
- src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTemplateLoader.java
- src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTransactionCallback.java
- src/community/features-autopopulate/features-autopopulate-core/src/main/resources/applicationContext.xml
- src/community/features-autopopulate/features-autopopulate-core/src/test/java/org/geoserver/autopopulate/AutopopulateTransactionCallbackTest.java
- src/community/features-autopopulate/features-autopopulate-core/src/test/java/org/geoserver/autopopulate/test-data/transactionCustomizer.properties
- src/community/features-autopopulate/pom.xml
- src/community/pom.xml
- src/community/release/ext-features-autopopulate.xml
- src/community/release/pom.xml
- src/web/app/pom.xml
> [Backport to 2.24.x][Community Plugin] Features-Autopopulate

- doc/en/user/source/community/features-autopopulate/index.rst
- doc/en/user/source/community/index.rst
- src/community/features-autopopulate/features-autopopulate-core/pom.xml
- src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTemplate.java
- src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTemplateLoader.java
- src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTransactionCallback.java
- src/community/features-autopopulate/features-autopopulate-core/src/main/resources/applicationContext.xml
- src/community/features-autopopulate/features-autopopulate-core/src/test/java/org/geoserver/autopopulate/AutopopulateTransactionCallbackTest.java
- src/community/features-autopopulate/features-autopopulate-core/src/test/java/org/geoserver/autopopulate/test-data/transactionCustomizer.properties
- src/community/features-autopopulate/pom.xml
- src/community/pom.xml
- src/community/release/ext-features-autopopulate.xml
- src/community/release/pom.xml
- src/web/app/pom.xml
> [Backport to 2.23.x][Community Plugin] Features-Autopopulate

- src/community/security/oauth2-geonode/src/test/java/org/geoserver/security/oauth2/GeoNodeLoginButtonTest.java
- src/community/security/oauth2-github/src/test/java/org/geoserver/security/oauth2/GitHubLoginButtonTest.java
- src/community/security/oauth2-google/src/test/java/org/geoserver/security/oauth2/GoogleLoginButtonTest.java
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OAuth2FilterConfigValidatorTest.java
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/test/java/org/geoserver/web/security/oauth2/OpenIdConnectLoginButtonTest.java
> [Community][OAUTH2] Fix auth2 login test cases

- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACService.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/ItemsTest.java
[![GEOS-11342](https://badgen.net/badge/JIRA/GEOS-11342/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11342) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11342] STAC should exclude items when the collection in path is  wrong

- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACService.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/ItemsTest.java
[![GEOS-11342](https://badgen.net/badge/JIRA/GEOS-11342/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11342) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7508
> [Backport 2.25.x] [GEOS-11342] STAC should exclude items when the collection in path is  wrong

- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACService.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/ConformanceTest.java
[![GEOS-11345](https://badgen.net/badge/JIRA/GEOS-11345/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11345) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11345] STAC Conformance URIs need to be updated

- doc/en/user/source/configuration/globalsettings.rst
- doc/en/user/source/configuration/index.rst
- doc/en/user/source/configuration/logging.rst
- doc/en/user/source/configuration/properties/index.rst
- doc/en/user/source/data/webadmin/layers.rst
- doc/en/user/source/production/config.rst
- doc/en/user/source/production/misc.rst
[![GEOS-11141](https://badgen.net/badge/JIRA/GEOS-11141/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11141) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Documentation update only, no functional change, providing context for some recent CVE feedback.
To support this guidance there is now a nice table of application properties donated from GeoCat documentation.
> [GEOS-11141] Provide context for use of environment variables and application properties

- doc/en/user/source/community/features-autopopulate/index.rst
> [Community][Feature Autopopulate] Minor documentation updates.

- src/pom.xml
[![GEOS-11362](https://badgen.net/badge/JIRA/GEOS-11362/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11362) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11362] Upgrade Spring libs from 5.3.32 to 5.3.33

- src/pom.xml
[![GEOS-11360](https://badgen.net/badge/JIRA/GEOS-11360/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11360) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11360] Upgrade Apache POI from 4.1.1 to 5.2.5

- src/pom.xml
[![GEOS-11360](https://badgen.net/badge/JIRA/GEOS-11360/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11360) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7537
> [Backport 2.24.x] [GEOS-11360] Upgrade Apache POI from 4.1.1 to 5.2.5

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/Link.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/OGCAPIMediaTypes.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACLandingPage.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/LandingPageTest.java
[![GEOS-11347](https://badgen.net/badge/JIRA/GEOS-11347/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11347) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11347] STAC Landing Page links should include root link

- src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTemplate.java
- src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTemplateLoader.java
- src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTransactionCallback.java
- src/community/features-autopopulate/features-autopopulate-core/src/test/java/org/geoserver/autopopulate/AutopopulateTransactionCallbackTest.java
[![GEOS-11358](https://badgen.net/badge/JIRA/GEOS-11358/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11358) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
References: https://osgeo-org.atlassian.net/browse/GEOS-11358
> [GEOS-11358] Feature-Autopopulate Update operation does not apply the Update Element filter

- src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTemplate.java
- src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTemplateLoader.java
- src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTransactionCallback.java
- src/community/features-autopopulate/features-autopopulate-core/src/test/java/org/geoserver/autopopulate/AutopopulateTransactionCallbackTest.java
[![GEOS-11358](https://badgen.net/badge/JIRA/GEOS-11358/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11358) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
* [GEOS-11358] Feature-Autopopulate Update operation does not apply the Update Element filter
* - Update jdoc and test case
* - Get rid of heavy loggers
* - Make sure the ecql expression are evaluated each time
* - Search for the user into the SecurityContext if not able to find him on the local env
* - Removing unneeded lop
* - Make sure we correctly handle the FeatureCollection iterator
(cherry picked from commit …
> [Backport to 2.23.x][GEOS-11358] Feature-Autopopulate Update operation does not apply the Update Element filter

- src/wfs/src/main/java/org/geoserver/wfs/GetFeature.java
This addresses a regression that was introduded with API change to avoid calculating total for formats that do not require such a value.
> [GEOS-11306] Chace GetFeature total using AtomicLong for thread safety

- src/wfs/src/main/java/org/geoserver/wfs/GetFeature.java
> [Backport 2.24.x] [GEOS-11306] Chace GetFeature total using AtomicLong for thread safety

- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java
- src/main/src/main/java/org/geoserver/security/filter/GeoServerPreAuthenticatedUserNameFilter.java
[![GEOS-11331](https://badgen.net/badge/JIRA/GEOS-11331/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11331) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
The changes is two-folded.
- Changing the exception message so that it might give some more clue.
- Avoid the exception for OpenID plugin, by returning null and log a warning message.
> [GEOS-11331] OAuth2 can throw a " java.lang.RuntimeException: Never should reach this point"

- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java
- src/main/src/main/java/org/geoserver/security/filter/GeoServerPreAuthenticatedUserNameFilter.java
[![GEOS-11331](https://badgen.net/badge/JIRA/GEOS-11331/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11331) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7551
> [Backport 2.23.x] [GEOS-11331] OAuth2 can throw a " java.lang.RuntimeException: Never should reach this point"

- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java
- src/main/src/main/java/org/geoserver/security/filter/GeoServerPreAuthenticatedUserNameFilter.java
[![GEOS-11331](https://badgen.net/badge/JIRA/GEOS-11331/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11331) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7551
> [Backport 2.24.x] [GEOS-11331] OAuth2 can throw a " java.lang.RuntimeException: Never should reach this point"

- src/pom.xml
[![GEOS-11374](https://badgen.net/badge/JIRA/GEOS-11374/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11374) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7567
> [Backport 2.24.x] [GEOS-11374] Upgrade Spring version from 5.3.33 to 5.3.34

- src/pom.xml
[![GEOS-11374](https://badgen.net/badge/JIRA/GEOS-11374/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11374) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7567
> [Backport 2.25.x] [GEOS-11374] Upgrade Spring version from 5.3.33 to 5.3.34

- doc/en/developer/source/policies/committing.rst
[![GEOS-11375](https://badgen.net/badge/JIRA/GEOS-11375/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11375) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
A quick update to reflect GeoServer commit access is granted to individuals (not a group or company).
> [GEOS-11375] GSIP 224 - Individual contributor clarification

- doc/en/developer/source/policies/committing.rst
[![GEOS-11375](https://badgen.net/badge/JIRA/GEOS-11375/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11375) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7575
> [Backport 2.24.x] [GEOS-11375] GSIP 224 - Individual contributor clarification

- doc/en/developer/source/policies/committing.rst
[![GEOS-11375](https://badgen.net/badge/JIRA/GEOS-11375/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11375) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7575
> [Backport 2.25.x] [GEOS-11375] GSIP 224 - Individual contributor clarification

- src/web/core/src/main/java/org/geoserver/web/system/status/ConsoleInfoUtils.java
- src/web/core/src/test/java/org/geoserver/web/system/status/ConsoleInfoUtilsStackTest.java
[![GEOS-11311](https://badgen.net/badge/JIRA/GEOS-11311/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11311) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7562
> [Backport 2.23.x] [GEOS-11311] Show a full stack trace in the JVM stack dump panel

- src/web/core/src/main/java/org/geoserver/web/system/status/ConsoleInfoUtils.java
- src/web/core/src/test/java/org/geoserver/web/system/status/ConsoleInfoUtilsStackTest.java
[![GEOS-11311](https://badgen.net/badge/JIRA/GEOS-11311/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11311) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7562
> [Backport 2.24.x] [GEOS-11311] Show a full stack trace in the JVM stack dump panel

- src/web/core/src/main/java/org/geoserver/web/system/status/ConsoleInfoUtils.java
- src/web/core/src/test/java/org/geoserver/web/system/status/ConsoleInfoUtilsStackTest.java
[![GEOS-11311](https://badgen.net/badge/JIRA/GEOS-11311/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11311) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7562
> [Backport 2.25.x] [GEOS-11311] Show a full stack trace in the JVM stack dump panel

- src/main/src/main/java/org/geoserver/catalog/WMSStoreInfo.java
- src/main/src/main/java/org/geoserver/catalog/WMTSStoreInfo.java
Fixes broken build from https://github.com/geoserver/geoserver/pull/7552
> Fix PMD MissingOverride

- src/main/src/main/java/org/geoserver/catalog/WMSStoreInfo.java
- src/main/src/main/java/org/geoserver/catalog/WMTSStoreInfo.java
> Backport 7552 to 2.25.x

- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java
[![GEOS-11381](https://badgen.net/badge/JIRA/GEOS-11381/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11381) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7586
**Authored by:** @MarquesDeAzevedo
> [Backport 2.25.x] [GEOS-11381] Fix error in OIDC plugin in combination with RoleService

- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java
[![GEOS-11381](https://badgen.net/badge/JIRA/GEOS-11381/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11381) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7586
**Authored by:** @MarquesDeAzevedo
> [Backport 2.23.x] [GEOS-11381] Fix error in OIDC plugin in combination with RoleService

- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
> [Backport 2.23.x] GeoFence: minor log level change

- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
> [Backport 2.24.x] GeoFence: minor log level change

- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
> [Backport 2.25.x] GeoFence: minor log level change

- doc/en/developer/source/policies/community-modules.rst
[![GEOS-11386](https://badgen.net/badge/JIRA/GEOS-11386/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11386) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
The current graduation rules require having a handful of users as a way to make sure the module is general enough. This proposal amends the rule wording to indicate the intent, rather than the a way to confirm generality.
See proposal https://github.com/geoserver/geoserver/wiki/GSIP-223 by @aaime 
> [GEOS-11386] GSIP-223 Community module graduation, amending generality rule

- src/pom.xml
[![GEOS-11388](https://badgen.net/badge/JIRA/GEOS-11388/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11388) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7604
> [Backport 2.25.x] [GEOS-11388] Update ImageIO-EXT to 1.4.10

- doc/en/api/1.0.0/rat.yaml
- src/extension/rat/src/main/java/org/geoserver/rat/rest/PAMController.java
- src/extension/rat/src/test/java/org/geoserver/rat/rest/PAMControllerTest.java
- src/extension/rat/src/test/resources/org/geoserver/rat/web/rat.tiff.aux2.xml
[![GEOS-11377](https://badgen.net/badge/JIRA/GEOS-11377/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11377) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7583
> [Backport 2.25.x] [GEOS-11377] RAT module: allow to reload/recompute the RAT

- src/extension/csw/core/src/test/java/org/geoserver/csw/GetCapabilitiesTest.java
- src/main/src/main/java/org/geoserver/ows/CiteComplianceHack.java
- src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
- src/ows/src/test/java/org/geoserver/ows/DispatcherTest.java
- src/wfs/src/main/java/applicationContext.xml
- src/wfs/src/test/java/org/geoserver/wfs/GetFeatureTest.java
- src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetCapabilitiesTest.java
- src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetCapabilitiesTest.java
- src/wms/src/main/java/applicationContext.xml
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesSystemTest.java
[![GEOS-11382](https://badgen.net/badge/JIRA/GEOS-11382/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11382) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Fixes: https://osgeo-org.atlassian.net/browse/GEOS-11382
> [GEOS-11382] The interceptor "CiteComplianceHack" never gets invoked by the Dispatcher Servlet

- src/extension/csw/core/src/test/java/org/geoserver/csw/GetCapabilitiesTest.java
- src/main/src/main/java/org/geoserver/ows/CiteComplianceHack.java
- src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
- src/ows/src/test/java/org/geoserver/ows/DispatcherTest.java
- src/wfs/src/main/java/applicationContext.xml
- src/wfs/src/test/java/org/geoserver/wfs/GetFeatureTest.java
- src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetCapabilitiesTest.java
- src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetCapabilitiesTest.java
- src/wms/src/main/java/applicationContext.xml
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesSystemTest.java
[![GEOS-11382](https://badgen.net/badge/JIRA/GEOS-11382/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11382) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7590
> [Backport 2.25.x] [GEOS-11382] The interceptor "CiteComplianceHack" never gets invoked by the Dispatcher Servlet

- src/extension/csw/core/src/test/java/org/geoserver/csw/GetCapabilitiesTest.java
- src/main/src/main/java/org/geoserver/ows/CiteComplianceHack.java
- src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
- src/ows/src/test/java/org/geoserver/ows/DispatcherTest.java
- src/wfs/src/main/java/applicationContext.xml
- src/wfs/src/test/java/org/geoserver/wfs/GetFeatureTest.java
- src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetCapabilitiesTest.java
- src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetCapabilitiesTest.java
- src/wms/src/main/java/applicationContext.xml
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesSystemTest.java
[![GEOS-11382](https://badgen.net/badge/JIRA/GEOS-11382/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11382) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7590
> [Backport 2.24.x] [GEOS-11382] The interceptor "CiteComplianceHack" never gets invoked by the Dispatcher Servlet

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/MaxSizeInputStream.java
- src/pom.xml
[![GEOS-11393](https://badgen.net/badge/JIRA/GEOS-11393/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11393) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR is just a regular dependency upgrade. The code change removes using the deprecated CountingInputStream class and is covered by multiple existing unit tests.
> [GEOS-11393] Upgrade commons-io from 2.12.0 to 2.16.1

- src/pom.xml
[![GEOS-11395](https://badgen.net/badge/JIRA/GEOS-11395/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11395) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11395] Upgrade guava from 32.0.0 to 33.2.0

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/MaxSizeInputStream.java
- src/pom.xml
[![GEOS-11393](https://badgen.net/badge/JIRA/GEOS-11393/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11393) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7618
> [Backport 2.24.x] [GEOS-11393] Upgrade commons-io from 2.12.0 to 2.16.1

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/MaxSizeInputStream.java
- src/pom.xml
[![GEOS-11393](https://badgen.net/badge/JIRA/GEOS-11393/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11393) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7618
> [Backport 2.25.x] [GEOS-11393] Upgrade commons-io from 2.12.0 to 2.16.1

- src/community/release/ext-oauth2-openid-connect.xml
- src/community/security/keycloak/pom.xml
- src/community/security/oauth2-geonode/pom.xml
- src/community/security/oauth2-github/pom.xml
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml
- src/community/security/oauth2/oauth2-core/pom.xml
- src/pom.xml
> [Backport 2.24.x] Removing unecessary jackson-mapper-asl dependency

- src/gwc/pom.xml
> [Backport 2.25.x] Avoid wanings about IAU missing in GWC test logs

- src/extension/security/cas/src/main/java/org/geoserver/security/cas/GeoServerCasAuthenticationFilter.java
- src/extension/security/cas/src/test/java/org/geoserver/security/cas/GeoServerCasAuthenticationFilterTest.java
[![GEOS-11202](https://badgen.net/badge/JIRA/GEOS-11202/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11202) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7571
**Authored by:** @mbosecke
> [Backport 2.24.x] [GEOS-11202] Respect proxy base URL when building CAS service URL.

- src/extension/security/cas/src/main/java/org/geoserver/security/cas/GeoServerCasAuthenticationFilter.java
- src/extension/security/cas/src/test/java/org/geoserver/security/cas/GeoServerCasAuthenticationFilterTest.java
[![GEOS-11202](https://badgen.net/badge/JIRA/GEOS-11202/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11202) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7571
**Authored by:** @mbosecke
> [Backport 2.25.x] [GEOS-11202] Respect proxy base URL when building CAS service URL.

- src/platform/src/main/java/org/geoserver/util/IOUtils.java
- src/platform/src/test/java/org/geoserver/util/IOUtilsTest.java
[![GEOS-11332](https://badgen.net/badge/JIRA/GEOS-11332/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11332) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7580
> [Backport 2.24.x] [GEOS-11332] Renaming style with uppercase/downcase empty the sld file

- src/platform/src/main/java/org/geoserver/util/IOUtils.java
- src/platform/src/test/java/org/geoserver/util/IOUtilsTest.java
[![GEOS-11332](https://badgen.net/badge/JIRA/GEOS-11332/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11332) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7580
> [Backport 2.25.x] [GEOS-11332] Renaming style with uppercase/downcase empty the sld file

- src/pom.xml
[![GEOS-11403](https://badgen.net/badge/JIRA/GEOS-11403/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11403) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11403] Upgrade commons-text from 1.10.0 to 1.12.0

- src/pom.xml
[![GEOS-11404](https://badgen.net/badge/JIRA/GEOS-11404/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11404) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11404] Upgrade commons-codec from 1.15 to 1.17.0

- src/pom.xml
[![GEOS-11402](https://badgen.net/badge/JIRA/GEOS-11402/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11402) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7643
> [Backport 2.24.x] [GEOS-11402] Upgrade PostgreSQL driver from 42.7.2 to 42.7.3

- src/pom.xml
[![GEOS-11402](https://badgen.net/badge/JIRA/GEOS-11402/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11402) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7643
> [Backport 2.25.x] [GEOS-11402] Upgrade PostgreSQL driver from 42.7.2 to 42.7.3

- src/pom.xml
[![GEOS-11403](https://badgen.net/badge/JIRA/GEOS-11403/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11403) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7644
> [Backport 2.24.x] [GEOS-11403] Upgrade commons-text from 1.10.0 to 1.12.0

- src/pom.xml
[![GEOS-11403](https://badgen.net/badge/JIRA/GEOS-11403/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11403) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7644
> [Backport 2.25.x] [GEOS-11403] Upgrade commons-text from 1.10.0 to 1.12.0

- src/pom.xml
[![GEOS-11404](https://badgen.net/badge/JIRA/GEOS-11404/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11404) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7645
> [Backport 2.24.x] [GEOS-11404] Upgrade commons-codec from 1.15 to 1.17.0

- src/pom.xml
[![GEOS-11404](https://badgen.net/badge/JIRA/GEOS-11404/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11404) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7645
> [Backport 2.25.x] [GEOS-11404] Upgrade commons-codec from 1.15 to 1.17.0

- src/pom.xml
[![GEOS-11407](https://badgen.net/badge/JIRA/GEOS-11407/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11407) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7664
> [Backport 2.24.x] [GEOS-11407] Upgrade jackson from 2.15.2 to 2.17.1

- src/pom.xml
[![GEOS-11407](https://badgen.net/badge/JIRA/GEOS-11407/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11407) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7664
> [Backport 2.25.x] [GEOS-11407] Upgrade jackson from 2.15.2 to 2.17.1

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/xml/v1_0_0/WpsXmlReader.java
- src/ows/src/main/java/org/geoserver/ows/XmlRequestReader.java
- src/ows/src/test/java/org/geoserver/ows/DispatcherTest.java
- src/ows/src/test/java/org/geoserver/ows/MessageXmlParser.java
- src/wcs1_0/src/main/java/org/geoserver/wcs/xml/v1_0_0/WcsXmlReader.java
- src/wcs1_1/src/main/java/org/geoserver/wcs/xml/v1_1_1/WcsXmlReader.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/xml/WcsXmlReader.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v1_0_0/WfsXmlReader.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v1_1_0/WfsXmlReader.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v2_0/WfsXmlReader.java
- src/wfs/src/test/java/org/geoserver/wfs/ExternalEntitiesTest.java
- src/wms/src/main/java/org/geoserver/sld/SLDXmlRequestReader.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/CapabilitiesXmlReader.java
- src/wms/src/main/java/org/geoserver/wms/map/GetMapXmlReader.java
- src/wms/src/test/java/org/geoserver/wms/map/GetMapXmlReaderTest.java
- src/wms/src/test/resources/org/geoserver/wms/map/WMSPostServiceException.xml
[![GEOS-11408](https://badgen.net/badge/JIRA/GEOS-11408/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11408) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
WCS does a nice job of creating a helpful message, rather than a generic IO exception. This PR makes a similar improvement for the other XmlRequestReaders.
This provides a small API change, an additional utility method in XmlRequestReader that the subclasses can use to process an exception prior to use in SecurityException constructor.
> [GEOS-11408] XmlRequestReader clean generic XML request parsing exceptions

- src/main/src/main/java/org/geoserver/config/GeoServerInfo.java
- src/main/src/main/java/org/geoserver/config/impl/GeoServerInfoImpl.java
- src/main/src/main/java/org/geoserver/util/AllowListEntityResolver.java
- src/main/src/main/java/org/geoserver/util/EntityResolverProvider.java
- src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
- src/main/src/test/java/org/geoserver/util/EntityResolverProviderTest.java
It is great with the 2.25.0 release people are using ENTITY_RESOLUTION_ALLOWLIST. This PR gathers some feedback and clarifications in response to public use.
> [GEOS-11398] Javadoc clarification and test cases for Entity Resolution

- src/main/src/main/java/org/geoserver/config/GeoServerInfo.java
- src/main/src/main/java/org/geoserver/config/impl/GeoServerInfoImpl.java
- src/main/src/main/java/org/geoserver/util/AllowListEntityResolver.java
- src/main/src/main/java/org/geoserver/util/EntityResolverProvider.java
- src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
- src/main/src/test/java/org/geoserver/util/EntityResolverProviderTest.java
> [Backport 2.25.x] [GEOS-11398] Javadoc clarification and test cases for Entity Resolution

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/xml/v1_0_0/WpsXmlReader.java
- src/ows/src/main/java/org/geoserver/ows/XmlRequestReader.java
- src/ows/src/test/java/org/geoserver/ows/DispatcherTest.java
- src/ows/src/test/java/org/geoserver/ows/MessageXmlParser.java
- src/wcs1_0/src/main/java/org/geoserver/wcs/xml/v1_0_0/WcsXmlReader.java
- src/wcs1_1/src/main/java/org/geoserver/wcs/xml/v1_1_1/WcsXmlReader.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/xml/WcsXmlReader.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v1_0_0/WfsXmlReader.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v1_1_0/WfsXmlReader.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v2_0/WfsXmlReader.java
- src/wfs/src/test/java/org/geoserver/wfs/ExternalEntitiesTest.java
- src/wms/src/main/java/org/geoserver/sld/SLDXmlRequestReader.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/CapabilitiesXmlReader.java
- src/wms/src/main/java/org/geoserver/wms/map/GetMapXmlReader.java
- src/wms/src/test/java/org/geoserver/wms/map/GetMapXmlReaderTest.java
- src/wms/src/test/resources/org/geoserver/wms/map/WMSPostServiceException.xml
[![GEOS-11408](https://badgen.net/badge/JIRA/GEOS-11408/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11408) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7669
> [Backport 2.25.x] [GEOS-11408] XmlRequestReader clean generic XML request parsing exceptions

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/xml/v1_0_0/WpsXmlReader.java
- src/ows/src/main/java/org/geoserver/ows/XmlRequestReader.java
- src/ows/src/test/java/org/geoserver/ows/DispatcherTest.java
- src/ows/src/test/java/org/geoserver/ows/MessageXmlParser.java
- src/wcs1_0/src/main/java/org/geoserver/wcs/xml/v1_0_0/WcsXmlReader.java
- src/wcs1_1/src/main/java/org/geoserver/wcs/xml/v1_1_1/WcsXmlReader.java
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/xml/WcsXmlReader.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v1_0_0/WfsXmlReader.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v1_1_0/WfsXmlReader.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v2_0/WfsXmlReader.java
- src/wfs/src/test/java/org/geoserver/wfs/ExternalEntitiesTest.java
- src/wms/src/main/java/org/geoserver/sld/SLDXmlRequestReader.java
- src/wms/src/main/java/org/geoserver/wms/capabilities/CapabilitiesXmlReader.java
- src/wms/src/main/java/org/geoserver/wms/map/GetMapXmlReader.java
- src/wms/src/test/java/org/geoserver/wms/map/GetMapXmlReaderTest.java
- src/wms/src/test/resources/org/geoserver/wms/map/WMSPostServiceException.xml
[![GEOS-11408](https://badgen.net/badge/JIRA/GEOS-11408/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11408) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7669
> [Backport 2.24.x] [GEOS-11408] XmlRequestReader clean generic XML request parsing exceptions

- src/main/src/test/java/org/geoserver/util/EntityResolverProviderTest.java
Forward port additional test case clarifications from https://github.com/geoserver/geoserver/pull/7678
This way both PreventLocalEntityResolver and AllowListEntityResolver are tested (rather than just the default).
> [GEOS-11398] Additional entityResolverProviderTest checks

- src/release/war.xml
Noticed while checking 2.25.1 download artifacts
> war bundle has license and licenses folder

- src/pom.xml
[![GEOS-11411](https://badgen.net/badge/JIRA/GEOS-11411/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11411) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11411] Upgrade to ImageIO-EXT 1.4.11

- doc/en/user/source/extensions/rat/index.rst
- doc/en/user/source/extensions/rat/installing.rst
- doc/en/user/source/extensions/rat/using.rst
> Update rat .rst

- src/release/war.xml
> [Backport 2.25.x] war bundle has license and licenses folder

- src/platform/src/main/java/org/geoserver/platform/GeoServerResourceLoader.java
Fixes: [storage.DefaultStorageFinder] - Found system environment variableGEOSERVER_DATA_DIR set to
> Add space between type and variable

- src/pom.xml
[![GEOS-11411](https://badgen.net/badge/JIRA/GEOS-11411/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11411) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7683
> [Backport 2.25.x] [GEOS-11411] Upgrade to ImageIO-EXT 1.4.11

- src/release/war.xml
> [Backport 2.24.x] war bundle has license and licenses folder

- src/community/jms-cluster/jms-geoserver/pom.xml
- src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/DocumentFile.java
[![GEOS-11412](https://badgen.net/badge/JIRA/GEOS-11412/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11412) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
These references to JDOMException are unnecessary, and might be the cause of the error I experienced.
By removing these references from the code, I was also able to erase the dependency to org.jdom:jdom2 from the pom.xml.
> [GEOS-11412] JMS failure because of missing JDOM jar

- src/community/jms-cluster/jms-geoserver/pom.xml
- src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/DocumentFile.java
[![GEOS-11412](https://badgen.net/badge/JIRA/GEOS-11412/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11412) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7693
> [Backport 2.24.x] [GEOS-11412] JMS failure because of missing JDOM jar

- src/community/jms-cluster/jms-geoserver/pom.xml
- src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/DocumentFile.java
[![GEOS-11412](https://badgen.net/badge/JIRA/GEOS-11412/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11412) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7693
> [Backport 2.22.x] [GEOS-11412] JMS failure because of missing JDOM jar

- src/community/jms-cluster/jms-geoserver/pom.xml
- src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/DocumentFile.java
[![GEOS-11412](https://badgen.net/badge/JIRA/GEOS-11412/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11412) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7693
> [Backport 2.25.x] [GEOS-11412] JMS failure because of missing JDOM jar

- src/community/release/ext-datadir-catalog-loader.xml
> Fix typo in datadir-catalog-loader release descriptor (s/dataird/datadir/g)

- src/main/src/main/java/org/geoserver/ows/CiteComplianceHack.java
- src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesSystemTest.java
[![GEOS-11430](https://badgen.net/badge/JIRA/GEOS-11430/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11430) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7711
> [Backport 2.25.x] [GEOS-11430] CiteComplianceHack not correctly parsing the context

- src/main/src/main/java/org/geoserver/ows/CiteComplianceHack.java
- src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
- src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesSystemTest.java
[![GEOS-11430](https://badgen.net/badge/JIRA/GEOS-11430/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11430) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7711
> [Backport 2.24.x] [GEOS-11430] CiteComplianceHack not correctly parsing the context

- doc/en/user/source/gettingstarted/web-admin-quickstart/index.rst
- src/main/src/main/java/org/geoserver/catalog/Predicates.java
- src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java
- src/web/core/src/main/java/org/geoserver/web/wicket/GeoServerDataProvider.java
- src/web/core/src/main/java/org/geoserver/web/wicket/GeoServerTablePanel.html
- src/web/core/src/main/resources/GeoServerApplication.properties
- src/web/core/src/main/resources/GeoServerApplication_it.properties
- src/web/core/src/test/java/org/geoserver/web/wicket/GeoServerDataProviderTest.java
[![GEOS-11351](https://badgen.net/badge/JIRA/GEOS-11351/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11351) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7615
Authored by: @axl8713
> [Backport 2.25.x] [GEOS-11351] Exact term search in the pages' filters

- doc/en/user/source/security/tutorials/activedirectory/index.rst
Backport #7717
**Authored by:** @rob518183
> [Backport 2.25.x] Update tutorials/activedirectory/index.rst

- src/pom.xml
[![GEOS-11432](https://badgen.net/badge/JIRA/GEOS-11432/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11432) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11432] Upgrade to ImageIO-EXT 1.4.12

- src/pom.xml
[![GEOS-11432](https://badgen.net/badge/JIRA/GEOS-11432/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11432) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7719
> [Backport 2.25.x] [GEOS-11432] Upgrade to ImageIO-EXT 1.4.12

- src/extension/wps/web-wps/src/main/java/org/geoserver/wps/web/WPSRequestBuilder.java
- src/web/demo/src/main/java/org/geoserver/web/demo/DemoRequestsPage.java
- src/web/wcs/src/main/java/org/geoserver/wcs/web/demo/WCSRequestBuilder.java
[![GEOS-11390](https://badgen.net/badge/JIRA/GEOS-11390/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11390) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This is a follow-up to PR https://github.com/geoserver/geoserver/pull/7672
There were some CSS issues with custom themes - the issue appears to be in the custom #renderHeader().
This PR changes it so it calls `super.renderHeader()`, then add the custom JS.  This ensures the standard wicket headers are correctly written.
- [n/a] [Documentation](https://github.com/geoserver/geoserver/tree/main/d …
> [GEOS-11390] Replace TestWfsPost with Javascript Demo Page

- src/extension/wps/web-wps/src/main/java/org/geoserver/wps/web/WPSRequestBuilder.java
- src/web/demo/src/main/java/org/geoserver/web/demo/DemoRequestsPage.java
- src/web/wcs/src/main/java/org/geoserver/wcs/web/demo/WCSRequestBuilder.java
[![GEOS-11390](https://badgen.net/badge/JIRA/GEOS-11390/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11390) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7721
**Authored by:** @davidblasby
> [Backport 2.25.x] [GEOS-11390] Replace TestWfsPost with Javascript Demo Page

- src/main/src/main/java/org/geoserver/security/SecureCatalogImpl.java
- src/security/security-tests/src/test/java/org/geoserver/ows/LocalWorkspaceSecureCatalogTest.java
[![GEOS-11423](https://badgen.net/badge/JIRA/GEOS-11423/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11423) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Make `SecureCatalogImpl.getXXX():List` methods defer to `list(Class, Filter.INCLUDE):CloseableIterator`
so the security filter is passed down to the catalog facade and avoid loading all objects.
> [GEOS-11423] Use securityFilter in SecureCatalogImpl bulk get methods

- src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/gstore/DGGSGeometryFeatureSource.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/CollectionTest.java
Quick fix for a test, to re-establish a fully building baseline.
> Making all OGC API tests pass

- src/main/src/main/java/org/geoserver/security/ResourceAccessManager.java
- src/web/core/src/main/java/org/geoserver/web/WorkspaceAdminComponentAuthorizer.java
- src/web/core/src/test/java/org/geoserver/web/WorkspaceAdminComponentAuthorizerTest.java
[![GEOS-11424](https://badgen.net/badge/JIRA/GEOS-11424/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11424) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7704
> [Backport 2.25.x] [GEOS-11424] Speed up web-ui WorkspaceAdminComponentAuthorizer

- src/main/src/main/java/org/geoserver/security/SecureCatalogImpl.java
- src/security/security-tests/src/test/java/org/geoserver/ows/LocalWorkspaceSecureCatalogTest.java
[![GEOS-11423](https://badgen.net/badge/JIRA/GEOS-11423/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11423) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7698
> [Backport 2.25.x] [GEOS-11423] Use securityFilter in SecureCatalogImpl bulk get methods

- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLConstants.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLDocumentBuilder.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLLayerGroupConfigurationPanel.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java
[![GEOS-11422](https://badgen.net/badge/JIRA/GEOS-11422/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11422) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11422] MapML License Metadata Stored With Incorrect Keys

- src/community/oseo/oseo-assembly/pom.xml
[![GEOS-11438](https://badgen.net/badge/JIRA/GEOS-11438/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11438) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Simple packaging issue, a missing dependency. The modules do work anyways, but the GUI part is missing.
> [GEOS-11438] OpenSearch for EO/STAC lack the service configuration panel

- .github/workflows/assembly.yml
- .github/workflows/backport.yml
- .github/workflows/docs.yml
- .github/workflows/javadoc.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/postgis_appschema_online.yml
- .github/workflows/qa.yml
- .github/workflows/windows.yml
> [Backport 2.25.x] [ci] update workflow actions and maven version

- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccess.java
[![GEOS-11439](https://badgen.net/badge/JIRA/GEOS-11439/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11439) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Avoid computing the list of names multiple times in a single request (happens during image mosaic initialization, for example).
> [GEOS-11439] JDBCOpenSearch access should cache the list of type name s in request scope

- src/community/gdal/gdal-wcs/src/main/java/org/geoserver/wcs/response/GdalCoverageResponseDelegate.java
[![GEOS-11442](https://badgen.net/badge/JIRA/GEOS-11442/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11442) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
See ticket. We cannot control gdal_translate availability on the system, so no new test, but I've checked all existing tests do pass.
> [GEOS-11442] Cache availability of gdal_translate in gdal_translate based WCS output formats

- src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccess.java
[![GEOS-11439](https://badgen.net/badge/JIRA/GEOS-11439/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11439) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7738
> [Backport 2.25.x] [GEOS-11439] JDBCOpenSearch access should cache the list of type name s in request scope

- src/community/gdal/gdal-wcs/src/main/java/org/geoserver/wcs/response/GdalCoverageResponseDelegate.java
[![GEOS-11442](https://badgen.net/badge/JIRA/GEOS-11442/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11442) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7740
> [Backport 2.25.x] [GEOS-11442] Cache availability of gdal_translate in gdal_translate based WCS output formats

- src/community/security/keycloak/pom.xml
- src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/GeoServerKeycloakFilter.java
- src/community/security/keycloak/src/test/java/org/geoserver/security/keycloak/GeoServerKeycloakFilterTest.java
[![GEOS-11336](https://badgen.net/badge/JIRA/GEOS-11336/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11336) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11336] upgrade keycloak

- src/community/security/keycloak/pom.xml
- src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/GeoServerKeycloakFilter.java
- src/community/security/keycloak/src/test/java/org/geoserver/security/keycloak/GeoServerKeycloakFilterTest.java
[![GEOS-11336](https://badgen.net/badge/JIRA/GEOS-11336/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11336) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7724
> [Backport 2.24.x] [GEOS-11336] upgrade keycloak

- src/community/security/keycloak/pom.xml
- src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/GeoServerKeycloakFilter.java
- src/community/security/keycloak/src/test/java/org/geoserver/security/keycloak/GeoServerKeycloakFilterTest.java
[![GEOS-11336](https://badgen.net/badge/JIRA/GEOS-11336/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11336) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7724
> [Backport 2.25.x] [GEOS-11336] upgrade keycloak

- doc/en/developer/source/cite-test-guide/index.rst
The one page  `developer/source/cite-test-guide/index.rst` has several entries in the table of contents as its headings do not form a page structure:
* https://docs.geoserver.org/latest/en/developer/cite-test-guide/index.html
* https://docs.geoserver.org/latest/en/developer/cite-test-guide/index.html#cite-automation-tests-with-docker
* https://docs.geoserver.org/latest/en/developer/cite-test-guide/index.html#run-cite-test-suites-in-local-pc
This is not a functional change so I am not going to open a ticket.
> fix cite test instructions headings for table of contents

- src/community/taskmanager/core/src/assembly/assembly.xml
[![GEOS-10690](https://badgen.net/badge/JIRA/GEOS-10690/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10690) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-10690] Taskmanager community module: fix assembly

- doc/en/user/source/community/oauth2/oidc.rst
Backport #7763
**Authored by:** @rob518183
> [Backport 2.25.x] Update oidc.rst

- src/pom.xml
[![GEOS-11464](https://badgen.net/badge/JIRA/GEOS-11464/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11464) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11464] Update Jackson 2 libs from 2.17.1 to 2.17.2

- src/community/datadir-catalog-loader/src/main/java/org/geoserver/catalog/datadir/DataDirectoryGeoServerLoader.java
- src/community/datadir-catalog-loader/src/test/java/org/geoserver/catalog/datadir/DataDirectoryGeoServerLoaderTest.java
[![GEOS-11469](https://badgen.net/badge/JIRA/GEOS-11469/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11469) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
As the "Datadir catalog loader" loads and parses the datadir files in parallel, decrypting passwords is deferred, or the calls to GeoServerExtensions inside XStreamPersister causes a deadlock in the main thread.
So far `DataDirectoryGeoServerLoader` decrypted passwords in `DataStoreInfo` connection parameters, but it didn't on `HTTPStoreInfo.password`.
> [GEOS-11469] Datadir catalog loader does not decrypt HTTPStoreInfo passwords

- src/community/datadir-catalog-loader/src/main/java/org/geoserver/catalog/datadir/DataDirectoryGeoServerLoader.java
- src/community/datadir-catalog-loader/src/test/java/org/geoserver/catalog/datadir/DataDirectoryGeoServerLoaderTest.java
[![GEOS-11469](https://badgen.net/badge/JIRA/GEOS-11469/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11469) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7774
> [Backport 2.25.x] [GEOS-11469] Datadir catalog loader does not decrypt HTTPStoreInfo passwords

- src/restconfig/src/main/java/org/geoserver/rest/security/UsersRestController.java
- src/restconfig/src/test/java/org/geoserver/rest/security/UserRoleRestControllerTest.java
[![GEOS-11462](https://badgen.net/badge/JIRA/GEOS-11462/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11462) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Check existing user-group association before attempting this call to avoid SQL duplicate key violations (for JDBC user/group service)
> [GEOS-11462] 500 error thrown when double adding a user to a group via REST with JDBC user/group services

- src/restconfig/src/main/java/org/geoserver/rest/security/UsersRestController.java
- src/restconfig/src/test/java/org/geoserver/rest/security/UserRoleRestControllerTest.java
[![GEOS-11462](https://badgen.net/badge/JIRA/GEOS-11462/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11462) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7783
> [Backport 2.24.x] [GEOS-11462] 500 error thrown when double adding a user to a group via REST with JDBC user/group services

- src/restconfig/src/main/java/org/geoserver/rest/security/UsersRestController.java
- src/restconfig/src/test/java/org/geoserver/rest/security/UserRoleRestControllerTest.java
[![GEOS-11462](https://badgen.net/badge/JIRA/GEOS-11462/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11462) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7783
> [Backport 2.25.x] [GEOS-11462] 500 error thrown when double adding a user to a group via REST with JDBC user/group services

- doc/en/api/1.0.0/reload.yaml
- doc/en/user/source/rest/api/reset.rst
- src/main/src/main/java/applicationContext.xml
- src/main/src/main/java/applicationSecurityContext.xml
- src/main/src/main/java/org/geoserver/security/GeoServerSecurityManager.java
- src/main/src/main/java/org/geoserver/security/auth/AuthenticationCache.java
- src/main/src/main/java/org/geoserver/security/auth/AuthenticationCacheImpl.java
- src/main/src/main/java/org/geoserver/security/auth/GeoServerRootAuthenticationProvider.java
- src/main/src/main/java/org/geoserver/security/auth/GuavaAuthenticationCacheImpl.java
- src/main/src/main/java/org/geoserver/security/auth/LRUAuthenticationCacheImpl.java
- src/main/src/main/java/org/geoserver/security/auth/UsernamePasswordAuthenticationProvider.java
- src/main/src/test/java/org/geoserver/security/auth/AbstractAuthenticationProviderTest.java
- src/main/src/test/java/org/geoserver/security/auth/TestingAuthenticationCache.java
- src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
- src/restconfig/src/main/java/org/geoserver/rest/CatalogReloadController.java
- src/security/security-tests/src/test/java/org/geoserver/security/auth/AbstractAuthenticationProviderTest-context.xml
[![GEOS-11443](https://badgen.net/badge/JIRA/GEOS-11443/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11443) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7768
> [Backport 2.25.x] [GEOS-11443] REST API does not take effect immediately due to 10 minute authentication cache

- doc/en/api/1.0.0/reload.yaml
- doc/en/user/source/rest/api/reset.rst
- src/main/src/main/java/applicationContext.xml
- src/main/src/main/java/applicationSecurityContext.xml
- src/main/src/main/java/org/geoserver/security/GeoServerSecurityManager.java
- src/main/src/main/java/org/geoserver/security/auth/AuthenticationCache.java
- src/main/src/main/java/org/geoserver/security/auth/AuthenticationCacheImpl.java
- src/main/src/main/java/org/geoserver/security/auth/GeoServerRootAuthenticationProvider.java
- src/main/src/main/java/org/geoserver/security/auth/GuavaAuthenticationCacheImpl.java
- src/main/src/main/java/org/geoserver/security/auth/LRUAuthenticationCacheImpl.java
- src/main/src/main/java/org/geoserver/security/auth/UsernamePasswordAuthenticationProvider.java
- src/main/src/test/java/org/geoserver/security/auth/AbstractAuthenticationProviderTest.java
- src/main/src/test/java/org/geoserver/security/auth/TestingAuthenticationCache.java
- src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
- src/restconfig/src/main/java/org/geoserver/rest/CatalogReloadController.java
- src/security/security-tests/src/test/java/org/geoserver/security/auth/AbstractAuthenticationProviderTest-context.xml
[![GEOS-11443](https://badgen.net/badge/JIRA/GEOS-11443/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11443) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7768
> [Backport 2.24.x] [GEOS-11443] REST API does not take effect immediately due to 10 minute authentication cache

- doc/en/user/source/data/raster/imagemosaic/configuration.rst
- src/pom.xml
[![GEOS-11477](https://badgen.net/badge/JIRA/GEOS-11477/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11477) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Doc updates and JAI-EXT upgrade, the actual implementation is in GeoTools and JAI-EXT:
https://github.com/geotools/geotools/pull/4840
> [GEOS-11477] Add a max and a min merge mode for image mosaics

- src/rest/src/test/java/org/geoserver/rest/util/IOUtilsTest.java
[![GEOS-11468](https://badgen.net/badge/JIRA/GEOS-11468/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11468) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
PMD has a few JUnit specific that were missed for IOUTilsTest
> [GEOS-11468] PMD fixes for IOUtils

- src/restconfig/src/main/java/org/geoserver/rest/catalog/WMSStoreController.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/WMTSStoreController.java
Backport #7795
**Authored by:** @logresearch
> [Backport 2.25.x] Update Logging Statement for WMS Store Deletion

- src/pom.xml
[![GEOS-11473](https://badgen.net/badge/JIRA/GEOS-11473/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11473) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11473] Upgrade guava from 33.2.0 to 33.2.1

- src/pom.xml
[![GEOS-11479](https://badgen.net/badge/JIRA/GEOS-11479/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11479) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11479] Upgrade junit from 4.13.1 to 4.13.2

- src/pom.xml
[![GEOS-11478](https://badgen.net/badge/JIRA/GEOS-11478/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11478) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11478] Upgrade commons-lang3 from 3.14.0 to 3.15.0

- src/restconfig/src/main/java/org/geoserver/rest/catalog/WMSStoreController.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/WMTSStoreController.java
Backport #7795
**Authored by:** @logresearch
> [Backport 2.24.x] Update Logging Statement for WMS Store Deletion

- src/pom.xml
[![GEOS-11475](https://badgen.net/badge/JIRA/GEOS-11475/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11475) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11475] Upgrade commons-codec from 1.17.0 to 1.17.1

- src/pom.xml
- src/wms/src/main/java/org/geoserver/wms/decoration/TextDecoration.java
[![GEOS-11472](https://badgen.net/badge/JIRA/GEOS-11472/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11472) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11472] Upgrade freemarker from 2.3.31 to 2.3.33

- doc/en/user/source/production/java.rst
- src/pom.xml
- src/release/bin/startup.bat
- src/release/bin/startup.sh
Objectives: use latest, make it work with Java 17 and 21 out of the box.
Status: tested on Linux with java 11, 17 and 21, I can render maps, the renderer name does not show up in 17 and 21 (probably due to reflection being limited?). Untested on windows. Untested in deploys with spaces and other oddball chars in paths.
Shared branch, help welcomed.
> Attempt updating to latest Marlin renderer

- doc/en/user/source/production/java.rst
- src/pom.xml
- src/release/bin/startup.bat
- src/release/bin/startup.sh
> [Backport 2.25.x] Attempt updating to latest Marlin renderer

- doc/en/user/source/extensions/mapml/installation.rst
A recent commit on MapML documentation refactoring the structure, removed by mistake some recent changes.
Restoring them.
> MapML: Restoring missing updates on documentation from recent merge

- src/community/schemaless-features/mongodb-schemaless/pom.xml
- src/community/schemaless-features/mongodb-schemaless/src/test/java/org/geoserver/schemalessfeatures/mongodb/WFSSchemalessMongoTest.java
- src/community/schemaless-features/mongodb-schemaless/src/test/java/org/geoserver/schemalessfeatures/mongodb/WMSSchemalessMongoTest.java
- src/community/schemaless-features/mongodb-schemaless/src/test/resources/org/geoserver/schemalessfeatures/mongodb/test-data/stations/json/stations1.json
- src/community/schemaless-features/mongodb-schemaless/src/test/resources/org/geoserver/schemalessfeatures/mongodb/test-data/stations/query/postQuery.xml
[![GEOS-11470](https://badgen.net/badge/JIRA/GEOS-11470/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11470) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
https://osgeo-org.atlassian.net/browse/GEOS-11470
The goal of this PR is to upgrade the version of Mongo driver used in schemaless plugin to latest version (4.11.2).
The previous version of the driver (4.0.6) has some compatibility issues for versions of Mongo never then 4.2 (and latest is 7.0).
You can find more information regarding Java driver compatibility here: …
> [GEOS-11470] Upgrade the version of Mongo driver for schemaless plugin from 4.0.6 to 4.11.2

- src/community/gwc-azure-blob/src/main/resources/applicationContext.xml
- src/gwc/src/main/resources/geowebcache-core-context.xml
[![GEOS-7630](https://badgen.net/badge/JIRA/GEOS-7630/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-7630) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Basically a follow up to https://github.com/geoserver/geoserver/pull/6325 that covers the Azure blob store as well. 
Logic is the same, the crucial bit that makes the PR work there is the dependency between the blob store configuration support and the environment synchronizer, which was replicated here.
An actual test with Azure would require an online resource over Azure paid services (at the time of writing at least, once we …
> [GEOS-7630] Azure blob store may not get environment parameters from property file

- src/web/app/pom.xml
After the [Community assembly rework, split COG module into "per cloud" zip packages](2a813faf44491a5d532f4d2fc3f1db0939c6e198) commit, the `cog` maven profile in `src/web/app/pom.xml` is broken:
```
[ERROR] Failed to execute goal on project gs-web-app: Could not resolve
dependencies for project org.geoserver.web:gs-web-app:jar:2.26-SNAPSHOT:
The following artifacts could not be resolved:
org.geoserver.community:gs-cog:jar:2.26-SNAPSHOT (absent):
Could not find artifact org.geoserver.community:gs-cog:jar:2.26-SNAPSHOT
in osgeo-snapshots (https://repo.osgeo.org/repository/snapshot/)
```
Add all the specific cog-xxx jars to the `cog` profile, consistently with the `cog` profile defined in `src/community/pom.xml`, which includes all the cog modules.
> Fix cog maven profile for gs-web-app

- src/community/gwc-azure-blob/src/main/resources/applicationContext.xml
- src/gwc/src/main/resources/geowebcache-core-context.xml
[![GEOS-7630](https://badgen.net/badge/JIRA/GEOS-7630/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-7630) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7815
> [Backport 2.24.x] [GEOS-7630] Azure blob store may not get environment parameters from property file

- src/community/gwc-azure-blob/src/main/resources/applicationContext.xml
- src/gwc/src/main/resources/geowebcache-core-context.xml
[![GEOS-7630](https://badgen.net/badge/JIRA/GEOS-7630/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-7630) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7815
> [Backport 2.25.x] [GEOS-7630] Azure blob store may not get environment parameters from property file

- src/pom.xml
> Upgrade easymock from 5.2.0 to 5.4.0

- src/pom.xml
> Upgrade mockito from 5.6.0 to 5.12.0

- src/pom.xml
> Upgrade awaitility from 4.2.0 to 4.2.2

- src/web/app/pom.xml
> [Backport 2.25.x] Fix cog maven profile for gs-web-app

- src/web/core/src/main/java/org/geoserver/web/css/geoserver.css
- src/web/security/core/src/main/java/org/geoserver/security/web/PaletteFormComponent.java
- src/web/security/core/src/main/java/org/geoserver/security/web/role/RolePaletteFormComponent.java
- src/web/security/core/src/main/java/org/geoserver/security/web/role/RuleRolesFormComponent.java
- src/web/security/core/src/main/java/org/geoserver/security/web/user/UserGroupPaletteFormComponent.java
[![GEOS-11502](https://badgen.net/badge/JIRA/GEOS-11502/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11502) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #7837
> [Backport 2.25.x] [GEOS-11502] Permit resize on user/group/role palette textbox to allow for extra long role names

- src/community/hz-cluster/src/test/java/org/geoserver/cluster/hazelcast/EventHzSynchronizerRecvTest.java
- src/kml/src/test/java/org/geoserver/kml/KMLTest.java
- src/main/src/test/java/org/geoserver/config/FileExistsMatcher.java
- src/pom.xml
- src/restconfig/src/test/java/org/geoserver/rest/catalog/WMSLayerTest.java
- src/restconfig/src/test/java/org/geoserver/rest/catalog/WMTSLayerTest.java
This is a test dependency upgrade.
Since the addition of org.awaitility:awaitility, geoserver contains two versions of the hamcrest library:
org.hamcrest:hamcrest:2.0 from the org.awaitility:awaitility dependency
org.hamcrest:hamcrest-core:1.3 from the junit:junit dependency
org.hamcrest:hamcrest-library:1.3 from the root pom.xml
org.hamcrest:hamcrest-integration:1.3 from the root pom.xml
This PR upgrades hamcrest to 3.0 and removes the hamcrest-core, hamcrest-library, and hamcrest-integration dependencies. The version is set to 3.0 for hamcrest-core and hamcrest-library in case there is another transitive dependency on it (these are empty jar files). hamcrest-integration has no version beyond 1.3.
Some code changes were required for deprecated or removed API.
For core and extension …
> Upgrade hamcrest to 3.0

- src/pom.xml
[![GEOS-11506](https://badgen.net/badge/JIRA/GEOS-11506/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11506) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11506] Upgrade Spring version from 5.3.37 to 5.3.39 and Spring security from 5.8.13 to 5.8.14

- src/pom.xml
[![GEOS-11506](https://badgen.net/badge/JIRA/GEOS-11506/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11506) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
backports #7845 but **ONLY** the spring framework upgrade, not spring security
>  [Backport 2.25.x] [GEOS-11506] Upgrade Spring version from 5.3.34 to 5.3.39

- doc/en/user/source/security/layer.rst
> Fix security/layer spelling & grammar

- src/pom.xml
[![GEOS-11512](https://badgen.net/badge/JIRA/GEOS-11512/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11512) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR is just a dependency upgrade.
> [GEOS-11512] Upgrade jasypt from 1.9.2 to 1.9.3

- doc/en/user/source/extensions/mapml/installation.rst
[The MapML polyfill has been renamed to "MapML.js"](https://github.com/Maps4HTML/MapML.js/issues/964), and usages of the term Web-Map-Custom-Element to refer to it must be removed.
> Rename Web-Map-Custom-Element -> MapML.js. Update links to docs.

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/GeoJSONPPIO.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ppio/GeoJSONPPIOTest.java
[![GEOS-11514](https://badgen.net/badge/JIRA/GEOS-11514/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11514) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR fixes an exception being thrown when a WPS Execute request contains a geometry input in geojson format.
> [GEOS-11514] Fix parsing WPS geometry geojson inputs

- src/pom.xml
This PR is a test dependency upgrade.
> Upgrade jsoup from 1.15.3 to 1.18.1

- doc/en/user/source/styling/css/filters.rst
- src/extension/css/pom.xml
- src/extension/css/src/main/java/org/geoserver/community/css/web/CssHandler.java
- src/extension/css/src/main/resources/applicationContext.xml
- src/extension/css/src/test/java/org/geoserver/community/css/web/CssHandlerTest.java
- src/extension/ysld/src/main/resources/applicationContext.xml
[![GEOS-11515](https://badgen.net/badge/JIRA/GEOS-11515/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11515) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Follow up to https://github.com/geotools/geotools/pull/4882, requires that PR to be merged to compile.
> [GEOS-11515] Add support for zoom level rule filtering in CSS

- src/community/ogcapi/dggs/dggs-clickhouse/src/main/java/org/geootols/dggs/clickhouse/ClickHouseFilterToSQL.java
- src/community/ogcapi/dggs/dggs-clickhouse/src/test/java/org/geootols/dggs/clickhouse/ClickHouseFilterToSQLTest.java
- src/community/ogcapi/dggs/dggs-core/pom.xml
- src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/rhealpix/RHealPixDGGSFactory.java
- src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/rhealpix/RHealPixDGGSInstance.java
- src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/rhealpix/RHealPixZoneIterator.java
- src/community/ogcapi/dggs/dggs-core/src/test/java/org/geotools/dggs/rhealpix/RHealPixGeometryStoreTest.java
- src/community/ogcapi/dggs/dggs-core/src/test/java/org/geotools/dggs/rhealpix/RHealPixInstanceTest.java
See tickets for details:
* https://osgeo-org.atlassian.net/browse/GEOS-11518
* https://osgeo-org.atlassian.net/browse/GEOS-11519
> DGGS improvements (do not force CET timezone in filters, run again all online tests)

- doc/en/user/source/datadirectory/setting.rst
This PR applies a change in the Geoserver docs, for the part that documents how to externalize the data-directory.
The wording contained the word 'recommended' for the set up of the context-parameter in the web.xml file.
The word 'recommended' was removed since it could be mistaken by the readers, there is not a 'recommended'  method, but is explained as an alternative.
> removed 'recommended' from the datadir set up wording

- src/release/ext-vectortiles.xml
[![GEOS-11527](https://badgen.net/badge/JIRA/GEOS-11527/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11527) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
A missing dependency noticed while doing interactive testing. Follow up to https://github.com/geoserver/geoserver/pull/7877
>  [GEOS-11527] Adding missing dependency on gt-process-geometry in assembly

- src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/iterator/CoalescingVTIterator.java
- src/extension/vectortiles/src/test/java/org/geoserver/wms/vector/iterator/CoalescingVTIteratorTest.java
[![GEOS-11531](https://badgen.net/badge/JIRA/GEOS-11531/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11531) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11531] When coaleshing linestrings in vector tiles output, fuse them to create a single long line

- src/web/core/src/main/java/org/geoserver/web/wicket/Select2DropDownChoice.java
[![GEOS-11530](https://badgen.net/badge/JIRA/GEOS-11530/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11530) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Really annoying when editing a layer cached gridsets. See ticket for details.
Writing a test for this one would require running an actual browser, I'd shelve this one in the "too hard to write a test"  category.
> [GEOS-11530] Adding or removing a grid subset in the layer caching tab, causes the grid dropdown to get duplicated

- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/SimplifyProcessTest.java
- src/pom.xml
[![GEOS-11532](https://badgen.net/badge/JIRA/GEOS-11532/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11532) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
See release notes https://github.com/GeoWebCache/geowebcache/pull/1317
> [GEOS-11532] Update to JTS 1.20.0

- src/pom.xml
[![GEOS-11545](https://badgen.net/badge/JIRA/GEOS-11545/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11545) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11545] Update to JAI-EXT 1.1.27

- src/pom.xml
[![GEOS-11544](https://badgen.net/badge/JIRA/GEOS-11544/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11544) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Follow up with the upgrade on [GeoTools](https://github.com/geotools/geotools/pull/4905) and [GeoWebCache](https://github.com/GeoWebCache/geowebcache/pull/1319)
> [GEOS-11544] Upgrade to ImageIO-EXT 1.4.13

- build/qa/pmd-ruleset.xml
- src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/utils/BackupUtils.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/Directory.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/RemoteData.java
- src/extension/importer/core/src/main/java/org/geoserver/importer/VFSWorker.java
- src/extension/importer/pom.xml
- src/pom.xml
[![GEOS-11533](https://badgen.net/badge/JIRA/GEOS-11533/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11533) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Update to a version compatible with httpclient 3.1 as used by geoserver.
> [GEOS-11533] Update org.apache.commons.vfs2 to 2.9.1

- src/extension/geofence/geofence-server/src/test/java/org/geoserver/geofence/server/integration/GeofenceIntegrationTestSupport.java
- src/extension/geofence/geofence-wps/src/test/java/org/geoserver/geofence/server/integration/GeofenceWPSTest.java
- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/RuleFilterBuilder.java
- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/cache/CacheManager.java
- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/cache/CachedRuleLoaders.java
- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/cache/CachedRuleReader.java
- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/cache/RuleCacheLoaderFactory.java
- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/config/GeoFenceConfigurationController.java
- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/containers/CachedContainerAccessResolver.java
- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/containers/ContainerAccessCacheLoaderFactory.java
- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/containers/ContainerAccessResolver.java
- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/containers/ContainerLimitResolver.java
- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/containers/DefaultContainerAccessResolver.java
- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/rest/CacheController.java
- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/web/GeofencePage.html
- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/web/GeofencePage.java
- src/extension/geofence/geofence/src/main/resources/GeoServerApplication.properties
- src/extension/geofence/geofence/src/main/resources/applicationContext.xml
- src/extension/geofence/geofence/src/test/java/org/geoserver/geofence/CacheReaderTest.java
[![GEOS-11526](https://badgen.net/badge/JIRA/GEOS-11526/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11526) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR also includes "[GEOS-11525] GeoFence: refactor cache classes" on which it depends on.
ATM I'm using this PR only for circle checks, will probably create a new one if #7876 is merged before this.
This PR caches the results computed on client side on the Containers.
> [GEOS-11526] GeoFence: slow GeoServer response when there are many roles and layergroups

- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APISearchQuery.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACSearchQuery.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACService.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/SearchTest.java
[![GEOS-11541](https://badgen.net/badge/JIRA/GEOS-11541/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11541) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11541] STAC search endpoint sortby query not working with POST

- doc/en/user/source/gettingstarted/geopkg-quickstart/index.rst
- doc/en/user/source/gettingstarted/group-quickstart/index.rst
- doc/en/user/source/gettingstarted/image-quickstart/index.rst
- doc/en/user/source/gettingstarted/postgis-quickstart/index.rst
- doc/en/user/source/gettingstarted/shapefile-quickstart/index.rst
- doc/en/user/source/gettingstarted/style-quickstart/index.rst
- src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
Hi!
As I was reading the doc I noticed some typos and decided to create a PR to fix them.
> fixes various typos

- src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
- src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetFeatureTest.java
- src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureTest.java
[![GEOS-11543](https://badgen.net/badge/JIRA/GEOS-11543/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11543) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
fixed to ignore lists of lists and added tests
> [GEOS-11543] WFS Unable to use propertyName to filter properties in a GetFeature request

- doc/en/user/source/conf.py
- doc/en/user/source/datadirectory/location.rst
- doc/en/user/source/datadirectory/setting.rst
- doc/en/user/source/installation/docker.rst
Having the data directory location in `C:\Program Files (x86)\GeoServer 2.26.x\data_dir` is misguided, recommending "%PROGRAMDATA%" (for example).
> Update GEOSERVER_DATA_DIR example locations

- src/web/core/src/main/java/org/geoserver/web/data/layer/SQLViewAbstractPage.java
fixing a typo in a doc-comment similar to https://github.com/geotools/geotools/pull/4922  
> Fix spelling of geoemtry (geometry) in comment

- src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/ogcapi/v1/dggs/DGGSService.java
- src/community/ogcapi/dggs/ogcapi-dggs/src/test/java/org/geoserver/ogcapi/v1/dggs/LandingPageTest.java
- src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIDispatcher.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/v1/coverages/CoveragesService.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/v1/coverages/LandingPageTest.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/LandingPageTest.java
- src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/ogcapi/v1/images/ImagesService.java
- src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/ogcapi/v1/images/LandingPageTest.java
- src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/v1/maps/MapsService.java
- src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/LandingPageTest.java
- src/community/ogcapi/ogcapi-styles/src/main/java/org/geoserver/ogcapi/v1/styles/StylesService.java
- src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/ogcapi/v1/styles/LandingPageTest.java
- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACService.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/LandingPageTest.java
- src/main/src/main/java/org/geoserver/ows/DisabledServiceCheck.java
- src/platform/src/main/java/org/geoserver/platform/OWS20Exception.java
- src/platform/src/main/java/org/geoserver/platform/ServiceException.java
[![GEOS-11517](https://badgen.net/badge/JIRA/GEOS-11517/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11517) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
[GEOS-11517] Using various OGC APIs results in service enabled check related WARN logs
> [GEOS-11517] Using various OGC APIs results in service enabled check related WARN logs

- src/community/ogcapi/ogcapi-core/pom.xml
- src/community/oseo/oseo-assembly/src/assembly/assembly.xml
- src/pom.xml
[![GEOS-11560](https://badgen.net/badge/JIRA/GEOS-11560/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11560) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This basically follows up with https://github.com/geotools/geotools/pull/4935, where the CQL2 modules have been given a name that follows a consistent naming convention. All of the existing OGC API modules assemblies (besides one) are already including "gt-cql2-*" so the naming convention change in GEoTools will also make sure the CQL2-JSON is included in the OGC API services.
> [GEOS-11560] OGC API modules lack cql2-json in assembly

- src/web/wms/src/main/java/org/geoserver/wms/web/data/AbstractStylePage.java
> fix style CodeMirror editor to save/apply with modified XML

- doc/en/user/source/introduction/gettinginvolved.rst
Fixed typo
- [NA] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [NA] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).
> Fixed typo in gettinginvolved.rst

- src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/gstore/DGGSResolutionCalculator.java
- src/community/ogcapi/dggs/dggs-core/src/test/java/org/geotools/dggs/gstore/DGGSResolutionCalculatorTest.java
- src/community/ogcapi/dggs/web-dggs/pom.xml
- src/community/ogcapi/dggs/web-dggs/src/main/java/org/geoserver/web/publish/dggs/DGGSConfigPanel.html
- src/community/ogcapi/dggs/web-dggs/src/main/java/org/geoserver/web/publish/dggs/DGGSConfigPanel.java
- src/community/ogcapi/dggs/web-dggs/src/main/java/org/geoserver/web/publish/dggs/DGGSConfigurationPageInfo.java
- src/community/ogcapi/dggs/web-dggs/src/main/resources/GeoServerApplication.properties
- src/community/ogcapi/dggs/web-dggs/src/main/resources/applicationContext.xml
- src/community/ogcapi/dggs/web-dggs/src/test/java/org/geoserver/web/publish/dggs/DGGSConfigPanelTest.java
[![GEOS-11563](https://badgen.net/badge/JIRA/GEOS-11563/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11563) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [Backport 2.26.x] [GEOS-11563] Allow configuring a DGGS resolution offset on a layer basis 

- src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/gstore/DGGSResolutionCalculator.java
- src/community/ogcapi/dggs/dggs-core/src/test/java/org/geotools/dggs/gstore/DGGSResolutionCalculatorTest.java
- src/community/ogcapi/dggs/web-dggs/pom.xml
- src/community/ogcapi/dggs/web-dggs/src/main/java/org/geoserver/web/publish/dggs/DGGSConfigPanel.html
- src/community/ogcapi/dggs/web-dggs/src/main/java/org/geoserver/web/publish/dggs/DGGSConfigPanel.java
- src/community/ogcapi/dggs/web-dggs/src/main/java/org/geoserver/web/publish/dggs/DGGSConfigurationPageInfo.java
- src/community/ogcapi/dggs/web-dggs/src/main/resources/GeoServerApplication.properties
- src/community/ogcapi/dggs/web-dggs/src/main/resources/applicationContext.xml
- src/community/ogcapi/dggs/web-dggs/src/test/java/org/geoserver/web/publish/dggs/DGGSConfigPanelTest.java
[![GEOS-11563](https://badgen.net/badge/JIRA/GEOS-11563/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11563) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [Backport 2.25.x] [GEOS-11563] Allow configuring a DGGS resolution offset on a layer basis 

- src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/rhealpix/RHealPixDGGSFactory.java
- src/community/ogcapi/dggs/dggs-core/src/test/java/org/geotools/dggs/rhealpix/RHealPixDGGSFactoryTest.java
[![GEOS-11579](https://badgen.net/badge/JIRA/GEOS-11579/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11579) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
See ticket for details (odd issue, same method throws two different exceptions depending on whether it's the first time the method is invoked, or not).
> [GEOS-11579] DGGS modules prevent GeoServer startup if JEP is not installed

- src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayersPage.html
- src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayersPage.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/CachedLayersPageTest.java
[![GEOS-11573](https://badgen.net/badge/JIRA/GEOS-11573/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11573) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR updates the Tile Layers page to work with Wicket 9 in the same was as the Layer Preview page.
> [GEOS-11573] TileLayer preview doesn't work anymore

- src/pom.xml
[![GEOS-11587](https://badgen.net/badge/JIRA/GEOS-11587/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11587) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11587] Update mapfish-print-v2 to version 2.3.2

- doc/en/user/source/production/config.rst
- doc/en/user/source/webadmin/index.rst
[![GEOS-11141](https://badgen.net/badge/JIRA/GEOS-11141/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11141) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
The documentation was restructured to separate out administrator from workspace administrator in response to security vulnerability on log file traversal.
See https://github.com/geoserver/geoserver/security/advisories/GHSA-8g7v-vjrc-x4g5
> [GEOS-11141] Change docs to workspace admin recommendation

- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLURLBuilder.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLBaseProxyTest.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMTSProxyTest.java
[![GEOS-11561](https://badgen.net/badge/JIRA/GEOS-11561/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11561) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Use the capabilities getmap / gettile url as the "base" for templates, fall back to using the URL of the capabilities document itself.
Update MapMLBaseProxyTest.java to check the cascaded request against the request URL from the capabilities document OR if that is null, use the URL OF the capabilities document as the base.
Update assertCascading in MapMLWMTSProxyTest.java to compare against resource request URL from …
>  [GEOS-11561] Client-Delegating MapML Proxy - update

- src/community/netcdf-ghrsst/pom.xml
- src/community/taskmanager/core/bin/pom.xml
- src/community/taskmanager/core/pom.xml
- src/extension/importer/core/pom.xml
- src/extension/netcdf-out/pom.xml
- src/extension/vectortiles/pom.xml
- src/platform/pom.xml
- src/pom.xml
- src/release/pom.xml
- src/security/ldap/pom.xml
- src/web/core/pom.xml
[![GEOS-11590](https://badgen.net/badge/JIRA/GEOS-11590/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11590) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR upgrades the log4j and slf4j dependencies to their current versions and is related to the Wicket 9 upgrade. The slf4j version is now managed in the root GeoServer POM and unnecessary version properties were removed from child POMs.
See https://osgeo-org.atlassian.net/browse/GEOS-11590 for more information.
I tested changing the logging levels from the GeoServer UI and everything seems to work fine still.
For core …
> [GEOS-11590] Upgrade log4j to 2.24.1 and slf4j to 2.0.16

- src/pom.xml
Remove duplicate dependency declaration for gt-cql2-text in the root pom, inadvertently added in #7808
> Remove duplicate dependency declaration for gt-cql2-text in the root pom

- doc/en/user/source/data/database/sqlserver.rst
see https://discourse.osgeo.org/t/sql-server-plugin-extension/50931/4
> Update SQL Server supported versions

- build/cite/ogcapi-features10/release/global.xml
The ets-ogcapi-features10 test suite will chek the transformed collection items fall inside the collection's declared spatialExtent (WGS84). In doing so, the test themselves are limited to 7 decimals for geographic coordinates, and hence will fail with GeoServer's higher accuracy, despite GeoServer responses being correct.
> ogcapi-features CITE tests: set numDecimals to 7 to match CITE test limitations

- .github/workflows/cite.yml
- build/cite/Makefile
- build/cite/ogcapi-features10/.gitignore
- build/cite/ogcapi-features10/build-ets.sh
- build/cite/ogcapi-features10/compose.override.yml
Use a patched version of `ogccite/ets-ogcapi-features10:1.8-SNAPSHOT-teamengine-5.4.1`.
Currently, we require the following pull request to be applied: [Fix global crs codes lookup in discovery collections crs tests](https://github.com/opengeospatial/ets-ogcapi-features10/pull/255) to the test suite.
This may happen again, hence we're introducing a build step to generate the required `ogccite/ets-ogcapi-features10` image out of the `geoserver/ets-ogcapi-features10` fork, using a branch named `geoserver/integration`.
The procedure to maintain that branch is to rebase on top of the upstream master branch as required, and apply the additional branches with `git merge --no-ff`.
> Use a patched ogccite/ets-ogcapi-features10 Docker image with additional fixes

- src/pom.xml
[![GEOS-11610](https://badgen.net/badge/JIRA/GEOS-11610/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11610) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11610] Update Jetty from 9.4.55.v20240627 to 9.4.56.v20240826

- src/kml/src/main/java/org/geoserver/kml/iterator/AbstractFolderIteratorFactory.java
- src/kml/src/main/java/org/geoserver/kml/iterator/PlainFolderIteratorFactory.java
- src/kml/src/test/java/org/geoserver/kml/KMLTest.java
[![GEOS-11603](https://badgen.net/badge/JIRA/GEOS-11603/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11603) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR changes the KML download folder name and ground overlay name to use the layer title instead of the layer name and adds the layer abstract to the folder description to be consistent with the network link and superoverlay folder names.
> [GEOS-11603] KML download mode does not show layer titles

- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLURLBuilder.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/gwc/gridset/MapMLGridsets.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/tcrs/TiledCRSConstants.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/tcrs/CustomTiledCRSTest.java
[![GEOS-11605](https://badgen.net/badge/JIRA/GEOS-11605/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11605) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11605]:MapML custom TiledCRS (Fix on scaleDenominators Loading)

- src/pom.xml
[![GEOS-11615](https://badgen.net/badge/JIRA/GEOS-11615/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11615) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11615] Update to Imageio-EXT 1.4.14

- src/web/core/src/main/java/org/geoserver/web/wicket/js/codemirror/addon/search/search.js
- src/web/core/src/main/java/org/geoserver/web/wicket/js/codemirror/css/codemirrorlinenos.css
[![GEOS-11586](https://badgen.net/badge/JIRA/GEOS-11586/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11586) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR moves the inline style into the external CSS file.
> [GEOS-11586] Patch CodeMirror to work with Wicket's CSP

- doc/en/user/source/installation/upgrade.rst
[![GEOS-10949](https://badgen.net/badge/JIRA/GEOS-10949/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10949) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
As this was a breaking change it should be a little bit more clear  about URL Checks.
> [GEOS-10949] Update instructions should have a heading for URL Checks

- .github/workflows/assembly.yml
- .github/workflows/javadoc.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/qa.yml
- .github/workflows/windows.yml
[![MNG-7868](https://badgen.net/badge/JIRA/MNG-7868/0052CC)](https://osgeo-org.atlassian.net/browse/MNG-7868) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
We have a fair amount of builds randomly failing with "could not acquire lock" in Maven itself.
Tracked it back to this, looks like it might be a networking issue, it's not solved but they propose workarounds to make it less likely:
https://issues.apache.org/jira/browse/MNG-7868
Those extra settings have been added to the maven options in this PR.
> Workaround for 'could not acquire lock', see https://issues.apache.org/jira/browse/MNG-7868

- src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
`GeoJSONGetFeatureResponse` logs "about to encode JSON" at the `INFO` level, resulting in log flooding on a default logging config.
Lower it to `Level.FINE`.
> Avoid log flooding by GeoJSONGetFeatureResponse

- src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java
[![GEOT-7670](https://badgen.net/badge/JIRA/GEOT-7670/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7670) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This is a down-stream fix for https://github.com/geotools/geotools/pull/4973, which involves changing the manual synchronization used in one of the unit tests.
> [GEOT-7670] Fix synchronization between DataStoreFinder and DataAccessFinder

- doc/en/user/source/tutorials/imagepyramid/imagepyramid.rst
> Update imagepyramid.rst - remove dead links from docs

- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/v1/coverages/CollectionDocument.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/v1/coverages/CollectionsDocument.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/v1/coverages/CollectionsTest.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/CollectionsDocument.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/CollectionsTest.java
- src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/v1/maps/CollectionDocument.java
- src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/v1/maps/CollectionsDocument.java
- src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/CollectionsTest.java
[![GEOS-11621](https://badgen.net/badge/JIRA/GEOS-11621/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11621) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Got features test working
added maps collections
added coverages
cleanup
> [GEOS-11621] OGC API Services Not Honoring the Skip Misconfigured Layers Setting

- src/pom.xml
- src/release/ext-mysql.xml
- src/release/extensions/mysql/mysql-README.md
- src/security/jdbc/pom.xml
[![GEOS-11631](https://badgen.net/badge/JIRA/GEOS-11631/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11631) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11631] Update MySQL driver to 9.1.0

- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/v1/coverages/CollectionDocument.java
- src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/v1/coverages/CollectionsDocument.java
- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/v1/coverages/CollectionsTest.java
- src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/CollectionsDocument.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/CollectionsTest.java
- src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/v1/maps/CollectionDocument.java
- src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/v1/maps/CollectionsDocument.java
- src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/CollectionsTest.java
[![GEOS-11621](https://badgen.net/badge/JIRA/GEOS-11621/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11621) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Got features test working
added maps collections
added coverages
cleanup
fixed features and coverages not to return null when skipping
fixed nulls for maps
Changed to non-recursion version
removed redundant check
One more redundant
cleanup
> [GEOS-11621] OGC API Services Not Honoring the Skip Misconfigured Layers Setting 2.26.x backport

- src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/v1/coverages/CollectionsTest.java
- src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/CollectionsTest.java
- src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/CollectionsTest.java
> [GEOS-11632] OGCAPI tests are failing due to not reverting altered layers

- src/main/src/main/java/org/geoserver/security/RESTfulDefinitionSource.java
- src/main/src/main/java/org/geoserver/security/filter/GeoServerSecurityInterceptorFilter.java
- src/main/src/test/java/org/geoserver/security/filter/GeoServerRequestHeaderAuthenticationFilterTest.java
[![GEOS-1630](https://badgen.net/badge/JIRA/GEOS-1630/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-1630) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11630] REST API throws HTTP 500 When Security Metadata Has Null Attributes

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/InternalWFSInputProvider.java
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/ProcessParameterIO.java
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/WFSPPIO.java
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/xml/WPSConfiguration.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteInternalWFSTest.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/xml/v1_0_0/WpsXmlReaderTest.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v2_0/WFSConfiguration.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/v2_0/WFSParserDelegate.java
[![GEOS-11564](https://badgen.net/badge/JIRA/GEOS-11564/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11564) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR will build the grounds for handling internal WFS calls with version 2.0. There might be some tweaks to handle the full specter of possibilities with version 2.0 calls.
> [GEOS-11564] WPS calls to internal WFS will handle requests with version=2.0.0

- src/pom.xml
- src/release/ext-mysql.xml
- src/release/extensions/mysql/mysql-README.md
- src/security/jdbc/pom.xml
[![GEOS-11631](https://badgen.net/badge/JIRA/GEOS-11631/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11631) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #8088
> [Backport 2.25.x] [GEOS-11631] Update MySQL driver to 9.1.0

- src/web/core/src/main/java/org/geoserver/web/GeoServerApplication.java
- src/web/core/src/test/java/org/geoserver/web/data/store/CoverageStoreNewPageTest.java
- src/web/core/src/test/java/org/geoserver/web/data/store/DataAccessEditPageTest.java
- src/web/core/src/test/java/org/geoserver/web/data/store/DataAccessNewPageTest.java
[![GEOS-11636](https://badgen.net/badge/JIRA/GEOS-11636/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11636) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11636] Store panels won't always show feedback in target panels

- doc/en/user/source/introduction/gettinginvolved.rst
When mentioning editing, the word 'exceeds' was spelled incorrectly, with an additional h. This has now been removed.
> Remove small typo in gettinginvolved.rst

- src/wfs/src/test/java/org/geoserver/wfs/response/CSVOutputFormatTest.java
[![GEOS-11494](https://badgen.net/badge/JIRA/GEOS-11494/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11494) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11494] WFS GetFeature request with a propertyname parameter fails when layer attributes are customized

- doc/en/developer/source/cite-test-guide/index.rst
> Make examples consistent

- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml
- src/main/pom.xml
- src/pom.xml
- src/web/core/pom.xml
- src/web/security/ldap/pom.xml
- src/wms/pom.xml
[![GEOS-11608](https://badgen.net/badge/JIRA/GEOS-11608/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11608) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
upgrade from Java 5 to Java 8 version and update to latest release
> [GEOS-11608] Update Bouncy Castle Crypto package from bcprov-jdk15on:1.69 to bcprov-jdk18on:1.79

- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectFilterConfig.java
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdFilterConfigTest.java
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/resources/geoserver-environment.properties
- src/community/security/oauth2/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuth2FilterConfig.java
- src/community/security/oauth2/oauth2-core/src/test/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilterTest.java
- src/community/security/oauth2/oauth2-core/src/test/resources/geoserver-environment.properties
[![GEOS-11651](https://badgen.net/badge/JIRA/GEOS-11651/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11651) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
[GEOS-11651] Support env parametrization on OIDC filter
> [GEOS-11651] Support env parametrization on OIDC filter

- doc/en/user/source/extensions/printing/index.rst
- src/extension/printing/pom.xml
- src/extension/printing/src/main/java/org/geoserver/printing/PrintingServletWrappingController.java
- src/extension/printing/src/test/java/org/geoserver/printing/PrintingServletWrappingControllerTest.java
- src/extension/printing/src/test/java/org/geoserver/printing/SmokeTest.java
[![GEOS-11652](https://badgen.net/badge/JIRA/GEOS-11652/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11652) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
[GEOS-11652](https://osgeo-org.atlassian.net/browse/GEOS-11652)
Externalize printing configuration folder
> [GEOS-11652] Externalize printing configuration folder

- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLDocumentBuilder.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLHTMLOutput.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/tcrs/MapMLProjection.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/tcrs/CustomTiledCRSTest.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/web/MapMLTCRSTest.java
[![GEOS-11605](https://badgen.net/badge/JIRA/GEOS-11605/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11605) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11605]:MapML TCRS follow up on the custom TCRS support for YX CRSs

- src/extension/monitor/core/src/test/java/org/geoserver/monitor/PipeliningTaskQueueTest.java
Seeing this in github build failures, but never locally:
```
2024-12-20T18:08:43.0677920Z 18:08:43,067 [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 20.207 s <<< FAILURE! - in org.geoserver.monitor.PipeliningTaskQueueTest
2024-12-20T18:08:43.0678550Z 18:08:43,067 [ERROR] test(org.geoserver.monitor.PipeliningTaskQueueTest)  Time elapsed: 20.207 s  <<< ERROR!
2024-12-20T18:08:43.0679580Z org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.geoserver.monitor.PipeliningTaskQueueTest that uses java.util.concurrent.ConcurrentLinkedQueue, java.util.concurrent.ConcurrentLinkedQueueint was not fulfilled within 20 seconds.
2024-12-20T18:08:43.0680620Z 	at org.geoserver.monitor.PipeliningTaskQueueTest.test(PipeliningTaskQueueTest.java:59) …
```
> Monitor tests: Github action slowness tolerance

- src/community/backup-restore/web/src/main/java/org/geoserver/backuprestore/web/BackupRestoreDataPage.html
- src/community/backup-restore/web/src/main/java/org/geoserver/backuprestore/web/style.css
- src/community/elasticsearch/src/main/java/org/geoserver/elasticsearch/ElasticConfigurationPage.java
- src/community/security/oauth2/oauth2-web/src/main/java/org/geoserver/web/security/oauth2/GeoServerOAuth2AuthProviderPanel.html
- src/community/taskmanager/core/bin/src/main/resources/org/geoserver/taskmanager/web/panel/FileUploadPanel.html
- src/community/taskmanager/core/bin/src/main/resources/org/geoserver/taskmanager/web/styleTaskManager.css
- src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/web/panel/FileUploadPanel.java
- src/community/taskmanager/core/src/main/resources/org/geoserver/taskmanager/web/panel/FileUploadPanel.html
- src/community/taskmanager/core/src/main/resources/org/geoserver/taskmanager/web/styleTaskManager.css
- src/extension/authkey/src/main/java/org/geoserver/security/web/AuthenticationKeyFilterPanel.html
- src/extension/authkey/src/main/java/org/geoserver/security/web/AuthenticationKeyFilterPanel.java
- src/extension/authkey/src/main/java/org/geoserver/security/web/WebServiceBodyResponseUserGroupServicePanel.html
- src/extension/authkey/src/main/java/org/geoserver/security/web/WebServiceBodyResponseUserGroupServicePanel.java
- src/extension/importer/web/src/main/java/org/geoserver/importer/web/ImportDataPage.html
- src/extension/importer/web/src/main/java/org/geoserver/importer/web/ImportTaskTable$ExceptionPanel.html
- src/extension/importer/web/src/main/java/org/geoserver/importer/web/ImportTaskTable$LayerLinkPanel.html
- src/extension/importer/web/src/main/java/org/geoserver/importer/web/ImportTaskTable$LayerPreviewPanel.html
- src/extension/importer/web/src/main/java/org/geoserver/importer/web/ImportTaskTable$NoCRSPanel.html
- src/extension/importer/web/src/main/java/org/geoserver/importer/web/ImportTaskTable.java
- src/extension/importer/web/src/main/java/org/geoserver/importer/web/JobQueuePanel.html
- src/extension/importer/web/src/main/java/org/geoserver/importer/web/style.css
- src/extension/security/web/web-cas/src/main/java/org/geoserver/security/web/cas/CasAuthFilterPanel.html
- src/web/core/src/main/java/org/geoserver/web/GeoServerLoginPage.html
This PR should fix all of the remaining CSP violations from the Wicket 9 upgrade after https://github.com/geoserver/geoserver/pull/8053 is merged. I do not use any of the extensions or community modules so those changes are completely untested by me but I'm putting it here if anyone is interested.
> Fixed some Wicket CSP violations

- doc/en/user/source/community/datadir-catalog-loader/index.rst
- doc/en/user/source/community/index.rst
Add documentation for the DataDirectory Catalog Loader community module
> Add documentation for the DataDirectory Catalog Loader community module

- src/extension/printing/pom.xml
- src/release/ext-printing.xml
`xml-apis:xml-apis-xerces:2.7.1` is the same as
`xml-apis:xml-apis` but from 2012 and unnecessary since Java 1.6.
> Remove dependency on xml-apis-xerces on the printing extension

- doc/en/developer/source/eclipse-guide/index.rst
- doc/en/developer/source/quickstart/intellij.rst
fix a typo introduced with https://github.com/geoserver/geoserver/pull/8158  
> fix typo ASOP -> AOSP

- src/community/ogcapi/dggs/dggs-core/pom.xml
[![GEOS-11671](https://badgen.net/badge/JIRA/GEOS-11671/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11671) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Simple dependency upgrade
> [GEOS-11671] Upgrade H3 dependency to 3.7.3

- .github/workflows/cite.yml
- build/cite/Makefile
- build/cite/geotiff11/compose.override.yml
- build/cite/run-test.sh
One of the CITE tests allows to check compliance of a GeoTIFF file.
The implementation actually executes a few GeoTIFF extractions, from WMS and WCS, and checks the results for each one, setting the stage for running multiple file oriented tests (which can be re-used for the KML and GeoPackage CITE tests).
For the tests to pass, https://github.com/geotools/geotools/pull/5033 must be merged first
> GeoTIFF CITE tests

- src/community/cog/cog-azure/src/assembly/assembly.xml
[![GEOS-11680](https://badgen.net/badge/JIRA/GEOS-11680/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11680) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
See linked for details.
> [GEOS-11680] Azure COG assembly lacks mandatory libraries, won't work

- src/pom.xml
> Upgrade FreeMarker from 2.3.33 to 2.3.34

- src/pom.xml
This dependency upgrade includes a security fix.
> Upgrade Wicket from 9.18.0 to 9.19.0

- src/pom.xml
> Upgrade Jackson from 2.17.2 to 2.18.2

- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLGenerator.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLGetFeatureInfoOutputFormat.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java
[![GEOS-11681](https://badgen.net/badge/JIRA/GEOS-11681/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11681) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11681] MapML raster GetFeatureInfo not working

- src/pom.xml
[![GEOS-11685](https://badgen.net/badge/JIRA/GEOS-11685/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11685) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11685] Bump jetty.version from 9.4.56.v20240826 to 9.4.57.v20241219

- src/wms/src/main/java/org/geoserver/sld/SLDXmlRequestReader.java
- src/wms/src/test/java/org/geoserver/sld/SLDXmlRequestReaderTest.java
[![GEOS-11682](https://badgen.net/badge/JIRA/GEOS-11682/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11682) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11682] Add tests for WMS SLD XML request reader

- doc/en/user/source/extensions/printing/protocol.rst
- doc/en/user/source/geowebcache/config.rst
- doc/en/user/source/geowebcache/index.rst
- doc/en/user/source/geowebcache/using.rst
- doc/en/user/source/geowebcache/webadmin/defaults.rst
- doc/en/user/source/services/wms/googleearth/tutorials/superoverlaysgwc.rst
I was looking at the GWC docs within Geoserver, such as [GeoWebCache — GeoServer 2.27.x User Manual](https://docs.geoserver.org/latest/en/user/geowebcache/index.html#gwc) & [Using GeoWebCache — GeoServer 2.27.x User Manual](https://docs.geoserver.org/latest/en/user/geowebcache/using.html)
These pages have links to the main GeoWebCache documentation, but they link to the domain _http://geowebcache.org_ This seems to be an obsolete domain, which is currently domain parked. It should instead point to _https://geowebcache.osgeo.org/_.
This PR fixes the dead links, and links to the correct pages.
- [✓] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [-] I have sent a [Contribution Licence …
> fix: Updated the GWC URLs

- src/community/ogcapi/dggs/dggs-clickhouse/src/main/java/org/geotools/dggs/clickhouse/ClickHouseDialect.java
- src/community/ogcapi/dggs/dggs-clickhouse/src/main/java/org/geotools/dggs/clickhouse/ClickHouseFilterToSQL.java
- src/community/ogcapi/dggs/dggs-clickhouse/src/test/java/org/geotools/dggs/clickhouse/ClickHouseDateOnlineTest.java
- src/community/ogcapi/dggs/dggs-clickhouse/src/test/java/org/geotools/dggs/clickhouse/ClickHouseDateTestSetup.java
[![GEOS-11686](https://badgen.net/badge/JIRA/GEOS-11686/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11686) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11686] Clickhouse DGGS stores cannot properly read dates

- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLFeaturesBuilder.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLSimplifier.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/RoundingPrecisionTransformer.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLStyleVisitorTest.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSFeatureTest.java
[![GEOS-11683](https://badgen.net/badge/JIRA/GEOS-11683/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11683) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
refined test
added hint
cleanup
> [GEOS-11683] MapML WMS Features Coordinate Precision Should be adjusted based on scale

- src/community/ogcapi/dggs/ogcapi-dggs-assembly/src/assembly/assembly.xml
- src/community/ogcapi/ogcapi-coverages-assembly/src/assembly/assembly.xml
- src/community/ogcapi/ogcapi-images-assembly/src/assembly/assembly.xml
- src/community/ogcapi/ogcapi-maps-assembly/src/assembly/assembly.xml
- src/community/ogcapi/ogcapi-styles-assembly/src/assembly/assembly.xml
- src/community/ogcapi/ogcapi-tiles-assembly/src/assembly/assembly.xml
[![GEOS-11687](https://badgen.net/badge/JIRA/GEOS-11687/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11687) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11687] OGC API packages contain the gs-web-core jar

- src/community/ogcapi/dggs/ogcapi-dggs-assembly/src/assembly/assembly.xml
- src/community/ogcapi/ogcapi-coverages-assembly/src/assembly/assembly.xml
- src/community/ogcapi/ogcapi-features-assembly/src/assembly/assembly.xml
- src/community/ogcapi/ogcapi-images-assembly/src/assembly/assembly.xml
- src/community/ogcapi/ogcapi-maps-assembly/src/assembly/assembly.xml
- src/community/ogcapi/ogcapi-styles-assembly/src/assembly/assembly.xml
- src/community/ogcapi/ogcapi-tiles-assembly/src/assembly/assembly.xml
[![GEOS-11687](https://badgen.net/badge/JIRA/GEOS-11687/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11687) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
https://github.com/geoserver/geoserver/pull/8214 backport
> [2.26.x backport] [GEOS-11687] OGC API packages contain gs-web-core

- src/community/ogcapi/dggs/ogcapi-dggs-assembly/src/assembly/assembly.xml
- src/community/ogcapi/ogcapi-coverages-assembly/src/assembly/assembly.xml
- src/community/ogcapi/ogcapi-features-assembly/src/assembly/assembly.xml
- src/community/ogcapi/ogcapi-images-assembly/src/assembly/assembly.xml
- src/community/ogcapi/ogcapi-maps-assembly/src/assembly/assembly.xml
- src/community/ogcapi/ogcapi-styles-assembly/src/assembly/assembly.xml
- src/community/ogcapi/ogcapi-tiles-assembly/src/assembly/assembly.xml
[![GEOS-11687](https://badgen.net/badge/JIRA/GEOS-11687/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11687) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
https://github.com/geoserver/geoserver/pull/8214 backport to 2.25.x
> [2.25.x backport] [GEOS-11687] OGC API packages contain gs-web-core

- src/gwc/src/main/java/org/geoserver/gwc/wmts/GWCResourceServiceVoter.java
- src/web/core/src/main/java/org/geoserver/web/ServiceDescriptionProvider.java
- src/web/gwc/src/main/java/org/geoserver/gwc/web/GWCServiceDescriptionProvider.java
- src/web/gwc/src/test/java/org/geoserver/gwc/web/GWCServiceLinksTest.java
- src/web/wcs/src/main/java/org/geoserver/wcs/web/WCSServiceDescriptionProvider.java
- src/web/wfs/src/main/java/org/geoserver/wfs/web/WFSServiceDescriptionProvider.java
[![GEOS-11672](https://badgen.net/badge/JIRA/GEOS-11672/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11672) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Allows WMTS to be selectable as a serivce to disable; and will only list WMTS servivces if TileLayer is defined for the layer or LayerGroup.
Noticed reuse the GWC "voter" to avoid duplicating logic (such as checking for a tile layer).
> [GEOS-11672] WMTS layer service enablement

- build/cite/wfs20/citewfs-2.0/security/config.xml
- data/citecsw-2.0.2/security/config.xml
- data/citensg-1.0/security/config.xml
- data/release/security/config.xml
- src/main/src/main/java/org/geoserver/security/GeoServerSecurityFilterChain.java
- src/main/src/main/java/org/geoserver/security/GeoServerSecurityManager.java
- src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
- src/rest/src/test/java/org/geoserver/rest/IndexControllerTest.java
- src/security/security-tests/src/test/java/org/geoserver/security/auth/AuthenticationFilterTest.java
[![GEOS-11664](https://badgen.net/badge/JIRA/GEOS-11664/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11664) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR updates the security config to properly handle the base REST path with an extension. Existing config files with the old REST paths will be automatically updated to the new REST paths.
GeoServer unit tests don't seem to verify that a user is allowed to access a specific URL path so I don't know how to create a unit test for this.
> [GEOS-11664] Update REST security paths

- src/wfs/src/main/java/org/geoserver/wfs/InsertElementHandler.java
- src/wfs/src/test/java/org/geoserver/wfs/TransactionListenerTest.java
- src/wfs/src/test/java/org/geoserver/wfs/TransactionListenerTester.java
[![GEOS-11673](https://badgen.net/badge/JIRA/GEOS-11673/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11673) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11673] : [WFS-T] : Features order in transaction not respected

- doc/en/user/source/community/oauth2/oidc.rst
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectFilterConfig.java
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdConnectIntegrationTest.java
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.html
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.java
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/resources/GeoServerApplication.properties
- src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/test/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanelTest.java
- src/community/security/oauth2/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilter.java
- src/main/src/main/java/org/geoserver/security/filter/GeoServerSecurityFilter.java
[![GEOS-11694](https://badgen.net/badge/JIRA/GEOS-11694/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11694) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
See ticket and new docs for details
> [GEOS-11694] OpenID connect: allow caching authentication when an expiration is declared in the access token

- CONTRIBUTING.md
Missed in [GEOS-11659], update the CONTRIBUTING.md file to reflect the usage of Palantir Java format.
> Replace google-java-format by palantir in CONTRIBUTING.md

- src/pom.xml
[![GEOS-11701](https://badgen.net/badge/JIRA/GEOS-11701/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11701) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11701] Update JAI-Ext to 1.1.28

- doc/en/user/source/installation/war.rst
- recommend Tomcat v9, not 7+
- change Tomcat and Jetty links to HTTPS
- change Jetty link to project's current URL
> Update Tomcat recommendation, update external links

- src/pom.xml
[![GEOS-11701](https://badgen.net/badge/JIRA/GEOS-11701/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11701) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [Backport 2.25.x] [GEOS-11701] Update JAI-Ext to 1.1.28

- src/pom.xml
> Upgrade commons-lang3 from 3.15.0 to 3.17.0

- src/pom.xml
> Upgrade commons-io from 2.16.1 to 2.18.0

- src/pom.xml
> Upgrade Wicket from 9.19.0 to 9.20.0

- src/extension/vectortiles/src/main/java/org/geoserver/wms/geojson/GeoJsonWMSBuilder.java
- src/extension/vectortiles/src/main/java/org/geoserver/wms/topojson/TopologyBuilder.java
- src/pom.xml
- src/web/demo/src/main/java/org/geoserver/web/demo/DemoRequestsPage.java
This is just a regular dependency upgrade. There are some minor code changes to refactor using newly deprecated API.
> Upgrade guava from 33.2.1 to 33.4.0

- src/extension/ogr/ogr-wfs/src/main/java/org/geoserver/wfs/response/OGRWrapper.java
- src/web/app/pom.xml
[![GEOS-11707](https://badgen.net/badge/JIRA/GEOS-11707/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11707) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Address incompatibility with ``ogr2ogr --help`` and ``ogr2ogr --long-format`` not listing formats.
> [GEOS-11707] Use ogr2ogr --formats to obtain supported formats

- src/web/core/src/main/java/org/geoserver/web/wicket/GSModalWindow$ContentsPanel.html
- src/web/core/src/main/java/org/geoserver/web/wicket/GSModalWindow.java
- src/web/core/src/main/java/org/geoserver/web/wicket/modal/GSModalWindow.css
- src/web/core/src/main/java/org/geoserver/web/wicket/modal/GSModalWindow.js
- src/web/core/src/main/java/org/geoserver/web/wicket/modal/modal.css
[![GEOS-11657](https://badgen.net/badge/JIRA/GEOS-11657/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11657) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Created from @davidblasby https://github.com/geoserver/geoserver/pull/8247, breakout out as a distinct PR (to avoid fixes that need to be back ported):
This PR is for adding Drag/Resize to the (wicket) GSModalWindow, also found related https://github.com/geoserver/geoserver/pull/8259
https://github.com/user-attachments/assets/bc3c02de-2c1a-44ec-8e97-021f95d111ff
1. Move/resize.  This is mostly done in Javascript - see …
> [GEOS-11657] add drag/resize to GSDialogWindow

- src/pom.xml
> Upgrade jsoup from 1.18.1 to 1.18.3

- src/pom.xml
commons-lang 2 is still included in GeoServer because of a transitive dependency from json-lib.
> Upgrade commons-lang from 2.5 to 2.6

- src/pom.xml
> Upgrade easymock from 5.4.0 to 5.5.0

- src/pom.xml
> Upgrade mockito from 5.12.0 to 5.15.2

- src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACSortablesMapper.java
- src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/SearchTest.java
[![GEOS-11715](https://badgen.net/badge/JIRA/GEOS-11715/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11715) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11715] STAC sortby won't work with properties. prefixed names

- build/cite/wcs10/citewcs-1.0/wmts.xml
- build/cite/wcs11/citewcs-1.1/wmts.xml
Currently the home page does not show, with this error, because wmts.xml is missing:
```
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:175)
... 134 more
Caused by: java.lang.NullPointerException: Cannot invoke …
```
> Fix home page in WCS CITE test data dirs

- src/pom.xml
> Upgrade oshi-core from 6.6.3 to 6.6.6

- src/pom.xml
> Upgrade wiremock from 3.10.0 to 3.11.0

- src/pom.xml
> Upgrade commons-text from 1.12.0 to 1.13.0

- src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
- src/extension/geofence/geofence/src/test/java/org/geoserver/geofence/GeofenceAccessManagerTest.java
[![GEOS-11700](https://badgen.net/badge/JIRA/GEOS-11700/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11700) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Improved IP address parsing allowing formats:
- `ipv4`
- `ipv4:port`
- `ipv6`
- `[ipv6]`
- `[ipv6]:port`
- `hostname`
- `hostname:port`
> [GEOS-11700] GeoFence fails in recognizing some caller IP address

- src/pom.xml
This is just a test dependency upgrade. The junit-bom is now used to manage the versions of all junit-jupiter dependencies.
> Upgrade junit-upiter from 5.10.1 to 5.11.4

- src/pom.xml
> Upgrade commons-logging from 1.2 to 1.3.5

- src/pom.xml
> Upgrade commons-beanutils from 1.9.4 to 1.10.1

- src/pom.xml
> Upgrade hazelcast from 5.3.6 to 5.3.8

- src/pom.xml
> Upgrading JAI-EXT to 1.1.29

- src/extension/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIDispatcher.java
- src/extension/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIRequestInfo.java
- src/extension/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/APIRequestInfoTest.java
- src/extension/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/HelloServiceTest.java
- src/extension/ogcapi/ogcapi-features/pom.xml
- src/extension/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/LandingPageTest.java
- src/main/src/main/java/org/geoserver/ows/DisabledServiceCheck.java
- src/main/src/main/java/org/geoserver/security/csp/CSPHeaderDAO.java
- src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
- src/wfs/src/test/java/org/geoserver/wfs/GetCapabilitiesTest.java
[![GEOS-11724](https://badgen.net/badge/JIRA/GEOS-11724/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11724) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This prevents dispatcher calling a disabled per-layer service.
> [GEOS-11724] DisabledServiceCheck check resource disabled service list

- doc/en/developer/source/release/guide/index.rst
> [GEOS-11572] Release process update job geoserver-main-nightly for docker

- doc/en/user/source/installation/docker.rst
- doc/en/user/source/services/features/install.rst
- doc/en/user/source/styling/ysld/installing.rst
[![GEOS-11572](https://badgen.net/badge/JIRA/GEOS-11572/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11572) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Now that 2.27.x is working some of the examples need to be updated (were showing up as 2.27-SNAPSHOT for example).
> [GEOS-11572] Update docker instructions for 2.27.x

- src/community/jdbcconfig/pom.xml
- src/extension/app-schema/app-schema-oracle-test/pom.xml
- src/extension/app-schema/app-schema-test/pom.xml
- src/extension/oracle/pom.xml
- src/extension/wps-jdbc/pom.xml
- src/pom.xml
- src/release/ext-oracle.xml
- src/release/extensions/oracle/oracle-README.md
- src/web/app/pom.xml
[![GEOS-11743](https://badgen.net/badge/JIRA/GEOS-11743/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11743) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
related: https://github.com/geotools/geotools/pull/5118
> [GEOS-11743] Upgrade Oracle JDBC driver (ojdbc) from 8 to 11

- doc/en/README.md
- doc/en/user/source/configuration/properties/index.rst
- doc/en/user/source/installation/war.rst
Address feedback from chat wondering why Tomcat 10 is not working. The discussion of Servlet version was not clear enough.
> Please do not use Tomcat 10

- doc/en/user/source/configuration/crshandling/coordtransforms.rst
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLGetFeatureOutputFormatTest.java
[![GEOT-7716](https://badgen.net/badge/JIRA/GEOT-7716/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7716) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Follow up on GEOT-7716.
Depends on 
https://github.com/geotools/geotools/pull/5126
> GEOT-7716: Follow up on EPSG DB Update (11.0.31)

- src/pom.xml
[![GEOS-11754](https://badgen.net/badge/JIRA/GEOS-11754/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11754) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
See release notes https://github.com/mapfish/mapfish-print-v2/releases/tag/release%2F2.3.3 for changes.
I synchronized the mapfish-print-v2 pom.xml with the versions used by GeoServer, but still need to wait for this PR QA process to see how successful the changes are. 
The PR will be merged when all the build checks are green ([see automated QA …
> [GEOS-11754] Update mapfish-print-v2 to 2.3.3

- src/pom.xml
[![GEOS-11763](https://badgen.net/badge/JIRA/GEOS-11763/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11763) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
For the fix of https://github.com/geosolutions-it/jai-ext/issues/309 jai-ext needs to be updated to the latest version (1.1.30) that contains the fix. 
> [GEOS-11763] Update jai-ext to latest version (1.1.30)

- doc/en/user/source/services/wcs/vendor.rst
- doc/en/user/source/services/wms/vendor.rst
- src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/WCSNetCDFMosaicTest.java
- src/main/src/main/java/org/geoserver/ows/kvp/ClipGeometryParser.java
- src/wcs/src/main/java/applicationContext.xml
- src/wcs/src/main/java/org/geoserver/wcs/WCSCoverageClipCallback.java
- src/wcs/src/main/java/org/vfny/geoserver/util/WCSUtils.java
- src/wcs2_0/src/main/java/applicationContext.xml
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/GranuleStackClipCallback.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/GetCoverageKvpTest.java
- src/wms/src/main/java/org/geoserver/wms/clip/ClipWMSGetMapCallBack.java
[![GEOS-11761](https://badgen.net/badge/JIRA/GEOS-11761/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11761) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11761] Add support for the clip vendor parameter to WCS as well

- doc/en/user/source/services/wcs/vendor.rst
- doc/en/user/source/services/wms/vendor.rst
- src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/WCSNetCDFMosaicTest.java
- src/main/src/main/java/org/geoserver/ows/kvp/ClipGeometryParser.java
- src/wcs/src/main/java/applicationContext.xml
- src/wcs/src/main/java/org/geoserver/wcs/WCSCoverageClipCallback.java
- src/wcs/src/main/java/org/vfny/geoserver/util/WCSUtils.java
- src/wcs2_0/src/main/java/applicationContext.xml
- src/wcs2_0/src/main/java/org/geoserver/wcs2_0/GranuleStackClipCallback.java
- src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/GetCoverageKvpTest.java
- src/wms/src/main/java/org/geoserver/wms/clip/ClipWMSGetMapCallBack.java
[![GEOS-11761](https://badgen.net/badge/JIRA/GEOS-11761/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11761) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
2.26.x backport of https://github.com/geoserver/geoserver/pull/8395
> [Backport 2.26.x] [GEOS-11761] Add support for the clip vendor parameter to WCS as well

- doc/en/developer/source/policies/security.rst
- doc/en/developer/source/release/guide/index.rst
Moving the write a blog post instructions earlier in the process as something that can be worked on while release jobs are going. There is no policy change here, only examples and cross linking to security policy.
Documented build server environmental variable for docker main job.
> Release guide clarifications and blog post examples for upcoming 2.27.0 release

- src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
- src/main/src/main/java/org/vfny/geoserver/util/DataStoreUtils.java
[![GEOS-11766](https://badgen.net/badge/JIRA/GEOS-11766/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11766) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Checking out the data dir loader PR I've found this two issues affecting the performance of startup.
There are no tests as the code is achieving the same goals in a different way
The PR will be merged when all the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)), there is a code committer review, and the checklist has been …
> [GEOS-11766] Speed up CRS and store factory lookups during catalog loading

- src/pom.xml
[![GEOS-11770](https://badgen.net/badge/JIRA/GEOS-11770/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11770) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Dependency update
> [GEOS-11770] Update to jai-ext 1.1.31

- doc/en/user/source/community/flatgeobuf/index.rst
- doc/en/user/source/community/flatgeobuf/installing.rst
Just indicate that the community module also provides a datastore as well as an outputFormat.
> Improve FlatGeobuf docs ever so slightly

- src/pom.xml
[![GEOS-11770](https://badgen.net/badge/JIRA/GEOS-11770/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11770) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [2.25.x backport] [GEOS-11770] Update to jai-ext 1.1.31

- src/pom.xml
[![GEOS-11771](https://badgen.net/badge/JIRA/GEOS-11771/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11771) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11771] Update to Imageio-EXT 1.4.15

- doc/en/developer/source/policies/community-modules.rst
Fixed a formatting issue in the documentation for community modules developer policies.
> Fixed formatting issue in community modules developer policies.

- doc/en/user/source/community/monitor-micrometer/installation.rst
- src/community/monitor-micrometer/src/assembly/assembly.xml
[![GEOS-11782](https://badgen.net/badge/JIRA/GEOS-11782/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11782) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
The Monitor Micrometer community module added with #8374 was missing the assembly file for the build.
These changes add this file and update the installation instruction to include Docker usage.
The PR will be merged when all the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)), there is a code committer review, and the …
> [GEOS-11782] Added assembly file to Monitor Micrometer community module.

- doc/en/user/source/installation/upgrade.rst
Based discourse troubleshooting a warning to check proxy base url setting will prevent heartbreak.
> Docs: Check proxy base before updating

- doc/en/user/source/community/monitor-micrometer/installation.rst
Fixed a typo in the documentation for monitor micrometer community module.
> Fixed typo in monitor micrometer community module documentation.

- src/wms/src/main/resources/webresources/wms/OpenLayers2Map.js
- src/wms/src/main/resources/webresources/wms/OpenLayers3Map.js
[![GEOS-11767](https://badgen.net/badge/JIRA/GEOS-11767/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11767) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
The preview is using JPEG only since the javascript code was pushed outside of the freemarker template, the Jira ticket has an explanation as to what's happening.
> [GEOS-11767] Regression: OL preview always uses JPEG format

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/catalog/JDBCCatalogFacade.java
- src/main/src/main/java/org/geoserver/catalog/impl/AbstractCatalogFacade.java
- src/main/src/main/java/org/geoserver/catalog/impl/DefaultCatalogFacade.java
- src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java
Three recently added catalog tests are failing for jdbcconfig
* Two "exact term" tests actually had errors in the order of saving items to the catalog, that are forgiven by the default catalog since everything lives in memory.
* The sync test failed because the jdbccatalogfacade sync method was apparently faulty. Because it is quite similar to the "manual" sync of the defaultcatalogfacade I made a new method in AbstractCatalogFacade to avoid code duplication.
> JDBCConfig: Fix failing Catalog tests

- src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/catalog/JDBCCatalogFacade.java
- src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java
- src/main/src/test/java/org/geoserver/security/impl/DefaultResourceAccessManagerTest.java
- src/wfs/src/main/java/org/geoserver/wfs/xml/WFSXmlUtils.java
- src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureTest.java
I have made three separate changes (one commit for each) to address the issue(s).
(1) As by @groldan's suggestion, replace the wfs XML parser eager featuretype cache with a lazy one.
(2) Introduce a cache for security filters in the security system
(3) Improve the jdbcconfig caching for layer/resource links (which we may assume are one-to-one)
While either (1) or (2) by itself resolves this specific issue with WFS post requests; and (3) goes a long way, I decided to submit all three fixes because they will  each improve performance elsewhere.
[![GEOS-11726](https://badgen.net/badge/JIRA/GEOS-11726/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11726) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11e …
> GEOS-11726: slow post requests: caching improvements

- src/pom.xml
Moved dep version from 3.8-SNAPSHOT to 3.8.0
> GeoFence: use release version 3.8.0

- src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java
[![GEOS-11774](https://badgen.net/badge/JIRA/GEOS-11774/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11774) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
I have tested that this fix works as expected in a 2.27.x setup.
There is no unit test, because I dodn't know how to write them in this plugin.
> [GEOS-11774] Logout with OAuth plugin will give error if logged in locally

- src/restconfig/src/main/java/org/geoserver/rest/catalog/LayerGroupController.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/StyleController.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/WMSLayerController.java
- src/restconfig/src/main/java/org/geoserver/rest/catalog/WMTSLayerController.java
- src/restconfig/src/main/java/org/geoserver/rest/resources/ResourceController.java
[![GEOS-11791](https://badgen.net/badge/JIRA/GEOS-11791/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11791) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> GEOS-11791: REST controller logging details after validation

- build/cite/docker-compose.yml
I discovered that the environment and healthcheck parameters were ignored in the previous version.
> Fix YAML multi-level anchor in docker-compose.yml

- src/extension/csw/web-csw/src/main/java/org/geoserver/csw/web/CSWServiceDescriptionProvider.java
- src/extension/ogcapi/web-ogcapi/src/main/java/org/geoserver/web/ogcapi/OgcApiServiceDescriptionProvider.java
- src/extension/ogcapi/web-ogcapi/src/test/java/org/geoserver/web/ogcapi/OgcApiServiceDescriptionProviderTest.java
- src/extension/wps/web-wps/src/main/java/org/geoserver/wps/web/WPSServiceDescriptionProvider.java
- src/main/src/main/java/org/geoserver/ows/DisabledServiceCheck.java
- src/web/core/src/main/java/org/geoserver/web/ServiceDescriptionProvider.java
- src/web/core/src/main/java/org/geoserver/web/ServiceInfoCapabilitiesProvider.java
- src/web/core/src/test/java/org/geoserver/web/CapabilitiesHomePagePanelTest.java
- src/web/core/src/test/java/org/geoserver/web/FakeServiceDescriptionProvider.java
- src/web/core/src/test/resources/applicationContext.xml
- src/web/gwc/src/main/java/org/geoserver/gwc/web/GWCServiceDescriptionProvider.java
- src/web/rest/src/main/java/org/geoserver/web/RESTServiceDescriptionProvider.java
- src/web/wcs/src/main/java/org/geoserver/wcs/web/WCSServiceDescriptionProvider.java
- src/web/wfs/src/main/java/org/geoserver/wfs/web/WFSServiceDescriptionProvider.java
- src/web/wms/src/main/java/org/geoserver/wms/web/WMSServiceDescriptionProvider.java
[![GEOS-11792](https://badgen.net/badge/JIRA/GEOS-11792/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11792) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This only occurred when no workspaces were available; but was still annoying. 
> [GEOS-11792] Fix welcome page listing all services via sevice caps

- src/release/src/markdown/README.md
> README.html user forum update

- doc/en/developer/source/cite-test-guide/index.rst
> Capitalise CITE correctly in cite-test-guide

- doc/en/developer/source/cite-test-guide/index.rst
> Update available suites in cite-test-guide

- src/ows/src/main/java/org/geoserver/ows/kvp/URLKvpParser.java
- src/platform/src/main/java/org/geoserver/platform/resource/Paths.java
- src/web/core/src/main/java/org/geoserver/web/CapabilitiesHomePagePanel.java
- src/wms/src/main/java/org/geoserver/wms/featureinfo/FreeMarkerTemplateManager.java
> Fix missing deprecation warnings thrown in IntelliJ IDE

- doc/en/user/source/extensions/netcdf/netcdf.rst
[![GEOT-7742](https://badgen.net/badge/JIRA/GEOT-7742/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7742) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
See https://github.com/geotools/geotools/pull/5145
> Documentation following up GEOT-7742

- doc/en/user/source/community/hz-cluster/index.rst
- doc/en/user/source/community/index.rst
> Documentation for the hz-clustering community module

- src/web/core/src/main/java/org/geoserver/web/data/layer/CoverageViewEditor.html
[![GEOS-11797](https://badgen.net/badge/JIRA/GEOS-11797/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11797) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11797]: minor fix on coverageViewEditor page (remove style)

- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLDocumentBuilder.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java
[![GEOS-11799](https://badgen.net/badge/JIRA/GEOS-11799/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11799) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport #8492
**Authored by:** @prushforth
> [Backport 2.26.x] [GEOS-11799] Serialize <map-link rel="legend"> in MapML response

- doc/en/developer/source/policies/security.rst
> update placeholder instructions to hide vulnerabilities until disclosure

- build/qa/pmd-ruleset.xml
- src/community/jms-cluster/activemqBroker/src/test/java/org/geoserver/web/Start.java
- src/extension/ogcapi/web-ogcapi/src/main/java/org/geoserver/web/ogcapi/OgcApiServiceDescriptionProvider.java
- src/extension/ogcapi/web-ogcapi/src/test/java/org/geoserver/web/ogcapi/OgcApiServiceDescriptionProviderTest.java
- src/extension/wps/web-wps/src/main/java/org/geoserver/wps/web/WPSRequestBuilder.java
- src/extension/wps/web-wps/src/main/java/org/geoserver/wps/web/WPSRequestBuilderPanel.java
- src/extension/wps/web-wps/src/test/java/org/geoserver/wps/web/WPSRequestBuilderTest.java
- src/platform/src/main/java/org/geoserver/platform/SystemEnvironmentStatus.java
- src/platform/src/main/java/org/geoserver/platform/SystemPropertyStatus.java
- src/platform/src/test/java/org/geoserver/platform/SystemEnvironmentTest.java
- src/platform/src/test/java/org/geoserver/platform/SystemPropertiesStatusTest.java
- src/release/installer/mac/console/src/main/java/org/geoserver/console/GeoServerConsole.java
- src/web/core/src/main/java/org/geoserver/web/AboutGeoServerPage.java
- src/web/core/src/main/java/org/geoserver/web/ServicesPanel.java
- src/web/core/src/test/java/org/geoserver/web/GeoServerHomePageTest.java
- src/web/demo/src/main/java/org/geoserver/web/demo/DemoRequestsPage.java
- src/web/demo/src/test/java/org/geoserver/web/demo/DemoRequestsPageTest.java
- src/web/wcs/src/main/java/org/geoserver/wcs/web/demo/WCSRequestBuilder.java
- src/web/wcs/src/main/java/org/geoserver/wcs/web/demo/WCSRequestBuilderPanel.java
[![GEOS-11804](https://badgen.net/badge/JIRA/GEOS-11804/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11804) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
@jodygarnett do you want to review?
> [GEOS-11804] Disallow usage of var in GeoServer source code

- src/community/features-templating/features-templating-web/src/main/java/org/geoserver/featurestemplating/web/TemplateConfigurationPage.java
[![GEOS-11811](https://badgen.net/badge/JIRA/GEOS-11811/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11811) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-11811
Features templating editor is unable to update and save the template body.  Any change made on the editor is not saved or reflected on the templating processing.  Only upload file and apply works currently.
This PR introduce a UI fix that is currently manual tested due to its Javascript runtime dependency on browser.
The PR will …
> [GEOS-11811] Fix features templating editor unable to save content

- doc/en/docguide/source/sphinx.rst
The page Sphinx Syntax has a link to the Sphinx Primer for reStructuredText which referenced a website that is no longer active.
This PR proposes changing this to a non-version specific page on the Sphinx documentation site (authoritative). 
> Quickfix - Documentation - Link to Sphinx Primer for reStructuredText updated to sphinx-doc.org

- src/community/features-templating/features-templating-ogcapi/src/main/java/org/geoserver/featurestemplating/ogcapi/TemplateCallBackOGC.java
- src/community/features-templating/features-templating-ogcapi/src/test/java/org/geoserver/featurestemplating/response/GMLComplexFeatureResponseAPITest.java
[![GEOS-11816](https://badgen.net/badge/JIRA/GEOS-11816/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11816) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-11816
> [GEOS-11816] Features templating OGC API fetch by ID fails

- doc/en/user/source/configuration/properties/index.rst
- doc/en/user/source/data/webadmin/workspaces.rst
- src/web/core/src/main/java/org/geoserver/web/data/workspace/WorkspaceEditPage.java
- src/web/core/src/main/java/org/geoserver/web/services/BaseServiceAdminPage.java
- src/web/wfs/src/test/java/org/geoserver/wfs/web/WFSAdminPageTest.java
[![GEOS-11810](https://badgen.net/badge/JIRA/GEOS-11810/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11810) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
The property WORKSPACE_ADMIN_SERVICE_ACCESS has been created to allow Workspace Admins to have access to manage the settings for OGC features. When the settings is set to true(case insensitive) it will allow access for Worskpace Admin to change properties in services in their workspace.
- [☑️] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [☑️] I have sent a …
> [GEOS-11810] New application setting to allow access by Workspace Admin

- src/extension/geofence/geofence-server/src/main/java/org/geoserver/geofence/server/web/GeofenceServerAdminPage.java
- src/extension/geofence/geofence-server/src/main/java/org/geoserver/geofence/server/web/GeofenceServerPage.java
- src/web/core/src/main/java/org/geoserver/web/wicket/GeoServerDNDBehavior.java
- src/web/core/src/main/java/org/geoserver/web/wicket/ReorderableTablePanel.java
- src/web/core/src/main/java/org/geoserver/web/wicket/gs-wicket-dnd.js
- src/web/core/src/test/java/org/geoserver/web/data/layergroup/LayerGroupEditPageTest.java
[![GEOS-11817](https://badgen.net/badge/JIRA/GEOS-11817/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11817) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR adds a Wicket Behavior that adds JavaScript to the page to overwrite a wicket-dnd function that causes a CSP violation with a patched version that does not have the CSP violation. The CSP violation is preventing the page from completing the AJAX request which causes the GUI spinner to not disappear and can prevent other AJAX functionality on the page.
Before the patch, the patched function eventually called `new …
> [GEOS-11817] GUI spinner remains after drag and drop

- doc/en/user/source/configuration/properties/index.rst
Update the documentation to include variables for parametrized catalog 
> Add parametrized catalog variables

- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/gs/PagedUniqueProcess.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/WPSTestSupport.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/H2PagedUniqueTest.java
- src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/PagedUniqueProcessTest.java
[![GEOS-11818](https://badgen.net/badge/JIRA/GEOS-11818/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11818) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11818] PageUniqueProcess regression after [GEOT-7628]

- src/community/oseo/oseo-service/src/main/java/org/geoserver/opensearch/eo/OSEODispatcherCallback.java
- src/community/oseo/oseo-service/src/test/java/org/geoserver/opensearch/eo/SearchTest.java
[![GEOS-11831](https://badgen.net/badge/JIRA/GEOS-11831/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11831) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> GEOS-11831: oseo callback improvements

- build/qa/pmd-junit-ruleset.xml
- src/community/ogcapi/dggs/dggs-clickhouse/src/test/java/org/geotools/dggs/clickhouse/ClickHouseGeometrylessOnlineTest.java
- src/community/ogcapi/dggs/dggs-clickhouse/src/test/java/org/geotools/dggs/clickhouse/ClickHouseRHealPixOnlineTest.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java
- src/pom.xml
[![GEOS-11834](https://badgen.net/badge/JIRA/GEOS-11834/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11834) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Avoid all warnings about JUnit4 checks being deprecated and update PMD while on it
> [GEOS-11834] Update PMD to 7.13

- src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/data/store/panel/SmartDataLoaderStoreEditPanel.java
[![GEOS-11830](https://badgen.net/badge/JIRA/GEOS-11830/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11830) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-11725
> [GEOS-11830] Smart data loader create store page fails when environment variables are in use

- src/extension/geofence/geofence-server/src/test/java/org/geoserver/geofence/server/rest/RulesRestControllerTest.java
- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLDocumentBuilder.java
- src/extension/rat/src/test/java/org/geoserver/rat/RasterAttributeTableTest.java
- src/main/src/test/java/org/geoserver/config/util/XStreamPersisterTest.java
- src/pom.xml
- src/restconfig/src/test/java/org/geoserver/rest/system/status/MonitorRestTest.java
- src/wms/src/test/java/org/geoserver/wms/map/GetMapIntegrationTest.java
- src/wms/src/test/java/org/geoserver/wms/map/RenderTimeStatisticsTest.java
[![GEOS-11836](https://badgen.net/badge/JIRA/GEOS-11836/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11836) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11836] Upgrade ErrorProne to 2.31.0

- doc/en/developer/source/maven-guide/index.rst
- doc/en/developer/source/policies/community-modules.rst
- src/community/backup-restore/core/pom.xml
- src/community/jms-cluster/activemqBroker/pom.xml
- src/community/taskmanager/core/bin/pom.xml
- src/community/taskmanager/core/pom.xml
- src/extension/security/cas/pom.xml
- src/main/pom.xml
- src/pom.xml
- src/rest/pom.xml
- src/restconfig/pom.xml
- src/security/ldap/pom.xml
- src/web/security/ldap/pom.xml
- src/wms/pom.xml
[![GEOS-11843](https://badgen.net/badge/JIRA/GEOS-11843/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11843) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
As part of the preparation work for the "GeoServer 3" migration to Spring 6, we'll use Maven Bill of Materials for dependency sets that provide them (e.g. the new GeoTools BOM will include BOMs for log4j, slf4j, and jackson).
For server projects, we're adding each individual spring and spring-security dependency, either to the root pom's dependencyManagement or in individual modules.
In order to centralize version …
> [GEOS-11843] Use Spring framework BOM to manage Spring and Spring Security dependencies

- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/v1/stac/collection.ftl
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/v1/stac/collections.ftl
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/v1/stac/collections.json
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/v1/stac/item.ftl
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/v1/stac/item_include.ftl
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/v1/stac/items-header.ftl
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/v1/stac/items.json
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/v1/stac/landingPage.ftl
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/v1/stac/queryables-collection.ftl
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/v1/stac/queryables-common.ftl
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/v1/stac/queryables-global.ftl
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/v1/stac/search-header.ftl
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/v1/stac/sortables-collection.ftl
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/v1/stac/sortables-common.ftl
- src/community/oseo/oseo-stac/src/main/resources/org/geoserver/ogcapi/v1/stac/sortables-global.ftl
[![GEOS-11708](https://badgen.net/badge/JIRA/GEOS-11708/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11708) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Breadcrumbs on STAC html pages were broken. STAC tempaltes were now changed to similar style than OGC features tempaltes have.
Fixing: https://osgeo-org.atlassian.net/browse/GEOS-11708  
The PR will be merged when all the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)), there is a code committer review, and the checklist …
> [GEOS-11708] STAC breadcrumbs rendering as plain text

- data/release/global.xml
[![GEOS-11855](https://badgen.net/badge/JIRA/GEOS-11855/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11855) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR removes the CogSettings section from the global.xml file which was unnecessarily added as part of the OGC API processes implementation (https://github.com/geoserver/geoserver/commit/c5db2fe167cac03bcd101cfbea3ba6343b3ead12). When the COG module is not installed, starting GeoServer from the default data directory will cause a couple of stack traces in the server logs that are harmless but look scary.
For core and …
> [GEOS-11855] Remove CogSettings from the release global.xml

- src/pom.xml
> Upgrade postgresql from 42.7.5 to 42.7.6

- src/pom.xml
This PR is a dependency upgrade with a security fix.
> Upgrade commons-beanutils from 1.10.1 to 1.11.0

- src/pom.xml
> Upgrade commons-io from 2.18.0 to 2.19.0

- src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLFeatureUtil.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLFormatOptionsMatrixTest.java
- src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLTestSupport.java
[![GEOS-11863](https://badgen.net/badge/JIRA/GEOS-11863/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11863) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
for cached raster coverages where appropriate.
The MapML module recently added the ability to request “vector” representation for raster data, which means encoding individual tile requests in a <map-tile row=”n” column=”m” zoom=”zn” src=”request url”> element.  The request url is currently always a tile-shaped WMS GetMap request, but it should be possible to get it to be a WMTS GetTile, but it never happens, though the core …
> [GEOS-11863] Use GetTile or GetMap requests in <map-tile src> 

- src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/domain/DomainModelBuilder.java
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/postgis/mockdata/meteo_int8_db.sql
[![GEOS-11819](https://badgen.net/badge/JIRA/GEOS-11819/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11819) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-11819
> [GEOS-11819] Make smart data loader skip unsupported column types

- src/web/core/src/main/java/org/geoserver/web/wicket/GeoServerTablePanel.java
- src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.html
- src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.java
- src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.js
- src/web/demo/src/test/java/org/geoserver/web/demo/MapPreviewPageTest.java
- src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayersPage.java
- src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayersPage.js
- src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/CachedLayersPageTest.java
[![GEOS-11862](https://badgen.net/badge/JIRA/GEOS-11862/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11862) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
This PR updates the Layer Preview and Tile Layers pages to execute the JavaScript code to set the event handlers every time the table is updated through filtering, paging or sorting.
This PR requires manually testing that the JavaScript is being executed correctly in the browser.
The PR will be merged when all the build checks are green ([see automated QA …
> [GEOS-11862] Layer Preview and Tile Layers page dropdown links broken after updating table

- src/web/core/src/main/java/org/geoserver/web/wicket/GeoServerTablePanel.java
- src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.html
- src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.java
- src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.js
- src/web/demo/src/test/java/org/geoserver/web/demo/MapPreviewPageTest.java
- src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayersPage.java
- src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayersPage.js
- src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/CachedLayersPageTest.java
[![GEOS-11862](https://badgen.net/badge/JIRA/GEOS-11862/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11862) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
2.27.x backport for https://github.com/geoserver/geoserver/pull/8611
> [Backport 2.27.x] [GEOS-11862] Layer Preview and Tile Layers page dropdown links broken after updating table

- .github/workflows/cite.yml
- build/cite/Makefile
- build/cite/ogcapi-tiles10/compose.override.yml
- build/cite/run-test.sh
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/v1/tiles/TiledCollectionDocument.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/v1/tiles/TilesAPIBuilder.java
- src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/ogcapi/v1/tiles/TilesService.java
- src/community/ogcapi/ogcapi-tiles/src/main/resources/org/geoserver/ogcapi/v1/tiles/openapi.yaml
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/v1/tiles/ApiTest.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/v1/tiles/ConformanceTest.java
- src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/ogcapi/v1/tiles/GetTileTest.java
- src/community/pom.xml
- src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
- src/web/app/pom.xml
See the various tickets for details.
It won't pass on the production TeamEngine, it should pass on the beta version though (needs a fix available in version 1.1 of the test suite).
> Execute and pass CITE tests for OGC API Tiles

- src/community/ogcapi/ogcapi-maps-assembly/pom.xml
[![GEOS-11880](https://badgen.net/badge/JIRA/GEOS-11880/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11880) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Simple POM dependency change
> [GEOS-11880] OGC API Maps is not showing up in GeoServer home page

- src/community/ogcapi/ogcapi-processes/src/main/java/org/geoserver/ogcapi/v1/processes/AbstractProcessIO.java
- src/community/ogcapi/ogcapi-processes/src/main/java/org/geoserver/ogcapi/v1/processes/ProcessDocument.java
- src/community/ogcapi/ogcapi-processes/src/main/resources/org/geoserver/ogcapi/v1/processes/process.ftl
- src/community/ogcapi/ogcapi-processes/src/test/java/org/geoserver/ogcapi/v1/processes/ProcessDescriptionTest.java
Small improvements for the usability of the process description resource
> OGC API process description, small fixes

- src/web/app/pom.xml
[![GEOS-11882](https://badgen.net/badge/JIRA/GEOS-11882/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11882) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
As described in https://osgeo-org.atlassian.net/browse/GEOS-11882 and https://osgeo-org.atlassian.net/browse/GEOS-11881, 
`postgis-jdbc:jar:1.3.3 ` includes some unwanted libs:
```
[INFO] +- org.postgis:postgis-jdbc:jar:1.3.3:compile
[INFO] |  \- org.postgis:postgis-stubs:jar:1.3.3:compile
[INFO] |     \- postgresql:postgresql:jar:8.3-603.jdbc4:compile
```
In this PR we are excluding them.
In a future PR we're going to …
> [GEOS-11882] Cleanup postgis-jdbc dependencies

- src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/TemplateCallback.java
- src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/GML3GetComplexFeatureTest.java
[![GEOS-11878](https://badgen.net/badge/JIRA/GEOS-11878/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11878) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-11878
> [GEOS-11878] WFS HITS request returns the whole data records on a GML feature templated layer

- src/extension/printing/pom.xml
[![GEOS-11879](https://badgen.net/badge/JIRA/GEOS-11879/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11879) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
See https://osgeo-org.atlassian.net/browse/GEOS-11879  
Added a dep to xalan:serializer to avoid random errors.
> [GEOS-11879] Xalan causes a java.lang.NoClassDefFoundError

- src/main/src/main/java/org/geoserver/catalog/CoverageViewReader.java
- src/main/src/test/java/org/geoserver/catalog/CoverageViewTest.java
[![GEOS-11877](https://badgen.net/badge/JIRA/GEOS-11877/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11877) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Backport for 2.27.x
> [GEOS-11877]:follow up, coverageView fixing fill missing bands

- src/pom.xml
Use latest GeoFence build that fixes/excludes some maven dependencies.
> Bump GeoFence to 3.8.1

- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/response/TemplateComplexTestSupport.java
- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/response/TemplateJSONSimpleTestSupport.java
- src/community/features-templating/features-templating-ogcapi/src/test/java/org/geoserver/featurestemplating/response/GMLComplexFeatureResponseAPITest.java
- src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/wfs/BaseTemplateGetFeatureResponse.java
- src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/wfs/GMLTemplateResponse.java
- src/extension/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIBodyMethodProcessor.java
- src/extension/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/FeatureTest.java
[![GEOS-11887](https://badgen.net/badge/JIRA/GEOS-11887/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11887) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-11887
> [GEOS-11887] Features Templating does not returns content type and charset header on OGC-API

- src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AttributesToPointGeometryTransform.java
- src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadAnimationProcess.java
- src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/ProcessListenerNotifier.java
- src/main/src/main/java/org/geoserver/ows/DisabledServiceCheck.java
- src/main/src/main/java/org/geoserver/security/DisabledServiceResourceFilter.java
- src/platform/src/main/java/org/geoserver/platform/resource/Resources.java
- src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPRoleService.java
- src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPUserGroupService.java
see https://github.com/geotools/geotools/pull/5283, should fix https://github.com/geoserver/geoserver/security/dependabot/464
> Fix deprecation warnings due to upstream commons-lang3 upgrade

- src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/domain/DomainModelBuilder.java
- src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/postgis/mockdata/meteo_int8_db.sql
[![GEOS-11819](https://badgen.net/badge/JIRA/GEOS-11819/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11819) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [2.27.x backport][GEOS-11819] Make smart data loader skip unsupported column types

- doc/en/user/source/community/monitor-micrometer/usage.rst
> fix typo in monitor-micrometer docs

- src/web/core/src/test/java/org/geoserver/web/data/workspace/WorkspaceProviderTest.java
[![GEOS-11892](https://badgen.net/badge/JIRA/GEOS-11892/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11892) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
It appears that due to current issues with wicket resulted from transition to java 17 some tests are being reported as passed, but in reality simply did not run.
One of such example is WorkspaceProviderTest which was passing when the original commit was contributed.
However when an attempt was made to created backports for it, the checks started to fail, mentioning WorkspaceProviderTest.
The call to …
> [GEOS-11892]:Column mentioning user that performed last modification for layers and stores list UI - fix Wicket tests

- src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/web/ClusterPage.html
[![GEOS-11910](https://badgen.net/badge/JIRA/GEOS-11910/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11910) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
- Fixed the existance of multiple classes which broke the JMS Cluster Extension settings section
> [GEOS-11910] JMS Cluster settings Section is not showing properly

- doc/en/user/source/introduction/gettinginvolved.rst
Documentatio(m) -> Documentatio(n)
> Fix typo in gettinginvolved.rst

- doc/en/user/source/data/raster/imagemosaic/configuration.rst
[![GEOT-7804](https://badgen.net/badge/JIRA/GEOT-7804/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7804) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
Updating ImageMosaic documentation.
> [GEOT-7804]: Follow up on ImageMosaic doc, for SkipExternalOverviews

- doc/en/api/1.0.0/authenticationfilterconfiguration.yaml
- doc/en/api/1.0.0/filterchain.yaml
- doc/en/user/source/rest/api/authenticationfilters.rst
- src/restconfig/src/main/java/org/geoserver/rest/security/AuthenticationFilterChainRestController.java
- src/restconfig/src/main/java/org/geoserver/rest/security/AuthenticationFilterController.java
- src/restconfig/src/main/java/org/geoserver/rest/security/xml/AuthFilter.java
- src/restconfig/src/main/java/org/geoserver/rest/security/xml/AuthFilterChain.java
- src/restconfig/src/main/java/org/geoserver/rest/security/xml/AuthFilterChainCollection.java
- src/restconfig/src/test/java/org/geoserver/rest/security/AuthenticationFilterChainRestControllerMarshallingTest.java
- src/restconfig/src/test/java/org/geoserver/rest/security/AuthenticationFilterChainRestControllerTest.java
- src/restconfig/src/test/java/org/geoserver/rest/security/AuthenticationFilterControllerTest.java
- src/restconfig/src/test/java/org/geoserver/rest/security/AuthenticationFilterRestControllerMarshallingTest.java
[![GEOS-11815](https://badgen.net/badge/JIRA/GEOS-11815/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11815) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
minor changes:  
* filterChain --> filterchain 
* authFilter --> authfilter
> [GEOS-11815] Create Auth Filter REST API Endpotins minor changes:  filterChain --> filterchain  authFilter --> authfilter

- src/community/gwc-azure-blob/src/assembly/assembly.xml
[![GEOS-11929](https://badgen.net/badge/JIRA/GEOS-11929/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11929) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
> [GEOS-11929]: Fixing gwc-azure-blobstore zip packaging

- src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/response/TemplateComplexTestSupport.java
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/GeoJSONQueryablesSchema.json
- src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/HTMLQueryablesSchema.xhtml
- src/community/features-templating/features-templating-ogcapi/src/main/java/org/geoserver/featurestemplating/ogcapi/OGCSchemaOverride.java
- src/community/features-templating/features-templating-ogcapi/src/main/java/org/geoserver/featurestemplating/ogcapi/SchemaCallBackOGC.java
- src/community/features-templating/features-templating-ogcapi/src/main/java/org/geoserver/featurestemplating/ogcapi/TemplateCallBackOGC.java
- src/community/features-templating/features-templating-ogcapi/src/main/resources/applicationContext.xml
- src/community/features-templating/features-templating-ogcapi/src/test/java/org/geoserver/featurestemplating/response/GeoJSONGetComplexFeaturesResponseAPITest.java
- src/community/features-templating/features-templating-ogcapi/src/test/java/org/geoserver/featurestemplating/response/HTMLComplexFeaturesResponseApiTest.java
[![GEOS-11895](https://badgen.net/badge/JIRA/GEOS-11895/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11895) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-11895
> [GEOS-11895] Features templates schemas overrides should be applied to OGC-API queryables output

- src/community/security/oidc/oidc-web/src/main/java/org/geoserver/web/security/oauth2/login/OAuth2LoginAuthProviderPanel.java
- src/community/security/oidc/oidc-web/src/main/java/org/geoserver/web/security/oauth2/login/ToggleDisplayCheckboxBehavior.java
I was testing the UX and found two issues:
1. The sub-config panels (i.e. google, github, or oidc-generic) were not longer hiding.
* this was due to the CSS inclusion (content-security-policy safe) moved to the wrong spot.
2. I noticed some issues with pressing the "discovery" button when you haven't put in a "name" (of the filter) value. 
* I fixed this partially
* It now does the same as the old UX
* This code is based on the old code, so I think its too much work to fix for a small gain
> oidc: fix two ux problems
