geoserver/geoserver

src/gwc/src/main/resources/geowebcache-wmsservice-context.xml
src/gwc/src/test/java/org/geoserver/gwc/wms/TestFullWMSBeans.java

Please look at the following JIRA: https://jira.codehaus.org/browse/GEOS-6627. Note that the following pull request requires that the https://github.com/GeoWebCache/geowebcache/pull/272 pull request has been already merged in GWC.

[GEOS-6627]GWC causes a wrong handling of the ImageIO and ImageIO-Ext plugins (Backport on 2.6.x branch)

---

src/web/core/src/main/java/org/geoserver/web/data/style/StyleDetachableModel.java
src/web/wms/src/main/java/org/geoserver/wms/web/data/AbstractStylePage.java
src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleEditPage.java
src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleNewPage.java

Since I cannot find a way to write a test for this one, I submitted a pull request in case someone wants to review. The trick to make it work was to move the format into a field, since we cannot keep the format in the html and get it back when the format dropdown gets disabled (disabled fields are not posted back, by HTML standard)

[GEOS-6745] Copy style needs to copy content and format

---

src/main/src/test/java/org/geoserver/data/test/MockCatalogBuilder.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/FeatureTypeTest.java

Some minor test fixes required for compatibility with the geotools property-ng migration:
Added namespace.getURI to MockCatalogBuilder
Removed instanceof test to support new implementation
Fixed spelling mistake

Test fixes for gt-property-ng migration

---

src/wcs2_0/src/main/java/org/geoserver/wcs2_0/util/NCNameResourceCodec.java
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/CoverageIdConverterTest.java
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/LayerCodecTest.java
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/DescribeCoverageTest.java
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/GetCoverageKvpTest.java

Backport on 2.6.x branch of the fix for JIRA: https://jira.codehaus.org/browse/GEOS-6805

[GEOS-6805] Support for WCS 2.0 request without defining workspace in coverageId(Backport 2.6.x)

---

src/extension/wcs2_0-eo/core/src/main/java/applicationContext.xml
src/extension/wcs2_0-eo/core/src/main/java/org/geoserver/wcs2_0/eo/response/GranuleCoverageExtension.java
src/extension/wcs2_0-eo/core/src/main/java/org/geoserver/wcs2_0/eo/response/GranuleCoverageInfo.java
src/extension/wcs2_0-eo/core/src/test/java/org/geoserver/wcs2_0/eo/DescribeCoverageTest.java
src/extension/wcs2_0-eo/core/src/test/java/org/geoserver/wcs2_0/eo/GranuleCoverageExtensionTest.java
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/DefaultWebCoverageService20.java
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCS20DescribeCoverageTransformer.java
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/util/WCS20DescribeCoverageExtension.java
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/DescribeCoverageTest.java

Please look at the following JIRA: https://jira.codehaus.org/browse/GEOS-6809. Note that the following pull request will move 2 classes (SingleGranuleGridCoverageReader.java and GranuleCoverageInfo.java) from the wcs2.0-eo module to the wcs2.0 one.

[GEOS-6809] WCS 2.0 DescribeCoverage should be able to handle single granules

---

src/extension/wcs2_0-eo/core/src/main/java/org/geoserver/wcs2_0/eo/response/DescribeEOCoverageSetTransformer.java
src/extension/wcs2_0-eo/core/src/test/java/org/geoserver/wcs2_0/eo/DescribeOECoverageSetTest.java

Backport on 2.6.x branch of the fix for JIRA: https://jira.codehaus.org/browse/GEOS-6808. Notice that this pull request requires to merge the related GT counterpart on 12.x branch: https://github.com/geotools/geotools/pull/684.

[GEOS-6808] WCS-EO DescribeEOCoverageSet should be more lenient (Backport on 2.6.x)

---

src/extension/wcs2_0-eo/core/src/main/java/applicationContext.xml
src/extension/wcs2_0-eo/core/src/main/java/org/geoserver/wcs2_0/eo/response/GranuleCoverageExtension.java
src/extension/wcs2_0-eo/core/src/main/java/org/geoserver/wcs2_0/eo/response/GranuleCoverageInfo.java
src/extension/wcs2_0-eo/core/src/test/java/org/geoserver/wcs2_0/eo/DescribeCoverageTest.java
src/extension/wcs2_0-eo/core/src/test/java/org/geoserver/wcs2_0/eo/GranuleCoverageExtensionTest.java
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/DefaultWebCoverageService20.java
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCS20DescribeCoverageTransformer.java
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/util/WCS20DescribeCoverageExtension.java
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/DescribeCoverageTest.java

Backport on 2.6.x branch of the fix for JIRA: https://jira.codehaus.org/browse/GEOS-6809

[GEOS-6809] WCS 2.0 DescribeCoverage should be able to handle single granules (Backport 2.6.x)

---

src/wcs1_1/src/main/java/org/geoserver/wcs/DefaultWebCoverageService111.java
src/wcs1_1/src/test/java/org/geoserver/wcs/GetCoverageTest.java
src/web/wcs/src/main/java/org/geoserver/wcs/web/publish/WCSLayerConfig.java

Apparently my earlier fix wasn't sufficient and didn't work all that well. That's why I changed the order of the check in the String which makes the check more stable. Also I've added an extra test for RangeSubset with interpolation in GetCoverage (where it belongs).
Finally I've renamed Nearest Neighbour in the web interface to Nearest Neighbor which seems to fix the web interface from not displaying this interpolation method when loading a new layer. Now it works properly. I've also addressed my potential concerns about this on the developers mailing list.
(Resubmitted from #847)

[GEOS-6688-3] Fix for nearest neighbor interpolation (with tests).

---

doc/en/user/source/services/wms/time.rst
src/ows/src/main/java/org/geoserver/ows/kvp/TimeKvpParser.java
src/ows/src/test/java/org/geoserver/ows/kvp/TimeKvpParserTest.java

Patch to provide support within WMS/WCS services for TIME parameter handling of relative time keywords 'back' and 'present'.  See JIRA for more details. 
https://jira.codehaus.org/browse/GEOS-6778
Proposal:
https://github.com/geoserver/geoserver/wiki/GSIP-124---WMS-WCS-Relative-Time-Support

[GEOS-6778] Added support for relative time keywords in WMS/WCS TIME parameter

---

src/extension/wps/wps-core/src/test/java/org/geoserver/wps/InputLimitsTest.java
src/wms/src/test/java/org/geoserver/wms/dimension/RasterTimeDimensionDefaultValueTest.java

Also has a mostly-unrelated fix to the WMS time dimension test, which fails at the end of some months.

Fix JDK8 build - WPS part

---

src/community/jms-cluster/activemqBroker/src/main/webapp/META-INF/MANIFEST.MF
src/community/jms-cluster/activemqBroker/src/main/webapp/WEB-INF/classes/META-INF/DEPENDENCIES
src/community/jms-cluster/activemqBroker/src/main/webapp/WEB-INF/classes/META-INF/MANIFEST.MF
src/extension/app-schema/pom.xml
src/pom.xml

For https://jira.codehaus.org/browse/GEOS-6868
Tested full build; no failures.
See also: https://github.com/geotools/geotools/pull/728

(GEOS 6868) Upgrade to commons-lang 2.6

---

src/main/src/main/java/org/geoserver/security/auth/GuavaAuthenticationCacheImpl.java
src/platform/src/main/java/org/geoserver/platform/resource/FileSystemWatcher.java

Fix for [GEOS-6850](https://jira.codehaus.org/browse/GEOS-6850).  Made FileSystemWatcher and GuavaAuthenticationCacheImpl DisposableBeans so they can shut down their ExecutorServices.  Also made the threads Daemons to reduce the impact of failing to shut them down and gave them identifiable names to make debugging easier.  Added a Disposer object to dispose of the objects in situations where they have been created after Spring context startup as discussed on the mailing list.

GEOS-6850 - Multiple Thread Pools left running at shutdown

---

build/functions

Release script was treating the `.`s in version numbers as wild cards when searching through JIRA releases.
For instance, 2.5.5 matched the string 20515, which was the JIRA release ID for the 2.5.3 release.

Match release tag as a string rather than regular expression

---

src/security/ldap/src/main/java/org/geoserver/security/ldap/BindingLdapAuthoritiesPopulator.java
src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPSecurityProvider.java
src/security/ldap/src/test/java/org/geoserver/security/ldap/LDAPAuthenticationProviderTest.java
src/security/ldap/src/test/resources/data3.ldif

LDAP Authorities Populator was failing to authenticate (and load roles) when there is a user with a colon in their password, because it attaches password to username with colon and then splits again.

Ldap Security: authorities populator fails when colon in password

---

src/web/core/src/main/java/org/geoserver/web/GeoServerHomePage.java
src/web/core/src/test/java/org/geoserver/web/GeoServerHomePageTest.java

As reported in https://jira.codehaus.org/browse/GEOS-6841, this delivers a quick fix for the issue by checking if the mail address is equals to null. If it is this will be replaced by geoserver@example.org on the homepage.
I specifically choose example org because it is an IANA reserved domain for test purposes and can be used without prior consent.

[GEOS-6841] Fix for invalid email address on the front page

---

src/extension/wps/wps-core/pom.xml
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/InternalWCSInputProvider.java
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/WFSPPIO.java
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/xml/WPSConfiguration.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteOnCoverageTest.java
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/WCS2GetCoverageRequestBuilder.java

Added support for embedding WCS 2.0 in WPS, also a basic unit tests which checks that an 1.1 and 2.0.1 xml request can be embedded in a WPS request.

GEOS-6905 support WCS 2.0 requests embedded in WPS

---

src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleNewPageTest.java

The testMissingName() test in StyleNewPageTest was not actually being executed before. Further, it's call to form.setValue() was incorrect and caused a failure. The test has been updated to run and passes correctly.

Fixing unused/broken test

---

doc/en/developer/source/programming-guide/versioning/wfsv/requirements.rst
doc/en/developer/source/release-guide/old.rst
doc/en/user/source/extensions/jp2k.rst
doc/en/user/source/services/wms/get_legend_graphic/legendgraphic.rst

This address part of, not all of, GEOS-6608. More work is required, ideally before codehaus disappears.
Also fix a few typos noted along the way.

GEOS-6608: Start removing links to confluence from docs.

---

src/wfs/src/main/java/org/geoserver/wfs/xml/WFSURIHandler.java
src/wfs/src/main/java/org/geoserver/wfs/xml/WFSXmlUtils.java
src/wfs/src/main/java/org/geoserver/wfs/xml/v1_0_0/WfsXmlReader.java
src/wfs/src/test/java/org/geoserver/wfs/xml/PropertyRule.java
src/wfs/src/test/java/org/geoserver/wfs/xml/WFSURIHandlerTest.java

Adds mechanism to specify hostnames that are aliases for the local host as well as logging to aid in diagnosing issues.
Provided unit tests for aliases and proxy baseurl but was unable to mock the NetworkInterface discovery as NetworkInterface is final and has no public constructor.

GEOS-6059 Allow user specification of aliases for localhost

---

src/wfs/src/main/java/org/geoserver/wfs/xml/WFSURIHandler.java
src/wfs/src/main/java/org/geoserver/wfs/xml/WFSXmlUtils.java
src/wfs/src/main/java/org/geoserver/wfs/xml/v1_0_0/WfsXmlReader.java
src/wfs/src/test/java/org/geoserver/wfs/xml/PropertyRule.java
src/wfs/src/test/java/org/geoserver/wfs/xml/WFSURIHandlerTest.java

Backport of #962 to 2.7.x
Bug mitigation for GEOS-6059, allows manual resolution of errors due to failure to detect that a DescribeFeatureType is reflexive via system property.

GEOS-6059 Allow user specification of aliases for localhost, Backport to 2.7.x

---

src/web/demo/src/main/java/org/geoserver/web/demo/PreviewLayer.java
src/web/demo/src/test/java/org/geoserver/web/demo/PreviewLayerProviderTest.java

Small fix to better support workspaced LayerGroups, plus test case.

Fixed PreviewLayer to used prefixed name for layer groups

---

src/extension/wps/wps-core/src/main/java/applicationContext.xml
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/resource/CoverageResourceListener.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/CropCoverageTest.java
src/wcs/src/main/java/org/geoserver/wcs/CoverageCleanerCallback.java

Allows CoverageResourceListener to clean up after any coverages that failed to load (due to invalid crop).
See https://jira.codehaus.org/browse/GEOS-6921

Use CoverageResourceListener to call CoverageCleanerCallback

---

src/extension/wps/wps-core/src/main/java/applicationContext.xml
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/resource/CoverageResourceListener.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/CropCoverageTest.java
src/wcs/src/main/java/org/geoserver/wcs/CoverageCleanerCallback.java

Backport of #975 to 2.7
Cherry picked without changes, local test build succeeded.

GEOS-6921 - Use CoverageResourceListener to call CoverageCleanerCallback, Backport to 2.7

---

doc/en/user/source/datadirectory/migrating.rst
src/main/src/main/java/org/geoserver/catalog/CatalogFacade.java
src/platform/src/main/java/org/geoserver/platform/resource/Paths.java
src/platform/src/test/java/org/geoserver/platform/resource/PathsTest.java

This is in response to a naming regression described in the following JIRA ticket: http://jira.codehaus.org/browse/GEOS-6811
The solution introduces a new Java System Property, STRICT_PATH, which if set to false, will relax the restrictions on names. The characters which are allowed with this flag set to false are:
* star (*)
* colon (:)
* comma (,)
* single quote (')
* ampersand (&)
* question mark (?)
* double quote (")
* less than (<)
* greater than (>)
* bar (|)
This will allow migration from geoserver 2.5.x to future versions for any catalogs which contained these characters.

Relaxing Naming Restrictions with STRICT_PATH=false flag [GEOS-6811]

---

doc/en/user/source/datadirectory/migrating.rst
src/main/src/main/java/org/geoserver/catalog/CatalogFacade.java
src/platform/src/main/java/org/geoserver/platform/resource/Paths.java
src/platform/src/test/java/org/geoserver/platform/resource/PathsTest.java

Backport of #960 to 2.6.  Corrects regression in 2.6.0 by making the new stricter validation optional and off by default.

[GEOS-6811] Relaxing Naming Restrictions with STRICT_PATH=false flag, Backport to 2.6

---

doc/en/user/source/datadirectory/migrating.rst
src/main/src/main/java/org/geoserver/catalog/CatalogFacade.java
src/platform/src/main/java/org/geoserver/platform/resource/Paths.java
src/platform/src/test/java/org/geoserver/platform/resource/PathsTest.java

Backport of #960 to 2.7.  Corrects regression in 2.6.0 by making the new stricter validation optional and off by default.

[GEOS-6811] Relaxing Naming Restrictions with STRICT_PATH=false flag, Backport to 2.7

---

src/platform/src/main/java/org/geoserver/platform/resource/Paths.java
src/platform/src/test/java/org/geoserver/platform/resource/PathsTest.java

@jodygarnett @travislbrundage this pull request refactors strict path handling to permit testing both with and without strict path, and increases test coverage. (Current tests depend on STRICT_PATH which will always be false, so strict path behaviour is never tested.) Full build passes on master. Not yet tested on 2.7.x or 2.6.x but backport would improve maintainability.

Improved strict path testability and coverage

---

src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendUtils.java
src/wms/src/test/java/org/geoserver/wms/legendgraphic/AbstractLegendGraphicOutputFormatTest.java
src/wms/src/test/resources/org/geoserver/wms/legendgraphic/ColorMapWithCql.sld

This pull request adds GetLegendGraphic support for ColorMapEntry attributes using cql expressions (see http://jira.codehaus.org/browse/GEOT-5052 for WMS GetMap support)

GEOS-6946: added support for cql in ColorMapEntry for GetLegendGraphic requests

---

doc/en/developer/source/policies/community-modules.rst

Updating the docs for contributing a community module. Some links were outdated and it needed to be updated to use git instead of subversion.

Updating community module process

---

src/extension/wps/wps-core/src/main/java/org/geoserver/wps/gs/ImportProcess.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/ImportProcessTest.java

If the store does not exist but a store name is provided, create it.
The functionality is virtually identical to not providing a store name,
except the provided store name is used instead of a default

GEOS-6970 Support store creation in Import

---

src/extension/importer/core/src/main/java/org/geoserver/importer/DataFormat.java
src/extension/importer/core/src/main/java/org/geoserver/importer/DataStoreFormat.java
src/extension/importer/core/src/main/java/org/geoserver/importer/GridFormat.java
src/extension/importer/core/src/test/java/org/geoserver/importer/ImporterDataTest.java

See https://jira.codehaus.org/browse/GEOS-6958
While this is technicaly a bugfix, it affects the Catalog, so it might be an idea to keep this fix just on master for a bit before any backporting is considered.
In addition to the automated tests, I have tested this manually, and have not seen any detrimental effects to the catalog.

[GEOS-6958] Use relative paths when importing from data directory

---

src/main/src/main/resources/schemas/sld/StyledLayerDescriptor.xsd
src/main/src/test/java/org/vfny/geoserver/util/valid.sld

Fix for [GEOS-6971](https://osgeo-org.atlassian.net/browse/GEOS-6971) by updating schema file.  Also updated test data to cover this case.

[GEOS-6971] Color-blending example doesn't validate in SLD

---

src/extension/importer/core/src/main/resources/META-INF/services/org.geotools.data.DataStoreFactorySpi
src/extension/importer/core/src/main/resources/META-INF/services/org.geotools.data.FileDataStoreFactorySpi

The CSVDataStoreFactory has been moved to geotools and is no longer available under this name.
https://osgeo-org.atlassian.net/browse/GEOS-6978

Remove META-INF/services reference to CSVDataStoreFactory [GEOS-6978]

---

src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/gwc/src/test/java/org/geoserver/gwc/GWCTest.java

Backport on 2.6.x of the fix for JIRA: https://osgeo-org.atlassian.net/browse/GEOS-6979

[GEOS-6979] GWC caching with CQL_FILTER returns no parameter filter exists for FILTER (Backport 2.6.x)

---

src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/gwc/src/test/java/org/geoserver/gwc/GWCTest.java

Backport on 2.7.x of the fix for JIRA: https://osgeo-org.atlassian.net/browse/GEOS-6979

[GEOS-6979] GWC caching with CQL_FILTER returns no parameter filter exists for FILTER (Backport 2.7.x)

---

doc/en/developer/source/maven-guide/index.rst
doc/en/developer/source/programming-guide/app-schema/index.rst
src/community/jdbcconfig/pom.xml
src/extension/app-schema/app-schema-oracle-test/pom.xml
src/extension/app-schema/app-schema-test/pom.xml
src/extension/importer/core/pom.xml
src/extension/oracle/pom.xml
src/pom.xml
src/web/app/pom.xml

This change is primarily intended for use with app-schema online tests, but I upgraded everything that used the old ojdbc.jar for consistency.

Update to Oracle 12 driver (ojdbc7)

---

src/community/hz-cluster/src/main/java/org/geoserver/cluster/hazelcast/HzExtensionFilter.java
src/community/hz-cluster/src/main/resources/applicationContext.xml
src/community/hz-cluster/src/test/java/org/geoserver/cluster/hazelcast/HzExtensionFilterTest.java
src/main/pom.xml
src/main/src/main/java/org/geoserver/util/DefaultCacheProvider.java
src/main/src/test/java/org/geoserver/platform/GeoServerExtensionsHelper.java
src/main/src/test/java/org/geoserver/platform/GeoServerExtensionsHelperTest.java
src/main/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java
src/main/src/test/java/org/geoserver/util/DefaultCacheProviderTest.java
src/platform/pom.xml
src/platform/src/main/java/org/geoserver/platform/GeoServerExtensions.java
src/platform/src/test/java/org/geoserver/util/LoggerRule.java
src/platform/src/test/java/org/geoserver/util/LoggerRuleTest.java
src/pom.xml

Resolve conflicts between CacheProviders by picking one and then logging a warning.  The user can specify priority with a system property.
This was tricky to test so i made some changes to unit testing support.
I also added automatic conflict resolution for hz-cluster without the need for user action.
See: https://osgeo-org.atlassian.net/browse/GEOS-6994

GEOS-6994, Cache provider conflict resolution

---

src/main/src/main/resources/org/geoserver/catalog/impl/CatalogPropertyAccessor_FullTextProperties.properties
src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java

[GEOS-7003] Fixed the layer preview search not searching layer titles and keywords and layer group titles and abstracts in 2.7.0.

[GEOS-7003] Fixed the layer preview search not searching layer titles and keywords and layer group titles and abstracts in 2.7.0.

---

src/extension/inspire/src/main/java/org/geoserver/inspire/wms/WMSExtendedCapabilitiesProvider.java
src/gwc/src/main/java/org/geoserver/gwc/wms/CachingExtendedCapabilitiesProvider.java
src/wms/src/main/java/org/geoserver/wms/ExtendedCapabilitiesProvider.java
src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
src/wms/src/main/java/org/geoserver/wms/capabilities/CapabilityUtil.java
src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformerTest.java

This one follows up discussion on the mailing list. It is meant to be merged on the master branch once 2.7.x has been cut off

[GEOS-6865] Allow wms extension capabilities providers to customize the root crs list and the layer scale ranges

---

src/restconfig/src/main/java/org/geoserver/catalog/rest/CoverageResource.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/CoverageTest.java

Using the native name rather than the catalog name so that coverage readers will recognize the name.

GEOS-6874 REST API bug - The specified coverageName is not supported

---

src/main/src/main/java/org/geoserver/config/GeoServerDataDirectory.java
src/main/src/test/java/org/geoserver/config/GeoServerDataDirectoryTest-applicationContext.xml
src/main/src/test/java/org/geoserver/config/GeoServerDataDirectoryTest.java
src/main/src/test/java/org/geoserver/config/external.sld

Resource.file() will create the file if it doesn't exist. Changed to use a method that does not create the file, only generates the correct path.

[GEOS-7025] Stopped GeoServerDataDirectory.parsedStyle from creating files for nonexistant URLs

---

doc/en/user/source/rest/api/styles.rst
src/restconfig/src/main/java/org/geoserver/catalog/rest/StyleResource.java

No test case for this one since the parameter only really has any effect when using extended style formats such as CSS (eg convert a CSS style to SLD, or vise-versa). This change was tested upstream with a style extension and did work correctly.

[GEOS-7038] Added support for prettyPrint to REST GET Style

---

doc/en/user/source/services/wms/index.rst
doc/en/user/source/services/wms/nonstandardautonamespace.rst

I have added a couple of notes that refer to the version of GeoTools.  This might be confusing in GeoServer documentation but I felt they were needed.

Add documentation for non standard auto CRS namespace in WMS

---

src/web/security/core/src/test/java/org/geoserver/security/web/data/DataSecurityPageTest.java
src/web/security/core/src/test/java/org/geoserver/security/web/data/EditDataAccessRulePageTest.java
src/web/security/core/src/test/java/org/geoserver/security/web/data/NewDataAccessRulePageTest.java

@mcrmcr @aaime please see discussion:
https://osgeo-org.atlassian.net/browse/GEOS-7037
A race condition in PropertyFileWatcher caused by file second timestamp precision in Linux on Java 7 revealed two defects in tests: (1) an invalid layer admin rule used in a test, and (2) failure to add two basic rules to a test. This pull requests adds some forced reloads to ensure consistent behaviour between Linux  Java 7 and other platforms and fixes the two incorrect tests which only passed elsewhere because caching allowed them to circumvent property file loading and validation.

[GEOS-7037] Intermittent build failures in gs-web-sec-core under load

---

src/wms/src/main/resources/org/geoserver/wms/map/OpenLayers3MapTemplate.ftl

Added meta tag with charset UTF-8 to ol3 template to correctly instruct browsers how to interpret the layer preview document.

GEOS-4858 Added meta tag with charset UTF-8 to ol3 template

---

src/wms/src/main/resources/org/geoserver/wms/map/OpenLayers3MapTemplate.ftl

Added meta tag with charset UTF-8 to ol3 template to correctly instruct browsers how to interpret the layer preview document.

GEOS-4858 Added meta tag with charset UTF-8 to ol3 template [2.7.x]

---

doc/en/user/source/production/config.rst

I recently tried to remove web-*.jar files from a GeoServer 2.7.1 installation and I figured out the docs are outdated.

Update configuration doc to incluse gs- prefix for web jars

---

doc/en/user/source/webadmin/basics.rst
doc/en/user/source/webadmin/data/index.rst
doc/en/user/source/webadmin/data/layergroups.rst
doc/en/user/source/webadmin/data/layers.rst
doc/en/user/source/webadmin/data/stores.rst
doc/en/user/source/webadmin/data/styles.rst
doc/en/user/source/webadmin/data/workspaces.rst
doc/en/user/source/webadmin/layerpreview/index.rst

This patch makes the structure of the WebAdmin Data data type pages all follow the same pattern.  It also makes section wording consistent, and clearer in some cases.  A few section headings have been added, to make structure clearer and allowing easier linking.

Regularize WebAdmin Data documentation

---

src/extension/inspire/src/main/java/org/geoserver/inspire/web/UniqueResourceIdentifiersProvider.java
src/extension/inspire/src/test/java/org/geoserver/inspire/web/InspirePanelTest.java
src/extension/inspire/src/test/java/org/geoserver/inspire/web/UniqueResourceIdentifiersEditorTest.java

This capability was commented out in code as no known examples but
there are possible uses and the element exists in INSPIRE schema.

[GEOS-7043] - Enable to set the SpatialDataSetIdentifier/@metadataURL

---

src/web/wfs/src/main/resources/GeoServerApplication.properties

This caused transifex to think, that another property has began with key "override"

Added missing escape symbol

---

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java

Fixing a case I'd forgotten to test for in #1107
This will not fix the problem for any keywords that were already set, it just ensures that any further keyword edits will be correctly searchable.

[GEOS-7064] Ensure that resource keywords are searchable from layers after edit

---

src/restconfig/pom.xml
src/restconfig/src/main/java/org/geoserver/catalog/rest/DataStoreFileResource.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/DataStoreFileResourceTest.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/DataStoreFileUploadTest.java

Refactored `DataStoreFileResource` to let `AppSchemaDataAccess` fit in. Basically, it was necessary to substitute `DataStore/DataStoreFactorySpi` interfaces with `DataAccess/DataAccessFactory`. The functionality of the service should be unaffected by the change.

[GEOS-7087] App-schema mapping file upload via REST

---

src/restconfig/src/main/java/org/geoserver/catalog/rest/DataStoreFileResource.java

Allows direct geopackage file upload through restconfig. Depends on https://github.com/geotools/geotools/pull/896 (not to build, but to work).

Restconfig: add GeoPackage format for store file upload

---

src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteTest.java
src/main/src/main/java/org/geoserver/util/NoExternalEntityResolver.java
src/wcs1_0/src/test/java/org/geoserver/wcs/GetCoverageTest.java
src/wcs1_1/src/test/java/org/geoserver/wcs/GetCoverageTest.java
src/wcs2_0/src/test/resources/testDescribeCoverageEntityExpansion.xml
src/wfs/src/main/java/org/geoserver/wfs/xml/v1_1_0/WFS.java
src/wfs/src/test/java/org/geoserver/wfs/ExternalEntitiesTest.java

In order to get the test cases to pass, WFS 1.1 uses the wfs.xsd from geotools (This is because maven/eclipse will use `file:` paths for resources in the current module, instead of the `jar:` paths used when the module is packaged).
Depends on https://github.com/geoserver/geoserver/pull/1129 to pass tests.

[GEOS-7095] Fix for exploitable bypass for XXE fix

---

src/extension/importer/core/src/main/java/org/geoserver/importer/DataStoreFormat.java

Add support for non-JDBC databases to GeoServer Importer.
No test case, because the only example of such a database I know of is the gt-mongodb extension, an unsupported geotools module. The fact that it passes the pre-existing test cases should be sufficient.
Manual tests appeared to work fine.

[GEOS-7102] Importer support for non-JDBC databases

---

src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteTest.java
src/main/src/main/java/org/geoserver/util/NoExternalEntityResolver.java
src/wcs1_0/src/test/java/org/geoserver/wcs/GetCoverageTest.java
src/wcs1_1/src/test/java/org/geoserver/wcs/GetCoverageTest.java
src/wfs/src/test/java/org/geoserver/wfs/ExternalEntitiesTest.java

Using a whitelist of `systemId.matches("^(?i)(jar:file|http).*\\.xsd$")` to test for valid schema URLs
Updated test cases with `FILE://` and `.XSD` in place of `file://` and `.xsd` to confirm case insensitivity.
Old blacklist approach, with case instensitive fix, here: https://github.com/geoserver/geoserver/compare/master...tbarsballe:xxe-blacklist

Case insensitive XXE fix (whitelist)

---

src/main/src/main/java/org/geoserver/catalog/Catalog.java
src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java

This fixes most of GEOS-7098; as long as there is a default store that matches the argument class, it will get returned. Default workspaces for getStoreByName have also been fixed.
Becuase CoverageStore and WMSStore do not support default store behavior, the behavior when trying to get the default stores of these classes is undefined.

[GEOS-7098] Improve getStoreByName null handling

---

src/community/solr/src/main/java/applicationContext.xml
src/community/solr/src/main/java/org/geoserver/solr/SolrConfigurationPage.java
src/community/solr/src/main/java/org/geoserver/solr/SolrConfigurationPanel.java
src/community/solr/src/main/java/org/geoserver/solr/SolrFeatureTypeCallback.java
src/community/solr/src/test/java/org/geoserver/solr/SolrStorePageTest.java
src/gwc/src/main/java/org/geoserver/gwc/layer/CatalogLayerEventListener.java
src/gwc/src/test/java/org/geoserver/gwc/layer/CatalogLayerEventListenerTest.java
src/main/src/main/java/org/geoserver/catalog/FeatureTypeInfo.java
src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
src/main/src/main/java/org/geoserver/catalog/impl/FeatureTypeInfoImpl.java
src/main/src/main/java/org/geoserver/security/decorators/DecoratingFeatureTypeInfo.java
src/web/core/src/main/java/org/geoserver/web/data/resource/FeatureResourceConfigurationPanel.html
src/web/core/src/main/java/org/geoserver/web/data/resource/FeatureResourceConfigurationPanel.java
src/web/core/src/main/java/org/geoserver/web/data/resource/ResourceConfigurationException.java
src/web/core/src/main/java/org/geoserver/web/data/resource/ResourceConfigurationPage.java
src/web/core/src/main/java/org/geoserver/web/data/resource/ResourceConfigurationPanel.java
src/web/core/src/main/java/org/geoserver/web/data/store/DefaultDataStoreEditPanel.java
src/web/core/src/main/java/org/geoserver/web/data/store/ParamInfo.java
src/web/core/src/main/resources/GeoServerApplication.properties
src/web/core/src/main/resources/GeoServerException.properties
src/wfs/src/test/java/org/geoserver/wfs/GetFeatureTest.java
src/wms/src/main/java/org/geoserver/wms/GetMap.java
src/wms/src/test/java/org/geoserver/wms/featureinfo/GetFeatureInfoJSONTest.java

This one packs the work needed to deprecate the field strategy in the SOLR store in 3 separate commits, in particular, handling deprecacted store config fields, exposing the CQL filter, and updating the SORL configurations so that it can effectively replublish the same "root" layer over and over with different configurations (sql view like).
CQL filtering wise, we followed the advices on the list, and avoided parsing and generating the CQL from a Filter object representation, but storing the CQL instead and parsing it as needed.

Store field deprecation, CQL filter in layers, and SOLR improvements

---

src/wcs1_0/src/main/java/org/geoserver/wcs/response/Wcs10CapsTransformer.java
src/wcs1_0/src/main/java/org/geoserver/wcs/response/Wcs10DescribeCoverageTransformer.java
src/wcs1_0/src/test/java/org/geoserver/wcs/DescribeCoverageTest.java
src/wcs1_0/src/test/java/org/geoserver/wcs/GetCapabilitiesTest.java
src/wcs1_1/src/main/java/org/geoserver/wcs/response/DescribeCoverageTransformer.java
src/wcs1_1/src/main/java/org/geoserver/wcs/response/WCSCapsTransformer.java
src/wcs1_1/src/test/java/org/geoserver/wcs/DescribeCoverageTest.java
src/wcs1_1/src/test/java/org/geoserver/wcs/GetCapabilitiesTest.java
src/wfs/src/main/java/org/geoserver/wfs/CapabilitiesTransformer.java
src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetCapabilitiesTest.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetCapabilitiesTest.java

[GEOS-7085] Add the proxy base URL to metadata links, if necessary, in WCS DescribeCoverage and WCS/WFS GetCapabilities responses.

[GEOS-7085] Add the proxy base URL to metadata links

---

src/wms/src/main/java/org/geoserver/wms/capabilities/LegendSampleImpl.java
src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesLegendURLTest.java

Attempting to backport this bug fix to 2.7.x.
[GEOS-7013] Fixed dynamic legend size calculation for raster styles.

[GEOS-7013] 2.7.x Fixed dynamic legend size calculation for raster styles.

---

src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java
src/wms/src/test/java/org/geoserver/wms/map/GetMapKvpRequestReaderTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapIntegrationTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetMapIntegrationTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/WMSCascadeTest.java

As discussed at PSC meeting.  Backports cleanly to 2.7 and 2.6.

Hide WMS errors related to SLD lookup that can leak local network info

---

src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
src/ows/src/test/java/org/geoserver/ows/DispatcherTest.java
src/ows/src/test/java/org/geoserver/ows/TestDispatcherCallback.java

Fix for [GEOS-7128](https://osgeo-org.atlassian.net/browse/GEOS-7128), to ensure all callbacks are handled if an exception is thrown in fireFinishedCallback. The other callbacks (init, serviceDispatched, ...) will not catch exceptions, but in this case the exceptions are caught at a higher level, and returned as an <ows:Exception> response. However, for the finished() callback, the (valid) reponse has already been written, so we cannot return an Exception response, hence this fix.
Note that this means that if an exception is thrown from any fire___Callback other than fireFinishedCallback(), subsequent callbacks of that type will not be fired, and the request will terminate with an OWS Exception response. 
I have an alternate fix that catches and logs all exceptions fired by callbacks …

[GEOS-7128] Catch/Log DispatcherCallback Exceptions on fireFinishedCallback

---

src/pom.xml

Codehaus has shutdown, this repository no longer exists.

Removing dead maven repo.

---

src/wcs1_1/src/main/java/org/geoserver/wcs/response/CoveragesTransformer.java
src/wcs1_1/src/main/java/org/geoserver/wcs/response/WCSCapsTransformer.java
src/wcs1_1/src/test/java/org/geoserver/wcs/DescribeCoverageTest.java
src/wcs1_1/src/test/java/org/geoserver/wcs/GetCapabilitiesTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-7140
WCS 1.1 now advertises workspace prefixes
* Updated GetCapabilitiesTest to account for this
* Added test case to check that identifiers returned by DescribeCoverage match those returned by GetCapapabilites, and that two coverages with the same name in different workspaces do not cause conflicts.

[GEOS-7140] WCS 1.1 now advertises workspace prefixes

---

src/main/src/main/java/org/geoserver/catalog/NamespaceWorkspaceConsistencyListener.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/NamespaceTest.java

Makes sure when namespace is deleted via REST API, also associated workspace is deleted.

[GEOS-7086] Backport to 2.7.x branch

---

src/main/src/main/java/org/geoserver/catalog/NamespaceWorkspaceConsistencyListener.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/NamespaceTest.java

Makes sure when namespace is deleted via REST API, also associated workspace is deleted.

[GEOS-7086] Backport to 2.6.x branch

---

src/main/src/main/java/org/geoserver/security/SecureCatalogImpl.java
src/main/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java

Updated SecureCatalogImpl to use the factory method instead of the constructor to create the CloseableIteratorAdapter to ensure that the wrapped CloseableIterator is closed properly.

[GEOS-7151] Fix code not closing CloseableIterator warnings

---

src/extension/importer/core/src/main/java/org/geoserver/importer/DataStoreFormat.java

For certain formats (eg. MongoDB), data.getName() returns null in importer. In these cases, we should populate the store name using the DataStoreFactory name. 
See https://osgeo-org.atlassian.net/browse/GEOS-7155
Since this only occurs with certain extensions, an automated test case is not really viable. This has been tested against the mongodb extension and works fine.

[GEOS-7155] Handle null store names in importer

---

src/main/src/main/resources/schemas/gml/2.1.2/geometry.xsd

Now both feature.xsd and geometry.xsd imports the same xlinks.xsd and the XSD validates correctly.

[GEOS-7167] GML2 xlinks import diverge fixed

---

src/web/core/src/main/java/org/geoserver/web/css/geoserver.css
src/web/wms/src/main/java/org/geoserver/wms/web/publish/WMSLayerConfig.html

Applied a class to the list rather than to the label allowing for manipulation of the CSS higher up the tree.
Retains the pseudo-hanging indent so long labels won't wrap underneath the checkbox while also making the label an inline element so it doesn't result in clicking on the whitespace toggling the input.

Accepts check box clicks outside the boxes [GEOS-6948]

---

src/extension/monitor/core/src/main/resources/org/geoserver/monitor/filter.properties

From Javier Avalos on mailing list:
> I answered myself : 
> adding the following line:
> /pdf/ **
> to the filter.properties configuration file of the monitoring module and restart geoserver the error disappears .
> Cheers!

resolve conflict between printing and monitor extension

---

doc/en/user/source/rest/examples/ruby.rst

Active development of the rgeoserver gem referenced in the documentation has moved to a new repository and is now maintained by @drh-stanford. Rubygems points to this repo as well. The examples provided on the old gem repo are broken.

update link to rgeoserver gem

---

src/main/src/main/java/org/geoserver/security/SecureCatalogImpl.java
src/main/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java

Use the factory method instead of the constructor to create the CloseableIteratorAdapter to ensure that the wrapped CloseableIterator is closed properly.

[GEOS-7151] 2.7.x Backport patch to fix CloseableIterator warnings

---

src/wcs1_0/src/main/java/org/geoserver/wcs/response/Wcs10CapsTransformer.java
src/wcs1_0/src/main/java/org/geoserver/wcs/response/Wcs10DescribeCoverageTransformer.java
src/wcs1_0/src/test/java/org/geoserver/wcs/DescribeCoverageTest.java
src/wcs1_0/src/test/java/org/geoserver/wcs/GetCapabilitiesTest.java
src/wcs1_1/src/main/java/org/geoserver/wcs/response/DescribeCoverageTransformer.java
src/wcs1_1/src/main/java/org/geoserver/wcs/response/WCSCapsTransformer.java
src/wcs1_1/src/test/java/org/geoserver/wcs/DescribeCoverageTest.java
src/wcs1_1/src/test/java/org/geoserver/wcs/GetCapabilitiesTest.java
src/wfs/src/main/java/org/geoserver/wfs/CapabilitiesTransformer.java
src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetCapabilitiesTest.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetCapabilitiesTest.java

[GEOS-7085] Add the proxy base URL to metadata links, if necessary, in WCS DescribeCoverage and WCS/WFS GetCapabilities responses.

[GEOS-7085] 2.7.x Backport patch to add the proxy base URL to WCS/WFS metadata links

---

doc/en/user/source/community/spatialite/index.rst

The link pointing to the native spatialite-Librarys in the geotools Wiki was misspelled, fixed it.

fix broken link to spatialite native libs

---

src/community/script/groovy/pom.xml

Removes a broken dependency on Codehaus. The groovy-eclipse-compiler
plugin is now in the main Nexus repo.

[GEOS-7190] Fix script community module build

---

src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/GeoServerTileLayerEditor.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/LayerCacheOptionsTabPanelTest.java

Fix is simple, if the create flag is not set, then the enabled one may be null and should be ignored.
Updating the test that should have caught this was harder.  Wicket is doing something funny and I don't entirely understand what.  This tweak involves calling an internal Wicket method that's not part of the official API to trigger validation where the error occurs.  The test now fails when the fix isn't in place, but it's somewhat questionable in its own right.

GEOS-7203, Disabling Caching for a layer causes NPE

---

src/extension/inspire/src/main/java/org/geoserver/inspire/wfs/WFSExtendedCapabilitiesProvider.java
src/extension/inspire/src/main/java/org/geoserver/inspire/wms/WMSExtendedCapabilitiesProvider.java
src/extension/inspire/src/test/java/org/geoserver/inspire/wfs/WFSExtendedCapabilitiesTest.java
src/extension/inspire/src/test/java/org/geoserver/inspire/wms/WMSExtendedCapabilitiesTest.java

This is just the same as https://github.com/geoserver/geoserver/pull/1217 but branched from master rather than 2.8.x in case that is the preferred way round to do things. Would like it cherry-picked back to 2.8.x branch though as it fixes bug.

GEOS-7189: Fix deserialization of boolean metadata parameter.

---

src/extension/app-schema/app-schema-test/pom.xml
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/web/AbstractMapPreviewPageTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/web/Gml311LinksTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/web/Gml32LinksTest.java
src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.java
src/web/demo/src/main/java/org/geoserver/web/demo/PreviewLayer.java

A couple of test classes extending `GeoServerWicketTestSupport` have been added to `gs-app-schema-test` module.

[GEOS-7226] GML links in Layer Preview don't work for app-schema layers

---

src/web/core/src/main/java/org/geoserver/web/data/resource/FeatureResourceConfigurationPanel.java
src/web/core/src/test/java/org/geoserver/web/data/resource/FeatureResourceConfigurationPanelTest.java
src/wms/src/main/java/org/geoserver/wms/featureinfo/VectorRenderingLayerIdentifier.java

ResourceConfigurationPage#updateResource can be called with target==null.
So we need to check for it.
A NPE was always raised when the user edits an existing SQL view and was hitting
the save button. So he was never able to go back to the layer edition, making
impossible to change a SQL view.
Fixed a small typo in a log while I was at it.

Fix a NPE when changing a SQL view for a layer.

---

src/main/src/test/java/org/geoserver/data/test/tiger_roads.sld
src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/CapabilitiesTest.java

The WMS 1.1.1 DTD requires Style to match
"(Name,Title,Abstract?,LegendURL*,StyleSheetURL?,StyleURL?)". Adds
small test data file from the release data set.
Includes a small amount of refactoring to reduce code duplication.
More at https://osgeo-org.atlassian.net/browse/GEOS-7217

[GEOS-7217] Ensure we provide a Title element for the Style in Capabilities document

---

doc/en/user/source/services/wms/reference.rst

This commit clarifies the GetFeatureInfo behaviour on layergroups

[GEOS-7220] Update WMS documentation

---

src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java
src/main/src/test/java/org/geoserver/catalog/impl/CatalogBuilderTest.java

Fix acts on `CatalogBuilder` to make sure even geometryless layers are assigned a (fake) SRS and lat/lon BBOX.
See [related Mailing list discussion](http://osgeo-org.1560.x6.nabble.com/Should-CatalogBuilder-set-a-default-SRS-if-none-was-found-td5226811.html).

[GEOS-7216] WFS GetCapabilities throws NPE if published layer has no geometry

---

src/extension/importer/core/src/main/java/org/geoserver/importer/DataStoreFormat.java
src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
src/extension/importer/core/src/test/java/org/geoserver/importer/ImporterDataTest.java
src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/RESTDataTest.java
src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/TaskResourceTest.java

Moved bounds calculation from `createContext()` to `doImport()` (DataStoreFormat only)
See https://osgeo-org.atlassian.net/browse/GEOS-7227
Some changes to test cases:
* Removed checks for null bounds; no longer applicible
* Added check to confirm a user-defined CRS is preserved after bounds are calculated

[GEOS-7227] Defer bounds calculation during import

---

src/extension/ogr/ogr-wps/pom.xml
src/extension/ogr/ogr-wps/src/test/java/org/geoserver/wps/ogr/WPSOgrTest.java
src/platform/pom.xml
src/platform/src/test/java/org/geoserver/util/XmlTestUtil.java
src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetFeatureTest.java

Fixes unit test failures that seem to be local to my machine in the WFS and OGR-WPS modules.
It's not clear why the WFS tests only fail on my machine.  The OGR-WPS ones are ignored if ogr2ogr is not present.  Adding it to ares so the tests run may be a good idea.

Fix unit test failures

---

src/pom.xml

Manage `xml-apis` version in parent POM to avoid version conflicts when Maven Cobertura plugin is run.

[GEOS-7256] Maven Cobertura plugin does not work

---

doc/en/developer/source/eclipse-guide/index.rst

We should probably make our own code template for GeoServer rather then requiring a manual step

fix svn links in developers guide

---

src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
src/extension/importer/core/src/test/java/org/geoserver/importer/ImporterTest.java

Continuation/improvement of https://github.com/geoserver/geoserver/pull/1247
When doing some downstream testing, I ran into a NPE in the vicinity of Importe.java:927. However, I was unable to reproduce this failure in a debugger.
Changes: 
* Updated the bounds status check to be more null-safe.
* Also updated the check to match string values of "true" (which can ocurr if the metadata has been saved to disk).

[GEOS-7227] Improve null handling for Import bounds calculation

---

doc/en/user/source/extensions/css/directives.rst

Avoid warning about title underline being too short.

Minor documentation fix

---

doc/en/user/source/community/gdal/index.rst
doc/en/user/source/community/gdal/usage_example.txt

Changing included file's extension from `*.rst` to `*.txt` removes compilation warning:
```
WARNING: document isn't included in any toctree
```

Fixed gdal-wcs usage example

---

src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/CapabilitiesTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesIntegrationTest.java

This is a pretty old bug: https://osgeo-org.atlassian.net/browse/GEOS-6432.
The PR extends current test for 1.1.1, and adds a new for 1.3.0. If there is an existing 1.3.0 test, would appreciate someone pointing it out to me.

[GEOS-6432] Include all supported WMS exception formats in GetCapabilities

---

data/citewcs-1.0/services.xml
data/citewfs-1.0/wcs.xml
data/citewfs-1.0/wfs.xml
data/citewfs-1.0/wms.xml
data/citewfs-1.1-h2/wcs.xml
data/citewfs-1.1-h2/wfs.xml
data/citewfs-1.1-h2/wms.xml
data/citewfs-1.1/wcs.xml
data/citewfs-1.1/wfs.xml
data/citewfs-1.1/wms.xml
data/citewms-1.1/wcs.xml
data/citewms-1.1/wfs.xml
data/citewms-1.1/wms.xml
data/release/wcs.xml
data/release/wfs.xml
data/release/wms.xml
src/community/gss/demo/central/wcs.xml
src/community/gss/demo/central/wfs.xml
src/community/gss/demo/central/wms.xml
src/community/gss/demo/unit/wcs.xml
src/community/gss/demo/unit/wfs.xml
src/community/gss/demo/unit/wms.xml
src/main/src/test/java/org/geoserver/config/services.xml
src/main/src/test/java/org/geoserver/data/test/services.xml
src/main/src/test/java/org/geoserver/logging/services.xml
src/wcs2_0/src/test/resources/wcs-test.xml
src/wfs/src/test/java/org/geoserver/wfs/wfs-minimal.xml
src/wfs/src/test/java/org/geoserver/wfs/wfs-test.xml
src/wms/src/test/resources/org/geoserver/wms/wms-test.xml

This updates the various configuration files (mainly used in
GetCapabilities) to be consistent in what they specify for
<maintainer> and <onlineResource>.
The original bug report (https://osgeo-org.atlassian.net/browse/GEOS-6226) talked about invalid entries which is not the case any longer. However we still had some variation, which is made consistent in this change.
For extra value, there are a few spelling fixes too.

[GEOS-6226] Make maintainer and onlineResource elements consistent

---

src/main/src/main/java/org/geoserver/config/GeoServerDataDirectory.java
src/main/src/test/java/org/geoserver/config/GeoServerDataDirectoryTest.java
src/main/src/test/resources/org/geoserver/config/external_with_params.sld

At the moment geoserver strips additional parameters from an external graphics resource:
/test/mypic.gen?param1=1
is transformed to
/test/mypic.gen
Additional parameters are very useful in customizng dynamic symbol renderers.
This patch preserves these parameters.

preserve parameters for relative external urls of an external graphics

---

src/pom.xml
src/wms/pom.xml

Pretty straight forward, no code changes. Only significant change is that some spring code that the wms module depeds on (some freemarker) stuff now lives in a new spring module, so there is a new dependency on spring-context-support required there.

Upgrading spring version to 3.2.15

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/FeatureGML32Test.java
src/wfs/src/main/java/org/geoserver/wfs/StoredQuery.java

To actually reproduce the issue, the provided unit test must be run on a test database, which is explained in the [GeoServer programming guide](http://docs.geoserver.org/latest/en/developer/programming-guide/app-schema/index.html#running-tests-from-junit).

[GEOS-7306] Stored Queries don't work on App-Schema layers backed by DB

---

src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/RawDataPPIO.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ppio/RawDataPPIOTest.java

Fixes issue with RawData input streams not being closed when encoding RawData

GEOS-7312 - close inputstream after finishing with it

---

src/wms/src/main/java/org/geoserver/wms/WMS.java
src/wms/src/main/java/org/geoserver/wms/featureinfo/GetFeatureInfoKvpReader.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java

Allow GetFeatureInfo on layer groups if at least one layer is queryable. Currently, if one layer in a layerGroup has querying disabled, the entire layer group is unequeryable.
See issues:
https://osgeo-org.atlassian.net/browse/GEOS-6340
https://osgeo-org.atlassian.net/browse/GEOS-7293
This feature was funded by: Tracasa (http://www.tracasa.es/en)

[GEOS-6340]: Allow GetFeatureInfo on layer groups if at least one layer is queryable

---

src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java
src/main/src/test/java/org/geoserver/catalog/impl/CatalogBuilderTest.java

This pull fix the issue https://osgeo-org.atlassian.net/browse/GEOS-7311.
The testSingleBandedCoverage test function (https://github.com/geoserver/geoserver/blob/master/src/main/src/test/java/org/geoserver/catalog/impl/CatalogBuilderTest.java#L192) now works in non-english environments.
Alvaro

[GEOS-7311]: Fix extraction of nullValues of a coverage

---

src/community/jdbcconfig/pom.xml
src/extension/importer/core/pom.xml
src/web/app/pom.xml

Was causing build issues when the `oracle` or `sqlserver` profiles were enabled to build the data store extensions along with the `jdbcconfig` or `importer` extensions.  The latter modules should have been using the `sqlserverDriver` and `oracleDriver` profiles instead.

Consolidate dependencies on proprietary JDBC drivers in profiles separate from building their data store extensions

---

doc/en/developer/source/policies/psc.rst

As per nomination of @smithkm :
Alessio Fabiani
Andrea Aime +1
Ben Caradoc-Davies +1 (second)
Christian Mueller +1
Jody Garnett +1 (motion)
Jukka Rahkonen +1
Phil Scadden
Simone Giannecchini +1

Update psc list

---

src/extension/importer/rest/src/main/resources/applicationContext.xml
src/extension/monitor/core/src/main/java/applicationContext.xml
src/rest/src/main/java/org/geoserver/rest/BeanResourceFinder.java
src/rest/src/test/java/applicationContext.xml
src/restconfig/src/main/java/applicationContext.xml
src/restconfig/src/main/java/applicationSecurityContext.xml

Found this one while reviewing old tickets. Not affecting much the core REST api, but unfortunately the importer and monitoring REST API are fully non thread-safe (facepalm!).
I've made sure that the BeanResourceFinder rebels against non thread safe usage and then fixed the application contexts.
If someone used BeanResourceFinder in REST plugins this change will pose backwards compatibility issues but... do we really want to allow thread unsafe usage?

[GEOS-4179] Importer and monitoring REST resources are not thread-safe

---

src/community/vectortiles/src/main/java/org/geoserver/wms/vector/PipelineBuilder.java
src/community/vectortiles/src/main/java/org/geoserver/wms/vector/VectorTileMapOutputFormat.java
src/community/vectortiles/src/main/resources/applicationContext.xml

I have made some changes to the module;
a) turned on clipping for all formats (applicationContext.xml)
* OpenLayers handles this properly now
b) add new option (applicationContext.xml) for oversampling 
* Results looked "blocky", setting this to "2" makes it more detailed
* please verify that I didn't miss anything!!
c) Changed from DouglasPeuckerSimplifier to TopologyPreservingSimplifier
* DP was not properly simplifying polygons with "thin" parts

improvments

---

doc/en/user/source/webadmin/data/layergroups.rst
src/main/src/main/java/org/geoserver/catalog/LayerGroupInfo.java
src/main/src/main/java/org/geoserver/catalog/impl/LayerGroupInfoImpl.java
src/main/src/main/java/org/geoserver/security/decorators/DecoratingLayerGroupInfo.java
src/web/core/src/main/java/org/geoserver/web/data/layergroup/AbstractLayerGroupPage.html
src/web/core/src/main/java/org/geoserver/web/data/layergroup/AbstractLayerGroupPage.java
src/web/core/src/main/resources/GeoServerApplication.properties
src/web/core/src/main/resources/GeoServerApplication_es.properties
src/wms/src/main/java/org/geoserver/wms/WMS.java
src/wms/src/main/java/org/geoserver/wms/featureinfo/GetFeatureInfoKvpReader.java
src/wms/src/main/java/org/geoserver/wms/kvp/MapLayerInfoKvpParser.java
src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java

This pull allows make a Layer Group explicitly not queryable. Currently, a layer Group is queryable if it contains at least a queryable layer, and the user can not override it.
See issues:
https://osgeo-org.atlassian.net/browse/GEOS-7294
This feature was funded by: Tracasa (http://www.tracasa.es/en)

[GEOS-7294] Allow make a Layer Group not queryable

---

doc/en/user/source/styling/sld-reference/textsymbolizer.rst

Add scalable font size example for TextSymbolizer

Add scalable font size example

---

src/wcs/src/main/java/org/geoserver/wcs/WCSInfoImpl.java

These appear to be unintentionally duplicated identically, removing the second copy.

Duplicated isGmlPrefixing and setGmlPrefixing?

---

src/wms/src/main/java/org/geoserver/wms/map/RenderedImageMapOutputFormat.java
src/wms/src/test/java/org/geoserver/wms/map/GetMapIntegrationTest.java

Fix for:
[GEOS-7352] Error rendering coverage with transformation when out of bounding box
This can be backported to 2.8.x and 2.7.x.

[GEOS-7352] Error rendering coverage with transformation when out of bounding box

---

doc/en/developer/source/programming-guide/versioning/wfsv/oracle.rst

Small typo in the documentation appears in the page title, so also shows in the parent page's TOC tree.

Fixed typo in the Oracle Workspace Manager documentation title

---

src/extension/wps/wps-core/src/main/java/org/geoserver/wps/resource/CoverageResourceListener.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/resource/CoverageResourceListenerTest.java

LazyInputMap fires a ProcessEvent before it begins loading the inputs and another ProcessEvent after each input is loaded.  The current CoverageResourceListener will only check the inputs on the first event, where all of the inputs will be null.  This can result in leaking file handles.
This pull request updates CoverageResourceListener to check for non-null values.

[GEOS-7366] Fixed a WPS file handle leak.

---

src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONBuilder.java
src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
src/wfs/src/main/java/org/geoserver/wfs/json/RoundingUtil.java
src/wfs/src/test/java/org/geoserver/wfs/json/GeoJSONBuilderTest.java
src/wfs/src/test/java/org/geoserver/wfs/json/GeoJSONTest.java
src/wfs/src/test/java/org/geoserver/wfs/json/PointReduced.properties
src/wfs/src/test/java/org/geoserver/wfs/json/RoundingUtilTest.java

This change adds support for limiting the number of decimal places used
for doubles when outputting GeoJSON responses to WFS queries.  Unit tests
are also added for this functionality.

[GEOS-2613] GeoJSON support for setting decimal places.

---

src/wms/src/main/java/org/geoserver/wms/GetMap.java

It avoids a possible memory leak when the GetMap method throws an error.

Avoid log about non existing memory leak

---

src/web/core/src/main/java/org/geoserver/web/GeoServerApplication.java
src/web/core/src/main/java/org/geoserver/web/GeoServerResourceStreamLocator.java
src/web/core/src/test/java/org/geoserver/web/GeoServerResourceStreamLocatorTest.java

Updates the name iterator to avoid returning multiple locale specific
resource names for resources we don’t ship locale specific versions of.
Also turns off minified resources.

Updates GeoServerResourceStreamLocator to avoid resource lookups.

---

src/web/core/src/main/java/org/geoserver/web/data/resource/CoverageBandsConfigurationPanel.java

Fall back to regular DoubleConverter after special infinity cases are covered. Previous code caused issues because BigDecimal can't handle Double.INFINITY

Update the DoubleInfinityConverter to fall back to its super class

---

src/web/demo/src/main/java/org/geoserver/web/demo/DemoRequestResponse.java

AttributeModifier apparently has slightly different behavior than what was previously used to change the form URL on the WCS/WPS request builder pages.

Fix for request builder pages

---

doc/en/user/source/production/java.rst

OpenGeo provides native installer resources for JAI and JAI Image I/O. User may have problems to find bin packages via Oracle pages since there are only Versions 1.1.2 / 1.0 available (http://www.oracle.com/technetwork/java/javasebusiness/downloads/java-archive-downloads-java-client-419417.html)

Changed JAI Download links to data.opengeo.org

---

src/wms/src/test/java/org/geoserver/wms/WMSDimensionsTestSupport.java

@aaime I think you originally added the test, can you take a look at this replacement? I had some issues with it randomly on my machine (I think because the method used autocasts to float from long) and I think the replacement should accomplish the same thing. 
Update the assertDateEquals method to compare that the dates are within the tolerance of one another, rather than using the method from Assert.assertEquals. The assertEquals that it was using
was autocasting to float, which was then causing infrequent issues (at least for me). The updated method should accomplish the intended goal and the tests still pass

Updated the assertDateEquals to compare difference

---

src/wfs/src/main/java/org/geoserver/wfs/kvp/FilterKvpParser.java
src/wfs/src/test/java/org/geoserver/wfs/kvp/Filter_2_0_0_KvpParserTest.java

See: https://osgeo-org.atlassian.net/browse/GEOS-7385
Supersedes: https://github.com/geoserver/geoserver/pull/1446

[GEOS-7385] Do not re-encode Filter in default charset when parsing WFS KVP Filter

---

src/community/release/ext-geogig.xml

The includes pattern doesn't match the plugin artifact JAR file name.

Fixing GeoGig plugin assembly descriptor

---

src/wms/src/main/java/org/geoserver/wms/featureinfo/FeatureInfoStylePreprocessor.java
src/wms/src/test/java/org/geoserver/wms/featureinfo/RenderingBasedFeatureInfoTest.java
src/wms/src/test/resources/org/geoserver/wms/featureinfo/dashed-exp.sld

This patch makes the WMS GetFeatureInfo operation work with styles that contains strokes with dash-arrays that contains expressions. Something like this for example:
```
(...)
<LineSymbolizer>
<Stroke>
<CssParameter name="stroke">#0000FF</CssParameter>
<CssParameter name="stroke-dasharray">
<ogc:Mul>
<ogc:Function name="strLength">
<ogc:Literal>VWXYZ</ogc:Literal>
</ogc:Function>
<ogc:Literal>4</ogc:Literal>
</ogc:Mul>
<ogc:Literal>5</ogc:Literal>
</CssParameter>
</Stroke>
</LineSymbolizer>
(...)
```
I also added a test for this use case.

[GEOS-7255] Makes WMS GetFeatureInfo work with expressions dash-arrays

---

src/wms/src/main/java/org/geoserver/wms/featureinfo/FeatureInfoStylePreprocessor.java
src/wms/src/test/java/org/geoserver/wms/featureinfo/RenderingBasedFeatureInfoTest.java
src/wms/src/test/resources/org/geoserver/wms/featureinfo/dashed-exp.sld

This patch makes the WMS GetFeatureInfo operation work with styles that contains strokes with dash-arrays that contains expressions. Something like this for example:
```
(...)
<LineSymbolizer>
<Stroke>
<CssParameter name="stroke">#0000FF</CssParameter>
<CssParameter name="stroke-dasharray">
<ogc:Mul>
<ogc:Function name="strLength">
<ogc:Literal>VWXYZ</ogc:Literal>
</ogc:Function>
<ogc:Literal>4</ogc:Literal>
</ogc:Mul>
<ogc:Literal>5</ogc:Literal>
</CssParameter>
</Stroke>
</LineSymbolizer>
(...)
```
I also added a test for this use case.

[GEOS-7255] Makes WMS GetFeatureInfo work with expressions dash-arrays (backport to 2.8.x)

---

src/main/src/main/java/org/geoserver/catalog/impl/LocalWorkspaceCatalog.java
src/main/src/test/java/org/geoserver/catalog/impl/LocalWorkspaceLayersTest.java

The LayerGroup object ignores its LocalWorkspaceIncludesPrefix setting when the object is fetched from "catalog.getLayerGroups()" method. It works ok when the LayerGroup object is fetched from "catalog.getLayerGroupByName('x')" method.
This PR fixes the issue:
https://osgeo-org.atlassian.net/browse/GEOS-7370
This feature was funded by: Tracasa (http://www.tracasa.es/en)

[GEOS-7370] Fix use of LocalWorkspaceIncludesPrefix setting

---

src/community/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
src/community/geofence/src/test/java/org/geoserver/geofence/AccessManagerTest.java

Currently if GeoFence is active a request like this:
`curl -X GET 'http://localhost:8080/geoserver/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&STYLES=,line&LAYERS=tiger-ny,tiger_roads&SRS=EPSG%3A4326&WIDTH=531&HEIGHT=768&BBOX=-74.05900955200195%2C40.640830993652344%2C-73.87670516967773%2C40.9045028686523445' -o result.png`
will provoke an index out of bounds exception.
This patch allow GeoFence to properly handle requests that contains LayerGroups, normal Layers and dynamic styles.
This patch also adds a test case for this.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7414

[GEOS-7414] Fix LayerGroups styles handling in Geofence

---

src/community/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
src/community/geofence/src/test/java/org/geoserver/geofence/AccessManagerTest.java

Currently if GeoFence is active a request like this:
`curl -X GET 'http://localhost:8080/geoserver/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&STYLES=,line&LAYERS=tiger-ny,tiger_roads&SRS=EPSG%3A4326&WIDTH=531&HEIGHT=768&BBOX=-74.05900955200195%2C40.640830993652344%2C-73.87670516967773%2C40.9045028686523445' -o result.png`
will provoke an index out of bounds exception.
This patch allow GeoFence to properly handle requests that contains LayerGroups, normal Layers and dynamic styles.
This patch also adds a test case for this.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7414

[GEOS-7414] Fix LayerGroups styles handling in Geofence (backport to 2.8.x)

---

src/main/src/main/java/org/geoserver/security/InMemorySecurityFilter.java
src/main/src/main/java/org/geoserver/security/SecureCatalogImpl.java
src/main/src/test/java/org/geoserver/security/impl/SecureCatalogImplFilterTest.java
src/web/demo/src/test/java/org/geoserver/web/demo/PreviewLayerProviderMixedModeTest.java
src/web/demo/src/test/java/org/geoserver/web/demo/PreviewLayerProviderTest.java
src/web/demo/src/test/resources/org/geoserver/web/demo/ResourceAccessManagerContext.xml
src/wfs/src/test/java/org/geoserver/wfs/ResourceAccessManagerWFSTest.java

Mixed mode is quite more popular that I'd thought.
Make sure we only throw in mixed mode when there is a direct single resource access, evaluating what "single" means at the Catalog API access level (if one uses an access by id or by name, then that's direct access, some external information was provided by a user to get there), and hide the layers when just listing or filtering based on workspace and the like. 
Solves GEOS-5714, GEOS-4695, GEOS-3903, GEOS-5290

Fixes to mixed mode catalog behavior

---

src/main/src/main/java/org/geoserver/catalog/ResourcePool.java

Changed the ResourcePool to use a non-deprecated method to get the style body. Deprecated method used the file interface, which caused issues when using JDBC resource store.

Updating the ResourcePool to use non-deprecated method

---

data/release/demo/WPS_aggregate_1.0.xml
data/release/demo/WPS_aggregate_groupby_1.0.xml
doc/en/user/source/services/wps/processes/gs.rst

Improves the documentation of the WPS aggregate process adding real examples that can be executed againts data shipped by GeoServer release. It also documents the output formats and how they should be interpreted.

[GEOS-7440] Document the WPS aggregate process

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SecuredFeatureChainingTest.java
src/main/src/main/java/org/geoserver/security/decorators/SecuredDataStoreInfo.java

Takes the simplest path and changes the signature of `SecuredDataStoreInfo.getDataStore` to return a generic `DataAccess<FeatureType, Feature>` instance.
Formally, this is a public API change, but shouldn't present a real problem, as the `getDataStore` method in `DataStoreInfo` (the interface decorated by `SecuredDataStoreInfo`) already returns `DataAccess<FeatureType, Feature>`.

[GEOS-7459] Securing an app-schema data store may result in ClassCastException being thrown

---

src/extension/excel/src/main/resources/GeoServerApplication.properties
src/pom.xml
src/web/app/pom.xml

Three very small updates for the Excel module:
* Add a web app profile for Excel
* Add Wicket `wfs.format` labels for Excel output formats
* Update Apache POI to 3.14
I don't believe any of these changes require new test cases.

Excel extension module updates

---

src/pom.xml

* Prevent Java Serialization vulnerability of having cc 3.2.1 and earlier on the classpath
* https://commons.apache.org/proper/commons-collections/security-reports.html
Related PRs:
https://github.com/locationtech/geomesa/pull/827
https://github.com/geotools/geotools/pull/1128
https://github.com/GeoWebCache/geowebcache/pull/376
Signed-off-by: Andrew Hulbert <andrew.hulbert@ccri.com>

Upgrade to commons-collections 3.2.2 to address CVE-2015-8103

---

src/pom.xml

This baby brings down the build times of a "-Prelease -T4" build from almost 21 minutes to 14.30 on my computer. 
Suggestion from http://zeroturnaround.com/rebellabs/your-maven-build-is-slow-speed-it-up/

Secret knobs to speed up short lived JVM

---

src/pom.xml

On my computer this single change cuts the release build time from 20:43 down to 19:13, or a minute and a half speedup.

[GEOS-7474] Speed up usage of git-commit-it

---

src/gwc/src/main/resources/geowebcache-rest-context.xml

@smithkm this is the GeoServer counterpart to the GeoWebCache PR https://github.com/GeoWebCache/geowebcache/pull/374
Do not merge this PR until GeoWebCache PR https://github.com/GeoWebCache/geowebcache/pull/374 is merged. This PR must then be merged or the GeoServer build will break.
It is expected that Travis CI will fail for this PR as it does not know about the GeoWebCache changes.

Delete cached tiles when layer removed with REST DELETE via integrated GeoWebCache

---

src/community/pom.xml

There was already a mechanism to do the same thing another way.
The script module defines default on profiles for its submodules which can be deactivated.
`-P script,-script-js,-script-bsh,-script-rb,-script-groovy`

Revert #1558

---

src/main/src/main/java/org/geoserver/catalog/SLDHandler.java
src/main/src/main/java/org/geoserver/config/LockProviderInitializer.java
src/main/src/main/java/org/geoserver/logging/LoggingUtils.java
src/main/src/test/java/org/geoserver/catalog/PropertyStyleHandler.java
src/main/src/test/java/org/geoserver/catalog/StylesTest.java
src/main/src/test/java/org/geoserver/logging/LoggingStartupContextListenerTest.java
src/platform/src/main/java/org/geoserver/platform/resource/FileSystemResourceStore.java

…by changing logging level or styles. Lock held open when stream is not closed due to use of Resoruce.in() obtaining a lock on creation and releasing the lock on close().
See https://osgeo-org.atlassian.net/browse/GEOS-7492

[GEOS-7492] Admin can temporarily lock themselves out of UI or REST

---

doc/en/user/source/extensions/importer/rest_examples.rst

While the Importer REST API examples contained plenty of the more complicated upload into postgis processes, there was no example for a more basic workflow. This commit adds a the basic example of uploading a file to an existing postgis store.
Thanks to @DBlasby for the example content.

Add upload shapefile to postgis example to importer docs

---

doc/en/user/source/community/remote-wps/install_geoserver.rst

It looks like usages of -XX:MaxPermSize have already been removed from the codebase, but this paramater is still mentioned in the docs.

Java 8: Remove -XX:MaxPermSize (from docs)

---

src/community/geofence-server/src/main/resources/applicationContext.xml

Issue with description: https://osgeo-org.atlassian.net/browse/GEOS-7494

[GEOS-7494] Makes geofence-server uses the correct properties file (backport 2.8.x)

---

src/main/src/main/java/org/geoserver/security/SecureCatalogImpl.java
src/main/src/main/java/org/geoserver/security/decorators/SecuredLayerInfo.java
src/main/src/test/java/org/geoserver/security/impl/AbstractAuthorizationTest.java
src/main/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java

Issue: https://osgeo-org.atlassian.net/browse/GEOS-7499
The cause of this issue was SecureCatalogImpl and SecuredLayerInfo not properly handling the SecuredWMSLayerInfo wrapper.
The SecureCatalogImpl was not unwrapping resources info of type SecuredWMSLayerInfo, this was provoking the "Not a proxy error" exception.
The SecuredWMSLayerInfo was not unwrapping resources info of type SecuredWMSLayerInfo in the setResource method, so it was overriding the existing layer WMSLayerInfo resource with the secure wrapper. So the first request will go well and the next ones will fail (tricky to found this error).
This pull request add proper handling for the SecuredWMSLayerInfo wrapper and also add tests cases for this.

[GEOS-7499] Fix unwrapping of SecuredWMSLayerInfo in SecuredLayerInfo and SecureCatalogImpl (backport to 2.8.x)

---

src/main/src/main/java/org/geoserver/security/SecureCatalogImpl.java
src/main/src/main/java/org/geoserver/security/decorators/SecuredLayerInfo.java
src/main/src/test/java/org/geoserver/security/impl/AbstractAuthorizationTest.java
src/main/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java

Issue: https://osgeo-org.atlassian.net/browse/GEOS-7499
The cause of this issue was SecureCatalogImpl and SecuredLayerInfo not properly handling the SecuredWMSLayerInfo wrapper.
The SecureCatalogImpl was not unwrapping resources info of type SecuredWMSLayerInfo, this was provoking the "Not a proxy error" exception.
The SecuredWMSLayerInfo was not unwrapping resources info of type SecuredWMSLayerInfo in the setResource method, so it was overriding the existing layer WMSLayerInfo resource with the secure wrapper. So the first request will go well and the next ones will fail (tricky to found this error).
This pull request add proper handling for the SecuredWMSLayerInfo wrapper and also add tests cases for this.

[GEOS-7499] Fix unwrapping of SecuredWMSLayerInfo in SecuredLayerInfo and SecureCatalogImpl

---

src/platform/src/main/java/org/geoserver/platform/resource/Files.java
src/platform/src/main/java/org/geoserver/platform/resource/Paths.java
src/platform/src/test/java/org/geoserver/platform/resource/FileWrapperResourceTheoryTest.java
src/platform/src/test/java/org/geoserver/platform/resource/ResourceTheoryTest.java
src/restconfig/src/main/java/org/geoserver/rest/resources/ResourceFinder.java
src/restconfig/src/main/java/org/geoserver/rest/resources/ResourceResource.java

See:
Paths.names (method used by multiple ResourceStores) not removing root slash
https://osgeo-org.atlassian.net/browse/GEOS-7493

GEOS-7493 Path.names not removing root slash

---

doc/en/user/source/webadmin/tilecache/defaults.rst
src/web/gwc/src/main/java/org/geoserver/gwc/web/InMemoryBlobStorePanel.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/GWCSettingsPageTest.java

The issue associated with this pull request: https://osgeo-org.atlassian.net/browse/GEOS-7523
This pull request fixes the issue, updates the documentation and add a test case.

[GEOS-7523] Make GWC settings UI only show the accepted eviction policies (backport 2.8.x)

---

src/community/vectortiles/pom.xml
src/community/vectortiles/src/main/java/no/ecc/vectortile/VectorTileEncoderNoClip.java
src/community/vectortiles/src/main/java/org/geoserver/wms/mapbox/MapBoxTileBuilder.java
src/community/vectortiles/src/test/java/org/geoserver/wms/mapbox/MapBoxTileBuilderTest.java

See details in ticket.
a) moved to 1.0.9
b) created subclass that doesn't do any clipping
c) use the sub-class

GEOS-7521: fix external module so it doesn't clip

---

src/main/src/main/java/org/geoserver/config/GeoServerPropertyOverrideConfigurer.java
src/main/src/test/java/org/geoserver/config/GeoServerPropertyOverrideConfigurerTest.java

Associated issues: 
- https://osgeo-org.atlassian.net/browse/GEOS-7534
- https://osgeo-org.atlassian.net/browse/GEOS-7204

[GEOS-7534] Make GeoServerPropertyOverrideConfigurer use replace method

---

src/main/src/main/java/org/geoserver/config/GeoServerPropertyOverrideConfigurer.java
src/main/src/test/java/org/geoserver/config/GeoServerPropertyOverrideConfigurerTest.java

Backport of this pull request: https://github.com/geoserver/geoserver/pull/1590
I have manually tested this on windows and linux with a path similar to this: 
`C:\Users\nuno\Work\GEOSERVERDATA\a~è$%  ºhãç éº` (of course unit tests for this also exists).

[GEOS-7534] Make GeoServerPropertyOverrideConfigurer use replace method (backport 2.9.x)

---

src/main/src/main/java/org/geoserver/config/GeoServerPropertyOverrideConfigurer.java
src/main/src/test/java/org/geoserver/config/GeoServerPropertyOverrideConfigurerTest.java

Backport of this pull request: #1590
I have manually tested this on windows and linux with a path similar to this:
`C:\Users\nuno\Work\GEOSERVERDATA\a~è$% ºhãç éº` (of course unit tests for this also exists).

[GEOS-7534] Make GeoServerPropertyOverrideConfigurer use replace method (backport 2.8.x)

---

doc/en/developer/source/release-guide/index.rst

After doing the GeoServer 15-RC1 release, I found that the release guide was incomplete and out-of-date in some places. This intends to remedy the problems I found:
**Add manual jira publishing instructions.**
The current release instructions rely on the `geoserver-release-jira` job on the ares jenkins server. This job has not been working for about a year. Until someone finds the time to fix the JIRA release scripts, the Release Guide should be updated with manual release steps.
**Add note for OS X sed scripts.**
The sed scripts used to update the pom files with the new release dependancies do not run on OS X. I have added a not on how to get them to work on OS X. Unfortunately, there is no way to modify the command in a way that is compatible with both OS's while preserving the same …

Update release guide

---

doc/en/developer/source/eclipse-guide/index.rst

Downloading the links to the eclipse formatter configuration and the code templates resulted in downloading a HTML version of these files. This PR changes the links to point directly to the raw files.

Use github raw urls to reference eclipse configuration files

---

src/release/installer/win/GeoServerEXE.nsi
src/release/installer/win/wrapper.conf

Jetty fails to start when running GeoServer as a Windows service.
The PR updates GeoServerEXE.nsi script to create a temporary files directory for Jetty and wrapper.conf according to comments on GEOS-7507.

GEOS-7507 windows installer service wrapper jetty update

---

src/kml/src/main/java/org/geoserver/kml/sequence/PlainFolderSequenceFactory.java
src/kml/src/test/java/org/geoserver/kml/KMLTest.java

Rather than grabbing the raw feature source use the current context feature
collection, which already has been set up to deal with reprojection, etc...

GEOS-7369: Handling placemarks encoded with ground overlay for data in projected crs.

---

src/pom.xml

A 3rd party repo went down and was causing the build to take > 10 hours due to very long timeouts.
Given the way that Maven handles repo failures, I think that we should do our best to minimize the number of repos included. All of the necessary jars seem to be pulling correctly when only the Boundless and OSGeo repositories are used.
I was having a problem pulling a jar when building the community extensions, but the project (geoscript-py) is currently semi abandoned and was relying on unsupported snapshots.
[I submitted this previously, but had accidentally done it off of a branch under active development]

Remove unnecessary repositories from main pom file

---

src/release/ext-netcdf-out.xml

Fairly basic configuration change based on testing the netcdf-out extension. It turns out it was missing the jar required for native linking (required for NetCDF 4 support).

[GEOS-7597] Add JNA to netcdf-out release configuration

---

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/JDBCGeoServerLoader.java

See issue here: https://osgeo-org.atlassian.net/browse/GEOS-7595
Looking at the existing test case, it only test the empty config / no import case, hence why it didn't catch this issue. I would have liked to add a proper test case, but was not quite sure how to implement it properly, given that: (a) jdbcconfig relies upon an existing configuration, and a database and (b) I am not especially familiar with jdbcconfig.
While this is a community module and therefore strictly speaking does not require a test case, I would be much happier if it had one. I would appreciiate it if someone more familiar with the jdbcconfig module would either be able to add a proper test case, or give me a few pointers.
Also: @NielsCharlier - this change reverts some of the changes you made for …

[GEOS-7595] Fix JDBCConfig import

---

src/pom.xml

GeoTools uses commons-pool 1.5.4 via gt-referencing
GeoServer explicitly requires commons-pool 1.5.3 in the top level pom. However, the only dependancies that use this are gt-referencing (via gs-wcs) and commons-dbcp (via gs-jdbcconfig), both of which actually depend upon 1.5.4.
The GeoServer dependancy appears necessary in order for the release module to actually pick up the jar during packaging.
This PR fixes the patch version so that we are actually consistent with the dependancies that are pulling this jar.

Match geotools commons-pool version

---

src/extension/netcdf-out/src/main/java/org/geoserver/netcdfout/NetCDFOutStatus.java

Ask the native lib for its version (if available), put in Status Page message.
This implementation uses reflection because JNA is an optional jar.

GEOS-7567 GSIP-143 netcdf-out status page - add native lib version (if available)

---

src/main/src/main/java/applicationContext.xml
src/platform/src/main/java/org/geoserver/platform/SystemEnvironmentStatus.java
src/platform/src/main/java/org/geoserver/platform/SystemPropertyStatus.java
src/platform/src/test/java/org/geoserver/platform/SystemEnvironmentTest.java
src/platform/src/test/java/org/geoserver/platform/SystemPropertiesStatusTest.java

Added status page for System.getenv and System.getProperties.
Also, noticed that RenderingEngineStatusTest.java didn't have (c) header and had incorrect formating - fixed.

GSIP-143 add status page for system properties and environment

---

CONTRIBUTING.md
doc/en/developer/source/policies/committing.rst
doc/en/developer/source/policies/review.rst

This implements the documentation changes as proposed under GSIP-147.
See https://github.com/geoserver/geoserver/wiki/GSIP%20147 for proposal.
It also fixes a few broken links in the affected files, which came up during testing.

[GEOS-7629] GSIP-147 Align with Geotools copyright header management practices

---

src/main/src/main/java/org/geoserver/GeoServerConfigurationLock.java
src/web/core/src/main/java/org/geoserver/web/GeoServerApplication.java
src/web/core/src/main/java/org/geoserver/web/GeoServerHomePage.java
src/web/core/src/main/java/org/geoserver/web/GeoServerUnlockablePage.java
src/web/core/src/main/java/org/geoserver/web/ServerBusyPage.html
src/web/core/src/main/java/org/geoserver/web/ServerBusyPage.java
src/web/core/src/main/java/org/geoserver/web/WicketCallback.java
src/web/core/src/main/java/org/geoserver/web/WicketConfigurationLockCallback.java
src/web/core/src/main/resources/GeoServerApplication.properties
src/web/core/src/test/java/org/geoserver/web/admin/AbstractAdminPrivilegeTest.java
src/web/core/src/test/java/org/geoserver/web/admin/ServerBusyPageTest.java

The idea behind this proposal is the following one:
Currently GeoServer tries to acquire an exclusive lock when accessing pages which can read/write the configuration through the WicketConfigurationCallback, thus causing the UI to hang until the configuration has been released by the catalog.
The problem is that in some cases, if the configuration change requires too much, the UI is not accessible at all.
With this PR I would like to address to goals:
1. Avoid completely freeze the UI when the configuration is locked
2. Allow a developer (who knows what he is doing) to create pages which can be accessed also when the configuration is locked by some process (thing for instance to an extension which needs to safely cancel/stop a long write operation)
The proposed solution is the following …

PR: (GEOS-7619) Allow the Wicket UI to show a Server Busy page when updating the configuration instead of locking the server

---

src/extension/importer/core/src/main/java/org/geoserver/importer/FeatureDataConverter.java
src/extension/importer/core/src/test/java/org/geoserver/importer/FeatureDataConverterTest.java

The default conversion applies logic to rename attributes with spaces or other
cases where the name is not a valid XML element name. This matches the behaviour
of the conversion that is done on the feature by feature level.

GEOS-7646: Applying default conversion to feature type for PostGIS.

---

src/community/geogig/src/main/java/org/geogig/geoserver/rest/InitCommandResource.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/InitRequestHandler.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/GeoServerFunctionalTestContext.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/PluginWebAPICucumberHooks.java
src/community/geogig/src/test/resources/org/geogig/geoserver/functional/PluginInitRepository.feature

- Remove automatic DataStore creation during INIT via plugin
- Return a 400 Bad Request if Content-Type is not supported,
instead of creating a GeoGig repository with default config.

Align plugin for GeoGig REST implementation with GeoGig Web API

---

src/web/core/src/main/java/org/geoserver/web/wicket/DecimalConverter.java
src/web/core/src/test/java/org/geoserver/web/wicket/DecimalTextFieldTest.java

[GEOS-7661] Support NaN in DecimalConverter

---

doc/en/user/source/community/jms-cluster/index.rst

This is a proposed fix for: https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-7212

[GEOS-7212] Missing links in "JMS based Clustering" documentation

---

src/community/jms-cluster/jms-geoserver/pom.xml
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/DocumentFile.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/DocumentFileHandler.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogStylesFileHandler.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/DocumentFileTest.java
src/community/jms-cluster/jms-geoserver/src/test/resources/document_file_1.xml

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7467
JMD plugin doesn't serialize and send the whole store anymore. A test case was added for this.

[GEOS-7467] Make JMS cluster plugin only serialize the necessary data

---

src/community/geogig/src/main/java/org/geogig/geoserver/config/ConfigStore.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/GeoServerGeoGigRepositoryResolver.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryCache.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryInfo.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryManager.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/GeoServerRepositoryProvider.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/InitCommandResource.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/InitRequestHandler.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/repository/RepositoryEditFormPanel.java
src/community/geogig/src/main/resources/applicationContext.xml
src/community/geogig/src/test/java/org/geogig/geoserver/config/ConfigStoreTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/GeoServerFunctionalTestContext.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/PluginWebAPICucumberHooks.java
src/community/geogig/src/test/java/org/geogig/geoserver/rest/GeoGigWebAPIIntegrationTest.java
src/web/app/pom.xml

- Fix GeoGig repository name on Init with PG backend
- Add geogig profile to web/app/pom.xml
- Let RepositoryManager cache RepositoryInfo instances
- Simplified RepositoryInfo.getRepoName()
- It simply delegates to RepositoryResolver.getName(URI),
the logic to resolve the name has been moved to geogig.
- Make sure RepositoryCache returns an open repository if it exists
- Follow up from upstream: upgrade web api to use Repository instead of GeoGIG
- Don't let DataStore.dispose() close the geogig repository.
- Repository instances are cached as it can be resource
intensive to continuously create and destroy them.

[Up-port from 2.9] Fix GeoGig plugin to align with GeoGig core changes

---

src/community/geogig/src/main/java/org/geogig/geoserver/config/ConfigStore.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/GeoServerGeoGigRepositoryResolver.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryCache.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryInfo.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryManager.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/GeoServerRepositoryProvider.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/InitCommandResource.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/InitRequestHandler.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/repository/RepositoryEditFormPanel.java
src/community/geogig/src/main/resources/applicationContext.xml
src/community/geogig/src/test/java/org/geogig/geoserver/config/ConfigStoreTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/GeoServerFunctionalTestContext.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/PluginWebAPICucumberHooks.java
src/community/geogig/src/test/java/org/geogig/geoserver/rest/GeoGigWebAPIIntegrationTest.java

- Fix GeoGig repository name on Init with PG backend
- Add geogig profile to web/app/pom.xml
- Let RepositoryManager cache RepositoryInfo instances
- Simplified RepositoryInfo.getRepoName()
- It simply delegates to RepositoryResolver.getName(URI),
the logic to resolve the name has been moved to geogig.
- Make sure RepositoryCache returns an open repository if it exists
- Follow up from upstream: upgrade web api to use Repository instead of GeoGIG
- Don't let DataStore.dispose() close the geogig repository.
- Repository instances are cached as it can be resource
intensive to continuously create and destroy them.

[Backport from 2.9] Fix GeoGig plugin to align with GeoGig core changes

---

src/release/installer/mac/build.xml

Looks like this URL didn't get updated to the new repo location.

App bundler jar URL fix

---

src/community/jms-cluster/jms-geoserver/pom.xml
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/DocumentFile.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/DocumentFileHandler.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogStylesFileHandler.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/DocumentFileTest.java
src/community/jms-cluster/jms-geoserver/src/test/resources/document_file_1.xml

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7467
JMS plugin doesn't serialize and send the whole store anymore. A test case was added for this.

[GEOS-7467] Make JMS cluster plugin only serialize the necessary data (backport 2.9.x)

---

src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/LegendCapabilitiesTest.java

The WMS get capabilities page now contains the correct link for workspaced legend graphics.

[GEOS-7635] Workspaced legendgraphics fix

---

src/community/params-extractor/src/main/java/org/geoserver/params/extractor/EchoParametersDao.java
src/community/params-extractor/src/main/java/org/geoserver/params/extractor/Filter.java
src/community/params-extractor/src/main/java/org/geoserver/params/extractor/RulesDao.java
src/community/params-extractor/src/main/java/org/geoserver/params/extractor/UrlMangler.java
src/community/params-extractor/src/test/resources/testApplicationContext.xml

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7671
The params-extractor community module was relying on GeoServerDataDirectory implementing the ResourceStore interface.
This was a consequence of the ResourceStore interface use clean:
https://github.com/nmco/geoserver/commit/8039744f129957dec49ce585c110a0e19868922a

[GEOS-7671] Params-Extractor module should rely on GeoServerDatadir instead of ResourceStore interface

---

doc/en/user/source/styling/sld/extensions/rendering-transform.rst

it doesn't seem like this documentation reflects a change to the namespaces for the geotools processes that are referenced.  I thought it may be nice to update this minor detail.

minor updates to reflect the newer namespace of the processes

---

src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/ImporterIntegrationTest.java
src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/RequestContextListener.java
src/extension/importer/rest/src/test/resources/applicationContext.xml

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7676
This pull request also provides a test case for this.
This is a backport to 2.8.x of pull request #1762

[GEOS-7676] Makes the importer share the request context when starting a job asynchronously (backport 2.8.x)

---

src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/ImporterIntegrationTest.java
src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/RequestContextListener.java
src/extension/importer/rest/src/test/resources/applicationContext.xml

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7676
This pull request also provides a test case for this.
This is a backport to 2.9.x of pull request https://github.com/geoserver/geoserver/pull/1762

[GEOS-7676] Makes the importer share the request context when starting a job asynchronously (backport 2.9.x)

---

src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/MultiDimensionalExtension.java
src/community/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/MultiDimensionalExtensionTest.java

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7725
Tests were updated so the content type of the responses are also checked.

[GEOS-7725] Makes WMTS multi dimensional operations use the correct content-type

---

src/wms/src/main/java/org/geoserver/wms/map/RenderedImageMapOutputFormat.java
src/wms/src/test/java/org/geoserver/wms/map/VectorToRasterTransformTest.java

I'll send an email to the dev list, but in general the assumption is that a vector-to-raster rendering transform is still going to make good use of the bbox in the query that is added to the query object in the StreamingRenderer code path, but not in the directRasterRender() code path.  For example the geotools HeatmapProcess by default will not make use of bbox in the query because it is using  Query.ALL supplied by the direct raster rendering path.
I can file a contributor agreement assuming this seems reasonable.

vector-to-raster render transform avoids direct raster path

---

src/web/core/src/main/java/org/geoserver/web/GeoServerBasePage.java
src/web/core/src/main/java/org/geoserver/web/css/geoserver.css
src/web/wms/src/main/java/org/geoserver/wms/web/data/AbstractStylePage.html
src/web/wms/src/main/java/org/geoserver/wms/web/data/AbstractStylePage.java
src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleEditPage.java
src/web/wms/src/main/resources/GeoServerApplication.properties

Removes the style name inside the page "contents" and puts it in the title instead

Get back some vertical space in the style editor

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/AbstractStylePage.java

https://osgeo-org.atlassian.net/browse/GEOS-7729
I tried adding a test case for this one, but it turns out we already test for the error message [here](https://github.com/geoserver/geoserver/blob/master/src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java#L109).
It looks like the tester is getting the page that results from the form submission, however the cause of this bug (not seeing error messages) is that this page never actually gets returned to the user (by calling target.add(...)).
I can't see any way to test for this behavior within the wicket test framework.
However, some basic manual testing shows that the fix does work (I'm not happy about not having a unit test, but can't see any way around it here).

[GEOS-7729] Display style page error messages on submit

---

src/wms/src/main/java/org/geoserver/wms/map/OpenLayersMapOutputFormat.java
src/wms/src/main/resources/org/geoserver/wms/map/OpenLayers3MapTemplate.ftl

https://osgeo-org.atlassian.net/browse/GEOS-7272
Either of this or https://github.com/geoserver/geoserver/pull/1702 is a viable fix
This is a hackier fix, but carries less risk of introducing problems with new projections, since it is not changing how we handle them.

[GEOS-7272] OL3 Preview wraps tiled layers

---

doc/en/user/source/data/raster/gdal.rst
src/release/ext-gdal.xml

See https://osgeo-org.atlassian.net/browse/GEOS-7578
When installing the GDAL extension using current versions of the native GDAL libraries, the user should use the gdal-*.jar bindings build with SWIG for the version of the GDAL binaries being used.
The imageio-ext-gdal-bindings*.jar is an older version of these GDAL bindings, and can cause classloader conflicts with current versions.

[GEOS-7578] Do not package outdated gdal-bindings jar

---

src/release/installer/mac/build.xml

Forgot this from the last release. The location of this jar changed.

Updating the appbundler jar link

---

src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
src/gwc/src/test/java/org/geoserver/gwc/layer/GeoServerTileLayerTest.java

Requesting WMS and LegendSample beans provokes a Spring cyclic dependency error. This pull request fix this issue by requesting the beans only when needed.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7750

[GEOS-7750] Get WMS and LegendSample beans only when needed

---

src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
src/gwc/src/test/java/org/geoserver/gwc/layer/GeoServerTileLayerTest.java

Requesting WMS and LegendSample beans provokes a Spring cyclic dependency error. This pull request fix this issue by requesting the beans only when needed.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7750
Backport of pull request: https://github.com/geoserver/geoserver/pull/1829

[GEOS-7750] Get WMS and LegendSample beans only when needed (backport 2.9.x)

---

src/extension/grib/src/test/java/org/geoserver/catalog/CoverageViewReaderTest.java
src/main/src/main/java/org/geoserver/catalog/CoverageViewReader.java

This is a fix for [GEOS-7749](https://osgeo-org.atlassian.net/browse/GEOS-7749) bug, regarding an ArrayIndexOutOfBounds exception that occurs on CoverageViewReader at the procedure of the resulting coverage dimension wrapping when any of the source coverages of the view have less bands than the resulting coverage.
A small test is also included to prove the fix.

[GEOS-7749] Fixed ArrayIndexOutOfBounds bug on sample dimensions calculation.

---

src/community/geogig/pom.xml
src/community/geogig/src/main/java/org/geogig/geoserver/config/PostgresConfigBean.java
src/community/geogig/src/test/java/org/geogig/geoserver/config/PostgresConfigBeanTest.java

- Address GeoGig issue: https://github.com/locationtech/geogig/issues/150
- Use Spring Web URIComponentsBuilder to correctly encode special characters
in the query parameter values for URIs

Fix URI building/parsing of PostgreSQL URIs for GeoGig

---

src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
src/gwc/src/test/java/org/geoserver/gwc/layer/GeoServerTileLayerTest.java

GeoServerTileLayer was always using the default width and height for the GetLegendeGraphics URL instead of of the computed values.
This pull request also updates the tests.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7746

[GEOS-7746] Use the computed width and height instead of the default values

---

src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
src/gwc/src/test/java/org/geoserver/gwc/layer/GeoServerTileLayerTest.java

GeoServerTileLayer was always using the default width and height for the GetLegendeGraphics URL instead of of the computed values.
This pull request also updates the tests.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7746
Backport of pull request: https://github.com/geoserver/geoserver/pull/1836

[GEOS-7746] Use the computed width and height instead of the default values (backport 2.9.x)

---

src/platform/src/main/java/org/geoserver/platform/GeoServerEnvironment.java
src/platform/src/test/java/org/geoserver/platform/GeoServerEnvironmentTest.java
src/platform/src/test/java/org/geoserver/platform/SystemEnvironmentTest.java

It is just a change of the default value of a flag. There's no need to add specific tests for this since there are already tests for GeoServerEnvironment functionality.

[GEOS-7754] GeoServer Environment Allow Parametrization should set to FALSE by Default

---

src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/DescribeDomainsTransformer.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/Domains.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/MultiDimensionalExtension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/CoverageDimensionsReader.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/Dimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/DimensionsUtils.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/HistogramUtils.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/RasterCustomDimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/RasterElevationDimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/RasterTimeDimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/VectorElevationDimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/VectorTimeDimension.java
src/community/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/MultiDimensionalExtensionTest.java
src/community/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/RasterElevationDimensionTest.java
src/community/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/RasterTimeDimensionTest.java
src/community/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/TestsSupport.java
src/community/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/VectorElevationDimensionTest.java
src/community/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/VectorTimeDimensionTest.java

This pull request provide two commits that fix this issues (one commit for each issue):
- https://osgeo-org.atlassian.net/browse/GEOS-7722
- https://osgeo-org.atlassian.net/browse/GEOS-7721
All the changes were made in the WMTS multi dimensional community module.
The existing dimensions retrieval machinery assumes that we always want the unique values (no duplicates) and hence returns the domain values in a TreeSet. The GetHistogram operation needs to access the full domain values (including the duplicates ones).
For every DescribeOperation a bounding box of the used features will be used as spatial domain and properly encoded in the response. When is not possible to compute a bounding  box for the selected features (no geometry, non structured reader, etc ...) a default referenced …

WMTS multi dimensional fixes

---

src/main/src/main/java/org/geoserver/catalog/ResourcePoolInitializer.java
src/main/src/main/java/org/geoserver/config/GeoServerInitializer.java
src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
src/main/src/main/java/org/geoserver/config/GeoServerReinitializer.java
src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java
src/web/core/src/main/java/org/geoserver/web/data/store/WMSStoreNewPage.java
src/web/core/src/test/java/org/geoserver/web/data/store/1.3.0Capabilities-xxe.xml
src/web/core/src/test/java/org/geoserver/web/data/store/WMSStoreNewPageTest.java

Add GeoServerReinitializer marker interface for GeoServerInitializers that should be run on both inital load and reload.
Updated test case, including improved cause verification based on GEOT-5533.

Re-set entityResolverPrivider on configuration reload. Pass entityResolver to WMSStore

---

doc/en/user/source/security/layer.rst
src/main/src/main/java/org/geoserver/security/impl/layers.properties.template
src/main/src/test/java/org/geoserver/catalog/impl/CascadeVisitorAbstractTest.java
src/wfs/src/test/java/org/geoserver/wfs/WFSCurvesTestSupport.java
src/wfs/src/test/java/org/geoserver/wfs/WFSXStreamLoaderTest.java
src/wfs/src/test/java/org/geoserver/wfs/v1_1/Transaction3DTest.java

This pull request changes the default configuration so that by default  layers data can only be edited by admin users. Documentation was also updated.
Mailing list discussion: http://osgeo-org.1560.x6.nabble.com/Who-changed-my-data-or-is-it-sane-to-have-WFS-T-open-to-all-by-default-td5286288.html
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7744
Backport of pull request: https://github.com/geoserver/geoserver/pull/1835

[GEOS-7744] Makes layers data by default only editable by admin users (backport 2.8.x)

---

src/community/geogig/src/main/java/org/geogig/geoserver/config/GeoServerGeoGigRepositoryResolver.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryCache.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/repository/RepositoryEditPanel.java

- Separate Geogig DataStore repository references from cached
references so repos don't get closed on DataStore instances

Fix GeoGig DB closed issue

---

src/extension/inspire/src/main/java/org/geoserver/inspire/wmts/InspireGridSetLoader.java
src/extension/inspire/src/main/resources/applicationContext.xml
src/extension/inspire/src/test/java/org/geoserver/inspire/wmts/InspireGridSetLoaderTest.java
src/gwc/src/main/java/org/geoserver/gwc/GWC.java

This pull request added a new method on GWC singleton to allow GeoServer extensions to register non editable grid sets.
https://osgeo-org.atlassian.net/browse/GEOS-7782

[GEOS-7782] Add INSPIRE grid set when INSPIRE extensions is loaded

---

doc/en/user/source/extensions/inspire/using.rst
src/extension/inspire/src/main/java/org/geoserver/inspire/wmts/InspireGridSetLoader.java
src/extension/inspire/src/main/resources/applicationContext.xml
src/extension/inspire/src/test/java/org/geoserver/inspire/wmts/InspireGridSetLoaderTest.java
src/gwc/src/main/java/org/geoserver/gwc/GWC.java

This pull request added a new method on GWC singleton to allow GeoServer extensions to register non editable grid sets.
https://osgeo-org.atlassian.net/browse/GEOS-7782

[GEOS-7782] Add INSPIRE grid set when INSPIRE extensions is loaded (backport 2.9.x)

---

src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetFeatureInfoIntegrationTest.java
src/wms/src/test/resources/org/geoserver/wms/wms_1_3/genericLines.properties
src/wms/src/test/resources/org/geoserver/wms/wms_1_3/genericLines.sld

https://osgeo-org.atlassian.net/browse/GEOS-7570
The actual fix for this is performed by this GeoTools pull request:
geotools/geotools#1329
This pull request only adds a new test case based on this issue.
Backport of pull request:
https://github.com/geoserver/geoserver/pull/1860

[GEOS-7570] Add test case for GetFeatureInfo with generic geometries (backport 2.9.x)

---

src/web/core/src/main/java/org/geoserver/web/data/layer/CoverageViewEditor.java
src/web/core/src/test/java/org/geoserver/web/data/layer/CoverageViewEditorTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7789
This pull request also adds a test case.

[GEOS-7789] Make output bands show bands index when creating a coverage view

---

src/web/core/src/main/java/org/geoserver/web/data/layer/CoverageViewEditor.java
src/web/core/src/test/java/org/geoserver/web/data/layer/CoverageViewEditorTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7789
This pull request also adds a test case.
Backport of pull request: https://github.com/geoserver/geoserver/pull/1878

[GEOS-7789] Make output bands show bands index when creating a coverage view (backport 2.9.x)

---

src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/LayerGroupTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7771
This particular solution causes a null value to be returned as "null" when encoded as JSON.
For example `{styles: {style: ["null", "null", "null", "null", "null"]}}`

[GEOS-7771] Fix JSON encoding for a list of nulls

---

src/main/src/main/java/org/geoserver/security/DisabledResourceFilter.java
src/wfs/src/test/java/org/geoserver/wfs/GetFeatureTest.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureJoinTest.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeaturePagingTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7792
This PR implements both the simple and ```getSecurityFilter``` changes proposed by @aaime. Note that the ```getSecurityFilter``` change does not fix the bug by itself. I would also like some feedback on the ```shouldApplyFilter``` logic; see the [Jira comment](https://osgeo-org.atlassian.net/browse/GEOS-7792?focusedCommentId=60278&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-60278) for details. This PR leaves the ```shouldApplyFilter``` logic as-is. I am happy to change it based on feedback.
This PR also fixes WFS 2.0 ```GetFeatureJoinTest``` and ```GetFeaturePagingTest```, which were running with disabled stores.

[GEOS-7792] WFS ignores disabling of stores (master)

---

doc/en/user/source/data/app-schema/joining.rst
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/AbstractAppSchemaTestSupport.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/FeatureChainingWfsTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NestedIdSupportTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/PolymorphismWfsTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SRSReprojectionTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SimpleAttributeFeatureChainWfsTest.java

Backport to GeoServer 2.9.x of unit tests and docs for GEOT-5526 (see #1847).
Note that build is expected to fail until geotools/geotools#1361 is merged.

[GEOT-5526] SQL Encoding of Filters on Nested Attributes

---

doc/en/developer/source/programming-guide/testing/index.rst

Over the course of writing test cases, I have found it usefull to compile a list of the actual contents of the default data dir initialized by GeoServerSystemTestSupport.
I feel like this list would probably be a usefull addition to the developer guide.

Document the GeoServerSystemTestSupport data dir

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleAdminPanel.java

For details see: https://osgeo-org.atlassian.net/browse/GEOS-7689

Prevent image being serialized, form uses wicketImage [GEOS-7689]

---

src/community/geogig/src/main/java/org/geogig/geoserver/rest/GeoServerRepositoryProvider.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/InitRequestHandler.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/RepositoryListResource.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/RepositoryResource.java
src/community/geogig/src/test/resources/org/geogig/geoserver/functional/PluginListRepositories.feature
src/community/release/ext-geogig.xml

Update the GeoGig plugin to use the new Response Representation framework in GeoGig that removes the coupling to XMLStreamWriter and Jettison bridging libraries.

Replace Jettison libraries with JSONP (JSR-353)

---

src/main/src/main/java/applicationContext.xml

Replacement for #1903 that is fixing the underlying problem, instead of the circumstance triggering it.
The real issue is that if by any accident Spring initializes EntityResolverProvider before having created GeoServer we end up in a circularity of this kind:
- EntityResolverProvider needs GeoServer (and the bean creation of EntityResolverProvider starts)
- GeoServer is initialized and post-processed by GeoServerLoader before EntityResolverProvider creation can finish, and the post-processing looks for all GeoServerInitializer
- ResourcePoolInitializer needs EntityResolverProvider, which is under construction, boom
The patch ensure that GeoServer is built before EntityResolverProvider bean creation is even attempted, allowing for a working startup instead. 
An alternative approach could …

Fix for (GEOS-7805) CSW Service does not work anymore due to EntityResolver bean circular reference

---

src/release/installer/win/GeoServerEXE.nsi

Since I had NSIS environment set up in windows figured I would try for this small improvement.

Allow windows installer to install jetty on port 80

---

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/events/JMSModifyEvent.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/events/configuration/JMSEventType.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/events/configuration/JMSServiceModifyEvent.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/events/configuration/JMSSettingsModifyEvent.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/configuration/JMSServiceHandler.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/configuration/JMSSettingsHandler.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/configuration/JMSSettingsHandlerSPI.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/server/JMSConfigurationListener.java
src/community/jms-cluster/jms-geoserver/src/main/resources/applicationContext.xml
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JMSServiceHandlerTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JMSWorkspaceHandlerTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsTestService.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsTestServiceLoader.java
src/community/jms-cluster/jms-geoserver/src/test/resources/TestContext.xml

Makes JMS plugin listen on all service events (add, modify and remove) and also makes the plugin aware of virtual services. This pull request also makes the JMS plugin aware of settings events.
Tests for the reported issues were added.
The following issues reports different problems for the same root cause:
- https://osgeo-org.atlassian.net/browse/GEOS-7755
- https://osgeo-org.atlassian.net/browse/GEOS-7269
- https://osgeo-org.atlassian.net/browse/GEOS-7268
- https://osgeo-org.atlassian.net/browse/GEOS-7758

[GEOS-7755] [GEOS-7269] [GEOS-7268][GEOS-7758] Makes JMS plugin listen on all services and settings events and be aware of virtual services

---

src/community/script/groovy/pom.xml
src/extension/vectortiles/pom.xml
src/pom.xml

See https://osgeo-org.atlassian.net/browse/GEOS-7840
This one will need to be backported to 2.10.x and 2.9.x

[GEOS-7840] Consistently use java-vector-tile:1.0.9

---

src/extension/importer/core/src/main/java/org/geoserver/importer/DataStoreFormat.java
src/extension/importer/core/src/main/java/org/geoserver/importer/ImportTransformFeatureCollection.java
src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java

This PR does two things;
a) splits the (quite long) loadIntoDataStore() method into two parts - setup and transferring features
b) provide two implementation for moving features one based on the low-level api (read-a-feature write-a-feature) and one based on the high-level api (FeatureCollection/featureStore.addFeatures).
For the non-datastore formats (GeoJSON, GML, KML), this PR will not affect functionality. However, for Datastore-backed data sources, this uses the FeatureCollection/featureStore.addFeatures() method.
The original feature transformation (cf copyFeaturesLowLevelAPI) has been re-implemented inside a FeatureCollection/FeatureIterator.
The FeatureIterator provides two pieces of functionality;
a) cancelability (cf CancelableFeatureIterator)
b) feature xformation (cf …

GEOS-7844: move importer to use high-level DS api

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/AbstractStylePage.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageNoLayersTest.java

Fix for https://osgeo-org.atlassian.net/browse/GEOS-7826
Added null check to the page constructor.
Added error messages when trying to navigate to other tabs when no layers are available.

[GEOS-7826] Add check for no layers when instantiating Style Editor page

---

src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
src/main/src/test/java/org/geoserver/catalog/impl/CascadeDeleteVisitorTest.java
src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/LayerGroupTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/LayerGroupWorkspaceTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/LayerGroupWorkspaceTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7858
Actual bugfix is in CatalogImpl/CatalogImplTest 
There are a bunch of additional test fixes to make other downstream test cases behave properly

[GEOS-7858] Verify layer group is not used before removing from catalog

---

src/pom.xml

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7877

[GEOS-7877] Upgrade imageio-ext version to 1.1.16

---

src/pom.xml

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7877

[GEOS-7877] Upgrade imageio-ext version to 1.1.16 (backport 2.10.x)

---

src/pom.xml

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7877

[GEOS-7877] Upgrade imageio-ext version to 1.1.16 (backport 2.9.x)

---

src/extension/wps/wps-core/src/main/java/org/geoserver/wps/GetCapabilities.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/GetCapabilitiesTest.java

Rather than 'java.lang.NullPointerException', the error message now contains a little bit more explanation.

Fix the NPE message when requesting the WPS GetCapabilities

---

src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
src/ows/src/test/java/org/geoserver/ows/DispatcherTest.java
src/ows/src/test/java/org/geoserver/ows/HelloWorld.java
src/ows/src/test/java/org/geoserver/ows/applicationContext.xml
src/ows/src/test/java/org/geoserver/test/CodeExpectingHttpServletResponse.java

Rather it uses setStatus and writes content like a normal response.
Using sendError causes the servlet container to include it’s own
content indicating the request is an error, which throws off the
desired response.

GEOS-7921: Updates dispatcher to not use sendError when non error code http status.

---

src/community/geogig/pom.xml

Changed the SNAPSHOT version for GeoGig plugin to 1.1
Signed-off-by: goudine <agoudine@boundlessgeo.com>

Update snapshot version

---

src/web/demo/src/main/java/org/geoserver/web/demo/SRSDescriptionPage.html
src/web/demo/src/main/java/org/geoserver/web/demo/SRSDescriptionPage.java

https://osgeo-org.atlassian.net/browse/GEOS-7909
Converted OL2 preview to OL3
Also made some improvements to the bounds calculation used by the preview.
Tested with EPSG:4326, EPSG:3857, EPSG:2000 (Anguilla 1957 / British West Indies Grid), and EPSG:3031 (Antarctic Polar Stereographic). All render fine and start at a sensible zoom.

[GEOS-7909] Upgrade SRS List demo to use OL3

---

src/extension/importer/core/src/main/java/org/geoserver/importer/EPSGCodeLookupCache.java

Fixed the import of SoftValueHashMap in GT (not in imageio-ext)

[GEOS-7907] Import of SoftValueHashMap fixed

---

src/community/ows-simulate/pom.xml
src/community/ows-simulate/src/main/java/org/geoserver/ows/SimulateCallback.java
src/community/ows-simulate/src/main/resources/applicationContext.xml
src/community/ows-simulate/src/test/java/org/geoserver/ows/SimulateCallbackTest.java
src/community/ows-simulate/src/test/java/org/geoserver/ows/SimulateIntegrationTest.java
src/community/pom.xml
src/community/release/ext-ows-simulate.xml
src/community/release/pom.xml

When active allows to specify a "simulate" option to an OGC request
causing it to return after parsing the request but before actually
running it. The response to such a request is a serializastion of
the resulting "request object", which provides info about how the
request was parsed and interpreted.

Adding ows-simulate community module.

---

src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
src/ows/src/test/java/org/geoserver/ows/DispatcherTest.java
src/ows/src/test/java/org/geoserver/ows/HelloWorld.java
src/ows/src/test/java/org/geoserver/ows/applicationContext.xml
src/ows/src/test/java/org/geoserver/test/CodeExpectingHttpServletResponse.java

Rather it uses setStatus and writes content like a normal response.
Using sendError causes the servlet container to include it’s own
content indicating the request is an error, which throws off the
desired response.

GEOS-7921: Updates dispatcher to not use sendError. (2.10 backport)

---

src/community/ysld/src/test/java/org/geoserver/ysld/YsldStyleGeneratorTest.java

Tests integration of the YsldHandler with the StyleGenerator framework. Improves test coverage for promotion to extension status (82%).

[GEOS-7939] Test YSLD Style Generator to improve coverage for YSLD promotion

---

doc/en/user/source/configuration/globalsettings.rst
src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
src/main/src/main/java/org/geoserver/config/impl/GeoServerInfoImpl.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/CapabilitiesModifyingTest.java

This is a tentative, and incomplete, pull request disabling data store check on startup when the capabilities document generation is configured to skip over invalid layers. There is a test failure in geogig that seems to be related to code not being up to date (I also had a app-schema one, but that seems to be only local, I probably need to update code there).

Do not check stores when capabilites generation is set in tolerant mode

---

src/restconfig/src/main/java/applicationContext.xml

https://osgeo-org.atlassian.net/browse/GEOS-7918

[GEOS-7918] Invalid scope attribute in gs-restconfig applicationContext.xml (master)

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/AbstractStylePage.java
src/web/wms/src/main/java/org/geoserver/wms/web/data/ExternalGraphicPanel.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java

When the AbstractStylePage is loaded with an existing style, it will now check if the StyleInfo object has a null LegendInfo. If so, it will insert a blank LegendInfo into the StyleInfo to act as the model for the ExternalGraphicPanel. This was already being done for new styles, but was missing for existing styles.
Added additional tests for discarding a legend on the StyleEditPage.
Also fixed another issue that was uncovered by this fix: Changed the “discard legend” functionality to fully reset user input — otherwise, supposedly discarded values could still fail to validate and prevent a save.

[GEOS-7944] Fix for null LegendInfo objects in StyleEditPage

---

LICENSE.txt
src/release/LICENSE.txt

The license adds a duplicate copy of GPLv2 (and an unnecessary copy of GPL v3), but I didn't alter the license at all.

Adding Java Service Wrapper license to LICENSE.txt

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleEditPage.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java
src/web/wms/src/test/resources/org/geoserver/wms/web/data/testMoveStyle.sld
src/web/wms/src/test/resources/org/geoserver/wms/web/data/testMoveStyleUpdated.sld

https://osgeo-org.atlassian.net/browse/GEOS-7930
Change the StyleEditPage submit function to first save the StyleInfo, then save the updated style body. When done in the opposite order, updates to the style body would be overwritten if the style was also moved.
Also added a test that isolates the bug by updating and moving a style at the same time.

[GEOS-7930] Prevent overwrite of updated styles when also changing workspace

---

src/main/pom.xml
src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/LayerGroupTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-7873
Alternative to https://github.com/geoserver/geoserver/pull/2072 that doesn't alter the rest API output, but instead uses reflection to hack around the jettison 1.0.1 bug.

[GEOS-7873] Workaround for JSON array serialization of nulls

---

src/main/src/main/java/org/geoserver/config/GeoServerPersister.java
src/platform/src/main/java/org/geoserver/platform/resource/FileSystemResourceStore.java
src/platform/src/main/java/org/geoserver/platform/resource/Resource.java

The other changes helped some in terms of build time on Travis (it's a bit shorter than usual, couple of minutes), so I prepared a patch mirroring the Resource.getContents() adding a Resource.setContents(byte[]). Let's see if this helps too.

[GEOS-7953] GSIP 155 - Core improvements for catalogs with many layers, follow up on the write side

---

src/gwc/src/main/java/org/geoserver/gwc/wmts/WMTSXStreamLoader.java
src/gwc/src/test/java/org/geoserver/gwc/wmts/WMTSXStreamLoaderTest.java

Removes the WMTS service blind enabling in the initialization and fix the test that was not invoking the initialization.
https://osgeo-org.atlassian.net/browse/GEOS-7926

[GEOS-7926] Fix WMTS blind re-enabling

---

doc/en/user/source/services/wms/reference.rst
doc/en/user/source/services/wms/vendor.rst
src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesResponse.java
src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/CapabilitiesTest.java

Backport of this pull request: https://github.com/geoserver/geoserver/pull/2080.
Permission to backport asked on the mailing list: http://osgeo-org.1560.x6.nabble.com/Add-a-WMS-vendor-FORMAT-parameter-to-force-the-return-of-WMS-1-1-1-capabilities-in-text-xml-td5305506.html

[GEOS-7962] Add a WMS FORMAT vendor parameter (backport 2.10.x)

---

doc/en/user/source/services/wms/reference.rst
doc/en/user/source/services/wms/vendor.rst
src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesResponse.java
src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/CapabilitiesTest.java

This pull request implements the support for the WMS ``format`` vendor parameter. WMS 1.1.1 capabilities document supported mime types were extend to include the ``text/xml`` mime type. Tests and documentation were also updated.
Associated issue: 
- https://osgeo-org.atlassian.net/browse/GEOS-7962
Mailing list discussion: 
- http://osgeo-org.1560.x6.nabble.com/Add-a-WMS-vendor-FORMAT-parameter-to-force-the-return-of-WMS-1-1-1-capabilities-in-text-xml-td5305506.html

[GEOS-7962] Add a WMS FORMAT vendor parameter

---

src/release/ext-gdal.xml

When the GDAL extension is installed the presence of the imageio-ext-gdalgeotiff.jar in the classpath can cause classpath loading problems: only classes in imageio-ext-tiff.jar should be loaded.
When this happen (the cp conflict is not predictable and the error may occurs depending on which layers are loaded in GS) geoserver fails at startup (see this stacktrace)
Since the imageio-ext-gdalgeotiff dependency is never used it can be removed explicitly from the gdal extension zip pkg and from the related geootols module's pom (see [GT related issue](https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-5636))

#[GEOS-7981] fixed imageio-ext-gdalgeotiff.jar classpath conflicts

---

src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryInfo.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/RepositoryResource.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/data/store/geogig/GeoGigDataStoreEditPanel.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/repository/RepositoriesListPanel.java
src/community/geogig/src/test/java/org/geogig/geoserver/config/RepositoryInfoTest.java

Use the `geoserver://<repo_name>` psuedo URI in places where we
do not want to expose GeoGig backend connection information, like
PostgreSQL passwords.

Mask the GeoGig repository location in UI and API responses

---

src/ows/src/main/java/org/geoserver/ows/Dispatcher.java

The OWS Dispatcher class contains a bunch of what are essentially utility methods.
I feel like these could be useful outside of Dispatcher (mainly for DispatcherCallbacks) and could therefore be made `public static`.
These methods all have no notable side effects.

Make applicable OWS Dispatcher utility methods accessible

---

src/gwc/src/main/java/org/geoserver/gwc/layer/DefaultTileLayerCatalog.java

This is a simple follow up for GSIP-155, reducing the time it takes to load the GWC config files

Parallelize loading GWC tile layer config files by using parallel streams

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/AbstractStylePage.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java

Fix for https://osgeo-org.atlassian.net/browse/GEOS-7991 -- Re-initialize LegendInfo when it is null after an "apply".

[GEOS-7991] Re-initialize null LegendInfo after Style Page “apply”

---

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogEventHandler.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogModifyEventHandlerTest.java

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7995
JMS plugin will not serialize properties of type catalog when propagating modify events. Catalogs are instance specific and most of is fields are transient, so no collateral effects are expected.
A test case for this was also added.

[GEOS-7995] Make JMS not serialize properties of type catalog

---

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogEventHandler.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogModifyEventHandlerTest.java

Backport of pull request: https://github.com/geoserver/geoserver/pull/2111
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7995
JMS plugin will not serialize properties of type catalog when propagating modify events. Catalogs are instance specific and most of is fields are transient, so no collateral effects are expected.
A test case for this was also added.

[GEOS-7995] Make JMS not serialize properties of type catalog (backport 2.10.x)

---

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogEventHandler.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogModifyEventHandlerTest.java

Backport of pull request: https://github.com/geoserver/geoserver/pull/2111
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7995
JMS plugin will not serialize properties of type catalog when propagating modify events. Catalogs are instance specific and most of is fields are transient, so no collateral effects are expected.
A test case for this was also added.

[GEOS-7995] Make JMS not serialize properties of type catalog (backport 2.9.x)

---

src/web/core/src/main/java/org/geoserver/web/admin/StatusPanel.java

When you start GeoServer with -Xmx higher than 1g (for e.g: 2g), the memory usage inside the "Server status" page displays the wrong number.
With -Xmx2g before my fix :
With -Xmx2g after my fix :

Fixed display info of memory usage inside server status page

---

doc/en/user/source/production/scripts/geoserver_deb

Made changes to Debian init.d file so the `$DAEMON` uses custom `$JAVA_HOME` specified in config variable file `/etc/default/$NAME`.

DAEMON to follow JAVA_HOME from config var file

---

src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/MultiDimDataStore.java
src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/MultiDimDataStoreFactory.java

A test case in the netcdf-out module uses AbstractDataStore. This PR modifies this to use ContentDataStore instead.

Convert deprecated AbstractDataStore usage to ContentDataStore

---

src/gwc/src/main/java/org/geoserver/gwc/wmts/WMTSXStreamLoader.java
src/gwc/src/test/java/org/geoserver/gwc/wmts/WMTSXStreamLoaderTest.java

Backport of pull request: https://github.com/geoserver/geoserver/pull/2053
Removes the WMTS service blind enabling in the initialization and fix the test that was not invoking the initialization.
https://osgeo-org.atlassian.net/browse/GEOS-7926

[GEOS-7926] Fix WMTS blind re-enabling (backport 2.10.x)

---

src/gwc/src/main/java/org/geoserver/gwc/wmts/WMTSXStreamLoader.java
src/gwc/src/test/java/org/geoserver/gwc/wmts/WMTSXStreamLoaderTest.java

Backport of pull request: https://github.com/geoserver/geoserver/pull/2053
Removes the WMTS service blind enabling in the initialization and fix the test that was not invoking the initialization.
https://osgeo-org.atlassian.net/browse/GEOS-7926

[GEOS-7926] Fix WMTS blind re-enabling (backport 2.9.x)

---

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/tasklet/CatalogBackupRestoreTasklet.java
src/gwc/src/main/java/org/geoserver/gwc/JDBCConfigurationStorage.java
src/gwc/src/main/java/org/geoserver/gwc/config/GeoserverXMLResourceProvider.java
src/gwc/src/test/java/org/geoserver/gwc/config/GWCExternalConfigTest.java

Mailing list discussion: http://osgeo-org.1560.x6.nabble.com/Add-back-the-possibility-to-externalize-GWC-configuration-using-GEOWEBCACHE-CACHE-DIR-td5309333.html
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8004
This [commit](https://github.com/geoserver/geoserver/commit/a72682bc5f86114dc56ba9d68f19b670da76cd99#diff-5b32e54953013fe49c4405ac132f9d3eR18) removed the possibility to externalize GWC configuration using Java property ``GEOWEBCACHE_CACHE_DIR``.
This pull request fix the issue above and adds a new test case. Code that assumed only the default location was also updated.
This changes were manually tested and everything seems to be working as expected. The ``back-restore`` module was also tested.
Since this restores a functionality that is already documented no …

[GEOS-8004] Adds back the possibility to externalize GWC configuration using GEOWEBCACHE_CACHE_DIR

---

src/wfs/src/main/java/org/geoserver/wfs/UpdateElementHandler.java
src/wfs/src/test/java/org/geoserver/wfs/v1_1/TransactionTest.java

When there's no properties given to update in the transaction there's nothing to do, so update should just return immediately.

GEOS-7883 Return empty transaction result when no properties are given

---

src/community/oseo/oseo-core/src/test/resources/postgis.sql

This PR adds to the postgis.sql script the DDL for the thumbs table of the opensearch db

added product_thumb table in opensearch db

---

src/community/jdbcconfig/pom.xml
src/pom.xml

Conflict between geogig and jdbcconfig depending on different versions of `compress-lzf.jar`

Update compress-lzf library version

---

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/tasklet/CatalogBackupRestoreTasklet.java
src/gwc/src/main/java/org/geoserver/gwc/JDBCConfigurationStorage.java
src/gwc/src/main/java/org/geoserver/gwc/config/GeoserverXMLResourceProvider.java
src/gwc/src/test/java/org/geoserver/gwc/config/GWCExternalConfigTest.java

Backport of this pull request: https://github.com/geoserver/geoserver/pull/2131
Mailing list discussion: http://osgeo-org.1560.x6.nabble.com/Add-back-the-possibility-to-externalize-GWC-configuration-using-GEOWEBCACHE-CACHE-DIR-td5309333.html
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8004
This [commit](https://github.com/geoserver/geoserver/commit/a72682bc5f86114dc56ba9d68f19b670da76cd99#diff-5b32e54953013fe49c4405ac132f9d3eR18) removed the possibility to externalize GWC configuration using Java property ``GEOWEBCACHE_CACHE_DIR``.
This pull request fix the issue above and adds a new test case. Code that assumed only the default location was also updated.
This changes were manually tested and everything seems to be working as expected. The ``back-restore`` module was …

[GEOS-8004] Adds back the possibility to externalize GWC configuration using GEOWEBCACHE_CACHE_DIR (backport 2.10.x)

---

src/community/geogig/src/main/java/org/geogig/geoserver/rest/GeoServerRepositoryProvider.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/GeogigDispatcher.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/ImportExistingRepo.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/ImportRepoCommandResource.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/InitCommandResource.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/GeoServerFunctionalTestContext.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/PluginWebAPICucumberHooks.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/RunWebAPIFunctionalTest.java
src/community/geogig/src/test/resources/features/webCommand/importExistingRepo.feature

This commit adds the functionality of importing existing PostGres and directory
backed GeoGig repositories into GeoServer via the web API.

Import Existing GeoGig repo via web API

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleEditPage.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java

This PR makes sure that the style file is saved before the style info is stored in the catalog, this way someone listen on the catalog modified event can have access to the correct style file. This PR cotnains also a test for this behavior.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8037
Mailing list discussion: http://osgeo-org.1560.x6.nabble.com/Style-modify-event-and-changed-resource-td5311789.html

[GEOS-8037] Save style file before saving the style info

---

src/community/spatialite/pom.xml
src/community/spatialite/src/test/java/org/geoserver/spatialite/RestTest.java
src/extension/h2/pom.xml
src/extension/h2/src/test/java/org/geoserver/h2/RestTest.java
src/restconfig/src/main/java/org/geoserver/catalog/rest/DataStoreFileResource.java

This PR fix the REST handling of H2 and SpatiaLite data stores and add tests cases for both. Both cases requires special handling that cannot be generalized \ abstracted in an elegant way.
SpatiLite tests will only run if the appropriated native libraries are available otherwise they will be skipped and a warning will be logged.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-5869

[GEOS-5869] Fix REST handling of H2 and SpatiaLite datastores

---

src/community/spatialite/pom.xml
src/community/spatialite/src/test/java/org/geoserver/spatialite/RestTest.java
src/extension/h2/pom.xml
src/extension/h2/src/test/java/org/geoserver/h2/RestTest.java
src/restconfig/src/main/java/org/geoserver/catalog/rest/DataStoreFileResource.java

Backport of this PR: https://github.com/geoserver/geoserver/pull/2153
This PR fix the REST handling of H2 and SpatiaLite data stores and add tests cases for both. Both cases requires special handling that cannot be generalized \ abstracted in an elegant way.
SpatiLite tests will only run if the appropriated native libraries are available otherwise they will be skipped and a warning will be logged.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-5869

[GEOS-5869] Fix REST handling of H2 and SpatiaLite datastores (backport 2.11.x)

---

src/community/spatialite/pom.xml
src/community/spatialite/src/test/java/org/geoserver/spatialite/RestTest.java
src/extension/h2/pom.xml
src/extension/h2/src/test/java/org/geoserver/h2/RestTest.java
src/restconfig/src/main/java/org/geoserver/catalog/rest/DataStoreFileResource.java

Backport of this PR: #2153
This PR fix the REST handling of H2 and SpatiaLite data stores and add tests cases for both. Both cases requires special handling that cannot be generalized \ abstracted in an elegant way.
SpatiLite tests will only run if the appropriated native libraries are available otherwise they will be skipped and a warning will be logged.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-5869

[GEOS-5869] Fix REST handling of H2 and SpatiaLite datastores (backport 2.10.x)

---

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/JMSActiveMQFactory.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/events/configuration/JMSServiceModifyEvent.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/configuration/JMSServiceHandler.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/server/JMSConfigurationListener.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/JmsServicesTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsServiceHandlerTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsTestServiceInfo.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsTestServiceInfoImpl.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsTestServiceLoader.java

Backport of PR: https://github.com/geoserver/geoserver/pull/2159
This PR amend the services configuration handling in JMS community module. Integration tests for the found issues were added and existing tests improved (removing some annoying exceptions \ logs).
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8026

[GEOS-8026] Fix services configuration events handling in JMS community module (backport 2.11.x)

---

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/JMSActiveMQFactory.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/events/JMSModifyEvent.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/events/configuration/JMSServiceModifyEvent.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/configuration/JMSServiceHandler.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/server/JMSConfigurationListener.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/JmsServicesTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsServiceHandlerTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsTestServiceInfo.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsTestServiceInfoImpl.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsTestServiceLoader.java

Backport of PR: #2159
This PR amend the services configuration handling in JMS community module. Integration tests for the found issues were added and existing tests improved (removing some annoying exceptions \ logs).
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8026

[GEOS-8026] Fix services configuration events handling in JMS community module (backport 2.10.x)

---

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogModifyEventHandler.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/server/JMSCatalogListener.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/server/events/StyleModifyEvent.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/JmsStylesTest.java
src/community/jms-cluster/jms-geoserver/src/test/resources/test_style_modified.sld

This PR makes JMS plugin handle correctly styles workspaces changes, style names changes were the content of the style is also changed and were the workspace is also changed. To avoid any synchronization issues when a style is modified the style file is propagated in the same event. 
Tests cases for this situations were added.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8039

[GEOS-8039] Fix JMS plugin styles workspaces change handling

---

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogModifyEventHandler.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/server/JMSCatalogListener.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/server/events/StyleModifyEvent.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/JmsStylesTest.java
src/community/jms-cluster/jms-geoserver/src/test/resources/test_style_modified.sld

Backport of this PR: https://github.com/geoserver/geoserver/pull/2164
This PR makes JMS plugin handle correctly styles workspaces changes, style names changes were the content of the style is also changed and were the workspace is also changed. To avoid any synchronization issues when a style is modified the style file is propagated in the same event.
Tests cases for this situations were added.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8039

[GEOS-8039] Fix JMS plugin styles workspaces change handling (backport 2.11.x)

---

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogModifyEventHandler.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/server/JMSCatalogListener.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/server/events/StyleModifyEvent.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/JmsStylesTest.java
src/community/jms-cluster/jms-geoserver/src/test/resources/test_style_modified.sld

Backport of this PR: https://github.com/geoserver/geoserver/pull/2164
This PR makes JMS plugin handle correctly styles workspaces changes, style names changes were the content of the style is also changed and were the workspace is also changed. To avoid any synchronization issues when a style is modified the style file is propagated in the same event.
Tests cases for this situations were added.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8039

[GEOS-8039] Fix JMS plugin styles workspaces change handling (backport 2.10.x)

---

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/tasklet/CatalogBackupRestoreTasklet.java
src/gwc/src/main/java/org/geoserver/gwc/JDBCConfigurationStorage.java
src/gwc/src/main/java/org/geoserver/gwc/config/GeoserverXMLResourceProvider.java
src/gwc/src/test/java/org/geoserver/gwc/config/GWCExternalConfigTest.java

Backport of this pull request: https://github.com/geoserver/geoserver/pull/2131
Mailing list discussion: http://osgeo-org.1560.x6.nabble.com/Add-back-the-possibility-to-externalize-GWC-configuration-using-GEOWEBCACHE-CACHE-DIR-td5309333.html
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8004
This [commit](https://github.com/geoserver/geoserver/commit/a72682bc5f86114dc56ba9d68f19b670da76cd99#diff-5b32e54953013fe49c4405ac132f9d3eR18) removed the possibility to externalize GWC configuration using Java property ``GEOWEBCACHE_CACHE_DIR``.
This pull request fix the issue above and adds a new test case. Code that assumed only the default location was also updated.
This changes were manually tested and everything seems to be working as expected. The ``back-restore`` module was …

[GEOS-8004] Adds back the possibility to externalize GWC configuration using GEOWEBCACHE_CACHE_DIR (backport 2.9.x)

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleEditPage.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java

Backport of pull request: https://github.com/geoserver/geoserver/pull/2162
This PR makes sure that the style file is saved before the style info is stored in the catalog, this way someone listen on the catalog modified event can have access to the correct style file. This PR cotnains also a test for this behavior.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8037
Mailing list discussion: http://osgeo-org.1560.x6.nabble.com/Style-modify-event-and-changed-resource-td5311789.html

[GEOS-8037] Save style file before savign the style info (backport 2.10.x)

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleEditPage.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java

Backport of pull request: https://github.com/geoserver/geoserver/pull/2162
This PR makes sure that the style file is saved before the style info is stored in the catalog, this way someone listen on the catalog modified event can have access to the correct style file. This PR cotnains also a test for this behavior.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8037
Mailing list discussion: http://osgeo-org.1560.x6.nabble.com/Style-modify-event-and-changed-resource-td5311789.html

[GEOS-8037] Save style file before savign the style info (backport 2.11.x)

---

src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
src/gwc/src/test/java/org/geoserver/gwc/layer/GeoServerTileLayerTest.java

Stop using deprecated ``TileLayer.LegendInfo`` class.
GWC associated PR: https://github.com/GeoWebCache/geowebcache/pull/502

Make tile layer use new legend info structure

---

src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java

This issue fix the NPE exception and adds an integration test where a capabilities document that contains a layer group is invoked (yes is a simple test that is important but didn't existed).
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8073

[GEOS-8073] Performing a WMTS GetCapabilities request with layer groups provokes a NPE

---

src/extension/app-schema/app-schema-oracle-test/pom.xml
src/extension/app-schema/app-schema-postgis-test/pom.xml
src/extension/app-schema/app-schema-test/pom.xml
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/FeatureChainingWfsTest.java
src/extension/app-schema/app-schema-test/src/test/resources/test-data/FirstParentFeature.json
src/extension/app-schema/app-schema-test/src/test/resources/test-data/MappedFeature.json
src/extension/app-schema/app-schema-test/src/test/resources/test-data/MultipleCollections.json
src/extension/app-schema/app-schema-test/src/test/resources/test-data/Observation.json
src/extension/app-schema/app-schema-test/src/test/resources/test-data/ParentFeature.json
src/wfs/src/main/java/org/geoserver/wfs/json/ComplexGeoJsonWriter.java
src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java

Adds a GeoJSON encoder for complex features. The workflow is similar to the GML one, if the response result only contain simple features the actual simple features GeoJSON encoder is used otherwise the complex features GeoJSON encoder will be used.
Tests for the complex GeoJSON encoder were added in the app-schema module since this is the only place were complex features can actually be produced.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8068

[GEOS-8068] Add GeoJson encoder for complex features

---

src/community/pom.xml

The LocationTech builds for GeoGig seem to be stable again.

Re-enable GeoGig plugin in communityRelease module

---

src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesIntegrationTest.java

Makes WMS 1.3.0 capabilities transform use layer groups to compute the global bounding box. This pull request also adds a test case.
Makes WMS capabilities also filter layer groups by namespaces like layers a test case for this is also added.
Associated issues: 
- https://osgeo-org.atlassian.net/browse/GEOS-8072
- https://osgeo-org.atlassian.net/browse/GEOS-5176

[GEOS-8072] [GEOS-5176] WMS 1.3.0 capabilities global bounding box computation doesn't use layer groups

---

src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesIntegrationTest.java

Backport of this pull requests: https://github.com/geoserver/geoserver/pull/2203
Makes WMS 1.3.0 capabilities transform use layer groups to compute the global bounding box. This pull request also adds a test case.
Makes WMS capabilities also filter layer groups by namespaces like layers a test case for this is also added.
- https://osgeo-org.atlassian.net/browse/GEOS-8072
- https://osgeo-org.atlassian.net/browse/GEOS-5176

[GEOS-8072] [GEOS-5176] WMS 1.3.0 capabilities global bounding box computation doesn't use layer groups (backport 2.11.x)

---

src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesIntegrationTest.java

Backport of this pull requests: https://github.com/geoserver/geoserver/pull/2203
Makes WMS 1.3.0 capabilities transform use layer groups to compute the global bounding box. This pull request also adds a test case.
Makes WMS capabilities also filter layer groups by namespaces like layers a test case for this is also added.
- https://osgeo-org.atlassian.net/browse/GEOS-8072
- https://osgeo-org.atlassian.net/browse/GEOS-5176

[GEOS-8072] [GEOS-5176] WMS 1.3.0 capabilities global bounding box computation doesn't use layer groups (backport 2.10.x)

---

src/community/pom.xml
src/community/release/pom.xml

Now that #2216 is merged, there are some failing community modules.
This PR disables these modules, until such time that they can be updated.

REST API refresh - Disable failing community modules

---

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/catalog/JDBCCatalogFacade.java
src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/ConfigDatabaseTest.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/JMSCatalogPostModifyEventHandler.java
src/main/src/main/java/org/geoserver/catalog/Catalog.java
src/main/src/main/java/org/geoserver/catalog/event/CatalogPostModifyEvent.java
src/main/src/main/java/org/geoserver/catalog/event/impl/CatalogPostModifyEventImpl.java
src/main/src/main/java/org/geoserver/catalog/impl/AbstractCatalogDecorator.java
src/main/src/main/java/org/geoserver/catalog/impl/AbstractCatalogFacade.java
src/main/src/main/java/org/geoserver/catalog/impl/AbstractFilteredCatalog.java
src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
src/main/src/main/java/org/geoserver/catalog/impl/DefaultCatalogFacade.java
src/main/src/main/java/org/geoserver/security/SecureCatalogImpl.java
src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java
src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesLegendURLTest.java

GSIP Here: https://github.com/geoserver/geoserver/wiki/GSIP-157
API Changes:
* Public methods `getPropertyNames`,`getOldValues`,`getNewValues` added to **CatalogPostModifyEvent** interface.
* Public methods `getPropertyNames`, `setPropertyNames`, `getNewValues`, `setNewValues`, `getOldValues`, `setOldValues` added to **CatalogPostModifyEventImpl**.
* The arguments `List<String> propertyNames`, `List oldValues`, `List newValues` have been added to the package private method `firePostModified` of **AbstractCatalogDecorator**, **AbstractFilteredCatalog**, **CatalogImpl**, and **SecureCatalogImpl**, and to the protected methods `beforeSaved` and `afterSaved` of **AbstractCatalogFacade**.
All invocations of above methods and classes have been updated accordingly.
~Given that all the changes …

GSIP-157 / GEOS-7987 - Track modified properties in CatalogPostModifyEvent

---

src/community/hz-cluster/pom.xml
src/extension/monitor/core/pom.xml
src/pom.xml
src/restconfig/pom.xml

This PR also harmonises hz-cluster hamcrest versions and places them under dependency management. Backports of this latter change to 2.11.x and 2.10.x in https://github.com/geoserver/geoserver/pull/2239 and https://github.com/geoserver/geoserver/pull/2240 respectively.

Restrict hamcrest-library to test scope and harmonise versions (master)

---

src/community/hz-cluster/pom.xml
src/pom.xml

Backport of the hz-cluster part of https://github.com/geoserver/geoserver/pull/2238 .

Use dependency management for hz-cluster hamcrest versions (2.11.x)

---

src/community/hz-cluster/pom.xml
src/pom.xml

Backport of the hz-cluster part of https://github.com/geoserver/geoserver/pull/2238 .

Use dependency management for hz-cluster hamcrest versions (2.10.x)

---

src/platform/pom.xml
src/pom.xml

I forgot to remove these deps that are no longer needed after the refactoring to `FileSystemResourceStoreTest`.

[GEOS-7946] Remove leftover PowerMock dependencies from POM

---

src/restconfig/src/test/java/org/geoserver/rest/resources/ResourceControllerTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8027

[GEOS-8027] JUnit ResourceTest.testSpecialCharacterNames fails on Windows

---

src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesIntegrationTest.java

Backport of this pull request: https://github.com/geoserver/geoserver/pull/2244
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8088

[GEOS-8088] WMS 1.3.0 GlobalBoundingBoxForLayerGroups test is locale dependent (2.10.x)

---

src/platform/pom.xml
src/platform/src/main/java/org/geoserver/platform/resource/FileSystemResourceStore.java
src/platform/src/main/java/org/geoserver/platform/resource/Files.java
src/platform/src/test/java/org/geoserver/platform/resource/FileSystemResourceStoreTest.java
src/pom.xml

Backport of #2202 #2217 #2243 , after squashing.

[GEOS-7946] Using java.nio.file.Files.move() with ATOMIC_MOVE option to avoid case sensitivity issues

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/ExternalGraphicPanel.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleNewPageTest.java

Pull request with bug fix and unit test.  Can be backported to 2.10.x and 2.11.x.

[GEOS-8025] Fixed missing slash in external legend graphic URLs if the proxy base URL does not end in a slash.

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleAdminPanel.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleNewPageTest.java

Pull request with bug fix and unit test.  Can be backported to 2.10.x and 2.11.x.

[GEOS-8024] Fixed the legend preview failing on non-SLD styles.

---

src/main/src/main/java/org/geoserver/ows/LocalWorkspaceCatalogFilter.java
src/main/src/test/java/org/geoserver/ows/LocalWorkspaceSecureCatalogTest.java
src/platform/src/main/java/org/geoserver/platform/util/GeoServerPropertyFactoryBean.java
src/platform/src/test/java/org/geoserver/platform/util/GeoServerPropertyFactoryBeanTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8091
Revised version of abandoned PR #1362
Still uses `GEOSERVER_GLOBAL_LAYER_GROUP_INHERIT` as I can't think of a better term for this than inherit even though it's admittedly not entirely intuitive.

Property to control global layer group visibility in virtual services, GEOS-8091

---

doc/en/user/source/production/config.rst
src/main/src/main/java/org/geoserver/filters/XFrameOptionsFilter.java
src/main/src/test/java/org/geoserver/filters/XFrameOptionsFilterTest.java
src/web/app/src/main/webapp/WEB-INF/web.xml

A backport of 
https://github.com/geoserver/geoserver/pull/2225
with the minor caveat that instead of defaulting to SAMEORIGIN, I have turned the header OFF by default, to retain back-compat and not break existing builds.

Allow X-Frame-Options header to be set (2.10.x)

---

src/wms/src/main/java/org/geoserver/wms/WMSRequests.java
src/wms/src/test/java/org/geoserver/wms/WMSRequestsTest.java

Pull request with bug fix and unit test.  Can be backported to 2.10.x and 2.11.x.

[GEOS-8077] Fixed custom dimension values being dropped from GetMap URLs in the response KML document.

---

src/main/src/main/resources/org/geoserver/catalog/template_raster.sld
src/wms/src/test/java/org/geoserver/wms/WMSTestSupport.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetMapIntegrationTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8101
Best place I could fit the test case is gs-wms, as that is the only straightforward way I can find to actually render a style.

[GEOS-8101] Remove FeatureTypeName from raster_template.sld

---

src/main/src/main/java/org/geoserver/config/GeoServerDataDirectory.java
src/main/src/test/java/org/geoserver/config/GeoServerDataDirectoryTest.java
src/main/src/test/resources/org/geoserver/config/external_with_params_and_fragment.sld

This PR adds support for preservation of external graphic URL fragments during the load of a parsedStyle.
When GeoServerDataDirectory loads a parsedStyle, it locates external graphics (while preserving Cql templates) using only the URL base path, ignoring query parameters and URL #fragments. It then attempts to preserve the original URL by re-adding query parameters, but fails to re-add the fragment.
Supporting URL fragments would be generally useful to designate subordinate resources, e.g., an individual icon inside a sprite sheet. This pattern has already been established for [bulk WKT shapes](http://docs.geoserver.org/stable/en/user/styling/sld/extensions/pointsymbols.html#bulk-wkt-shapes), for which you can write: `<OnlineResource xlink:type="simple" …

[GEOS-8050] Preserve external graphic URL #fragments during GeoServerDataDirectory.parsedStyle(..)

---

src/community/pom.xml

Adds JMS plugin back to community release profile since the REST API is now aligned with the new API.

Add back JMS plugin to community release profile

---

src/main/src/main/java/org/geoserver/ows/OWSHandlerMapping.java
src/main/src/test/java/org/geoserver/ows/OWSHandlerMappingTest.java
src/wfs/src/test/java/org/geoserver/wfs/GetFeatureTest.java

New pull request with bug fix and unit tests that fixes conflicts caused by:
https://github.com/geoserver/geoserver/commit/c2f9c8302d917d643b4c51ee7d3dcaddf23cc9ed
This pull request can only be backported to 2.10.x and 2.11.x if that commit is also backported.

[GEOS-8023] Fixed Virtual Service layer name lookup not using workspace qualified layer names.

---

src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetFeatureInfoIntegrationTest.java

Pull request with bug fix and unit test. Can be backported to 2.10.x and 2.11.x.
Updated the removal of non-queryable layers in a WMS GetFeatureInfo request to remove their corresponding styles and filters.

[GEOS-8092] Fixed GetFeatureInfo errors for requests with both queryable and non-queryable layers

---

src/ows/src/main/java/org/geoserver/ows/util/KvpUtils.java
src/wfs/src/main/java/applicationContext.xml
src/wfs/src/test/java/org/geoserver/wfs/GetFeatureTest.java
src/wms/src/main/java/applicationContext.xml

Fixes support for null service / version / request in KvpUtils.purgeParsers and KvpUtils.findParser (according to the javadoc, this was already supported, but it appears the implementation was bugged).
KvpUtils.purgeParsers will now no longer purge parsers based on service / version / request if the applicable parameter is null in the original Kvp map.
KvpUtils.findParser now properly handles cases where both the kvp map and kvp parser have a null service / version / parser.
The beans "wfsFormatOptionsKvpParser" and "wmsFormatOptionsKvpParser" are functionally identical and have been renamed to "formatOptionsKvpParser" - in the case that both WFS and WMS are enabled, one will override the other. This prevents us throwing an IllegalStateException due to multiple identical KvpParsers (this …

[GEOS-8117] Improve support for null service/version/request in KvpUtils

---

src/main/src/main/java/org/geoserver/ows/StylePublisher.java
src/main/src/test/java/org/geoserver/ows/StylePublisherTest.java

External access to resources in subdirectories of the styles folder was broken in GeoServer 2.9.2 and 2.10.0 by the fix for https://osgeo-org.atlassian.net/browse/GEOS-7635.  The ability to access resources in styles subdirectories goes back to at least GeoServer 1.7.x.
This pull request removes the restriction of the number of tokens in the request path and that the first subdirectory must be a valid workspace.

[GEOS-8040] Fixed accessing resources in subdirectories of the styles folder.

---

src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java

[[GEOS-8122] Intermittent failure of FileUtils.deleteDirectory in SystemTestData.tearDown](https://osgeo-org.atlassian.net/browse/GEOS-8122)
[[GEOS-8123] GWC caches stale response encoders](https://osgeo-org.atlassian.net/browse/GEOS-8123)

[GEOS-8122][GEOS-8123] Fixes for FileUtils.deleteDirectory test failures

---

src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/WCSNetCDFMosaicTest.java

Tests now work with NetCDF-3 as well, almost certainly a benefit of the segfault fix included in https://github.com/geoserver/geoserver/pull/2281 . Where the NetCDF-C 4.4 native implementation made a best-effort write and the NetCDF-C 4.1 native implementation segfaulted, the NetCDF-3 Java implementation threw an exception. Now that the logic error in `NetCDFOutputManager.writeDataValues` has been removed, both NetCDF-3 and NetCDF-4 work.

[GEOS-8099] Expand test coverage to include NetCDF-3

---

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/listener/BackupRestoreJobExecutionListener.java
src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/listener/GenericListenersExecutor.java
src/community/backup-restore/core/src/main/resources/applicationContext.xml
src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java
src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/GenericListener.java
src/community/backup-restore/core/src/test/resources/applicationContext.xml

Backport of this pull request: https://github.com/geoserver/geoserver/pull/2314
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8124
Adds an extension point that will execute generic listeners.

[GEOS-8124] Add extension point in backup / restore module for generic resources handler (backport 2.10.x)

---

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/listener/BackupRestoreJobExecutionListener.java
src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/listener/GenericListenersExecutor.java
src/community/backup-restore/core/src/main/resources/applicationContext.xml
src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java
src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/GenericListener.java
src/community/backup-restore/core/src/test/resources/applicationContext.xml

Backport of this pull request: https://github.com/geoserver/geoserver/pull/2314
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8124
Adds an extension point that will execute generic listeners.

[GEOS-8124] Add extension point in backup / restore module for generic resources handler (backport 2.11.x)

---

src/community/mbstyle/pom.xml
src/community/mbstyle/src/main/java/org/geoserver/community/mbstyle/MBStyleHandler.java
src/community/mbstyle/src/test/java/org/geoserver/rest/catalog/MBStyleControllerTest.java
src/community/mbstyle/src/test/resources/org/geoserver/rest/catalog/teststyle.json

Change MBStyleHandler.FORMAT to “mbstyle” to avoid conflict with “json” extension in the REST API.
Add MBStyleController test, containing tests for mbstyle using the REST API endpoints.

MBStyle - Change format to “mbstyle”; Add REST tests in MBStyleControllerTest

---

src/gwc/src/main/java/org/geoserver/gwc/ConfigurableQuotaStore.java
src/gwc/src/main/java/org/geoserver/gwc/DummyQuotaStore.java
src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/gwc/src/main/resources/geowebcache-diskquota-context.xml
src/gwc/src/main/resources/geowebcache-rest-context.xml
src/gwc/src/test/java/org/geoserver/gwc/GWCTest.java

Depends on: https://github.com/GeoWebCache/geowebcache/pull/505
Allows the GWC transaction listener to truncate all parameters including non-enumerable ones (such as regexps) when it detects a change.  Also corrects for API changes in GWC.

API Changes in GWC and cross parameter autotruncation, GEOS-8074

---

src/community/mbstyle/src/test/java/org/geoserver/community/mbstyle/web/MBStyleHandlerTest.java
src/restconfig/src/main/java/org/geoserver/catalog/rest/StyleFinder.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/StyleTest.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/TestStyleHandlerExtensionConflict.java
src/restconfig/src/test/resources/testStyleHandlerExtensionConflict.xml

Updates StyleFinder to only create MediaType mappings for StyleHandler extensions IF the extension is not already being used. This will prevent styles that use general extensions (e.g., “style.json”) from interfering with the existing Restlet content negotiation (which allows .json to be used as a shortcut for an “application/json” accept header).
This effectively preserves the current behavior of the REST API for styles: using *.json will still always map to "application/json" and thus return the style info object in json format. If a user specifically wants the style definition body from a StyleHandler with a conflicting extension, they must use the StyleHandler's mime type (e.g., "application/vnd.geoserver.mbstyle+json").
Issue: https://osgeo-org.atlassian.net/browse/GEOS-8138

[GEOS-8138] Prevent StyleFinder from overwriting existing MediaType mappings

---

src/extension/security/cas/src/main/java/org/geoserver/security/cas/CasAuthenticationHelper.java
src/extension/security/cas/src/main/java/org/geoserver/security/cas/GeoServerCasAuthenticationFilter.java

We use Geoserver in a docker container, behind HAProxy for https management.
Problem : when no port is specified, service.toExternalForm() returns a service uri starting with https, but with :80 as port.
Of course, this breaks cas checks and redirection.
This PR simply remove :80 from generated uri .

Remove port 80 in cas URL

---

src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetFeatureInfoIntegrationTest.java

Backport GEOS-8092 fix to 2.11.x.

[GEOS-8092] 2.11.x Updated the removal of non-queryable layers in a WMS GetFeatureInfo request to remove their corresponding styles and filters.

---

src/community/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/RulesBuilder.java
src/community/sldService/src/test/java/org/geoserver/sldservice/utils/classifier/ClassifierTestSupport.java

Potential fix for https://osgeo-org.atlassian.net/browse/GEOS-7501
Use parseDouble instead of convert function to create renderable sld rules, and only if 'normalize' boolean is true.
The 'convert' function creates SLD rules that are not renderable (exception included at bottom):
```
<PropertyIsGreaterThanOrEqualTo>
<Function name="convert">
<PropertyName>value</PropertyName>
<Literal>java.lang.Double</Literal>
</Function>
<Literal>220.0</Literal>
</PropertyIsGreaterThanOrEqualTo>
```
Switching to 'parseDouble' produces renderable SLD:
```
<PropertyIsGreaterThanOrEqualTo>
<Function name="parseDouble">
<PropertyName>value</PropertyName>
</Function>
<Literal>220.0</Literal>
</PropertyIsGreaterThanOrEqualTo>
```
The exception caused by the convert function is:
```
Caused by: …
```

Use parseDouble instead of convert function in sldService community module

---

src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/ProcessParameterIO.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ppio/ProcessParameterIOTest.java

Fix with unit test for:
https://osgeo-org.atlassian.net/browse/GEOS-8046
This bug only causes annoying but harmless warning messages in the logs if the environment does not contain any PPIOFactory implementations.  I've found two, one in gs-gdal-wps and another in gs-ogr-wps, but I don't use either plugin.

[GEOS-8046] Fixed ProcessParameterIO performing extension lookups with a null ApplicationContext.

---

src/restconfig/src/main/java/org/geoserver/rest/catalog/AboutStatusController.java
src/restconfig/src/test/java/org/geoserver/rest/catalog/AboutControllerTest.java

A fix for [GEOS-8151](https://osgeo-org.atlassian.net/browse/GEOS-8151) to prevent users with escape chars in their environment variables breaking the tests.

GEOS-8151 - escape escape chars in XML

---

src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java
src/restconfig/src/test/java/org/geoserver/rest/catalog/StyleControllerTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-7959
This prevents the global default styles (point, line, polygon, raster, generic) from being renamed, assigned to a workspace, or deleted. This change is implemented at the CatalogImpl level.
Several changes have already been made to the UI to support this; those changes will remain as they provide useful behaviour (displaying dialogs and error messages)
This change will automatically affect the REST API. REST tests have been added as a separate commit to make any future backporting easier (given the resent REST rewrite).
Since this is a change to a core catalog class, care should be taken when deciding whether or not to backport. I would be happiest waiting a month on master before backporting, even though this is technically a bugfix.

[GEOS-7959] Disallow changing default styles

---

src/extension/css/src/test/java/org/geoserver/rest/catalog/CssStyleControllerTest.java
src/restconfig/src/main/java/org/geoserver/rest/catalog/StyleController.java
src/restconfig/src/test/java/org/geoserver/rest/catalog/StyleControllerTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8080
This version of the fix is for the new (>= 2.12) REST API. See also https://github.com/geoserver/geoserver/pull/2364

[GEOS-8080] Style in default workspace no longer overrides global style in rest GET

---

doc/en/user/source/data/raster/imagemosaic/configuration.rst
doc/en/user/source/data/raster/imagemosaic/tutorial.rst
src/main/src/main/java/org/geoserver/catalog/CatalogRepository.java
src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java

This pull request passes a Repository reference to readers, allowing them to refer to GeoServer datastore/dataaccess.
Working on it I noticed code duplication and oddities in the way readers are created and cached in the resource pool, cleaning it up and ended with one significant change to ResourcePool (one public method removed), but eliminating in the process the need to have two separate coverage reader caches and making sure readers get the hints they need no matter what the context is. 
ResourcePool is not meant to be used by "client" code, and its actual usage is limited to catalog classes and configuration related bits, such as REST config and Web UI, so I'm not too much concerned about the removal of that one public method to get the non hinted coverage cache reference (nothing …

[GEOS-8166] Allow image mosaic to refer a GeoServer configured store

---

src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java

[GEOS-7873] Use Logger.log for errors, not e.printStackTrace

---

src/main/src/main/java/org/geoserver/feature/RetypingFeatureCollection.java
src/main/src/test/java/org/geoserver/feature/RetypingFeatureCollectionTest.java

Fix for [GEOS-8176](https://osgeo-org.atlassian.net/browse/GEOS-8176) which forces the subCollections returned by the RetypeingFeatureCollection to be retyped.

[GEOS-8176] RetypingFeatureCollection doesn't retype subCollections

---

doc/en/user/source/production/container.rst
doc/en/user/source/styling/mbstyle/index.rst
doc/en/user/source/styling/mbstyle/reference/spec.rst
doc/en/user/source/styling/mbstyle/source.rst

Added a basic walkthrough of how to publish vector tiles for use with MapBox Style clients to MBStyle docs.
All `mapbox://` examples in the spec have been replaced with GeoServer examples. Places where the syntax is a actually described have remained unchanged.

Mbstyle - Source URL syntax & walkthrough

---

src/web/core/src/main/java/org/geoserver/web/wicket/GeoServerTablePanel.java
src/web/core/src/test/java/org/geoserver/web/wicket/GeoServerTablePanelTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-7893
When updateMatch is called, dataView has not yet been updated with the filtered results (dataProvider has). This fix makes update rely more upon the dataProvider info for computing values.

[GEOS-7893] GeoServerTabelPanel shows the correct number of results

---

src/pom.xml

We are on 1.4.7, see the changelog to 1.4.8, 1.4.9 and 1.4.10 for good reasons to upgrade:
http://x-stream.github.io/changes.html

Upgrade XStream to the latest version

---

src/community/geogig/src/main/java/org/geogig/geoserver/config/ConfigStore.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryCache.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryInfo.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryManager.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/GeoServerRepositoryProvider.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/ImportRepoCommandResource.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/InitCommandResource.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/data/store/geogig/BranchSelectionPanel.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/repository/RepositoryEditPanel.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/repository/RepositoryImportPanel.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/repository/RepositoryInfoDetachableModel.java
src/community/geogig/src/test/java/org/geogig/geoserver/HeapResourceStore.java
src/community/geogig/src/test/java/org/geogig/geoserver/config/ConfigStoreTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/config/RepositoryManagerConfigStoreIntegrationTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/config/RepositoryManagerTest.java

Geogig plugin's ConfigStore saves serialized RepositoryInfo instances
to GeoServers ResourceStore. Initially developer against the
default file based ResourceStore, it assumed it could freely
cache the RepositoryInfo instances.
On a clustered environemnt, modifications might occur on different
cluster nodes. This patch makes it so ResourceStore events are
properly handled for create/changed/deleted notifications by keeping
ConfigStore (in charge of storing the serialized RepositoryInfo instances)
and RepositoryManager (in charge of actual geogig Repository instances)
in synch, even when events come from different servers.

Make sure geogig's ConfigStore works on a clustered environment

---

src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/PipelineBuilder.java
src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/VectorTileMapOutputFormat.java
src/extension/vectortiles/src/main/java/org/geotools/renderer/lite/VectorMapRenderUtils.java
src/extension/vectortiles/src/test/java/org/geoserver/wms/vector/VectorTileMapOutputFormatTest.java

Mimics the behaviour of StreamingRenderer by using MetaTileBufferEstimator to estimate the size of the buffer from the style if it is not provided by the `buffer` parameter.
Addresses one of the points of GEOS-7979

[GEOS-7979] Add buffer to vector tiles so wide symbols are not clipped at tile boundaries

---

src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryCache.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryManager.java

By making RepositoryManager implement Spring's DisposableBean
and calling repoCache.invalidateAll(), which in turn will close
the open repos.

Make sure repositories are closed on server shutdown

---

doc/en/docguide/source/index.rst
doc/en/docguide/source/install.rst
doc/en/docguide/source/installlatex.rst

While working on the new build.geoserver.org build server, it was discovered that installing the necessary dependencies for LaTeX is nontrivial for CentOS.
In order to document the steps taken to get the LaTeX doc build working, I have added a new section to the docguide detailing  how to install LaTeX, and any other required extensions, for a selection of OSes.
@bmmpxf - would you be able to look over the Windows section, and verify that matches your experience.
If anyone else has tried building the docs on linux, I would appreciate their review as well.

Add instructions for installing LaTeX (and dependencies) to the docguide

---

src/extension/control-flow/src/main/java/org/geoserver/flow/config/DefaultControlFlowConfigurator.java
src/extension/control-flow/src/test/java/org/geoserver/flow/config/DefaultControlFlowConfigurationTest.java

Fixes the Control Flow plugin logging error messages during the GeoServer startup when the ip.blacklist and/or ip.whitelist properties are being used.  The only difference in behavior is whether or not an error message is logged and an existing unit test was modified but it requires manual inspection of the logs to verify the bug/fix.
This pull request can be backported to 2.11.x and 2.10.x.

[GEOS-8179] Fixed control flow ip.blacklist/ip.whitelist error messages during startup.

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/AbstractAppSchemaMockData.java

Backport of this PR: https://github.com/geoserver/geoserver/pull/2453
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8209

[GEOS-8209] Online app-schema tests fail for NamespacesWfsTest test (backport 2.10.x)

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/AbstractAppSchemaMockData.java

Backport of this PR: https://github.com/geoserver/geoserver/pull/2453
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8209

[GEOS-8209] Online app-schema tests fail for NamespacesWfsTest test (backport 2.11.x)

---

src/web/core/src/main/java/org/geoserver/web/MenuPageInfo.java
src/web/core/src/main/java/org/geoserver/web/data/workspace/WorkspaceEditPage.java
src/web/core/src/main/java/org/geoserver/web/services/ServiceMenuPageInfo.java

It is impossible to create a MenuPageInfo programmatically, because of a wrong usage of generics. 
It only works through Spring, because spring ignores generics.
MenuPageInfo has an associated class, which should be a subclass of GeoServerBasePage.
However. MenuPageInfo extends ComponentInfo<GeoServerBasePage>, rather than ComponentInfo<?extends GeoServerBasePage> that means that the associated class   MUST be GeoServerBasePage.class itself, which doesn't make sense.

[GEOS-8216] Fix MenuPageInfo Generics

---

src/restconfig/src/main/java/org/geoserver/catalog/rest/LayerGroupResource.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/LayerGroupTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8062
Pre rest-api-refresh version of https://github.com/geoserver/geoserver/pull/2447

[GEOS-8062] Include links to nested LayerGroups in REST LayerGroup representation (2.11 backport)

---

src/main/src/main/java/org/geoserver/config/GeoServerDataDirectory.java
src/main/src/test/java/org/geoserver/config/GeoServerDataDirectoryTest.java
src/main/src/test/java/org/geoserver/config/GeoServerPersisterTest.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8221
This also fixes https://osgeo-org.atlassian.net/browse/GEOS-8134 , superseding https://github.com/geoserver/geoserver/pull/2445 (and includes the test cases from that PR)

[GEOS-8221] GeoServerDataDir - treat null workspace as global workspace

---

src/extension/vectortiles/src/main/java/org/geotools/renderer/lite/VectorMapRenderUtils.java
src/extension/vectortiles/src/test/java/org/geoserver/wms/vector/VectorTileMapOutputFormatTest.java
src/extension/vectortiles/src/test/resources/org/geoserver/config/scaleDependentPolygonStyle.sld

GEOS-8236 When there are no active rules, use a Query with Filter.EXCLUDE.  This can be combined with other "OR" rules if the layer is used multiple times.

GEOS-8236: provide proper behavior for Styles that end up having no enabled rules

---

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/ConfigDatabaseTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8203
Updated to catch EmptyResultDataAccessException which is what gets thrown by Spring instead of returning null.  Added unit test and also added a missing @Test annotation to another unit test.
Can be backported to 2.11.x an 2.10.x.

[GEOS-8203] Fixed deleting a workspace when using JDBC Configuration returning an error response.

---

src/community/geogig/pom.xml
src/community/geogig/src/main/java/org/geogig/geoserver/config/GeogigModuleStatus.java
src/community/geogig/src/main/resources/applicationContext.xml
src/community/geogig/src/main/resources/org/geogig/geoserver/config/module_version.properties

Adds a ModuleStatus spring bean for geogig to report
module's version in the web UI's status/modules tab
and REST's /rest/about/status

Add geogig module status reporting to UI and REST

---

src/community/geogig/src/main/java/org/geogig/geoserver/wms/GeoGigCatalogVisitor.java
src/community/geogig/src/test/java/org/geogig/geoserver/GeoGigTestData.java
src/community/geogig/src/test/java/org/geogig/geoserver/wms/GeoGigCatalogVisitorTest.java

When POSTing a GeoGig DataStore via the GeoServer REST API, the
"autoIndexing" connectionParameter value seems to be interpreted
as a String ("true"/"false") instead of a boolean (true/false).
This isn't the case when creating the DataStore via the GeoServer
UI. This change handles the value correctly in either case.

Fix GeoGig CatalogVisitor so that it handles "autoIndexing" correctly.

---

src/community/geogig/src/main/java/org/geogig/geoserver/wms/GeoGigCatalogVisitor.java
src/community/geogig/src/test/java/org/geogig/geoserver/GeoGigTestData.java
src/community/geogig/src/test/java/org/geogig/geoserver/wms/GeoGigCatalogVisitorTest.java

When POSTing a GeoGig DataStore via the GeoServer REST API, the
"autoIndexing" connectionParameter value seems to be interpreted
as a String ("true"/"false") instead of a boolean (true/false).
This isn't the case when creating the DataStore via the GeoServer
UI. This change handles the value correctly in either case.

[2.11.x] Fix GeoGig CatalogVisitor so that it handles "autoIndexing" correctly.

---

src/community/geogig/src/main/java/org/geogig/geoserver/wms/GeoGigCatalogVisitor.java
src/community/geogig/src/test/java/org/geogig/geoserver/GeoGigTestData.java
src/community/geogig/src/test/java/org/geogig/geoserver/wms/GeoGigCatalogVisitorTest.java

When POSTing a GeoGig DataStore via the GeoServer REST API, the
"autoIndexing" connectionParameter value seems to be interpreted
as a String ("true"/"false") instead of a boolean (true/false).
This isn't the case when creating the DataStore via the GeoServer
UI. This change handles the value correctly in either case.

[2.10.x] Fix GeoGig CatalogVisitor so that it handles "autoIndexing" correctly.

---

src/community/geogig/src/main/java/org/geogig/geoserver/wms/GeoGigCatalogVisitor.java
src/community/geogig/src/test/java/org/geogig/geoserver/GeoGigTestData.java
src/community/geogig/src/test/java/org/geogig/geoserver/wms/GeoGigCatalogVisitorTest.java

When POSTing a GeoGig DataStore via the GeoServer REST API, the
"autoIndexing" connectionParameter value seems to be interpreted
as a String ("true"/"false") instead of a boolean (true/false).
This isn't the case when creating the DataStore via the GeoServer
UI. This change handles the value correctly in either case.

[2.9.x] Fix GeoGig CatalogVisitor so that it handles "autoIndexing" correctly.

---

src/community/dyndimension/src/main/java/org/geoserver/web/data/resource/DynamicDimensionsTabPanel.java
src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupEntryPanel.java
src/web/core/src/main/java/org/geoserver/web/wicket/GeoServerTablePanel.java
src/web/core/src/main/java/org/geoserver/web/wicket/ReorderableTablePanel.java

So, this one is a bit nasty. The code working against tables is written under the assumption that one can use the constant Property values in the providers and compare by identity.
Which works, until sessions serialization kicks in (happens if one tries to use the GeoServer UI in multiple tabs with the same login, for example), at which point the properties get serialized, deserialized, and are the clone of the original ones.
I've made changes so that the code avoids keeping a copy of the property list and always defer to a fresh call to the provider to get them, going back to the normal case.
Another option could have been to go everywhere and use equality comparison instead of identity comparison, but decided not to go there because:
- Property is an interface, none of the …

[GEOS-8237] UI page table contents get ruined once page is serialized and read back

---

src/web/security/core/src/main/java/org/geoserver/security/web/service/AbstractServiceAccessRulePage.java
src/web/security/core/src/test/java/org/geoserver/security/web/service/NewServiceAccessRulePageTest.java

Add missing WFS 2.0.0 operations in Data Security view
See https://osgeo-org.atlassian.net/browse/GEOS-7495

[GEOS-7495] Fix WFS Operations in Data Security view don't match WFS 2.0 Capabilities

---

doc/en/user/source/styling/sld/reference/layers.rst

I just tried out the InlineFeature example at http://docs.geoserver.org/latest/en/user/styling/sld/reference/layers.html#example using a WMS request with the SLD parameter.
GeoServer gave an error response with SAXParseExceptions indicating that the "gml" and "ogc" namespaces were not defined in the SLD.
After adding these namespaces the SLD rendered fine.
I have updated the doc example accordingly.

Add required namespaces to SLD InlineFeature example

---

src/wms/src/main/java/org/geoserver/wms/map/OpenLayersMapOutputFormat.java
src/wms/src/main/resources/org/geoserver/wms/map/OpenLayers2MapTemplate.ftl
src/wms/src/main/resources/org/geoserver/wms/map/OpenLayers3MapTemplate.ftl
src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapOutputFormatTest.java
src/wms/src/test/java/org/geoserver/wms/staticRasterStore/StaticRasterFormat.java
src/wms/src/test/java/org/geoserver/wms/staticRasterStore/StaticRasterFormatFactory.java
src/wms/src/test/java/org/geoserver/wms/staticRasterStore/StaticRasterReader.java
src/wms/src/test/resources/META-INF/services/org.geotools.coverage.grid.io.GridFormatFactorySpi

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8263
The PR changes the layer preview behavior to activate filtering if a coverage layer reader supports filtering (e.g. image mosaic).
Testing this was bit tricky, depending on ImageMosaic for the tests was not a good idea so I created a static reader that always return a static image but more importantly allowed me to define the read parameters I need.

[GEOS-8263] Allow in layer preview filtering (CQL, OGC and FeatureID) for rasters formats that support filtering

---

src/wms/src/main/java/org/geoserver/wms/map/OpenLayersMapOutputFormat.java
src/wms/src/main/resources/org/geoserver/wms/map/OpenLayers2MapTemplate.ftl
src/wms/src/main/resources/org/geoserver/wms/map/OpenLayers3MapTemplate.ftl
src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapOutputFormatTest.java
src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapTemplateTest.java
src/wms/src/test/java/org/geoserver/wms/staticRasterStore/StaticRasterFormat.java
src/wms/src/test/java/org/geoserver/wms/staticRasterStore/StaticRasterFormatFactory.java
src/wms/src/test/java/org/geoserver/wms/staticRasterStore/StaticRasterReader.java
src/wms/src/test/resources/META-INF/services/org.geotools.coverage.grid.io.GridFormatFactorySpi

Backport of this PR: https://github.com/geoserver/geoserver/pull/2494
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8263
The PR changes the layer preview behavior to activate filtering if a coverage layer reader supports filtering (e.g. image mosaic).
Testing this was bit tricky, depending on ImageMosaic for the tests was not a good idea so I created a static reader that always return a static image but more importantly allowed me to define the read parameters I need.

[GEOS-8263] Allow in layer preview filtering (CQL, OGC and FeatureID) for rasters formats that support filtering (backport to 2.11.x)

---

src/web/core/src/main/java/org/geoserver/web/data/store/DefaultDataStoreEditPanel.java
src/web/core/src/main/java/org/geoserver/web/data/store/ParamInfo.java
src/web/core/src/test/java/org/geoserver/web/data/store/DataAccessNewPageDatabaseTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8010
Depends upon https://github.com/geotools/geotools/pull/1659. Travis CI will fail until that is merged.
Supersedes https://github.com/geoserver/geoserver/pull/2449; only one of these PRs should be merged.

[GEOS-8010] dbtype and filetype store arguments should not be visible

---

src/rest/src/main/java/org/geoserver/rest/converters/FreemarkerHTMLMessageConverter.java

See https://osgeo-org.atlassian.net/browse/GEOS-8234
FreemarkerHTMLMessageConverter was erroneously closing the output stream, causing GZIPResponseStream to throw this error.
Since the tests don't use GZIPResponseStream, the issue was not affecting them.
Consequently, can't really add a test case for this one.

[GEOS-8234] HTML converter shouldn't close the HTTP Response outputstream

---

doc/en/user/source/installation/osx_binary.rst
doc/en/user/source/installation/osx_installer.rst
doc/en/user/source/installation/osx_jaierror.txt

This is stemming from some feedback we got at the code sprint at FOSS4G 2017.
Note: The line endings in the changed files have been converted to standard unix for sanity, only actual changes are adding `    .. include:: ./osx_jaierror.txt`.

Add troubleshooting information for installing geoserver on a Mac with an old version of JAI

---

src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/StyleCapabilitiesTest.java
src/wms/src/test/resources/org/geoserver/wms/wms_1_3/styleWithTitle.sld
src/wms/src/test/resources/org/geoserver/wms/wms_1_3/styleWithoutDescription.sld
src/wms/src/test/resources/org/geoserver/wms/wms_1_3/styleWithoutTitle.sld

This fix proposal aims to add a Title element in the Style's GetCapabilities response.
It resumes the work from https://github.com/geoserver/geoserver/pull/2200
See https://osgeo-org.atlassian.net/browse/GEOS-8063

[GEOS-8063] Fix WMS1.3.0 SLD definition can break getcapabilities

---

src/community/release/ext-geopkg.xml
src/pom.xml
src/web/app/pom.xml
src/web/core/pom.xml
src/web/core/src/main/java/applicationContext.xml
src/web/core/src/main/java/org/geoserver/web/data/store/DefaultDataStoreEditPanel.java
src/web/core/src/test/java/org/geoserver/web/data/store/CoverageStoreNewPageTest.java
src/web/core/src/test/java/org/geoserver/web/data/store/DataAccessNewPageTest.java

This moves the read part of the GeoPackage module into core.
Vector data works fine, but is slow extracting small portions because the spatial index is not used.
Raster data unfortunately does not work, seems like there is an axis flipping issue.

[GEOS-8265] Move GeoPackage support into core

---

src/gwc/src/main/java/org/geoserver/gwc/layer/CatalogStyleChangeListener.java
src/gwc/src/test/java/org/geoserver/gwc/layer/CatalogStyleChangeListenerTest.java

Fixes an exception generated when changing just the workspace of a style, but not the name.
Looking through this code though, it seems like there may be other logistical issues in what happens here though. It seems as though the listener truncates every layer associated with a style of the same name without taking into consideration the workspace of the style? I need to look at it further. For now though this fixes the ArrayIndexOutOfBoundsException.

[GEOS-8288] Check that name has actually been changed in the style change listener

---

src/community/mbstyle/src/test/java/org/geoserver/community/mbstyle/web/MBStyleHandlerTest.java
src/community/mbstyle/src/test/resources/org/geoserver/community/mbstyle/web/citeGroup.json
src/main/src/main/java/org/geoserver/catalog/GeoServerSLDVisitor.java
src/main/src/main/java/org/geoserver/catalog/LayerGroupHelper.java
src/web/wms/src/main/java/org/geoserver/wms/web/data/OpenLayersPreviewPanel.java

Support non-sld formats for "Preview as Style Group"
Improvements to GeoServerSLDVisitor and LayerGroupHelper to support InlineFeature elements for use with background layers
Depends upon https://github.com/geotools/geotools/pull/1704

Support for MBStyle StyleGroups

---

src/rest/src/main/java/org/geoserver/rest/IndexController.java

https://osgeo-org.atlassian.net/browse/GEOS-8308
This fix simply doesn't include any endpoints which do not start with `/rest`, restoring the functionality of the original index page.
We may wish to consider improving the index page to include the gwc endpoints in the future.

[GEOS-8308] Only include /rest endpoints in IndexController

---

src/community/geopkg/src/main/java/org/geoserver/geopkg/GeoPackageGetMapOutputFormat.java
src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoPackageProcess.java
src/community/geopkg/src/test/java/org/geoserver/geopkg/wps/gs/GeoPackageProcessTest.java

The problem is that if the WPS XML does not include the 
`<format>....</format>`
part, we end up adding a `format:<null>` entry  to the options map, then we only check if the key is present (not the value being null).
An earlier attempt just added a check if the value was non-null, but there is another "is key present, if so, dereference value" check on the mbtiles AbstractTilesGetMapOutputFormat code that is very similar (that I didn't want to have to test), and this seems cleaner in any case.

[GEOS-8310] Fix geopackage tile image format default handling.

---

src/community/geogig/pom.xml

PostgreSQL driver version is now in the main GeoServer dependency management section.

Remove explicit PostgreSQL version in GeoGig module POM

---

src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayersPage.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/CachedLayersPageTest.java

Applies URL mangling to the seed link on CachedLayersPage so it is safe when GeoServer is behind a proxy.
https://github.com/geoserver/geoserver/commit/80a6580237f668f2924773d27b3a733caf61696c#diff-a97ba9e81155e8aad931c3222bc6a456R173
https://osgeo-org.atlassian.net/browse/GEOS-8319

Mangle seed links in CacheLayersPage, fixes GEOS-8319

---

src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayersPage.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/CachedLayersPageTest.java

Mangle seed links in CacheLayersPage, fixes GEOS-8319, Backport to 2.12

---

src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayersPage.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/CachedLayersPageTest.java

Mangle seed links in CacheLayersPage, fixes GEOS-8319, Backport to 2.11

---

src/main/src/main/java/org/geoserver/filters/LoggingFilter.java
src/ows/src/main/java/org/geoserver/ows/util/RequestUtils.java
src/ows/src/test/java/org/geoserver/ows/util/RequestUtilsTest.java

Added a utility method to get the client IP address, checking the X-Forwarded-For request header, and updated Logging Filter to use it.  This method was copied from org.geoserver.monitor.MonitorFilter and made public static and unit tests were added to test it.  Extensions that uses this same duplicated code block have not been modified in this pull request since it is not necessary and I am not familiar with every one of those extensions.
Also, removed an extra double quotes character in the logging filter output.

[GEOS-8316] Fixed LoggingFilter ignoring the X-Forwarded-For request header

---

doc/en/README.md

Just fixed a small typo in maven command.
I've also trimmed trailing spaces. I hope (🙏) this is not a problem during PR review.
Any feedback is welcome.
Keep rocking this great project - Thank you.

correct typo in maven command parameter

---

doc/en/api/1.0.0/coveragestores.yaml

Unlike data stores, all coverage stores have the same PUT/POST structure - the location of the data is determined solely by an URL.
Consequently, individual examples for each coverage type seem unnecessary (perhaps a second example for imagemosaic would be useful, but that seems to already be covered better in the ImageMosac extension docs).

Swagger REST API Examples - Coverage Stores

---

doc/en/api/1.0.0/datastores.yaml

POST examples are minimal required to be valid.
PUT examples are maximal (except for connection parameters, which are described inline), and exclude values which cannot be changed via REST, such as `name`, `workspace`, or the `dbtype` connection parameter.
The current examples just include stores that are included in GeoServer by default, not extensions or community modules.
Misc swagger errors were also fixed.

Swagger REST API Examples - Datastores

---

src/kml/src/test/java/org/geoserver/kml/KMLReflectorTest.java
src/kml/src/test/resources/org/geoserver/kml/xAL.xsd

If not online, this happens:
```
Tests in error: 
testValidKML(org.geoserver.kml.KMLReflectorTest): src-resolve: Cannot resolve the name 'xal:AddressDetails' to a(n) 'element declaration' component.
```
This adds the xAL.xsd file. The alternative would be to change this Reflector test to be an Online one.

[GEOS-8353] Ensure KML validates without being online.

---

src/extension/dxf/core/src/main/java/org/geoserver/wfs/response/dxf/Rel14DXFWriter.java
src/extension/dxf/core/src/test/java/org/geoserver/wfs/response/DXFOutputFormatTest.java

With this change autocad, draftsight and others shows the attributes in dxf as labels at the correct position.

[GEOS-6799] place dxf attributes on interior point

---

src/platform/src/main/java/org/geoserver/platform/GeoServerResourceLoader.java

Also, changed the logger name to the correct package name.  This is a simple logging change and does not have any unit tests.

[GEOS-8328] Updated GeoServerResourceLoader to stop setting its logging level.

---

src/main/src/main/java/org/geoserver/catalog/impl/AbstractCatalogFacade.java
src/main/src/test/java/org/geoserver/config/util/XStreamPersisterTest.java

This modifies the fix for https://osgeo-org.atlassian.net/browse/GEOS-8289 to only apply to styles that have a workspace.
This pull request can be backported to 2.12.x only.

[GEOS-8364] Fixed "Failed to resolve workspace" messages for non-workspaced styles.

---

src/main/src/main/java/org/geoserver/ows/LocalWorkspaceCallback.java
src/main/src/main/java/org/geoserver/ows/OWSHandlerMapping.java
src/main/src/test/java/org/geoserver/ows/LocalWorkspaceCallbackTest.java
src/main/src/test/java/org/geoserver/ows/OWSHandlerMappingTest.java

This pull request modifies LocalWorkspaceCallback and OWSHandlerMapping to only look up layer groups without a workspace.  It also delays looking up the global layer group until after checking if a workspace exists to reduce database queries with JDBC Configuration.

[GEOS-8318] Updated virtual service global layer group look up to not load workspaced layer groups

---

src/main/src/main/java/org/geoserver/catalog/AttributeTypeInfo.java
src/main/src/main/java/org/geoserver/catalog/impl/AttributeTypeInfoImpl.java
src/main/src/main/java/org/geoserver/catalog/impl/FeatureTypeInfoImpl.java
src/main/src/test/java/org/geoserver/catalog/impl/FeatureTypeInfoImplTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8324
My solution has been to duplicate the behaviour from `AttributeTypeInfoImpl.equals()` inside of `FeatureTypeInfoImpl.equals()`, excluding the check for whether the FeatureTypeInfos are equal to avoid recursion. This is a bit brittle to API changes, but is at least a complete equality check.
An alternative solution would be to remove the equality check on FeatureTypeInfo from `AttributeTypeInfoImpl.equals()`

[GEOS-8324] Avoid recursion in FeatureTypeInfoImpl.equals

---

src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendMerger.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetLegendGraphicTest.java

This commit stops the generation of an empty row on a vertical non-raster
legend when there is a text symbolizer used in the style SLD.

[GEOS-7757] Fix empty row during legend creation.

---

src/community/geogig/pom.xml

back-porting this pom change as it missed the 2.12/2.13 cutoff

[backport 2.12.x] Remove explicit PostgreSQL version in GeoGig module POM

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleAdminPanel.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StylePageSecurityTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8225
This looks like it was another issue introduced by the style page rewrite; prior to that the workspace drop-down was disabled only when editing styles, not when creating new ones.
This behaviour has been restored.

[GEOS-8225] Allow workspace to be set on new styles if not admin

---

src/web/demo/src/main/java/org/geoserver/web/demo/PreviewLayerProvider.java
src/web/demo/src/test/java/org/geoserver/web/demo/PreviewLayerProviderTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8242
The size of the results when there was no filter was being cached, and that value was getting used in place of the actual number of results returned by the filter.
An alternative fix would be to just not cache the size value.
This behaviour seems to have been introduced by https://github.com/geoserver/geoserver/pull/836

[GEOS-8242] Use separate keys when caching different queries

---

doc/en/developer/source/programming-guide/wps-services/implementing.rst

This removes the duplicate dependency ``gs-wps-core`` in the English WPS-implementation documentation. Otherwise the duplicate leads to an error when building the WPS with Maven:
``duplicate declaration of version ${gs.version}``

Remove duplicate dependency gs-wps-core (en)

---

src/platform/src/main/java/org/geoserver/platform/GeoServerExtensions.java

https://osgeo-org.atlassian.net/browse/GEOT-5289
https://github.com/geotools/geotools/pull/1670
Failure was:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project gs-platform: Compilation failure
[ERROR] /home/ben/geoserver/src with spaces/geoserver/src/platform/src/main/java/org/geoserver/platform/GeoServerExtensions.java:[166,40] error: cannot find symbol
```
Fix follows change to `PropertyAccessors.java` in https://github.com/geotools/geotools/pull/1670 .

Fix compile failure in gs-platform caused by GeoTools Java 9 compatibility changes [GEOT-5289]

---

src/community/jms-cluster/jms-geoserver/pom.xml
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/DocumentFile.java
src/pom.xml
src/restconfig/pom.xml
src/restconfig/src/main/java/org/geoserver/rest/catalog/AvailableResourcesConverter.java
src/restconfig/src/main/java/org/geoserver/rest/catalog/MapXMLConverter.java
src/restconfig/src/main/java/org/geoserver/rest/security/RuleMapXMLConverter.java
src/wms/pom.xml
src/wms/src/main/java/org/geoserver/wms/decoration/MapDecorationLayout.java

https://osgeo-org.atlassian.net/browse/GEOS-8340
Adds the JDom dependency in the pom files where required and changes the package names from `org.jdom` to `org.jdom2`
This follows up on geotools/geotools#1719

[GEOS-8340] Upgrade JDom library to version 2.0.6

---

build/publish_release.sh

See here: https://osgeo-org.atlassian.net/browse/GEOS-7622

[GEOS-7622] Automatic relase scripts should copy PDF docs, shouldn't copy mac and win prebuild files

---

src/release/jetty/modules/servlets.mod
src/release/jetty/start.ini
src/release/pom.xml

See https://osgeo-org.atlassian.net/browse/GEOS-7343
Tested locally by building the bin.zip and uncommenting the CORS filter, seems to work. Should try and confirm with the next release artifacts.

[GEOS-7343] Add jetty-servlets to system-independent binary to support CORS filter

---

src/web/wms/src/main/resources/org/geoserver/wms/web/data/ol-load.ftl

Fix for https://osgeo-org.atlassian.net/browse/GEOS-8369
Turns out the window.onload function was holding on to the old source referencing the initial preview layer, and not getting updated when the preview layer was changed. This has been fixed.
No test case, since this involves JS nested in Ajax updated nested in Wicket; and is therefore likely untestable within the wicket test framework.

[GEOS-8369] Style preview - Update window.onload when ol source (preview layer) changes

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NamespacesWfsTest.java
src/wfs/src/main/java/org/geoserver/wfs/WFSWorkspaceQualifier.java
src/wfs/src/main/java/org/geoserver/wfs/response/v2_0/GetPropertyValueResponse.java

The trick of adding all the namespaces in the catalog before encoding, taking care of temporarily disabling local workspace filtering if needed, was applied also to `GetPropertyValueResponse` .
Test cases for GetPropertyValue requests and GetFeature requests making use of a StoredQuery were added to the test class `NamespacesWfsTest`, which provides a sample mapping involving two nested complex feature types in two GML flavors, 3.1 and 3.2: this allows to test both GML 3.1 and GML 3.2 output formats (where applicable).

[GEOS-8108] fix for null namespaces with GetPropertyValue and stored queries requests

---

src/main/src/main/java/org/geoserver/filters/GZIPResponseStream.java
src/main/src/test/java/org/geoserver/filters/GZipFilterTest.java

[GEOS-8409] GZIPResponseStream should not throw Exception on flushing

---

src/community/script/groovy/pom.xml
src/community/script/rb/src/test/resources/org/geoserver/script/rb/main-helloWorld.rb
src/community/script/web/src/main/java/org/geoserver/script/web/Script.java
src/community/script/web/src/main/java/org/geoserver/script/web/ScriptEditPage.java
src/community/script/web/src/main/java/org/geoserver/script/web/ScriptNewPage.java
src/community/script/web/src/main/java/org/geoserver/script/web/ScriptsModel.java

The script community module can't find the scriptMgr bean because it was renamed scriptManager. Also there is a failing ruby application test because of the restlet to spring migration.
JIRA:
https://osgeo-org.atlassian.net/browse/GEOS-8427

Fixes for GEOS-8427: rename scriptMgr to scriptManager, fix ruby test  and upgrade groovy

---

src/wms/src/main/java/org/geoserver/wms/legendgraphic/BufferedImageLegendGraphicBuilder.java
src/wms/src/main/java/org/geoserver/wms/legendgraphic/ColorMapLegendCreator.java
src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendMerger.java
src/wms/src/test/java/org/geoserver/wms/legendgraphic/LegendLayoutTest.java

See: https://osgeo-org.atlassian.net/browse/GEOS-8389
Turns out the LegendMerger was always assuming a title would be present, and with `forceTitles:off` would try merging layer group images with each other in place of the titles.
* Added `forceTitlesOff` property to `MergeOptions`
* If `forceTitlesOff=true`, LegendMerger doesn't try to merge images with the (nonexistant) titles
* Added a full set of tests for LayerGroup legend generation

[GEOS-8389] Support forceTitles:off for layer group legends

---

src/wfs/src/main/java/org/geoserver/wfs/Transaction.java
src/wfs/src/test/java/org/geoserver/wfs/TransactionTest.java

This PR adds a condition to account for the principal being an instance of String. This occurs when sending wfs transactions while supplying the oauth access token, anonymous is stored as the VersioningCommitAuthor.
https://osgeo-org.atlassian.net/browse/GEOS-8459

[GEOS-8459] Handle case where principal is instance of String

---

src/wfs/src/main/java/org/geoserver/wfs/FeatureSizeFeatureCollection.java
src/wfs/src/main/java/org/geoserver/wfs/GetFeature.java
src/wfs/src/test/java/org/geoserver/wfs/GetFeatureNoCachingTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8430
Replaces #1355
Rebased the pull request on current master to make sure everything builds against today's code, and:
- Improve use of generic and use try with resources when possible
- Some fixes to docs, cut down on advertisement and augment code behavior description
- Made the class public (sigh) because subclasses of GetFeature in GeoServer extensions might actually need it (since the code is right in the middle of an extension point)
- Added test to make sure GetFeature works with both caching on and off
- Created a GeoServer ticket and made the commits refer to it

[GEOS-8430] Cache small amount of features in memory to avoid repeated data scans in GetFeature requests

---

src/extension/dxf/core/src/main/java/org/geoserver/wfs/response/dxf/DXFWriterFinder.java

GeoTools plugin system has changed in response to Java 9 restrictions (changing API to use factory rather than service provider).
Follow API change to geotools covered here:
- https://github.com/geotools/geotools/wiki/FactoryRegistry-Refactoring-for-Java-9-Compatibility
- https://github.com/geotools/geotools/pull/1670

Change to factory registry

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/FeatureChainingWfsTest.java
src/wfs/src/main/java/org/geoserver/wfs/xml/FeatureTypeSchemaBuilder.java
src/wfs/src/main/java/org/geoserver/wfs/xml/v1_1_0/XmlSchemaEncoder.java
src/wfs/src/test/java/org/geoserver/wfs/v1_1/DescribeFeatureTypeTest.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/DescribeFeatureTypeTest.java

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8250
Like in WFS 1.0, WFS 2.0 schema import is unnecessary when doing a describe feature type. According to WFS 2.0 standard the describe feature type should only describe the feature type not the full response:
> The DescribeFeatureType operation returns a schema description of feature types offered by a WFS instance. The schema descriptions define how a WFS expects feature instances to be encoded on input (via Insert, Update and Replace actions) and how feature instances shall be encoded on output (in response to a GetPropertyValue, GetFeature or GetFeatureWithLock operation).
This PR removes the uncessary and wrong import adn adds several tests cases for this, including app-schema integration tests.

[GEOS-8250] WFS 2.0 DescribeFeatureType responses for app-schema type s contain a spurious WFS 2.0 jar import

---

src/community/nsg-profiles/nsg-wmts-profile/src/main/java/org/geoserver/nsg/wmts/GridSetsLoader.java
src/extension/inspire/src/main/java/org/geoserver/inspire/wmts/WMTSExtendedCapabilitiesProvider.java
src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
src/gwc/src/main/java/org/geoserver/gwc/layer/StyleParameterFilter.java
src/gwc/src/main/java/org/geoserver/gwc/wmts/WMTSCapabilitiesProvider.java
src/gwc/src/main/resources/geowebcache-wmtsservice-context.xml
src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/wmts/WMTSAdminPage.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/wmts/WMTSAdminPageTest.java

- https://osgeo-org.atlassian.net/browse/GEOS-8434
- https://osgeo-org.atlassian.net/browse/GEOS-8436
- https://osgeo-org.atlassian.net/browse/GEOS-8439
- https://osgeo-org.atlassian.net/browse/GEOS-8438
**Depends on this PR https://github.com/GeoWebCache/geowebcache/pull/572**

[GEOS-8434, GEOS-8436, GEOS-8439, GEOS-8438] Allow WMTS to use CITE compliance mode

---

src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/ImporterIntegrationTest.java
src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/RequestContextListener.java

See https://osgeo-org.atlassian.net/browse/GEOS-8460
See also https://github.com/geoserver/geoserver/pull/1762 ; this is effectivly a continuation of that PR, making the same logic apply to `initAsync` and `createContextAsync` in addition to `runAsync`.

[GEOS-8460] Make importer share the request context when initializing a job asynchronously

---

src/main/src/main/java/org/geoserver/catalog/impl/LocalWorkspaceCatalog.java
src/main/src/test/java/org/geoserver/catalog/impl/LocalWorkspaceCatalogTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8485
LocalWorkspaceCatalog is called with a "workspace:layergroup" string wich was not well handled.
This commit aligns getLayerGroupByName on getLayerByName method.
To reproduce, configure a LayerGroup in a Workspace then call a GetLegendGraphic. Without this PR, call fails.
Contributor License Agreement sent for Sogelink.

[GEOS-8485] GetLegendGraphic request not working with layer groups in workspace

---

src/main/src/main/java/org/geoserver/catalog/impl/LocalWorkspaceCatalog.java
src/main/src/test/java/org/geoserver/catalog/impl/LocalWorkspaceCatalogTest.java

No unit tests have been added or modified but the behavior from the caller's point of view should not be changed so the existing tests in LocalWorkspaceCatalogTest and LocalWorkspaceLayersTest should be sufficient.

[GEOS-8334] Reduced the number of LocalWorkspaceCatalog database queries when using JDBC Configuration.

---

src/main/src/main/java/org/geoserver/catalog/impl/LocalWorkspaceCatalog.java
src/main/src/test/java/org/geoserver/catalog/impl/LocalWorkspaceCatalogTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8485
Backport from MR #2681 to branch 2.12.x

[Backport on 2.12.x][GEOS-8485] Fix GetLegendGraphic to work on layergroup in workspace

---

src/main/src/main/java/org/geoserver/catalog/impl/LocalWorkspaceCatalog.java
src/main/src/test/java/org/geoserver/catalog/impl/LocalWorkspaceCatalogTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8485
Backport from MR #2681 to branch 2.11.x

[Backport on 2.11.x][GEOS-8485] Fix GetLegendGraphic to work on layergroup in workspace

---

src/restconfig/src/main/java/org/geoserver/rest/catalog/StyleController.java
src/restconfig/src/test/java/org/geoserver/rest/catalog/StyleControllerTest.java

Charset is ignored as it is already handled by HttpServletRequest internals.
_Contributor License Agreement already signed and sent to osgeo._

[GEOS-8475] Handle charset in contentType header when uploading style through restconfig

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/FeatureChainingWfsTest.java
src/wfs/src/main/java/org/geoserver/wfs/xml/FeatureTypeSchemaBuilder.java
src/wfs/src/main/java/org/geoserver/wfs/xml/v1_1_0/XmlSchemaEncoder.java
src/wfs/src/test/java/org/geoserver/wfs/v1_1/DescribeFeatureTypeTest.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/DescribeFeatureTypeTest.java

Link to related JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-8250
This is the backport of #2676 to GeoServer 2.12.x (stable).

[GEOS-8250] WFS 2.0 DescribeFeatureType responses for app-schema types contain a spurious WFS 2.0 jar import

---

src/wcs/src/main/java/org/geoserver/wcs/responses/AscCoverageResponseDelegate.java
src/wcs1_0/src/test/java/org/geoserver/wcs/GetCoverageTest.java
src/web/wcs/src/main/java/org/geoserver/wcs/web/publish/WCSLayerConfig.java

This change just allows both, because we advertise it as ARCGRID in some places (including as
default publish format) and that is used in the default resource directory. So changing it everywhere still seemed likely to cause breakage (e.g. for upgrades in place).
Also fixes case where requesting compressed mime-type doesn't return compressed.
Also fixes case where requesting compressed mime-type returns an unusual file extension
("ArcGrid-GZIP" instead of "asc.gz").

[GEOS-6540] Fix problem in ArcGrid WCS format (advertised as ARCGRID, supported ArcGrid)

---

doc/en/developer/source/release-guide/index.rst

With the new changes to the nightly doc build to get it to work with the new build server (see discussion on mailing list), the procedure for cutting a new RC has changed slightly.
Since we are directly pushing to the relevant folders, it is no longer necessary to update the ProxyPass on the doc server.

Update release guide with new docbuild instructions

---

doc/en/user/source/extensions/inspire/index.rst

INSPIRE has now published guidance on using a WCS for a download service at https://inspire.ec.europa.eu/id/document/tg/download-wcs

Remove out-of-date note on INSPIRE WCS guidance

---

src/community/mbstyle/src/test/java/org/geoserver/rest/catalog/MBStyleControllerTest.java
src/extension/css/src/test/java/org/geoserver/rest/catalog/CssStyleControllerTest.java
src/extension/ysld/src/test/java/org/geoserver/rest/catalog/YsldStyleControllerTest.java
src/restconfig/src/main/java/org/geoserver/rest/catalog/StyleController.java

See https://osgeo-org.atlassian.net/browse/GEOS-8493
In order to make this fix a bit more sane, this PR also includes heavy refactoring on the StyleController class, moving most common code snippets into methods, and making each endpoint implementation more consistent with respect to behaviour, error messages, and variable names. As part of this, some methods were moved to different places in the file, so it might be a little difficult to follow the changes (the file structure was a mess before, it should be more organized now).
Functionality-wise, the only change should be the Support for POSTing non-SLD files (StyleController has pretty good test cases, and they are all happy, so I am reasonably confident in this). Some error messages _may_ have changed to be more consistent between …

[GEOS-8493] Support POST for non-SLD styles

---

src/web/demo/src/main/java/org/geoserver/web/demo/DemoRequestResponse.java
src/web/demo/src/test/java/org/geoserver/web/demo/DemoRequestsPageTest.java
src/wfs/src/main/java/org/vfny/geoserver/wfs/servlets/TestWfsPost.java
src/wfs/src/test/java/org/vfny/geoserver/wfs/servlets/TestWfsPostOnlineIntegrationTest.java
src/wfs/src/test/java/org/vfny/geoserver/wfs/servlets/TestWfsPostTest.java

This one wound up turning into two different bugs partway through fixing it. Still submitting as one PR, since the bugs are closely related, but included the fixes as separate commits.
[GEOS-8543](https://osgeo-org.atlassian.net/browse/GEOS-8543) - Error handling just used a PrintWriter for output, so if an error occurred during error handling, then everything already written would be included in the new error response, resulting in malformed output. Fixed, and added some (online) tests (not optimal, but there isn't really any other way to test the full servlet functionality)
[GEOS-8544](https://osgeo-org.atlassian.net/browse/GEOS-8544) - When sending a request, the demo page sends the form content to a new form in the modal window page, which then sends that to GeoServer and handled the …

[GEOS-8543] [GEOS-8544] Demo page fixes

---

src/wcs2_0/src/main/java/org/geoserver/wcs2_0/kvp/WCS20GetCoverageRequestReader.java
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/GeoTiffKvpTest.java

See also https://osgeo-org.atlassian.net/browse/GEOS-8555

[GEOS-8555] GeoServer does not understand WCS 2.0 GeoTiff extension prefixes in KVP requests

---

src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java

Fixes [GEOS-8366](https://osgeo-org.atlassian.net/browse/GEOS-8366) by changing the relative path to an absolute path.

[GEOS-8366] fix bug adding a new GeoPackage datastore from within the data directory

---

doc/en/api/1.0.0/layergroups.yaml
doc/en/api/1.0.0/layers.yaml
src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
src/rest/src/main/java/org/geoserver/rest/converters/XStreamCatalogListConverter.java
src/restconfig/src/main/java/org/geoserver/rest/catalog/LayerController.java
src/restconfig/src/main/java/org/geoserver/rest/catalog/LayerGroupController.java
src/restconfig/src/main/java/org/geoserver/rest/catalog/ftl-templates/LayerGroupInfo.ftl
src/restconfig/src/main/java/org/geoserver/rest/catalog/ftl-templates/layergroups.ftl
src/restconfig/src/main/java/org/geoserver/rest/catalog/ftl-templates/layers.ftl
src/restconfig/src/test/java/org/geoserver/rest/catalog/LayerControllerTest.java
src/restconfig/src/test/java/org/geoserver/rest/catalog/LayerGroupControllerTest.java

This has been an ongoing issue, and has a number of associated JIRA tickets:
* https://osgeo-org.atlassian.net/browse/GEOS-4339
* https://osgeo-org.atlassian.net/browse/GEOS-5356
* https://osgeo-org.atlassian.net/browse/GEOS-6227
* https://osgeo-org.atlassian.net/browse/GEOS-7682
The issue is that layers of the same name in different workspaces show up identically when listing layers using the rest API (not noted in most of these issues is that this also affects the layer list shown when viewing a layer group).
This also presents as a legitimate error for links to layers, as links also use the unprefixed name and therefore always go to the default / first layer with that name.
There has been a bunch of ongoing discussion, which ultimately boils down to we should probably use prefixed …

[GEOS-4339][GEOS-5356][GEOS-6227][GEOS-7682] REST API - Use prefixed layer names in lists and links

---

src/web/security/core/src/main/java/org/geoserver/security/web/auth/CommaSeparatedListConverter.java

When using the UI to add IP addresses to the `Excluded network masks`, the serialized config that is written looks like this:
```xml
<bruteForcePrevention>
<enabled>true</enabled>
<minDelaySeconds>1</minDelaySeconds>
<maxDelaySeconds>5</maxDelaySeconds>
<maxBlockedThreads>100</maxBlockedThreads>
<whitelistedMasks  class="java.util.Arrays$ArrayList">
<a class="string-array">
<string>127.0.0.1</string>
<string>192.168.0.1</string>
</a>
</whitelistedMasks>
</bruteForcePrevention>
```
This is because the UI page (`AuthenticationPage`) that contains the brute force protection config uses `CommaSeparatedListConverter` to convert the user entered list of IPs into a `List<String>`. The problem is, the implementation uses `java.util.Arrays.asList()` which returns a private concrete class: …

Fix serialization of brute force whitelist mask

---

src/community/hz-cluster/src/main/java/org/geoserver/cluster/hazelcast/HzCacheProvider.java
src/community/hz-cluster/src/test/java/org/geoserver/cluster/hazelcast/HzCacheProviderTest.java

Updated HzCacheProvider to support the same system property to control the cache eviction time that JDBCCacheProvider uses.  This is pretty much a copy and paste from:
https://github.com/geoserver/geoserver/blob/master/src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/JDBCCacheProvider.java

[GEOS-8320] Added system property for Hazelcast cache expiration time

---

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/config/JDBCGeoServerImplTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8323
This pull requests adds a call to logStatement for all JDBC Configuration queries that weren't already being logged.  It also removes an unnecessary use of the Guava Joiner class to do the query result size and timing logging and adds that logging to getAll.  A few java.* and org.* imports were also moved to be grouped with other imports from those packages.
No new new unit tests were added but the modified methods are covered by many of the tests in CatalogImplWithJDBCFacadeTest and JDBCGeoServerImplTest which inherit the tests from CatalogImplTest and GeoServerImplTest.  This pull request also fixes an NPE when JDBCGeoServerImplTest runs org.geoserver.config.GeoServerImplTest.testModifyLogging().
This pull request can be backported to …

[GEOS-8323] Added debug logging to all JDBC Configuration database queries

---

src/community/solr/pom.xml
src/pom.xml

https://osgeo-org.atlassian.net/browse/GEOS-8535
Note that the necessary fixes have already be done in GeoTools:
https://github.com/geotools/geotools/pull/1792
The exception we get when creating a Solr store in GeoServer::

[GEOS-8535] Using Apache Solr data store from GeoServer UI may result in a class not found exception

---

src/gwc/src/main/java/org/geoserver/gwc/layer/DefaultTileLayerCatalog.java
src/gwc/src/test/java/org/geoserver/gwc/layer/DefaultTileLayerCatalogTest.java

This fixes an issue with tile layers that have an empty "Allowed Styles" parameter filter when saving. The issue has to do with Collections.unmodifiableSet not being serializable after the tile layer catalog switched to the SecureXstream implementation.
The issue mainly affected the backup/restore community module, which was failing when a tile layer had now styles selected except for the default.

Fix serialization issue with tile layers with empty style parameter filter

---

src/wms/src/main/java/org/geoserver/wms/featureinfo/RasterLayerIdentifier.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetFeatureInfoIntegrationTest.java

This pull request fixes incorrect WMS GetFeatureInfo responses for raster layers using "Reproject native to declared" with a different native and declared CRS.  RasterLayerIdentifier.identify makes multiple calls to the GridCoverage2DReader getOriginalEnvelope, getOriginalGridToWorld and getCoordinateReferenceSystem methods which should all be returning responses using the native CRS instead of the declared CRS when the projection policy is reproject to declared.
This pull request can be backported to 2.12.x and 2.11.x.

[GEOS-8545] Fixed incorrect GetFeatureInfo for coverage using reproject to declared

---

src/wfs/src/main/java/org/geoserver/wfs/GetFeature.java
src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetFeatureTest.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureTest.java

Prevent optimizations when the combination of `count` and `startIndex` result in fewer than `count` features matching the request.

[GEOS-7233] Fix `totalFeatures` count for WFS 2.0 GetFeature requests

---

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/listener/BackupJobExecutionListener.java
src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/tasklet/FinalizeBackupTasklet.java
src/community/backup-restore/core/src/main/resources/applicationContext.xml
src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java

This moves the final step of the backup process from the afterJob call to its own discrete Spring Batch step. This prevents the job from being marked as COMPLETED before the entire process is finished.
We ran into this issue when trying to script backups, because the job gets marked as completed but the zip file does not exist yet.

[GEOS-8587] Finalize backup as part of backup job

---

src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/Dimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/DimensionsUtils.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/DomainSummary.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/RasterCustomDimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/RasterDimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/RasterElevationDimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/RasterTimeDimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/VectorDimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/VectorElevationDimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/VectorTimeDimension.java

The changes in this pull request:
- The optimization reported in the title
- Taking apart the Dimension class, which was a "method collector" mixing vector and raster stuff, and creating two subclasses better separating the vector and raster bits
- Making the other subclasses extend one of the above, reducing the amount of code duplication (they could have been parameterized away by just using VectorDimension and RasterDimension, but then I would have had to change all creation points... probably enough changes for a first round)

[GEOS-8598] WMTS n-dimensional DescribeDomain loads the entire domain of a dimension when min/max would suffice

---

src/main/src/main/java/org/geoserver/security/impl/DataAccessRuleDAO.java

When parsing security rules, class DataAccessRuleDao log a warn when a rule doesn't match an existing layer. This check doesn't handle layergroups in workspaces, only workspaces, layers with or without
workspaces and layergroups without workspace.
This fix adds a check on layergroups in workspace in order not to log a false warning.

[GEOS-8607] Fix warning when parsing rules on a non global group

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/BBox3DTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/BBoxFilterTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/Gsml32BoreholeIntervalWfsTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/IsolatedNamespacesWfsTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NamespacesWfsTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SRSReprojectionTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SRSWfsTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SimpleAttributeFeatureChainWfsTest.java
src/wfs/src/main/java/org/geoserver/wfs/xml/GML32OutputFormat.java
src/wfs/src/main/java/org/geoserver/wfs/xml/GML3OutputFormat.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8352
Follow up to https://github.com/geotools/geotools/pull/1824 
This one will not even compile until the geotools counterpart is merged (and the build will fail as soon as the GT is merged, if this is also not merged)
Same arrangement as the GT one, I'm asking @nmco for review but maybe @bencaradocdavies is interested too

[GEOS-8352] Number of decimals ignored for GML 3.2 output

---

src/main/src/main/java/org/geoserver/security/decorators/DefaultSecureCatalogFactory.java
src/main/src/main/java/org/geoserver/security/decorators/SecuredObjects.java
src/main/src/test/java/org/geoserver/security/decorators/SecuredResourceInfoTest.java

The original GEOS-8603 fix added WMSLayerInfo and WMTSLayerInfo types to the `secure` method of the default factory, but forgot to add them to the list of supported types. Tests added as well.

[GEOS-8603] Include missing types in `canSecure` list

---

src/main/src/main/java/org/geoserver/security/decorators/DefaultSecureCatalogFactory.java
src/main/src/main/java/org/geoserver/security/decorators/SecuredObjects.java
src/main/src/test/java/org/geoserver/security/decorators/SecuredResourceInfoTest.java

The original GEOS-8603 fix added WMSLayerInfo and WMTSLayerInfo types to the `secure` method of the default factory, but forgot to add them to the list of supported types. Tests added as well.

[GEOS-8603] Backport 2.13.x - Include missing types in `canSecure` list

---

src/extension/app-schema/app-schema-oracle-test/pom.xml
src/extension/app-schema/app-schema-postgis-test/pom.xml
src/extension/app-schema/app-schema-test/pom.xml

`DefaultGeometryTest` seems to cause Jenkins geoserver-master-app-schema-online to hang. See: https://sourceforge.net/p/geoserver/mailman/message/36277267/

Exclude App-Schema default geometry tests from the online tests

---

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/config/JDBCGeoServerImplTest.java

Pull request for https://osgeo-org.atlassian.net/browse/GEOS-8636 that fixes the service cache not being updated when service info is saved to or removed from the database.  Several unused imports were also removed.
Contains unit test and can be backported to 2.13.x.

[GEOS-8636] JDBC Configuration: Ensure that the JDBC Configuration service cache does not retain old service info when the database is updated.

---

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/catalog/CatalogImplWithJDBCFacadeTest.java

Pull request for https://osgeo-org.atlassian.net/browse/GEOS-7210 that fixes incorrect character encoding when saving new catalog objects to the database.
Contains unit test and can be backported to 2.13.x.

[GEOS-7210] JDBC Configuration: Fixed incorrect encoding of special characters when adding catalog objects with JDBC Configuration.

---

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/catalog/JDBCCatalogFacade.java
src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/JDBCConfigTestSupport.java
src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/catalog/CatalogImplWithJDBCFacadeTest.java
src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java

Pull request for https://osgeo-org.atlassian.net/browse/GEOS-8631 that fixes READ locks not being upgraded to WRITE locks before modifying the catalog when using JDBC Configuration.  Ideally, IsolatedCatalogFacade would have been moved to setFacade() at the same time but this causes ModificationProxy issues in JDBC Configuration so it will have to be done separately.
A commented out unit test that ignored an assertion error was removed since that unit test has been passing for a while now.
Contains unit test and can be backported to 2.13.x.

[GEOS-8631] JDBC Configuration: Fixed JDBC Configuration not upgrading to write locks before modifying the catalog.

---

src/main/src/main/java/org/geoserver/catalog/impl/ModificationProxy.java
src/main/src/test/java/org/geoserver/catalog/impl/ModificationProxyTest.java

Utility method to alter wrappers underneath a modification proxy without losing any staged modifications.
Created to assist with #2771 but it turned out to not be needed there.  Still potentially useful though.

ModificationProxy.rewrap

---

src/platform/src/main/java/org/geoserver/platform/ModuleStatusImpl.java
src/platform/src/main/java/org/geoserver/platform/RenderingEngineStatus.java
src/platform/src/test/java/org/geoserver/platform/RenderingEngineStatusTest.java
src/web/core/src/test/java/org/geoserver/web/admin/StatusPageTest.java

See: https://osgeo-org.atlassian.net/browse/GEOS-8305
Adds a version lookup that searches the pom.properties for a matching artifactId and retrieves the version.
This lookup requires reading every pom.properties on the classpath, and as such is done on demand so as to not impact startup time (it takes somewhere on the order of 1 second on a default install, but even so).
I'm not particularly happy with this solution, but the current implementation of ModuleStatus does not include any information that can be used to associate it with a class or package from the module it describes. Consequently, any better solutions I can think of would require an API change.
The test was added in StatusPageTest.java so that the gs-main module will actually be compiled as a jar when the test runs (an …

[GEOS-8305] Fix module status version lookup

---

doc/en/developer/source/policies/committing.rst
src/release/installer/win/GeoServerEXE.nsi

Fixes regarding the following issue:
[GEOS-8683] Windows Installation issue - upgrading GeoServer results in corrupt data_dir
[GEOS-8697] Remove language warnings during Windows setup compilation
[GEOS-8698] Windows Installer: Remove 'work' folder when uninstalling
[GEOS-8712] GeoServer Developer documentation contains invalid links to contributor agreements

Multiple Windows Installer issues + developer documentation

---

doc/en/developer/source/policies/community-process.rst
doc/en/developer/source/release-guide/index.rst

For an upcoming GSIP.
Also includes some other minor release process changes discovered during the 2.13-beta release.
See also: https://github.com/geotools/geotools/pull/1811

Changing release process - create new branch during beta instead of RC

---

doc/en/user/source/security/usergrouprole/usergroups.rst

The Java term is speaking of the `java.security.Principal` interface

correct spelling from principle to principal

---

src/community/geofence-server/src/main/java/org/geoserver/geofence/internal/InternalUserResolver.java

Not finding a matching user is an expected case, not worth a WARNING log message.
Also fixed a typo

Reduce non-warning message to FINER and fix typo

---

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/listener/RestoreJobExecutionListener.java
src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/tasklet/FinalizeRestoreTasklet.java
src/community/backup-restore/core/src/main/resources/applicationContext.xml

Similar to #2770 this PR moves the final catalog reload/reset into a Spring batch tasklet instead of the afterJob call. This ensures that the restore job is fully finalized before reporting complete, which makes it easier for clients/scripts to do work after doing the restore.

Move the catalog reload/reset to a final Spring batch step. 

---

src/pom.xml

https://osgeo-org.atlassian.net/browse/GEOS-8729

[GEOS-8729] MongoDB extension descriptor missing in the main pom.xml

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/StationsMockData.java

https://osgeo-org.atlassian.net/browse/GEOS-8724
I could not reproduce the original issue locally, this PR does two things:
- if an something bad happens when removing the tests temp directory, the exception is logged and no exception is throw
- the tests root directory is not shared anymore between instances

[GEOS-8724] Intermittent build failure in NamespacesWfsTest

---

src/pom.xml

https://osgeo-org.atlassian.net/browse/GEOS-8729

[GEOS-8729] MongoDB extension descriptor missing in the main pom.xml (backport 2.13.x)

---

src/pom.xml

https://osgeo-org.atlassian.net/browse/GEOS-8729

[GEOS-8729] MongoDB extension descriptor missing in the main pom.xml (backport 2.12.x)

---

src/gwc/src/main/java/org/geoserver/gwc/controller/GwcWmtsRestUrlHandlerMapping.java
src/gwc/src/main/resources/applicationContext.xml
src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java

*** Depends on this GWC PR https://github.com/GeoWebCache/geowebcache/pull/644 ***
https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-8707?filter=myopenissues
GWS WMTS service can be invoked using a REST API, which means that this REST API should take into account virtual services logic.
To implement this, I basically end-up implementing a custom URL mapping that will take care of matching the correct controller when workspaces are involved. This will also take care of settling the correct local workspace and clean it.
Note, this PR adds this big function ``prefixWithWorkspaceName`` I tried to break it in several pieces but it just keep going more awkward and more complex to read ... handling layer groups, workspaces, virtual services dependent behavior is not …

[GEOS-8707] WMTS REST API is not compatible with local workspaces

---

src/extension/ogr/ogr-wps/src/test/java/org/geoserver/wps/ogr/WPSOgrTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8765
Fix is to accept either column name in the failing `assertTrue`.

[GEOS-8765] Undocumented GDAL 2.3.0 CSV output geometry column name change breaks WPSOgrTest

---

src/web/wms/src/main/resources/org/geoserver/wms/web/data/ol-load.ftl
src/wms/src/main/java/org/geoserver/wms/WMSServiceExceptionHandler.java
src/wms/src/main/java/org/geoserver/wms/map/AbstractOpenLayersMapOutputFormat.java
src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapOutputFormatTest.java

We can get at least this, it's not much, but better than a blank:

[GEOS-8768] OpenLayers preview do not report exceptions 'in image' anymore

---

src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/gwc/src/main/java/org/geoserver/gwc/layer/CatalogLayerEventListener.java
src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
src/gwc/src/test/java/org/geoserver/gwc/layer/CatalogLayerEventListenerTest.java

Fix CatalogLayerEventListener behavior:
- truncate layer tiles whe styles change
- don't remove the style parameter filter if it is empty
- simplify default style tile truncation
Add integration tests for tile truncation on style changes
https://osgeo-org.atlassian.net/browse/GEOS-8780

[GEOS-8780] Fix CatalogLayerEventListener handling of tile truncation

---

src/wfs/src/main/java/org/geoserver/wfs/FeatureSizeFeatureCollection.java
src/wfs/src/test/java/org/geoserver/wfs/FeatureCollectionDelegationTest.java

* The FeatureSizeFeatureCollection can now delegate visitors to underlying datastores.
https://osgeo-org.atlassian.net/browse/GEOS-8779
Signed-off-by: Jim Hughes <jnh5y@ccri.com>

GEOS-8779 Allow for the FeatureSizeFeatureCollection to delegate

---

src/community/nsg-profiles/pom.xml
src/community/pom.xml

https://osgeo-org.atlassian.net/browse/GEOS-8751
This PR changes will make ``nsg-profiles`` ``pom.xml`` file to be also published. 
When a maven command is issued inside the NSG profiles module directory both the WMTS and WFS profiles will be activated. Outside NSG profiles module directory each profile needs to be explicitly activated.

[GEOS-8751] Missing gs-nsg-profiles pom in maven repository

---

src/community/nsg-profiles/pom.xml
src/community/pom.xml

Backport of PR https://github.com/geoserver/geoserver/pull/2919.

[GEOS-8751] Missing gs-nsg-profiles pom in maven repository (backport 2.13.x)

---

src/platform/src/test/java/org/geoserver/platform/resource/FileWrapperResourceTheoryTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8789

[GEOS-8789] FileWrapperResourceTheoryTest fails if java.io.tmpdir is relative

---

src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/gwc/src/test/java/org/geoserver/gwc/GWCDataSecurityTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8550
NPE only occurs when you make a workspace-virtual WMS request against a workspaced layer group and all of the following are true:
- Caching is enabled
- GWC Data Security is enabled
- Direct WMS integration is enabled
Caused because LocalWorkspace has a NameDequalifyingProxy which will strip off the workspace if we just call prefixedName

[GEOS-8550] Fix GWC Secrutiy NPE for layer group request

---

src/extension/wps/wps-core/src/test/java/org/geoserver/wps/InputLimitsTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8801

[GEOS-8801] InputLimitsTest ignores java.io.tmpdir

---

src/extension/importer/core/src/main/java/org/geoserver/importer/ImportContext.java
src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/ImporterIntegrationTest.java

When an error occurs during import initialization, the error is caught and the context state is set to INIT_ERROR.
However, later in initialization, Importer.changed() is called, which resets the state, overwriting this value with PENDING. This has been fixed, and Importer will now correctly report the INIT_ERROR state.
For some background info, see https://osgeo-org.atlassian.net/browse/GEOS-8563
Note - This doesn't really fix GEOS-8563, but does make it more clear that importer is in an error state when the issue occurs.

[GEOS-8563] Importer should correctly report INIT_ERROR state

---

src/pom.xml

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8810
**Depends on https://github.com/GeoWebCache/geowebcache/pull/666**

[GEOS-8810] Upgrade commons-io dependency to 2.6

---

src/main/src/test/java/org/geoserver/data/test/SystemTestData.java

https://osgeo-org.atlassian.net/browse/GEOS-8814
Fix for a pre-existing loop failure condition off-by-one error found while backporting.

[GEOS-8814] Fix loop failure condition off-by-one error

---

src/pom.xml

Backport of https://github.com/geoserver/geoserver/pull/2951

[GEOS-8810] Upgrade commons-io dependency to 2.6 (backport 2.12.x)

---

src/pom.xml

Backport of https://github.com/geoserver/geoserver/pull/2951

[GEOS-8810] Upgrade commons-io dependency to 2.6 (backport 2.13.x)

---

src/pom.xml

https://osgeo-org.atlassian.net/browse/GEOS-8819

[GEOS-8819] Upgrade json-lib dependency to 2.4

---

src/pom.xml

Backport of https://github.com/geoserver/geoserver/pull/2963

[GEOS-8819] Upgrade json-lib dependency to 2.4 (backport 2.13.x)

---

src/pom.xml

Backport of https://github.com/geoserver/geoserver/pull/2963

[GEOS-8819] Upgrade json-lib dependency to 2.4 (backport 2.12.x)

---

src/extension/excel/src/main/java/org/geoserver/wfs/response/ExcelCellStyles.java
src/pom.xml

Tested this by deploying an updated geoserver war + extension to tomcat; hitting the two standard URLs (per extension README, one is .xls and the other .xlsx), and opening them in LibreOffice. Data looked reasonable, headings were bolded as expected.

[GEOS-8816] Update Apache POI dependency to 3.17.

---

src/extension/security/cas/pom.xml
src/extension/security/cas/src/main/java/org/geoserver/security/cas/GeoServerCasAuthenticationFilter.java
src/pom.xml
src/security/security-tests/src/test/java/org/geoserver/security/BruteForceAttackTest.java

Tested by booting on tomcat8, logged in OK.
Made sure the CAS extension unpacked OK, tomcat8 restarted afterwards, and that the CAS authentication filter showed up - couldn't test whether it worked correctly, since I don't have a CAS server.
I did see one problem where  geoserver (presumably spring-security) complained about a URL with a ";" character being potentially malicious, but couldn't reproduce and nothing in the logs. More testing would be appreciated.

[GEOS-8821] Upgrade spring-security to 4.2.7-RELEASE.

---

doc/en/user/source/configuration/globalsettings.rst
src/main/src/main/java/org/geoserver/config/impl/GeoServerInfoImpl.java
src/main/src/main/java/org/geoserver/ows/ProxifyingURLMangler.java
src/main/src/main/java/org/geoserver/ows/QuickTemplate.java
src/main/src/test/java/org/vfny/geoserver/util/URLProxifyingTest.java

- Fixed the name of the "Forwarded" header
- Added user documentation (English only)
Dee discussion: https://github.com/geoserver/geoserver/commit/3c05cfb84151fbcdf5bde6d4d42faa4d743673e9#commitcomment-29588575

[GEOS-8240] Fix "Forwarded" header name, add user docs

---

src/community/wfs3/src/main/java/org/geoserver/wfs3/response/AbstractHTMLResponse.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/response/FreemarkerTemplateSupport.java
src/community/wps-remote/src/main/java/org/geoserver/wps/remote/plugin/output/XMPPRawDataOutput.java
src/extension/monitor/core/src/main/java/org/geoserver/monitor/auditlog/AuditLogger.java
src/extension/monitor/core/src/test/java/org/geoserver/monitor/auditlog/AuditTemplateLoaderTest.java
src/gwc/src/main/java/org/geoserver/gwc/layer/CatalogLayerEventListener.java
src/gwc/src/main/java/org/geoserver/gwc/layer/DynamicGridSubset.java
src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
src/gwc/src/test/java/org/geoserver/gwc/layer/GeoServerTileLayerTest.java
src/main/src/main/java/org/geoserver/template/FeatureWrapper.java
src/main/src/main/java/org/geoserver/template/GeoServerTemplateLoader.java
src/main/src/main/java/org/geoserver/template/TemplateUtils.java
src/main/src/test/java/org/geoserver/template/FeatureWrapperTest.java
src/rest/src/main/java/org/geoserver/rest/RestBaseController.java
src/web/core/src/main/java/org/geoserver/web/LoginFormHTMLInclude.java
src/web/core/src/main/java/org/geoserver/web/util/WebUtils.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/GridSubsetsEditor.java
src/web/wms/src/main/java/org/geoserver/wms/web/data/OpenLayersPreviewPanel.java
src/wfs/src/main/java/org/geoserver/wfs/response/ShapeZipOutputFormat.java
src/wms/pom.xml
src/wms/src/main/java/org/geoserver/wms/decoration/TextDecoration.java
src/wms/src/main/java/org/geoserver/wms/featureinfo/FeatureTemplate.java
src/wms/src/main/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormat.java
src/wms/src/main/java/org/geoserver/wms/map/AbstractOpenLayersMapOutputFormat.java
src/wms/src/test/java/org/geoserver/wms/featureinfo/FeatureDescriptionTemplateTest.java
src/wms/src/test/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormatTest.java
src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapTemplateTest.java
src/wms/src/test/resources/org/geoserver/wms/featureinfo/test_execute.ftl

This retains the feature of being able to override the dynamic extent with a static one as from reading the code this appears to be intentional, and is a useful feature, if not one accessible by the UI.  
I did update the UI to indicate that this is happening  (GEOS-8803).  The mechanism for doing this is a bit crude as it uses an if statement when building the Wicket UI rather than a more proper Converter object.  If we ever make this editable via the UI, this will need to change, but it's good enough for now.
Depends on https://github.com/GeoWebCache/geowebcache/pull/664

[GEOS-8778, GEOS-8803] Keep track of whether gridsubset extent is dynamic

---

doc/en/user/source/extensions/printing/configuration.rst

the parameters of the YAML were surrounded by quotes (`"`), it would be nice to visualize these parameters like code snippets

Fix typo and make formatting nice

---

doc/en/developer/source/programming-guide/wps-services/implementing.rst

Added osgeo dependency to fix Maven build. 
These were not downloaded before: 
*The following artifacts could not be resolved: jgridshift:jgridshift:jar:1.0, javax.media:jai_imageio:jar:1.1, javax.media:jai_codec:jar:1.1.3, javax.media:jai_core:jar:1.1.3: Could not find artifact jgridshift:jgridshift:jar:1.0 in boundless*
geoserver-users mail list message linked to this:
https://sourceforge.net/p/geoserver/mailman/message/36360921/

Add osgeo dependency to implementing wps tutorial

---

src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoPackageProcessRequestPPIO.java
src/community/geopkg/src/test/java/org/geoserver/geopkg/wps/gs/GeoPackageProcessTest.java

This pull request updates GeoPackageProcessRequestPPIO to set the EntityResolver on the Parser before using it to validate the input XML and it is dependent on the GeoTools pull request https://github.com/geotools/geotools/pull/1965 which has already been merged.
This pull request can be backported to 2.12.x and 2.13.x.

Updated GeoPackage process to set EntityResolver before validating XML.

---

src/wfs/src/main/java/org/geoserver/wfs/StoredQuery.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/StoredQueryTest.java

This pull request ensures that the EntityResolver is set on the DocumentBuilder before using it to validate the XML sent in WFS CreateStoredQuery requests.
This pull request can be backported to 2.13.x and 2.12.x.

Updated WFS CreateStoredQuery to set EntityResolver before validating XML.

---

src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureTest.java

This pull request updates the OWS Dispatcher to set the EntityResolver on the DocumentBuilder before using it to parse SOAP requests.  Reflection is used here because the EntityResolverProvider class is in the gs-main module.  This pull request also fixes a race condition parsing SOAP requests since DocumentBuilder instances are not thread-safe.
This pull request can be backported to 2.13.x and 2.12.x

Set the EntityResolver in OWS Dispatcher before parsing SOAP requests.

---

src/extension/wps/web-wps/src/main/java/org/geoserver/wps/web/ComplexInputPanel.java
src/extension/wps/web-wps/src/main/java/org/geoserver/wps/web/WPSExecuteTransformer.java
src/extension/wps/web-wps/src/main/java/org/geoserver/wps/web/WPSRequestBuilder.java
src/extension/wps/web-wps/src/main/java/org/geoserver/wps/web/WPSRequestBuilderPanel.java
src/extension/wps/web-wps/src/test/java/org/geoserver/wps/web/WPSRequestBuilderTest.java
src/extension/wps/web-wps/src/test/java/org/geoserver/wps/web/secret.txt

This pull request ensures that the EntityResolver is set on the WPSExecuteTransformer object before using the transformer to builder the Execute XML and updates WPSExecuteTransformer to use the EntityResolver when internally parsing text as XML.  WPSRequestBuilderPanel contained unused code to build the Execute XML that was removed.
This pull request can be backported to 2.13.x and probably 2.12.x.

Set the EntityResolver in the WPS Request Builder when building the Execute XML.

---

src/restconfig/src/main/java/org/geoserver/rest/catalog/MapXMLConverter.java
src/restconfig/src/test/java/org/geoserver/rest/security/AccessControllersTest.java
src/restconfig/src/test/resources/org/geoserver/rest/security/secret.txt

This pull request updates MapXMLConverter to set the EntityResolver on the SAXBuilder before using it to parse the input XML.

Set the EntityResolver in MapXMLConverter before parsing XML.

---

src/community/backup-restore/core/pom.xml
src/community/geogig/pom.xml
src/community/nsg-profiles/nsg-wfs-profile/pom.xml
src/community/wmts-multi-dimensional/pom.xml
src/extension/vectortiles/pom.xml
src/extension/ysld/pom.xml
src/ows/pom.xml
src/pom.xml

https://osgeo-org.atlassian.net/browse/GEOT-6066
GeoServer changes required to build with https://github.com/geotools/geotools/pull/1986 . Expected to fail until https://github.com/geotools/geotools/pull/1986 is merged.

[GEOT-6066] Remove junit and xmlunit from binary product

---

src/community/gwc-s3/src/main/java/org/geoserver/gwc/web/blob/S3BlobStorePanel.html
src/community/gwc-s3/src/main/java/org/geoserver/gwc/web/blob/S3BlobStorePanel.java
src/web/gwc/src/main/resources/GeoServerApplication.properties

Depends on https://github.com/GeoWebCache/geowebcache/pull/674

Support non-amazon s3 compatible servers in GWC S3 blobstore

---

src/security/jdbc/pom.xml
src/web/security/jdbc/pom.xml

This pull request adds the test scope to a test dependency to prevent it and its transitive test dependencies from getting into the released GeoServer WAR file.
This pull request can be backported to 2.13.x.

[GEOS-8877] Added test scope to gs-sec-jdbc test dependency.

---

src/kml/src/main/java/org/geoserver/kml/decorator/PlacemarkNameDecoratorFactory.java
src/kml/src/main/java/org/geoserver/kml/decorator/PlacemarkStyleDecoratorFactory.java
src/kml/src/main/java/org/geoserver/kml/icons/IconPropertyExtractor.java
src/kml/src/main/java/org/geoserver/kml/icons/Icons.java
src/kml/src/test/java/org/geoserver/kml/decorator/PlacemarkStyleDecoratorTest.java
src/kml/src/test/java/org/geoserver/kml/icons/IconPropertiesTest.java
src/kml/src/test/java/org/geoserver/kml/icons/IconTestSupport.java

See [GEOS-8885](https://osgeo-org.atlassian.net/browse/GEOS-8885) for details.
Will need to check for code that assumes expressions are provided:

ysld generate styles break kml output formats [GEOS-8885]

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/AbstractAppSchemaTestSupport.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NamespacesWfsTest.java
src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/stations_two_queries.xml
src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/stations_two_queries_1.1.xml
src/wfs/src/main/java/org/geoserver/wfs/xml/FeatureTypeSchemaBuilder.java

Fix and tests for [GEOS-8799] "WFS GetFeature response contains NULL namespaces for App-Schema complex features when multiple queries are used".
https://osgeo-org.atlassian.net/browse/GEOS-8799

[GEOS-8799] NULL namespace prefixes used in AppSchema WFS GetFeature responses

---

src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayersPage.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/CachedLayersPageTest.java

Added buildURL call when building the link to the tiled layers preview.
Made during the foss4g2018 code sprint with [mirandadam](https://github.com/mirandadam)

[GEOS-7653] tiled layers preview does not use Proxy Base URL

---

src/gwc/src/test/java/org/geoserver/gwc/RESTIntegrationTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8895
Test case for https://github.com/GeoWebCache/geowebcache/pull/683 (since the error is only in embedded GWC)

[GEOS-8895] Integration test for embedded GWC reload endpoint

---

src/community/jms-cluster/activemqBroker/pom.xml

spring-asm was merged into spring-core with the release of Spring 3.2.0, and should no longer be included as a dependency.

Remove spring-asm dependency from jms-cluster

---

src/release/RUNNING.txt

Seems that the text in RUNNING.txt was written for older
versions of jetty.
In current version you need to change the portnummer in start.ini
if I'm correct... Well I happened to need to do it, can THIS worked,
the 8080 is not available anymore in any file in etc folder

Fix doc about changing jetty port

---

src/wms/src/main/java/org/geoserver/wms/GetLegendGraphicRequest.java
src/wms/src/main/java/org/geoserver/wms/legendgraphic/BufferedImageLegendGraphicBuilder.java
src/wms/src/main/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReader.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetLegendGraphicTest.java

Fix and test for GEOS-7636 "GetLegendGraphic ignores the OnlineResource configured in the style for raster layers"
This PR modify some nested conditional logic that prevented to show the correct OnlineResource and always returned the standard blue square.  Now GetLegendGraphic shows the proper image.
https://osgeo-org.atlassian.net/browse/GEOS-7636

[GEOS-7636] GetLegendGraphic online resource is ignored on rasters

---

src/wms/src/main/java/org/geoserver/wms/GetLegendGraphicRequest.java
src/wms/src/main/java/org/geoserver/wms/legendgraphic/BufferedImageLegendGraphicBuilder.java
src/wms/src/main/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReader.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetLegendGraphicTest.java

Fix and test for GEOS-7636 "GetLegendGraphic ignores the OnlineResource configured in the style for raster layers"
This PR modify some nested conditional logic that prevented to show the correct OnlineResource and always returned the standard blue square. Now GetLegendGraphic shows the proper image.
https://osgeo-org.atlassian.net/browse/GEOS-7636

[GEOS-7636] GetLegendGraphic online resource is ignored on rasters 2.14.x backport

---

src/web/core/src/main/java/org/geoserver/web/css/geoserver.css
src/web/core/src/main/resources/org/apache/wicket/extensions/markup/html/form/palette/Palette.html

See https://osgeo-org.atlassian.net/browse/GEOS-8936
This fix modifies the Palette.html template used by wicket, wrapping the each of the `<select>` elements in a div so that a horizontal scroll can be added (the select element does *not* support horizontal scroll on its own). Note: Wicket, and by extension the original Palette.html, is licensed under Apache 2.0, which is compatible with GPL and permits modified files to be relicensed.
Limitations:
* If you have a wide style name such that horizontal scrolling is required, the vertical scroll bar for the select will start off outside the visible region of the `<select>`. This is a limitation of how the select element works.
* If you have an especially large style name, the default style select box higher up on the page will overflow the …

[GEOS-8936] Allow Additional Styles select boxes to scroll

---

src/main/src/main/java/org/geoserver/config/util/OneWayPackageAliasingMapper.java
src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
src/main/src/test/java/org/geoserver/config/util/XStreamPersisterTest.java
src/main/src/test/resources/org/geoserver/config/old_jts_binding.xml

For https://osgeo-org.atlassian.net/browse/GEOS-8929
This change only affects reading; writing output is unchanged.
It is possible to alter this so that writing is likewise aliased in order to address [GEOS-8886](https://osgeo-org.atlassian.net/browse/GEOS-8886); see discussion in that ticket.

[GEOS-8929] Alias old com.vividsolutions.jts.geom.* to new org.locationtech.jts.geom.* in XStream reader

---

doc/en/user/source/installation/upgrade.rst

https://osgeo-org.atlassian.net/browse/GEOS-8886
See also: https://github.com/geoserver/geoserver/pull/3102 (Which has the actual REST api documentation changes associated with this issue)

[GEOS-8886] Add migration guide for REST API Change due to JTS Upgrade

---

doc/en/user/source/styling/sld/reference/pointsymbolizer.rst
doc/fr/user/source/styling/sld-reference/pointsymbolizer.rst

According to the [StyledLayerDescriptor.xsd](http://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd) the element `<WellKnownName>` is not required in a `<Mark>` (see also excerpt below) - its `minOccurs` is set to `0`. The documentation was updated accordingly.
Excerpt from StyledLayerDescriptor.xsd:
```
<xsd:element name="Mark">
<xsd:annotation>
<xsd:documentation>
A "Mark" specifies a geometric shape and applies coloring to it.
</xsd:documentation>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="sld:WellKnownName" minOccurs="0"/>
<xsd:element ref="sld:Fill" minOccurs="0"/>
<xsd:element ref="sld:Stroke" minOccurs="0"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
```

Set WellKnownName as optional

---

src/wms/src/main/java/org/geoserver/wms/capabilities/DimensionHelper.java

We are using GeoServer to display a large number of GeoTIFFs using ImageMosaic data stores. The data has several dimensions (time and custom). We are adding new data to these stores periodically and the goal is to be able to display years of data (millions of granules). We have encountered performance problems with the WMS GetCapabilities operation. It is most noticeable when using Oracle database (or PostGIS with parameter WrapStore=true). We implemented changes which improved the performance for our use case significantly. We would like to publish these changes and hopefully merge them into the official repo.
Details:
our performance problems are caused by the queries for values and defaults for dimensions. The currently used queries vary depending on the selected presentation for the …

ImageMosaic GetCapabilities performance

---

src/community/oseo/oseo-core/src/test/resources/postgis.sql

Adding the missing index on the geometry attribute of the "granule". This can have a significant impact on systems with a great number of published granules

[GEOS-8945] Missing Spatial Index in OSEO Setup Instructions

---

doc/en/user/source/community/index.rst

The community modules have been disabled for a couple of years, this makes the docs consistent.

[GEOS-8955] Disable docs for Resumable REST and REST mapper.

---

src/main/src/main/java/org/geoserver/catalog/FeatureTypeInfo.java
src/main/src/main/java/org/geoserver/catalog/impl/FeatureTypeInfoImpl.java
src/main/src/main/java/org/geoserver/security/decorators/DecoratingFeatureTypeInfo.java
src/web/wfs/src/main/java/org/geoserver/wfs/web/publish/WFSLayerConfig.html
src/web/wfs/src/main/java/org/geoserver/wfs/web/publish/WFSLayerConfig.java
src/web/wfs/src/main/resources/GeoServerApplication.properties
src/web/wfs/src/test/java/org/geoserver/wfs/web/WFSLayerConfigTest.java
src/wfs/src/main/java/org/geoserver/wfs/WFSGetFeatureOutputFormat.java
src/wfs/src/main/java/org/geoserver/wfs/xml/GML2OutputFormat.java
src/wfs/src/main/java/org/geoserver/wfs/xml/GML3FeatureTransformer.java
src/wfs/src/main/java/org/geoserver/wfs/xml/GML3GeometryTranslator.java
src/wfs/src/main/java/org/geoserver/wfs/xml/GML3OutputFormat.java
src/wfs/src/test/java/org/geoserver/wfs/xml/GMLOutputFormatTest.java

Enables configuration of new formatting options introduced with GEOT-6119 for WFS GML output formats

GEOS-8935: introduced new coordinates formatting options for WFS GML output formats

---

src/gwc/src/main/java/org/geoserver/gwc/FakeHttpServletRequest.java
src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
src/gwc/src/test/java/org/geoserver/gwc/HttpRequestRecorderCallback.java
src/gwc/src/test/resources/gwc-integration-test.xml

**Backport of: https://github.com/geoserver/geoserver/pull/3126**
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8944

[GEOS-8944] GWC fails to cache tiles if GeoFence with source IP driven rules are used for authentication (backport 2.14.x)

---

src/gwc/src/main/java/org/geoserver/gwc/FakeHttpServletRequest.java
src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
src/gwc/src/test/java/org/geoserver/gwc/HttpRequestRecorderCallback.java
src/gwc/src/test/resources/gwc-integration-test.xml

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8944

[GEOS-8944] GWC fails to cache tiles if GeoFence with source IP driven rules are used for authentication

---

src/gwc/src/main/java/org/geoserver/gwc/FakeHttpServletRequest.java
src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
src/gwc/src/test/java/org/geoserver/gwc/HttpRequestRecorderCallback.java
src/gwc/src/test/resources/gwc-integration-test.xml

**Backport of: https://github.com/geoserver/geoserver/pull/3126**
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8944

[GEOS-8944] GWC fails to cache tiles if GeoFence with source IP driven rules are used for authentication (backport 2.13.x)

---

src/community/wfs3/src/main/java/org/geoserver/wfs3/DefaultWebFeatureService30.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/TileDataRequest.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/TilingSchemeDescriptionRequest.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/WFS3Filter.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/WebFeatureService30.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/kvp/GetFeatureKvpRequestReader.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/kvp/TilingSchemeDetailKVPReader.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/response/BoundingBoxDocument.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/response/GetFeatureMapboxOutputFormat.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/response/TileMatrixDocument.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/response/TilingSchemeDescriptionDocument.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/response/TilingSchemeDetailResponse.java
src/community/wfs3/src/main/resources/applicationContext.xml
src/community/wfs3/src/test/java/org/geoserver/wfs3/GetFeatureMapboxOutputFormatTest.java
src/community/wfs3/src/test/java/org/geoserver/wfs3/TilingSchemesTest.java

WFS 3 MapBox response on /items breaks georeferencing, this PR fix this issue.
Detail:
Currently the response encodes using the collection bbox, which might not be the one requested (can be smaller, can be larger). However the client only has the requested bbox to do referencing, so the encoding "area" must perfectly match the requested bbox.

Fix for WFS 3 MapBox response on /items breaking georeferencing

---

doc/en/user/source/production/container.rst

The GC documentation was a bit out of date regarding which GC's are currently default. Also added a small note to not combine different GC's when setting up a new GeoServer install. This should suite new users, which are unfamiliar with Java settings.

Updated garbage collector documentation

---

src/community/wfs3/src/main/java/org/geoserver/wfs3/response/TilingSchemeDescriptionDocument.java
src/community/wfs3/src/test/java/org/geoserver/wfs3/TilingSchemesTest.java

This PR fix the problem on tiling scheme description on no-US Locale JVM setting.  Now doubles format are always on Locale.US

Wfs3 tiling scheme description double format locale

---

src/restconfig/src/main/java/org/geoserver/rest/catalog/WorkspaceController.java
src/restconfig/src/test/java/org/geoserver/rest/catalog/WorkspaceTest.java

[https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-8870](https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-8870)
Fixed bug  error trying to rename workspace through rest api.
For tests:
curl -v --user admin:geoserver -X put -H "Content-Type: application/json" -d '{"workspace": {"name":"toppNew"}}' http://localhost:8080/geoserver/rest/workspaces/topp 
Before
< HTTP/1.1 403 Can't change name of workspace
After:
< HTTP/1.1 200 OK

GEOS-8870 error trying to rename workspace through rest api

---

doc/en/build.xml
doc/en/release/user.xml
doc/en/user/source/community/solr/optimize.rst
doc/en/user/source/data/app-schema/mongo-tutorial.rst
doc/en/user/source/data/app-schema/wms-support.rst
doc/en/user/source/rest/api/accesscontrol.rst
doc/en/user/source/rest/api/manifests.rst
doc/en/user/source/services/wfs/outputformats.rst
doc/en/user/source/services/wms/googleearth/tutorials/time/time.rst
doc/en/user/source/services/wms/reference.rst
doc/en/user/source/styling/css/cookbook/line.rst
doc/en/user/source/styling/css/cookbook/point.rst
doc/en/user/source/styling/css/cookbook/polygon.rst
doc/en/user/source/styling/css/directives.rst
doc/en/user/source/styling/css/examples/randomfills.rst
doc/en/user/source/styling/css/nested.rst
doc/en/user/source/styling/css/styledmarks.rst
doc/en/user/source/styling/css/transformation.rst
doc/en/user/source/styling/css/tutorial.rst
doc/en/user/source/styling/workshop/mbstyle/linestring.rst
doc/en/user/source/styling/workshop/mbstyle/mbstyle.rst
doc/en/user/source/styling/workshop/mbstyle/point.rst
doc/en/user/source/styling/workshop/ysld/done.rst

This makes use of the scss parser, which seems more tolerant. There are still a couple of cases that aren't parsed and we have no syntax highlighting, but they're minor.

[GEOS-8957] Clean up remaining doc warnings and switch configuration

---

src/extension/dxf/core/src/test/java/org/geoserver/wfs/response/DXFOutputFormatTest.java

This saves a couple of thousand lines in the test log output.

[GEOS-8967] Reduce verbosity of DXF tests.

---

src/extension/wps/web-wps/src/test/java/org/geoserver/wps/web/WPSExecuteTransformerTest.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/WPSXStreamLoaderTest.java

One case is just dumping what was read from the file, which is not useful.

[GEOS-8967] Reduce verbosity in WPS tests.

---

src/wms/src/main/java/org/geoserver/wms/map/png/PNGJWriter.java

Old PRs:
https://github.com/geoserver/geoserver/pull/3153
https://github.com/geoserver/geoserver/pull/3158
Doing multiple WMS GetMap requests, result on a message "Failed to encode the PNG" at Error level.
At ows dispatcher class the level is FINER.
@aaime commented on the old pull request:
A simple approach could be to just avoid logging and have the exception go up the chain, it will get logged by the Dispatcher if it's not a client stream aborted exception, e.g.:
} catch (Exception e) {
throw new ServiceException("Failed to encode the PNG", e);
}
I tested and it works fine.
It logs as a TRACE level as expected.
I create this new PR, because i can't do a change over the github interface without Format Errors when processing maven.

[GEOS-8958] - ClientStreamAbortedException should be logged at debug level

---

src/extension/libjpeg-turbo/src/main/java/org/geoserver/map/turbojpeg/TurboJpegImageWorker.java
src/extension/libjpeg-turbo/src/test/java/org/geoserver/map/turbojpeg/TurboImageWorkerTest.java

Depends on
https://github.com/geotools/geotools/pull/2095

[GEOS-8964]: Fix IllegalArgumentExcep on turboJPEG writing -bkp to 2.14.x

---

src/extension/libjpeg-turbo/src/main/java/org/geoserver/map/turbojpeg/TurboJpegImageWorker.java
src/extension/libjpeg-turbo/src/test/java/org/geoserver/map/turbojpeg/TurboImageWorkerTest.java

Depends on https://github.com/geotools/geotools/pull/2096

[GEOS-8964]: Fix IllegalArgumentExcep on turboJPEG writing - 2.13.x

---

src/pom.xml
src/release/ext-vectortiles.xml

The ring orientation fix has been done in the java-vector-tiles libraries, we just need to upgrade and handle the changed protobuf dependencies.

[GEOS-8974] Vector tiles ring orientations do not match the latest MVT spec

---

src/web/gwc/src/main/java/org/geoserver/gwc/web/gridset/GridSetBuilder.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/gridset/GridSetBuilderTest.java

GS-GWC web GUI sets wrong EPSG:4326 coordinate axis order for topLeftCorner when saving a GridSet, also doesn't check the CRS's axis order to configure on it.
As result of this we got a wrong coordinates axis order on WMS GetCapabilities TileMatrixSet -> topLeftCorner.
This PR adds a CRS's axis order check before set the axis configuration on GridSet on save.

[GEOS-8972] GS-GWC web GUI sets wrong EPSG:4326 coordinate axis order for topLeftCorner when saving a GridSet fix

---

src/extension/printing/pom.xml

Geoserver printing plugin (print-lib) leaves opened files
- upgrade to print-lib 2.1.3 with this problem already solved

fix [GEOS-8968] Geoserver printing plugin (print-lib) leaves opened files

---

src/extension/printing/pom.xml

Geoserver printing plugin (print-lib) leaves opened files
- upgrade to print-lib 2.1.3
merge from master

2.14.x - fix [GEOS-8968] Geoserver printing plugin (print-lib) leaves opened files

---

src/web/gwc/src/main/java/org/geoserver/gwc/web/gridset/GridSetBuilder.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/gridset/GridSetBuilderTest.java

GS-GWC web GUI sets wrong EPSG:4326 coordinate axis order for topLeftCorner when saving a GridSet, also doesn't check the CRS's axis order to configure on it.
As result of this we got a wrong coordinates axis order on WMS GetCapabilities TileMatrixSet -> topLeftCorner.
This PR adds a CRS's axis order check before set the axis configuration on GridSet on save.

[GEOS-8972] GS-GWC web GUI sets wrong EPSG:4326 coordinate axis order for topLeftCorner when saving a GridSet 2.14.x backport

---

src/extension/sldService/pom.xml

remove xom dependency that is unused and was raising warnings for jdk11

gt-sldservice fix

---

src/platform/src/main/java/org/geoserver/platform/RenderingEngineStatus.java
src/platform/src/test/java/org/geoserver/platform/RenderingEngineStatusTest.java

Providing slightly less information in this page in order to remove dependence on internals.

Remove JDK internals from rendering status panel

---

src/extension/vectortiles/src/main/java/org/geoserver/wms/mapbox/MapBoxTileBuilderFactory.java
src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/VectorTileBuilderFactory.java
src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/VectorTileMapOutputFormat.java
src/extension/vectortiles/src/test/java/org/geoserver/wms/vector/VectorTilesIntegrationTest.java

In practice, only MVT is interested in this, but because of how the paint area is set up it needed to be more generic, that's why I added it to the VTMOF.java interface.

[GEOS-8990] - Add an option to scale the vector tile size

---

doc/en/user/source/extensions/vectortiles/tutorial.rst

https://github.com/geoserver/geoserver/pull/3223 is incompatible with OL 3.17.1, works fine with OL 5.3.0
See also: https://github.com/GeoWebCache/geowebcache/pull/715

[GEOS-8990] Update docs with warning about OL incompatibilites

---

doc/en/user/source/extensions/vectortiles/tutorial.rst
src/extension/vectortiles/src/main/java/org/geoserver/wms/mapbox/MapBoxTileBuilderFactory.java
src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/VectorTileBuilderFactory.java
src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/VectorTileMapOutputFormat.java
src/extension/vectortiles/src/main/resources/GeoServerApplication.properties
src/extension/vectortiles/src/main/resources/org/geoserver/gwc/advertised_formats.properties
src/extension/vectortiles/src/test/java/org/geoserver/wms/vector/VectorTilesIntegrationTest.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/CachingOptionsPanel.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/GeoServerTileLayerEditor.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/GWCSettingsPageTest.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/LayerCacheOptionsTabPanelTest.java

Backport of https://github.com/geoserver/geoserver/pull/3175 + https://github.com/geoserver/geoserver/pull/3223 (Since the second one somewhat depends upon the first)
Depends upon https://github.com/GeoWebCache/geowebcache/pull/712

[GEOS-8971] + [GEOS-8990] (vectortiles fixes) - 2.14.x backport

---

doc/en/user/source/extensions/vectortiles/tutorial.rst
src/extension/vectortiles/src/main/java/org/geoserver/wms/mapbox/MapBoxTileBuilderFactory.java
src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/VectorTileBuilderFactory.java
src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/VectorTileMapOutputFormat.java
src/extension/vectortiles/src/main/resources/GeoServerApplication.properties
src/extension/vectortiles/src/main/resources/org/geoserver/gwc/advertised_formats.properties
src/extension/vectortiles/src/test/java/org/geoserver/wms/vector/VectorTilesIntegrationTest.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/CachingOptionsPanel.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/GeoServerTileLayerEditor.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/GWCSettingsPageTest.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/LayerCacheOptionsTabPanelTest.java

Backport of #3175 + #3223 (Since the second one somewhat depends upon the first)
Depends upon https://github.com/GeoWebCache/geowebcache/pull/713

[GEOS-8971] + [GEOS-8990] (vectortiles fixes) - 2.13.x backport

---

src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/VectorTileMapOutputFormat.java

As reported on list, with a single complex geometry (1.5 million points, australia shoreline) the speedup factor of swapping the ops is around 10 times, but even with a Natural Earth 10m admin units (provinces) it is still between 3 and 4 times faster, from an informal bench.
Seeding the NE admin units with the existing code, up to level 10, 16 threads, and blocking computation after a minute, shows each thread build like 3k tiles:
Swapping the operation and repeating gives around 11k tiles per thread instead:

[GEOS-9020] Vector tiles: clip before running topology preserving simplification

---

src/kml/src/main/java/org/geoserver/kml/utils/KMLFeatureAccessor.java
src/kml/src/test/java/org/geoserver/kml/KMLTest.java

2.14.x backport for https://github.com/geoserver/geoserver/pull/3236

[GEOS-9007][2.14.x] Fixed the KML output format ignoring the sortBy parameter when querying the records for a vector layer.

---

src/kml/src/main/java/org/geoserver/kml/utils/KMLFeatureAccessor.java
src/kml/src/test/java/org/geoserver/kml/KMLTest.java

2.13.x backport for https://github.com/geoserver/geoserver/pull/3236

[GEOS-9007][2.13.x] Fixed the KML output format ignoring the sortBy parameter when querying the records for a vector layer.

---

src/wms/src/main/java/org/geoserver/wms/WMSRequests.java
src/wms/src/test/java/org/geoserver/wms/WMSRequestsTest.java

2.14.x backport for https://github.com/geoserver/geoserver/pull/3234

[GEOS-9003][2.14.x] Fixed exception building KML network links for requests containing a layer group and CQL filter.

---

src/wms/src/main/java/org/geoserver/wms/WMSRequests.java
src/wms/src/test/java/org/geoserver/wms/WMSRequestsTest.java

2.13.x backport for https://github.com/geoserver/geoserver/pull/3234

[GEOS-9003][2.13.x] Fixed exception building KML network links for requests containing a layer group and CQL filter.

---

doc/en/user/source/extensions/sldservice/index.rst
src/extension/sldService/pom.xml
src/extension/sldService/src/main/java/org/geoserver/sldservice/rest/BaseSLDServiceController.java
src/extension/sldService/src/main/java/org/geoserver/sldservice/rest/ClassifierController.java
src/extension/sldService/src/main/java/org/geoserver/sldservice/rest/ImageReader.java
src/extension/sldService/src/main/java/org/geoserver/sldservice/rest/ReferencedEnvelopeConverter.java
src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/RasterSymbolizerBuilder.java
src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/ClassifierTest.java
src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/SLDServiceBaseTest.java
src/extension/sldService/src/test/java/org/geoserver/sldservice/utils/classifier/RasterSymbolizerBuilderTest.java
src/extension/sldService/src/test/java/org/geoserver/sldservice/utils/classifier/RulesBuilderTest.java
src/rest/src/main/java/org/geoserver/rest/RestConfiguration.java

* Use histogram based operations, instead of collecting all possible values from the raster
* If the raster is too big, subsample it
* Allow the caller to define a significant area of interest and work on it instead of using the full extent (bbox)

[GEOS-9034] Have SLDService raster classification work against large raster datasets

---

doc/en/developer/source/quickstart/intellij.rst

Having issues getting Geoserver to build and run on Intellij using Windows 10.  After writing to the dev mailing list, it was suggested by Andrea Aime that I create a pull request to document how to fix the issues.

Add directions on building and running on windows

---

src/extension/app-schema/app-schema-mongo-test/src/test/resources/mappings/stations.xml
src/extension/app-schema/app-schema-mongo-test/src/test/resources/schemas/stations.xsd

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-9027

[GEOS-9027] MongoDB complex store iterator enters in an infinite loop if no ID is defined (backport 2.13.x)

---

src/extension/app-schema/app-schema-mongo-test/src/test/resources/mappings/stations.xml
src/extension/app-schema/app-schema-mongo-test/src/test/resources/schemas/stations.xsd

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-9027

[GEOS-9027] MongoDB complex store iterator enters in an infinite loop if no ID is defined (backport 2.14.x)

---

src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.java
src/web/demo/src/test/java/org/geoserver/web/demo/MapPreviewPageTest.java

This PR fix a bug related to layer groups preview hiding WMS and WFS preview links since Resource doesn't exists for them.

GEOS-9033 Allow configuring services on a per layer basis - Layer Group preview fix

---

src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/PipelineBuilder.java

Topology preservation rules are there for polygons, but I don't see any for lines

[GEOS-9045] Vector tiles module: avoid using TopologyPreservingSimplifier for lines

---

doc/en/user/source/styling/workshop/ysld/done.rst
doc/en/user/source/styling/workshop/ysld/point.rst
doc/en/user/source/styling/workshop/ysld/polygon.rst
doc/en/user/source/styling/ysld/reference/symbolizers/text.rst

Changed "x-label-priority" and "x-labelPriority" in the YSLD documentation to "priority".  Also, fixed an instance where "x-max-displacement" was being used instead of "x-maxDisplacement".

Fixed YSLD doc for priority labeling.

---

src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java
src/main/src/test/java/org/geoserver/catalog/impl/CatalogBuilderTest.java

[GEOS-8973](https://osgeo-org.atlassian.net/browse/GEOS-8973)
This adds CRS lookup to the REST coverage handler to avoid ArrayIndexOutOfBounds exceptions when the source files NativeCRS is missing identifiers.

[GEOS-8973] add srs lookup to REST coverage handler

---

src/extension/printing/pom.xml
src/pom.xml

Printing plugin upgrade version of JTS from vividsolutions to locationtech.
Mapfish print 2.1.4 released:
https://github.com/mapfish/mapfish-print/pull/772

GEOS-9051 Printing plugin upgrade version of JTS from vividsolutions to locationtech

---

src/wcs1_0/src/main/java/org/geoserver/wcs/DefaultWebCoverageService100.java
src/wcs1_0/src/test/java/org/geoserver/wcs/CustomDimensionsTest.java
src/wcs1_0/src/test/java/org/geoserver/wcs/DynamicDimensionsTest.java
src/wcs1_0/src/test/java/org/geoserver/wcs/GetCoverageTest.java
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCSDimensionsSubsetHelper.java
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/xml/GetCoverageTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-9084
This pull request makes custom dimension names in WCS 1.0.0 and 2.0.1 GetCoverage requests case insensitive to be consistent with time and elevation (WCS 1.1.1 has no custom dimension support).  The WCS 1.0 GetCoverageTest was modified to demonstrate that elevation is already case insensitive.  The WCS 2.0 GetCoverageTest already has tests that use both "time" and "Time" and both "elevation" and "Elevation" so there was no need to modify any tests to demonstrate that those dimension names are already case insensitive.
Rather than rejecting it as an invalid axis label, GeoServer currently returns the coverage using the default custom dimension value instead of the requested value for WCS 2.0.1 GetCoverage requests with a custom dimension …

[GEOS-9084] Made custom dimension names in WCS GetCoverage requests case insensitive.

---

src/community/jdbcconfig/src/main/resources/org/geoserver/jdbcconfig/internal/initdb.postgres.sql

This pull requests removes duplicate database indexes on the jdbcconfig object, type and property_type tables since PostgreSQL automatically creates indexes for primary keys.
https://www.postgresql.org/docs/current/indexes-unique.html
This pull request is related to https://github.com/geoserver/geoserver/pull/3294
https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-9055

[GEOS-9055] JDBCConfig - duplicate database index

---

doc/en/user/source/data/app-schema/joining.rst
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SimpleAttributeFeatureChainWfsTest.java

Is known that OR queries are difficult to optimize for postgresql and are usually slow.
The fix for slow queries with OR involved is using UNION queries, so we need optimize certain complex subqueries. The slow appschema subquery involved is that generated by NestedFilterToSQL class so we need to change the use of OR clause in the root condition for UNION queries.
Since this performance issue affect postgresql, the fix should be isolated for this datasource only, and adding a system property for disable.
We'll need execute online tests with postgresql and geoserver-appschema with new improvement enabled and disabled.
https://github.com/geotools/geotools/pull/2225

[GEOS-9088] Appschema OR performance improvement on postgresql (2.14.x backport)

---

src/community/jdbcconfig/src/main/resources/org/geoserver/jdbcconfig/internal/initdb.postgres.sql

2.14.x backport for https://github.com/geoserver/geoserver/pull/3294 and https://github.com/geoserver/geoserver/pull/3316

[GEOS-9055][2.14.x] JDBCConfig - duplicate database index

---

src/wcs1_0/src/main/java/org/geoserver/wcs/DefaultWebCoverageService100.java
src/wcs1_0/src/test/java/org/geoserver/wcs/CustomDimensionsTest.java
src/wcs1_0/src/test/java/org/geoserver/wcs/DynamicDimensionsTest.java
src/wcs1_0/src/test/java/org/geoserver/wcs/GetCoverageTest.java
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCSDimensionsSubsetHelper.java
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/xml/GetCoverageTest.java

2.14.x backport for https://github.com/geoserver/geoserver/pull/3309

[GEOS-9084][2.14.x] Made custom dimension names in WCS GetCoverage requests case insensitive.

---

src/main/src/main/java/org/geoserver/security/GeoServerSecurityManager.java
src/web/security/core/src/main/java/org/geoserver/security/web/SecurityHomePageContentProvider.java
src/web/security/core/src/test/java/org/geoserver/security/web/SecurityHomePageContentProviderTest.java

2.14.x backport for https://github.com/geoserver/geoserver/pull/3308

[GEOS-9083][2.14.x] Added back missing default master password warning.

---

doc/en/user/source/styling/sld/reference/rastersymbolizer.rst
src/wms/src/main/java/org/geoserver/wms/legendgraphic/Cell.java
src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendUtils.java
src/wms/src/test/java/org/geoserver/wms/legendgraphic/AbstractLegendGraphicOutputFormatTest.java

2.14.x backport for https://github.com/geoserver/geoserver/pull/3307

[GEOS-9081][2.14.x] Allow expressions in ColorMapEntry labels for GetLegendGraphic.

---

doc/en/user/source/data/app-schema/joining.rst
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SimpleAttributeFeatureChainWfsTest.java

Is known that OR queries are difficult to optimize for postgresql and are usually slow.
The fix for slow queries with OR involved is using UNION queries, so we need optimize certain complex subqueries. The slow appschema subquery involved is that generated by NestedFilterToSQL class so we need to change the use of OR clause in the root condition for UNION queries.
Since this performance issue affect postgresql, the fix should be isolated for this datasource only, and adding a system property for disable.
We'll need execute online tests with postgresql and geoserver-appschema with new improvement enabled and disabled.
Depends on geotools PR:
https://github.com/geotools/geotools/pull/2220

[GEOS-9088] Appschema OR performance improvement on postgresql
