geoserver/geoserver

src/wms/src/main/java/org/geoserver/wms/GetMap.java

Added a call to SimplifyingFeatureVisitor around Filters.and to prevent "Filter.INCLUDE AND Filter.INCLUDE"

WMS GetMap - Simplify Filters before creating query

---

src/extension/wcs2_0-eo/core/src/main/java/org/geoserver/wcs2_0/eo/kvp/WCS20DescribeEOCoverageSetRequestReader.java
src/wcs1_1/src/main/java/applicationContext.xml
src/wcs1_1/src/test/java/org/geoserver/wcs/GetCapabilitiesTest.java
src/wcs1_1/src/test/java/org/geoserver/wcs/kvp/SectionsKvpParserTest.java
src/wcs2_0/src/main/java/applicationContext.xml
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/kvp/SectionsKvpParser.java
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/SectionsKvpParserTest.java

Backport on 2.6.x branch of the fix for JIRA: https://jira.codehaus.org/browse/GEOS-6807

[GEOS-6807] WCS GetCapabilties requests with Sections parameter throws an exception (Backport 2.6.x)

---

src/kml/src/test/java/org/geoserver/kml/KMLSuperOverlayTest.java
src/kml/src/test/java/org/geoserver/kml/KMLTest.java

Due to epsg database upgrade.
This pull request depends on geotools/geotools#687

Laxed some floating point assertions to account for minor reprojection changes.

---

src/community/geopkg/src/main/java/org/geoserver/geopkg/GeoPackageGetFeatureOutputFormat.java
src/community/geopkg/src/main/java/org/geoserver/geopkg/wps/GeoPackageProcess.java
src/community/geopkg/src/test/java/org/geoserver/geopkg/GeoPackageGetFeatureOutputFormatTest.java
src/community/geopkg/src/test/java/org/geoserver/geopkg/wps/gs/GeoPackageProcessTest.java

! Depends on https://github.com/geotools/geotools/pull/637

Geopackage: write spatial index in process & wfs

---

doc/en/user/source/services/wms/vendor.rst
src/kml/src/main/java/org/geoserver/kml/KMLReflector.java
src/kml/src/main/java/org/geoserver/kml/builder/SimpleNetworkLinkBuilder.java
src/kml/src/main/java/org/geoserver/kml/builder/SuperOverlayNetworkLinkBuilder.java
src/kml/src/test/java/org/geoserver/kml/KMLReflectorTest.java

Added visibility and interval refresh support to KML as new format_options parameters
Added handling for layer labels and descriptions in SuperOverlay.  Added unit test coverage for all new capabilities. Added explanation of new format_options parameters to vendor parameters page
https://jira.codehaus.org/browse/GEOS-6801

[GEOS-6801] Added improved naming and description details for KML network links

---

src/community/dds/src/main/java/org/geoserver/wms/worldwind/BilMapResponse.java
src/community/dds/src/test/java/org/geoserver/wms/worldwind/BilTest.java
src/web/app/pom.xml

This is a reissue of pull request #616, opened by @gberaudo. I applied the two commits in the original pull request to the master branch, with some small modification due to changes in master since the pull request was issued. I also added a unit test and removed some commented out dead code.

Return empty BIL image on non intersecting box.

---

src/wcs1_0/src/main/java/org/geoserver/wcs/kvp/Wcs10GetCapabilitiesRequestReader.java
src/wcs1_0/src/test/java/org/geoserver/wcs/GetCapabilitiesTest.java
src/wcs1_1/src/main/java/org/geoserver/wcs/kvp/WcsGetCapabilitiesRequestReader.java
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/kvp/WCS20GetCapabilitiesRequestReader.java
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/GetCapabilitiesTest.java

This pull request contains a a patch which should fix JIRA GEOS-6807 without breaking cite-tests

Patch for kvp parsing Sections parameter and acceptVersions (GEOS-6807)

---

src/restconfig/src/test/java/org/geoserver/catalog/rest/FeatureTypeTest.java

This is a replacement for #860 (the changes have already been applied to master).

core improvements for clustering module (backport)

---

doc/en/user/source/extensions/geosearch.rst

Addresses GEOS-6267 (http://jira.codehaus.org/browse/GEOS-6267)

Update geosearch.rst (GEOS-6267)

---

doc/en/developer/source/policies/community-modules.rst
doc/en/developer/source/programming-guide/ows-services/implementing.rst
doc/en/developer/source/programming-guide/rest-services/implementing.rst
doc/en/developer/source/programming-guide/testing/index.rst
doc/en/developer/source/programming-guide/web-ui/implementing.rst
doc/en/developer/source/programming-guide/wps-services/implementing.rst
doc/en/user/source/styling/sld-extensions/uom.rst

Resolves http://jira.codehaus.org/browse/GEOS-6429 amongst other fixes.

More documentation fixes

---

src/web/core/src/main/java/org/geoserver/web/AboutGeoServerPage.html
src/web/core/src/main/resources/GeoServerApplication.properties

Resolves http://jira.codehaus.org/browse/GEOS-2599
Also fixes an unrelated typo I noticed while checking this.

[GEOS-2559] Update About page documentation

---

src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPAuthenticationProvider.java
src/security/ldap/src/test/java/org/geoserver/security/ldap/LDAPAuthenticationProviderTest.java
src/security/ldap/src/test/java/org/geoserver/security/ldap/LDAPBaseTest.java

Backport of https://github.com/geoserver/geoserver/pull/928/commits

LDAP authentication: support active role service

---

src/main/src/main/java/org/geoserver/security/auth/GuavaAuthenticationCacheImpl.java
src/platform/src/main/java/org/geoserver/platform/resource/FileSystemWatcher.java

GEOS-6850 - Multiple Thread Pools left running at shutdown - Backport to 2.6

---

src/security/ldap/src/main/java/org/geoserver/security/ldap/BindingLdapAuthoritiesPopulator.java
src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPSecurityProvider.java
src/security/ldap/src/test/java/org/geoserver/security/ldap/LDAPAuthenticationProviderTest.java
src/security/ldap/src/test/resources/data3.ldif

Backport of https://github.com/geoserver/geoserver/pull/934

Ldap Security: authorities populator fails when colon in password

---

src/main/src/main/java/org/geoserver/catalog/CoverageDimensionCustomizerReader.java
src/main/src/test/java/org/geoserver/catalog/CoverageDimensionCustomizerReaderTest.java

Backport on 2.5.x of the fix for JIRA: https://jira.codehaus.org/browse/GEOS-6685

[GEOS-6685] WrappedSampleDimension sets NoData category as qualitative (Backport on 2.5.x)

---

doc/en/user/source/community/index.rst
doc/en/user/source/community/rest-upload/index.rst
src/community/pom.xml
src/community/release/ext-rest-upload.xml
src/community/rest-upload/pom.xml
src/community/rest-upload/src/main/java/applicationContext.xml
src/community/rest-upload/src/main/java/org/geoserver/restupload/ResumableUploadCatalogFinder.java
src/community/rest-upload/src/main/java/org/geoserver/restupload/ResumableUploadCatalogResource.java
src/community/rest-upload/src/main/java/org/geoserver/restupload/ResumableUploadPathMapper.java
src/community/rest-upload/src/main/java/org/geoserver/restupload/ResumableUploadResourceCleaner.java
src/community/rest-upload/src/main/java/org/geoserver/restupload/ResumableUploadResourceManager.java
src/community/rest-upload/src/test/java/org/geoserver/restupload/ResumableUploadTest.java
src/rest/src/main/java/org/geoserver/rest/util/IOUtils.java
src/web/app/pom.xml

JIRA: https://jira.codehaus.org/browse/GEOS-6886

[GEOS-6886] REST resumable upload community module

---

src/community/pom.xml
src/community/release/ext-rest-upload.xml
src/community/rest-upload/pom.xml

Pull request for fixing the geoserver-master-nightly jenkins job.

Fixed rest-upload community module dependency and assembly pom

---

src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/InternalWPSInputProvider.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteTest.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/MultiOutputEchoProcess.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/WPSTestSupport.java

This PR request shows as fix the issue https://jira.codehaus.org/browse/GEOS-6907
It needs a junit test, but I only have located the error using an optional sextante process that returns more of one output items (as sxt:kriging process).

GEOS-6907 Search wps result item by name or data type

---

src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java

Pure performance optimization, thus no tests (the existing ones will guard against regressions)

[GEOS-6923] Slow JSON response on EPSG:900913 defined vector layer

---

src/wcs1_1/src/main/java/org/geoserver/wcs/DefaultWebCoverageService111.java
src/wcs1_1/src/test/java/org/geoserver/wcs/GetCoverageTest.java

This pull request fixes the issue: https://jira.codehaus.org/browse/GEOS-6906

GEOS-6906 Fix bad calculation of source Coverage Transform

---

doc/en/user/source/gettingstarted/web-admin-quickstart/index.rst
doc/en/user/source/services/wms/time.rst
doc/en/user/source/webadmin/data/layers.rst
doc/en/user/source/webadmin/layerpreview/index.rst

Editing the WMS Time section led to updating the web admin side of things, which led to a cleaning of the entire Layers page.

Copyediting WMS Time (and Layers) sections

---

src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java
src/main/src/test/java/org/geoserver/security/impl/AbstractAuthorizationTest.java
src/main/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java
src/main/src/test/java/org/geoserver/security/impl/layerLock.properties
src/main/src/test/java/org/geoserver/security/impl/wsLock.properties

For details see: https://jira.codehaus.org/browse/GEOS-6943

Fix for 2.7-RC1 security regression [GEOS-6943]

---

src/community/pom.xml
src/community/release/ext-hz-cluster.xml
src/community/release/pom.xml

Build a plugin zip for the Hazelcast clustering community module

Add hazelcast cluster module to community extensions build

---

src/community/pom.xml
src/community/release/ext-hz-cluster.xml
src/community/release/pom.xml

Backport of #983
Build hz-cluster plugin zip as part of nightly build.

Add hazelcast cluster module to community extensions build, Backport to 2.7

---

src/main/src/main/java/org/geoserver/catalog/LayerGroupHelper.java
src/main/src/test/java/org/geoserver/catalog/CatalogIntegrationTest.java

Fix (and test case) for https://jira.codehaus.org/browse/GEOS-6944

[GEOS-6944] Fixed UNKNOWN crs for layer group

---

src/web/gwc/src/main/java/org/geoserver/gwc/web/CachingOptionsPanel.java

Fix for https://jira.codehaus.org/browse/GEOS-6949

[GEOS-6949] Fixed 16 showing twice

---

src/extension/wps/wps-core/pom.xml
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/InternalWCSInputProvider.java
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/WFSPPIO.java
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/xml/WPSConfiguration.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteOnCoverageTest.java
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/WCS2GetCoverageRequestBuilder.java

Backport of GEOS-6905 to 2.7.x, including fix for missing test dependency

GEOS-6905 2.7.x

---

src/web/core/src/main/java/org/geoserver/web/data/store/AbstractCoverageStorePage.html
src/web/core/src/main/java/org/geoserver/web/data/store/AbstractWMSStorePage.html
src/web/core/src/main/java/org/geoserver/web/data/store/panel/CheckBoxParamPanel.html
src/web/core/src/main/java/org/geoserver/web/data/store/panel/TextParamPanel.html

Fix for [GEOS-6036](http://jira.codehaus.org/browse/GEOS-6036) by removing span elements that weren't needed but were interfering with Firefox.

[GEOS-6036] Remove unnecessary span elements from UI

---

src/community/wps-sextante/src/main/java/org/geoserver/wps/sextante/GTRasterLayer.java

New changes to compile the wps-sextante plugin using last master branch

Changes to compile wps-sextante module with sextante libs 1.0 (update)

---

doc/en/user/source/webadmin/data/layers.rst

Add doc for the WMS Queryable checkbox to the Web Admin Layer page

Add WMS Queryable checkbox doc

---

doc/en/user/source/webadmin/data/layers.rst
doc/en/user/source/webadmin/data/stores.rst

Added subheadings, made formatting more consistent, minor text changes, and added a hint or two about layer naming.

Improve Doc for WebAdmin Store and Layer pages

---

doc/en/user/source/extensions/css/workshop/linestring.rst

Pull request fixes syntax regressions in tutorial (or codebase) hard to know which.

Minor syntax fixes to CSS tutorial

---

src/wms/src/main/java/org/geoserver/wms/capabilities/LegendSampleImpl.java
src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesLegendURLTest.java

[GEOS-7013] Fixed dynamic legend size calculation for raster styles.

[GEOS-7013] Fixed dynamic legend size calculation for raster styles.

---

src/pom.xml

Adjust expected result test result for GetFeatureInfo test due to difference in transform accuracy.
This request requires that https://github.com/geotools/geotools/pull/829 be applied first

Adjust for change of Matrix library (GEOS-7009)

---

src/community/gwc-distributed/src/test/java/org/geoserver/gwc/HazelcastTest.java

HazelcastTest fails wherever multicast is not available. This is the same problem seen in GeoWebCache issue 306 and fixed in GeoWebCache pull request 307:
https://github.com/GeoWebCache/geowebcache/issues/306
https://github.com/GeoWebCache/geowebcache/pull/307
The solution in this pull request is the same as for GeoWebCache: disabling multicast discovery and enabling tcp on localhost. In this pull request, the Hazelcast network configuration is set programmatically, as are other Hazelcast config parameters in this fixture; by comparison, the GeoWebCache test fixture uses a Spring applicationContextTest.xml.
This change is in the middle of a bunch of lines with mixed space/tab indentation, which I also fixed. To see the substantive changes (the four statements with …

Disabled multicast node discovery in HazelcastTest

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/onlineTest/DataReferenceWfsOnlineTest.java
src/extension/csw/api/src/main/java/org/geoserver/csw/records/CSWRecordDescriptor.java
src/extension/csw/api/src/main/java/org/geoserver/csw/records/RecordFeatureTypeRegistryConfiguration.java
src/extension/csw/api/src/main/java/org/geoserver/csw/records/iso/MetaDataDescriptor.java

Accompanies https://github.com/geotools/geotools/pull/841

Complex features refactoring: update csw & app-schema

---

doc/en/user/source/advanced/crshandling/configurecrs.rst
src/main/src/main/java/org/geoserver/GeoserverInitStartupListener.java
src/main/src/test/java/org/geoserver/GeoServerInitStartupListenerTest.java

GEOS-7035: Allows COMPARISON_TOLERANCE override through System Property

---

src/wfs/src/main/java/org/geoserver/wfs/WFSWorkspaceQualifier.java
src/wfs/src/test/java/org/geoserver/wfs/WFSWorkspaceQualifierTest.java

Same handling for WFS-T Insert and Replace.

GEOS-6986: Extended namespace validation for WFS-T replace

---

src/restconfig/src/main/java/org/geoserver/rest/GlobalSettingsResource.java
src/restconfig/src/main/java/org/geoserver/rest/templates/settings.ftl

See: https://osgeo-org.atlassian.net/browse/GEOS-7074

properties.pngAcceleration is undefined [GEOS-7074]

---

doc/en/user/source/community/geofence-server/index.rst
doc/en/user/source/community/geofence-server/installing.rst
doc/en/user/source/community/geofence-server/rest-userrole.rst
doc/en/user/source/community/geofence-server/rest.rst
doc/en/user/source/community/index.rst
src/community/geofence-server/pom.xml
src/community/geofence-server/src/main/java/org/geoserver/geofence/rest/GeofenceSecurityInterceptor.java
src/community/geofence-server/src/main/java/org/geoserver/geofence/rest/RolesRestController.java
src/community/geofence-server/src/main/java/org/geoserver/geofence/rest/RulesRestController.java
src/community/geofence-server/src/main/java/org/geoserver/geofence/rest/UsersRestController.java
src/community/geofence-server/src/main/java/org/geoserver/geofence/rest/xml/JaxbGroupList.java
src/community/geofence-server/src/main/java/org/geoserver/geofence/rest/xml/JaxbRoleList.java
src/community/geofence-server/src/main/java/org/geoserver/geofence/rest/xml/JaxbRule.java
src/community/geofence-server/src/main/java/org/geoserver/geofence/rest/xml/JaxbRuleList.java
src/community/geofence-server/src/main/java/org/geoserver/geofence/rest/xml/JaxbUser.java
src/community/geofence-server/src/main/java/org/geoserver/geofence/rest/xml/JaxbUserList.java
src/community/geofence-server/src/main/resources/applicationContext.xml
src/community/geofence-server/src/test/java/org/geoserver/geofence/internal/InternalServicesTest.java
src/community/geofence-server/src/test/java/org/geoserver/geofence/rest/RulesRestControllerTest.java
src/community/geofence-server/src/test/java/org/geoserver/geofence/rest/UserRoleRestControllerTest.java
src/community/pom.xml
src/community/release/ext-geofence-server.xml
src/community/release/ext-geofence.xml
src/community/release/pom.xml
src/main/src/test/java/org/geoserver/test/GeoServerAbstractTestSupport.java
src/main/src/test/java/org/geoserver/test/GeoServerTestApplicationContext.java
src/pom.xml

The Geofence REST API.
Some questions for the reviewers though:
- The user/group and role rest controllers don't really belong in the geofence-server module. Should I perhaps make a new community module or do they belong in an existing module?
- The user/group and role rest controllers seem too trivial to me to write unit tests for, each method only calls one other method. Suggestions for what I could write for testing is welcome though

Geofence: REST API

---

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/DbMappings.java
src/community/jdbcconfig/src/main/resources/org/geoserver/jdbcconfig/internal/nested_properties.properties
src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java

[GEOS-7064](https://osgeo-org.atlassian.net/browse/GEOS-7064)
Fixed a mistake in the tests, and corrected a bug they uncovered in JDBCConfig.
@groldan, `lookUpRelatedObject` seems to all be your code.  Do my changes make sense to you?

[GEOS-7064] Full text search unit tests in JDBCConfig failing

---

src/gwc/src/main/java/org/geoserver/gwc/ConfigurableBlobStore.java
src/gwc/src/test/java/org/geoserver/gwc/ConfigurableBlobStoreTest.java

ConfigurableBlobStore must add listeners to delegate regardless of its configuration status.
ConfigurableBlobStore is precluding blob store listeners from being added to
the delegate blob store at start up time, since GWCInitializer.initialize
calls ConfigurableBlobStore.setChanged() after the beans have been loaded.
This is making the disk-quota subsystem unusable, since it needs to register
a blobstore listener at startup time. Moreover, adding the listener should
not depend on whether the ConfigurableBlobStore has set up its caching
preferences.

ConfigurableBlobStore must add listeners to delegate

---

doc/en/user/source/rest/api/accesscontrol.rst
doc/en/user/source/rest/api/index.rst
doc/en/user/source/rest/examples/curl.rst
src/main/src/main/java/org/geoserver/security/GeoServerSecurityManager.java
src/main/src/main/java/org/geoserver/security/impl/RESTAccessRuleDAO.java
src/rest/src/main/java/org/geoserver/rest/MapResource.java
src/restconfig/src/main/java/applicationContext.xml
src/restconfig/src/main/java/applicationSecurityContext.xml
src/restconfig/src/main/java/org/geoserver/security/rest/AbstractAccessControlResource.java
src/restconfig/src/main/java/org/geoserver/security/rest/CatalogModeResource.java
src/restconfig/src/main/java/org/geoserver/security/rest/DataAccessControlResource.java
src/restconfig/src/main/java/org/geoserver/security/rest/RESTAccessControlResource.java
src/restconfig/src/main/java/org/geoserver/security/rest/RuleXMLFormat.java
src/restconfig/src/main/java/org/geoserver/security/rest/ServiceAccessControlResource.java
src/restconfig/src/test/java/org/geoserver/security/rest/AccessControlResourceTest.java

Hi 
Pull Request for GSIP 120.
This pull request contains
Core Code
Test Code
REST API Doc
Curl examples

GEOS-6726 Add Rest API for access control

---

src/main/src/main/java/org/geoserver/catalog/NamespaceWorkspaceConsistencyListener.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/NamespaceTest.java

See mailing list and associated [JIRA issue](https://osgeo-org.atlassian.net/browse/GEOS-7086) for discussion.

[GEOS-7086] Make sure if namespace is deleted, associated workspace is deleted too

---

src/community/authkey/src/main/resources/GeoServerApplication_ro.properties
src/community/dds/src/main/java/GeoServerApplication_ro.properties
src/community/hello_web/src/main/java/GeoServerApplication_ro.properties
src/extension/arcsde/src/main/resources/GeoServerApplication_ro.properties
src/extension/css/src/main/resources/GeoServerApplication_ro.properties
src/extension/web-csw/src/main/resources/GeoServerApplication_ro.properties
src/extension/wps/web-wps/src/main/resources/GeoServerApplication_ro.properties
src/web/core/src/main/resources/GeoServerApplication_ro.properties
src/web/demo/src/main/resources/GeoServerApplication_ro.properties
src/web/gwc/src/main/resources/GeoServerApplication_ro.properties
src/web/security/core/src/main/resources/GeoServerApplication_ro.properties
src/web/wcs/src/main/resources/GeoServerApplication_ro.properties
src/web/wfs/src/main/resources/GeoServerApplication_ro.properties

Signed-off-by: Frank Gasdorf <fgdrf@users.sourceforge.net>

[i18n] Romanian properties files synched from Transifex

---

doc/en/user/source/filter/function_reference.rst

Adds a description of the new IN filter function taking a variable number of arguments to the "Filter Function Reference" page.

[GEOS-7111] Updated 'Filter Function Reference' page

---

src/main/src/main/java/org/geoserver/util/NoExternalEntityResolver.java
src/wcs1_0/src/test/java/org/geoserver/wcs/GetCoverageTest.java
src/wcs1_1/src/test/java/org/geoserver/wcs/GetCoverageTest.java

See discussion on https://osgeo-org.atlassian.net/browse/GEOS-7095

[GEOS-7095] Do not allow ?#; in schema strings

---

doc/en/user/source/data/app-schema/app-schema-resolution.rst
doc/en/user/source/rest/api/datastores.rst
doc/en/user/source/rest/examples/curl.rst

Documentation for REST API extension introduced by [this commit](https://github.com/ridethepenguin/geoserver/commit/51583d36a85720250e67f7b647177fee7a9fa91f).

[GEOS-7132] Added docs and examples for app-schema mappings REST API

---

src/main/src/main/java/org/geoserver/util/NoExternalEntityResolver.java

Cherry-picked https://github.com/geoserver/geoserver/pull/1173 against master.

[GEOS-7139] Add vfs to supported protocols

---

src/restconfig/pom.xml
src/restconfig/src/main/java/org/geoserver/catalog/rest/DataStoreFileResource.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/DataStoreFileResourceTest.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/DataStoreFileUploadTest.java

Backport from master to 2.7.x branch.

[GEOS-7087] App-schema mapping file upload via REST

---

src/web/core/src/test/java/org/geoserver/web/admin/JAIPageTest.java

https://github.com/geoserver/geoserver/pull/1201 changed the JAI page to only show JAI options if native JAI is enabled. This breaks the JAIPageTest for systems where narive JAI is not enabled or not supported.
This PR fixes the test case to account for this.
Tested on OS X (No native JAI). Since the parts that require JAI are unchanged, I assume they still work.

[GEOS-7177] Fix JAIPageTest for systems without native JAI

---

src/release/ext-importer.xml

Added missing commons-vfs2 dependency

Fix for GEOS-7206 "Commons-vfs issue on Importer"

---

src/release/ext-importer.xml

Added missing commons-vfs2 dependency

Fix for GEOS-7206 "Commons-vfs issue on Importer

---

src/extension/inspire/src/main/java/org/geoserver/inspire/wfs/WFSExtendedCapabilitiesProvider.java
src/extension/inspire/src/main/java/org/geoserver/inspire/wms/WMSExtendedCapabilitiesProvider.java
src/extension/inspire/src/test/java/org/geoserver/inspire/wfs/WFSExtendedCapabilitiesTest.java
src/extension/inspire/src/test/java/org/geoserver/inspire/wms/WMSExtendedCapabilitiesTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7189

GEOS-7189: Fix deserialization of boolean metadata parameter.

---

README.md

Reverts geoserver/geoserver#1228

Revert "Adding travis badge to README.md"

---

src/main/src/main/java/org/geoserver/logging/LoggingUtils.java

This allows to use a DailyRollingFileAppender.

[GEOS-7213] Check geoserverlogfile appender against FileAppender

---

doc/en/user/source/community/jms-cluster/index.rst

Added missing space in "JMS based Clustering" chapter.

Missing space in "JMS based Clustering" chapter added

---

src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadEstimatorProcess.java
src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadProcess.java
src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterDownload.java
src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterEstimator.java
src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/ScaleToTarget.java
src/community/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
src/community/wps-download/src/test/java/org/geoserver/wps/gs/download/ScaleToTargetTest.java

[GEOS-7214] Add scaling support to WPS gs:Download process

---

doc/en/developer/source/eclipse-guide/index.rst
doc/en/developer/source/quickstart/index.rst

For https://osgeo-org.atlassian.net/browse/GEOS-7221

[GEOS-7221] Document how to debug extensions from eclipse

---

doc/en/user/source/data/database/primarykey.rst

Following up http://sourceforge.net/p/geoserver/mailman/message/34484253/ and my own experience of creating the table in the 'public' schema instead...

Doc primary key: Correct table name and schema qualified

---

doc/en/user/source/rest/api/reset.rst

Fix for: https://osgeo-org.atlassian.net/browse/GEOS-7187

"Resource reset" REST API documentation fix

---

src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterEstimator.java
src/community/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java

This is not to be seen as a definitive solution to the problem, just a bare minimum sanity check, as OOM exceptions may still occur and cause the actual download to fail, even if the estimator said it was OK to download.

[GEOS-7230] gs:DownloadEstimator should check size is less than Integer.MAX_VALUE

---

doc/en/user/source/security/index.rst

Link to rancor.boundlessgeo.com was broken

Updated link to Christian's thesis

---

src/pom.xml

I did a full build (clean install), a release build (install -Prelease), and a "really clean" build where I removed the whole $HOME/.m2 directory, then did a clean install -Prelease build.

[GEOS-7200] Remove snapshot use for OSGEO repo.

---

src/extension/app-schema/app-schema-oracle-test/pom.xml
src/extension/app-schema/app-schema-postgis-test/pom.xml
src/extension/app-schema/app-schema-test/pom.xml
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/web/AbstractMapPreviewPageTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/web/Gml311LinksTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/web/Gml32LinksTest.java
src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.java
src/web/demo/src/main/java/org/geoserver/web/demo/PreviewLayer.java

[GEOS-7226] Default GML links in Layer Preview page do not work for app-schema layers

---

src/extension/wcs2_0-eo/core/src/main/java/org/geoserver/wcs2_0/eo/response/SingleGranuleGridCoverageReader.java
src/main/src/main/java/org/geoserver/catalog/CoverageDimensionCustomizerReader.java
src/main/src/main/java/org/geoserver/catalog/CoverageViewReader.java
src/main/src/main/java/org/geoserver/catalog/SingleGridCoverage2DReader.java
src/main/src/main/java/org/geoserver/security/decorators/SecuredGridCoverage2DReader.java

Make sure to not merge this pull request before merging 
https://github.com/geotools/geotools/pull/999

GeoServer updates needed as consequency of GEOT-5247

---

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/CatalogUtils.java

Closes GEOS-7259, JMS based cluster should use qualified names for Layers and Layergroups

Closes GEOS-7259

---

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/CatalogUtils.java

JMS based cluster should use qualified names for Layers and Layergroups

backport of fix for GEOS-7259

---

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/CatalogUtils.java

JMS Clustering should prefix Styles names with workspace

Fix for GEOS-7267

---

doc/en/developer/source/programming-guide/ows-services/hello/pom.xml
doc/en/developer/source/programming-guide/ows-services/hello/src/main/java/HelloWorld.java
doc/en/developer/source/programming-guide/ows-services/hello/src/main/java/applicationContext.xml
doc/en/developer/source/programming-guide/ows-services/implementing.rst

Also extract out the files to make it easier to test and use.

[GEOS-7246] Update OWS programming example for repo change.

---

doc/en/user/source/community/gdal/usage_example.rst
doc/en/user/source/community/geofence-server/gui.rst
doc/en/user/source/community/geofence-server/rest-userrole.rst
doc/en/user/source/community/geofence-server/rest.rst
doc/en/user/source/community/gwc-s3/index.rst
doc/en/user/source/community/rest-upload/index.rst
doc/en/user/source/community/solr/optimize.rst
doc/en/user/source/data/raster/gdal.rst
doc/en/user/source/extensions/grib/grib.rst
doc/en/user/source/extensions/importer/rest_reference.rst
doc/en/user/source/extensions/monitoring/upgrade.rst
doc/en/user/source/extensions/netcdf-out/nc4.rst
doc/en/user/source/geowebcache/config.rst
doc/en/user/source/googleearth/tutorials/time/time.rst
doc/en/user/source/introduction/gettinginvolved.rst

Avoids warnings, a couple of typo fixes.

[GEOS-6876] Minor documentation cleanups.

---

doc/en/user/source/extensions/css/cascading.rst
doc/en/user/source/extensions/css/directives.rst
doc/en/user/source/extensions/css/index.rst
src/main/src/main/java/org/geoserver/jai/JAIInitializer.java

Documentation for https://github.com/geotools/geotools/pull/1017

[GEOS-7274] Add a Flat translation mode to CSS

---

src/community/authkey/src/test/java/org/geoserver/security/AuthencationKeyOWSTest.java
src/wms/src/main/java/org/geoserver/wms/map/OpenLayersMapOutputFormat.java

See [JIRA issue](https://osgeo-org.atlassian.net/browse/GEOS-7295) for details.
PR has no unit test because it was not trivial to write one and I wasn't sure it's needed for such a simple fix, but I can add one if required.

[GEOS-7295] Authkey community module breaks OpenLayers preview

---

src/extension/inspire/pom.xml
src/extension/inspire/src/main/java/org/geoserver/inspire/wcs/WCSExtendedCapabilitiesProvider.java
src/extension/inspire/src/main/java/org/geoserver/inspire/web/InspireAdminPanel.java
src/extension/inspire/src/main/resources/applicationContext.xml
src/extension/inspire/src/test/java/org/geoserver/inspire/wcs/WCSExtendedCapabilitiesTest.java
src/extension/inspire/src/test/java/org/geoserver/inspire/web/InspirePanelTest.java

GEOS-6435 - Add INSPIRE extended capabilities to WCS

---

src/main/src/main/java/org/geoserver/catalog/LayerGroupInfo.java
src/main/src/main/java/org/geoserver/catalog/LayerInfo.java
src/main/src/main/java/org/geoserver/catalog/PublishedInfo.java
src/main/src/main/java/org/geoserver/catalog/impl/LayerGroupInfoImpl.java
src/main/src/main/java/org/geoserver/security/decorators/DecoratingLayerGroupInfo.java
src/main/src/test/java/org/geoserver/config/DefaultGeoServerLoaderTest.java
src/main/src/test/resources/data_dir/nested_layer_groups/workspaces/topp/layergroups/simplegroup.xml
src/restconfig/src/test/java/org/geoserver/catalog/rest/LayerGroupTest.java
src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/CapabilitiesTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesIntegrationTest.java

See https://github.com/geoserver/geoserver/wiki/GSIP-135
https://osgeo-org.atlassian.net/browse/GEOS-5888
https://osgeo-org.atlassian.net/browse/GEOS-7313

Layergroups: attribution & metadatalinks API+rest+getcapabilities

---

doc/en/user/source/tutorials/imagemosaic-jdbc/imagemosaic-jdbc_tutorial.rst

See JIRA ticket: https://osgeo-org.atlassian.net/browse/GEOS-7322

[GEOS-7322] Update dead link

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/FeatureGML32Test.java
src/wfs/src/main/java/org/geoserver/wfs/StoredQuery.java

This is the backport of #1330 to the 2.8.x branch.

[GEOS-7306] Stored Queries don't work on App-Schema layers backed by database

---

doc/en/user/source/tutorials/image_mosaic_plugin/imagemosaic.rst

Update the imagemosaic tutorial with new content to match actual behavior.
Some content adapted from http://geoserver.geo-solutions.it/multidim/en/imagemosaic/index.html
Added description of JDBC indexing / datastore.properties
Added documentation on indexer.properties
Update GeoServer ImageMosaic Layer Configuration parameters with new parameters.
Fix formatting.

Update imagemosiac tutorial

---

src/extension/inspire/src/main/java/org/geoserver/inspire/wms/WMSExtendedCapabilitiesProvider.java
src/gwc/src/main/java/org/geoserver/gwc/wms/CachingExtendedCapabilitiesProvider.java
src/wms/src/main/java/org/geoserver/wms/ExtendedCapabilitiesProvider.java
src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
src/wms/src/main/java/org/geoserver/wms/capabilities/CapabilityUtil.java
src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesScaleDenominatorTest.java
src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformerTest.java
src/wms/src/test/resources/org/geoserver/wms/capabilities/Accident3_2.sld

https://osgeo-org.atlassian.net/browse/GEOS-7333

WMS GetCapabilities Mix/MaxDenominators for layer groups [GEOS-7333]

---

src/wfs/src/main/java/org/geoserver/wfs/StoredQueryProvider.java
src/wfs/src/test/java/org/geoserver/wfs/StoredQueryProviderTest.java

This is a resubmitted fix for GEOS-7297.  The original pull request is now out of date and I made several changes as a result of feedback.

[GEOS-7297] Fix issue where Stored Queries fail under load.

---

src/community/geofence-server/src/main/java/org/geoserver/geofence/web/GeofenceRulePage.html
src/community/geofence-server/src/main/java/org/geoserver/geofence/web/GeofenceRulePage.java
src/community/geofence-server/src/main/java/org/geoserver/geofence/web/GeofenceRulesModel.java
src/community/geofence-server/src/main/resources/GeoServerApplication.properties

https://osgeo-org.atlassian.net/browse/GEOS-7348

[GEOS-7347] Allow to enter an allowed area in Geofence UI

---

src/community/geofence-server/pom.xml
src/community/geofence-server/src/main/java/org/geoserver/geofence/web/GeofenceServerPage.java
src/web/core/src/main/java/org/geoserver/web/wicket/GeoServerTablePanel.java

The drag and drop feature is implemented using library: 
https://github.com/svenmeier/wicket-dnd 
The associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7348

[GEOS-7348] Rules priority can be managed using drag and drop

---

src/community/geofence-server/pom.xml
src/community/geofence-server/src/main/java/org/geoserver/geofence/web/GeofenceAdminRulePage.html
src/community/geofence-server/src/main/java/org/geoserver/geofence/web/GeofenceAdminRulePage.java
src/community/geofence-server/src/main/java/org/geoserver/geofence/web/GeofenceAdminRulesModel.java
src/community/geofence-server/src/main/java/org/geoserver/geofence/web/GeofenceServerAdminPage$ButtonPanel.html
src/community/geofence-server/src/main/java/org/geoserver/geofence/web/GeofenceServerAdminPage.html
src/community/geofence-server/src/main/java/org/geoserver/geofence/web/GeofenceServerAdminPage.java
src/community/geofence-server/src/main/resources/GeoServerApplication.properties
src/community/geofence-server/src/main/resources/applicationContext.xml
src/pom.xml
src/web/core/src/main/java/org/geoserver/web/wicket/GeoServerTablePanel.java

Issue: https://osgeo-org.atlassian.net/browse/GEOS-7356

[GEOS-7356] Add GeoFence admin rules page

---

src/pom.xml
src/web/core/pom.xml
src/web/core/src/main/java/org/geoserver/web/data/layer/CascadedWFSStoredQueryNewPage.java
src/web/core/src/main/java/org/geoserver/web/data/layer/CoverageViewAbstractPage.java
src/web/core/src/main/java/org/geoserver/web/data/layer/SQLViewAbstractPage.java
src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupEditPage.java
src/web/core/src/main/java/org/geoserver/web/data/resource/DataLinkEditor.java
src/web/core/src/main/java/org/geoserver/web/data/resource/DimensionEditor.java
src/web/core/src/main/java/org/geoserver/web/data/resource/MetadataLinkEditor.java
src/web/core/src/main/java/org/geoserver/web/data/store/WMSStoreNewPage.java
src/web/core/src/main/java/org/geoserver/web/wicket/FileExistsValidator.java
src/web/core/src/main/java/org/geoserver/web/wicket/SRSListTextArea.java
src/web/core/src/main/java/org/geoserver/web/wicket/URIValidator.java
src/web/core/src/main/java/org/geoserver/web/wicket/XMLNameValidator.java
src/web/core/src/test/java/org/geoserver/web/wicket/FileExistsValidatorTest.java

POM conversion per advice at https://cwiki.apache.org/confluence/display/WICKET/Migration+to+Wicket+1.5#MigrationtoWicket1.5-Mavenusersarerecommendedtodependonorg.apache.wicket:wicket:pomfromnowon
Convert over usage of AbstractValidator to IValidator. Those are untested, but do at least fix compilation problems.

Wicket 7 conversion

---

src/extension/wps/wps-core/src/main/java/applicationContext.xml
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/DefaultProcessManager.java
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/ProcessStartupFilter.java
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/WPSExecutionManager.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/other/NoArgWPS.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/other/NoArgWPSTest.java
src/extension/wps/wps-core/src/test/resources/applicationContext-noargs.xml

Look ma, an insurmountable problem fixed!

[GEOS-7281] move input-less processes to RUNNING state during execution

---

src/community/vectortiles/src/main/java/org/geoserver/wms/vector/PipelineBuilder.java

I made some changes;
a) minor documentation additions
b) Generalization was being done after transforming to the target CRS, but was using the source CRS generalization factor
c) Changed clipping so the clipping rectangle is 12px bigger than the actual tile boundary.  This is what the streaming renderer does.  This was done because it hides the introduced clip lines to polygons. 
d) changed the clipper to use an envelope instead of a polygon and use the GeometryClipper with some support for dealing with topology exceptions.
All of these are fairly minor.

added clipping buffer

---

src/web/core/src/main/java/org/geoserver/web/admin/StatusPage.html
src/web/core/src/main/java/org/geoserver/web/admin/StatusPage.java
src/web/core/src/main/resources/GeoServerApplication.properties

https://osgeo-org.atlassian.net/browse/GEOS-7377

GEOS-7377: added Java rendering engine to status page

---

src/web/core/src/main/java/org/geoserver/web/wicket/browser/FileProvider.java

Spot fix for compilation with Wicket 7.

Wicket 7 conversion for web.wicket.browser.FileProvider

---

src/web/core/src/main/java/org/geoserver/web/wicket/property/PropertyEditorFormComponent.java

Wicket 7 build fixes for web.wicket.property.PropertyEditorFormComponent

---

src/web/core/src/main/java/org/geoserver/web/data/layer/CascadedWFSStoredQueryNewPage.java
src/web/core/src/main/java/org/geoserver/web/data/layer/CoverageViewAbstractPage.java
src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupEditPage.java
src/web/core/src/main/java/org/geoserver/web/data/resource/DataLinkEditor.java
src/web/core/src/main/java/org/geoserver/web/data/resource/DimensionEditor.java
src/web/core/src/main/java/org/geoserver/web/data/resource/MetadataLinkEditor.java
src/web/core/src/main/java/org/geoserver/web/data/store/WMSStoreNewPage.java
src/web/core/src/main/java/org/geoserver/web/wicket/FileExistsValidator.java
src/web/core/src/main/java/org/geoserver/web/wicket/SRSListTextArea.java
src/web/core/src/main/java/org/geoserver/web/wicket/URIValidator.java
src/web/core/src/main/java/org/geoserver/web/wicket/XMLNameValidator.java
src/web/core/src/main/resources/GeoServerApplication.properties

I'd failed to realise those were resource keys.

[Wicket 7] Fix errors in conversion at c1aabb94e843263851e376bdff2d28ba45bba7e6

---

src/extension/inspire/src/main/resources/org/geoserver/inspire/available_languages.properties

As per discussion in GEOS-7338.
Assuming too trivial to need copyright headers.

GEOS-7388 Add Croatian to list of languages

---

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcloader/JDBCLoaderProperties.java

@NielsCharlier can we re-add the fill-in method here? Was there a reason to remove it?

Re-add the fill-in method to replace the data dir property

---

src/gwc/src/main/java/org/geoserver/gwc/layer/CatalogConfiguration.java
src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
src/gwc/src/test/java/org/geoserver/gwc/layer/CatalogConfigurationTest.java

See: https://osgeo-org.atlassian.net/browse/GEOS-7387

[GEOS-7387] Cached layer removal fails to remove cached tiles

---

src/wms/src/test/java/org/geoserver/wms/WMSDimensionsTestSupport.java

Updated the test assertion to use assertTrue instead of vanilla assert, since assert will fail unless assertions are enabled.

Update the test to use assertTrue instead of just assert.

---

src/community/jms-cluster/activemqBroker/pom.xml
src/community/netcdf-out/pom.xml
src/community/w3ds/pom.xml
src/pom.xml
src/web/core/pom.xml

Homogenize slf4j dependency version, there were
several mixed versions across modules.
Upgrade to latest stable 1.7.14.

Set slf4j dependencies version in root pom.

---

src/community/release/ext-geofence-server.xml

This also removes the extra spaces at the end of the lines.

[GEOS-7395] Add missing JARs to geofence plugin

---

src/community/release/ext-geofence-server.xml

This also corrects some spaces issues.

[GEOS-7395] Add missing JARs to geofence plugin (2.8.x backport)

---

doc/en/user/source/data/database/sqlview.rst

Trying out pull requests, I'll have some more suggestions later.

Make a note for read-only limitation.

---

src/community/params-extractor/src/main/java/org/geoserver/params/extractor/Rule.java
src/community/params-extractor/src/test/java/org/geoserver/params/extractor/RuleTest.java
src/community/pom.xml
src/community/release/pom.xml

Remove JDK8 dependency and make rule tests predictable (backport 2.8.x)

---

src/community/params-extractor/src/main/java/org/geoserver/params/extractor/Rule.java
src/community/params-extractor/src/test/java/org/geoserver/params/extractor/RuleTest.java
src/community/pom.xml
src/community/release/pom.xml

Remove JDK8 dependency and make rule tests predictable (backport 2.7.x)

---

src/wfs/src/main/java/org/geoserver/wfs/response/CSVOutputFormat.java
src/wfs/src/test/java/org/geoserver/wfs/response/CSVOutputFormatTest.java

* Use Guava Escapers to escape embedded quotes in attributes rather
than String.replace as the latter recompiles the regex for every
single attribute
* Compute the attribute formatters once and reuse rather than checking
instanceof for every attribute

Improve performance in CSVOutputFormat

---

src/extension/csw/core/src/test/java/org/geoserver/csw/store/internal/LayerGroupTest.java
src/main/src/main/java/org/geoserver/catalog/impl/ModificationProxyCloner.java
src/main/src/main/java/org/geoserver/security/SecureCatalogImpl.java
src/main/src/main/java/org/geoserver/security/decorators/DecoratingCatalogFactory.java
src/main/src/main/java/org/geoserver/security/decorators/SecuredLayerGroupInfo.java
src/main/src/test/java/org/geoserver/catalog/CatalogIntegrationTest.java
src/main/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java
src/main/src/test/java/org/geoserver/security/impl/SecuredLayerGroupTest.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/LayerGroupTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7392
ModificationProxyCloner change was in the end not necessary to fix the bug, but the change still makes sense so I am leaving it in.

GEOS-7392 SecuredLayerGroup bug

---

src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/EnumPPIO.java
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/ProcessParameterIO.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ppio/EnumPPIOTest.java

I made this change as part of a pull request pending, but I thought I would break it out separately.

Added specific EnumPPIO for handling enum parameter types.

---

src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
src/main/src/test/java/org/geoserver/config/util/XStreamPersisterTest.java
src/main/src/test/resources/org/geoserver/config/virtualtable_error_GEOS-7400.xml

Patch for [GEO-7400](https://osgeo-org.atlassian.net/browse/GEOS-7400)

Patch for [GEO-7400]

---

src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
src/extension/importer/core/src/main/java/org/geoserver/importer/SpatialFile.java
src/extension/importer/core/src/test/java/org/geoserver/importer/ImporterDataTest.java
src/main/src/main/java/org/geoserver/catalog/StyleGenerator.java

When importing from a file source it checks if the style came with a
style file, and when that is the case tries to use that for the style
of the new layer rather than generating one from scratch.

Added support for importing files along with styling.

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SecuredFeatureChainingTest.java
src/main/src/main/java/org/geoserver/security/decorators/SecuredDataStoreInfo.java

This is the backport of #1530 to the 2.8.x branch.

[GEOS-7459] Securing an app-schema data store may result in ClassCastException being thrown

---

doc/en/developer/source/policies/gsip.rst

https://github.com/geoserver/geoserver/wiki/GSIP-141

GSIP 141 - Change GSIP voting rules to 30% positive with 50% quorum

---

src/community/wps-remote/src/main/java/org/geoserver/wps/remote/RemoteProcessClient.java
src/community/wps-remote/src/main/java/org/geoserver/wps/remote/plugin/XMPPClient.java
src/community/wps-remote/src/main/java/org/geoserver/wps/remote/plugin/output/XMPPRawDataOutput.java

Related to Improvement JIRA GEOS-7480

[GEOS-7480] - NetCDF Importer Fixes

---

src/community/pom.xml

Allows python to be built without building all the other bindings.

Add community profiles for building just the python and UI components of scripting.

---

src/community/pom.xml

Build `geoserver-VERSION-python-plugin.zip`

Build python community plugin zip.

---

src/extension/wps/wps-core/src/main/java/applicationContext.xml
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/gs/AggregateProcessJSONPPIO.java
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/gs/AggregateProcessPPIO.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/AggregateProcessTest.java

Issue: https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-7433

[GEOS-7433] Add support for aggregation process group by results (backport 2.8.x)

---

src/main/src/main/java/org/geoserver/catalog/SLDHandler.java
src/main/src/main/java/org/geoserver/config/LockProviderInitializer.java
src/main/src/main/java/org/geoserver/logging/LoggingUtils.java
src/main/src/test/java/org/geoserver/catalog/PropertyStyleHandler.java
src/main/src/test/java/org/geoserver/logging/LoggingStartupContextListenerTest.java
src/platform/src/main/java/org/geoserver/platform/GeoServerResourceLoader.java
src/platform/src/main/java/org/geoserver/platform/resource/FileSystemResourceStore.java

…by changing logging level or styles

(2.8.x) [GEOS-7492] Admin can temporarily lock themselves out of UI or REST 

---

src/community/wps-sextante/src/test/java/org/geoserver/wps/sextante/SextanteIntegrationTest.java

Changes to compile the wps-sextante plugin using last master branch

Changes to compile wps-sextante module

---

src/community/geofence-server/src/main/resources/applicationContext.xml

Issue with description: https://osgeo-org.atlassian.net/browse/GEOS-7494

[GEOS-7494] Makes geofence-server uses the correct properties file

---

src/release/bin/shutdown.sh
src/release/bin/startup.sh

Alternative to https://github.com/geoserver/geoserver/pull/1552 that should be more general and not break MacOS.

Detect Java runtime from JAVA_HOME or PATH

---

doc/en/user/source/community/index.rst
doc/en/user/source/community/ysld/gs-extensions.rst
doc/en/user/source/community/ysld/index.rst
doc/en/user/source/community/ysld/installing.rst
src/community/pom.xml
src/community/release/ext-ysld.xml
src/community/release/pom.xml
src/community/ysld/pom.xml
src/community/ysld/src/main/java/org/geoserver/ysld/GWCZoomContextFinder.java
src/community/ysld/src/main/java/org/geoserver/ysld/YsldHandler.java
src/community/ysld/src/main/resources/applicationContext.xml
src/community/ysld/src/main/resources/org/geoserver/ysld/template_generic.ysld
src/community/ysld/src/main/resources/org/geoserver/ysld/template_line.ysld
src/community/ysld/src/main/resources/org/geoserver/ysld/template_point.ysld
src/community/ysld/src/main/resources/org/geoserver/ysld/template_polygon.ysld
src/community/ysld/src/main/resources/org/geoserver/ysld/template_raster.ysld
src/community/ysld/src/test/java/org/geoserver/ysld/GWCZoomContextFinderTest.java
src/community/ysld/src/test/java/org/geoserver/ysld/ResourceLocatorTest.java
src/web/app/pom.xml

https://osgeo-org.atlassian.net/browse/GEOS-7520

GEOS-7520: Import YSLD module as new Community Module

---

src/restconfig/src/main/java/org/geoserver/catalog/rest/StyleFinder.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/StyleTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-7517 for more details about the issue.

[GEOS-7517] Return HTTP 404 for REST PUT against global styles when style exists in workspace

---

doc/en/user/source/geowebcache/webadmin/defaults.rst
src/web/gwc/src/main/java/org/geoserver/gwc/web/InMemoryBlobStorePanel.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/GWCSettingsPageTest.java

The issue associated with this pull request: https://osgeo-org.atlassian.net/browse/GEOS-7523
This pull request fixes the issue, updates the documentation and add a test case.

[GEOS-7523] Make GWC settings UI only show the accepted eviction policies

---

doc/en/user/source/community/geofence-server/tutorial.rst

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7536

[GEOS-7536] Update geofence-geoserver module documentation

---

doc/en/user/source/community/geofence-server/tutorial.rst

Backport of pull request https://github.com/geoserver/geoserver/pull/1592

[GEOS-7536] Update geofence-geoserver module documentation (backport 2.9.x)

---

src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorFilter.java
src/extension/monitor/core/src/test/java/org/geoserver/monitor/MonitorFilterTest.java

Hi,
I've done the changes for this issue along with two unit tests. Please review.
Enjoy,
Jan

GEOS 7538: Monitoring plugin doesn't log remote user

---

src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorFilter.java
src/extension/monitor/core/src/test/java/org/geoserver/monitor/MonitorFilterTest.java

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7538

[GEOS-7538] Allows monitoring of remote user in case of arbitrary UserDetails implementations (backport 2.9.x) 

---

src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorFilter.java
src/extension/monitor/core/src/test/java/org/geoserver/monitor/MonitorFilterTest.java

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7538

[GEOS-7538] Allows monitoring of remote user in case of arbitrary UserDetails implementations

---

src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorFilter.java
src/extension/monitor/core/src/test/java/org/geoserver/monitor/MonitorFilterTest.java

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7538

[GEOS-7538] Fix copyright headers date

---

doc/en/user/source/production/java.rst

Please see: https://osgeo-org.atlassian.net/browse/GEOS-7554

Doc warning for pure java jai / native jai incompatibility [GEOS-7554]

---

src/extension/gdal/src/main/java/applicationContext.xml
src/extension/gdal/src/main/java/org/geoserver/gdal/GDALStatus.java
src/extension/gdal/src/test/java/org/geoserver/gdal/GDALStatusTest.java

Implementation of the ModuleStatus for GDAL plugin.  Fairly simple, but gives lots of good information.

[GSIP 143] GdalStatus

---

src/extension/libjpeg-turbo/src/main/java/org/geoserver/map/turbojpeg/TurboJPEGMapResponse.java
src/extension/libjpeg-turbo/src/main/java/org/geoserver/map/turbojpeg/TurboJpegStatus.java
src/extension/libjpeg-turbo/src/main/resources/applicationContext.xml
src/extension/libjpeg-turbo/src/test/java/org/geoserver/map/turbojpeg/TurboJpegStatusTest.java

This is a ModuleStatus implementation for LibTurboJpeg.
It's fairly simple, but gives decent status information on LibTurboJpeg.

[GSIP 143] Turbojpegstatus

---

doc/en/user/source/community/index.rst
doc/en/user/source/community/jdbcstore/configuration.rst
doc/en/user/source/community/jdbcstore/index.rst
doc/en/user/source/community/jdbcstore/installing.rst
src/community/pom.xml
src/community/release/ext-jdbcstore.xml
src/community/release/pom.xml

https://osgeo-org.atlassian.net/browse/GEOS-7515

[GEOS-7515] JDBCStore: plugin + docs

---

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/web/ClusterPage.java

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7565

[GEOS-7565] Set model type for cluster web page components

---

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/web/ClusterPage.java

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7565

[GEOS-7565] Set model type for cluster web page components (backport to 2.9.x)

---

src/web/core/src/main/resources/GeoServerApplication_de.properties

Fix typo in German translation

---

src/extension/netcdf-out/src/main/java/applicationContext.xml
src/extension/netcdf-out/src/main/java/org/geoserver/netcdfout/NetCDFOutStatus.java
src/extension/netcdf-out/src/test/java/org/geoserver/netcdfout/NetCDFOutStatusTest.java
src/extension/netcdf/src/main/java/applicationContext.xml
src/extension/netcdf/src/main/java/org/geoserver/netcdf/NetCDFStatus.java
src/extension/netcdf/src/test/java/org/geoserver/netcdf/NetCDFStatusTest.java

Module status for netcdf and netcdf-out.  Looks for native dependencies and tries to report on them.

GSIP-143 GEOS-7567 Module status for netcdf and netcdf-out

---

doc/en/user/source/data/raster/geotiff.rst

See: http://osgeo-org.1560.x6.nabble.com/ImageMosaic-and-custom-CRS-GeoTIFFs-td5270295.html

Add info about .prj file in GeoTIFF reader docs

---

doc/en/user/source/services/wms/get_legend_graphic/index.rst
src/main/src/test/java/org/geoserver/data/test/rainfall_classes_nolabels.sld
src/wms/src/main/java/org/geoserver/wms/legendgraphic/BufferedImageLegendGraphicBuilder.java
src/wms/src/main/java/org/geoserver/wms/legendgraphic/ColorMapLegendCreator.java
src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendMerger.java
src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendUtils.java
src/wms/src/main/java/org/geoserver/wms/legendgraphic/RasterLayerLegendHelper.java
src/wms/src/test/java/org/geoserver/wms/legendgraphic/AbstractLegendGraphicOutputFormatTest.java
src/wms/src/test/java/org/geoserver/wms/legendgraphic/BaseLegendTest.java
src/wms/src/test/java/org/geoserver/wms/legendgraphic/LegendLayoutTest.java

https://github.com/geoserver/geoserver/wiki/GSIP-146

GEOS-7573: Added optional parameters to manage legend layout

---

src/extension/netcdf-out/pom.xml

[GEOT-5434] Upgrade to NetCDF-Java 4.6.6
https://osgeo-org.atlassian.net/browse/GEOT-5434
Must be merged at the same time as https://github.com/geotools/geotools/pull/1211

[GEOT-5434] Upgrade to NetCDF-Java 4.6.6

---

doc/en/user/source/configuration/crshandling/coordtransforms.rst

Additional documentation example

Example of NAD27 to WGS84 coordiante operation

---

src/platform/src/main/java/org/geoserver/platform/ModuleStatusImpl.java
src/platform/src/test/java/org/geoserver/platform/ModuleStatusTest.java
src/restconfig/src/main/java/org/geoserver/rest/AboutStatus.java
src/restconfig/src/main/java/org/geoserver/rest/templates/ModuleStatusImpl.ftl

Fixed bug in ModuleStatusImpl (wasn't actually recording isEnabled/isAvailable) - GEOS-7608
Added test case
Added isEnabled/isAvailable to HTML and JSON output.
Added test case (there wasn't any existing REST tests I could find)

GEOS-7608 GEOS-7567 GSIP-143 bug fix and improved module status page

---

src/extension/importer/rest/src/main/resources/applicationContext.xml
src/extension/importer/web/src/main/resources/applicationContext.xml
src/extension/netcdf/src/main/java/org/geoserver/netcdf/NetCDFStatus.java
src/web/security/core/src/main/java/applicationContext.xml
src/web/wcs/src/main/java/applicationContext.xml

GSIP-143 minor typos noticed in module names

---

doc/en/user/source/services/wms/outputformats.rst
src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerMetaTile.java
src/gwc/src/main/resources/org/geoserver/gwc/advertised_formats.properties
src/gwc/src/test/java/org/geoserver/gwc/GWCTest.java
src/wms/src/main/java/applicationContext.xml
src/wms/src/main/java/org/geoserver/wms/WMSMapContent.java
src/wms/src/main/java/org/geoserver/wms/WebMap.java
src/wms/src/main/java/org/geoserver/wms/map/JpegOrPngChooser.java
src/wms/src/main/java/org/geoserver/wms/map/JpegPngMapResponse.java
src/wms/src/main/java/org/geoserver/wms/map/MetatileMapOutputFormat.java
src/wms/src/main/resources/org/geoserver/wms/map/OpenLayers2MapTemplate.ftl
src/wms/src/main/resources/org/geoserver/wms/map/OpenLayers3MapTemplate.ftl
src/wms/src/test/java/org/geoserver/wms/map/JpegOrPngChooserTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapIntegrationTest.java

Depends on:
https://github.com/GeoWebCache/geowebcache/pull/395
(might not build/work without it)

[GEOS-7603] Add support for dynamically choosing jpeg or png compression based on output contents

---

src/gwc/src/main/java/org/geoserver/gwc/dispatch/GwcServiceDispatcherCallback.java
src/gwc/src/main/java/org/geoserver/gwc/layer/CatalogConfiguration.java
src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
src/gwc/src/main/resources/geowebcache-geoserver-context.xml
src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
src/gwc/src/test/java/org/geoserver/gwc/GWCTestHelpers.java
src/gwc/src/test/java/org/geoserver/gwc/dispatch/GwcServiceDispatcherCallbackTest.java
src/gwc/src/test/java/org/geoserver/gwc/layer/CatalogConfigurationTest.java
src/gwc/src/test/java/org/geoserver/gwc/layer/GeoServerTileLayerTest.java

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7591

[GEOS-7591] Allow WMTS service to be invoked per workspace

---

src/web/core/src/main/java/org/geoserver/web/data/resource/CoverageBandsConfigurationPanel.java
src/web/core/src/main/java/org/geoserver/web/wicket/DecimalConverter.java
src/web/core/src/main/java/org/geoserver/web/wicket/DecimalListConverter.java
src/web/core/src/main/java/org/geoserver/web/wicket/DecimalListTextField.java
src/web/core/src/main/java/org/geoserver/web/wicket/DecimalTextField.java
src/web/core/src/test/java/org/geoserver/web/wicket/DecimalListTextFieldTest.java
src/web/core/src/test/java/org/geoserver/web/wicket/DecimalTextFieldTest.java
src/web/core/src/test/java/org/geoserver/web/wicket/InputTestPage.html
src/web/core/src/test/java/org/geoserver/web/wicket/InputTestPage.java

@dromagnoli this one is for you to review (as the original author of the editable version of the band properties)

[GEOS-7621] Coverage band details editing, issues with locale, list separators and decimal numbers representation

---

src/web/core/src/main/java/org/geoserver/web/data/resource/ResourceConfigurationPage.java
src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7628

[GEOS-7628] Fix ResourceConfigurationPage.updateResource()

---

src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/LegendCapabilitiesTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/LegendCapabilitiesTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7601

[GEOS-7601] Legend graphic URL fix

---

doc/en/user/source/datadirectory/setting.rst
src/platform/src/main/java/org/geoserver/platform/GeoServerResourceLoader.java
src/platform/src/test/java/org/geoserver/platform/GeoServerResourceLoaderTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7630
Target branch: master

[GEOS-7630] Support requiring files to exist for GeoServer startup

---

src/community/geofence-server/src/main/resources/applicationContext.xml

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7652
Runtime dependency on this pull request: https://github.com/geoserver/geofence/pull/78

[GEOS-7652] Add a correct order to geofence-server PropertyOverrideConfigurer

---

src/web/core/src/main/java/org/geoserver/web/data/ConfirmRemovalPanel.html
src/web/core/src/main/java/org/geoserver/web/data/ConfirmRemovalPanel.java
src/web/core/src/main/resources/GeoServerApplication.properties
src/web/core/src/test/java/org/geoserver/web/data/ConfirmRemovalPanelTest.java

https://osgeo-org.atlassian.net/browse/GEOS-5090

[GEOS-5090] Show styles to be deleted in GUI notification

---

src/main/src/main/java/org/geoserver/config/util/SecureXStream.java

Spelling / punctuation / line-ending whitespace

Minor log message cleanups

---

src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/gwc/src/main/resources/geowebcache-core-context.xml
src/gwc/src/test/java/org/geoserver/gwc/GWCTest.java
src/main/src/main/java/applicationContext.xml
src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
src/main/src/main/java/org/geoserver/security/GeoServerSecurityManager.java
src/main/src/main/java/org/geoserver/security/config/BaseSecurityNamedServiceConfig.java
src/main/src/main/java/org/geoserver/security/config/SecurityConfig.java
src/main/src/main/java/org/geoserver/security/config/SecurityManagerConfig.java
src/main/src/main/java/org/geoserver/security/password/MasterPasswordConfig.java
src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java
src/main/src/test/java/org/geoserver/security/GeoServerSecurityManagerTest.java
src/main/src/test/resources/geoserver-environment.properties
src/platform/src/main/java/org/geoserver/platform/GeoServerEnvironment.java
src/platform/src/test/java/org/geoserver/platform/GeoServerEnvironmentTest.java
src/web/core/src/main/java/org/geoserver/web/data/layer/NewLayerPage.java
src/web/core/src/main/java/org/geoserver/web/data/layer/NewLayerPageProvider.java
src/web/core/src/main/java/org/geoserver/web/data/store/AbstractCoverageStorePage.java
src/web/core/src/main/java/org/geoserver/web/data/store/AbstractDataAccessPage.java
src/web/core/src/main/java/org/geoserver/web/data/store/AbstractWMSStorePage.java
src/web/core/src/main/java/org/geoserver/web/data/store/CoverageStoreEditPage.java
src/web/core/src/main/java/org/geoserver/web/data/store/CoverageStoreNewPage.java
src/web/core/src/main/java/org/geoserver/web/data/store/DataAccessEditPage.java
src/web/core/src/main/java/org/geoserver/web/data/store/DataAccessNewPage.java
src/web/core/src/main/java/org/geoserver/web/data/store/DefaultDataStoreEditPanel.java
src/web/core/src/main/java/org/geoserver/web/data/store/WMSStoreEditPage.java
src/web/core/src/main/java/org/geoserver/web/data/store/WMSStoreNewPage.java
src/web/core/src/main/java/org/geoserver/web/services/BaseServiceAdminPage.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/diskquota/DiskQuotaSettingsPage.java

--- WARNING: requires GeoWebCache PR GeoWebCache/geowebcache#408

PR: (GEOS-7614) Allowing GeoServer to store property placeholders as templates into the catalog

---

src/community/release/ext-gwc-distributed.xml

See https://osgeo-org.atlassian.net/browse/GEOS-7657

[GEOS-7657] Add missing jar to gwc-distributed community module.

---

src/main/src/main/java/org/geoserver/security/decorators/DecoratingStructuredGridCoverage2DReader.java
src/main/src/main/java/org/geoserver/security/decorators/DefaultSecureDataFactory.java
src/main/src/main/java/org/geoserver/security/decorators/SecuredGridCoverage2DReader.java
src/main/src/main/java/org/geoserver/security/decorators/SecuredStructuredGridCoverage2DReader.java
src/main/src/test/java/org/geoserver/security/decorators/SecuredGridCoverage2DReaderTest.java

Make secure decorators supporting StructuredGridCoverage2DReaders

[GEOS-7644]: Backport to 2.8.x

---

src/main/src/main/java/org/geoserver/security/decorators/DecoratingStructuredGridCoverage2DReader.java
src/main/src/main/java/org/geoserver/security/decorators/DefaultSecureDataFactory.java
src/main/src/main/java/org/geoserver/security/decorators/SecuredGridCoverage2DReader.java
src/main/src/main/java/org/geoserver/security/decorators/SecuredStructuredGridCoverage2DReader.java
src/main/src/test/java/org/geoserver/security/decorators/SecuredGridCoverage2DReaderTest.java

Make secure decorators support StructuredGridCoverage2DReaders

[GEOS-7644]: Backport to 2.9.x

---

src/community/jms-cluster/jms-geoserver/pom.xml
src/community/script/pom.xml
src/main/pom.xml
src/ows/src/main/java/org/geoserver/ows/util/OwsUtils.java
src/pom.xml
src/rest/pom.xml
src/web/security/core/src/main/java/org/geoserver/security/web/ConfirmRemovalNamedServicePanel.java
src/web/security/core/src/main/java/org/geoserver/security/web/data/ConfirmRemovalDataAccessRulePanel.java
src/web/security/core/src/main/java/org/geoserver/security/web/group/ConfirmRemovalGroupPanel.java
src/web/security/core/src/main/java/org/geoserver/security/web/role/ConfirmRemovalRolePanel.java
src/web/security/core/src/main/java/org/geoserver/security/web/service/ConfirmRemovalServicePanel.java
src/web/security/core/src/main/java/org/geoserver/security/web/user/ConfirmRemovalUserPanel.java

Update dependencies to avoid upstream bugs. Backport to 2.9.x

---

src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/gwc/src/test/java/org/geoserver/gwc/GWCDataSecurityChallengeIntegrationTest.java

[GEOS-7632] Fix WMS endpoint possibly returning cached tiles to unauthorized users. Backport to 2.9.x

---

.travis.yml

See: https://sourceforge.net/p/geoserver/mailman/message/35248797/

Add Travis CI coverage of communityRelease profile

---

src/community/geogig/src/main/java/org/geogig/geoserver/config/ConfigStore.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/GeoServerGeoGigRepositoryResolver.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryCache.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryInfo.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryManager.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/GeoServerRepositoryProvider.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/InitCommandResource.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/InitRequestHandler.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/repository/RepositoryEditFormPanel.java
src/community/geogig/src/main/resources/applicationContext.xml
src/community/geogig/src/test/java/org/geogig/geoserver/config/ConfigStoreTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/GeoServerFunctionalTestContext.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/PluginWebAPICucumberHooks.java
src/community/geogig/src/test/java/org/geogig/geoserver/rest/GeoGigWebAPIIntegrationTest.java
src/web/app/pom.xml

- Adapt plugin to Repository refactor
- Adapt plugin to PG repository ID changes in GeoGig
- Fix overly aggressive repository closing

Fix GeoGig plugin to align with GeoGig core changes

---

doc/en/user/source/styling/sld-extensions/pointsymbols.rst

@jodygarnett Can you give this a quick review?

updated point symbols doc to reflect current bulk wkt behaviour

---

doc/en/user/source/community/wps-download/index.rst
src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadEstimatorProcess.java
src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadProcess.java
src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterDownload.java
src/community/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java

PR for JIRA GEOS-7669 (ability to select band indices for raster data downloads with WPS). 
[https://osgeo-org.atlassian.net/browse/GEOS-7669](url)
Affects wps-download module.

Added ability to select band indices for raster data downloads

---

doc/en/user/source/community/wps-download/index.rst
src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadEstimatorProcess.java
src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadProcess.java
src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterDownload.java
src/community/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java

[GOES-7669] Added ability to select band indices for raster data downloads

---

doc/en/user/source/rest/api/styles.rst
src/restconfig/src/main/java/org/geoserver/catalog/rest/StyleResource.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/StyleTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7627
(incorrect JIRA ID fixed thanks to @afabiani)

[GEOS-7627] Support "recurse" deletion of style referenced by layers via REST

---

build/build_release.sh
doc/en/release/README.txt

See [GEOS-6611](https://osgeo-org.atlassian.net/browse/GEOS-6611)

Adding a README to the HTML release artifact

---

src/extension/security/cas/src/main/java/applicationContext.xml

https://osgeo-org.atlassian.net/browse/GEOS-7670
- removing eagerlyCreateSessions property from SingleSignOutHttpSessionListener bean

[GEOS-7670] CAS: Fixing context initialisation

---

doc/en/user/Makefile
doc/en/user/source/filter/function_reference.rst

seems to have a bonus pdf fix included.

fix documentation [GEOS-7680]

---

doc/en/user/source/data/raster/imagemosaic/configuration.rst

GeoServer Documentation update for GeoTools improvement:
https://github.com/geotools/geotools/pull/1271

Setting up ImageMosaic doc for CoverageNameCollector [GEOT-5481]

---

src/community/geofence-server/src/main/java/org/geoserver/geofence/rest/RulesRestController.java
src/community/geofence-server/src/test/java/org/geoserver/geofence/rest/RulesRestControllerTest.java

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7647
Mailing list discussion: http://osgeo-org.1560.x6.nabble.com/Extending-GeoFence-REST-interface-td5276626.html

[GEOS-7647] Add REST entry point to GeoFence for moving rules to a target priority

---

src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/ImporterIntegrationTest.java
src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/RequestContextListener.java
src/extension/importer/rest/src/test/resources/applicationContext.xml

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7676
This pull request also provides a test case for this.

[GEOS-7676] Makes the importer share the request context when starting a job asynchronously

---

src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java
src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/ImporterIntegrationTest.java

- Fix for JIRA GEOS-7738 Importer should preserve auth on async requests

PR Backport - Fix for JIRA GEOS-7738 Importer should preserve auth on async requests

---

src/platform/src/main/java/org/geoserver/platform/resource/ResourceNotification.java

See https://osgeo-org.atlassian.net/browse/GEOS-7740

[GEOS-7740] Make ResourceNotification serializable

---

src/platform/src/main/java/org/geoserver/platform/resource/FileSystemResourceStore.java

Depends upon https://github.com/geoserver/geoserver/pull/1811; Travis build will fail until that PR is merged to master.

[GEOS-7651] Use IOUtils rename method for FileSystemResource

---

src/platform/src/main/java/org/geoserver/platform/resource/FileSystemResourceStore.java

Slightly hacky method that does not depend upon https://github.com/geoserver/geoserver/pull/1811. This should be sufficient to fix GEOS-7651 for 2.9.x and earlier in a way that does not require API changes.

[GEOS-7651] Use IOUtils rename method for FileSystemResource (2.9.x)

---

src/release/installer/mac/build.sh
src/release/installer/mac/codesign-geoserver-app.sh
src/release/installer/mac/dmgbuild_settings.py

* Add code-signing support for GeoServer.app bundle on OS X
* Migrate OS X DMG generation to dmgbuild utility; no GUI login required

OS X App bundle improvements

---

src/community/jdbcstore/src/main/java/org/geoserver/jdbcstore/JDBCResourceStore.java
src/community/jdbcstore/src/main/resources/jdbcstore.properties
src/community/jdbcstore/src/main/resources/jdbcstore.properties.h2
src/community/jdbcstore/src/main/resources/jdbcstore.properties.postgres

Following up the discussion in https://github.com/geoserver/geoserver/pull/1821

[GEOS-7748] JdbcResourceStore: fix ignore directories

---

src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
src/gwc/src/test/java/org/geoserver/gwc/layer/GeoServerTileLayerTest.java
src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
src/web/core/src/main/java/org/geoserver/web/data/store/AbstractCoverageStorePage.java
src/web/core/src/main/java/org/geoserver/web/data/store/AbstractDataAccessPage.java
src/web/core/src/main/java/org/geoserver/web/data/store/AbstractWMSStorePage.java
src/web/core/src/main/java/org/geoserver/web/data/store/CoverageStoreEditPage.java
src/web/core/src/main/java/org/geoserver/web/data/store/CoverageStoreNewPage.java
src/web/core/src/main/java/org/geoserver/web/data/store/DataAccessEditPage.java
src/web/core/src/main/java/org/geoserver/web/data/store/DataAccessNewPage.java
src/web/core/src/main/java/org/geoserver/web/data/store/WMSStoreEditPage.java
src/web/core/src/main/java/org/geoserver/web/data/store/WMSStoreNewPage.java
src/web/core/src/test/java/org/geoserver/web/data/store/CoverageStoreEditPageTest.java
src/web/core/src/test/java/org/geoserver/web/data/store/DataAccessEditPageTest.java

Make use of the correct ResourcePool "clone" methods everywhere

[GEOS-7753] - Cannot update existing store configuration, GeoServer complains with a "store already exists" error

---

src/main/src/main/java/applicationContext.xml
src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
src/main/src/main/java/org/geoserver/catalog/ResourcePoolInitializer.java
src/main/src/main/java/org/geoserver/util/EntityResolverProvider.java
src/main/src/test/java/org/geoserver/catalog/1.3.0Capabilities-xxe.xml
src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java
src/web/core/src/main/java/org/geoserver/web/data/store/WMSStoreNewPage.java

No known usable attack vectors as the WMS client code parsing caps does not report details about the parse fail, and cascaded GetFeatureInfo was alredy covered, but just to be safe...

Follow up on GEOT-5514 (2.9.x branch)

---

src/main/src/main/java/applicationContext.xml
src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
src/main/src/main/java/org/geoserver/catalog/ResourcePoolInitializer.java
src/main/src/main/java/org/geoserver/util/EntityResolverProvider.java
src/main/src/test/java/org/geoserver/catalog/1.3.0Capabilities-xxe.xml
src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java
src/web/core/src/main/java/org/geoserver/web/data/store/WMSStoreNewPage.java

No known usable attack vectors as the WMS client code parsing caps does not report details about the parse fail, and cascaded GetFeatureInfo was alredy covered, but just to be safe...
Depends on https://github.com/geotools/geotools/pull/1318

Follow up on GEOT-5514.

---

src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/MultiDimensionalExtension.java
src/community/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/MultiDimensionalExtensionTest.java

This pull request makes sure that the bounding box coordinate reference system is correctly updated and adds a test case for this. 
https://osgeo-org.atlassian.net/browse/GEOS-7762

[GEOS-7762] Validates the provided matrix tile set and updates bounding box CRS

---

src/main/src/main/java/org/geoserver/catalog/CoverageViewReader.java

This pull request makes CoverageViewReader adds the BANDS parameter descriptor only if the delegate reader format doesn't have it, avoiding the reported exception.
Since the provided bands selection values will not make sense to the delegate reader CoverageViewRead will not forward that parameter anymore.
- https://osgeo-org.atlassian.net/browse/GEOS-7773
- https://osgeo-org.atlassian.net/browse/GEOS-7774
There is no tests updates or new tests, this code execution already has tests coverage and this issues would have only happened if the imagemoasic and netcdf bands support had been merged.

[GEOS-7773][GEOS-7774] Makes CoverageViewReader handle BANDS parameter properly

---

doc/en/user/source/extensions/inspire/using.rst

https://osgeo-org.atlassian.net/browse/GEOS-7781

[GEOS-7781] Update INSPIRE community module documentation with specific WMTS service info (backport 2.9.x)

---

src/wms/src/main/java/org/geoserver/wms/map/GetMapXmlReader.java
src/wms/src/test/java/org/geoserver/wms/map/GetMapXmlReaderTest.java
src/wms/src/test/resources/org/geoserver/wms/map/WMSPostLayerFeatureConstraintFilter.xml

Adds the already parsed filter to the request parse result along side the layers and styles.
Added test to check the addition of filters.

[GEOS-7766] Adds parsed filter to parsed WMS POST request

---

data/release/demo/WCS_getCoverage_2.0.1_scale_factor.xml

https://osgeo-org.atlassian.net/browse/GEOS-7780
This pull request targets master.

[GEOS-7780] Add WCS scale factor XML demo

---

src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetFeatureInfoIntegrationTest.java
src/wms/src/test/resources/org/geoserver/wms/wms_1_3/genericLines.properties
src/wms/src/test/resources/org/geoserver/wms/wms_1_3/genericLines.sld

https://osgeo-org.atlassian.net/browse/GEOS-7570
The actual fix for this is performed by this GeoTools pull request:
https://github.com/geotools/geotools/pull/1329
This pull request only adds a new test case based on this issue.

[GEOS-7570] Add test case for GetFeatureInfo with generic geometries

---

src/extension/csw/core/src/test/java/org/geoserver/csw/GetRecordByIdTest.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteTest.java
src/main/src/main/java/org/geoserver/util/EntityResolverProvider.java
src/main/src/main/java/org/geoserver/util/NoExternalEntityResolver.java
src/wcs1_0/src/test/java/org/geoserver/wcs/GetCoverageTest.java
src/wcs1_1/src/test/java/org/geoserver/wcs/GetCoverageTest.java
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/xml/DescribeCoverageTest.java
src/wfs/src/test/java/org/geoserver/wfs/ExternalEntitiesTest.java

Depends on https://github.com/geotools/geotools/pull/1340

Rename NoExternalEntityResolver to PreventLocalEntityResolver

---

src/web/core/src/main/java/org/geoserver/web/data/layer/CoverageViewEditor.java
src/web/core/src/test/java/org/geoserver/web/data/layer/CoverageViewEditorTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7789
This pull request also adds a test case.
Backport of pull request: https://github.com/geoserver/geoserver/pull/1878

[GEOS-7789] Make output bands show bands index when creating a coverage view (backport 2.8.x)

---

src/community/vectortiles/src/main/java/no/ecc/vectortile/VectorTileEncoderNoClip.java
src/community/vectortiles/src/main/java/org/geoserver/wms/topojson/TopoJSONEncoder.java
src/community/vectortiles/src/main/java/org/geoserver/wms/vector/PipelineBuilder.java
src/community/vectortiles/src/main/java/org/geoserver/wms/vector/VectorTileMapOutputFormat.java
src/community/vectortiles/src/main/java/org/geotools/renderer/lite/VectorMapRenderUtils.java

formating changes - ran Geoserver code formatter + removed commented out code

---

src/community/vectortiles/src/main/java/org/geoserver/wms/vector/PipelineBuilder.java
src/community/vectortiles/src/test/java/org/geoserver/wms/vector/ClipRemoveDegenerateTest.java

This is the same as https://github.com/geoserver/geoserver/pull/1624 except this does NOT contain the formating changes as well (moved to separate PR).

GEOS-7557 - filter clipped geometries so degenerate geometries are removed

---

src/release/installer/win/GeoServerEXE.nsi

For details see: https://osgeo-org.atlassian.net/browse/GEOS-7677

Update jetty port specified by installer [GEOS-7677]

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/ExternalGraphicPanel.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleNewPageTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7702

[GEOS-7702] Fix legend autofill NPE

---

src/extension/grib/src/test/java/org/geoserver/catalog/CoverageViewReaderTest.java
src/main/src/main/java/org/geoserver/catalog/CoverageViewReader.java
src/main/src/main/java/org/geoserver/catalog/SingleGridCoverage2DReader.java
src/wms/src/main/java/org/geoserver/wms/map/RenderedImageMapOutputFormat.java
src/wms/src/test/java/org/geoserver/wms/map/RenderedImageMapOutputFormatTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7731
Travis Failure is expected.
https://github.com/geotools/geotools/pull/1353 need to be merged first to make this PR green

[GEOS-7731] Support of AbstractGridFormat.BANDS parameter for CoverageViewReader - Backport to 2.9.x

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/LayerAssociationPanel.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7797
In addition to a test case for the error in question, also added a generic test case for the Publishing tab.

[GEOS-7797] Add null check to Style Editor Publishing Tab

---

src/community/geofence-server/src/main/java/org/geoserver/geofence/internal/InternalUserResolver.java
src/community/geofence-server/src/test/java/org/geoserver/geofence/internal/InternalUserResolverTest.java

PR for [GEOS-7803] GeoFence Embedded does not check for plain Rule Services

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/AbstractStylePage.java

https://osgeo-org.atlassian.net/browse/GEOS-7691

[GEOS-7691] Update OL preview on save without reloading page

---

src/community/geofence-server/src/main/java/org/geoserver/geofence/internal/InternalUserResolver.java
src/community/geofence-server/src/test/java/org/geoserver/geofence/internal/InternalUserResolverTest.java

[2.9.x Backport] PR for (GEOS-7803) GeoFence Embedder does not check for plain Rule Services

---

src/community/geofence-server/src/main/java/org/geoserver/geofence/internal/InternalUserResolver.java
src/community/geofence-server/src/test/java/org/geoserver/geofence/internal/InternalUserResolverTest.java

[2.10.x Backport] PR for (GEOS-7803) GeoFence Embedder does not check for plain Rule Services

---

src/release/installer/win/GeoServerEXE.nsi
src/release/installer/win/wrapper.conf

See: https://osgeo-org.atlassian.net/browse/GEOS-7677

Pass service wrapper port setting to jetty [GEOS-7677]

---

src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/WFSPPIO.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteTest.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/places-FeatureCollectionLocation.xml

See [GEOS-5663](https://osgeo-org.atlassian.net/browse/GEOS-5663) for more details.

fix miss initialized flag in WFSPPIO to fix GEOS-5663

---

src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/WFSPPIO.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteTest.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/places-FeatureCollectionLocation.xml

backport of https://github.com/geoserver/geoserver/pull/1928

Backport of GEOS-5663 to 2.10.x

---

src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
src/restconfig/src/main/java/org/geoserver/catalog/rest/CoverageResource.java
src/restconfig/src/main/java/org/geoserver/catalog/rest/CoverageStoreResource.java
src/restconfig/src/main/java/org/geoserver/catalog/rest/DataStoreResource.java
src/restconfig/src/main/java/org/geoserver/catalog/rest/FeatureTypeResource.java
src/restconfig/src/main/java/org/geoserver/catalog/rest/LayerGroupResource.java
src/restconfig/src/main/java/org/geoserver/catalog/rest/LayerResource.java
src/restconfig/src/main/java/org/geoserver/catalog/rest/WMSLayerResource.java
src/restconfig/src/main/java/org/geoserver/catalog/rest/WMSStoreResource.java
src/restconfig/src/main/java/org/geoserver/service/rest/WCSSettingsResource.java
src/restconfig/src/main/java/org/geoserver/service/rest/WFSSettingsResource.java
src/restconfig/src/main/java/org/geoserver/service/rest/WMSSettingsResource.java
src/restconfig/src/test/java/org/geoserver/service/rest/WCSSettingsTest.java
src/restconfig/src/test/java/org/geoserver/service/rest/WFSSettingsTest.java
src/restconfig/src/test/java/org/geoserver/service/rest/WMSSettingsTest.java
src/wms/src/main/java/org/geoserver/wms/WMSXStreamLoader.java

https://osgeo-org.atlassian.net/browse/GEOS-7822
This fix uses the same approach as in https://github.com/geoserver/geoserver/pull/1541, but for ServiceInfo instead of CatalogInfo this time around

[GEOS-7822] Support unset primitive fields on REST PUT against ServiceInfo

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/AbstractStylePage.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7828

[GEOS-7828] Show style page error messages after clicking submit

---

src/restconfig/src/main/java/org/geoserver/service/rest/templates/wcsSettings.ftl
src/restconfig/src/main/java/org/geoserver/service/rest/templates/wfsSettings.ftl
src/restconfig/src/main/java/org/geoserver/service/rest/templates/wmsSettings.ftl
src/restconfig/src/test/java/org/geoserver/service/rest/LocalWCSSettingsTest.java
src/restconfig/src/test/java/org/geoserver/service/rest/LocalWFSSettingsTest.java
src/restconfig/src/test/java/org/geoserver/service/rest/LocalWMSSettingsTest.java
src/restconfig/src/test/java/org/geoserver/service/rest/WCSSettingsTest.java
src/restconfig/src/test/java/org/geoserver/service/rest/WFSSettingsTest.java
src/restconfig/src/test/java/org/geoserver/service/rest/WMSSettingsTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7821
Added `!` to most properties (show "" when a value is null instead of throwing an error).
Added proper validation and parsing for list properties.
Minor HTML syntax fixup.
Minimal HTML GET test cases.

[GEOS-7821] Fixup gs-restconfig services ftl templates and add minimal  HTML tests

---

src/security/jdbc/src/main/java/org/geoserver/security/jdbc/JDBCRoleService.java
src/security/jdbc/src/test/resources/org/geoserver/security/jdbc/insertroles.sql
src/security/jdbc/src/test/resources/org/geoserver/security/jdbc/rolesddl.xml

Weird case which may happen in some situations where the table has a different definition (see rolesddl.xml sample in the DB2 test use case).

PR - Fix for (GEOS-7806) JDBCRoleService may cause NPE for roles with NULL property name

---

src/main/src/main/java/org/geoserver/GeoserverInitStartupListener.java

[GEOS-7464] Using this tile cache cleans up the tile cache at the end of a request with very large images a lot faster

---

src/main/src/main/java/org/geoserver/catalog/CascadeDeleteVisitor.java
src/main/src/main/java/org/geoserver/catalog/CascadeRemovalReporter.java
src/main/src/test/java/org/geoserver/catalog/impl/CascadeDeleteVisitorTest.java
src/main/src/test/java/org/geoserver/catalog/impl/CascadeRemovalReporterTest.java
src/main/src/test/java/org/geoserver/catalog/impl/CascadeVisitorAbstractTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7857

[GEOS-7857] Fix CascadeDeleteVisitor for nested layer groups

---

src/web/core/src/main/java/org/geoserver/web/data/workspace/WorkspaceEditPage$SettingsPanel.html

https://osgeo-org.atlassian.net/browse/GEOS-7760

[GEOS-7760] Fix padding on workspace settings

---

src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java
src/wms/src/test/java/org/geoserver/wms/WMSMockData.java

https://osgeo-org.atlassian.net/browse/GEOS-7852

[GEOS-7852] Ensure passed catalog objects exist when calling setDefault

---

src/community/release/ext-geofence-server.xml

https://osgeo-org.atlassian.net/browse/GEOS-7870

[GEOS-7870] Exclude posgis jars from geofence-server build

---

src/main/src/main/java/org/geoserver/GeoserverInitStartupListener.java
src/main/src/test/java/org/geoserver/catalog/CatalogIntegrationTest.java
src/main/src/test/java/org/geoserver/config/util/XStreamPersisterTest.java
src/web/core/src/test/java/org/geoserver/web/wicket/CRSPanelTest.java

Based on https://github.com/geotools/geotools/pull/1394, not sure if it will work without

Fix build after fast lookup changes, use harder to lookup CRSs

---

src/main/src/main/java/org/geoserver/ManifestLoader.java

Thank you to Joop van de Wege for reporting and providing a fix for this issue: https://osgeo-org.atlassian.net/browse/GEOS-7838

[GEOS-7838] Fix for manifest loader

---

src/main/src/main/java/org/geoserver/catalog/CoverageViewReader.java

This is the backport of this pull request: https://github.com/geoserver/geoserver/pull/1856

[GEOS-7773][GEOS-7774] Makes CoverageViewReader handle BANDS parameter properly (backport 2.9.x)

---

src/extension/gdal/src/main/java/org/geoserver/gdal/GDALStatus.java

https://osgeo-org.atlassian.net/browse/GEOS-7882

[GEOS-7882] Fix status NPE when using custom GDAL

---

src/main/src/main/java/org/geoserver/config/impl/GeoServerInfoImpl.java
src/main/src/test/java/org/geoserver/config/GeoServerImplTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7890

[GEOS-7890] Fix false negative in GeoServerInfoImpl.equals()

---

src/main/src/main/java/org/geoserver/config/impl/LoggingInfoImpl.java
src/main/src/test/java/org/geoserver/config/GeoServerImplTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7891

[GEOS-7891] Support ModificationProxies in LoggingInfoImpl.equals

---

doc/en/user/source/community/wmts-multidimensional/index.rst
doc/en/user/source/services/wms/basics.rst
doc/en/user/source/services/wms/reference.rst

Also a couple of other minor doc corrections that showed up during test.

[GEOS-7889] Fix GetMap reference docs (1.3 -> 1.3.0)

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/FeatureChainingWfsTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7860
See discussion on geoserver-devel mailing list:
http://osgeo-org.1560.x6.nabble.com/app-schema-test-keeps-on-failing-locally-td5299512.html

Fix test for ex schemaLocation includes [GEOS-7860]

---

doc/en/user/source/filter/function_reference.rst

Adds sin(). Also adds some missing formatting from GEOS-7680.

[GEOS-7445] Fix filter reference docs.

---

doc/en/user/source/configuration/status.rst

See https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-6269

[GEOS-6269] Update documentation for status page to match image.

---

doc/en/user/source/data/cascaded/wms.rst

see https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-6911

[GEOS-6911] Update documentation to remove obsolete authentication limitation

---

src/community/geogig/src/test/java/org/geogig/geoserver/functional/GeoServerFunctionalTestContext.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/RunWebAPIFunctionalTest.java

Update geogig plugin with latest functional test changes.

---

src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupEditPage.java
src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupEntryPanel.java
src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupListPanel.java
src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerListPanel.java
src/web/core/src/main/java/org/geoserver/web/data/layergroup/RootLayerEntryPanel.java
src/web/core/src/test/java/org/geoserver/web/data/layergroup/LayerGroupBaseTest.java
src/web/core/src/test/java/org/geoserver/web/data/layergroup/LayerGroupEditPageTest.java

Hi @tbarsballe I've added a small change that apparently succeeds in bringing back the chosen workspace to the server side. Could you double check, and if you like the change, merge?

[GEOS-7342] Filter layers and layer groups by workspace when adding to layer group

---

src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
src/ows/src/main/java/org/geoserver/ows/HttpErrorCodeException.java
src/ows/src/test/java/org/geoserver/ows/DispatcherTest.java
src/ows/src/test/java/org/geoserver/ows/HelloWorld.java
src/ows/src/test/java/org/geoserver/ows/applicationContext.xml

(cherry picked from commit a1bebe6c5e58bb9c0ec8f28e0fa99b70a4474a8a)

GEOS-7933: Adding contentType to HttpErrorCodeException, 2.10.x backport

---

src/community/jms-cluster/jms-commons/src/main/java/org/geoserver/cluster/client/JMSContainer.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/CatalogUtils.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/server/JMSCatalogListener.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/JmsEventsListener.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/JmsLayerGroupsTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/JmsStylesTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsServiceHandlerTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsWorkspaceHandlerTest.java
src/community/jms-cluster/jms-geoserver/src/test/resources/TestContext.xml
src/community/jms-cluster/jms-geoserver/src/test/resources/test_style.sld

- https://osgeo-org.atlassian.net/browse/GEOS-7947
- https://osgeo-org.atlassian.net/browse/GEOS-7948
This PR also adds integration tests for the handling of new styles and new layers group events.

[GEOS-7947][GEOS-7948] Fix JMS styles and layer groups handling

---

src/community/jms-cluster/jms-commons/src/main/java/org/geoserver/cluster/client/JMSContainer.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/CatalogUtils.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/server/JMSCatalogListener.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/JmsEventsListener.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/JmsLayerGroupsTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/JmsStylesTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsServiceHandlerTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsWorkspaceHandlerTest.java
src/community/jms-cluster/jms-geoserver/src/test/resources/TestContext.xml
src/community/jms-cluster/jms-geoserver/src/test/resources/test_style.sld

Backport of this pull request: https://github.com/geoserver/geoserver/pull/2066
- https://osgeo-org.atlassian.net/browse/GEOS-7947
- https://osgeo-org.atlassian.net/browse/GEOS-7948
This PR also adds integration tests for the handling of new styles and new layers group events.

[GEOS-7947][GEOS-7948] Fix JMS styles and layer groups handling (backport 2.10.x)

---

src/community/jms-cluster/jms-commons/src/main/java/org/geoserver/cluster/client/JMSContainer.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/catalog/CatalogUtils.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/server/JMSCatalogListener.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/JmsEventsListener.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/JmsLayerGroupsTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/JmsStylesTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsServiceHandlerTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsWorkspaceHandlerTest.java
src/community/jms-cluster/jms-geoserver/src/test/resources/TestContext.xml
src/community/jms-cluster/jms-geoserver/src/test/resources/test_style.sld

Backport of this pull request: https://github.com/geoserver/geoserver/pull/2066
- https://osgeo-org.atlassian.net/browse/GEOS-7947
- https://osgeo-org.atlassian.net/browse/GEOS-7948
This PR also adds integration tests for the handling of new styles and new layers group events.

[GEOS-7947][GEOS-7948] Fix JMS styles and layer groups handling (backport 2.9.x)

---

src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java
src/restconfig/src/main/java/org/geoserver/catalog/rest/CoverageResource.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/CoverageTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7631 provides the background. I took a
different approach to that suggest by the reporter to ensure keywords and title are
set up correctly too.

[GEOS-7631] Set store name on REST upload.

---

src/web/core/src/main/java/org/geoserver/web/data/store/panel/FileModel.java
src/web/core/src/test/java/org/geoserver/web/data/store/panel/FileModelTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-7905 for background.
This probably addresses (part of) https://osgeo-org.atlassian.net/browse/GEOS-4616 too

[GEOS-7905] Handle store display after REST upload.

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleAdminPanel.java
src/web/wms/src/main/java/org/geoserver/wms/web/data/StylePage.java
src/web/wms/src/main/resources/GeoServerApplication.properties
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageRenameTest.java

https://osgeo-org.atlassian.net/browse/GEOS-7752
Disabled renaming of default styles, since this causes problems elsewhere

[GEOS-7752] - Disabling the style name when editing a default style

---

src/main/src/main/java/org/geoserver/GeoServerNodeData.java
src/main/src/test/java/org/geoserver/GeoServerNodeDataTest.java
src/web/core/src/main/java/org/geoserver/web/DefaultGeoServerNodeInfo.java
src/web/core/src/main/java/org/geoserver/web/GeoServerNodeInfo.java
src/web/core/src/test/java/org/geoserver/web/CustomGeoServerNodeIdTest.java

Issue link - https://osgeo-org.atlassian.net/browse/GEOS-7960

GEOS-7960: Factoring out GeoServerNodeData class from GeoServerNodeInfo.

---

src/main/src/main/java/org/geoserver/GeoServerNodeData.java
src/main/src/test/java/org/geoserver/GeoServerNodeDataTest.java
src/web/core/src/main/java/org/geoserver/web/DefaultGeoServerNodeInfo.java
src/web/core/src/main/java/org/geoserver/web/GeoServerNodeInfo.java
src/web/core/src/test/java/org/geoserver/web/CustomGeoServerNodeIdTest.java

Backport to 2.10.x. Prepping the pull request to ensure the travis and the build is happy but before I merge I would like to hear from one of the PSC if this one is suitable for backport as it's not a bug fix.

GEOS-7960: Factoring out GeoServerNodeData class from GeoServerNodeInfo (2.10.x backport)

---

src/gwc/src/main/java/org/geoserver/gwc/config/GWCInitializer.java

Found another linear scan that can be parallelized, helps some in the non cached startup time (used to be between 230 and 290 seconds, latest tests with this one seem to be reliably on 200 seconds)

Further parallelize GWC config loading

---

src/main/src/main/java/org/geoserver/ows/LocalHttpServletRequest.java
src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java

See: https://osgeo-org.atlassian.net/browse/GEOS-7900

[GEOS-7900] HttpServletRequestAware: store request in ThreadLocal

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/AbstractStylePage.java
src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleEditPage.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java
src/web/wms/src/test/resources/org/geoserver/wms/web/data/testMoveStyle.sld
src/web/wms/src/test/resources/org/geoserver/wms/web/data/testMoveStyleUpdated.sld

Backports two bug fixes for the StyleEditPage to 2.10.x

[Backport] GEOS-7991-null-legend-2.10.x

---

src/main/src/main/java/org/geoserver/catalog/ResourcePool.java

This one is a little tricky, I don't have a test right now because the actual conditions under which this is a problem are extremely specific:
- Using a non-default ResourceStore. When doing this no base directory gets set in GeoServerResourceLoader, which causes a few other things to fail when they start trying to munge things into a File based off the base directory.
- Using a custom GridFormat AND a custom DataStorePanelInfo implementation for it. We're testing a GridFormats that use things like S3 and HDFS internally right now, which have custom URL protocols (eg. s3://). We have a custom UI that skips all file-y validations for these URLs. However the ResourcePool still attempts to convert this to a file in order to pass to the GridReader.
Thankfully this is all fixed by using …

GEOS-7937 - Remove use of deprecated Files method in ResourcePool

---

src/gwc/src/main/java/org/geoserver/gwc/layer/DefaultTileLayerCatalog.java

One last speedup to the integrated GWC, allows to startup the 40k layers sample data dir within 45s on a hot cache.
Rationale: the DefaultCatalogFacade is fully memory based, there is no reason not to have the same for the DefaultTileLayerCatalog. A jdbc based configuration should have its own JDBC based alternative (I have the strong impression that JDBCConfig is not actually used in combination with embedded GWC anyways)

DefaultTileLayerCatalog to mimick the GS own default catalog and keep everything in memory

---

src/community/jdbc-metrics/pom.xml
src/community/jdbc-metrics/src/main/java/org/geoserver/jdbc/metrics/RequestMetricsCallback.java
src/community/jdbc-metrics/src/main/java/org/geoserver/jdbc/metrics/RequestMetricsController.java
src/community/jdbc-metrics/src/main/java/org/geoserver/jdbc/metrics/RequestMetricsFactory.java
src/community/jdbc-metrics/src/main/java/org/geoserver/jdbc/metrics/RequestMetricsFilter.java
src/community/jdbc-metrics/src/main/resources/META-INF/services/org.geotools.jdbc.JDBCCallbackFactory
src/community/jdbc-metrics/src/main/resources/applicationContext.xml
src/community/pom.xml

Uses a JDBC feature reader callback to include some timing metrics
about requests that hit database resources.

First cut of a jdbc metrics module.

---

src/extension/control-flow/src/main/java/org/geoserver/flow/ControlFlowCallback.java

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8003
The error that originate this issue is not easy to reproduce (actually not idea how to do it) since it depends on Sping beans initialization race conditions. The normal beans instantiation is already tested by the current tests, so no new tests were added.
This whole situation happens because we don't have a standard way in Spring and GeoServer of marking a bean as the default one and allow extensions to provide an override. The closes mechanism we have right now is the beans priority interface, but this mechanism implies that who is using the beans should expected several beans and use the priority one and this is always not the case.

[GEOS-8003] Remove BeanFactoryPostProcessor callbacks beans invocations

---

src/extension/control-flow/src/main/java/org/geoserver/flow/ControlFlowCallback.java

Backport of pull request: https://github.com/geoserver/geoserver/pull/2126
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8003
The error that originate this issue is not easy to reproduce (actually not idea how to do it) since it depends on Sping beans initialization race conditions. The normal beans instantiation is already tested by the current tests, so no new tests were added.
This whole situation happens because we don't have a standard way in Spring and GeoServer of marking a bean as the default one and allow extensions to provide an override. The closes mechanism we have right now is the beans priority interface, but this mechanism implies that who is using the beans should expected several beans and use the priority one and this is always not the case.

[GEOS-8003] Remove BeanFactoryPostProcessor callbacks beans invocations (backport 2.10.x)

---

src/extension/control-flow/src/main/java/org/geoserver/flow/ControlFlowCallback.java

Backport of pull request: https://github.com/geoserver/geoserver/pull/2126
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8003
The error that originate this issue is not easy to reproduce (actually not idea how to do it) since it depends on Sping beans initialization race conditions. The normal beans instantiation is already tested by the current tests, so no new tests were added.
This whole situation happens because we don't have a standard way in Spring and GeoServer of marking a bean as the default one and allow extensions to provide an override. The closes mechanism we have right now is the beans priority interface, but this mechanism implies that who is using the beans should expected several beans and use the priority one and this is always not the case.

[GEOS-8003] Remove BeanFactoryPostProcessor callbacks beans invocations (backport 2.9.x)

---

src/community/geofence/src/main/java/org/geoserver/geofence/web/GeofencePage.java
src/community/gwc-sqlite/src/main/java/org/geoserver/gwc/web/blob/SqliteMultipartFilter.java
src/community/gwc-sqlite/src/main/resources/applicationContext.xml
src/extension/inspire/src/test/java/org/geoserver/inspire/web/InspirePanelTest.java
src/extension/wps/web-wps/src/main/java/org/geoserver/wps/web/WPSAccessRulePage.java
src/pom.xml
src/web/core/src/main/java/org/geoserver/web/admin/CoverageAccessPage.java
src/web/core/src/main/java/org/geoserver/web/admin/GlobalSettingsPage.java
src/web/core/src/main/java/org/geoserver/web/admin/JAIPage.java
src/web/core/src/main/java/org/geoserver/web/services/BaseServiceAdminPage.java

See https://osgeo-org.atlassian.net/browse/GEOS-7925
Fix wicket multipart upload:
* Upgrade from Wicket 7.1.0 to 7.2.0; this issue was fixed by WICKET-6002.
* Remove CommonsMultipartResolver from gs-gwc-sqlite context

[GEOS-7925] Fix wicket multipart upload

---

src/kml/src/main/java/org/geoserver/kml/KMLEncoder.java
src/kml/src/main/resources/org/geoserver/kml/icon_style_patch.xsl
src/kml/src/test/java/org/geoserver/kml/KMLReflectorTest.java

Attempting to use the technique found here:
http://blog.bdoughan.com/2012/11/using-jaxb-with-xslt-to-produce-html.html

[GEOS-7963] Fixed invalid elements being added to the KML IconStyle.

---

src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
src/wms/src/test/java/org/geoserver/wms/capabilities/GetCapabilitiesSRCOrderTest.java

Hi, a small change related to the issue:
https://osgeo-org.atlassian.net/browse/GEOS-7791

[GEOS-7791] SRS list in wrong order

---

src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/JMSActiveMQFactory.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/events/configuration/JMSServiceModifyEvent.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/configuration/JMSServiceHandler.java
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/server/JMSConfigurationListener.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/JmsServicesTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsServiceHandlerTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsTestServiceInfo.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsTestServiceInfoImpl.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/handlers/configuration/JmsTestServiceLoader.java

This PR amend the services configuration handling in JMS community module. Integration tests for the found issues were added and existing tests improved (removing some annoying exceptions \ logs).
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8026

[GEOS-8026] Fix services configuration events handling in JMS community module

---

src/wfs/src/main/java/org/geoserver/wfs/xml/ApplicationSchemaXSD1.java
src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetFeatureTest.java

This PR just amend some typos and formatting errors that were contributed by this PR https://github.com/geoserver/geoserver/pull/2140.

[GEOS-8017] Amend formatting and fix typos

---

src/wfs/src/main/java/org/geoserver/wfs/InsertElementHandler.java
src/wfs/src/test/java/org/geoserver/wfs/TransactionTest.java
src/wfs/src/test/java/org/geoserver/wfs/v1_1/TransactionTest.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/TransactionTest.java

For more information https://osgeo-org.atlassian.net/browse/GEOS-8042

[GEOS-8042] WFS-T fix for InsertResultsFeatureId order

---

src/wfs/src/main/java/org/geoserver/wfs/InsertElementHandler.java
src/wfs/src/test/java/org/geoserver/wfs/TransactionTest.java
src/wfs/src/test/java/org/geoserver/wfs/v1_1/TransactionTest.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/TransactionTest.java

Depends on GEOT-5684, [PR-1529](https://github.com/geotools/geotools/pull/1529) and GEOT-5683, [PR-1530](https://github.com/geotools/geotools/pull/1530)

[GEOS-8042] WFS-T fix for InsertResultsFeatureId order - backport 2.11.x

---

src/wfs/src/main/java/org/geoserver/wfs/InsertElementHandler.java
src/wfs/src/test/java/org/geoserver/wfs/TransactionTest.java
src/wfs/src/test/java/org/geoserver/wfs/v1_1/TransactionTest.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/TransactionTest.java

Depends on GEOT [PR-1537 ](https://github.com/geotools/geotools/pull/1537) and GEOT [PR-1540](https://github.com/geotools/geotools/pull/1540)

[GEOS-8042] WFS-T fix for InsertResultsFeatureId order - backport 2.10.x

---

src/wfs/src/main/java/org/geoserver/wfs/InsertElementHandler.java
src/wfs/src/test/java/org/geoserver/wfs/TransactionTest.java
src/wfs/src/test/java/org/geoserver/wfs/v1_1/TransactionTest.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/TransactionTest.java

Depends on GEOT [PR-1539](https://github.com/geotools/geotools/pull/1539) and GEOT [PR-1538](https://github.com/geotools/geotools/pull/1538)

[GEOS-8042] WFS-T fix for InsertResultsFeatureId order - backport 2.9.x

---

src/community/notification/src/main/java/org/geoserver/notification/MessageMultiplexer.java
src/community/notification/src/main/java/org/geoserver/notification/NotifierInitializer.java
src/community/notification/src/test/java/org/geoserver/notification/IntegrationTest.java

[GEOS-8076] Notification plugin: Multiplexer keeps opening threads by taking the whole CPU time

---

src/community/jms-cluster/jms-geoserver/pom.xml
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/web/ClusterPage.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/web/ClusterPageTest.java

Fix JMS community module UI and adds a test case.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8078

[GEOS-8078] JMS community module configuration WEB page throws an exception when accesing it

---

src/community/jms-cluster/jms-geoserver/pom.xml
src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/web/ClusterPage.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/impl/web/ClusterPageTest.java

Backport of this pull request: https://github.com/geoserver/geoserver/pull/2232
Fix JMS community module UI and adds a test case.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8078

[GEOS-8078] JMS community module configuration WEB page throws an exception when accesing it (backport 2.11.x)

---

src/restconfig/pom.xml
src/restconfig/src/test/java/org/geoserver/catalog/rest/CoverageStoreTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8038

[GEOS-8038] Intermittent build failure in gs-restconfig CoverageStoreTest.testDeletePurgeAllAfterConfigure (2.10.x)

---

src/restconfig/pom.xml
src/restconfig/src/test/java/org/geoserver/catalog/rest/CoverageStoreTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8038

[GEOS-8038] Intermittent build failure in gs-restconfig CoverageStore Test.testDeletePurgeAllAfterConfigure (2.11.x)

---

doc/en/api/1.0.0/importer.yaml
doc/en/api/1.0.0/importerData.yaml
doc/en/api/1.0.0/importerTasks.yaml
doc/en/api/1.0.0/importerTransforms.yaml
doc/en/pom.xml
doc/en/user/source/rest/index.rst
src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/ImportController.java
src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/ImportDataController.java
src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/ImportTaskController.java
src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/ImportTransformController.java
src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/converters/ImportJSONWriter.java

Importer API docs, plus some cosmetic code changes discovered while writing the docs.

Importer REST API Docs

---

src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesIntegrationTest.java

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8088

[GEOS-8088] WMS 1.3.0 GlobalBoundingBoxForLayerGroups test is locale dependent

---

src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesIntegrationTest.java

Backport of this pull request: https://github.com/geoserver/geoserver/pull/2244
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8088

[GEOS-8088] WMS 1.3.0 GlobalBoundingBoxForLayerGroups test is locale dependent (2.11.x)

---

src/extension/csw/core/src/main/java/org/geoserver/csw/DefaultWebCatalogService.java
src/extension/csw/core/src/test/java/org/geoserver/csw/GetCapabilitiesTest.java

Fix for https://osgeo-org.atlassian.net/browse/GEOS-8052
GeoServer.getService already has logic to deal with virtual services, so that just needed to be hooked up.

[GEOS-8052] Support virtual services for CSW GetCapabilities

---

src/extension/monitor/core/src/main/java/org/geoserver/monitor/auditlog/AuditLogger.java

Monitoring: remove obsolete caching of config files

---

doc/en/user/source/production/config.rst
src/main/src/main/java/org/geoserver/filters/XFrameOptionsFilter.java
src/main/src/test/java/org/geoserver/filters/XFrameOptionsFilterTest.java
src/web/app/src/main/webapp/WEB-INF/web.xml

Set the default X-Frame-Options header to be SAMEORIGIN

Change the default X-Frame-Options header to be SAMEORIGIN

---

src/web/core/src/main/java/org/geoserver/web/LoginFormHTMLInclude.java
src/web/core/src/main/resources/org/geoserver/web/include_login_form.html
src/web/core/src/test/java/org/geoserver/web/LoginFormHTMLIncludeTest.java

This PR disables autocomplete for the default login form, with a system property available to reenable it.

Allow login form autocomplete to be disabled via System Property

---

src/web/core/src/main/java/org/geoserver/web/LoginFormHTMLInclude.java
src/web/core/src/main/resources/org/geoserver/web/include_login_form.html
src/web/core/src/test/java/org/geoserver/web/LoginFormHTMLIncludeTest.java

A backport of https://github.com/geoserver/geoserver/pull/2253

Allow login form autocomplete attribute to be disabled via config (2.10.x)

---

doc/en/user/source/production/config.rst
src/main/src/main/java/org/geoserver/filters/XFrameOptionsFilter.java
src/main/src/test/java/org/geoserver/filters/XFrameOptionsFilterTest.java
src/web/app/src/main/webapp/WEB-INF/web.xml

Backport of https://github.com/geoserver/geoserver/pull/2225

Allow X-Frame-Options header to be customized (2.11.x) 

---

src/web/core/src/main/java/org/geoserver/web/GeoServerHomePage.html

This is effectively just a backport of https://github.com/geoserver/geoserver/commit/e0b67098dd270ef56f20741abeaeef72bf3f2a95 to 2.11.x

[GEOS-8106] Switch contributedContent from fragment to div

---

src/platform/src/test/java/org/geoserver/platform/resource/FileSystemResourceStoreTest.java

@Before and @After were there because I can't manage to make work @Rule with power mockito runner. As no need to power mockito anymore...
Refactor.

[geos-7946], prefer @Rule to @Before end @After as done elsewhere.

---

doc/en/user/source/data/webadmin/layergroups.rst
src/community/geofence-server/pom.xml
src/pom.xml
src/web/core/pom.xml
src/web/core/src/main/java/org/geoserver/web/css/geoserver.css
src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupEntry.java
src/web/core/src/main/java/org/geoserver/web/wicket/ReorderableTablePanel.java

I don't think this can be tested using the Wicket tester but if anyone has suggestions, I'll try :-p
Btw, the flickers at the top of the animation are an issue in the recording program itself and/or my machine local compiz setting (it's the desktop background bleeding though).
Thanks to @nmco for sharing this approach in the geofence-server module.

[GEOS-8111] Add drag and drop support for reordering layers in a layer group

---

src/restconfig/src/main/java/org/geoserver/rest/catalog/FeatureTypeController.java
src/restconfig/src/test/java/org/geoserver/rest/catalog/FeatureTypeTest.java

Adds support for a request to `/workspaces/<ws>/datastores/<ds>/featuretypes[.<format>]` with the query parameter `list=all`.
This parameter value is documented in the [REST API docs](http://docs.geoserver.org/stable/en/user/rest/api/featuretypes.html), but the code ignored the value until now, as discussed in [GEOS-7908](https://osgeo-org.atlassian.net/browse/GEOS-7908). The documented behavior is to return “The union of configured and available” feature types, so this commit updates the FeatureTypeController to return a list of all feature type names for the data source when “list=all”.

[GEOS-7908] REST API: Add support for list=all when listing feature types

---

src/wms/src/main/java/org/geoserver/wms/WMSWorkspaceQualifier.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetMapIntegrationTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8110

[GEOS-8110] Fix IndexOutOfBounds in WMSWorkspaceQualifier

---

src/community/mbstyle/pom.xml
src/community/mbstyle/src/main/java/org/geoserver/community/mbstyle/web/MBStyleHandler.java
src/community/mbstyle/src/test/java/org/geoserver/community/mbstyle/web/MBStyleHandlerTest.java

Should wait until https://github.com/geotools/geotools/pull/1573 is merged.

Backport MBStyle to 2.11.x

---

src/community/mbstyle/src/main/java/org/geoserver/community/mbstyle/MBStyleHandler.java
src/community/mbstyle/src/main/resources/applicationContext.xml
src/community/mbstyle/src/main/resources/org/geoserver/community/mbstyle/template_line.json
src/community/mbstyle/src/main/resources/org/geoserver/community/mbstyle/template_point.json
src/community/mbstyle/src/main/resources/org/geoserver/community/mbstyle/template_polygon.json
src/community/mbstyle/src/main/resources/org/geoserver/community/mbstyle/template_raster.json
src/community/mbstyle/src/test/java/org/geoserver/community/mbstyle/web/MBStyleHandlerTest.java
src/main/src/main/java/org/geoserver/catalog/StyleGenerator.java

Add style generation support for MBStyle, plus some improvements to StyleGenerator error messages.

Add style generation support for MBStyle

---

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/listener/BackupRestoreJobExecutionListener.java
src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/listener/GenericListenersExecutor.java
src/community/backup-restore/core/src/main/resources/applicationContext.xml
src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java
src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/GenericListener.java
src/community/backup-restore/core/src/test/resources/applicationContext.xml

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8124
Adds an extension point that will execute generic listeners.

[GEOS-8124] Add extension point in backup / restore module for generic resources handler

---

src/wms/src/main/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReader.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetLegendGraphicTest.java

- PR refactoring and improved test-case

[Backport to 2.11.x] Fix for GEOS-8128 - SLD static legend dimensions not respected

---

src/wms/src/main/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReader.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetLegendGraphicTest.java

- PR refactoring and improved test-case

[Backport to 2.10.x] Fix for GEOS-8128 - SLD static legend dimensions not respected

---

src/wms/src/main/java/org/geoserver/wms/legendgraphic/GetLegendGraphicKvpReader.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetLegendGraphicTest.java

- PR refactoring and improved test-case

[Backport to 2.9.x] Fix for GEOS-8128 - SLD static legend dimensions not respected

---

src/community/mbstyle/src/main/java/org/geoserver/community/mbstyle/MBStyleHandler.java
src/community/mbstyle/src/main/resources/org/geoserver/community/mbstyle/template_generic.json

Depends upon https://github.com/geotools/geotools/pull/1580

MBStyle - add 'Generic' stlye generation

---

src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/gwc/src/main/java/org/geoserver/gwc/dispatch/GwcServiceProxy.java
src/gwc/src/test/java/org/geoserver/gwc/GWCDataSecurityTest.java
src/gwc/src/test/java/org/geoserver/gwc/GWCTest.java

[GEOS-8041] Do bounding box access checks for all GWC services

---

src/ows/src/test/java/org/geoserver/ows/kvp/TimeKvpParserTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8139

[GEOS-8139] Intermittent off-by-one-second failure in TimeKvpParserTest.testContinuousRelativeInterval

---

src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/gwc/src/main/java/org/geoserver/gwc/dispatch/GwcServiceProxy.java
src/gwc/src/test/java/org/geoserver/gwc/GWCDataSecurityTest.java
src/gwc/src/test/java/org/geoserver/gwc/GWCTest.java

[GEOS-8041] Do bounding box access checks for all GWC services, Backport to 2.11

---

src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/gwc/src/main/java/org/geoserver/gwc/dispatch/GwcServiceProxy.java
src/gwc/src/test/java/org/geoserver/gwc/GWCDataSecurityTest.java
src/gwc/src/test/java/org/geoserver/gwc/GWCTest.java

[GEOS-8041] Do bounding box access checks for all GWC services, Backport to 2.10

---

src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/gwc/src/main/java/org/geoserver/gwc/dispatch/GwcServiceProxy.java
src/gwc/src/test/java/org/geoserver/gwc/GWCDataSecurityTest.java
src/gwc/src/test/java/org/geoserver/gwc/GWCTest.java

Backport of #2329 
2.9 is no longer maintained so anyone who needs this will have to build GeoServer themselves.

[GEOS-8041] Do bounding box access checks for all GWC services, Backport to 2.9

---

src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetFeatureInfoIntegrationTest.java

Backport GEOS-8092 fix to 2.10.x.

[GEOS-8092] 2.10.x Updated the removal of non-queryable layers in a WMS GetFeatureInfo request to remove their corresponding styles and filters.

---

src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/DeferredFileOutputStreamWebMap.java
src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/Pipeline.java
src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/PipelineBuilder.java
src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/VectorTileBuilder.java
src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/VectorTileBuilderFactory.java
src/extension/vectortiles/src/main/java/org/geoserver/wms/vector/VectorTileMapOutputFormat.java
src/extension/vectortiles/src/main/java/org/geotools/renderer/lite/VectorMapRenderUtils.java

Added JavaDocs while I was figuring out how the Vectortiles module works.

Adding javadocs to vector tiles

---

src/community/geogig/src/main/java/org/geogig/geoserver/config/ConfigStore.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/GeoServerContextBuilder.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/LogStore.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/LogStoreInitializer.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryManager.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/GeoServerRepositoryProvider.java
src/community/geogig/src/main/resources/META-INF/services/org.locationtech.geogig.hooks.CommandHook
src/community/geogig/src/main/resources/applicationContext.xml
src/community/geogig/src/test/java/org/geogig/geoserver/HeapResourceStore.java
src/community/geogig/src/test/java/org/geogig/geoserver/config/AbstractLogStoreTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/config/ConfigStoreTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/config/HSQLLogStoreTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/config/SQLiteLogStoreTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/security/SecurityLoggerTestIntegrationTest.java

* Update geogig plugin to have less reliance on a filesystem-backed resource store.
* Revamp the plugin's internal Repository cache utilization

GeoGig: Update plugin to use Resource API

---

src/community/geogig/src/main/java/org/geogig/geoserver/config/ConfigStore.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/GeoServerContextBuilder.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/LogStore.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/LogStoreInitializer.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryManager.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/GeoServerRepositoryProvider.java
src/community/geogig/src/main/resources/META-INF/services/org.locationtech.geogig.hooks.CommandHook
src/community/geogig/src/main/resources/applicationContext.xml
src/community/geogig/src/test/java/org/geogig/geoserver/HeapResourceStore.java
src/community/geogig/src/test/java/org/geogig/geoserver/config/AbstractLogStoreTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/config/ConfigStoreTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/config/HSQLLogStoreTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/config/SQLiteLogStoreTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/security/SecurityLoggerTestIntegrationTest.java

Porting changes made to the plugin for GeoGig from 2.11.x branch to keep master in sync

[forward port] GeoGig: Update plugin to use Resource API

---

src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/WFSPPIO.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ppio/WFSPPIOTest.java
src/main/src/test/java/org/geoserver/data/test/wfs.xml

Fix for [GEOS-8158](https://osgeo-org.atlassian.net/browse/GEOS-8158)

WFSPPIO fails to remove MetaDataProperty attributes

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleAdminPanel.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageRenameTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-7958

[GEOS-7958] Disallow workspacing default styles

---

src/community/geogig/src/main/java/org/geogig/geoserver/rest/ImportExistingRepo.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/GeoGigSettingsPage.html
src/community/geogig/src/main/java/org/geogig/geoserver/web/GeoGigSettingsPage.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/settings/CacheManagerBeanModel.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/settings/CacheStatusPanel.html
src/community/geogig/src/main/java/org/geogig/geoserver/web/settings/CacheStatusPanel.java
src/community/geogig/src/main/resources/GeoServerApplication.properties
src/community/geogig/src/main/resources/applicationContext.xml

New geogig settings page with options to monitor and configure the shared cache

Geogig shared cache 2.11.x

---

src/community/geogig/src/main/java/org/geogig/geoserver/web/GeoGigSettingsPage.html
src/community/geogig/src/main/java/org/geogig/geoserver/web/GeoGigSettingsPage.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/settings/CacheManagerBeanModel.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/settings/CacheStatusPanel.html
src/community/geogig/src/main/java/org/geogig/geoserver/web/settings/CacheStatusPanel.java
src/community/geogig/src/main/resources/GeoServerApplication.properties
src/community/geogig/src/main/resources/applicationContext.xml

New geogig settings page with options to monitor and configure the shared cache

Geogig shared cache 2.10.x

---

src/community/geogig/src/main/java/org/geogig/geoserver/web/GeoGigSettingsPage.html
src/community/geogig/src/main/java/org/geogig/geoserver/web/GeoGigSettingsPage.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/settings/CacheManagerBeanModel.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/settings/CacheStatusPanel.html
src/community/geogig/src/main/java/org/geogig/geoserver/web/settings/CacheStatusPanel.java
src/community/geogig/src/main/resources/GeoServerApplication.properties
src/community/geogig/src/main/resources/applicationContext.xml

New geogig settings page with options to monitor and configure the shared cache

Geogig shared cache 2.9.x

---

src/community/geogig/src/main/java/org/geogig/geoserver/web/GeoGigSettingsPage.html
src/community/geogig/src/main/java/org/geogig/geoserver/web/GeoGigSettingsPage.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/settings/CacheManagerBeanModel.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/settings/CacheStatusPanel.html
src/community/geogig/src/main/java/org/geogig/geoserver/web/settings/CacheStatusPanel.java
src/community/geogig/src/main/resources/GeoServerApplication.properties
src/community/geogig/src/main/resources/applicationContext.xml

New geogig settings page with options to monitor and configure the shared cache

Geogig shared cache 2.12.x

---

src/community/geopkg/src/main/resources/GeoServerApplication.properties
src/community/geopkg/src/main/resources/GeoServerApplication_es.properties
src/community/geopkg/src/main/resources/GeoServerApplication_pl.properties
src/community/geopkg/src/main/resources/GeoServerApplication_ru.properties
src/community/geopkg/src/main/resources/GeoServerApplication_tr.properties
src/web/demo/src/main/resources/GeoServerApplication_de.properties
src/web/demo/src/main/resources/GeoServerApplication_es.properties
src/web/demo/src/main/resources/GeoServerApplication_fr.properties
src/web/demo/src/main/resources/GeoServerApplication_ja.properties
src/web/demo/src/main/resources/GeoServerApplication_ko.properties
src/web/demo/src/main/resources/GeoServerApplication_nl.properties
src/web/demo/src/main/resources/GeoServerApplication_pl.properties
src/web/demo/src/main/resources/GeoServerApplication_pt_BR.properties
src/web/demo/src/main/resources/GeoServerApplication_ro.properties
src/web/demo/src/main/resources/GeoServerApplication_ru.properties
src/web/demo/src/main/resources/GeoServerApplication_sv.properties
src/web/demo/src/main/resources/GeoServerApplication_tr.properties

Fix for https://osgeo-org.atlassian.net/browse/GEOS-8163
Before:
After:

[GEOS-8163] Add display name mappings for GeoPackage output formats

---

src/community/geogig/src/main/java/org/geogig/geoserver/config/GeoServerContextBuilder.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/GeoServerGeoGigRepositoryResolver.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryManager.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/ImportRepoCommandResource.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/InitCommandResource.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/repository/RepositoryEditPanel.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/repository/RepositoryImportPanel.java
src/community/geogig/src/test/java/org/geogig/geoserver/GeoGigTestData.java
src/community/geogig/src/test/java/org/geogig/geoserver/config/RepositoryManagerTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/GeoServerFunctionalTestContext.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/PluginWebAPICucumberHooks.java
src/community/geogig/src/test/java/org/geogig/geoserver/web/repository/CommonPanelTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/web/repository/RepositoryEditPanelTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/web/repository/RepositoryImportPanelTest.java
src/community/geogig/src/test/resources/features/webCommand/PluginInit.feature
src/community/geogig/src/test/resources/features/webCommand/importExistingRepo.feature

Prevent duplicate GeoGig repository names

---

src/community/geogig/src/main/java/org/geogig/geoserver/config/GeoServerContextBuilder.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/GeoServerGeoGigRepositoryResolver.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryManager.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/ImportRepoCommandResource.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/InitCommandResource.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/repository/RepositoryEditPanel.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/repository/RepositoryImportPanel.java
src/community/geogig/src/test/java/org/geogig/geoserver/GeoGigTestData.java
src/community/geogig/src/test/java/org/geogig/geoserver/config/RepositoryManagerTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/GeoServerFunctionalTestContext.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/PluginWebAPICucumberHooks.java
src/community/geogig/src/test/java/org/geogig/geoserver/web/repository/CommonPanelTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/web/repository/RepositoryEditPanelTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/web/repository/RepositoryImportPanelTest.java
src/community/geogig/src/test/resources/features/webCommand/PluginInit.feature
src/community/geogig/src/test/resources/features/webCommand/importExistingRepo.feature

[backport 2.11.x] Prevent duplicate GeoGig repository names

---

src/community/geogig/src/main/java/org/geogig/geoserver/config/GeoServerContextBuilder.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/GeoServerGeoGigRepositoryResolver.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryManager.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/ImportRepoCommandResource.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/InitCommandResource.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/repository/RepositoryEditPanel.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/repository/RepositoryImportPanel.java
src/community/geogig/src/test/java/org/geogig/geoserver/GeoGigTestData.java
src/community/geogig/src/test/java/org/geogig/geoserver/config/RepositoryManagerTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/GeoServerFunctionalTestContext.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/PluginWebAPICucumberHooks.java
src/community/geogig/src/test/java/org/geogig/geoserver/web/repository/CommonPanelTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/web/repository/RepositoryEditPanelTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/web/repository/RepositoryImportPanelTest.java
src/community/geogig/src/test/resources/features/webCommand/PluginInit.feature
src/community/geogig/src/test/resources/features/webCommand/importExistingRepo.feature

[backport 2.10.x] Prevent duplicate GeoGig repository names

---

src/community/geogig/src/main/java/org/geogig/geoserver/config/GeoServerContextBuilder.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/GeoServerGeoGigRepositoryResolver.java
src/community/geogig/src/main/java/org/geogig/geoserver/config/RepositoryManager.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/ImportRepoCommandResource.java
src/community/geogig/src/main/java/org/geogig/geoserver/rest/InitCommandResource.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/repository/RepositoryEditPanel.java
src/community/geogig/src/main/java/org/geogig/geoserver/web/repository/RepositoryImportPanel.java
src/community/geogig/src/test/java/org/geogig/geoserver/GeoGigTestData.java
src/community/geogig/src/test/java/org/geogig/geoserver/config/RepositoryManagerTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/GeoServerFunctionalTestContext.java
src/community/geogig/src/test/java/org/geogig/geoserver/functional/PluginWebAPICucumberHooks.java
src/community/geogig/src/test/java/org/geogig/geoserver/web/repository/CommonPanelTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/web/repository/RepositoryEditPanelTest.java
src/community/geogig/src/test/java/org/geogig/geoserver/web/repository/RepositoryImportPanelTest.java
src/community/geogig/src/test/resources/features/webCommand/PluginInit.feature
src/community/geogig/src/test/resources/features/webCommand/importExistingRepo.feature

[backport 2.9.x] Prevent duplicate GeoGig repository names

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/StylePage.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StylePageTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8155

[GEOS-8155] Allow deletion of workspaced styles that share names with default styles

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/AbstractAppSchemaMockData.java

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8209

[GEOS-8209] Online app-schema tests fail for NamespacesWfsTest test

---

src/restconfig/src/main/java/org/geoserver/rest/catalog/LayerGroupController.java
src/restconfig/src/test/java/org/geoserver/rest/catalog/LayerGroupControllerTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8062

[GEOS-8062] Include links to nested LayerGroups in REST LayerGroup representation

---

doc/en/user/source/services/wcs/vendor.rst
doc/en/user/source/services/wms/vendor.rst
src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/kml/src/main/java/org/geoserver/kml/builder/SuperOverlayNetworkLinkBuilder.java
src/main/src/main/java/org/geoserver/ows/kvp/SortByKvpParser.java
src/ows/src/main/java/org/geoserver/ows/kvp/EMFKvpRequestReader.java
src/wcs2_0/src/main/java/applicationContext.xml
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/GetCoverage.java
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/GridCoverageRequest.java
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/kvp/WCS20GetCoverageRequestReader.java
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCSDefaultValuesHelper.java
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCSDimensionsSubsetHelper.java
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/GetCoverageKvpTest.java
src/wfs/src/main/java/applicationContext.xml
src/wms/src/main/java/org/geoserver/wms/FeatureInfoRequestParameters.java
src/wms/src/main/java/org/geoserver/wms/GetMap.java
src/wms/src/main/java/org/geoserver/wms/GetMapRequest.java
src/wms/src/main/java/org/geoserver/wms/WMS.java
src/wms/src/main/java/org/geoserver/wms/featureinfo/RasterLayerIdentifier.java
src/wms/src/main/java/org/geoserver/wms/featureinfo/VectorBasicLayerIdentifier.java
src/wms/src/main/java/org/geoserver/wms/featureinfo/VectorRenderingLayerIdentifier.java
src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java
src/wms/src/test/java/org/geoserver/wms/WMSDimensionsTestSupport.java
src/wms/src/test/java/org/geoserver/wms/map/GetMapKvpRequestReaderTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DimensionsRasterGetFeatureInfoTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DimensionsRasterGetMapTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DimensionsVectorGetFeatureInfoTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DimensionsVectorGetMapTest.java
src/wms/src/test/resources/org/geoserver/wms/TimeElevationStacked.properties
src/wms/src/test/resources/org/geoserver/wms/TimeElevationStacked.sld

This pull request depends on https://github.com/geotools/geotools/pull/1652 to compile, but it can be already reviewed in the meantime :-)

[GEOS-8223] Allow ordering layer contents in WMS using a "sortBy" vendor parameter, as well as mosaic contents in WCS

---

src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java

See https://osgeo-org.atlassian.net/browse/GEOS-8189 for more info.

GEOS-8189 Duplicate logging of loading resources and stores

---

src/restconfig/src/main/java/org/geoserver/catalog/rest/CoverageListResource.java
src/restconfig/src/main/java/org/geoserver/catalog/rest/WMSLayerListResource.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/CoverageTest.java
src/restconfig/src/test/java/org/geoserver/catalog/rest/WMSLayerTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8226
This is the 2.11.x version of the fix, the issue does not appear to affect master.

[GEOS-8226] Get stores in the right workspace when listing resources via REST (2.11.x)

---

src/wfs/src/test/java/org/geoserver/wfs/kvp/Filter_2_0_0_KvpParserTest.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureTest.java

https://osgeo-org.atlassian.net/browse/GEOT-5343
Unit tests for https://github.com/geotools/geotools/pull/1661. Expected to fail until https://github.com/geotools/geotools/pull/1661 is merged and artifacts are deployed.

[GEOT-5343] Support matchCase on PropertyIsLike in Filter 2.0

---

doc/en/user/source/extensions/wcs20eo/index.rst

Reflect issue of the spec, and fix a few typos.

[GEOS-8253] Update WCS 2.O Earth Observation docs.

---

src/restconfig/src/main/java/org/geoserver/rest/resources/ftl-templates/resourceDirectoryInfo.ftl
src/restconfig/src/test/java/org/geoserver/rest/resources/ResourceControllerTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8238
This fix is not actually going to be visible until https://github.com/geoserver/geoserver/pull/2473 is merged

[GEOS-8238] Fix Rest resource root html endpoint

---

doc/en/api/1.0.0/featuretypes.yaml

Minor additional docs fixes.

---

src/main/pom.xml

small pom change to protect against transitive dependencies

JTS 1.14.0 upgrade

---

src/extension/wps/wps-core/src/main/java/org/geoserver/wps/xml/WPSConfiguration.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/xml/v1_0_0/WpsXmlReaderTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8267

GEOS-8267: added support for viewParams in WPS Execute embedded WFS requests

---

src/gwc/src/main/java/org/geoserver/gwc/controller/DispatcherController.java
src/gwc/src/main/java/org/geoserver/gwc/dispatch/GwcServiceProxy.java
src/gwc/src/main/java/org/geoserver/gwc/layer/GWCGeoServerRESTConfigurationProvider.java
src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
src/gwc/src/main/resources/application.properties
src/gwc/src/main/resources/geowebcache-diskquota-context.xml
src/gwc/src/main/resources/geowebcache-rest-context.xml
src/gwc/src/main/resources/geowebcache-servlet.xml
src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
src/gwc/src/test/java/org/geoserver/gwc/RESTIntegrationTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8275

GeoWebCache REST API migrate to Spring MVC and addresses [GEOS-8275]

---

doc/en/user/source/data/raster/gdal.rst
src/release/ext-gdal.xml

Reverses https://github.com/geoserver/geoserver/pull/1643

Reverse GEOS-7578; package 1.9.2 gdal bindings with gdal extension

---

doc/en/user/source/community/index.rst
doc/en/user/source/community/s3-geotiff/index.rst
src/community/pom.xml
src/community/s3-geotiff/pom.xml
src/community/s3-geotiff/src/main/java/org/geoserver/s3/ui/S3InfoPanel.html
src/community/s3-geotiff/src/main/java/org/geoserver/s3/ui/S3InfoPanel.java
src/community/s3-geotiff/src/main/resources/applicationContext.xml
src/web/app/pom.xml

This PR creates a community module that uses the corresponding GeoTools unsupported module, as well as documentation for it.

Initial commit of s3-geotiff GeoServer module

---

src/community/gwc-sqlite/src/main/resources/applicationContext.xml
src/extension/ysld/src/test/java/org/geoserver/rest/catalog/YsldStyleControllerTest.java
src/gwc/pom.xml
src/gwc/src/main/java/org/geoserver/gwc/dispatch/GeoServerGWCDispatcherController.java
src/gwc/src/main/resources/application.properties
src/gwc/src/main/resources/geowebcache-rest-context.xml
src/gwc/src/main/resources/geowebcache-servlet.xml

Configuration changes to support the new MVC-based GeoWebCache rest API, when embedded in GeoServer.
Depends upon https://github.com/GeoWebCache/geowebcache/pull/539

GWC Rest Integration

---

doc/en/api/1.0.0/workspaces.yaml
src/restconfig/src/main/java/org/geoserver/rest/catalog/WorkspaceController.java

Mostly looking for missing query parameters and examples, we will get a short list of missing documentation as well.

review of rest api docs

---

src/gwc/src/main/java/org/geoserver/gwc/layer/CatalogStyleChangeListener.java
src/gwc/src/test/java/org/geoserver/gwc/layer/CatalogStyleChangeListenerTest.java

[GEOS-8288] Check that name has actually been changed in the style change listener (2.11.x backport)

---

LICENSE.txt

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8285

[GEOS-8285] Add clause in GeoServer LICENSE for OSHI library

---

doc/en/api/1.0.0/resource.yaml
doc/en/user/source/rest/index.rst
src/restconfig/src/main/java/org/geoserver/rest/resources/ResourceController.java
src/restconfig/src/test/java/org/geoserver/rest/resources/ResourceControllerTest.java

Adds swagger docs for resources
Also includes a fix for https://osgeo-org.atlassian.net/browse/GEOS-8300 as a separate commit (discovered during doc QA)

Rest API Swagger doc QA - resources

---

doc/en/api/1.0.0/datastores.yaml
doc/en/api/1.0.0/featuretypes.yaml
doc/en/user/source/rest/index.rst
src/rest/src/main/java/org/geoserver/rest/RestBaseController.java
src/restconfig/src/main/java/org/geoserver/rest/catalog/FeatureTypeController.java
src/restconfig/src/test/java/org/geoserver/rest/catalog/FeatureTypeControllerTest.java

Also includes some code changes to bring the endpoints inline with documented functionality (POST to `/workspaces/{workspaceName}/featureTypes` was throwing a NPE)

Rest API Swagger doc QA - datastores and featuretypes

---

src/main/src/main/java/org/geoserver/catalog/impl/AbstractCatalogFacade.java
src/main/src/test/java/org/geoserver/config/util/XStreamPersisterTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8289

[GEOS-8289] AbstractCatalogFacade.resolve(StyleInfo) resolves the workspace

---

src/community/status-monitoring/src/main/java/org/geoserver/status/monitoring/collector/MetricValue.java
src/community/status-monitoring/src/main/java/org/geoserver/status/monitoring/collector/OSHISystemInfoCollector.java

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8302

[GEOS-8302] Statatus monitoring community module is failing with division by zero (NaN)

---

src/release/installer/mac/build.xml

See https://osgeo-org.atlassian.net/browse/GEOS-8304

ignore user java extensions [GEOS-8304]

---

src/pom.xml
src/security/jdbc/pom.xml

https://osgeo-org.atlassian.net/browse/GEOS-8314

[GEOS-8314] gs-sec-jdbc tests fail with PostgreSQL 10 RC1 (master)

---

doc/en/api/1.0.0/gwcbounds.yaml
doc/en/api/1.0.0/gwcdiskquota.yaml
doc/en/api/1.0.0/gwcfilterupdate.yaml
doc/en/api/1.0.0/gwcindex.yaml
doc/en/api/1.0.0/gwclayers.yaml
doc/en/api/1.0.0/gwcmasstruncate.yaml
doc/en/api/1.0.0/gwcmemorycachestatistics.yaml
doc/en/api/1.0.0/gwcreload.yaml
doc/en/api/1.0.0/gwcseed.yaml
doc/en/user/source/rest/index.rst

Part of first pass for the GWC swagger documentation

Rest API Swagger doc - GWC swagger

---

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/ConfigDatabaseTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8203
Backporting fix to 2.11.x.

[GEOS-8203] 2.11.x Fixed deleting a workspace when using JDBC Configuration returning an error response.

---

doc/en/developer/source/release-guide/index.rst

update release instructions for posting

---

doc/en/api/1.0.0/styles.yaml

Improve style docs with a PUT example showing legend creation.

Swagger REST API Examples - Style PUT

---

src/community/geogig/src/main/java/org/geogig/geoserver/spring/config/AbstractDelegatingGeogigMessageConverter.java

Fix an NPE when using the plugin in a GeoNode context

---

src/community/geogig/src/main/java/org/geogig/geoserver/spring/config/AbstractDelegatingGeogigMessageConverter.java

[backport 2.12.x] Fix an NPE when using the plugin in a GeoNode context

---

doc/en/user/source/geowebcache/webadmin/defaults.rst
src/gwc/pom.xml
src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
src/gwc/src/main/resources/geowebcache-rest-context.xml
src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
src/gwc/src/test/java/org/geoserver/gwc/GWCTest.java

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8259
This PR depends on this GWC PR: https://github.com/GeoWebCache/geowebcache/pull/530
The GWC issue contains a detailed description of the work done: https://github.com/GeoWebCache/geowebcache/issues/529
This PR adds some tests cases on GS side and updates the documentation.

[GEOS-8259] Add WMTS RESTful API

---

src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/ProcessStatusTracker.java

Force the dates passed into the remove filter to be ISO formatted.

improve format of dates

---

src/pom.xml
src/security/jdbc/pom.xml

https://osgeo-org.atlassian.net/browse/GEOS-8314
Backport to 2.12.x.

[GEOS-8314] gs-sec-jdbc tests fail with PostgreSQL 10 RC1 (2.12.x)

---

src/wfs/src/test/java/org/geoserver/wfs/xml/v1_1/XMLParsingTest.java

This adds a test for GEOS-8227 which is fixed in GeoTools https://github.com/geotools/geotools/pull/17350.

[GEOS-8227] test for issue

---

doc/en/api/1.0.0/gwcseed.yaml
doc/en/user/source/rest/index.rst
src/gwc/src/test/java/org/geoserver/gwc/RESTIntegrationTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8401
Test cases for https://github.com/GeoWebCache/geowebcache/pull/560

[GEOS-8401] GWC REST seeding - improved docs and integration tests

---

src/community/pom.xml
src/community/release/pom.xml

https://osgeo-org.atlassian.net/browse/GEOS-8400

[GEOS-8400] Restore building of "backup-restore" community module

---

src/extension/inspire/src/main/java/org/geoserver/inspire/wmts/WMTSExtendedCapabilitiesProvider.java
src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
src/gwc/src/main/java/org/geoserver/gwc/layer/StyleParameterFilter.java
src/gwc/src/main/java/org/geoserver/gwc/wmts/WMTSCapabilitiesProvider.java
src/gwc/src/main/resources/applicationContext.xml
src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
src/gwc/src/test/java/org/geoserver/gwc/GWCTest.java
src/gwc/src/test/java/org/geoserver/gwc/layer/GeoServerTileLayerTest.java
src/gwc/src/test/java/org/geoserver/gwc/workspacedStyle.sld
src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
src/wms/src/main/java/org/geoserver/wms/capabilities/CapabilityUtil.java

**Depends on GeoWebCache PR: https://github.com/GeoWebCache/geowebcache/pull/565**
Associated issues: 
* https://osgeo-org.atlassian.net/browse/GEOS-8391
* https://osgeo-org.atlassian.net/browse/GEOS-8392
* https://osgeo-org.atlassian.net/browse/GEOS-8397
**Makes GeoServer default styles be advertised in WMTS capabilities document.**
Before this fix WMTS capabilities document will contain this:
```xml
<Contents>
<Layer>
<ows:Title>Manhattan (NY) points of interest</ows:Title>
<ows:Abstract>Points of interest in New York, New York (on Manhattan). One of the attributes contains the name of a file with a picture of the point of interest.</ows:Abstract>
<ows:WGS84BoundingBox>
<ows:LowerCorner>-74.0118315772888 40.70754683896324</ows:LowerCorner>
<ows:UpperCorner>-74.00153046439813 …
```

[GEOS-8391,GEOS-8392,GEOS-8397] Fix GeoServer GWC integration issues related with WMTS

---

src/community/pom.xml
src/community/release/pom.xml

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8440

[GEOS-8440] NSG wfs profile community podule plugin bundle is not published

---

src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java

Updated WMS 1.3.0 GetCapabilities not reload the service configuration from the database multiple times per layer and layer group and to only load the layers and layer groups from the catalog once per request.
No unit tests have been added or modified but the behavior from the caller's point of view should not be changed so the numerous existing GetCapabilities tests in the org.geoserver.wms.wms_1_3 package should be sufficient.
This pull request should be able to be backported to 2.11.x and 2.12.x.  It does change the method signature of a protected method but that is in a nested private class.

[GEOS-8335] WMS 1.3.0 GetCapabilities Optimizations For JDBC Configuration

---

src/community/gwc-s3/src/main/resources/applicationContext.xml

Enabled work done in https://github.com/GeoWebCache/geowebcache/pull/569 for https://github.com/GeoWebCache/geowebcache/issues/568

GEOS-8476: Enabled S3BlobStore parametric configuration

---

src/gwc/src/test/java/org/geoserver/gwc/RESTIntegrationTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8471
Test case for https://github.com/GeoWebCache/geowebcache/pull/577

[GEOS-8471] Add integration tests for embedded GWC seed form post

---

doc/en/developer/source/release-guide/index.rst

Update the release guide to fix Jenkins URL and Jira instructions.

Update the release guide

---

src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DimensionsRasterGetMapTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DynamicDimensionsTest.java

PR required to fix WMS tests once https://github.com/geotools/geotools/pull/1775 [GEOT-5906] get merged.

Updating GeoServer tests being changed as a consequency of [GEOT-5906]

---

src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/Operation.java
src/community/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/MultiDimensionalExtensionTest.java

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-8498
This PR fix the issue and adds a new test case, only code from **``wmts-multi-dimensional`` community module** was changed.

[GEOS-8498] WMTS multi dimensional community module throws NULL pointer exception instead of an exception report

---

src/restconfig/src/main/java/org/geoserver/rest/catalog/StyleController.java
src/restconfig/src/test/java/org/geoserver/rest/catalog/StyleControllerTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8475
Backport from MR #2682 to branch 2.12.x

[Backport on 2.12.x][GEOS-8475] Handle charset in contentType header when uploading style through restconfig

---

src/main/src/main/java/org/geoserver/catalog/LayerGroupHelper.java
src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
src/main/src/test/java/org/geoserver/catalog/CatalogIntegrationTest.java
src/web/core/src/test/java/org/geoserver/web/data/layergroup/LayerGroupBaseTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8470

[GEOS-8470] Improved validation for LayerGroups containing Style Groups

---

src/web/core/pom.xml
src/web/core/src/main/java/org/geoserver/web/css/geoserver.css
src/web/core/src/main/java/org/geoserver/web/data/store/panel/FileParamPanel.html
src/web/core/src/main/java/org/geoserver/web/data/store/panel/FileParamPanel.java
src/web/core/src/main/java/org/geoserver/web/wicket/browser/FileRootsFinder.java
src/web/core/src/main/java/org/geoserver/web/wicket/browser/GeoServerFileChooser.java
src/web/core/src/test/java/org/geoserver/web/wicket/browser/GeoServerFileChooserTest.java

[GEOS-8511] Allow file chooser text editor to auto-complete typed paths

---

src/web/demo/src/main/java/org/geoserver/web/demo/SRSDescriptionPage.java
src/web/demo/src/test/java/org/geoserver/web/demo/SRSListPageTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8536

[GEOS-8536] Support HeaderContribution for SRSListPage

---

src/pom.xml

To solve this: https://github.com/geosolutions-it/jai-ext/issues/175

GEOS-8537: upgraded jai-ext to 1.0.19

---

CONTRIBUTING.md

I updated a few links that were broken after the new OSGeo site went live.  I also made some formatting fixes that make it render correctly on GitHub.

fixing broken links and formatting issues in CONTRIBUTING.md

---

doc/en/developer/source/introduction.rst
doc/en/user/source/community/backuprestore/installation.rst
doc/en/user/source/community/dds/index.rst
doc/en/user/source/community/gwc-distributed/index.rst
doc/en/user/source/community/index.rst
doc/en/user/source/community/rest-upload/index.rst
doc/en/user/source/community/scripting/installation.rst
doc/en/user/source/community/solr/configure.rst
doc/en/user/source/community/spatialite/index.rst
doc/en/user/source/community/wmts-multidimensional/index.rst
doc/en/user/source/community/wps-download/index.rst
doc/en/user/source/geowebcache/config.rst
doc/en/user/source/styling/workshop/setup/install.rst

See https://osgeo-org.atlassian.net/browse/GEOS-8479

[GEOS-8479] Update doc links to point to build.geoserver.org

---

src/community/security/oauth2/src/main/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilter.java

Resolve al principal associated Roles through the RolesCalculator.
Fixes JIRA GEOS-8557 [OAUTH2] Auth filter causing CSRF exception due to misleading session cookie

[OAuth2 Community Module][GeoServerOAuthAuthenticationFilter] - OAuth2 Roles Computation Completeness

---

src/web/core/src/main/java/org/geoserver/web/data/workspace/WorkspaceNewPage.java
src/web/core/src/test/java/org/geoserver/web/data/workspace/WorkspaceNewPageTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8127

[GEOS-8127] Improved validation to WorkspaceNewPage for duplicate names

---

src/community/hz-cluster/src/main/java/org/geoserver/cluster/hazelcast/HzCacheProvider.java
src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/catalog/JDBCCatalogFacade.java
src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/config/JDBCGeoServerFacade.java
src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/FilterToCatalogSQL.java
src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/InfoIdentities.java
src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/InfoIdentity.java

Note that no new functionality is introduced so the existing test coverage is sufficient.

GEOS-8188 Jdbcconfig performance

---

src/community/jdbcstore/src/main/java/org/geoserver/jdbcstore/internal/JDBCDirectoryStructure.java
src/community/jdbcstore/src/test/java/org/geoserver/jdbcstore/AbstractJDBCResourceStoreTest.java

Note that no new functionality is introduced so the existing test coverage is sufficient.

GEOS-8530 Improve jdbcstore performance (dramatically)

---

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/listener/BackupJobExecutionListener.java
src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/tasklet/FinalizeBackupTasklet.java
src/community/backup-restore/core/src/main/resources/applicationContext.xml
src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java

[GEOS-8587] Finalize backup as part of backup job - 2.13.x

---

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/listener/BackupJobExecutionListener.java
src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/tasklet/FinalizeBackupTasklet.java
src/community/backup-restore/core/src/main/resources/applicationContext.xml
src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java

[GEOS-8587] Finalize backup as part of backup job - 2.12.x

---

doc/en/api/1.0.0/gwcblobstores.yaml
doc/en/api/1.0.0/gwcglobal.yaml
doc/en/api/1.0.0/gwcgridsets.yaml
doc/en/api/1.0.0/gwclayers.yaml
doc/en/user/source/rest/index.rst

API docs for https://github.com/GeoWebCache/geowebcache/pull/593
~WIP pending docs for the new global endpoint (will be added to this PR shortly).~

Add GWC API docs for REST improvements

---

src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/gwc/src/main/java/org/geoserver/gwc/JDBCConfigurationStorage.java
src/gwc/src/main/java/org/geoserver/gwc/layer/CatalogConfiguration.java
src/gwc/src/main/java/org/geoserver/gwc/layer/CatalogLayerEventListener.java
src/gwc/src/main/java/org/geoserver/gwc/layer/GWCGeoServerConfigurationProvider.java
src/gwc/src/main/java/org/geoserver/gwc/layer/GWCGeoServerRESTConfigurationProvider.java
src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayerInfo.java
src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayerInfoImpl.java
src/gwc/src/main/java/org/geoserver/gwc/layer/StyleParameterFilter.java
src/gwc/src/main/java/org/geoserver/gwc/layer/TileLayerInfoUtil.java
src/gwc/src/main/java/org/geoserver/gwc/wms/CachingExtendedCapabilitiesProvider.java
src/gwc/src/test/java/org/geoserver/gwc/layer/CatalogConfigurationLayerConformanceTest.java
src/wms/src/main/java/org/geoserver/wms/ExtendedCapabilitiesProvider.java

Based primarily on changes introduced by https://github.com/geoserver/geoserver/pull/2760
Also fixes a missing license header.

Update gs-gwc javadocs

---

src/community/pom.xml

See https://osgeo-org.atlassian.net/browse/GEOS-8614

[GEOS-8614] install/deploy community gs-security for -PcommunityRelease

---

src/extension/vectortiles/pom.xml
src/extension/vectortiles/src/main/java/org/geotools/renderer/lite/VectorMapRenderUtils.java
src/extension/vectortiles/src/test/java/org/geoserver/wms/vector/VectorTileMapOutputFormatTest.java
src/extension/vectortiles/src/test/java/org/geoserver/wms/vector/VectorTilesIntegrationTest.java

Added also an integration test, cause... http://silveiraneto.net/2017/03/27/2-unit-tests-0-integration-tests/

[GEOS-8065] Vector tiles miss support for WMS filters

---

doc/en/user/source/styling/mbstyle/reference/spec.rst

Since I last checked, a couple of additional features are now supported in OpenLayers.

Update OpenLayers support

---

src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/CoverageDimensionsReader.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/Dimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/HistogramUtils.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/RasterCustomDimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/RasterDimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/RasterElevationDimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/RasterTimeDimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/VectorDimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/VectorElevationDimension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/VectorTimeDimension.java
src/community/wmts-multi-dimensional/src/test/resources/TimeElevationWithStartEnd.properties
src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AbstractCommandLineTransform.java

Requires the changes in https://github.com/geotools/geotools/pull/1843 to be build and get into the M2 repos for tests to pass

[GEOS-8667] WMTS Multidimensional GetHistogram is memory bound and can cause OOM over large data sets

---

src/community/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/BinaryPPIO.java
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/CoveragePPIO.java
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/GeoTiffPPIO.java
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/ProcessParameterIO.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ppio/CoveragePPIOTest.java

The 2 commits have been combined into a single PR to avoid issues with OpenJDK installations

PNG-JPEG Download support. 

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/FeatureGML32Test.java
src/main/src/main/java/org/geoserver/security/InMemorySecurityFilter.java
src/wfs/src/main/java/org/geoserver/wfs/AliasedQuery.java
src/wfs/src/main/java/org/geoserver/wfs/GetFeature.java
src/wfs/src/main/java/org/geoserver/wfs/JoinExtractingVisitor.java
src/wfs/src/main/java/org/geoserver/wfs/StoredQuery.java
src/wfs/src/main/java/org/geoserver/wfs/xml/filter/v1_1/PropertyNameTypeBinding.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureJoinTest.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureTest.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/StoredQueryTest.java

Wait for https://github.com/geotools/geotools/pull/1853 before merging these backports

Set of bug-fixes related to WFS 2.0 (backporting from master) [GEOS-8638-8651-8675-8677]

---

doc/en/user/source/services/wfs/vendor.rst

https://osgeo-org.atlassian.net/browse/GEOS-8679

[GEOS-8679] Fix INTERSECTS typo.

---

doc/en/user/source/community/s3-geotiff/index.rst

see https://github.com/geotools/geotools/pull/1850

GEOT-5963 support S3 on other servers (docs)

---

src/gwc/src/main/resources/geowebcache-core-context.xml

For compatibility GeoWebcache/geowebcache#647

Adds gwcBlobStoreAggregator bean to geowebcacheDispatcher bean constructor

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/StationsMockData.java

https://osgeo-org.atlassian.net/browse/GEOS-8724

[GEOS-8724] Intermittent build failure in NamespacesWfsTest (backport 2.13.x)

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/DefaultGeometryTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NamespacesWfsTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/StationsMockData.java

https://osgeo-org.atlassian.net/browse/GEOS-8724

[GEOS-8724] Intermittent build failure in NamespacesWfsTest

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NamespacesWfsTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8724

[GEOS-8724] Intermittent build failure in NamespacesWfsTest (backport 2.12.x)

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/FeatureChainingWfsTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NestedGeometryFilterEncodingTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SRSReprojectionTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8737
**Depends on: https://github.com/geotools/geotools/pull/1896**

[GEOS-8737] Add App-Schema integration tests checkign that spatial filters on nested properties are delegated to the database

---

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/tasklet/CatalogBackupRestoreTasklet.java

Changes are purely to Backup-Restore community module

Change skip settings, GWC defaults to true. Purge to false.

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/OpenLayersPreviewPanel.java

https://osgeo-org.atlassian.net/browse/GEOS-8784
Only affects setup of OL preview so not amenable to unit test.

[GEOS-8784] Use prefixed names for style preview

---

doc/en/user/source/data/database/sqlview.rst

**Should only be merged after this PR https://github.com/geotools/geotools/pull/1919**
https://osgeo-org.atlassian.net/browse/GEOS-8772

[GEOS-8772] Add documentation about the :where_clause: place holder in SQL views \ virtual tables

---

src/web/gwc/src/main/java/org/geoserver/gwc/web/GWCSettingsPage.html

https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-8777
No unit test as it's not really amenable to one.

[GEOS-8777] Direct link to GWC homepage bypassing redirect

---

src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8764

[GEOS-8764] Allow LayerGroups in default worksaces to be found when workspace isn't specified

---

src/extension/wps/wps-core/src/main/java/org/geoserver/wps/gs/GeorectifyCoverage.java

https://osgeo-org.atlassian.net/browse/GEOS-8796

[GEOS-8796] GeorectifyCoverage fails to handle paths with spaces

---

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/tasklet/AbstractCatalogBackupRestoreTasklet.java
src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/tasklet/CatalogBackupRestoreTasklet.java
src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8794

[JIRA GEOS-8794] [Community Backup & Restore] Local Resource Finder on Restore does not check if File is null

---

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/tasklet/AbstractCatalogBackupRestoreTasklet.java
src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/tasklet/CatalogBackupRestoreTasklet.java
src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8794

[Backport 2.13.x][JIRA GEOS-8794] [Community Backup & Restore] Local Resource Finder on Restore does not check if File is null

---

src/main/src/test/java/org/geoserver/data/test/SystemTestData.java

https://osgeo-org.atlassian.net/browse/GEOS-8814

[GEOS-8814] Intermittent build failure caused by H2 log race with fixture data directory deletion

---

src/main/src/test/java/org/geoserver/data/test/SystemTestData.java

https://osgeo-org.atlassian.net/browse/GEOS-8814
Backport to 2.13.x.
This backport incorporates data directory debug pretty printing by @aaime and the loop logic fix.

[GEOS-8814] Intermittent build failure caused by H2 log race with fixture data directory deletion (2.13.x)

---

src/main/src/test/java/org/geoserver/data/test/SystemTestData.java

https://osgeo-org.atlassian.net/browse/GEOS-8814
Backport to 2.12.x.
This backport incorporates data directory debug pretty printing by @aaime and the loop logic fix.

[GEOS-8814] Intermittent build failure caused by H2 log race with fixture data directory deletion (2.12.x)

---

src/gwc/pom.xml
src/pom.xml
src/web/security/core/pom.xml
src/wms/pom.xml

Resolves https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-8807

Fix Maven warnings

---

src/main/pom.xml
src/main/src/main/java/org/geoserver/security/password/GeoServerDigestPasswordEncoder.java
src/main/src/main/java/org/geoserver/security/password/GeoServerPBEPasswordEncoder.java
src/pom.xml

Full compile (release).
Booted the war on tomcat8, checked login / logout and password change. Not sure if that is enough though.

[GEOS-8817] Upgrade jasypt to 1.9.2

---

src/wms/src/main/resources/org/geoserver/wms/map/OpenLayers3MapTemplate.ftl
src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapOutputFormatTest.java

Template Fix + Test to check parameters encode

Openlayers3 Freemarker template parameters fix

---

src/dependency-check-suppression.xml
src/pom.xml

https://osgeo-org.atlassian.net/browse/GEOS-8815

 [GEOS-8815] Add profile for dependency checking

---

src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/ImporterIntegrationTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8818

[GEOS-8818] Intermittent failure of ImporterIntegrationTest.testDirectWrongFile

---

doc/en/user/source/production/config.rst

Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>

GEOS-8779 Adding documentation on WFS caching

---

doc/en/user/source/security/tutorials/cas/index.rst

Since @Jasig is working for Apereo, I'm assuming this is the new CAS Server homepage.

CAS Server Broken link

---

doc/en/user/source/security/tutorials/cas/index.rst

Typo fixes for the CAS tutorial

---

src/community/jms-cluster/activemqBroker/pom.xml
src/pom.xml
src/web/security/ldap/pom.xml

Full release build, plus the jms community module compiled.

[GEOS-8826] Update bouncycastle provider to 1.60

---

src/community/wfs3/src/main/java/org/geoserver/wfs3/response/AbstractHTMLResponse.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/response/FreemarkerTemplateSupport.java
src/community/wps-remote/src/main/java/org/geoserver/wps/remote/plugin/output/XMPPRawDataOutput.java
src/extension/monitor/core/src/main/java/org/geoserver/monitor/auditlog/AuditLogger.java
src/extension/monitor/core/src/test/java/org/geoserver/monitor/auditlog/AuditTemplateLoaderTest.java
src/main/src/main/java/org/geoserver/template/FeatureWrapper.java
src/main/src/main/java/org/geoserver/template/GeoServerTemplateLoader.java
src/main/src/main/java/org/geoserver/template/TemplateUtils.java
src/main/src/test/java/org/geoserver/template/FeatureWrapperTest.java
src/rest/src/main/java/org/geoserver/rest/RestBaseController.java
src/web/core/src/main/java/org/geoserver/web/LoginFormHTMLInclude.java
src/web/core/src/main/java/org/geoserver/web/util/WebUtils.java
src/web/wms/src/main/java/org/geoserver/wms/web/data/OpenLayersPreviewPanel.java
src/wfs/src/main/java/org/geoserver/wfs/response/ShapeZipOutputFormat.java
src/wfs/src/test/java/org/geoserver/wfs/WFSTestSupport.java
src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetFeatureTest.java
src/wms/pom.xml
src/wms/src/main/java/org/geoserver/wms/decoration/TextDecoration.java
src/wms/src/main/java/org/geoserver/wms/featureinfo/FeatureTemplate.java
src/wms/src/main/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormat.java
src/wms/src/main/java/org/geoserver/wms/map/AbstractOpenLayersMapOutputFormat.java
src/wms/src/test/java/org/geoserver/wms/featureinfo/FeatureDescriptionTemplateTest.java
src/wms/src/test/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormatTest.java
src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapTemplateTest.java
src/wms/src/test/resources/org/geoserver/wms/featureinfo/test_execute.ftl

https://osgeo-org.atlassian.net/browse/GEOS-8825

[GEOS-8825] Centralize Freemarker configuration

---

src/community/wps-remote/src/main/java/org/geoserver/wps/remote/plugin/output/XMPPRawDataOutput.java
src/extension/monitor/core/src/main/java/org/geoserver/monitor/auditlog/AuditLogger.java
src/extension/monitor/core/src/test/java/org/geoserver/monitor/auditlog/AuditTemplateLoaderTest.java
src/main/src/main/java/org/geoserver/template/FeatureWrapper.java
src/main/src/main/java/org/geoserver/template/GeoServerTemplateLoader.java
src/main/src/main/java/org/geoserver/template/TemplateUtils.java
src/main/src/test/java/org/geoserver/template/FeatureWrapperTest.java
src/rest/src/main/java/org/geoserver/rest/RestBaseController.java
src/web/core/src/main/java/org/geoserver/web/LoginFormHTMLInclude.java
src/web/core/src/main/java/org/geoserver/web/util/WebUtils.java
src/web/wms/src/main/java/org/geoserver/wms/web/data/OpenLayersPreviewPanel.java
src/wfs/src/main/java/org/geoserver/wfs/response/ShapeZipOutputFormat.java
src/wfs/src/test/java/org/geoserver/wfs/WFSTestSupport.java
src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetFeatureTest.java
src/wms/pom.xml
src/wms/src/main/java/org/geoserver/wms/decoration/TextDecoration.java
src/wms/src/main/java/org/geoserver/wms/featureinfo/FeatureTemplate.java
src/wms/src/main/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormat.java
src/wms/src/main/java/org/geoserver/wms/map/AbstractOpenLayersMapOutputFormat.java
src/wms/src/test/java/org/geoserver/wms/featureinfo/FeatureDescriptionTemplateTest.java
src/wms/src/test/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormatTest.java
src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapTemplateTest.java
src/wms/src/test/resources/org/geoserver/wms/featureinfo/test_execute.ftl

https://osgeo-org.atlassian.net/browse/GEOS-8825
Backport of https://github.com/geoserver/geoserver/pull/2976

[GEOS-8825] Centralize Freemarker configuration, Backport to 2.13

---

src/community/wps-remote/src/main/java/org/geoserver/wps/remote/plugin/output/XMPPRawDataOutput.java
src/extension/monitor/core/src/main/java/org/geoserver/monitor/auditlog/AuditLogger.java
src/extension/monitor/core/src/test/java/org/geoserver/monitor/auditlog/AuditTemplateLoaderTest.java
src/main/src/main/java/org/geoserver/template/FeatureWrapper.java
src/main/src/main/java/org/geoserver/template/GeoServerTemplateLoader.java
src/main/src/main/java/org/geoserver/template/TemplateUtils.java
src/main/src/test/java/org/geoserver/template/FeatureWrapperTest.java
src/rest/src/main/java/org/geoserver/rest/RestBaseController.java
src/web/core/src/main/java/org/geoserver/web/LoginFormHTMLInclude.java
src/web/core/src/main/java/org/geoserver/web/util/WebUtils.java
src/web/wms/src/main/java/org/geoserver/wms/web/data/OpenLayersPreviewPanel.java
src/wfs/src/main/java/org/geoserver/wfs/response/ShapeZipOutputFormat.java
src/wfs/src/test/java/org/geoserver/wfs/WFSTestSupport.java
src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetFeatureTest.java
src/wms/pom.xml
src/wms/src/main/java/org/geoserver/wms/featureinfo/FeatureTemplate.java
src/wms/src/main/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormat.java
src/wms/src/test/java/org/geoserver/wms/featureinfo/FeatureDescriptionTemplateTest.java
src/wms/src/test/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormatTest.java
src/wms/src/test/java/org/geoserver/wms/map/OpenLayersMapTemplateTest.java
src/wms/src/test/resources/org/geoserver/wms/featureinfo/test_execute.ftl

https://osgeo-org.atlassian.net/browse/GEOS-8825
https://osgeo-org.atlassian.net/browse/GEOS-8835
Backport of #2976

[GEOS-8825, GEOS-8835] Centralize Freemarker configuration, Backport to 2.12

---

src/community/geogig/pom.xml
src/community/onelogin/pom.xml
src/pom.xml

Minor version changes. Did a full release build, plus built the geogig, authkey and onelogin community modules.
@mbarto the onelogin module did fail some tests - looks like it has some online tests. Can you confirm?

[GEOS-8830] Upgrade httpcomponents modules to latest.

---

src/main/src/main/java/org/geoserver/catalog/CoverageDimensionCustomizerReader.java
src/main/src/test/java/org/geoserver/catalog/CoverageDimensionCustomizerReaderTest.java

[GEOS-8844]: Expose wrapped GridCoverage

---

src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8852

[GEOS-8852] FeatureTypes and Features fetched from ResourcePool should have the same defaultGeometry

---

src/extension/wps/wps-core/src/main/java/org/geoserver/wps/WPSXStreamLoader.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/WPSXStreamLoaderTest.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/wps-test-error.xml

See https://osgeo-org.atlassian.net/browse/GEOS-7903 and https://osgeo-org.atlassian.net/browse/GEOS-7934

[GEOS-7934] WPSXStreamLoader shouldn't fail if it can't deserialize a process definition

---

src/community/geofence-server/pom.xml
src/community/geofence-server/src/main/java/org/geoserver/geofence/web/GeofenceRulePage.java
src/community/geofence-server/src/main/java/org/geoserver/geofence/web/GeofenceRulesModel.java
src/community/geofence-server/src/test/java/org/geoserver/geofence/rest/MultiPolygonAdapterTest.java
src/community/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
src/community/geofence/src/main/java/org/geoserver/geofence/rest/xml/JaxbRule.java
src/community/geofence/src/main/java/org/geoserver/geofence/rest/xml/MultiPolygonAdapter.java
src/community/geofence/src/test/java/org/geoserver/geofence/AccessManagerTest.java
src/community/pom.xml
src/pom.xml

Depends on https://github.com/geoserver/geofence/pull/114

GEOS-8861 - [Community GeoFence] Update GeoFence Plugin to JTS 1.15.1 and put it back to the build

---

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/catalog/CatalogImplWithJDBCFacadeTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8866

GEOS-8866 jdbcconfig: handle advertised field properly

---

src/web/core/src/main/java/org/geoserver/web/data/resource/LayerModel.java
src/web/core/src/main/java/org/geoserver/web/publish/PublishedConfigurationPage.java
src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8822
The bug itself cannot really be tested in unit test, but existing unit tests should cover that this does nothing bad.

GEOS-8822 publishing tab cannot be submitted with hazelcast session

---

src/security/jdbc/pom.xml
src/web/security/jdbc/pom.xml

2.13.x backport for https://github.com/geoserver/geoserver/pull/3031

[2.13.x][GEOS-8877] Added test scope to gs-sec-jdbc test dependency.

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/AbstractAppSchemaTestSupport.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NamespacesWfsTest.java
src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/stations_two_queries.xml
src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/stations_two_queries_1.1.xml
src/wfs/src/main/java/org/geoserver/wfs/xml/FeatureTypeSchemaBuilder.java

[GEOS-8799] NULL namespace prefixes Appschema 2.14.x backport
https://osgeo-org.atlassian.net/browse/GEOS-8799

[GEOS-8799] NULL namespace prefixes Appschema 2.14.x backport

---

src/community/pom.xml
src/community/release/ext-geofence-server.xml
src/community/release/ext-keycloak.xml
src/community/release/pom.xml
src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/AuthResults.java

closes https://osgeo-org.atlassian.net/browse/GEOS-8899

[JIRA GEOS-8899] [Community Security Plugins] Include Keycloak security plugins artifacts to community dependencies and release

---

src/community/pom.xml
src/community/release/ext-s3-geotiff.xml
src/community/release/ext-web-resource.xml
src/community/release/pom.xml

Adds the missing parts of the module configuration to the community build

[GEOS-8872] Fix build for community modules s3-geotiff and web-resource

---

src/community/pom.xml
src/community/release/ext-s3-geotiff.xml
src/community/release/ext-web-resource.xml
src/community/release/pom.xml

Backport of https://github.com/geoserver/geoserver/pull/3080

 [GEOS-8872] Fix build for community modules s3-geotiff and web-resource (2.14.x backport)

---

src/community/jms-cluster/activemqBroker/pom.xml

Backport of https://github.com/geoserver/geoserver/pull/3082

Remove spring-asm dependency from jms-cluster (2.13.x backport)

---

src/community/jms-cluster/activemqBroker/pom.xml

Backport of https://github.com/geoserver/geoserver/pull/3082

Remove spring-asm dependency from jms-cluster (2.14.x backport)

---

src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/LayerGroupWorkspaceTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/LayerWorkspaceTest.java

[GEOS-8909] Layer/LayerGroup order ASC on WMS GetCapabilitiesTransformer 2.14.x backport

[GEOS-8909] Layer/LayerGroup order ASC on WMS GetCapabilitiesTransformer 2.14.x backport

---

doc/en/api/1.0.0/featuretypes.yaml
doc/en/api/1.0.0/structuredcoverages.yaml
doc/en/user/source/community/scripting/hooks.rst
doc/en/user/source/extensions/importer/rest_examples.rst
doc/en/user/source/extensions/importer/rest_reference.rst
doc/en/user/source/rest/imagemosaic.rst
doc/en/user/source/rest/stores.rst

Upgrade documentation to reflect JTS upgrade

---

doc/en/user/source/extensions/netcdf/netcdf.rst
src/extension/netcdf-out/src/main/java/org/geoserver/wcs/responses/DefaultNetCDFEncoder.java
src/extension/netcdf/src/main/java/applicationContext.xml
src/extension/netcdf/src/main/java/org/geoserver/netcdf/NetCDFUnitsConfigurator.java
src/extension/netcdf/src/test/java/org/geoserver/netcdf/NetCDFUnitTest.java
src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/GMLTransformer.java
src/web/core/src/main/java/org/geoserver/web/data/resource/CoverageBandsConfigurationPanel.java

This PR depends on two GeoTools PRs, until they get merged it will fail to compile or execute tests:
* https://github.com/geotools/geotools/pull/2069
* https://github.com/geotools/geotools/pull/2075

[GEOS-8949] Allow NetCDF unit library configuration, and fix regression with some outputs caused by unit library upgrade

---

src/release/bin/shutdown.bat
src/release/bin/startup.bat

Some fixes regarding the Windows batch files
https://osgeo-org.atlassian.net/browse/GEOS-8950

Windows batch fixes

---

doc/en/user/source/community/netcdf-ghrsst/index.rst
doc/en/user/source/community/oauth2/index.rst
doc/en/user/source/community/taskmanager/user.rst
doc/en/user/source/community/wmts-multidimensional/index.rst
doc/en/user/source/configuration/globalsettings.rst
doc/en/user/source/data/raster/imagemosaic/tutorial.rst
doc/en/user/source/extensions/imagemap.rst
doc/en/user/source/extensions/monitoring/configuration.rst
doc/en/user/source/extensions/printing/configuration.rst
doc/en/user/source/filter/ecql_reference.rst
doc/en/user/source/production/container.rst
doc/en/user/source/rest/about.rst
doc/en/user/source/security/tutorials/credentialsfromheaders/index.rst
doc/en/user/source/services/wcs/reference.rst
doc/en/user/source/services/wcs/vendor.rst
doc/en/user/source/styling/mbstyle/cookbook/points.rst
doc/en/user/source/styling/mbstyle/cookbook/polygons.rst
doc/en/user/source/tutorials/animreflector.rst
doc/en/user/source/tutorials/tomcat-jndi/tomcat-jndi.rst
doc/en/user/source/tutorials/wmsreflector.rst

There are still 20+ warnings for where pygments isn't lexing the samples correctly.

[GEOS-8956] Update docs to fix sphinx warnings.

---

src/extension/app-schema/app-schema-mongo-test/src/test/java/org/geoserver/test/onlineTest/ComplexMongoDBLegacyTest.java
src/extension/app-schema/app-schema-mongo-test/src/test/java/org/geoserver/test/onlineTest/ComplexMongoDBSupport.java
src/extension/app-schema/app-schema-mongo-test/src/test/java/org/geoserver/test/onlineTest/ComplexMongoDBTest.java
src/extension/app-schema/app-schema-solr-test/src/test/java/org/geoserver/test/onlineTest/ComplexSolrTest.java
src/platform/src/main/java/org/geoserver/util/IOUtils.java

https://osgeo-org.atlassian.net/browse/GEOS-8954
Failing build:
https://build.geoserver.org/job/geoserver-master-app-schema-online/1296/display/redirect?page=changes
Relevant error:
```
-------------------------------------------------------
T E S T S
-------------------------------------------------------
Running org.geoserver.test.onlineTest.ComplexSolrTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.447 sec
Results :
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ gs-app-schema-solr-test ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: <https://build.geoserver.org/job/geoserver-master-app-schema-online/ws/src/extension/app-schema/app-schema-solr …
```

[GEOS-8954] Failling build for App-Schema integration tests for Solr and MongoDB

---

src/community/wfs3/src/main/java/org/geoserver/wfs3/DefaultWebFeatureService30.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/TilingSchemeDescriptionRequest.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/WFS3Filter.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/WebFeatureService30.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/kvp/TilingSchemeDetailKVPReader.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/response/BoundingBoxDocument.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/response/TileMatrixDocument.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/response/TilingSchemeDescriptionDocument.java
src/community/wfs3/src/main/java/org/geoserver/wfs3/response/TilingSchemeDetailResponse.java
src/community/wfs3/src/main/resources/applicationContext.xml
src/community/wfs3/src/test/java/org/geoserver/wfs3/TilingSchemesTest.java

This PR adds Wfs3 Tiling Scheme detail endpoint.
Example:
http://localhost:8080/geoserver/wfs3/tilingSchemes/GoogleMapsCompatible

Wfs3 Tiling Scheme detail endpoint

---

doc/en/user/source/data/database/sqlview.rst

**Should only be merged after https://github.com/geotools/geotools/pull/2086**
Backport of pull request:  https://github.com/geoserver/geoserver/pull/2901

[GEOS-8772] Add documentation about the :where_clause: place holder in SQL views \ virtual tables (backport 2.13.x)

---

src/extension/importer/core/src/main/java/org/geoserver/importer/EncryptedFieldConverter.java
src/extension/printing/src/main/java/org/geoserver/printing/PrintDemoPage.java

Part of the verbosity in the logs were two places where the formatter failed and outputs a stack trace.
This fixes that, and the format problems.

[GEOS-8967] Clean up formatter errors.

---

src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONBuilder.java

https://osgeo-org.atlassian.net/browse/GEOS-8965

[GEOS-8965] Simplefy GeoJSON builder measures (M) encoding code

---

doc/en/user/source/data/app-schema/mapping-file.rst
src/extension/app-schema/app-schema-indexes-test/README.rst
src/extension/app-schema/app-schema-indexes-test/pom.xml
src/extension/app-schema/app-schema-indexes-test/src/test/java/org/geoserver/test/onlineTest/ComplexIndexesTest.java
src/extension/app-schema/app-schema-indexes-test/src/test/java/org/geoserver/test/onlineTest/PgSchemaSetup.java
src/extension/app-schema/app-schema-indexes-test/src/test/java/org/geoserver/test/onlineTest/PostgresqlProperties.java
src/extension/app-schema/app-schema-indexes-test/src/test/java/org/geoserver/test/onlineTest/Resources.java
src/extension/app-schema/app-schema-indexes-test/src/test/java/org/geoserver/test/onlineTest/SolrIndexSetup.java
src/extension/app-schema/app-schema-indexes-test/src/test/java/org/geoserver/test/onlineTest/StationsMappingsSetup.java
src/extension/app-schema/app-schema-indexes-test/src/test/resources/test-data/complex-wildcard-query.xml
src/extension/app-schema/app-schema-indexes-test/src/test/resources/test-data/createFields.txt
src/extension/app-schema/app-schema-indexes-test/src/test/resources/test-data/geomType.txt
src/extension/app-schema/app-schema-indexes-test/src/test/resources/test-data/includedTypes.xml
src/extension/app-schema/app-schema-indexes-test/src/test/resources/test-data/insertData.txt
src/extension/app-schema/app-schema-indexes-test/src/test/resources/test-data/mappings.xml
src/extension/app-schema/app-schema-indexes-test/src/test/resources/test-data/meteo.xsd
src/extension/app-schema/app-schema-indexes-test/src/test/resources/test-data/pagination-test-query.xml
src/extension/app-schema/app-schema-indexes-test/src/test/resources/test-data/stations.sql
src/extension/app-schema/pom.xml

**Depends pull request https://github.com/geotools/geotools/pull/2081**
https://osgeo-org.atlassian.net/browse/GEOS-8959

[GEOS-8959] Add App-Schema integration tests and documentation about using Solr as an external index

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NestedGeometryFilterEncodingTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SRSReprojectionTest.java

**Depends on https://github.com/geotools/geotools/pull/2005**
Backport of PR:
https://github.com/geoserver/geoserver/pull/2885

[GEOS-8737] Add App-Schema integration tests checkign that spatial filters on nested properties are delegated to the database (backport 2.12.x)

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NestedGeometryFilterEncodingTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/SRSReprojectionTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/StationsMockData.java

**Depends on https://github.com/geotools/geotools/pull/2004**
Backport of PR:
https://github.com/geoserver/geoserver/pull/2885

[GEOS-8737] Add App-Schema integration tests checkign that spatial filters on nested properties are delegated to the database (backport 2.13.x)

---

src/community/netcdf-ghrsst/pom.xml
src/extension/netcdf-out/pom.xml

See https://github.com/geotools/geotools/pull/2083 for corresponding GeoTools PR.

[GEOS-8961] Upgrade netcdf to 4.6.11

---

src/extension/vectortiles/src/main/java/org/geoserver/wms/mapbox/MapBoxTileBuilderFactory.java
src/extension/vectortiles/src/main/resources/GeoServerApplication.properties
src/extension/vectortiles/src/main/resources/org/geoserver/gwc/advertised_formats.properties
src/extension/vectortiles/src/test/java/org/geoserver/wms/vector/VectorTilesIntegrationTest.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/CachingOptionsPanel.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/GeoServerTileLayerEditor.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/GWCSettingsPageTest.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/LayerCacheOptionsTabPanelTest.java

Depends on https://github.com/GeoWebCache/geowebcache/pull/694

[GEOS-8971] Use standard MapBox Vector Tiles mime type

---

src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/ImportLayer.java
src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/ImportTaskController.java
src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/converters/ImportJSONReader.java
src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/converters/ImportLayerJSONMessageConverter.java
src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/ImporterIntegrationTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-8869

[GEOS-8869] Importer REST should not override default LayerInfo Rest converter

---

src/community/gwc-distributed/src/test/java/org/geoserver/gwc/HazelcastTest.java
src/extension/wps/wps-cluster-hazelcast/pom.xml
src/pom.xml

* centralized hazelcast version
* fixed broken gwc test
hz-cluster module still failing Unable to fix it

Hazelcast community modules upgrade

---

src/extension/ogr/ogr-wps/src/test/java/org/geoserver/wps/ogr/WPSOgrTest.java
src/main/src/main/java/org/geoserver/catalog/impl/DefaultCatalogFacade.java
src/main/src/main/java/org/geoserver/catalog/impl/ModificationProxy.java
src/main/src/main/java/org/geoserver/config/util/CollectionConverter.java
src/main/src/main/java/org/geoserver/config/util/SecureXStream.java
src/main/src/main/java/org/geoserver/config/util/TreeMapConverter.java
src/main/src/main/java/org/geoserver/config/util/TreeSetConverter.java
src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
src/rest/src/main/java/org/geoserver/rest/converters/XStreamCatalogListConverter.java
src/rest/src/main/java/org/geoserver/rest/converters/XStreamJSONMessageConverter.java
src/wfs/src/test/java/org/geoserver/wfs/GetFeatureTest.java

There are quite a bit originating from GeoWebCache.
I've basically tried to follow the indication given by the XStream developers, and about to provide some feedback on the experience here: https://github.com/x-stream/xstream/issues/101

Eliminate XStream warnings originating from GeoServer

---

src/extension/wps/wps-core/src/main/java/org/geoserver/wps/GetCapabilities.java
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/WFSPPIO.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/ClipProcessTest.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/RasterAsPointCollectionTest.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/SimplifyProcessTest.java
src/main/src/test/java/org/geoserver/wfsng/WfsCompatibilityTest.java
src/ows/src/main/java/org/geoserver/ows/util/OwsUtils.java
src/ows/src/test/java/org/geoserver/ows/util/OwsUtilsTest.java
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/exception/OWS20ServiceExceptionHandler.java
src/wfs/src/main/java/org/geoserver/wfs/GetGmlObject.java
src/wfs/src/main/java/org/geoserver/wfs/response/ShapeZipOutputFormat.java
src/wfs/src/main/java/org/geoserver/wfs/xml/GML2OutputFormat2.java
src/wfs/src/main/java/org/geoserver/wfs/xml/v1_0_0/GetCapabilitiesTypeBinding.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/TransactionTest.java
src/wms/src/main/java/org/geoserver/wms/featureinfo/WMSLayerIdentifier.java

As a result of the EMF upgrade on GeoTools there are some minor changes required in GeoServer.

Emf upgrade

---

src/main/src/main/java/org/geoserver/ows/OWSHandlerMapping.java

Reverts geoserver/geoserver#3215
Sorry. just noticed that geoserver master is still frozen

Revert "Improve log messages"

---

src/main/src/main/java/org/geoserver/ows/OWSHandlerMapping.java

Update for PR provided by @Gnafu 
https://github.com/geoserver/geoserver/pull/3215
with proper reformatting applied by maven build.

Improve log messages

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/CoordinatesFormattingTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NamespacesWfsTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/StationsAppSchemaTestSupport.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/StationsMockData.java
src/wfs/src/main/java/org/geoserver/wfs/WFSGetFeatureOutputFormat.java

Complex features coordinates formatting fix and tests for GEOS-8935:
https://osgeo-org.atlassian.net/browse/GEOS-8935

[GEOS-8935] Complex features coordinates formatting fix (2.14.x backport)

---

src/community/authkey/src/main/java/org/geoserver/security/web/AuthenticationKeyFilterPanel.java

[GEOS-8868](https://osgeo-org.atlassian.net/browse/GEOS-8868) Change feedback panel name

GEOS-8868 Exception Synchronize user/group Authkey

---

src/web/security/ldap/src/main/java/org/geoserver/web/security/ldap/LDAPAuthProviderPanel.java
src/web/security/ldap/src/test/java/org/geoserver/web/security/ldap/LDAPAuthProviderPanelTest$LDAPFormTestPage.html
src/web/security/ldap/src/test/java/org/geoserver/web/security/ldap/LDAPAuthProviderPanelTest.java

[GEOS-8786](https://osgeo-org.atlassian.net/browse/GEOS-8786) Change feedback panel name

GEOS-8786 Fix Wicket exception - Test Connection button in LDAP Authentication Provider

---

doc/en/user/source/production/java.rst
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/DefaultGeometryTest.java
src/extension/arcsde/src/main/java/org/geoserver/web/data/store/arcsde/ArcSDECoverageStoreEditPanel.java
src/extension/importer/web/src/main/java/org/geoserver/importer/web/ImportDataPage.java

jdk11 Post-sprint activities, per the [spreadsheet](https://docs.google.com/spreadsheets/d/1oE6mU4jp-ZL5PebgXf-fuhtf7MY5dzSwPqpMtrzdZ94/edit#gid=2055024842)
Currently WIP, waiting to merge until everything is included
Depends upon https://github.com/geotools/geotools/pull/2183

jdk11 Post-sprint activities

---

src/extension/app-schema/app-schema-mongo-test/src/test/resources/mappings/stations.xml
src/extension/app-schema/app-schema-mongo-test/src/test/resources/schemas/stations.xsd

Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-9027

[GEOS-9027] MongoDB complex store iterator enters in an infinite loop if no ID is defined

---

src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/RasterSymbolizerBuilder.java
src/pom.xml

Do not merge yet, depends on https://github.com/geotools/geotools/pull/2194 and a JAI-EXTG release, now it's here only for review purposes.

Follow up GEOT-6193

---

src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/RasterSymbolizerBuilder.java
src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/RulesBuilder.java
src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/impl/BlueColorRamp.java
src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/impl/GrayColorRamp.java
src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/impl/RedColorRamp.java
src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/impl/SingleColorRamp.java
src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/ClassifierTest.java
src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/ColorRampTest.java
src/extension/sldService/src/test/java/org/geoserver/sldservice/utils/classifier/RasterSymbolizerBuilderTest.java
src/extension/sldService/src/test/java/org/geoserver/sldservice/utils/classifier/RulesBuilderTest.java

Fixing three issues in SLDService

Assorted fixes for SLDService

---

src/web/gwc/src/main/java/org/geoserver/gwc/web/blob/BlobStorePage.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/blob/BlobStorePageTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-9044

[GEOS-9044] Allow modifying blobstore without changing name via UI

---

src/wms/src/main/java/org/geoserver/wms/WMSRequests.java
src/wms/src/test/java/org/geoserver/wms/WMSRequestsTest.java

2.14.x backport for https://github.com/geoserver/geoserver/pull/3272

[GEOS-9011][2.14.x] Fixed KML network links losing some WMS GetMap parameters.

---

src/wms/src/main/java/org/geoserver/wms/WMSRequests.java
src/wms/src/test/java/org/geoserver/wms/WMSRequestsTest.java

2.13.x backport for https://github.com/geoserver/geoserver/pull/3272

[GEOS-9011][2.13.x] Fixed KML network links losing some WMS GetMap parameters.

---

src/main/src/main/java/org/geoserver/catalog/SLDHandler.java

See https://osgeo-org.atlassian.net/browse/GEOS-9046
Backport of #3283

[GEOS-9046] [Backport 2.13] Remove unnecessary check for ready in SLDHandler

---

src/main/src/main/java/org/geoserver/catalog/SLDHandler.java

See https://osgeo-org.atlassian.net/browse/GEOS-9046
Backport of #3283

[GEOS-9046] [Backport 2.14] Remove unnecessary check for ready in SLDHandler

---

src/community/security/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilter.java

Authorization header in the doFilter function and getPreAuthenticatedPrincipal.  Previosuly it was not getting token from header in the getPreAuthenticatedPrincipal function.  This is to get change into 2.14.x branch for future release of 2.14

Change to OAuth core to take token from header and parameter.

---

src/gwc/src/main/java/org/geoserver/gwc/config/GWCInitializer.java
src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
src/main/src/main/java/org/geoserver/config/GeoServerConfigPersister.java
src/main/src/main/java/org/geoserver/config/GeoServerDataDirectory.java
src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
src/main/src/main/java/org/geoserver/config/GeoServerLoaderProxy.java
src/main/src/test/java/org/geoserver/catalog/CatalogIntegrationTest.java
src/platform/src/main/java/org/geoserver/platform/ExtensionPriority.java
src/platform/src/main/java/org/geoserver/platform/GeoServerExtensions.java

While working on speeding up this very slow bit of the build I've found GEOS-9066, which is an important bug fix, and GEOS-9080, which is mostly annoying but still potentially harmful.

GWCIntegrationTest without full reloads, along with bug fixes found while working on it

---

doc/en/user/source/filter/function_reference.rst

See https://github.com/geotools/geotools/pull/2217

[GEOT-6208] Update docs for new GeoTools String functions

---

src/community/jdbcconfig/src/main/resources/org/geoserver/jdbcconfig/internal/initdb.postgres.sql

https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-9055

[GEOS-9055] JDBCConfig - duplicate database index

---

doc/en/user/source/configuration/image_processing/index.rst
doc/en/user/source/production/java.rst
src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/ClassifierTest.java
src/extension/sldService/src/test/java/org/geoserver/sldservice/utils/classifier/RasterSymbolizerBuilderTest.java
src/extension/wps/wps-core/src/test/java/org/geoserver/wps/WPSTestSupport.java
src/main/src/test/java/org/geoserver/catalog/CoverageViewTest.java
src/pom.xml
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DimensionsRasterGetMapTest.java

Depends on https://github.com/geotools/geotools/pull/2237

Swiching jai-ext on by default

---

doc/en/user/source/styling/mbstyle/reference/index.rst
doc/en/user/source/styling/mbstyle/reference/spec.rst

GeoServer port of https://github.com/geotools/geotools/pull/2238 (retaining GeoServer-specific URLs and examples)

Mapbox Styles expressions documentation

---

src/web/core/src/main/java/org/geoserver/web/admin/ModuleStatusPanel.java
src/web/core/src/test/java/org/geoserver/web/admin/StatusPageTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-9121

[GEOS-9121] Added a fixed sort order to the module status table.

---

src/web/core/src/main/java/org/geoserver/web/admin/ModuleStatusPanel.java
src/web/core/src/test/java/org/geoserver/web/admin/StatusPageTest.java

2.15.x backport for https://github.com/geoserver/geoserver/pull/3348

[GEOS-9121][2.15.x] Added a fixed sort order to the module status table.

---

src/extension/csw/api/src/main/java/org/geoserver/csw/records/iso/MetaDataDescriptor.java
src/extension/csw/core/src/main/java/org/geoserver/csw/response/MetaDataTransformer.java
src/extension/csw/core/src/main/resources/org/geoserver/csw/store/internal/MD_Metadata.default.properties
src/extension/csw/core/src/test/java/org/geoserver/csw/records/iso/GetRecordByIdTest.java
src/extension/csw/core/src/test/java/org/geoserver/csw/records/iso/GetRecordsTest.java
src/extension/csw/core/src/test/resources/org/geoserver/csw/store/internal/MD_Metadata.properties

https://osgeo-org.atlassian.net/browse/GEOS-9095
also fixed the wrong use of the AbstractMD_Identification tag (has to be MD_DataIdentification for layers)

GEOS-9095 csw iso metadata tag order

---

src/web/core/src/main/java/org/geoserver/web/admin/ModuleStatusPanel.java
src/web/core/src/test/java/org/geoserver/web/admin/StatusPageTest.java

2.14.x backport for https://github.com/geoserver/geoserver/pull/3348

[GEOS-9121][2.14.x] Added a fixed sort order to the module status table.

---

src/gwc/src/main/resources/geowebcache-core-context.xml

See https://osgeo-org.atlassian.net/browse/GEOS-9119

[GEOS-9119] Add missing parameter to gwcBlobStore bean configuration

---

src/pom.xml

Upgrade to [jts-1.16.1](https://github.com/locationtech/jts/releases/tag/jts-1.16.1) point release

Update to JTS 1.16.1

---

src/restconfig/src/main/java/org/geoserver/rest/security/RestConfigXStreamPersister.java
src/restconfig/src/main/resources/applicationContext.xml
src/restconfig/src/test/java/org/geoserver/rest/security/XStreamParserTest.java

https://osgeo-org.atlassian.net/browse/GEOS-8486
added XStreamPersister  dedicated to aliasing and white listing JaxbUser class for XML and JSON marshalling/unmarshalling

[GEOS-8486] create new user through REST API

---

src/restconfig/src/main/java/org/geoserver/rest/security/RestConfigXStreamPersister.java
src/restconfig/src/main/resources/applicationContext.xml
src/restconfig/src/test/java/org/geoserver/rest/security/XStreamParserTest.java

back porting to Stable
https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-8486

[GEOS-8486] create new user through REST API - 2.15.x

---

src/restconfig/src/main/java/org/geoserver/rest/security/RestConfigXStreamPersister.java
src/restconfig/src/main/resources/applicationContext.xml
src/restconfig/src/test/java/org/geoserver/rest/security/XStreamParserTest.java

back porting to Maintenance 
https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-8486

[GEOS-8486] create new user through REST API - 2.14.x

---

src/extension/importer/web/src/main/java/org/geoserver/importer/web/AbstractDbPanel.java
src/extension/importer/web/src/test/java/org/geoserver/importer/web/AbstractDBPanelTest.java
src/web/core/src/test/java/org/geoserver/web/GeoServerWicketUnitTestSupport.java

@jodygarnett @tbarsballe I did not test interactively, is it something you'd be happy to do?

[GEOS-9140] Import Data unable to connect to and create PostGIS DataStore

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleAdminPanel.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleNewPageTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-9151

[GEOS-9151] Fixed copying the style format in the New Style page.

---

src/main/src/main/java/org/geoserver/template/FeatureWrapper.java
src/wms/src/test/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormatTest.java
src/wms/src/test/resources/org/geoserver/wms/featureinfo/test_resource_content.ftl

See https://osgeo-org.atlassian.net/browse/GEOS-9155

[GEOS-9155] Fixed GetFeatureInfo templates not being able to retrieve metadata for raster layers.

---

src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/GMLTransformer.java
src/wcs2_0/src/main/resources/schemas/wcs/2.0/wcsgs.xsd
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/DescribeCoverageTest.java

2.15.x backport for https://github.com/geoserver/geoserver/pull/3388

[GEOS-9141][2.15.x] Fixed invalid WCS 2.0.1 DescribeCoverage with elevation and custom dimensions.

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleAdminPanel.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleNewPageTest.java

2.15.x backport for https://github.com/geoserver/geoserver/pull/3399

[GEOS-9151][2.15.x] Fixed copying the style format in the New Style page.

---

src/main/src/main/java/org/geoserver/template/FeatureWrapper.java
src/wms/src/test/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormatTest.java
src/wms/src/test/resources/org/geoserver/wms/featureinfo/test_resource_content.ftl

2.15.x backport for https://github.com/geoserver/geoserver/pull/3406

[GEOS-9155][2.15.x] Fixed GetFeatureInfo templates not being able to retrieve metadata for raster layers.

---

src/main/src/main/java/org/geoserver/template/FeatureWrapper.java
src/wms/src/test/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormatTest.java
src/wms/src/test/resources/org/geoserver/wms/featureinfo/test_resource_content.ftl

2.14.x backport for https://github.com/geoserver/geoserver/pull/3406

[GEOS-9155][2.14.x] Fixed GetFeatureInfo templates not being able to retrieve metadata for raster layers.

---

src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/GMLTransformer.java
src/wcs2_0/src/main/resources/schemas/wcs/2.0/wcsgs.xsd
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/DescribeCoverageTest.java

2.14.x backport for https://github.com/geoserver/geoserver/pull/3388

[GEOS-9141][2.14.x] Fixed invalid WCS 2.0.1 DescribeCoverage with elevation and custom dimensions.

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/StyleAdminPanel.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleNewPageTest.java

2.14.x backport for https://github.com/geoserver/geoserver/pull/3399

[GEOS-9151][2.14.x] Fixed copying the style format in the New Style page.

---

src/extension/wcs2_0-eo/core/src/test/java/org/geoserver/wcs2_0/eo/DescribeOECoverageSetTest.java
src/main/src/main/java/org/geoserver/security/decorators/SecuredCoverageInfo.java
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/GMLTransformer.java
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCS20DescribeCoverageTransformer.java
src/wcs2_0/src/test/java/org/geoserver/wcs2_0/ResourceAccessManagerWCSTest.java
src/wcs2_0/src/test/resources/org/geoserver/wcs2_0/ResourceAccessManagerContext.xml

Mimicks the behavior of WMS GetCapabilties, also allowing access to times/elevations when running DescribeCoverage

[GEOS-8450] DescribeCoverage should not fail on secured datasets with catalog in challenge mode

---

src/main/src/main/java/org/geoserver/catalog/StyleInfo.java
src/main/src/main/java/org/geoserver/catalog/impl/StyleInfoImpl.java
src/main/src/test/java/org/geoserver/catalog/CatalogIntegrationTest.java
src/restconfig/src/test/java/org/geoserver/rest/catalog/StyleControllerTest.java

This PR enhances StyleInfo and StyleInfoImpl Catalog objects adding a MetadataMap attribute for being serialized by Xstream.
Also adds Rest integration tests on Restconfig module.
https://osgeo-org.atlassian.net/browse/GEOS-9209

[GEOS-9209] Enhance StyleInfo with MetadataMap on Catalog object and Rest entpoint.

---

src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java

This test has been plaguing PRs with random failures for a while, this is an attempt to fix it.

Attempt to fix random failure in GWC tests

---

src/extension/app-schema/app-schema-indexes-test/src/test/java/org/geoserver/test/onlineTest/ComplexIndexesTest.java

This PR adds integration testing for: App-schema indexes makes query without correct maxFeatures number on "rows" parameter to Apache Solr.
https://osgeo-org.atlassian.net/browse/GEOS-9165
Requires:
https://github.com/geotools/geotools/pull/2336

[GEOS-9165] App-schema indexes integration test for fix solr query row limit

---

src/extension/app-schema/app-schema-indexes-test/src/test/java/org/geoserver/test/onlineTest/ComplexIndexesTest.java

This PR adds integration testing for: App-schema indexes makes query without correct maxFeatures number on "rows" parameter to Apache Solr.
https://osgeo-org.atlassian.net/browse/GEOS-9165
Requires:
https://github.com/geotools/geotools/pull/2358

[GEOS-9165] App-schema indexes integration test for fix solr query row limit (2.15.x backport)

---

src/extension/app-schema/app-schema-indexes-test/src/test/java/org/geoserver/test/onlineTest/ComplexIndexesTest.java

This PR adds integration testing for: App-schema indexes makes query without correct maxFeatures number on "rows" parameter to Apache Solr.
https://osgeo-org.atlassian.net/browse/GEOS-9165
Requires:
https://github.com/geotools/geotools/pull/2359

[GEOS-9165] App-schema indexes integration test for fix solr query row limit (2.14.x backport)

---

doc/en/user/source/data/app-schema/solr-tutorial.rst

This PR adds App-Schema Solr Index only layer support to Geoserver documentation.

Added App-Schema Solr Indexes documentation.

---

src/pom.xml

Upgraded spring security to latest bugfix version 5.1.5.

Upgraded spring security version from 5.1.1 -> 5.1.5

---

src/community/security/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilter.java
src/extension/geofence/src/main/java/org/geoserver/geoserver/authentication/auth/GeoFenceAuthenticationProvider.java
src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorFilter.java
src/extension/wps/wps-core/src/main/java/org/geoserver/wps/Executions.java
src/main/src/main/java/org/geoserver/security/SecurityUtils.java
src/main/src/main/java/org/geoserver/security/auth/GeoServerRootAuthenticationProvider.java
src/wfs/src/main/java/org/geoserver/wfs/Transaction.java

Backports to 2.15.x the Fixes for JIRA GEOS-9015 - WPS GetExecutions Operation Impl - Improve the way it recognizes the principal username

[Backport to 2.15.x] [Fixes JIRA GEOS-9015] - WPS GetExecutions Operation Impl - Improve the way it recognizes the principal username

---

src/main/src/test/java/org/geoserver/data/test/SystemTestData.java
src/restconfig/src/main/java/org/geoserver/rest/catalog/FeatureTypeController.java
src/restconfig/src/test/java/org/geoserver/rest/catalog/FeatureTypeControllerTest.java

Fix https://osgeo-org.atlassian.net/browse/GEOS-9217

fixed bug GEOS-9217

---

data/release/security/services.properties
src/main/src/main/java/org/geoserver/security/impl/serviceTemplate.properties

https://osgeo-org.atlassian.net/browse/GEOS-9215

[GEOS-9215] Restrict usage of WFS StoredQuery creation/update/removal to admin users by default

---

src/community/wfs3/pom.xml

Clean up WFS 3 (community module) POM, removing duplicate entry that causes maven to complain.

Remove duplicate schema entry from WFS 3 deps.

---

src/community/wfs3/src/test/java/org/geoserver/wfs3/CollectionsTest.java
src/community/wfs3/src/test/java/org/geoserver/wfs3/LandingPageTest.java
src/community/wfs3/src/test/java/org/geoserver/wfs3/WFS3TestSupport.java

Re-uses JSON tests where appropriate.

WFS3: add tests for YAML.

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/web/AbstractMapPreviewPageTest.java
src/web/demo/src/main/java/applicationContext.xml
src/web/demo/src/main/java/org/geoserver/web/demo/CommonFormatLink.java
src/web/demo/src/main/java/org/geoserver/web/demo/GMLFormatLink.java
src/web/demo/src/main/java/org/geoserver/web/demo/KMLFormatLink.java
src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.html
src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.java
src/web/demo/src/main/java/org/geoserver/web/demo/OpenLayersFormatLink.java
src/web/demo/src/main/java/org/geoserver/web/demo/PreviewLayer.java
src/web/demo/src/main/resources/GeoServerApplication.properties
src/web/demo/src/test/java/org/geoserver/web/demo/MapPreviewPageTest.java

Allow extension modules to add to the set of "Common Formats" links in the Layer Preview page on a per-layer basis.
Note that one (important) file MapPreviewPage.html shows itself to be 100% different from that in master.  I verified my settings for core autocrlf=true to be correct.  I looked at the history of the file and it appears that the previous check-in of the file also showed a 100% difference.   So this check-in may fix that problem from now on, so long as devs have the correct autocrlf setting locally (per the [recommendations](https://docs.geoserver.org/latest/en/developer/source.html#git-client-configuration)). …

[GEOS-9222] Permit extensibility of Common Formats from Layer Preview page

---

src/wms/src/main/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormat.java

Made getTemplate method in HTMLFeatureInfoOutputFormat protected

[GEOS-9193] made getTemplate method in HTMLFeatureInfoOutputFormat protected [Backport to 2.15.x]

---

src/gwc/src/main/java/org/geoserver/gwc/seed/SeederThreadLocalTransferExecutor.java
src/gwc/src/main/resources/geowebcache-core-context.xml
src/gwc/src/test/java/org/geoserver/gwc/GWCSeedingSecurityIntegrationTest.java

Backport of https://github.com/geoserver/geoserver/pull/3525 to 2.15.x

[GEOS-8752] Allow integrated GWC to seed secured layers (2.15.x backport)

---

src/gwc/src/main/java/org/geoserver/gwc/seed/SeederThreadLocalTransferExecutor.java
src/gwc/src/main/resources/geowebcache-core-context.xml
src/gwc/src/test/java/org/geoserver/gwc/GWCSeedingSecurityIntegrationTest.java

Backport of https://github.com/geoserver/geoserver/pull/3525 to 2.14.x

[GEOS-8752] Allow integrated GWC to seed secured layers (2.14.x backport)

---

src/pom.xml

Depends on:
https://github.com/geotools/geotools/pull/2420
https://github.com/GeoWebCache/geowebcache/pull/769

Updating imageio-ext and jai-ext versions

---

src/pom.xml

depends on:
https://github.com/geotools/geotools/pull/2421
https://github.com/GeoWebCache/geowebcache/pull/768

Updating to jai-ext 1.1.10 - on GS 2.15.x

---

src/pom.xml

https://osgeo-org.atlassian.net/browse/GEOS-9211

[GEOS-9211] Upgraded jackson to 2.9.9

---

src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/DescribeDomainsTransformer.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/MultiDimensionalExtension.java
src/community/wmts-multi-dimensional/src/main/java/org/geoserver/gwc/wmts/dimensions/DimensionsUtils.java
src/community/wmts-multi-dimensional/src/test/java/org/geoserver/gwc/wmts/MultiDimensionalExtensionTest.java
src/community/wmts-multi-dimensional/src/test/resources/TimeElevationWithStartEnd.properties

Wmts multidim bbox

---

doc/en/user/source/extensions/netcdf/netcdf.rst

Restoring the previous section reporting that 2D not-independent coordinate variables aren't unsupported

Updating NetCDF Documentation - 2D coord variables

---

doc/en/api/1.0.0/datastores.yaml
doc/en/user/source/rest/appschema.rst
src/extension/app-schema/app-schema-mongo-test/pom.xml
src/extension/app-schema/app-schema-mongo-test/src/test/java/org/geoserver/test/onlineTest/ComplexMongoDBSupport.java
src/extension/app-schema/app-schema-mongo-test/src/test/java/org/geoserver/test/onlineTest/ComplexMongoDBTest.java
src/extension/app-schema/app-schema-mongo-test/src/test/resources/data/stations1.json
src/extension/app-schema/app-schema-mongo-test/src/test/resources/data/stations2.json
src/extension/app-schema/app-schema-mongo-test/src/test/resources/mappings/stations.xml
src/extension/app-schema/app-schema-mongo-test/src/test/resources/mappings/stations_legacy.xml
src/extension/app-schema/app-schema-mongo-test/src/test/resources/schemas/stations.xsd
src/extension/mongodb/pom.xml
src/extension/mongodb/src/main/java/org/geoserver/rest/service/MongoStoreRestController.java

This PR adds a Rest controller endpoint for to clean previously generated schemas so mongoDB store can generate them with new parameters on demand. Some AppSchema MongoDB integration testing added.
Requires merged:
https://github.com/geotools/geotools/pull/2427
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-9241
Submitting the PR does not require you to check all …

[GEOS-9241] Enhance mongodb schema generation.

---

doc/en/docguide/source/install.rst
doc/en/docguide/source/workflow.rst

Updating the sphinx installation instruction and needed command to build the GeoServer documentation

[GEOS-9253]: Updating Sphinx DOC building instructions

---

.travis.yml
src/main/src/main/java/org/geoserver/config/GeoServerResourcePersister.java
src/main/src/test/java/org/geoserver/config/GeoServerPersistersTest.java

Backport 2.15.x [GEOS-9229] Rename the resource only if the old name and the new one are not identical

---

src/main/pom.xml
src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java

[Backport 2.14.x] GEOS-9237 --GeoTIFF sources configured with GeoServer 2.14.x might not work in 2.15.x

---

src/web/core/src/main/java/org/geoserver/web/wicket/FileExistsValidator.java
src/web/core/src/main/resources/GeoServerApplication.properties
src/web/core/src/test/java/org/geoserver/web/wicket/FileExistsValidatorTest.java
src/web/wms/src/main/java/org/geoserver/wms/web/WMSAdminPage.java

Reverts geoserver/geoserver#3630

Revert "[GEOS-9276] WMS configuration UI, watermark file input allows to validate a remote HTTP URL"

---

doc/en/user/source/configuration/crshandling/coordtransforms.rst
src/wcs2_0/src/main/java/org/geoserver/wcs2_0/util/EnvelopeAxesLabelsMapper.java

This is a simple follow up to the https://github.com/geotools/geotools/pull/2479 GeoTools EPSG database upgrade, updating documentation and fixing one item in the WCS code that the upgrade broke (the lon/lat axis are now available in a few variations, with different abbreviations). …

Follow up to the EPSG v9.6 upgrade

---

doc/en/user/source/community/gwc-s3/index.rst

Update docs (was noted during gwc-azure PR review).

Typo fix in gwc-s3 docs

---

src/web/core/src/main/java/org/geoserver/web/data/store/DefaultDataStoreEditPanel.java
src/web/core/src/main/java/org/geoserver/web/util/EnumAdapterModel.java
src/web/core/src/test/java/org/geoserver/web/data/store/DataAccessEditPageTest.java
src/web/core/src/test/java/org/geoserver/web/util/EnumAdapterModelTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-9283

[GEOS-9283] SSLMode in Postgis datastore is blank after reloading the configuration

---

src/main/src/main/java/applicationSecurityContext.xml
src/main/src/main/java/org/geoserver/security/SecuredResourceNameChangeListener.java
src/security/security-tests/src/test/java/org/geoserver/security/impl/RuleSyncedNameChangeTest.java

https://osgeo-org.atlassian.net/browse/GEOS-9228

[GEOS-9228] Renaming a layer doesn't update Data Security rules

---

src/community/jdbcstore/src/main/java/org/geoserver/jdbcstore/internal/JDBCDirectoryStructure.java

FileWatcher uses lastmodified() to determine if a file has changed.
In a clustered environment, JdbcStore will return the same value as long as you are keeping the same resource instance (re-getting the resource from the store would return an updated value).
Jdbcstore should be fixed to support this.

GEOS-9175 jdbcstore filewatcher compatibility

---

doc/en/api/1.0.0/datastores.yaml
doc/en/user/source/rest/appschema.rst
src/extension/app-schema/app-schema-mongo-test/pom.xml
src/extension/app-schema/app-schema-mongo-test/src/test/java/org/geoserver/test/onlineTest/ComplexMongoDBSupport.java
src/extension/app-schema/app-schema-mongo-test/src/test/java/org/geoserver/test/onlineTest/ComplexMongoDBTest.java
src/extension/app-schema/app-schema-mongo-test/src/test/resources/data/stations1.json
src/extension/app-schema/app-schema-mongo-test/src/test/resources/data/stations2.json
src/extension/app-schema/app-schema-mongo-test/src/test/resources/mappings/stations.xml
src/extension/app-schema/app-schema-mongo-test/src/test/resources/mappings/stations_legacy.xml
src/extension/app-schema/app-schema-mongo-test/src/test/resources/schemas/stations.xsd
src/extension/mongodb/pom.xml
src/extension/mongodb/src/main/java/org/geoserver/rest/service/MongoStoreRestController.java

This PR adds a Rest controller endpoint for to clean previously generated schemas so mongoDB store can generate them with new parameters on demand. Some AppSchema MongoDB integration testing added.
2.15.x backport.
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-9241
Submitting the PR does not require you to check all items, but by the time it gets merged, they should be …

[GEOS-9241] Enhance mongodb schema generation. (2.15.x backport)

---

build/build_release.sh
build/publish_release.sh

Update build scripts with SKIP COMMUNITY option

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/AbstractStylePage.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleNewPageTest.java

Style image preview breaks with jdbcstore. Using in memory stream rather than file reference to resolve.

GEOS-9185 style image preview jdbcstore

---

src/web/core/src/main/java/org/geoserver/web/css/geoserver.css

Show empty option in dropdowns (null workspace in style)

---

doc/en/api/1.0.0/datastores.yaml
src/extension/app-schema/app-schema-mongo-test/src/test/java/org/geoserver/test/onlineTest/ComplexMongoDBSupport.java
src/extension/app-schema/app-schema-mongo-test/src/test/java/org/geoserver/test/onlineTest/ComplexMongoDBTest.java
src/extension/mongodb/src/main/java/org/geoserver/rest/service/MongoStoreRestController.java

This PR improves MongoDB App-Schema schema rebuild REST endpoint, building only schemas used in declared mappings and giving an extra parameter to define a schema name to re-build.
Requires:
https://github.com/geoserver/geoserver/pull/3656
Issue:
https://osgeo-org.atlassian.net/browse/GEOS-9268
Submitting the PR does not require you to check all items, but by the time it …

[GEOS-9268] Make MongoDB App-Schema schema rebuilder endpoints only rebuild schemas present in mappings (2.15.x.backport)

---

CODE_OF_CONDUCT.md

OSGeo changed its recommendations from its own home grown code of conduct to https://www.contributor-covenant.org
See https://www.osgeo.org/code_of_conduct/ for details.
This pull request was actually made from the GitHub "community" wizard for adding a code of conduct to your repository. Ideally I would like to update http://geoserver.org/comm/userlist-guidelines.html also.
The following are required only for core and …

Adopt Contributor Covenant [GEOS-9295]

---

doc/en/developer/source/conf.py
doc/en/docguide/source/conf.py
doc/en/themes/geoserver/layout.html
doc/en/user/source/conf.py

Update the sphinx theme to include an edit button
- [ x You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)

Update sphinx theme to include edit link [GEOS-9282]

---

src/community/pom.xml

This PR removes status-monitoring reference on community pom.xml since it was promoted to core.

Fix status-monitoring reference on community pom.xml

---

.travis.yml

An attempt to make Travis also build documentation as well as release and community package assembly, to spot issues in those two areas at the PR level.

Travis changes to also build documentation and run assembly

---

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/catalog/CatalogImplWithJDBCFacadeTest.java

GEOS-9290 jdbcconfig: update catalog info references

---

src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/JDBCGeoServerLoader.java
src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/JDBCConfigTestSupport.java
src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/catalog/CatalogImplWithJDBCFacadeTest.java
src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/catalog/JDBGeoserverResourcePersisterTest.java
src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/GeoServerInstance.java
src/extension/csw/web-csw/src/main/java/org/geoserver/csw/web/CSWLayerConfig.java
src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
src/main/src/main/java/org/geoserver/config/DefaultGeoServerLoader.java
src/main/src/main/java/org/geoserver/config/GeoServerLoader.java
src/main/src/main/java/org/geoserver/config/GeoServerResourcePersister.java
src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java
src/main/src/test/java/org/geoserver/config/GeoServerPersistersTest.java
src/main/src/test/java/org/geoserver/data/test/SystemTestData.java
src/platform/src/main/java/org/geoserver/platform/resource/Resources.java
src/rest/src/main/java/org/geoserver/rest/converters/XStreamXMLMessageConverter.java
src/restconfig/src/main/java/org/geoserver/rest/catalog/LayerGroupController.java
src/restconfig/src/main/java/org/geoserver/rest/catalog/StyleController.java
src/restconfig/src/test/java/org/geoserver/rest/catalog/StyleControllerTest.java
src/security/security-tests/src/test/java/org/geoserver/security/impl/MemoryUserDetailsServiceTest.java

GEOS-9293 Style rest PUT issues

---

src/pom.xml

Follow up to GeoTools upgrade of JAI-EXT, 1.1.12 has a faster quantizer

Updating to jai-ext 1.1.12 (faster 8bit quantizer)

---

doc/en/user/source/filter/filter_reference.rst

added note clarifying disjoint

---

doc/en/developer/source/policies/psc.rst

Brad Hards stepping down from PSC.

---

src/community/ogcapi/ogcapi-styles/src/main/java/org/geoserver/api/styles/StylesService.java
src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/api/styles/StyleTest.java

Community module, making PR to get QA confirmations

Style post and put are failing if charset is not set in the HTTP request

---

src/extension/system-status/src/main/java/org/geoserver/system/status/web/RefreshedPanel.html
src/extension/system-status/src/main/java/org/geoserver/system/status/web/RefreshedPanel.java
src/extension/system-status/src/main/java/org/geoserver/system/status/web/SystemStatusMonitorPanel.html
src/extension/system-status/src/main/java/org/geoserver/system/status/web/SystemStatusMonitorPanel.java
src/extension/system-status/src/test/java/org/geoserver/system/status/SystemStatusMonitorPanelTest.java

Manual backport of:
https://github.com/geoserver/geoserver/pull/3725
Backport need to be manual since in 2.15.x is an extension and not core.

[GEOS-9311] Switching from System Status to Modules tab gives an error (Backport to 2.15.x)

---

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/AbstractDocument.java
src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/AbstractLandingPageDocument.java
src/community/ogcapi/ogcapi-core/src/main/resources/org/geoserver/api/common-header.ftl
src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/api/OGCApiTestSupport.java
src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/api/features/FeaturesLandingPage.java
src/community/ogcapi/ogcapi-styles/src/main/java/org/geoserver/api/styles/StylesLandingPage.java
src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/StyleDocument.java
src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TiledCollectionDocument.java
src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TilesDocument.java
src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TilesLandingPage.java
src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TilesService.java
src/community/ogcapi/ogcapi-tiles/src/main/resources/org/geoserver/api/tiles/collection.ftl
src/community/ogcapi/ogcapi-tiles/src/main/resources/org/geoserver/api/tiles/tiles.ftl
src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/CollectionTest.java
src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/GetTileTest.java
src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/LandingPageTest.java
src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/TileDescriptionTest.java
src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/TilesTestSupport.java

Align tile implementation to latest changes in API

---

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/AbstractDocument.java
src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TileMatrixSetDocument.java
src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TileMatrixSetLink.java
src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TileMatrixSets.java
src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TilesLandingPage.java
src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TilesService.java
src/community/ogcapi/ogcapi-tiles/src/main/resources/org/geoserver/api/tiles/landingPage.ftl
src/community/ogcapi/ogcapi-tiles/src/main/resources/org/geoserver/api/tiles/tileMatrixSet.ftl
src/community/ogcapi/ogcapi-tiles/src/main/resources/org/geoserver/api/tiles/tileMatrixSets.ftl
src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/LandingPageTest.java
src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/TileDescriptionTest.java

Adding tile matrix set declarations in OGC API for tiles

---

src/release/ext-gdal.xml

fixing gdal bindings jar name

---

src/community/release/pom.xml

Readds the GeoStyler community plugin that got lost due to https://github.com/geoserver/geoserver/commit/6116baeacd1916fd039ae52d118d86d27ef5d5bb#diff-5722047120a971de700f246992614df5R359

Readd the geostyler community module

---

doc/en/user/source/services/wms/basics.rst

Disambiguation of WMS Axis Ordering differences

---

.travis.yml

Travis CI: The 'sudo:' tag is deprecated in Travis

---

doc/en/developer/source/index.rst
doc/en/developer/source/win-installer.rst
doc/en/user/source/installation/win_installer.rst
src/pom.xml

Depends to, and follows up with https://github.com/geotools/geotools/pull/2588
and https://github.com/GeoWebCache/geowebcache/pull/792

[GEOS-9350] Upgrade Jackson to 2.9.10

---

src/pom.xml

[GEOS-9350] Upgrade Jackson to 2.9.10 (2.16.x backport)

---

src/main/src/main/java/org/geoserver/security/SecuredResourceNameChangeListener.java
src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java

[GEOS-9343] Update data rules (layer and layer groups) rules at runtime

---

src/main/src/main/java/org/geoserver/catalog/CatalogInfo.java
src/main/src/main/java/org/geoserver/catalog/impl/AdvertisedCatalog.java
src/main/src/main/java/org/geoserver/catalog/impl/LayerGroupInfoImpl.java
src/main/src/main/java/org/geoserver/security/DisabledResourceFilter.java
src/main/src/main/java/org/geoserver/security/decorators/DecoratingLayerGroupInfo.java
src/security/security-tests/src/test/java/org/geoserver/security/impl/AbstractAuthorizationTest.java
src/security/security-tests/src/test/java/org/geoserver/security/impl/AdvertisedCatalogTest.java
src/security/security-tests/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java
src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupEditPage$LayerGroupTab.html
src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupEditPage.java
src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupPage.html
src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupPage.java
src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupProvider.java
src/web/demo/src/main/java/org/geoserver/web/demo/PreviewLayerProvider.java
src/web/demo/src/test/java/org/geoserver/web/demo/PreviewLayerProviderTest.java

[GEOS-9340] Extra metadata for layers groups (enabled and advertised)

---

src/main/src/main/java/org/geoserver/catalog/CatalogInfo.java
src/main/src/main/java/org/geoserver/catalog/impl/AdvertisedCatalog.java
src/main/src/main/java/org/geoserver/catalog/impl/LayerGroupInfoImpl.java
src/main/src/main/java/org/geoserver/security/DisabledResourceFilter.java
src/main/src/main/java/org/geoserver/security/decorators/DecoratingLayerGroupInfo.java
src/security/security-tests/src/test/java/org/geoserver/security/impl/AbstractAuthorizationTest.java
src/security/security-tests/src/test/java/org/geoserver/security/impl/AdvertisedCatalogTest.java
src/security/security-tests/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java
src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupEditPage$LayerGroupTab.html
src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupEditPage.java
src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupPage.html
src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupPage.java
src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupProvider.java
src/web/demo/src/main/java/org/geoserver/web/demo/PreviewLayerProvider.java
src/web/demo/src/test/java/org/geoserver/web/demo/PreviewLayerProviderTest.java

Reverts geoserver/geoserver#3778

Revert "[GEOS-9340] Extra metadata for layers groups (enabled and advertised)"

---

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/APIDispatcher.java
src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/APIRequestInfo.java
src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/LocalWorkspaceCallback.java
src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/LocalWorkspaceURLPathHelper.java
src/community/ogcapi/ogcapi-core/src/main/resources/applicationContext.xml
src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/api/features/CollectionDocument.java
src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/api/features/ApiTest.java
src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/api/features/CollectionTest.java
src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/api/features/CollectionsTest.java
src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/api/features/FeatureTest.java
src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/api/features/LandingPageTest.java
src/community/ogcapi/ogcapi-images/src/main/resources/org/geoserver/api/images/collection.ftl
src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/api/images/ApiTest.java
src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/api/images/CollectionTest.java
src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/api/images/ImagesTestSupport.java
src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/api/images/LandingPageTest.java
src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/api/styles/ApiTest.java
src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/api/styles/LandingPageTest.java
src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TiledCollectionDocument.java
src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TilesAPIBuilder.java
src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TilesDocument.java
src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TilesService.java
src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/ApiTest.java
src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/CollectionsTest.java
src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/GetTileTest.java
src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/LandingPageTest.java
src/extension/sldService/src/main/java/org/geoserver/sldservice/rest/ImageReader.java
src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
src/main/src/main/java/org/geoserver/catalog/impl/LocalWorkspaceCatalog.java

Workspace specific support for OGC API services

---

doc/en/user/source/community/params-extractor/index.rst
src/community/params-extractor/src/main/java/org/geoserver/params/extractor/Filter.java
src/community/params-extractor/src/test/java/org/geoserver/params/extractor/FilterTest.java

Allows the params-extract filter to run before the security filters chain, so that parameters used by those filters can be succesfully extracted and used (for example by the authkey module)

[GEOS-9355] implemented support to use params-extractor filter as a standard servlet filter, to intercept the security filters chain

---

src/extension/mongodb/src/main/java/org/geoserver/data/GeoserverSchemaDirecotry.java
src/extension/mongodb/src/main/resources/applicationContext.xml

-makes use of GEOT-6394
https://osgeo-org.atlassian.net/browse/GEOT-6394
Opened as draft, because it depends on Geotools PR becaue it has pre-requisites PR at https://github.com/geotools/geotools/pull/2593

[GEOS-9364] mongodb http(s) and zip file support for schema support

---

src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureTest.java

Reverts geoserver/geoserver#3826
Depends on jars from https://github.com/geotools/geotools/pull/2610 being available

Revert "Disable failing tests, see https://osgeo-org.atlassian.net/browse/GEOS-9367"

---

src/wcs2_0/src/test/java/org/geoserver/wcs2_0/xml/ScalingExtentionTest.java

Adding some debug information to figure out the random build failures on the build servers (both jenkins and travis)

---

doc/en/developer/source/quickstart/eclipse_m2.rst

Correct spelling mistakes

---

doc/en/user/source/tutorials/freemarker.rst
src/wms/src/main/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormat.java
src/wms/src/test/java/org/geoserver/wms/featureinfo/HTMLFeatureInfoOutputFormatTest.java
src/wms/src/test/resources/org/geoserver/wms/featureinfo/test_static_content.ftl

[GEOS-9361] Add Math support on freemarker template

---

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/MappingJackson2HttpMessageConverter.java
src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/MappingJackson2YAMLMessageConverter.java
src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/api/OGCApiTestSupport.java
src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/api/features/CollectionTest.java
src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/api/images/STACItemFeaturesResponse.java
src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/api/images/CollectionsTest.java
src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/api/images/ImageTest.java
src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/api/images/LandingPageTest.java
src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/api/styles/CollectionCallbackIntegrationTest.java
src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/api/styles/StyleMetadataTest.java
src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/api/styles/StyleThumbnailTest.java
src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/api/styles/StylesTest.java
src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/CollectionTest.java
src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/TileDescriptionTest.java

Usual PR to check build before merge. Work in OGC community module API.

STAC collection links

---

doc/en/user/source/data/database/sqlview.rst

Spelling & grammar

---

src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/api/images/ImageListenerSupport.java
src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/api/images/ImagesService.java
src/rest/src/main/java/org/geoserver/rest/util/RESTUtils.java
src/web/app/pom.xml
src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java

Fixing tiles truncation when images are removed from images service

---

src/gwc/src/main/java/org/geoserver/gwc/ConfigurableBlobStore.java
src/gwc/src/test/java/org/geoserver/gwc/ConfigurableBlobStoreTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-9382

GeoServer fails to truncate tiles caches with parameters

---

src/web/core/src/main/java/org/geoserver/web/data/resource/BasicResourceConfig.java

-for native SRS detection native boundig calculation
is not used anymore
https://osgeo-org.atlassian.net/browse/GEOS-9390
Actual native SRS will be determined using empty FeatureSource instead of calculating Native bounds from catalog builder. …

[GEOS-9390] un-necessary bound calculation bug fix

---

doc/en/api/1.0.0/roles.yaml
src/restconfig/src/main/java/org/geoserver/rest/security/RolesRestController.java
src/restconfig/src/test/java/org/geoserver/rest/security/UserRoleRestControllerTest.java

See https://osgeo-org.atlassian.net/browse/GEOS-9345
Adds endpoints to add  roles to groups should be added to match the existing endpoint for users.
The docs for the security/roles endpoints had a number of omissions and errors, so I've also fixed those while adding this new endpoint to the docs. 
Submitting the PR does not require you to check all items, but by the time …

[GEOS-9345] Add group endooints to security/roles REST controller

---

doc/en/user/source/geowebcache/webadmin/defaults.rst

Spelling corrections

---

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/AbstractLandingPageDocument.java
src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/CollectionExtents.java
src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/Link.java
src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/api/features/CollectionDocument.java
src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/api/features/FeatureService.java
src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/api/features/FeaturesLandingPage.java
src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/api/features/collection.ftl
src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/api/features/collection_include.ftl
src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/api/features/landingPage.ftl
src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/api/features/CollectionTest.java
src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/api/features/CollectionsTest.java
src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/api/features/ConformanceTest.java
src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/api/features/LandingPageTest.java
src/community/ogcapi/ogcapi-images/src/main/resources/org/geoserver/api/images/collection.ftl
src/community/ogcapi/ogcapi-images/src/main/resources/org/geoserver/api/images/collections.ftl
src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/api/images/CollectionTest.java
src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/api/images/LandingPageTest.java
src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/api/styles/LandingPageTest.java
src/community/ogcapi/ogcapi-tiles/src/main/resources/org/geoserver/api/tiles/collection.ftl
src/community/ogcapi/ogcapi-tiles/src/main/resources/org/geoserver/api/tiles/collections.ftl
src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/CollectionTest.java
src/community/ogcapi/ogcapi-tiles/src/test/java/org/geoserver/api/tiles/LandingPageTest.java

Trying to get in the most important changes in the Features API (other API needs similar updates, only extent changes affects all of them in this PR)

Updating OGC Features to version 1.0 of the spec

---

doc/en/user/source/extensions/monitoring/audit.rst
doc/en/user/source/extensions/monitoring/reference.rst
src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorFilter.java
src/extension/monitor/core/src/main/java/org/geoserver/monitor/RequestData.java
src/extension/monitor/core/src/main/resources/org/geoserver/monitor/auditlog/content.ftl
src/extension/monitor/core/src/test/java/org/geoserver/monitor/MonitorFilterTest.java
src/wms/src/main/java/org/geoserver/wms/RasterCleaner.java
src/wms/src/main/java/org/geoserver/wms/map/RenderTimeStatistics.java
src/wms/src/main/java/org/geoserver/wms/map/RenderedImageMapOutputFormat.java
src/wms/src/main/java/org/geoserver/wms/map/RenderedImageMapResponse.java
src/wms/src/main/java/org/geoserver/wms/map/RenderedImageTimeDecorator.java
src/wms/src/test/java/org/geoserver/wms/map/GetMapIntegrationTest.java
src/wms/src/test/java/org/geoserver/wms/map/RenderTimeStatisticsTest.java
src/wms/src/test/java/org/geoserver/wms/map/RenderedImageMapOutputFormatTest.java
src/wms/src/test/java/org/geoserver/wms/map/TinyRasterBoundingBoxTest.java

[GEOS-9360] Ability to log processing time per layer

---

src/platform/pom.xml
src/platform/src/main/java/org/geoserver/platform/resource/FileSystemResourceStore.java
src/platform/src/main/java/org/geoserver/platform/resource/FileSystemWatcher.java
src/platform/src/main/java/org/geoserver/platform/resource/ResourceNotification.java
src/platform/src/test/java/org/geoserver/platform/resource/FileSystemResourceStoreTest.java
src/platform/src/test/java/org/geoserver/platform/resource/FileSystemResourceTheoryTest.java
src/pom.xml

[Backport 2.15.x] [GEOS-9191] FileSystemWatcher: 100% CPU usage while idle running on a large data directory

---

src/platform/pom.xml
src/platform/src/main/java/org/geoserver/platform/resource/FileSystemResourceStore.java
src/platform/src/main/java/org/geoserver/platform/resource/FileSystemWatcher.java
src/platform/src/main/java/org/geoserver/platform/resource/ResourceNotification.java
src/platform/src/test/java/org/geoserver/platform/resource/FileSystemResourceStoreTest.java
src/platform/src/test/java/org/geoserver/platform/resource/FileSystemResourceTheoryTest.java
src/pom.xml

Reverts geoserver/geoserver#3899
See: "[Geoserver-devel] Getting NPE at FileSystemWatcher" on the devel list

Revert "[Backport 2.15.x] [GEOS-9191] FileSystemWatcher: 100% CPU usage while idle running on a large data directory"

---

src/platform/pom.xml
src/platform/src/main/java/org/geoserver/platform/resource/FileSystemResourceStore.java
src/platform/src/main/java/org/geoserver/platform/resource/FileSystemWatcher.java
src/platform/src/main/java/org/geoserver/platform/resource/ResourceNotification.java
src/platform/src/test/java/org/geoserver/platform/resource/FileSystemResourceStoreTest.java
src/platform/src/test/java/org/geoserver/platform/resource/FileSystemResourceTheoryTest.java
src/pom.xml

Reverts geoserver/geoserver#3860
See: "[Geoserver-devel] Getting NPE at FileSystemWatcher" on the devel list

Revert "[GEOS-9191] FileSystemWatcher: 100% CPU usage while idle running on a large data directory"

---

src/platform/pom.xml
src/platform/src/main/java/org/geoserver/platform/resource/FileSystemResourceStore.java
src/platform/src/main/java/org/geoserver/platform/resource/FileSystemWatcher.java
src/platform/src/main/java/org/geoserver/platform/resource/ResourceNotification.java
src/platform/src/test/java/org/geoserver/platform/resource/FileSystemResourceStoreTest.java
src/platform/src/test/java/org/geoserver/platform/resource/FileSystemResourceTheoryTest.java
src/pom.xml

Reverts geoserver/geoserver#3896
See: "[Geoserver-devel] Getting NPE at FileSystemWatcher" on the devel list

Revert "[Backport 2.16.x] [GEOS-9191] FileSystemWatcher: 100% CPU usage while idle running on a large data directory"

---

doc/en/developer/source/eclipse-guide/index.rst

As per line 88 in src/web/app/src/test/java/org/geoserver/web/Start.java:
https.setPort(8443);

Fix SSL port 8843 -> 8443

---

doc/en/user/source/data/database/primarykey.rst

Enhance understanding, hopefully

---

data/app-schema-tutorial/styles/raster.sld
data/citensg-1.0/styles/default_line.sld
data/citensg-1.0/styles/default_point.sld
data/citensg-1.0/styles/default_polygon.sld
data/citensg-1.0/styles/default_raster.sld
data/citensg-1.0/styles/raster_with_scales.sld
data/citewcs-1.0/styles/raster.sld
data/citewcs-1.1/styles/default_line.sld
data/citewcs-1.1/styles/default_point.sld
data/citewcs-1.1/styles/default_polygon.sld
data/citewcs-1.1/styles/raster.sld
data/citewfs-2.0/styles/default_line.sld
data/citewfs-2.0/styles/default_point.sld
data/citewfs-2.0/styles/default_polygon.sld
data/citewfs-2.0/styles/default_raster.sld
data/citewms-1.1/styles/normal.sld
data/citewms-1.3/styles/default_line.sld
data/citewms-1.3/styles/default_point.sld
data/citewms-1.3/styles/default_raster.sld
data/release/styles/default_line2.sld
src/kml/src/test/resources/org/geoserver/kml/bridge.sld
src/kml/src/test/resources/org/geoserver/kml/bridgesubdir.sld
src/kml/src/test/resources/org/geoserver/kml/notthere.sld
src/main/src/main/java/org/geoserver/config/default_line.sld
src/main/src/main/java/org/geoserver/config/default_point.sld
src/main/src/main/java/org/geoserver/config/default_polygon.sld
src/main/src/main/java/org/geoserver/config/default_raster.sld
src/web/wms/src/test/java/org/geoserver/wms/web/data/default_point.sld
src/wms/src/test/resources/org/geoserver/wms/wms_1_1_1/raster.sld
src/wms/src/test/resources/org/geoserver/wms/wms_1_1_1/rasterScales.sld

-replaced word 'boring' with 'simple'
-improved description on styles inside code and sample data directories

backport GEOS-9409 to 2.16.x

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/Gsml30WfsTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NamespacesWfsTest.java
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NestedElementsFilteringTest.java
src/extension/app-schema/app-schema-test/src/test/resources/test-data/stations/nestedElements/persons.xml
src/wfs/src/main/java/org/geoserver/wfs/xml/FeatureTypeSchemaBuilder.java
src/wfs/src/main/java/org/geoserver/wfs/xml/GML3OutputFormat.java
src/wfs/src/main/java/org/geoserver/wfs/xml/WFSXmlUtils.java

App-Schema WFS GetFeature GML 3.1 and 3.2 reponses include namespaces from all workspaces on isolated workspace (virtual service) request.  This PR fixes this issue.
Requires:
https://github.com/geotools/geotools/pull/2674
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-9388 …

[GEOS-9388] App-Schema WFS GetFeature includes namespaces for all workspaces on isolated workspace

---

doc/en/user/source/community/importer-jdbc/index.rst

Fix a typo (only one table is created), and phrasing.

Importer JDBC storage small doc change

---

src/extension/importer/rest/src/test/java/org/geoserver/importer/rest/ImporterIntegrationTest.java

- [] New unit tests have been added covering the changes

[GEOS-9432] remove excess new line from test data

---

src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java

JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9420
subtle memory leak fix in `GeofenceAccessManager `for inner class `LayersParser`

[GEOS-9420] GeoFenceAccessManager leaks HTTP clients #413

---

doc/en/user/source/services/wfs/outputformats.rst

Spelling fixes

---

src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java

backport of https://github.com/geoserver/geoserver/pull/3931

[ 2.15.x Backport][GEOS-9420] GeoFenceAccessManager leaks HTTP clients #413

---

src/extension/mongodb/src/main/java/org/geoserver/data/GeoserverSchemaDirecotry.java
src/extension/mongodb/src/main/resources/applicationContext.xml

-makes use of GEOT-6394
https://osgeo-org.atlassian.net/browse/GEOT-6394

[2.16.x backport][GEOS-9364] mongodb http(s) and zip file support for schema support

---

src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/api/features/CollectionDocument.java
src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/api/features/FeatureService.java
src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/api/features/QueryablesDocument.java
src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/api/features/collection.ftl
src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/api/features/collection_include.ftl
src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/api/features/filter-capabilities.ftl
src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/api/features/queryables.ftl
src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/api/features/CollectionTest.java

OGC API Features Queryables HTML support

---

src/pom.xml

Updating ErrorProne to 2.3.4

---

src/release/ext-authkey.xml

added accessors-smart-1.1.jar to packaging which contains the missing interface `net.minidev.asm.FieldFilter` reported at JIRA https://osgeo-org.atlassian.net/browse/GEOS-9428
`accessors-smart-1.1.jar` is sub-dependency of `json-smart-2.2.0.jar`
Submitting the PR does not require you to check all …

[GEOS-9428] Authkey role service filters broken on 2.16+

---

src/extension/app-schema/app-schema-mongo-test/src/test/java/org/geoserver/test/onlineTest/ComplexMongoDBSupport.java
src/extension/app-schema/app-schema-mongo-test/src/test/java/org/geoserver/test/onlineTest/ComplexMongoDBTest.java
src/extension/app-schema/app-schema-mongo-test/src/test/resources/data/stations3.json

Integration Test involving app-schema MongoDB datasource with empty list on MongoDB collections.
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-9430

[2.16.x backport][GEOS-9430] Integration Test for empty lists on app-schema MongoDB

---

doc/en/user/source/extensions/monitoring/configuration.rst
src/extension/monitor/core/src/main/java/org/geoserver/monitor/GeoIPPostProcessor.java
src/extension/monitor/core/src/main/java/org/geoserver/monitor/LayerNameNormalizer.java
src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorConfig.java
src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorFilter.java
src/extension/monitor/core/src/main/java/org/geoserver/monitor/RequestPostProcessor.java
src/extension/monitor/core/src/main/java/org/geoserver/monitor/ReverseDNSPostProcessor.java
src/extension/monitor/core/src/main/resources/org/geoserver/monitor/monitor.properties
src/extension/monitor/core/src/test/java/org/geoserver/monitor/MonitorFilterTest.java

JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9436
-added new configuration option ignorePostProcessors
-added unit test
-updated docs
new property in `monitor.properties`
`ignorePostProcessors=reverseDNS`
Submitting the PR does not require you to check all items, but by the time it gets …

[GEOS-9436]Monitor extension:Ignore Post processors

---

src/web/wms/src/main/java/org/geoserver/wms/web/publish/WMSLayerConfig.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/publish/WMSLayerConfigTest.java

JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9437
-bug fixed
-updated unit test to validate remote style counts

[GEOS-9437] Remote styles list duplicating in cascaded WMS UI

---

src/web/wms/src/main/java/org/geoserver/wms/web/publish/WMSLayerConfig.html
src/web/wms/src/test/java/org/geoserver/wms/web/data/publish/WMSLayerConfigTest.java

JIRA  : https://osgeo-org.atlassian.net/browse/GEOS-9449
cascaded wms layers
-subtle UI fix in WMSLayerConfig.html

[GEOS-9449] Min/Max Scale denominator UI label shold not show for non cascaded wms layers

---

src/release/ext-authkey.xml

backport of https://github.com/geoserver/geoserver/pull/3937
JIRA https://osgeo-org.atlassian.net/browse/GEOS-9428

[2.16.x backport][GEOS-9428] Authkey role service filters broken on 2.16+

---

src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java

backport of https://github.com/geoserver/geoserver/pull/3932
JIRA: https://osgeo-org.atlassian.net/browse/GEOS-9431

[2.15.x backport][GEOS-9431] Integrated GWC does not kick in when making request not qualified by workspace

---

src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java

backport of
https://github.com/geoserver/geoserver/pull/3932
JIRA: https://osgeo-org.atlassian.net/browse/GEOS-9431

[2.16.x backport][GEOS-9431] Integrated GWC does not kick in when making request not qualified by workspace 

---

src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/AbstractLandingPageDocument.java
src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/GeoServerOpenAPI.java
src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/MappingJackson2HttpMessageConverter.java
src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/OpenAPIBuilder.java
src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/api/OpenAPIMessageConverter.java
src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/api/features/FeatureService.java
src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/api/features/openapi.yaml
src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/api/features/LandingPageTest.java
src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/api/images/ImagesService.java
src/community/ogcapi/ogcapi-styles/src/main/java/org/geoserver/api/styles/StylesService.java
src/community/ogcapi/ogcapi-tiles/src/main/java/org/geoserver/api/tiles/TilesService.java

Couple of fixes to improve compatibility in the Features API test suite. Other failures are (reported) bugs in the tests themselves. Checking that everything is fine build wise before merging.

OGC API CITE fixes

---

src/extension/sldService/src/main/java/org/geoserver/sldservice/rest/RasterizerController.java
src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/RasterizerTest.java

[GEOS-9444]: SLDService rasterize service includes a wrong FeatureTypeName in produced SLD (backport to 2.16.x)

---

src/extension/sldService/src/main/java/org/geoserver/sldservice/rest/RasterizerController.java
src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/RasterizerTest.java

[GEOS-9444]: SLDService rasterize service includes a wrong FeatureTypeName in produced SLD (backport to 2.15.x)

---

.github/workflows/macos.yml
.github/workflows/windows.yml
.travis.yml
src/platform/src/test/java/org/geoserver/platform/resource/FileSystemResourceTheoryTest.java

Windows and OSX build for GeoServer, from GitHub.

GitHub Windows and OSX workflows

---

src/extension/sqlserver/pom.xml
src/release/ext-sqlserver.xml

[GEOS-9460] Upgrade SQL Server packaging to use open source JDBC driver

---

src/extension/importer/web/src/main/java/org/geoserver/importer/web/ImporterConfigPage.java
src/extension/importer/web/src/test/java/org/geoserver/importer/web/ImporterConfigPageTest.java

backport of https://github.com/geoserver/geoserver/pull/3960

[Backport 2.16.x][GEOS-9438] Serializer errors when using the Importer GUI

---

src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/api/features/CollectionDocument.java
src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/api/features/CollectionsDocument.java
src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/api/features/FeatureResponseMessageConverter.java
src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/api/features/FeatureService.java
src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/api/features/openapi.yaml
src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/api/features/ApiTest.java
src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/api/features/CollectionTest.java
src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/api/features/CollectionsTest.java
src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/api/features/FeatureTest.java
src/wfs/src/main/java/org/geoserver/wfs/request/Query.java

OGC Features API CRS extension implementation (spec is a draft, mind)

---

src/main/src/main/java/org/geoserver/catalog/WMSLayerInfo.java
src/main/src/main/java/org/geoserver/catalog/impl/WMSLayerInfoImpl.java
src/main/src/main/java/org/geoserver/security/decorators/DecoratingWMSLayerInfo.java
src/web/wms/src/main/java/org/geoserver/wms/web/publish/WMSLayerConfig.html
src/web/wms/src/main/java/org/geoserver/wms/web/publish/WMSLayerConfig.java
src/web/wms/src/main/resources/GeoServerApplication.properties
src/web/wms/src/test/java/org/geoserver/wms/web/data/publish/WMSLayerConfigTest.java
src/wms/src/main/java/org/geoserver/wms/GetMap.java
src/wms/src/test/java/org/geoserver/wms/WMSCascadeTestSupport.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/WMSCascadeTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/WMSCascadeTest.java
src/wms/src/test/resources/org/geoserver/wms/caps111.xml
src/wms/src/test/resources/org/geoserver/wms/caps130.xml

backport of https://github.com/geoserver/geoserver/pull/3856

[Backport 2.16.x][GEOS-9380] Ignore remote WMS remote requests outside advertised bounds

---

src/community/flatgeobuf/pom.xml

See https://github.com/bjornharrtell/flatgeobuf/pull/35 for details on the improvements that this upgrade brings.

Upgrade flatgeobuf

---

doc/en/api/1.0.0/wmslayers.yaml

JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9461
update \doc\en\api\1.0.0\wmtslayers.yaml
-add remote styles and format
-add min/max scale denominators
-add respect remote bounds settings

[GEOS-9461] Update YAML docs for new cascaded WMS controls

---

.travis.yml
doc/en/api/1.0.0/wmslayers.yaml

backport of https://github.com/geoserver/geoserver/pull/3986

[Backport 2.16.x][GEOS-9461] Update YAML docs for new cascaded WMS controls (#3986)

---

src/main/src/main/java/org/geoserver/catalog/WMSLayerInfo.java
src/main/src/main/java/org/geoserver/catalog/impl/WMSLayerInfoImpl.java
src/main/src/main/java/org/geoserver/security/decorators/DecoratingWMSLayerInfo.java
src/web/wms/src/main/java/org/geoserver/wms/web/publish/WMSLayerConfig.html
src/web/wms/src/main/java/org/geoserver/wms/web/publish/WMSLayerConfig.java
src/web/wms/src/main/resources/GeoServerApplication.properties
src/web/wms/src/test/java/org/geoserver/wms/web/data/publish/WMSLayerConfigTest.java
src/wms/src/main/java/org/geoserver/wms/GetMap.java
src/wms/src/test/java/org/geoserver/wms/WMSCascadeTestSupport.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/WMSCascadeTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/WMSCascadeTest.java

backport of 
https://github.com/geoserver/geoserver/pull/3870
https://github.com/geoserver/geoserver/pull/3887
https://github.com/geoserver/geoserver/pull/3962

[Backport 2.16.x][GEOS-9387] min/max scale for cascaded wms layers

---

src/wfs/src/main/java/org/geoserver/wfs/WFSWorkspaceQualifier.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureJoinTest.java

Improve org.geoserver.wfs.WFSWorkspaceQualifier to resolve
typenames on the local workspace when a WFS request with
multiple elements in the 'typeNames' (not 'typeName') parameter
are specified.
checkOriginallyUnqualified() was only looking at TYPENAME (WFS 1.0),
and not TYPENAMES (2.0).
Since by the time TypeNameKvpParser resolves the requested type names,
the LocalWorkspace is not set, it may either resolve to an unqualified
QName, or one on any other workspace than the requested one (due to the
lenient resolution in TypeNameKvpParser.parseToken() calling
Catalog.getFeatureTypeByName(String), which in turns returns a feature
type in the default workspace or any other workspace if none is found).
This lead to either trying to use the wrong FeatureType or not finding
it at all.
Also …

[GEOS-9458] Fix WFS 2.0 join queries with unqualified typenames

---

src/wfs/src/main/java/org/geoserver/wfs/WFSWorkspaceQualifier.java
src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureJoinTest.java

Backport of #3971
Improve org.geoserver.wfs.WFSWorkspaceQualifier to resolve
typenames on the local workspace when a WFS request with
multiple elements in the 'typeNames' (not 'typeName') parameter
are specified.
checkOriginallyUnqualified() was only looking at TYPENAME (WFS 1.0),
and not TYPENAMES (2.0).
Since by the time TypeNameKvpParser resolves the requested type names,
the LocalWorkspace is not set, it may either resolve to an unqualified
QName, or one on any other workspace than the requested one (due to the
lenient resolution in TypeNameKvpParser.parseToken() calling
Catalog.getFeatureTypeByName(String), which in turns returns a feature
type in the default workspace or any other workspace if none is found).
This lead to either trying to use the wrong FeatureType or not finding
it …

[backport-2.16.x] [GEOS-9458] Fix WFS 2.0 join queries with unqualified typenames

---

.travis.yml

This should, hopefully, cure the "build failed, no output for 10 minutes" issue.

Reinstate download of latest maven version, usage of takari smart builder

---

.travis.yml

@dromagnoli this is hopefully the change you need for the "10 minutes without output" build issues. Can you keep an eye on it, and if it goes well, merge and then rebase your PRs?

Reinstate download of latest maven version and takari smart builder

---

src/main/src/main/java/org/geoserver/catalog/impl/WMSLayerInfoImpl.java
src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
src/main/src/test/java/org/geoserver/config/util/XStreamPersisterTest.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/publish/WMSLayerConfigTest.java

JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9479

[GEOS-9479] Add Backward compatibility on new Cascaded WMS settings

---

src/web/core/src/main/java/org/geoserver/web/publish/PublishedConfigurationPage.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/CachedLayersPageTest.java

backport of https://github.com/geoserver/geoserver/pull/3791

[Backport 2.16.x][GEOS-8940]Tile Layers page layer names bring to the "Publishing" tab by default

---

doc/en/user/source/styling/css/properties.rst
src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/LocalResolveTest.java
src/web/core/src/main/java/org/geoserver/web/wicket/js/codemirror/js/css.js

The action happened in GeoTools, here adding only docs and extending style editor autocomplete support.

Add docs and autocomplete support for recently added CSS properties

---

doc/en/user/source/extensions/monitoring/configuration.rst
src/extension/monitor/core/src/main/java/org/geoserver/monitor/GeoIPPostProcessor.java
src/extension/monitor/core/src/main/java/org/geoserver/monitor/LayerNameNormalizer.java
src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorConfig.java
src/extension/monitor/core/src/main/java/org/geoserver/monitor/MonitorFilter.java
src/extension/monitor/core/src/main/java/org/geoserver/monitor/RequestPostProcessor.java
src/extension/monitor/core/src/main/java/org/geoserver/monitor/ReverseDNSPostProcessor.java
src/extension/monitor/core/src/main/resources/org/geoserver/monitor/monitor.properties
src/extension/monitor/core/src/test/java/org/geoserver/monitor/MonitorFilterTest.java

backport of https://github.com/geoserver/geoserver/pull/3943

[Backport 2.16.x][GEOS-9436]Monitor extension:Ignore Post processors

---

src/wcs1_1/pom.xml
src/web/app/pom.xml

while here also upgrade this plugin to the current release and replace some tabs with spaces

fix a Maven warning about a missing plugin version

---

src/extension/sldService/src/main/java/org/geoserver/sldservice/rest/ClassifierController.java
src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/impl/CustomColorRamp.java
src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/ClassifierTest.java

See: https://osgeo-org.atlassian.net/browse/GEOS-9500
Some of colors in the custom color ramp end up being ignored and replaced with black instead

[GEOS-9500] SLDService won't respect custom color ramps when having less than 3 classes

---

src/extension/app-schema/app-schema-test/src/test/java/org/geoserver/test/NormalizedMultiValuesTest.java

This PR includes a small fix on AppSchema multvalue JSON testing due to data setup changed on other recent fix PR.

[GEOS-9493] Fix App-Schema Multivalue JSON testing due to data setup changed

---

src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/gwc/src/main/java/org/geoserver/gwc/layer/CatalogConfiguration.java
src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/GWCIconFactory.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayerProvider.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayersPage.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/NewCachedLayerPage.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/UnconfiguredCachedLayersProvider.java

Replaces  https://github.com/geoserver/geoserver/pull/3889 as there were conflicts and solving them was not the cleanest action... want to keep the other alive for reference.

GEOS-9397] Cached layers page may take minutes to show up (when backing stores are not responsive) - delayed icon computation

---

doc/en/api/1.0.0/wmtslayers.yaml

[GEOS-9499] Update documentation REST WMTS

---

src/web/core/src/main/java/org/geoserver/web/publish/PublishedConfigurationPage.java
src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/CachedLayersPageTest.java

backport of https://github.com/geoserver/geoserver/pull/3791

[Backport 2.15.x][GEOS-8940]Tile Layers page layer names bring to the "Publishing" tab by default

---

src/wfs/src/main/java/org/geoserver/wfs/StoredQueryProvider.java

Fix spelling mistakes in exceptions/logs

---

src/community/notification/pom.xml

JIRA : https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-9453
current version in notification community module : 4.0.0,
Latest version on Maven central : 5.8.0 …

[GEOS-9453] Update GeoServer dependencies on RabbitMQ to 4.8.0 or newer

---

src/community/jms-cluster/activemqBroker/pom.xml
src/community/jms-cluster/jms-commons/pom.xml
src/community/jms-cluster/jms-geoserver/pom.xml

JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9454
current version in jms-cluster\activemqBroker community module : 5.9.0
Latest version on Maven central : 5.15.11 …

[GEOS-9454] Update GeoServer dependencies on ActiveMQ from 5.9 to 5.15.9 or newer

---

src/pom.xml

- Bump Spring Framework dependencies from 5.1.1.RELEASE to 5.1.13.RELEASE, resolves CVE-2020-5398
- Bump Spring Security from 5.1.5.RELEASE to 5.1.8.RELEASE
see also:
- #3949
- https://osgeo-org.atlassian.net/browse/GEOS-9477

[GEOS-9477] Geoserver is flagged for CVE-2020-5398

---

src/pom.xml

GeoServer is flagged for CVE-2020-5398 - 2.16.x backport

---

src/pom.xml

[GEOS-9477] Geoserver is flagged for CVE-2020-5398 (original commit by Mark Prins) - 2.15.x backport

---

doc/en/user/source/styling/webadmin/index.rst
src/web/wms/src/main/java/org/geoserver/wms/web/data/ExternalGraphicPanel.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java
src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
src/wms/src/main/java/org/geoserver/wms/capabilities/CapabilityUtil.java
src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/LegendCapabilitiesTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/LegendCapabilitiesTest.java

JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9489
-UI page does not complain on URL and URI
-cap doc does not prefix external URL/URIs with base url
-legend urls are adverstised as get legend requests …

[GEOS-9489] Invalid <OnlineResource> for external legend graphics accessible in WMS capability document

---

src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/RulesBuilder.java
src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/ClassifierTest.java
src/extension/sldService/src/test/resources/org/geoserver/sldservice/rest/ClassificationLines.properties

[GEOS-9504] Avoid duplicated classes in SLDService output

---

src/web/wms/src/main/java/org/geoserver/wms/web/data/ExternalGraphicPanel.java
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java
src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
src/wms/src/main/java/org/geoserver/wms/capabilities/CapabilityUtil.java
src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/LegendCapabilitiesTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/LegendCapabilitiesTest.java

backport of https://github.com/geoserver/geoserver/pull/4033

[Backport 2.16.x ][GEOS-9489] Invalid <OnlineResource> for external legend graphics accessible in WMS capability document

---

doc/en/api/1.0.0/wmtslayers.yaml

[2.15.x][GEOS-9499] Update documentation REST WMTS

---

doc/en/api/1.0.0/wmtslayers.yaml

[2.16.x backport][GEOS-9499] Update documentation REST WMTS

---

src/main/src/main/java/org/geoserver/catalog/LayerGroupHelper.java
src/main/src/main/java/org/geoserver/catalog/impl/LayerInfoImpl.java
src/wms/src/test/java/org/geoserver/wms/WMSCascadeTestSupport.java
src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/WMSCascadeTest.java
src/wms/src/test/java/org/geoserver/wms/wms_1_3/WMSCascadeTest.java
src/wms/src/test/resources/org/geoserver/wms/caps111.xml
src/wms/src/test/resources/org/geoserver/wms/caps130.xml

JIRA: https://osgeo-org.atlassian.net/browse/GEOS-9498
- fixes in LayerGroupHelper to resolve correct remote style
for cascaded wms layer memeber layer of group
- added new unit tests
Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either …

[GEOS-9498] Add Backward compatibility on Layergroups with legacy Cascaded WMS Layers

---

doc/en/user/source/services/wms/get_legend_graphic/index.rst

spelling-mistakes-GetLegendGraphic

---

.github/PULL_REQUEST_TEMPLATE.md

Aligns GeoServer template with GeoTools one, see also:
https://github.com/geotools/geotools/pull/2809

Clarify the intended PR format, avoid or isolate unrelated changes

---

data/citewms-1.1/styles/basicPolygon.sld

[GEOS-9514] CITE WMS 1.1.1 Sample Datadir Style issue

---

src/community/notification/pom.xml

backport of https://github.com/geoserver/geoserver/pull/3965

[Backport 2.16.x][GEOS-9453] Update GeoServer dependencies on RabbitMQ to 4.8.0 or newer

---

src/community/jms-cluster/activemqBroker/pom.xml
src/community/jms-cluster/jms-commons/pom.xml
src/community/jms-cluster/jms-geoserver/pom.xml

backport of https://github.com/geoserver/geoserver/pull/3964

[Backport 2.16.x][GEOS-9454] Update GeoServer dependencies on ActiveMQ from 5.9 to 5.15.9 or newer

---

doc/en/api/1.0.0/usergroup.yaml

Add Basepath to usergroup rest Swagger

---

src/main/src/main/resources/schemas/sld/StyledLayerDescriptor.xsd
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java

JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9502
-updated
/gs-main/src/main/resources/schemas/sld/StyledLayerDescriptor.xsd
-added unit test

[GEOS-9502] <VendorOption> in <LineSymbolizer> validation bug

---

src/pom.xml

See details at https://osgeo-org.atlassian.net/browse/GEOS-9515

[GEOS-9515] Authkey and CSS modules are not compatible with each other, ASM library overlap

---

src/pom.xml

[GEOS-9515] Authkey and CSS modules are not compatible with each other, ASM library overlap, 2.16.x backport

---

src/main/src/main/resources/schemas/sld/StyledLayerDescriptor.xsd
src/web/wms/src/test/java/org/geoserver/wms/web/data/StyleEditPageTest.java

backport : https://github.com/geoserver/geoserver/pull/4059

[GEOS-9502] <VendorOption> in <LineSymbolizer> validation bug (#4059)

---

doc/en/api/1.0.0/styles.yaml

Fix typo in REST API styles docs

---

src/gwc/src/main/java/org/geoserver/gwc/GWC.java
src/gwc/src/main/java/org/geoserver/gwc/layer/CatalogConfiguration.java
src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/GWCIconFactory.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayerProvider.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayersPage.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/NewCachedLayerPage.java
src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/UnconfiguredCachedLayersProvider.java

Backport of https://github.com/geoserver/geoserver/pull/4038

GEOS-9397] Cached layers page may take minutes to show up (when backing stores are not responsive) - delayed icon computation - 2.16.x backport

---

src/extension/sldService/src/main/java/org/geoserver/sldservice/rest/ClassifierController.java
src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/RulesBuilder.java
src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/impl/CustomColorRamp.java
src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/ClassifierTest.java
src/extension/sldService/src/test/resources/org/geoserver/sldservice/rest/ClassificationLines.properties

SLDService: backport of GEOS-9500 and GEOS-9504 on 2.15.x

---

doc/en/user/source/production/container.rst

Edited the Marlin instructions for clarity and added instructions for checking which renderer is in use.

Revise the instructions for enabling/updating Marlin.

---

src/extension/app-schema/app-schema-indexes-test/src/test/java/org/geoserver/test/onlineTest/StationsMappingsSetup.java

Format check failing on app-schema-indexes online test

---

src/release/LICENSE.txt
src/release/ext-mbstyle.xml
src/release/ext-web-resource.xml

Fixing nightly build after some relative path license references did not work out.

Fix nightly build

---

src/community/geogig/pom.xml
src/community/geomesa/pom.xml
src/community/taskmanager/core/bin/pom.xml
src/community/wps-sextante/pom.xml
src/maven/pom.xml
src/pom.xml

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …

[SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/RulesBuilder.java
src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/ClassifierTest.java
src/extension/sldService/src/test/resources/org/geoserver/sldservice/rest/ClassificationPoints2.properties

[GEOS-9522] SldService generate overlapping rules

---

src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/RulesBuilder.java
src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/ClassifierTest.java
src/extension/sldService/src/test/resources/org/geoserver/sldservice/rest/ClassificationPoints2.properties

[GEOS-9522] SldService generate overlapping rules - 2.15.x backport

---

src/extension/sldService/src/main/java/org/geoserver/sldservice/utils/classifier/RulesBuilder.java
src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/ClassifierTest.java
src/extension/sldService/src/test/resources/org/geoserver/sldservice/rest/ClassificationPoints2.properties

[GEOS-9522] SldService generate overlapping rules - 2.16.x backport

---

doc/en/user/source/production/container.rst

Revise the instructions for enabling/updating Marlin.  [Backport to 2.16.x]

---

doc/en/user/source/production/container.rst

Revise the instructions for enabling/updating Marlin.  [Backport to 2.15.x]

---

src/community/geogig/pom.xml
src/pom.xml

I updated the HTTPComponents versions and built + tested GeoServer to ensure it ran correctly. We also built a container and pushed it up to Amazon for scanning, and the scans came back clean.

Updated the HTTPComponents version

---

doc/en/developer/source/tools.rst
doc/en/user/source/installation/index.rst
doc/en/user/source/installation/linux.rst
doc/en/user/source/installation/osx_binary.rst
doc/en/user/source/installation/war.rst
doc/en/user/source/installation/win_binary.rst
doc/en/user/source/production/java.rst
src/README.txt
src/release/RUNNING.txt
src/release/developer_README.txt
src/release/installer/win/GeoServerEXE.nsi

Remove recommendation of Oracle JDK in installation and build instructions

[GEOS-9527] Remove recommendation of OracleJDK from docs and readme files

---

src/community/geogig/pom.xml
src/pom.xml

Backporting to 2.16.x per @aaime
I updated the HTTPComponents versions and built + tested GeoServer to ensure it ran correctly. We also built a container and pushed it up to Amazon for scanning, and the scans came back clean. Worked from a clean back to correct the previous PR.
Submitting the PR does not require you to check all items, but by the time it gets merged, they …

backporting the httpcomponents update to 2.16.x

---

src/release/ext-ogr-wps.xml

Follow up to https://github.com/geoserver/geoserver/pull/4111

[GEOS-9527] include readme in ogr-wps extension

---

src/community/release/ext-jms-cluster.xml

Backport to 2.16.x of assembly instructions fix.

Upgraded ActiveMQ requires commons-pool2

---

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/tasklet/CatalogBackupRestoreTasklet.java
src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java
src/community/backup-restore/rest/src/main/java/org/geoserver/backuprestore/rest/BackupController.java
src/community/backup-restore/rest/src/main/java/org/geoserver/backuprestore/rest/RestoreController.java

[GEOS-9537] Restore plugin is not able to correctly restore styles anymore

---

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/tasklet/CatalogBackupRestoreTasklet.java
src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java
src/community/backup-restore/rest/src/main/java/org/geoserver/backuprestore/rest/BackupController.java
src/community/backup-restore/rest/src/main/java/org/geoserver/backuprestore/rest/RestoreController.java

(cherry picked from commit 7580eaa5d20183aaa567fb3a93ae68a9b0796374)

[Backport to 2.16.x][GEOS-9537][GEOS-9530] Restore plugin is not able to correctly restore styles anymore

---

src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/tasklet/CatalogBackupRestoreTasklet.java
src/community/backup-restore/core/src/test/java/org/geoserver/backuprestore/BackupTest.java
src/community/backup-restore/rest/src/main/java/org/geoserver/backuprestore/rest/BackupController.java
src/community/backup-restore/rest/src/main/java/org/geoserver/backuprestore/rest/RestoreController.java

(cherry picked from commit 7580eaa5d20183aaa567fb3a93ae68a9b0796374)

[Backport to 2.15.x][GEOS-9537][GEOS-9530] Restore plugin is not able to correctly restore styles anymore

---

src/pom.xml

GeoTools and GeoWebCache version numbers have not been updated to the new master branches

Update the dependency number versions for geotools and geowebcache

---

doc/en/api/1.0.0/coveragestores.yaml
doc/en/api/1.0.0/datastores.yaml
doc/en/api/1.0.0/featuretypes.yaml
doc/en/api/1.0.0/fonts.yaml
doc/en/api/1.0.0/gwcblobstores.yaml
doc/en/api/1.0.0/gwcbounds.yaml
doc/en/api/1.0.0/gwcdiskquota.yaml
doc/en/api/1.0.0/gwcfilterupdate.yaml
doc/en/api/1.0.0/gwcglobal.yaml
doc/en/api/1.0.0/gwcgridsets.yaml
doc/en/api/1.0.0/gwcindex.yaml
doc/en/api/1.0.0/gwclayers.yaml
doc/en/api/1.0.0/gwcmasstruncate.yaml
doc/en/api/1.0.0/gwcmemorycachestatistics.yaml
doc/en/api/1.0.0/gwcreload.yaml
doc/en/api/1.0.0/gwcseed.yaml
doc/en/api/1.0.0/importer.yaml
doc/en/api/1.0.0/importerData.yaml
doc/en/api/1.0.0/importerTasks.yaml
doc/en/api/1.0.0/importerTransforms.yaml
doc/en/api/1.0.0/layergroups.yaml

Fix for [GEOS-9543](https://osgeo-org.atlassian.net/browse/GEOS-9543). See also https://github.com/geoserver/geoserver/pull/4116

[GEOS-9543] Fix duplocated mapping keys in REST swagger docs

---

src/extension/css/src/test/java/org/geoserver/rest/catalog/CssStyleControllerTest.java
src/extension/css/src/test/resources/org/geoserver/rest/catalog/multilayer.css
src/extension/mbstyle/pom.xml
src/extension/mbstyle/src/test/java/org/geoserver/rest/catalog/MBStyleControllerTest.java
src/extension/mbstyle/src/test/resources/org/geoserver/rest/catalog/multilayer.json
src/rest/src/main/java/org/geoserver/rest/converters/StyleWriterConverter.java

See also: https://osgeo-org.atlassian.net/browse/GEOS-9544

[GEOS-9544] REST services fail to return the full style, if it's being converted, and the origin is multi-layer
